### ISSUE TITLE
Write guide on how to use a downloaded solc

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#1053]
Hardhat example showing how to do this: https://github.com/fvictorio/hardhat-examples/tree/master/custom-solc

Also, maybe it's better to just do #3294 instead.

**Comment by lilpolymath** [comment]
@fvictorio I would like to work on this but is there any reason why you think that #3294 is better despite the caveat there?

**Comment by fvictorio** [comment]
The workaround to use a downloaded solc is a bit involved; having built-in support to use a solc binary would be better. But adding that feature would need some design to be sure that whatever we do is backwards-compatible and  that it doesn't have weird edge cases.

**Comment by lilpolymath** [comment]
Oh alright, I agree with you. Do I work on the guide then pending the time the feature is implemented? I will take a look at seeing how the feature can be done.

**Comment by fvictorio** [comment]
Hey, sorry for not responding before.

I think we could have a guide under "other-guides" (that is, not shown in the sidebar) which basically explains [this](https://github.com/fvictorio/hardhat-examples/tree/master/custom-solc). Then we could add a link to it somewhere, perhaps in the ["Multiple solidity versions"](https://hardhat.org/hardhat-runner/docs/advanced/multiple-solidity-versions) guide.

**Comment by lilpolymath** [comment]
Got it. That is a reasonable approach. I will make a PR for it.

**Comment by lilpolymath** [comment]
@fvictorio here is the PR #4804. I added it as a tip in the ["Multiple solidity versions"](https://hardhat.org/hardhat-runner/docs/advanced/multiple-solidity-versions) guide. Let me know if that works.

**Comment by schaable** [comment]
Merged. Thanks @lilpolymath!
