### ISSUE TITLE
Feature Request: hardhat network on localhost integration with graph node

### ISSUE THREAD

**Issue by gitpusha** [NomicFoundation/hardhat#1066]
I am sure you have thought about this before.

It would be amazing to make hardhat network compatible with graph nodes so that one can test a dapp against hardhat network RPC forked from mainnet and a local graph node instance.

**Comment by dahifi** [comment]
You can, but there seem to be come issues with certain types of RPC calls. 

If you run the setup.sh file in TheGraph's docker folder, it should update your docker-compose file with your localhost IP:
```
environment:
      ethereum: 'mainnet:http://172.22.0.1:8545'
```
Run hardhat with `--hostname 0.0.0.0`, and your node instance should be able to connect it. 

IDK what issues you've been having, but I'm opening a ticket cause of a eth_call error that occurs when I try to set an entity field from a contract call.

**Comment by alcuadrado** [comment]
Can you create a repo to reproduce the problems you are having, @dahifi @gitpusha ? We are really interested in the graph working properly with Hardhat Network.

**Comment by dahifi** [comment]
@alcuadrado my issue was resolved in 2.0.4. Someone on the Graph Discord pointed out it was this PR: https://github.com/nomiclabs/hardhat/pull/948

**Comment by gitpusha** [comment]
> Can you create a repo to reproduce the problems you are having, @dahifi @gitpusha 

Tagging @hilmarx because he is working with the Graph in our team.

**Comment by alcuadrado** [comment]
I think this is ready. right?

**Comment by nazariyv** [comment]
> You can, but there seem to be come issues with certain types of RPC calls.
> 
> If you run the setup.sh file in TheGraph's docker folder, it should update your docker-compose file with your localhost IP:
> 
> ```
> environment:
>       ethereum: 'mainnet:http://172.22.0.1:8545'
> ```
> 
> Run hardhat with `--hostname 0.0.0.0`, and your node instance should be able to connect it.
> 
> IDK what issues you've been having, but I'm opening a ticket cause of a eth_call error that occurs when I try to set an entity field from a contract call.

thanks, this worked

**Comment by heri16** [comment]
Doesn't seem to work anymore with the latest master of the graph node.

**Comment by marcelomorgado** [comment]
Yes, the latest version isn't working.
As a workaround I'm using an older image: `graphprotocol/graph-node:9950bce`

**Comment by fvictorio** [comment]
@heri16 @marcelomorgado just to be clear: the latest version of graph-node doesn't work with the latest version of hardhat?

Could someone tell me what's the easiest way to reproduce this? (If someone can create a minimal repo that triggers the issue, it would be awesome)

**Comment by garythung** [comment]
I was able to get it to work with a normal Hardhat setup (node running with mainnet forked, default hostname to `127.0.0.1`) and with the original `graph-node:v0.24.0` `docker-compose.yml` untouched (i.e. `ethereum: 'mainnet:http://host.docker.internal:8545'`).

**Comment by jorions** [comment]
@garythung That did the trick for me. Using the current version of graph-node (`fraction` release https://github.com/graphprotocol/graph-node/commit/85726100b89b92bcbd90807ff5572073c1d75878) on Mac, the `docker-compose.yml` actually has the `ethereum` key already set to `ethereum: 'mainnet:http://host.docker.internal:8545'`, so hardhat seems to play nicely with it out of the box now. 

Thanks!

**Comment by Piquinikis** [comment]
Hi guys.

Someone can share an example about how it's needed to be configured `hardhat` and how to run the `graph-node`. I'm working around this for a while but I couldn't make runs it. 

Thanks :)

**Comment by kumikoda** [comment]
I was able to get a normal hardhat on `127.0.0.1` to work by changing the ethereum url to `mainnet:http://docker.for.mac.host.internal:8545`
see https://github.com/docker/for-mac/issues/2965#issuecomment-434504244

**Comment by fvictorio** [comment]
AFAIK Hardhat does work with the graph now? I haven't checked though, so if it doesn't, please comment here or open a new issue about this.
