### ISSUE TITLE
config.networks.hardhat.loggingEnabled = false is ignored by the node task

### ISSUE THREAD

**Issue by alcuadrado** [NomicFoundation/hardhat#1075]

**Comment by fvictorio** [comment]
This was fixed in #1100 or it's a different thing?

**Comment by alcuadrado** [comment]
I don't think so. I think we always enable the logging with an rpc call.

**Comment by sisco0** [comment]
Hello @alcuadrado I have made some change over the line in order to enable logging conditionally based on the `hardhatNetworkConfig.loggingEnabled` value. How should I test if this is the expected good behaviour? Is there any test that I could run?

**Comment by sisco0** [comment]
Please take care of the _Pull request_ attached to this issue in order to know if it fixes or not the behaviour.

**Comment by fvictorio** [comment]
The solution here is to expose the user config in the HRE. We should do that and then fix this. See comment: https://github.com/nomiclabs/hardhat/pull/1127#issuecomment-754134076

**Comment by ajb413** [comment]
I am trying to run a local instance of hardhat using a script. I am seeing lots of logs (like all the accounts that have the 10k ETH). I would prefer to hide all those logs when I boot up. Is this the same issue?

```bash
node myScript.js
```

```js
const hre = require('hardhat');

(async function () {
  hre.run('node');
  await hre.network.provider.send('hardhat_setLoggingEnabled', [ false ]);
})().catch(console.error);
```

The `setLoggingEnabled` request seems to turn off the logs, but not initially, I am still seeing logs before that request gets processed. I have also tried `hre.run('node', { loggingEnabled: false });` but that doesn't seem to work at all. I also have that set in my config file but it gets ignored. I just want to confirm this is the same issue. If it is not, is there a way for me to turn off the logs? Thank you.

**Comment by alcuadrado** [comment]
Yes, it's the same issue. As @fvictorio mentioned, in order to solve this we should modify the HRE to expose the pre-resolution user config. I guess that would make sense as long as it's readonly.

**Comment by alcuadrado** [comment]
This has been fixed.
