### ISSUE TITLE
Feature Request: stack traces for external verified contract dependencies

### ISSUE THREAD

**Issue by gitpusha** [NomicFoundation/hardhat#1077]
It would be amazing to have more stack trace support for contract dependencies that are not compiled in your hardhat project, but that you instantiate during e.g ` mainnet forking` tests and that are verified on Etherscan. 

As far as I understand hardhat needs to generate some build and debug files for a contract to be fully supported. 

If the source code and compile information is available from Etherscan maybe one way to circumvent this restriction is to have hardhat pull the source and compile info from Etherscan during runtime and compile the contracts and generate the needed build and debug files for them, to allow stack traces. 

Maybe one could let hardhat know it should do that for certain contract addresses.

A config like: 

```javascript
forking: {
     verifiedExternalContracts: [ "someAddress", "someOtherAddress" ] 
```

could let hardhat know what contract instances to go and try to pull info from Etherscan and compile locally for.

**Comment by miracle2k** [comment]
It would be nice if this could be supported not just for contract verified on Etherscan, but also contracts where I might have the source available locally, but is not part of my current hardhat project.

**Comment by fvictorio** [comment]
@miracle2k in that case you can just add those sources to your `contracts` directory and then they will show up, assuming that you are using the same solc version that it was used to deploy them.

**Comment by banshee** [comment]
> @miracle2k in that case you can just add those sources to your `contracts` directory and then they will show up, assuming that you are using the same solc version that it was used to deploy them.

That sounds extremely painful; lots of times there are many contracts pulled in via npm packages, and managing copying them around to a local contracts directory is unworkable.

**Comment by fvictorio** [comment]
Closing this in favor of #1217. It's not _exactly_ the same as this one, but I think the underlying need is the same.
