### ISSUE TITLE
EISDIR error when the artifacts directory is placed under sources

### ISSUE THREAD

**Issue by sebastinez** [NomicFoundation/hardhat#1093]
Hello nomiclabs,

I started with the migration from Buidler to Hardhat in one of my repositories. https://github.com/NRS-Soft/nuclearistrack on the "hardhat-migration" branch. with this commit https://github.com/NRS-Soft/nuclearistrack/commit/4bd9ada21f82e9de1dd25c6746e3c4117cc22cb3

I followed your guide https://hardhat.org/guides/migrate-from-buidler.html
But once completed the guide I get the following error message on `npx hardhat compile` or `npx hardhat test` command:
```
[Error: EISDIR: illegal operation on a directory, read] {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
```

As far as I know it has something to do with Node trying to read from a directory where it hasn't the permission.
I tried to change the paths in the `hardhat.config.js` countless times but couldn't make it work..

If you have any clues or eventually already encountered this problem please let me know, with Buidler everything worked fine.
I tried it with Node 10, 12 and even 14.

If you need any further information to reproduce the issue or eventually there is something big I'm missing.

Thank you very much!

**Comment by alcuadrado** [comment]
Hey @sebastinez,

Thanks for reporting this issue. Can you provide more info about your setup? Which OS are you running?

**Comment by sebastinez** [comment]
Hi @alcuadrado 

Thank you for your fast response. I'm using Ubuntu 20.04.1, the shell I'm using is zsh.
If you need more information regarding the permissions set on the directories and files please let me know.

**Comment by alcuadrado** [comment]
Thanks. Have you tried running `npx hardhat clean` and `npx hardhat clean --global`?

**Comment by sebastinez** [comment]
@alcuadrado thank you very much. Each time after running `npx hardhat clean` I'm able to run `npx hardhat compile` or `npx hardhat test` once and then I have to run `npx hardhat clean` again. It seems that somehow the files that get created give Node a hard time. I added an output of the `git diff` command after running `npx hardhat compile`

```
 create mode 100644 cache/solidity-files-cache.json
 create mode 100644 src/contracts/artifacts/build-info/592798ec-4031-472d-bee9-fafa3eb91f8e.json
 create mode 100644 src/contracts/artifacts/src/contracts/NuclearPoE.sol/NuclearPoE.dbg.json
 create mode 100644 src/contracts/artifacts/src/contracts/NuclearPoE.sol/NuclearPoE.json
 create mode 100644 src/contracts/artifacts/src/contracts/Ownable.sol/Ownable.dbg.json
 create mode 100644 src/contracts/artifacts/src/contracts/Ownable.sol/Ownable.json
 create mode 100644 src/contracts/artifacts/src/contracts/Process.sol/Process.dbg.json
 create mode 100644 src/contracts/artifacts/src/contracts/Process.sol/Process.json
```

As requested I link you to the tree file of the project, one is with the `npx hardhat clean` command and one after compilation or testing, and I added also a extract of the `git diff` command with the files that get created
https://gist.github.com/sebastinez/ede132d24351fe15d4252f208a10e6f1

Eventually there is some problem with the way I structured my project, and the paths I used, I send you my `hardhat.config.js` file.
https://github.com/NRS-Soft/nuclearistrack/blob/hardhat-migration/hardhat.config.js

Thank you very much!

**Comment by sebastinez** [comment]
@alcuadrado I think I found a workaround.
If I keep the generated `artifacts` folder as default value, meaning in the root folder, everything works fine.
This is the path section of my latest `hardhat.config.js`

```
  paths: {
    sources: './src/contracts',
    tests: './src/contracts/test',
    cache: './cache',
    artifacts: './artifacts',
  },
```

**Comment by fvictorio** [comment]
Ugh, that's weird. We should check if it was caused just because of a different artifacts path (unlikely, I think) or because the artifacts path was inside the contracts path. In any case, I think we should consider this a bug.

**Comment by alcuadrado** [comment]
The reason you are getting that error is that your artifacts directory is inside your sources directory. 

When emitting artifacts, one directory is created per each `.sol` file, which has the same name. The next  compilation process then gets confused, thinks that those are files, and tries to read them.

We should probably improve that error message, but I don't think we should support storing your compilation output inside the same directory where you place your sources.

**Comment by alcuadrado** [comment]
The problem comes from placing the artifacts directory inside of the sources one.

Hardhat creates a directory per each `.sol` file that it compiles, with the same name. Then, a successive compilation process will think that those are files, try to read them, and throw that error.

I think we should improve the error message, and maybe even validate that the artifacts folder isn't inside the sources one, but I don't think we should support this usecase.

**Comment by alcuadrado** [comment]
BTW, I noticed that you are committing your artifacts and cache dirs. We discourage doing that, as those can get HUGE.

**Comment by sebastinez** [comment]
Thank you very much @alcuadrado and @fvictorio.
I understand now why Node was trying to read a directory 😄

Yes I think, with a disclaimer in the documentation, to not store your `artifacts` in your `sources` directory, would be a great improvement. And for the ones like me a better error message would be great too. (If you don't mind I could check if I can make that happen)

Thanks @alcuadrado for the comment about committing artifacts and cache dirs, I do it because I need the compiled contracts in production. I'll see if I can generate the contracts during deployment.

For me this issue is closed.

**Comment by alcuadrado** [comment]
Hi,

I'm closing this issue as it has been a long time without activity, and it's unlikely it's still relevant/present.

Thanks for reporting it anyway, and please open a new one if you think it's needed.
