### ISSUE TITLE
How to add solidity output (as defined in the solidity.settings.outputSelection) to artifacts.

### ISSUE THREAD

**Issue by dvush** [NomicFoundation/hardhat#1121]
It is possible to configure output selection using settings field of the solidity config to get some additional output from compiler and this fields will appear in some of the .json files in the `artifacts/build-info` but not in the convenient arifact file that is generated for each contract separately. 

AFAIK form of artifact output for solidity is hard-coded and not configurable.

Is it possible to change it?

**Comment by fvictorio** [comment]
Does the `settings` property not work for you?

```
solidity: {
  version: "0.7.0",
  settings: {
    // whatever solc settings you want
  }
}
```

**Comment by dvush** [comment]
It works, but it does not add this output to the compile artifact file of the contract. 

Example: 
I add additional output ("storageLayout") for one of the contracts using settings.

It works and I can find this additional output hidden somewhere in the file that is named like this: `artifacts/build-info/2cf939d2-01e9-4fd7-ade9-7ffd16be72ee.json`. So to get this additional ouput in code I have to go to `artifacts/build-info` dir and search for information that I need in this files and it can be hard because there are multiple files like this and they have random names. 

Instead It would be convenient to see this output in the file `artifacts/File.sol/Contract.json` where some predefined set of compiler outputs is copied (ABI, bytecode, etc.)

Here is a function where built contract artifact is built https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/src/internal/artifacts.ts#L467 and it ignores all the outputs except some.

What would you recommend to do to conveniently work with it?

**Comment by fvictorio** [comment]
Oh, I see. It depends a lot on what you are trying to accomplish, but you can start with this:

```
const buildInfo = await hre.artifacts.getBuildInfo("contracts/Foo.sol:Foo")
const output = buildInfo.output.contracts["contracts/Foo.sol"]["Foo"]
```

and that will give you the raw output for that contract. The argument in the first call is the _fully qualified name_ of the contract, which is a string of the form `${sourceName}:${contractName}`, where source name is just the path from the root of your project to the solidity file where the contract is defined (always with forward slashes, even on windows) and the contract name is... well, the contract name.

The second line also uses the source name and the contract name to get the output, but they are different property accesses.

I realize this is not very ergonomic, but I'm not sure what would be the best way to improve this for your use case. Maybe an easier way to get the output from the contract name? Or having some way to extend the data in the generated artifact based on the build output?

**Comment by dvush** [comment]
Thanks! 

This looks great, I did not know about `.getBuildInfo`.

About possible ways to make it easier: I think both ways are good. 

Now I understand that I preferred second way because I thought about build-info files as some kind of cache that should not be used because of unpredictable file name and "messy" structure but if there is a  "getBuildInfo' for contract it is as good as it can be. Although it would be more convenient if it would be possible to have functions like `getSolidityBuildInfo` or  `getSolidityOutput`  given just contract name (similar to `hre.ethers.getContractFactory`) or name with path.

**Comment by fvictorio** [comment]
Closing this in favor of https://github.com/NomicFoundation/hardhat/issues/3319.
