### ISSUE TITLE
Forking Rinkeby. Could not generate stack trace.

### ISSUE THREAD

**Issue by skyfly200** [NomicFoundation/hardhat#1196]
The commit in my repo that I was at:
https://github.com/skyfly200/tiny-boxes/commit/ba5e2900fe2cb40107c4ec01d7ddebe1750debca

The command I ran: 
hh test ./test/Render.js --verbose

Error that I recieved

 > hardhat:core:hre Creating provider for network hardhat +220ms
>   hardhat:core:hardhat-network:node Could not generate stack trace. Please report this to help us improve Hardhat.
>   hardhat:core:hardhat-network:node  TypeError: Cannot use 'in' operator to search for 'pc' in undefined
>     at Object.isEvmStep (/mnt/c/Users/skyfl/Documents/GitHub/tiny-boxes/node_modules/hardhat/src/internal/hardhat-network/stack-traces/message-trace.ts:88:14)
>     at SolidityTracer._rawTraceEvmExecution (/mnt/c/Users/skyfl/Documents/GitHub/tiny-boxes/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:432:10)
>     at SolidityTracer._traceEvmExecution (/mnt/c/Users/skyfl/Documents/GitHub/tiny-boxes/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:236:29)
>     at SolidityTracer._getCreateMessageStackTrace (/mnt/c/Users/skyfl/Documents/GitHub/tiny-boxes/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:219:17)
>     at SolidityTracer.getStackTrace (/mnt/c/Users/skyfl/Documents/GitHub/tiny-boxes/node_modules/hardhat/src/internal/hardhat-network/stack-traces/solidityTracer.ts:70:19)
>     at HardhatNode._manageErrors (/mnt/c/Users/skyfl/Documents/GitHub/tiny-boxes/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:913:41)
>     at HardhatNode.estimateGas (/mnt/c/Users/skyfl/Documents/GitHub/tiny-boxes/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:508:27)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
>     at EthModule._estimateGasAction (/mnt/c/Users/skyfl/Documents/GitHub/tiny-boxes/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:390:9)
>     at HardhatNetworkProvider.request (/mnt/c/Users/skyfl/Documents/GitHub/tiny-boxes/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:102:18) +0ms

**Comment by fvictorio** [comment]
I believe this is no longer happening in the latest version of Hardhat.
