### ISSUE TITLE
Can not change gas price of local mainet fork

### ISSUE THREAD

**Issue by keeyi1chp** [NomicFoundation/hardhat#1216]
Here is my hardhat setting: 

```js
module.exports = {
  solidity: "0.7.3",
  networks: {
    hardhat: {
      forking: {
        url: "http://127.0.0.1:18545"
      },
      gasPrice: 150000000000
    }
  }
};
```

But the gas price is still 8000000000: 

```js
const gasPrice = await web3.eth.getGasPrice();
console.log(`gasPrice is ${gasPrice}`);   //  8000000000
```

So how to set gas price properly?

**Comment by lcswillems** [comment]
I have the same issue...

**Comment by fvictorio** [comment]
Hey @keeyi1chp, sorry for not answering before.

That option sets the default gas price for transactions that you send. On the other hand, `getGasPrice` uses the `eth_gasPrice` RPC method which is basically an estimation returned by the node of the current gas price.

We don't have a way to set the result of `eth_gasPrice` (we always return a hardcoded value). If by any chance you think that it would be useful to be able to configure it, feel free to open a new issue requesting it.

**Comment by lcswillems** [comment]
@fvictorio What do you mean by "we always return a hardcoded value". Why is it hardcoded?

I don't have this issue with Ganache! I fork the same network and get the correct gasPrice.

**Comment by fvictorio** [comment]
@lcswillems sorry for not responding before. I think it makes sense to expect forked networks to forward the `gasPrice` request. Feel free to open a feature request with this! (We could use this one, but I don't want to edit both the title and the content, in case this discussion is useful to someone else)

**Comment by lcswillems** [comment]
@fvictorio Maybe could you open this new issue or reopen this one? Because I see no reason of closing this one: currently it is not possible to "change the gas price of a local mainnet fork" and if I had to open a new issue, I would exactly copy paste this one.

**Comment by fvictorio** [comment]
@lcswillems that's fair, reopening :slightly_smiling_face:

**Comment by lcswillems** [comment]
Thanks!

**Comment by lcswillems** [comment]
@fvictorio Do you have any idea which part of Hardhat source code I should change in order to solve this issue?

**Comment by fvictorio** [comment]
You can try changing this:

https://github.com/nomiclabs/hardhat/blob/0625c12d7f2a75056218928f4f03411e50fad0ae/packages/hardhat-core/src/internal/core/config/default-config.ts#L5

**Comment by fvictorio** [comment]
I'm going to tentatively close this issue. We have [`hardhat_setNextBlockBaseFeePerGas`](https://hardhat.org/hardhat-network/docs/reference#hardhat_setnextblockbasefeepergas) now which, I think, is what most people would want. This doesn't exactly _set_ the value returned by `eth_gasPrice`, although it does affect it. But that method is not as useful anymore after EIP-1559 and `eth_feeHistory`. If someone really needs some kind of `hardhat_setGasPrice` method, please open a new issue explaining your use case.
