### ISSUE TITLE
Slow startup of the test task

### ISSUE THREAD

**Issue by shark0der** [NomicFoundation/hardhat#1219]
Our test suite startup time is quite slow (around 8 seconds) even for running a simple test (i.e. including a single file). 

Here we're running 3 really simple tests and it takes 7.7 seconds:
```
$ time npx hardhat test --no-compile test/unit/ClaimProofs/index.js


  ClaimProofs unit tests
    addProof
      ✓ should emit an event with coverId, ipfsHash and sender when called (212ms)
      ✓ should allow anyone to submit a proof for the same coverId (67ms)
      ✓ should allow someone to submit a proof multiple times (42ms)


  3 passing (3s)

npx hardhat test --no-compile test/unit/ClaimProofs/index.js  14.28s user 1.26s system 200% cpu 7.734 total
```

We're using hardhat with truffle5 and web3 plugins and do have a lot of artifacts (around 100) - our contracts, uniswap and various mocks. Although the number of artifacts is quite high, I think loading them shouldn't take THAT much time - I think in 2021, our laptops can handle hundreds of artifacts in under one second, so there must be some bottleneck somewhere. 

The repo in this example is https://github.com/NexusMutual/smart-contracts/tree/af2d4659088f81febc9c25620d03aba375485336

**Comment by alcuadrado** [comment]
This is an unfortunate regression. We put a lot of work on optimizing the startup time.

Do you use typescript?

**Comment by smoove** [comment]
> Do you use typescript?

Yes I do.

**Comment by fvictorio** [comment]
I can reproduce this in a ts project. Js projects seem to work fine.

**Comment by gakonst** [comment]
I also encountered this in [Optimism's Contracts](https://github.com/ethereum-optimism/contracts-v2/) when trying to build inside docker using `node:14-alpine`

**Comment by TransmissionsDev** [comment]
Same. Any update on this? Makes iterating quite slow.

**Comment by alcuadrado** [comment]
If printing a help message is taking multiple seconds, it's most probably because you are using typescript, and `ts-node` recompiles everything each time you run it, and that can be slow. As a workaround, you can set the env variable `TS_NODE_TRANSPILE_ONLY=1`.

If that doesn't help the reason is probably a plugin doing something slow during its intialization. Can you try commenting out some of them and re-running the help task?

**Comment by TransmissionsDev** [comment]
> If printing a help message is taking multiple seconds, it's most probably because you are using typescript, and `ts-node` recompiles everything each time you run it, and that can be slow. As a workaround, you can set the env variable `TS_NODE_TRANSPILE_ONLY=1`.
> 
> If that doesn't help the reason is probably a plugin doing something slow during its intialization. Can you try commenting out some of them and re-running the help task?

Adding `TS_NODE_TRANSPILE_ONLY=1` fixes the lag. Any chance this can get added by default or something similar to avoid the full recompile?

**Comment by fvictorio** [comment]
> Adding `TS_NODE_TRANSPILE_ONLY=1` fixes the lag! Any chance this can get added by default or something similar to avoid the full recompile?

Yes, this is something we've talked about and will probably do at some point if we are sure it doesn't cause any issues.

**Comment by alcuadrado** [comment]
> something similar to avoid the full recompile?

We are trying to sponsor the implementation of this feature in `ts-node` 🤞

**Comment by alcuadrado** [comment]
Some updates: 

1. We are sponsoring a change in `ts-node` so that it uses incremental builds.
2. This makes hardhat with ts super fast: https://github.com/TypeStrong/ts-node/#bundled-swc-integration

**Comment by fvictorio** [comment]
@ShravanSunder I don't think that's possible right now, sorry.

**Comment by fvictorio** [comment]
@shark0der confirmed that this is no longer an issue for their (non-typescript) project.

As for the rest of the discussion about ts, the latest versions of hardhat use the transpile-only mode by default.
