### ISSUE TITLE
Custom Gas and  gasMultiplier are not taking effect when deploying to Ropsten

### ISSUE THREAD

**Issue by HatimKH** [NomicFoundation/hardhat#1228]
Changing the values of gas and gasMultiplier in `hardhat.config.js` file  are not taking effect. The smart contract deployment is always done using the hardhat default values.

**Config 1**
````quote
module.exports = {
  solidity: "0.7.3",
  networks: {
    ropsten: {
      url: `https://ropsten.infura.io/v3/${INFURA_PROJECT_ID}`,
      accounts: [`0x${ROPSTEN_PRIVATE_KEY}`],
      gasMultiplier: 2
    }
  }
};
````
**Config 2**
````quote
module.exports = {
  solidity: "0.7.3",
  networks: {
    ropsten: {
      url: `https://ropsten.infura.io/v3/${INFURA_PROJECT_ID}`,
      accounts: [`0x${ROPSTEN_PRIVATE_KEY}`],
      gas: 500000
    }
  }
};
````

**Comment by nnabuuu** [comment]
Same problem observed on Polygon test network Mumbai as well

**Comment by mkobelt** [comment]
Also not working with the local Hardhat Network

**Comment by fvictorio** [comment]
Sorry for the late response.

I'm going to assume you are using ethers. These values don't work in that case, we've added a clarification about this [in the docs](https://hardhat.org/hardhat-network/docs/reference).

Of course, this is not ideal. I opened https://github.com/NomicFoundation/hardhat/issues/3496 to track that problem.
