### ISSUE TITLE
Custom timeout is not taking effect when deploying to Ropsten

### ISSUE THREAD

**Issue by HatimKH** [NomicFoundation/hardhat#1229]
Changing the values of timeout in `hardhat.config.js` file  are not taking effect. The upgradable smart contract deployment (openZepplin plugin) is timeout in an around 1 minute when the first contract deployment is taking more than 1 minute  .

**Config**

````quote
module.exports = {
  solidity: "0.7.3",
  networks: {
    ropsten: {
      url: `https://ropsten.infura.io/v3/${INFURA_PROJECT_ID}`,
      accounts: [`0x${ROPSTEN_PRIVATE_KEY}`],
      timeout: 200000
    }
  }
};
````

**Comment by sparrowDom** [comment]
I am seeing similar issues

**Comment by fvictorio** [comment]
This doesn't seem to happen in the latest version of Hardhat. If someone is still running into this and has minimal reproduction steps, please open a new issue.
