### ISSUE TITLE
Hardhat network forking with a proxy

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#1238]
Some users have reported that they can't use mainnet forking if they are behind a proxy. We should add an option for this.

**Comment by alcuadrado** [comment]
Do you mean a mandatory organization-wide proxy? Like in a corporate/university network?

**Comment by fvictorio** [comment]
Yes

**Comment by mhorsley30896** [comment]
Any update on this? I am running into this issue

**Comment by liuqiba** [comment]
I checked all the "forking" problems and found the solution only after seeing this article.
Thank you!!!!

**Comment by fvictorio** [comment]
This will be included in the next release but, if someone wants to try it right now, you can do it by installing the `dev` version that has this change: `npm i hardhat@2.9.8-dev.0`
