### ISSUE TITLE
ECONNREFUSED Upon "npx hardhat run ..." & "npx hardhat node"

### ISSUE THREAD

**Issue by DrManhattan115** [NomicFoundation/hardhat#1311]
![image](https://user-images.githubusercontent.com/49825641/110357552-66a3bd80-8009-11eb-9ef3-4ee344c43811.png)
![image](https://user-images.githubusercontent.com/49825641/110357673-8935d680-8009-11eb-8a2e-76d920989417.png)

**Comment by fvictorio** [comment]
This seems like just a connection error, but the way that message was shown doesn't feel right, so I'll keep this open to fix this.

**Comment by DrScatman** [comment]
@fvictorio Comcast's network threat detection blocked the local hardhat node. It seems I have to use a VPN...

**Comment by fvictorio** [comment]
Closing in favor of #1731, which is about improving the message shown.
