### ISSUE TITLE
Old hardhat-ganache verison on npm

### ISSUE THREAD

**Issue by mdenushev** [NomicFoundation/hardhat#1326]
Currently, on npm not uploaded [this commit](https://github.com/nomiclabs/hardhat/commit/71f268477bcd68afcf347d2700d2bf9253bbea3d#diff-f061864276d864bd266a85a7e2c9d97152e26740d2c770bffee605895d87c956) (also there is old version badge on npm), so now i cannot use istambul hardfork because it's not allowed

``` 
npx hardhat --network ganache test
Error in plugin @nomiclabs/hardhat-ganache: Ganache network config is invalid: value.hardfork is none of "byzantium", "constantinople", "petersburg"
```

**Comment by fvictorio** [comment]
I think the proper version was published more than a year ago.
