### ISSUE TITLE
forking from a node that requires authentication

### ISSUE THREAD

**Issue by pointtoken** [NomicFoundation/hardhat#1334]
How do you set up forking from a node that requires an authentication header?

**Comment by pointtoken** [comment]
I am guess this isn't possible in the current codebase. The way Ethers does it is quite elegant with their ConnectionInfo object, which could be deserialized to the hardhat config and then used when the node URL is instantiated, adding the header then, again you can see how Ethers does it...

**Comment by fvictorio** [comment]
Hi @pointtoken. No, this isn't possible right now. I'll keep this issue open though, since I guess it's something we want to fix at some point.

**Comment by fvictorio** [comment]
I think this is possible now using [custom `httpHeaders`](https://hardhat.org/hardhat-network/docs/guides/forking-other-networks#custom-http-headers).
