### ISSUE TITLE
Hardhat solpp - Error: Cannot find module 'antlr4/index'

### ISSUE THREAD

**Issue by sgissinger** [NomicFoundation/hardhat#1412]
I have this error when only importing in `hardhat.config`
```
import '@nomiclabs/hardhat-solpp'
```

I use node v12

This seems related to an issue with antlr4 versions
https://github.com/merklejerk/solpp/issues/7

The solution seems to bump solpp to 0.11.3

**Comment by davidtperk** [comment]
Can we get https://github.com/nomiclabs/hardhat/pull/2319 merged and republish the currently-broken [@nomiclabs/hardhat-solpp](https://www.npmjs.com/package/@nomiclabs/hardhat-solpp) package?

**Comment by fvictorio** [comment]
The latest version of `hardhat-solpp` doesn't seem to produce an error anymore. There is an annoying warning, but that happens even after ugprading solpp. Also, notice that solpp seems to be deprecated now https://github.com/merklejerk/solpp/issues/23

So I don't think we can close this issue? Let me know if you disagree.
