### ISSUE TITLE
Hardhat doesn't seem to work if node is installed with apt-get

### ISSUE THREAD

**Issue by quarquade** [NomicFoundation/hardhat#1457]
In a clean and new ubuntu 20.4 machine I'm not able to properly install install hardhat.
Here the log.

```
npm install --save-dev hardhat
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.1 (node_modules/mocha/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN test_01@1.0.0 No description
npm WARN test_01@1.0.0 No repository field.

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/vm/Development/eth/test_01/node_modules/ethereumjs-abi/node_modules/@types/bn.js/package.json.2568148019
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/vm/Development/eth/test_01/node_modules/ethereumjs-abi/node_modules/@types/bn.js/package.json.2568148019'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vm/.npm/_logs/2021-05-16T13_35_03_400Z-debug.log
```

after installing types, same situation but with a new missing dependency.
```
vm@vm:~/Development/eth/test_01$ npm install --save-dev types
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.1 (node_modules/mocha/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN test_01@1.0.0 No description
npm WARN test_01@1.0.0 No repository field.

+ types@0.1.1
added 1 package from 1 contributor, removed 283 packages and audited 1 package in 1065.162s
found 0 vulnerabilities

vm@vm:~/Development/eth/test_01$ npm install --save-dev hardhat
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.1 (node_modules/mocha/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN test_01@1.0.0 No description
npm WARN test_01@1.0.0 No repository field.

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/vm/Development/eth/test_01/node_modules/debug/node_modules/ms/package.json.3263783228
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/vm/Development/eth/test_01/node_modules/debug/node_modules/ms/package.json.3263783228'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vm/.npm/_logs/2021-05-16T16_23_49_938Z-debug.log
```

My setup is the following:
- OS: ubuntu 20.04
- Node: v10.19.0
- npm: 6.14.4

**Comment by Endlessline** [comment]
Can you upgrade npm to 7.x? I have the same setup with the exception of npm being v 7.11.1 and install works without issue.

**Comment by quarquade** [comment]
> Can you upgrade npm to 7.x? I have the same setup with the exception of npm being v 7.11.1 and install works without issue.

what is the safest way to update it / maintaining different version on the same machine ? Why minimal requirements are not indicated in the setup page? Thanks

**Comment by Bidon15** [comment]
The easiest way is to use nvm
Some examples are located here: https://hardhat.org/tutorial/setting-up-the-environment.html

**Comment by fvictorio** [comment]
> Why minimal requirements are not indicated in the setup page?

Hardhat works with node 10 or later (and we'll drop support for node 10 soon). But you are right, that should be indicated in the "Installation" section, thanks for the feedback.

Can we close this issue?

**Comment by quarquade** [comment]
> > Why minimal requirements are not indicated in the setup page?
> 
> Hardhat works with node 10 or later (and we'll drop support for node 10 soon). But you are right, that should be indicated in the "Installation" section, thanks for the feedback.
> 
> Can we close this issue?

you can but I was not able to install it on ubuntu

**Comment by fvictorio** [comment]
Oh, sorry, I thought it was a node version issue. Just to clarify, you are using node >= 10 and still unable to install it?

**Comment by fvictorio** [comment]
Ok, I just saw in your original issue that you mentioned the node version. This is very strange. I'm also on Ubuntu 20.04 and I've never had this problem. How is your node installed? A system installation, nvm, other?

**Comment by fvictorio** [comment]
Btw, I'm also in npm v6 and I don't have this problem.

**Comment by quarquade** [comment]
I installed using apt-get, successively installing the latest version of nodejs using the official script. Noting, same kind of errors. Are you on ubuntu or macos? My setup is quite easy to reproduce since I was using a virtual machine with a fresh new version of ubuntu 20.4.
Now i think i'll switch to macos, what is the best way: using nvm as suggested in a previous post? Thanks

**Comment by fvictorio** [comment]
I'm on Ubuntu. I haven't tried hardhat with the system version of node (that is, not installed with nvm), but I think it should work. I'll try to reproduce the problem at some other time, but yes, usually it's a good idea to just use nvm.

If you don't mind, I'll edit the title of the issue to better reflect the (possible) issue.

**Comment by quarquade** [comment]
thanks, I'll follow it. Now to speed up I switch to macos where it should work fine. Keep us updated, thanks

**Comment by alcuadrado** [comment]
@quarquade, what kind of vm are you running on? I mean, which virtualization system, architecture, and how did you install ubuntu there?

Thanks!

**Comment by fvictorio** [comment]
I couldn't reproduce this inside a fresh ubuntu docker container.
