### ISSUE TITLE
Support to avoid compiling contracts in hardhat-etherscan subtask

### ISSUE THREAD

**Issue by patitonar** [NomicFoundation/hardhat#1465]
I'm calling the hardhat-etherscan task programmatically as part of a contract deployment. Since etherscan takes some time to index the new contract I added a retry logic to wait some seconds and call the verify task a couple of times until it successfully verifies the contract.
Every time I call the verify task, it recompiles the contracts and display the output in the console making it difficult to follow my deployment logs.

It would be great to have a flag to avoid compiling the contracts when calling the verify subtask programmatically

**Comment by fvictorio** [comment]
We have a `noCompile` flag now.
