### ISSUE TITLE
[Request] Support glob patterns for 'test' tasks calling mocha

### ISSUE THREAD

**Issue by ScreamingHawk** [NomicFoundation/hardhat#1544]
This is related to #1242 

I find projects that I try to contribute to frequently use wildcard paths. 
While this works for Unix systems, it does not work in Windows. 

Example from a `package.json` in a project using hardhat:
```
"test:hardhat": "hardhat test \"test/*.spec.ts\""
```

I had a read of the discord chat and it appears this feature isn't a priority, but I still believe it will be a valuable change.

**Comment by fvictorio** [comment]
Thanks for submitting this @ScreamingHawk. One workaround you could use for now is to run `mocha` directly. [Here's](https://github.com/fvictorio/hardhat-examples/tree/master/parallel-tests) an example of how that is done.

**Comment by aspiers** [comment]
Scripts defined in `package.json` get expanded by a shell process, so you can just change the above to:

    "test:hardhat": "hardhat test test/*.spec.ts"

and it will work; there's no need for hardhat to do the expansion when the shell will do it.

`npx hardhat test test/*.spec.ts` from the CLI will work for the same reason.

Ideally it would also be possible to dictate which tests get run via the hardhat or mocha config files, but unfortunately that doesn't work either; I've submitted #1806 to track that.

**Comment by fvictorio** [comment]
The `test` task has a `--grep` param now.
