### ISSUE TITLE
Accept leading zeros in QUANTITY

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#1585]
This throws an error:

```js
await ethers.provider.send("hardhat_setBalance", ["0x7D6bF26aA0B80A44b2ba41edAE1AA7663B6B20ac", ethers.utils.parseEther("1").toHexString()])
```

The reason it doesn't work is that 1 eth in (padded) hex is `0x0de0b6b3a7640000`. Since users rely on `ethers.utils.parseEther` a lot, we should accept this (plus, it's a valid hex IMO).

The only thing we should decide is if we accept any amount of leading zeros or only hex strings padded to an even length. I'll check what geth does and update this issue.

**Comment by alcuadrado** [comment]
Unfortunately, this goes against the "definition" of the JSON-RPC types, as documented [here](https://ethereum.org/en/developers/docs/apis/json-rpc/#hex-value-encoding).

If we relax this type's validation, users can end up with test suites that only run with Hardhat Network despite only using standard json-rpc methods, which is something we want to avoid.

**Comment by fvictorio** [comment]
Yeah, that makes sense for the main quantity type. I wonder though if we can have a more permissive type for our methods, like `hardhat_setBalance`, just so that the `send("hardhat_setBalance", parseEther(...).toHexString())` snippet works.

**Comment by 5hanth** [comment]
+1

```
    await network.provider.request({
      method: 'hardhat_setBalance',
      params: ['0x7147C79F2B8d744DDeCD70318cf4a3471cc4fACa', '0xde0b6b3a7640000']
    })
```

```     Error: invalid object key - 0 (argument="transaction:0", value={"0":"e","1":"t","2":"h","3":"_","4":"g","5":"e","6":"t","7":"B","8":"a","9":"l","10":"a","11":"n","12":"c","13":"e","gasLimit":{"type":"BigNumber","hex":"0xcf09"},"from":"0x7147C79F2B8d744DDeCD70318cf4a3471cc4fACa"}, code=INVALID_ARGUMENT, version=properties/5.4.0)```

**Comment by alcuadrado** [comment]
This isn't related to this issue, @5hanth. Please double check your code.

**Comment by 5hanth** [comment]
my bad. it's not related to this. @alcuadrado there was another part that's trying to get balance.  ```  await network.provider.request({
      method: 'hardhat_setBalance',
      params: [myWallet, ethers.utils.parseEther('10.0').toHexString()]
    })``` works fine.

**Comment by fluidsonic** [comment]
I've started using Hardhat recently and also ran into this issue now.
From the error messages it's absolutely not clear what the actual issue is (leading zero).

Potential solutions:
- provide own utility functions for passing ether/gwei/etc.
- provide proper high-level function to set balance instead of going throw lower-level `EthereumProvider.send()`

And ideally:
- improve error message
- use more realistic [sample code](https://hardhat.org/guides/mainnet-forking.html#setting-account-balance) using an ether value instead of `"0x1000"`

**Comment by alcuadrado** [comment]
> * provide proper high-level function to set balance instead of going throw lower-level `EthereumProvider.send()`

We are moving into this direction. Not ETA right now tough.

**Comment by fvictorio** [comment]
> * use more realistic [sample code](https://hardhat.org/guides/mainnet-forking.html#setting-account-balance) using an ether value instead of `"0x1000"`

Agree with this. As a temporary measure, we could include a valid snippet for setting a balance with `parseEther`. Something like:

```js
const newBalance = ethers.utils.parseEther("1");

// this is necessary because hex quantities with leading zeros are not valid at the JSON-RPC layer
const newBalanceHex = newBalance.toHexString().replace("0x0", "0x");

await network.provider.send("hardhat_setBalance", [
  "0x0d2026b3EE6eC71FC6746ADb6311F6d3Ba1C000B",
  newBalanceHex,
]);
```

**Comment by banshee** [comment]
> > * use more realistic [sample code](https://hardhat.org/guides/mainnet-forking.html#setting-account-balance) using an ether value instead of `"0x1000"`
> 
> Agree with this. As a temporary measure, we could include a valid snippet for setting a balance with `parseEther`. Something like:
> 
> ```js
> const newBalance = ethers.utils.parseEther("1");
> 
> // this is necessary because hex quantities with leading zeros are not valid at the JSON-RPC layer
> const newBalanceHex = newBalance.toHexString().replace("0x0", "0x");
> ```

I'd probably use a more forgiving regular expression to grab all the leading zeros:

```
.replace(/0x0+/, "0x")
```

And definitely mention in the docs that it has to be valid according to https://ethereum.org/en/developers/docs/apis/json-rpc/#hex-value-encoding

**Comment by mds1** [comment]
You can also replace all leading zeros with [`ethers.utils.hexStripZeros(value)`](https://github.com/ethers-io/ethers.js/blob/c2c0ce75039e7256b287f9a764188d08ed0b7296/packages/bytes/src.ts/index.ts#L298-L308)

At first I was in favor of relaxing this, but if geth, etc. do behave the same way, I think it makes sense to stay consistent and leave this as-is, but with two main changes to reduce confusion when encountering this:
- Documenting the behavior + linking to the appropriate section of the spec, since many users (like me this morning) are likely not familiar with that aspect of the JSON RPC spec
- Improving the error message, perhaps something like `Invalid value "<value>" supplied to : QUANTITY. Make the sure the value has no leading zeros`

**Comment by fvictorio** [comment]
I strongly agree with both points :+1:

**Comment by fvictorio** [comment]
More data on this: geth, nethermind and OE all accept leading zeros for `eth_getStorageAt`. I still think we should follow the standard, but I also think the standard should be updated to allow leading zeros.

**Comment by feuGeneA** [comment]
@alcuadrado suggests just changing "QUANTITY" to something like "QUANTITY (0x-prefixed hex string without leading zeroes)" in https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/src/internal/core/jsonrpc/types/base-types.ts#L11

**Comment by chanhosuh** [comment]
> > ```js
> > const newBalance = ethers.utils.parseEther("1");
> > 
> > // this is necessary because hex quantities with leading zeros are not valid at the JSON-RPC layer
> > const newBalanceHex = newBalance.toHexString().replace("0x0", "0x");
> > ```
> 
> I'd probably use a more forgiving regular expression to grab all the leading zeros:
> 
> ```
> .replace(/0x0+/, "0x")
> ```

What happens if the new balance is actually zero?  I'm too lazy to check right now ;) but I presume using `0x` as the balance will give an error.

**Comment by fvictorio** [comment]
> What happens if the new balance is actually zero?

The result of `ethers.utils.parseEther("0").toHexString()` is `0x00`, so the `replace` trick should continue to work.

**Comment by chanhosuh** [comment]
> > What happens if the new balance is actually zero?
> 
> The result of `ethers.utils.parseEther("0").toHexString()` is `0x00`, so the `replace` trick should continue to work.

The replace with the regex will result in `0x`.

**Comment by fvictorio** [comment]
> The replace with the regex will result in `0x`.

Have you tried it or are you guessing that that will be the result? Because it did work for me. If you can share a case where that happens, we might refine the workaround.

**Comment by chanhosuh** [comment]
> > The replace with the regex will result in `0x`.
> 
> Have you tried it or are you guessing that that will be the result? Because it did work for me. If you can share a case where that happens, we might refine the workaround.

I "guessed" the result based on my understanding of regex syntax... but here you go (in the JS console):

```javascript
> "0x00".replace(/0x0+/, "0x")
'0x'
```

and the complete syntax in node:

```node
> const {ethers} = require("hardhat")
undefined
> ethers.utils.parseEther("0").toHexString().replace(/0x0+/, "0x")
'0x'
```

Again, let me emphasize that it's the regex version I quoted and responded to previously (you seem to think I'm responding to your workaround).  I mentioned this in my last response but I hope it's clearer this time around.

**Comment by fvictorio** [comment]
Oh yeah, you're right, my bad.

**Comment by fvictorio** [comment]
Closing this for now. In the coming weeks we will release a set of helpers with a more ergonomic API, and using the low-level JSON-RPC methods won't be necessary anymore. Those helpers will handle this problem in a transparent way, so ideally no one will have to deal with this anymore.

We'll post an update here when these helpers are released.

**Comment by alberts9** [comment]
Have the helpers been released?

**Comment by fvictorio** [comment]
@alberts9 yes! Check them out [here](https://hardhat.org/hardhat-network-helpers/docs/overview).

**Comment by QEDK** [comment]
It would be great to _atleast_ change the error message to something more verbose, it is slightly unrealistic to understanding anything of value from the current error message.

**Comment by fvictorio** [comment]
@QEDK I think we did? Which error message are you getting? And which version of hardhat are you using?

**Comment by QEDK** [comment]
> @QEDK I think we did? Which error message are you getting? And which version of hardhat are you using?

Using `2.10.2`, still getting `InvalidArgumentsError: Errors encountered in param 1: Invalid value "0x0c7be71a38523ae80000" supplied to : QUANTITY` atm.

**Comment by fastchain** [comment]
Checking gnosisSafe deployed on hardhat  virtualnode RPC

```
npx  hardhat info  0xF58681d366Afb34a3490862C39282FC2D938CCe5 --network local1

Checking Safe at 0xF58681d366Afb34a3490862C39282FC2D938CCe5
(node:870) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
An unexpected error occurred:

ProviderError: HttpProviderError
    at HttpProvider.request (/metarouter-v2-offchain/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
    at LocalAccountsProvider.request (/metarouter-v2-offchain/node_modules/hardhat/src/internal/core/providers/accounts.ts:187:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async EthersProviderWrapper.send (/metarouter-v2-offchain/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

also see this in  virtualnode RPC logs 

```
eth_chainId (2)
hardhat1        | eth_getStorageAt
hardhat1        | 
hardhat1        |   Errors encountered in param 1: Invalid value "0x0000000000000000000000000000000000000000000000000000000000000000" supplied to : QUANTITY
hardhat1        | 
```

my hardhat version is 

```
npx hardhat --version
2.11.2
```


It all looks like the same issue is mentioned above :(

**Comment by fvictorio** [comment]
@fastchain any chance you can open a new issue with reproduction steps?
