### ISSUE TITLE
Support JsonRpcProvider basic authentication for `hardhat.forking.url`

### ISSUE THREAD

**Issue by heri16** [NomicFoundation/hardhat#1588]
`networks.hardhat.forking.url` does not accept a  username or password config like in 
https://github.com/ethers-io/ethers.js/issues/159#issuecomment-381359645

```javascript
var urlInfo = {
    url: 'https://foobar.com/eth',
    user: 'username',
    password: 'password'123
};
```

As such we were not able to connect to our Chainstack archival node that requires http basic authentication.

Related code: https://github.com/nomiclabs/hardhat/blob/8277a7219ee25f41495bd6dfde6bd4e308fc84e4/packages/hardhat-core/src/types/config.ts#L71-L75

**Comment by heri16** [comment]
Should we add `httpHeaders` to `HardhatNetworkForkingUserConfig` just like in `HardhatNetworkUserConfig`?

that would allow doing something like this:
```javascript
fetch("https://httpbin.org/basic-auth/user/passwd", {
  headers: new Headers({
    "Authorization": `Basic ${base64.encode(`${login}:${password}`)}`
  }),
})
```

**Comment by fvictorio** [comment]
> Should we add `httpHeaders` to `HardhatNetworkForkingUserConfig` just like in `HardhatNetworkUserConfig`?

This seems like the proper solution to me, yes.

**Comment by alcuadrado** [comment]
We have those in the json rpc networks config, so adding it here should be pretty straight forward.

**Comment by TimDaub** [comment]
Hey, I also just discovered that this feature is missing. Essentially, I'd like to add `Authorization: Bearer abc`.

**Comment by fvictorio** [comment]
@TimDaub all open issues are considered for inclusion. The best way to show your support is to :+1: the issue itself.

**Comment by TimDaub** [comment]
I'll do it. Do we just have to add a type spec for http headers in the config u mentioned? Or do I have to pass those later to a fetch function too? May you point out the location? I'll send PR

**Comment by fvictorio** [comment]
My guess is that it would look like this:

```
hardhat: {
  forking: {
    httpHeaders: { ... }
```

Where `httpHeaders` has the same type as the one in the JSON-RPC based networks.

As to how to implement it, I'm not really sure. Maybe it's as simple as replacing this `undefined` with the headers from the fork config:

https://github.com/nomiclabs/hardhat/blob/c52b75e6d4b6e8a6857083d955dd798c05d4bf4b/packages/hardhat-core/src/internal/hardhat-network/provider/utils/makeForkClient.ts#L36

**Comment by TimDaub** [comment]
Thanks. I made some changes already. But how would you test this functionality? Should I write a separate test, or is the type definitions already fine for you?

**Comment by fvictorio** [comment]
> Thanks. I made some changes already. But how would you test this functionality? Should I write a separate test, or is the type definitions already fine for you?

I meant manually testing it to make sure that it works. Adding automatic tests for this is possible but seems a bit complex: it would mean creating some local HTTP server, using that as the URL, and validating that it receives the headers. It doesn't seem to be worth it IMO.

**Comment by TimDaub** [comment]
>  it would mean creating some local HTTP server, using that as the URL, and validating that it receives the headers. It doesn't seem to be worth it IMO.

Depends. If you guys e.g. use fetch, then [fetch-mock](https://www.npmjs.com/package/fetch-mock) is a pretty good choice. But it'd depend on whether it's usable with TSC and how complex it is to find the fetch instance to monkeypatch.

Shameless plug, I have my own lib for testing that really spins up a temporary HTTP server using express: https://github.com/TimDaub/expressively-mocked-fetch
