### ISSUE TITLE
.solhintignore file is not being recognized by @nomiclabs/hardhat-solhint plugin

### ISSUE THREAD

**Issue by outdoteth** [NomicFoundation/hardhat#1665]
Add `.solhintignore` file that looks like this:

```
External/ 
```

Run solhint with:

```
npx hardhat check
```

Get the following output:

![Screenshot 2021-07-14 at 12 03 59](https://user-images.githubusercontent.com/37438950/125611920-034ce540-c327-4414-8591-ad3df9b15971.png)

Expected everything in `External/` to be ignored but it's still being sent to solhint

**Comment by RauppRafael** [comment]
Same issue here
