### ISSUE TITLE
Contract caller on mainnet fork is a random address on each call

### ISSUE THREAD

**Issue by 0xdavinchee** [NomicFoundation/hardhat#1667]
On a Polygon mainnet fork using Infura, when I impersonate an account and connect to a contract with the impersonated address and interact with the contract, the hardhat node log shows that the contract interaction is from a random address each time I am interacting with the contract rather than the impersonated address. 
Note: I am using hardhat-deploy.

Below is a code which illustrates how I am impersonating the account and interacting with the contracts:

```
// get the contract instance
const contract = await ethers.getContract("Contract");
const impersonatedAddress = "0x84D34f4f83a87596Cd3FB6887cFf8F17Bf5A7B83";

// impersonate account 
await hre.network.provider.request({
    method: "hardhat_impersonateAccount",
    params: [impersonatedAddress],
  });
const signer = await ethers.getSigner(impersonatedAddress);

// contract calling .callA function using the impersonated signer 
await contract.connect(signer).callA();

// contract calling .callB function using the impersonated signer 
await contract.connect(signer).callB();
```

**Comment by fvictorio** [comment]
@0xdavinchee thanks for reporting this. Could you please try to reproduce this without `hardhat-deploy`, to check if it's a problem on our side or in the plugin side?

**Comment by 0xdavinchee** [comment]
@fvictorio hey I just tried reproducing this again without `hardhat-deploy` - that is, instead of loading the contract instance via a fixture, I loaded it the standard way:
```
  const contractFactory = await ethers.getContractFactory("Contract");
  const contract = await contractFactory.deploy(process.env.ADDRESS);
  await contract.deployed();
```
however I am still having the same issue where a random address is the caller of the contract.

**Comment by fvictorio** [comment]
Hey @0xdavinchee, I'm revisiting old issues and this one seems to me to no longer be happening. I believe this was a problem with ethers or hardhat-ethers that we fixed since then.

I'm going to close it now, but please let me know if it's still happening.
