### ISSUE TITLE
Add dark mode to the website

### ISSUE THREAD

**Issue by supafreq** [NomicFoundation/hardhat#1695]
Hurts my eyes- I'm sure I'm not alone.

Relevant website paths:
```
https://hardhat.org/getting-started/
https://hardhat.org/config/
https://hardhat.org/hardhat-network/
https://hardhat.org/guides/*
https://hardhat.org/advanced/*
https://hardhat.org/troubleshooting/*
https://hardhat.org/errors/*
https://hardhat.org/reference/*
https://hardhat.org/plugins/*
```

**Comment by alcuadrado** [comment]
Thanks for opening this issue, @supafreq. Unfortunately we won't have time to implement it in the near term.

**Comment by supafreq** [comment]
That's ok, as long as this issue is allowed to remain open then demand for it can be heard :)

**Comment by fvictorio** [comment]
We have dark mode now :partying_face:
