### ISSUE TITLE
hardhat-vyper plugin generates incompatible ABIs with typechain/ethers 

### ISSUE THREAD

**Issue by avele** [NomicFoundation/hardhat#1696]
Gas property in ABIs generated by the vyper compiler is `number` but typechain requires it to be `string`.

Reproduction steps: 
- basic hardhat setup
- `npm i @nomiclabs/hardhat-vyper`
-  `npm i @typechain/hardhat`
-  set up `hardhat.config.ts` and import install plugins
-  create some vyper contract in your project
-  create a script that imports generated types of vyper contract 
-  try to run the script
- should result in type error 
![image](https://user-images.githubusercontent.com/34437766/126337842-e1011d96-6ec4-45a7-bfda-7578ab9d2ef7.png)

**Comment by alcuadrado** [comment]
Hey @avele,

Shouldn't this be reported to typechain? Or is the `gas` property normally a string?

**Comment by avele** [comment]
@alcuadrado yeah, gas property is a string usually. Also in my experience gas property is rarely included in ABI, so as another solution you could provide an option to opt out adding it.

**Comment by penandlim** [comment]
Also encountering this issue with the latest typechain and vyper plugins for hardhat. I've created a ticket for typechain as well https://github.com/dethcrypto/TypeChain/issues/677

**Comment by frontier159** [comment]
This can be closed now

**Comment by fvictorio** [comment]
Thank you for the reminder @frontier159!
