### ISSUE TITLE
Update HH12 error message with a warning about windows

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#1713]
A lot of windows users are running into https://github.com/nomiclabs/hardhat/issues/1408 Since that issue is not easy to fix, we should at least update the error message to include a warning. I'm not sure about the text, but I guess it would be something like this:

> If you are on Windows, this might be caused by the shell you are using. Try using powershell or the Windows Subsystem for Linux (WSL) instead.

**Comment by aftermathdigital** [comment]
"Warning about windows", so sad that Windows' character is being assasinated by GitBash/mintty :(

Unfortunately, GitBash/mintty are giving windows a bad rep here by looking like a terminal to a user, but telling the applications they spawns that they're not a terminal: https://github.com/git-for-windows/git/wiki/FAQ#some-native-console-programs-dont-work-when-run-from-git-bash-how-to-fix-it

If you wanted to include an error message for these terminals specifically, it /could/ include the following workarounds:

`winpty bash "$(which npx)" hardhat`
`winpty bash "$(which npx)" hardhat init`

Which restore hardhat functionality with no patches.

**Comment by fvictorio** [comment]
> but that's really straying from HH and documenting other projects in your docs, which I appreciate you may not want to do.

I don't think it would hurt at all to be verbose and detailed in this particular error, since it's so annoying and common. Maybe this could be in some part of the site and the error message would show that URL, that way the output wouldn't be huge.

**Comment by alcuadrado** [comment]
I closed my failed attempt at fixing this :(

I'm almost convinced that we should copy what yarn does: https://github.com/yarnpkg/yarn/blob/master/bin/yarn

**Comment by alanhamid** [comment]
I found a way to avoid this issue by typing the commands in the following sequence.  I think it has something to do with when you install your Hardhat in the folder. 
I am creating my project in the directory called JACKPOT, and then I type the commands in the following order.  So far so good.  
Frist create your project folder and then switch to it: 
PS C:\Users\alanh> mkdir jackpot             
PS C:\Users\alanh> cd jackpot   
Then, start VS Code in that folder by typing the following command:  
PS C:\Users\alanh\jackpot> code .   
Then, add Hardhat to your projet and start the project: 
PS C:\Users\alanh\jackpot> yarn add --dev hardhat    
PS C:\Users\alanh\jackpot> yarn add --dev hardhat                                                                                                                                                                                                                                                     

Hope this helps. Cheers!

**Comment by fvictorio** [comment]
I'm going to close this issue, because we added that message to HH15 and it seems to have helped a lot. It seems like some users still run into HH12 now and then, but I don't have reproduction steps.
