### ISSUE TITLE
Secure account management

### ISSUE THREAD

**Issue by abarmat** [NomicFoundation/hardhat#1748]
I see many projects that rely on reading a mnemonic/private-key from the environment or an .env file using dotenv. The issue with that is that it is exposed on a file or bash and any other process can easily read.

We could have some type of account management like eth-brownie to keep accounts encrypted and unlock them whenever the user needs to sign. Having this feature can make it easier to then build hardware-wallet support on top.

Examples:
- https://github.com/aave/protocol-v2/blob/master/hardhat.config.ts#L32
- https://github.com/graphprotocol/contracts/blob/dev/hardhat.config.ts#L72

**Comment by zipzapzanigan** [comment]
+1 on this one
perhaps some sort of integration with https://www.hashicorp.com/products/vault ?

**Comment by fvictorio** [comment]
Closing this in favor of https://github.com/NomicFoundation/hardhat/issues/2265
