### ISSUE TITLE
Feature Request: Importing from a directory

### ISSUE THREAD

**Issue by zemse** [NomicFoundation/hardhat#1803]
## Use case

We have the following file structure:

```
interfaces
    IContractA.sol
    IContractB.sol
    index.sol
WorkingContract.sol
```

and index.sol contains:
```solidity
import { IContractA } from './IContractA.sol';
import { IContractB } from './IContractAB.sol';
```

In the working contract:

```solidity
// this errors
import { IContractA, IContractB } from './interfaces';

// this works
import { IContractA, IContractB } from './interfaces/index.sol';
```

The purpose of putting an index.sol inside a directory could be to remove a lot of imports in working contracts and it looks clean and more readable if one has a lot of contracts/interfaces/libraries they're importing. Very similar to index.js/ts.

The feature request is: It'd be great if we could autofill `/index.sol` part if one is importing from a directory.

**Comment by cameel** [comment]
There was a similar idea proposed by @frangio in OpenZeppelin at some point: https://github.com/OpenZeppelin/openzeppelin-contracts/issues/1607.

I just wanted to note that there are pretty important caveats if this were to be implemented in a naive way, by putting the content of `index.sol` under two different names (`interfaces/index.sol` and `interfaces` in Standard JSON input. The problem can be avoided by using the [import remapping](https://docs.soliditylang.org/en/latest/path-resolution.html#import-remapping) mechanism in the compiler. See https://github.com/OpenZeppelin/openzeppelin-contracts/issues/1607#issuecomment-870961978 for details.
