### ISSUE TITLE
feature request: support for read-only fs like AWS Lambda

### ISSUE THREAD

**Issue by campionfellin** [NomicFoundation/hardhat#1804]
#### Reasoning

I see you support a number of other CI systems (code [here](https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/src/internal/util/ci-detection.ts#L4-L18)).

I know that Lambda is not really a CI tool, so-to-speak, but we have a use case for generating and compiling contracts on-the-fly in response to client requests. This is essentially the flow:

* Client enters in contract name, symbol, etc
* Backend fills out template file with that info, the runs `npx hardhat compile` and returns the ABI and Bytecode.

There's a number of issues I ran into while implementing this, and I think the `hardhat` library could probably fix fairly easily on your side of things.

1. The Lambda container is a read-only file system (but does give you access to write under the `/tmp/` directory. That being said, the code for the app gets mounted at `/var/task/`.

Since we need to write the `.sol` files as clients make requests, we write them to the `/tmp` directory. However, hardhat won't let us compile if that is different than the directory the node modules was installed in. For example:

```js
// inside of /tmp directory
execSync(`cd /tmp/ && node /var/task/node_modules/hardhat/internal/cli/cli.js compile --verbose --config ./hardhat.config.js`, {stdio: 'inherit'})
```

This fails with [HH12](https://hardhat.org/errors/#HH12) that hardhat is not installed locally.

To get around this, we must copy the `node_modules` into `/tmp` for each request.

```js
execSync(`cp -r /var/task/node_modules /tmp/`)
```

This is manageable, but does add more latency to the request.

The next error is a bit trickier, and let me to one of your dependencies. When you are ensuring the directory (I think for telemetry?) [here](https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-core/src/internal/util/global-dir.ts#L21) it tries to write to something like `/home/user_123`.

To get around this, I found in that `env-paths` dependency [here](https://github.com/sindresorhus/env-paths/blob/main/index.js#L40-L44), you can set environmental variables to specify which path, so I put that to `/tmp` and it worked.

---

I guess as far as concrete proposals go - here is what I think would be nice

1. CLI flag to ignore the "local installation" error, especially if I am running it with the full path.
2. For the issue with the dependency and the `ensureDir()` call I am thinking perhaps there can be a way to turn off telemetry so it doesn't even attempt to do this? I am not sure though, that one is a bit tougher.

---

Please let me know if you need any more info or if you want to chat! Thanks :)

**Comment by fvictorio** [comment]
> CLI flag to ignore the "local installation" error, especially if I am running it with the full path.

I don't think this is something we want to do, since the assumption of a local installation is important. I think that you can accomplish what you want (compiling contracts that are outside the project) by overriding some compilation subtasks. This isn't easy, but it's not that hard either. But I don't know if this would make sense for your particular use case. The main question is if you can modify the hardhat config to make this change.

> For the issue with the dependency and the `ensureDir()` call I am thinking perhaps there can be a way to turn off telemetry so it doesn't even attempt to do this? I am not sure though, that one is a bit tougher.

This isn't the first time someone reports that this part of the telemetry check is causing issues. I think we just need to make that part more robust.

**Comment by campionfellin** [comment]
What is the definition of local for hardhat? I would have thought specifying a full path on the machine is local enough. I ended up getting it working, but we decided to go another route besides Lambda for other reasons.

Let me know if you end up making fixes for the telemetry! Feel free to close this for now as it's not a super pressing issue. Thanks for all the help and building such a great tool :)

**Comment by fvictorio** [comment]
> What is the definition of local for hardhat?

Installed with, for example, `npm i hardhat` instead of using a Hardhat version installed with `npm i -g hardhat`.

> Feel free to close this for now as it's not a super pressing issue.

I think we should keep this open, because our fs code should be more robust in scenarios like this
