### ISSUE TITLE
bsc network ProviderError: missing trie node

### ISSUE THREAD

**Issue by itoukaijiE** [NomicFoundation/hardhat#1825]
[#1236](https://github.com/nomiclabs/hardhat/issues/1236) has been closed so i would like to talk about it here.
when using fork(especially pinning block) from some non-archive node, it may fail to call some contract method if requiring some historical data. however, if without pinning block, it is supposed to call method successfully as the node has recently block state. actually in bsc it behave unexpected, even not using pinning block and get of error of 
```
bsc network ProviderError: missing trie node
```
this problem seems only occur in bsc.

**Comment by fvictorio** [comment]
@itoukaijiE does my comment [here](https://github.com/nomiclabs/hardhat/issues/1236#issuecomment-905668238) answers this?
