### ISSUE TITLE
Explore webpack packaging

### ISSUE THREAD

**Issue by alcuadrado** [NomicFoundation/hardhat#184]
We should explore packaging Buidler with webpack before releasing it. [Zeit's ncc](https://github.com/zeit/ncc) is a good example of how to do it, but it's focused on single-entrypoint projects.

This has many advantages (like faster and reproducible installations), but doing it right and keeping our performance optimizations may not be easy.

**Comment by fvictorio** [comment]
Is this still something you want to do?
