### ISSUE TITLE
Feature request: programmatically stop a hardhat node

### ISSUE THREAD

**Issue by 0xdavinchee** [NomicFoundation/hardhat#1879]
I have a use case where I am implementing a CI script on Github Actions which will test a subgraph I have implemented, the steps:
- npx hardhat node
- run deploy contract scripts
- checkout/clone graph-node repo
- cd docker and run docker-compose-up
- prepare, build and deploy local subgraph
- run tests
- kill node

there is currently no way to kill the node as killing the pid wouldn't kill the node according to @fvictorio

**Comment by fvictorio** [comment]
> there is currently no way to kill the node as killing the pid wouldn't kill the node according to @fvictorio

To clarify this, I mean that this shell idiom doesn't work:

```bash
npx hardhat node &
PID=$!
# do stuff
kill $PID
```
