### ISSUE TITLE
Calling any view method on a contract deployed with "hardhat_setCode" return an empty string

### ISSUE THREAD

**Issue by paulrberg** [NomicFoundation/hardhat#1883]
## Description

I am doing the following things to deploy a contract with the [hardhat_setCode](https://hardhat.org/hardhat-network/reference/#hardhat-setcode) JSON-RPC method:

1. Deploy a contract the usual way (via the `CREATE` opcode) with [waffle.deployContract](https://github.com/paulrberg/hardhat-set-code-bug/blob/26d9775121ba31e3361aa2f969a10283d0cac4b4/test/greeter/Greeter.ts#L22)
2. Load the runtime bytecode of that contract into a variable via `getCode`
3. Set the runtime bytecode at a custom address
4. Re-create the ethers.js contract at the custom address used in step 3

When I attempt to call a view method on this contract, I am getting only empty strings back. That makes my tests fail:

> AssertionError: expected '' to equal 'Hello, world!'

## Steps to Reproduce

1. Clone https://github.com/paulrberg/hardhat-set-code-bug
2. Install dependencies with `yarn install`
3. Create a `.env` file by following the `.env.example`
4. Generate TypeChain bindings via `yarn typechain`
5. Run `yarn test`

To make the tests pass, you can uncomment [line 35](https://github.com/paulrberg/hardhat-set-code-bug/blob/26d9775121ba31e3361aa2f969a10283d0cac4b4/test/greeter/Greeter.ts#L35).

## Environment

- hardhat@2.6.2

**Comment by paulrberg** [comment]
Just tried with Hardhat v2.6.4 and I got the same result.

**Comment by alcuadrado** [comment]
This is pretty odd, as we have a test that (tries to) verify this. We'll dig deeper into this. Thanks, @paulrberg

**Comment by paulrberg** [comment]
This might still be relevant @alcuadrado @fvictorio. Might be worth it to re-open the issue if the behavior hasn't been patched.

**Comment by fvictorio** [comment]
The problem here is that the expected response is part of the state of the contract, set during deployment, and not part of the code. So the bytecode is copied, but the state of the `greet` state variable is empty.

We should have an easy way to do this, like the `hardhat_copyAccount` method suggested in https://github.com/NomicFoundation/hardhat/issues/2718.
