### ISSUE TITLE
Invalid gas used when interacting through providers created by hand 

### ISSUE THREAD

**Issue by krzkaczor** [NomicFoundation/hardhat#1894]
If a user creates ethers providers (ex. connected to the mainnet) rather than specifying networks in hardhat configs wrong `gasLimit` is used. 

## Repro:
0. Have no networks configured in hardhat config.
1. Call `getContractAt` with provider connected to mainnet.
2. Sending any tx using returned contract will have super high `gasLimit`. This happens because HH will assume that it's connected to local devnet and will execute this [`addGasToAbiMethodsIfNecessary`](https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-ethers/src/internal/helpers.ts#L310).

More context: https://twitter.com/krzKaczor/status/1440293100082008064

## Solution:

If a network id from the provider doesn't match the one from the network config do not add gas to ABI methods. 

I can work on a fix if you agree that this is the right solution.

**Comment by fvictorio** [comment]
> If a network id from the provider doesn't match the one from the network config do not add gas to ABI methods.

This doesn't feel quite right to me. It would mean iterating over all networks and getting their network ids...

What about checking if the signer's provider is equal to `hre.ethers.provider`? I'm not sure how robust that would be though, because it would be a comparison by reference and there might be some false negatives.

**Comment by krzkaczor** [comment]
> What about checking if the signer's provider is equal to hre.ethers.provider? I'm not sure how robust that would be though, because it would be a comparison by reference and there might be some false negatives.

It could check chain id instead of reference equality.

**Comment by alcuadrado** [comment]
@krzkaczor do you mean that hardhat-ethers is changing the gasLimit even if the network's name is not hardhat?

**Comment by fvictorio** [comment]
@krzkaczor friendly ping
