### ISSUE TITLE
No name field in outputs section of an ABI causes INVALID_ARGUMENT exception

### ISSUE THREAD

**Issue by aliveli186** [NomicFoundation/hardhat#1901]
There is no `name` field specified in the following ABI which raises the exception:
`INVALID_ARGUMENT: invalid type (argument="type", value="u", code=INVALID_ARGUMENT, version=abi/5.0.7)`

I extract the ABI as follows and make the call over MetaMask:
```
  const MyToken = await hre.ethers.getContractFactory("MyToken");
  const MyAbi = MyToken.interface.format("json");
```

```
  {
    "type": "function",
    "name": "allowance",
    "constant": true,
    "stateMutability": "view",
    "payable": false,
    "inputs": [
      {
        "type": "address",
        "name": "owner"
      },
      {
        "type": "address",
        "name": "spender"
      }
    ],
    "outputs": [
      {
        "type": "uint256"
      }
    ]
  }
```

I compared the truffle generated ABI and found out that they add an empty `name` field even if it is not specified and when I manually added the `name` field to the ABI it worked.
```
  {
    "type": "function",
    "name": "allowance",
    "constant": true,
    "stateMutability": "view",
    "payable": false,
    "inputs": [
      {
        "type": "address",
        "name": "owner"
      },
      {
        "type": "address",
        "name": "spender"
      }
    ],
    "outputs": [
      {
        "type": "uint256",
        "name": ""
      }
    ]
  }
```
Could you please fix this with your generated ABIs to be more compatible?

**Comment by alcuadrado** [comment]
hey @aliveli186, this error message doesn't seem to be related to what you are describing.

Can you provide a reproduction script? Thanks
