### ISSUE TITLE
.solhintignore is not utilised in hardhat-solhint plugin

### ISSUE THREAD

**Issue by outdoteth** [NomicFoundation/hardhat#1903]
As per this line https://github.com/nomiclabs/hardhat/blob/master/packages/hardhat-solhint/src/index.ts#L88 the .solhintignore file is never read. `npx hardhat check` will run solhint using all files in the `config.paths.sources`.

Reproduce:

```
## .solhintignore
MyContract.sol
```

```
npx hardhat check
```

```
// output showing errors for MyContract.sol
```

**Comment by alcuadrado** [comment]
Thanks for reporting this, @Dylan-Kerler! This plugin needs to be updated. We'll get back to this issue once we have enough time to do it.

**Comment by ernanirst** [comment]
Hey @alcuadrado, just pinging this thread to stay active. I would love support for this too

**Comment by Rotemy** [comment]
Any news about this?
