### ISSUE TITLE
Hardhat couldn't infer error reason - random revert behaviour

### ISSUE THREAD

**Issue by 0xTimepunk** [NomicFoundation/hardhat#1904]
Hi!

I am receiving the following issue randomly when I call the borrow function on `LendingPool.sol` in my tests on an aave fork with some architectural changes. The error happens next to the emit Borrow event as you can see by the picture:

![image](https://user-images.githubusercontent.com/45543880/134660064-d7e5b4f7-3876-4c3b-8be1-19a651a6a175.png)

Copy paste of the message for context:
```
  Error: Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.
      at LendingPool._sendLogPayload (hardhat/console.sol:12)
      at LendingPool.log (hardhat/console.sol:173)
      at LendingPool._executeBorrow (contracts/protocol/lendingpool/LendingPool.sol:934)
      at LendingPool.borrow (contracts/protocol/lendingpool/LendingPool.sol:269)
      at InitializableImmutableAdminUpgradeabilityProxy._delegate (contracts/dependencies/openzeppelin/upgradeability/Proxy.sol:41)
      at InitializableImmutableAdminUpgradeabilityProxy._fallback (contracts/dependencies/openzeppelin/upgradeability/Proxy.sol:70)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async HardhatNode._mineBlockWithPendingTxs (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1582:23)
      at async HardhatNode.mineBlock (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:435:16)
      at async EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1494:18)
      at async HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:108:18)
      at async EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

And the same error, without using hardhat/console.sol (again, doesn't pop everytime so have to re-run tests many times to trigger it). It shows as if the error comes in the Borrow emit event.

![image](https://user-images.githubusercontent.com/45543880/134661524-da5f9113-8f89-4c40-9b88-359fc99e4a26.png)

This seems related to #1320 , but due to its random behavior (doesn't happen on every test run) I can't really find the true source of the problem. 

One note is that our contract code is almost next to the size limit and our tests do multiple borrows in rapid succession when this happens (a batch of 5 times 4 in this test suite). When the issue appears it usually happens next to the 4th or 5th borrow in that batch (we use a for loop in the tests to call borrow). Could there be some limit on hardhat itself to the event logs that are produced? We are using the latest hardhat version '2.6.4' if it helps.

This is hindering our CI/CD implementation so if there's anything I can do on my side to support solving or reproducing it better, let me know!

Thank so so much

**Comment by alcuadrado** [comment]
Hey @0xTimepunk,

Can you provide us with steps to reproduce this? It does seem to be a bug on our end. Maybe an ill-reported out of gas

**Comment by 0xTimepunk** [comment]
> Hey @0xTimepunk,
> 
> Can you provide us with steps to reproduce this? It does seem to be a bug on our end. Maybe an ill-reported out of gas

Hey @alcuadrado I would need to invite you to our repo as it is private as I think any steps I write here won't be very helpful. Should probably have a 1-1 call with you. Can I reach you via email? Thanks

**Comment by 0xTimepunk** [comment]
@alcuadrado we have tried to contact you via your visible email on github but perhaps you have not seen our message. Let me know if you have some other preferred way of doing this. Thanks

**Comment by Joe-mcgee** [comment]
Just had a similar thing happen to me  I have the github repo here https://github.com/Sigmadex/v0-proto 

When doing 
``npx hardhat node``
with the config
```mining: {
    auto: true
}
```
running the script `` npx hardhat run scripts/deploy.js --network localhost``
and than
``npx hardhat run scripts/scaffold-testnet.js --network localhost``

it performs as intended, as it does in ganache-cli (both with 0 blockTime and non-zero blockTime)

However, If I set
``mining: {
    auto: false,
    interval: 618
}
``
I get a similar error.  I added many console logs to attempt to locate the bug, but, like this issue, it fails at random points.  

I hope this helps

**Comment by abazlinton** [comment]
> Hey @0xTimepunk,
> 
> Can you provide us with steps to reproduce this? It does seem to be a bug on our end. Maybe an ill-reported out of gas

I get exactly the same error again when doing `console.log` - Tenderly says it's an out of gas error...but I'm not using much gas - it seems as if the console.log might itself be using up all the gas...?

**Comment by 0xTimepunk** [comment]
> > Hey @0xTimepunk,
> > Can you provide us with steps to reproduce this? It does seem to be a bug on our end. Maybe an ill-reported out of gas
> 
> I get exactly the same error again when doing `console.log` - Tenderly says it's an out of gas error...but I'm not using much gas - it seems as if the console.log might itself be using up all the gas...?

Adding @gretzke to this conversation

**Comment by tushargargght** [comment]
Any resolution on this yet? I am having the same problem.

**Comment by azerpas** [comment]
Same issue here while trying to deploy a `Governor` after deploying my `TimelockController` and `ERC20Votes` token.
