### ISSUE TITLE
"call revert exception" when interval mining is enabled on forked mainnet.

### ISSUE THREAD

**Issue by aliveli186** [NomicFoundation/hardhat#1905]
When I enable interval mining I receive the following error, when interval mining is disabled there is no error.

```
    hardhat: {
      forking: {
        url: eth_mainnet.url,
      },
      mining: {
        auto: false,
        interval: [3000, 4000]
      }
    }
```

```
Error: call revert exception (method="balanceOf(address)", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.4.1)
    at Logger.makeError (G:\solidity\node_modules\@ethersproject\logger\src.ts\index.ts:225:28)
    at Logger.throwError (G:\solidity\node_modules\@ethersproject\logger\src.ts\index.ts:237:20)
    at Interface.decodeFunctionResult (G:\solidity\node_modules\@ethersproject\abi\src.ts\interface.ts:425:23)
    at Contract.<anonymous> (G:\solidity\node_modules\@ethersproject\contracts\src.ts\index.ts:332:44)
    at step (G:\solidity\node_modules\@ethersproject\contracts\lib\index.js:48:23)
    at Object.next (G:\solidity\node_modules\@ethersproject\contracts\lib\index.js:29:53)
    at fulfilled (G:\solidity\node_modules\@ethersproject\contracts\lib\index.js:20:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'balanceOf(address)',
  errorArgs: null,
  errorName: null,
  errorSignature: null,
  address: '0x1Dc72ec89C9a103cbbCa816C9e5852947DAfA8e3',
  args: [ '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266' ],
  transaction: {
    data: '0x70a08231000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266',
    to: '0x1Dc72ec89C9a103cbbCa816C9e5852947DAfA8e3',
    from: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
  }
}
```

**Comment by alcuadrado** [comment]
Hey @aliveli186,

Can you please provide more info on how to reproduce this?

Note that if you are using interval mining you need to wait for your contract's deployment to be mined before calling it.

**Comment by aliveli186** [comment]
@alcuadrado I deploy the contracts first and later calling some methods on them from another script, all calls are awaited.
I'm sure they are deployed because I'm using their addresses when calling methods on them.
There are bunch of methods I'm calling and this balanceOf() is the one of last methods inside the script.
Unfortunately I don't know a way to reproduce it without the full code.
If I learn more will write.

**Comment by gabrielsdev** [comment]
I got this error too. Did you find how to solve it?

**Comment by aliveli186** [comment]
@gabrielsdev Yes, I found a way.
1) Remove the "mining" block from "hardhat.config.js" under "networks/hardhat".
2) Run the following script after deploying and initializing the contracts which manually starts the auto miner.

```
const hre = require("hardhat");

async function main() {
  await network.provider.send("evm_setAutomine", [false]);
  await network.provider.send("evm_setIntervalMining", [3000]);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
```

**Comment by gabrielsdev** [comment]
Thanks! My problem was different, the contract I'm using couldn't get the chainId of the network, so the contract revert when i tried to call the function.

**Comment by algorithmical** [comment]
@gabrielsdev  @aliveli186 
I am not interval mining. I am able to use the hardhat boilerplate to interact with that token.
When I use an existing token, import its ABI and try to load the contract from its address, then use balanceOf, I get that error.

My metamask points to localhost hardhat because without it the boilerplate project fails.
How do I call balanceOf on existing ERC-20 tokens I didn't create?
