### ISSUE TITLE
Feature request: CustomErrors with Artifact + Interface

### ISSUE THREAD

**Issue by wei3erHase** [NomicFoundation/hardhat#1919]
When releasing a proyect, we're trying to provide the artifact and the interface, for the users to be able to deploy and run tests on their local network (without releasing the source code).

Deployed contracts work fine, but the errors received are no longer **CustomErrors**, but `Transaction reverted without a reason string` from a `<UnrecognizedContract>.<unknown>`.  So developers running tests will not be able know what's wrong with their test scenario.

Is there a way of providing the artifact and the interface (containing the CustomErrors) and make the feature work as expected?

**Comment by fvictorio** [comment]
I think ideally you should be able to just add some files with custom errors (even if they are not used by any of your contracts) so that Hardhat knows about them. That won't work right now because only "known" custom errors associated to the reverted contract will be used.

See also #1875.

**Comment by fvictorio** [comment]
Closing in favor of https://github.com/NomicFoundation/hardhat/issues/3486
