### ISSUE TITLE
Implement a "Quarantine" function or folder for unused scripts/contracts

### ISSUE THREAD

**Issue by daweth** [NomicFoundation/hardhat#1923]
Many times during development/testing I have some files I would like to momentarily stop using, or some unfinished test that I would not like to run during `hardhat test`. I propose including a functionality to stop the compilation or running of certain files as part of the `hardhat init`.

**Comment by fvictorio** [comment]
For tests, you can use mocha's `.skip`. For example, you can replace a `describe` with `describe.skip` to skip a full suite. Similarly, you can use `it.skip` to skip a single test.

With respect to compilation... that is somewhat harder. For the time being, I think there's a way to do that by overriding some subtasks. It's not very straightforward though. If there's enough interest (that is, more than one person wants to do that), I can make an example. or maybe a plugin.

**Comment by fvictorio** [comment]
For the record, here's an example of how to ignore contracts so that they are not compiled: https://github.com/fvictorio/hardhat-examples/tree/master/ignore-solidity-files

I'm gonna close this now since we are using #2306 to track this feature request.
