### ISSUE TITLE
InvalidInputError: sender doesnt have enough funds to send tx

### ISSUE THREAD

**Issue by beskay** [NomicFoundation/hardhat#1933]
If you run tests on an instance of Hardhat Network that forks mainnet, and connect to a wallet address that has less than ~4ETH via method: "hardhat_impersonateAccount", you cant send transactions, or interact with smart contracts, due to an InvalidInputError.

I uploaded a minimal github repo to reproduce this error. See the Readme for more details.
https://github.com/beskay/Hardhat_InvalidInputError

Network config in hardhat.config.js: 
`  networks: {
    hardhat: {
      chainId: 1337,
      forking: {
        url: API_MAINNET,
        blockNumber: 13365034,
      },
    },
  },`

Error i am getting:

` InvalidInputError: sender doesn't have enough funds to send tx. The max upfront cost is: 4347376125669711168 and the sender's account only has: 421233560000000000`

If you clone my repo you will be able to reproduce the exact same error.

If i connect to a different wallet with enough ETH in it, everything works. The weird thing is, after the transaction went through, the amount of gas i paid is normal, like a few bucks, but somehow hardhat still shows that i need more than 4ETH to even be able to send that transaction.

**Comment by viraj124** [comment]
@fvictorio  I am on Mac with node version `v12.6.0` & hardhat version `2.9.1` my hardhat config looks like this, I added a very low gas limit like @beskay mentioned  but I still get this issue in my before each block
```
    hardhat: {
      accounts: {
        mnemonic,
      },
      chainId: chainIds.hardhat,
      gas: 1800000,
    },
```
Any other workaround I can do, I already tried with hardhat version `2.9.3` but that did not make a difference

**Comment by fvictorio** [comment]
@viraj124 sadly that setting doesn't work if you are using ethers. You'll need to manually set the `gasLimit` override in the relevant transactions.

Alternatively, setting a low base fee per gas with `initialBaseFeePerGas` could help too. Try setting that value to `7` and see if that makes things work better.

**Comment by viraj124** [comment]
@fvictorio so the only option is override either of the values manually?

**Comment by fvictorio** [comment]
I mentioned another option in my answer. If the base fee per gas is low enough, then transactions won't cost that much and the default gas limit could be fine. I'm not 100% sure about this, but it's worth trying I guess.

**Comment by akkien** [comment]
Just for anyone's needs, in my case, the hardhat's default account balance (10000 ETH) is not enough. 

So I solved the issue by setting the default account balance to a higher value (1000000 ETH in my case). See: https://hardhat.org/hardhat-network/docs/reference#accounts
