### ISSUE TITLE
Forking Celo fails with error "RpcBlockWithTransactions"

### ISSUE THREAD

**Issue by YWAssetManager** [NomicFoundation/hardhat#1966]
```
hh node --fork https://forno.celo.org
Error HH604: Error running JSON-RPC server: Invalid JSON-RPC response's result.

Errors: Invalid value undefined supplied to : RpcBlockWithTransactions | null/sha3Uncles: HASH, Invalid value undefined supplied to : RpcBlockWithTransactions | null/difficulty: QUANTITY, Invalid value undefined supplied to : RpcBlockWithTransactions | null/gasLimit: QUANTITY, Invalid value undefined supplied to : RpcBlockWithTransactions | null/uncles: HASH Array
```

This might be related to #1207, which fixed the same error for Kovan and xDai.

**Comment by alcuadrado** [comment]
I think the issue here is different. Celo's txs are slightly different than Ethereum's, so they fail to be parsed. We'll investigate this further, but we can't promise we'll fix it.

**Comment by mbare0** [comment]
Hi! Any updates on this issue?

**Comment by piersy** [comment]
@mbare0 This looks like the problem is caused by a different block header structure in celo compared with ethereum, the celo block header does not have the uncles, gasLimit or difficulty fields.

This is something we are looking at addressing starting with ethers.js
* https://github.com/celo-org/celo-blockchain/issues/1945

We are still investigating how to handle this best and it may be that we never reach parity with ethereum so in the meantime I think the best bet would be to fork hardhat to allow it to not require those fields.

**Comment by sashaaldrick** [comment]
> @mbare0 This looks like the problem is caused by a different block header structure in celo compared with ethereum, the celo block header does not have the uncles, gasLimit or difficulty fields.
> 
> This is something we are looking at addressing starting with ethers.js
> 
> * [Celo RPC API is incompatible with ethers.js celo-org/celo-blockchain#1945](https://github.com/celo-org/celo-blockchain/issues/1945)
> 
> We are still investigating how to handle this best and it may be that we never reach parity with ethereum so in the meantime I think the best bet would be to fork hardhat to allow it to not require those fields.

This is preventing us from deploying on Celo/Alfajores as we require local hardhat forking/ethers compatibility for testing and security checks. Any chance you know anyone over at celo who is working on this at the moment?

**Comment by piersy** [comment]
@sashaaldrick I am currently working at Celo, this is on our radar but we are not currently working on resolving this.

**Comment by roadbuilder** [comment]
so can't use ethersjs?

**Comment by aspiers** [comment]
Could https://github.com/celo-tools/celo-ethers-wrapper help fix this?

Also, @ricmoo mentioned that [things should get better in ethers v6](https://github.com/ethers-io/ethers.js/discussions/2919#discussioncomment-2689080).

**Comment by 0xged** [comment]
any update on this anyone? my integration tests are crying 💀

**Comment by lopeselio** [comment]
`Error HH604: Error running JSON-RPC server: Invalid JSON-RPC response's result.

Errors: Invalid value undefined supplied to : RpcBlockWithTransactions | null/sha3Uncles: HASH, Invalid value undefined supplied to : RpcBlockWithTransactions | null/difficulty: QUANTITY, Invalid value undefined supplied to : RpcBlockWithTransactions | null/uncles: HASH Array`

One of the developers on Celo discord was facing this error! Is it resolved @piersy ?

**Comment by fvictorio** [comment]
Hi, I think this will be fixed when we solve https://github.com/NomicFoundation/hardhat/issues/3590. Please follow that issue and if after we release a fix for it this is still a problem, then please opena a new issue. Thanks!
