### ISSUE TITLE
Add the ability to deploy to networks behind a Corporate HttpProxy 

### ISSUE THREAD

**Issue by furkilic** [NomicFoundation/hardhat#1978]
# SUMMARY

Hi everyone

Being behind a Corporate HttpProxy, I'd like to add the feature to deploy/interact with networks by using standard environment variables : `HTTPS_PROXY` or `HTTP_PROXY` .

This feature is really similar to https://github.com/nomiclabs/hardhat/pull/1291.

 # How to reproduce
```
# be behind a httpproxy
export HTTPS_PROXY=http://proxy.com
npx hardhat run --network external-network scripts/deploy.js
# Fail as not reachable
```
# Expected Result
```
# be behind a httpproxy
export HTTPS_PROXY=http://proxy.com
npx hardhat run --network external-network scripts/deploy.js
# Deploy Great Success !!!!
```

**Comment by mhorsley30896** [comment]
Will this fix enable mainnet forking behind proxy?

**Comment by star001007** [comment]
+1

**Comment by JetCyC** [comment]
+1
