### ISSUE TITLE
custom-errors not identified on the first test execution

### ISSUE THREAD

**Issue by leomassazza** [NomicFoundation/hardhat#1996]
### Issue description
Testing contracts with `custom-errors` under certain conditions will miss the custom-contract description.

### Context
This test is run via CI on a system that is deployed automatically where the deployment process involves updating some contracts and recompiling them.

The test (and deployment) involves the following steps:

1. Create a snapshot
2. Deploy the system (upgrading/changing some contracts and compiling them)
3. Deploy some contracts (part of the tests)
4. Execute the tests
5. Restore the snapshot

### Investigation done
Executing the test steps shown in **Context** will fail to detect the custom-contracts on the first run but will succeed on the following ones.

I reduced the error condition to, instead of taking the snapshot, just accessing `hre.ethers.providers` before compiling the new/updated contracts. (commenting out https://github.com/leomassazza/custom-errors/blob/main/test/sample-test.js#L16 will make the test pass)

### Reproduction Steps

You can find an complete example in this github repository (https://github.com/leomassazza/custom-errors) where this case is reproduced. You just need to checkout the repo, install the dependencies (npm install) and execute the tests removing any pre-created cache and artifacts.

execute: `rm -drf artifacts  cache && npx hardhat  test || npx hardhat test`

In fact, this command line will show that the first run will fail and will run it a second time where the tests will succeed. I added a console.log with the error picked by hardhat and there you can see the first run it shows:

`---> Revert message received from hardhat:  Error: Transaction reverted without a reason string
`

while the second one will show:

`---> Revert message received from hardhat:  Error: VM Exception while processing transaction: reverted with custom error 'SomeFancyError()'`

**Comment by ajsantander** [comment]
@fvictorio is there any progress with this? Anything we can do to help you better identify the issue and/or resolve it?

**Comment by fvictorio** [comment]
No progress yet, we'll try to prioritize this

**Comment by alcuadrado** [comment]
Sorry for the delay, @leomassazza, and thanks for the detailed reproduction script.

There are two things going on here:

1. The first one is a bug that I fixed locally. When hardhat network doesn't recognize a contract (i.e. it doesn't have its sources), it doesn't trace it. This lead to an incorrect `Transaction reverted without a reason string` message being used when `VM Exception while processing transaction: reverted with an unrecognized custom error` was the right one.

2. You are compiling some contracts after hardhat network gets initialized, so the contracts are not loaded. You can manually do that using `hardhat_addCompilationResult`, which takes the compiler version, input, and output.

**Comment by jefflau** [comment]
Any progress with this? I'm trying to add custom errors to one of our new ENS contracts and some of them work fine, some don't.

**Comment by JohnChangUK** [comment]
So this error comes up when you have custom errors defined in the contract, and Hardhat fails to recognise this when running unit tests locally against a hardhat node running on localhost:8545. The way I got around this was to run my tests using the `solidity-coverage` plugin: https://github.com/sc-forks/solidity-coverage

**Comment by JohnChangUK** [comment]
> > So this error comes up when you have custom errors defined in the contract, and Hardhat fails to recognise this when running unit tests locally against a hardhat node running on localhost:8545. The way I got around this was to run my tests using the `solidity-coverage` plugin: https://github.com/sc-forks/solidity-coverage
> 
> reporting some findings here. I was running in a similar case where tests were failing to parse custom errors but worked with `solidity-coverage`. It turned out it was because optimization runs were set to low on the compiler (coverage disable the optimizer).
> 
> I was using solc 0.8.4 and setting the optimizer runs value above 4400 fixed things (no idea why that threshold tho). Bumping solc version to 0.8.11 actually allowed me to keep the original (low) value in compiler runs and get custom errors working in tests.

Great investigation on this, appreciate the solution!
