### ISSUE TITLE
ProviderError: Method hardhat_mine not found  [Mining multiple blocks]

### ISSUE THREAD

**Issue by myuniswap2000** [NomicFoundation/hardhat#1998]
hello admin and everyone:
I have a problem：
（1） ProviderError: Method hardhat_mine not found  [Mining multiple blocks]
 (2) my version: 
     npx hardhat --version
    2.6.7
(3)my code:
const {network} = require("hardhat");
     await network.provider.send("hardhat_mine", [{
                blocks: 10,
                interval: 5
              }]);

thank you!!

**Comment by otr4v3z** [comment]
Is this available yet? It's in the [docs](https://hardhat.org/hardhat-network/reference/?#hardhat-mine), but i'm still getting the `MethodNotFoundError: Method hardhat_mine not found` error. 

Is there an alternative way of increasing the block number by 7000  blocks? I get a timeout error if I use `evm_mine` in a loop.

**Comment by fvictorio** [comment]
We haven't released this yet. We'll probably do it this week.

**Comment by senthilsamrat** [comment]
is it out yet?
