### ISSUE TITLE
Issue with hardhat node not creating the server right

### ISSUE THREAD

**Issue by gordo-labs** [NomicFoundation/hardhat#2019]
Hardhat node opens at

- Started HTTP and WebSocket JSON-RPC server at http://::1:8545/

It seems to be by using node v17 but happens as well in an arm64 terminal running node v12.

I just manage to make it work using rossetta-terminal and node v12, launching as well using node v17 with rossetta produces the same error.

**Comment by alcuadrado** [comment]
Hey @meta-sergio,

Can you provide more info so that we can reproduce this?

* Which OS and version are you using?
* Which exact node version
* Which terminal emulator
* Anything else you consider relevant

**Comment by neal-shah** [comment]
I'm getting the same issue - so I checked /etc/hosts yesterday and saw a `::1 localhost` entry.  Removing the entry and restarting `npx hardhat node` seemed to work.

However today when starting hardhat network I'm getting the same issue and I cannot see a `::1 localhost` entry in /etc/hosts - not too sure where it's getting this entry now.

**Comment by neal-shah** [comment]
So just realised, you override the hostname :)

```
npx hardhat node --hostname 127.0.0.1
```

Result:

```
Started HTTP and WebSocket JSON-RPC server at http://127.0.0.1:8545/
```

**Comment by fvictorio** [comment]
I'm not sure if this is something we fixed when we added support for node v18 or not. In any case, I'm going to tentatively close it. Please comment or open a new issue if you are running into a similar problem.
