### ISSUE TITLE
hardhat/console.sol `bytes` and `uint256[]` typed arguments support

### ISSUE THREAD

**Issue by MihanixA** [NomicFoundation/hardhat#2043]
Hardhat doesn't support logging `bytes` object to console via `hardhat/console.sol` though it might be useful in a huge amount of cases. 

I'd suggest printing `bytes` and `uint256[]` object as an array of numbers.

From a user perspective I don't think that implementing this feature could be technically difficult, but I could be wrong.

**Comment by fvictorio** [comment]
There is a `console.logBytes`, but I don't think we have a function for arrays.

With respect to adding an overload for `console.log(bytes)`, I guess that's doable? But maybe there is a good reason why there isn't one now.

**Comment by MihanixA** [comment]
@fvictorio Overload for bytes would be great. Also logging arrays would be very helpful

**Comment by alxiong** [comment]
seconded for overloading for bytes! 🙌

**Comment by fvictorio** [comment]
Sadly, overloading for bytes it's not possible, at least for now. The reason is that if we include that overload, then this statement wouldn't compile:

```solidity
console.log("abc")
```

because the compiler doesn't know if it should use `console.log(bytes)` or `console.log(string)`.

**Comment by sunny0714** [comment]
enum GameState {Opening, Waiting, Running}    
struct Pool {
        uint256 id;
        GameState state;
        uint256 tokenAmount;
        address[] players;
}
id and tokenAmount can be logged, but state and players can't be logged
that is, console.log(pool.state) or console.log(pool.players) are not working
Is there any way to deal with them?

**Comment by MihanixA** [comment]
> enum GameState {Opening, Waiting, Running}
> struct Pool {
> uint256 id;
> GameState state;
> uint256 tokenAmount;
> address[] players;
> }
> id and tokenAmount can be logged, but state and players can't be logged
> that is, console.log(pool.state) or console.log(pool.players) are not working
> Is there any way to deal with them?

There is no overload for `address[]` especially for your custom `GameState` enum. 
Try iterating through `address[]` array and log each one of them. 
As for `GameState` — try converting it to `uint`.

**Comment by nanaknihal** [comment]
It would also be great to support bytes32. Currently, bytes32 doesn't work for me in `console.logBytes`, nor `console.log`

**Comment by fvictorio** [comment]
@nanaknihal there is a `console.logBytes32` overload.

**Comment by kmjones1979** [comment]
would have been useful to have this when testing today. Writing this function doesn't seem to work.

    function keccakTest(address _address) public {
        bytes32 dHash = keccak256(abi.encodePacked(_address));
        console.log(bytes32(dHash));
        bytes32 aHash = keccak256(abi.encodePacked(address(_address)));
        console.log(bytes32(dHash));
    }

Perhaps I am not testing the correct way, but having bytes support in console.log seems to make sense to me.

**Comment by kmjones1979** [comment]
Ended up testing like this.

    function hashTestA() public view  returns (bytes32) {
        bytes32 prevHash = blockhash(block.number -1);
        uint256 nonce = diceGame.nonce();
        return keccak256(abi.encodePacked(prevHash, diceGame, nonce));
    }
    
    function hashTestB() public view  returns (bytes32) {
        bytes32 prevHash = blockhash(block.number -1);
        uint256 nonce = diceGame.nonce();
        return keccak256(abi.encodePacked(prevHash, address(diceGame), nonce));
    }

Side note: can anyone tell me why these hash function results match? I would expect them to be different.

**Comment by fvictorio** [comment]
@kmjones1979 see [this comment](https://github.com/NomicFoundation/hardhat/issues/2043#issuecomment-1047261161).

**Comment by developerjakesung** [comment]
> @nanaknihal there is a `console.logBytes32` overload.

such a big help!

**Comment by fvictorio** [comment]
I'm going to close this issue now because I don't think there's anything we can do, at least with the current capabilities of solidity.
