### ISSUE TITLE
Error: Transaction reverted and Hardhat couldn't infer the reason.

### ISSUE THREAD

**Issue by saicharanpogul** [NomicFoundation/hardhat#2045]
Same here.
```
...
   mapping(address => mapping(uint => Person)) private people;
   mapping(address => uint[]) private indexes;
...
   function addPerson(Person memory _person, uint8 _isPersonActive) public {
        // requires
        people[msg.sender][_person.personId] = _person;
        if(_isPersonActive == 2) { // some condition

            indexes[msg.sender].push(_person.personId); // <-- 1
        }
    }
...
```
I tried the marked line then I got the following error: ``` AssertionError: Returned error: Error: Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.```
The confusing part is I have some logic in another function that has almost similar functionality that worked, but in this function, it didn’t work.  (It is just a similar example to my code)

_Originally posted by @saicharanpogul in https://github.com/nomiclabs/hardhat/issues/2022#issuecomment-962677041_

**Comment by saicharanpogul** [comment]
When the gas is set to **450000** the transaction failed with the error: ``` AssertionError: Returned error: Error: Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.```
```
eth_sendTransaction
  Contract call:       <UnrecognizedContract>
  Transaction:         0xfaaf8b1ea04856e197a4f31a976b115ccbe71ca1bd5648d753d777c6eed33921
  From:                0x9965507d1a55bcc2695c58ba16fb37d819b0a4dc
  To:                  0x9e02f3a8567587d27d7eb1d087408d062b4c6a1c
  Value:               0 ETH
  Gas used:            443477 of 450000
  Block #171:          0x022346ae23fb46a56791bf3010defbfb505dc68f2c93ce83e4d282109fa398ef

  Error: Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.
```

And when the gas is set to **550000** the transaction got executed without error. 
```
eth_sendTransaction
  Contract call:       <UnrecognizedContract>
  Transaction:         0x9f12eb38792cb7218ccb49121eda3140a0a3fd6884d8ba15987f707cee9c39dc
  From:                0x9965507d1a55bcc2695c58ba16fb37d819b0a4dc
  To:                  0xc641b89a8d3d81151c6cd2f05fa593c95d2c1ffc
  Value:               0 ETH
  Gas used:            466401 of 550000
  Block #228:          0x2356eb4346fb1531f4fe093faeb596ddad07ee7e9a01e7ebf18a0f1de1fd50a1
```

Hardhat should throw low gas fees error when gas is set lower than used gas, but the error thrown was  ```AssertionError: Returned error: Error: Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.``` which made me clueless why the transaction was being rejected.

**Comment by jamiehewitt15** [comment]
Getting the same error `Error: Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.` while using hardhat `2.7.0` would be great to get a more specific error message

**Comment by fabianorodrigo** [comment]
I've received the same message. What is the best way to report details for Hardhat team? What should I send? Is there some log file that could help in this case?

**Comment by fvictorio** [comment]
This doesn't seem to be happening anymore, at least not with the provided snippet of code.

If someone is still running into this **and can provide minimal reproduction steps**, please open a new issue.
