### ISSUE TITLE
Inherit / reuse tasks

### ISSUE THREAD

**Issue by gnarvaja** [NomicFoundation/hardhat#2065]
It would be great to be able to inherit tasks, creating a new one that takes the definitions of the base class and adds new parameters or overrides something.

Like this: 

```javascript
  task("ens:baseTask", "Some task with some params")
    .addParam("param1", "Sample param 1", types.address)
    .addOptionalParam("param2", "Sample param 2", undefined, types.boolean)
    .setAction(actionFunction);

  task("ens:otherTask", "Inherist from baseTask and redefines some params", {inherits: "ens:baseTask"})
    .addParam("param3", "Sample param 3", types.address)
    .addOptionalParam("param2", "Redefines Sample param 2", undefined, types.boolean)
    .setAction(actionFunction2);
``` 

This will help a lot when we need some new parameters to customize existing tasks or in general.

**Comment by excalq** [comment]
Also removing required parameters. In my case, I'm adding a `verify` task that uses the locally saved deployment address.
