### ISSUE TITLE
Advanced-TypeScript-Sample-Project missing package.json

### ISSUE THREAD

**Issue by AtaTaheri** [NomicFoundation/hardhat#2068]
When initializing a hardhat project through these steps: 
- npx hardhat
- Create an advanced sample project that uses TypeScript

The sample project is fetched completely but the `package.json` file is missing.

**Comment by fvictorio** [comment]
This doesn't happen to me. Can you give us precise reproduction steps? What are you selecting for the different prompts, for example?

**Comment by saicoder** [comment]
I had the same issue, the package.json is created in the current working directory instead of the specified directory name. The solution for me was just to create a folder manually, cd into it, and run a hardhat with all default parameters

**Comment by fvictorio** [comment]
> instead of the specified directory name

What do you mean? We don't support specifying directory names. Do you mean that you did `npx hardhat my-hardhat-project` and expected things to be created there?

**Comment by saicoder** [comment]
No, I was thinking as an answer to the first question: 'Hardhat project root'. Let's say I'm in `~/tmp` and I run `npx hardhat`.
For question `Hardhat project root` I type `demo`. The hardhat files will be in  `~/tmp/demo` but package.json in `~/tmp`

**Comment by fvictorio** [comment]
> No, I was thinking as an answer to the first question: 'Hardhat project root'.

Ohh, I see, thanks for clarifying. To be honest, I don't know if this is expected behavior or not. @alcuadrado wdyt?

**Comment by AtaTaheri** [comment]
The exact reproduction steps: 
in command line: 
- `npx hardhat`
- `Create an advanced sample project that uses TypeScript`
-  Hardhat project root :  `sample-project`
-  Do you want to add a .gitignore? (Y/n) : `y`

**UPDATE**

Now that I am running it in the windows CMD (not in the IDE Terminal), I am getting this response at the end, specifying that I should install the dependencies manually : 

`You need to install these dependencies to run the sample project:
  npm install --save-dev "hardhat@^2.6.8" "@nomiclabs/hardhat-waffle@^2.0.0" "ethereum-waffle@^3.0.0" "chai@^4.2.0" "@nomiclabs/hardhat-ethers@^2.0.0" "ethers@^5.0.0" "@nomiclabs/hardhat-etherscan@^2.1.3" "dotenv@^10.0.0" "eslint@^7.29.0" "eslint-config-prettier@^8.3.0" "eslint-config-standard@^16.0.3" "eslint-plugin-import@^2.23.4" "eslint-plugin-node@^11.1.0" "eslint-plugin-prettier@^3.4.0" "eslint-plugin-promise@^5.1.0" "hardhat-gas-reporter@^1.0.4" "prettier@^2.3.2" "prettier-plugin-solidity@^1.0.0-beta.13" "solhint@^3.3.6" "solidity-coverage@^0.7.16" "@typechain/ethers-v5@^7.0.1" "@typechain/hardhat@^2.3.0" "@typescript-eslint/eslint-plugin@^4.29.1" "@typescript-eslint/parser@^4.29.1" "@types/chai@^4.2.21" "@types/node@^16.4.13" "@types/mocha@^9.0.0" "ts-node@^10.1.0" "typechain@^5.1.2" "typescript@^4.3.5"`
  
  Obviously, this is a little inconvenient.

**Comment by alcuadrado** [comment]
> > No, I was thinking as an answer to the first question: 'Hardhat project root'.
> 
> Ohh, I see, thanks for clarifying. To be honest, I don't know if this is expected behavior or not. @alcuadrado wdyt?

I'd say that this is a bug

**Comment by alcuadrado** [comment]
The sample project has been revamped so this is stale
