### ISSUE TITLE
Feature request: Add support for exporting Hardhat test results

### ISSUE THREAD

**Issue by hs2361** [NomicFoundation/hardhat#2071]
**Current situation:**
Hardhat supports writing tests using Waffle and Ethers.js as mentioned in the docs [here](https://hardhat.org/guides/waffle-testing.html). Waffle internally uses the Mocha test runner, and supports adding in Mocha configuration in the hardhat.config.js file as mentioned [here](https://github.com/nomiclabs/hardhat/tree/master/docs/config#mocha-configuration).

**The problem:**
However, since Waffle uses an older version of Mocha (specifically v7.1.2) as can be seen here
https://github.com/nomiclabs/hardhat/blob/70c8dd19540ec7e7f4527ec88d8046f7e5d9b9ea/packages/hardhat-waffle/package.json#L49
it is not possible to use newer features added into Mocha. Specifically the ability to export test results as JSON and then output the results to a file was added in with the release of [Mocha v9.1.0](https://github.com/mochajs/mocha/releases/tag/v9.1.0).

**Use case:**
Allowing the ability to use a different reporter for Hardhat tests and to export the test results separately would be a very useful feature for CI pipelines, where these test results can be uploaded and then processed to generate HTML test results (for example, using the [test-reporter GitHub Action](https://github.com/marketplace/actions/test-reporter) which supports Mocha test reports in JSON format). This could potentially make debugging failing Hardhat tests on CI pipelines much easier.

**Potential steps to add the feature**
Upgrading the version of Mocha used in Waffle to >= 9.1.0 would be one of the steps to add the ability to export test results with Mocha. However, other steps may be necessary depending on how the Mocha configuration has been implemented.

Looking forward to any suggestions or improvements from the community 😄

**Comment by fvictorio** [comment]
Just in case: you can run the tests using mocha directly. Check [this example](https://github.com/fvictorio/hardhat-examples/tree/master/parallel-tests)

Anyway, I think this issue is still relevant since it makes sense to want to pass something like a `--reporter` flag to the test task.

**Comment by fvictorio** [comment]
For the record: this is possible in the latest versions of hardhat. You just need to configure the reporter in your Hardhat config:

```
  mocha: {
    reporter: "json"
  }
```

You can also use an environment variable to configure it:

```
  mocha: {
    reporter: process.env.MOCHA_REPORTER ?? "spec"
  }
```

And then `MOCHA_REPORTER=json hh test`

There's no `--reporter` param yet; if someone wants that, please open a new issue with that feature request.
