### ISSUE TITLE
hardhat-etherscan no support for avalanche when pulling v 2.17(added support for avalanche)

### ISSUE THREAD

**Issue by Julian-dev28** [NomicFoundation/hardhat#2079]
To recreate:

Create an empty project

run `npm init`

run `yarn add --dev @nomiclabs/hardhat-etherscan`

open `node_modules/@nomiclabs/hardhat-etherscan/dist/src/network/prober.js`

See that there is no `_NetworkID_ `or `_networkIDtoEndpoints_` parameters for Avalanche

open `node_modules/@nomiclabs/hardhat-etherscan/src/network/prober.ts`

See that there is no `_NetworkID_` or `_networkIDtoEndpoints_` parameters for Avalanche

**Comment by fvictorio** [comment]
Hi @Julian-dev28. This is already implemented but we haven't released it yet. I think we'll probably make a new release on Tuesday. I'll leave a comment here when we do.

**Comment by Julian-dev28** [comment]
Ah I see. Thanks for the clarification!
