### ISSUE TITLE
eth_getBlockByNumber on forked instance: missing uncle hashes

### ISSUE THREAD

**Issue by vince91** [NomicFoundation/hardhat#2096]
Using hardhat mainnet forking, when calling `eth_getBlockByNumber` on a block with uncles, the response does not contain uncle hashes.

### Steps to reproduce:

1/ Fork mainnet

 `npx hardhat node --fork YOUR_NODE_URL --port 8666 --fork-block-number 13497486`

2/ Run Go snippet

```go
package main

import (
	"context"
	"fmt"
	"math/big"

	"github.com/ethereum/go-ethereum/ethclient"
)

func main() {
	client, _ := ethclient.Dial("http://localhost:8666")
	block, err := client.BlockByNumber(context.Background(), big.NewInt(13497486))
	if err != nil {
		panic(err)
	}
	fmt.Println("nbUncleHashes", len(block.Uncles()))
}
```

### Result

We get an error because that block has an uncle, but inside the response, the list of uncle hashes is empty.

https://github.com/ethereum/go-ethereum/blob/e761255ba7e19ec7c380f008f9035da3caa77994/ethclient/ethclient.go#L125

### Expected

Hardhat returns the list of uncle hashes and no error.

Related PR https://github.com/nomiclabs/hardhat/pull/1915

**Comment by alcuadrado** [comment]
Thanks @vince91! I was looking for a way to reproduce this

**Comment by alcuadrado** [comment]
I think that to fix this we would need to address your comment from #1915 and implement `eth_getUncleByBlockHashAndIndex`
