### ISSUE TITLE
Different behaviour in Hardhat forked mode than on mainnet

### ISSUE THREAD

**Issue by Bobface** [NomicFoundation/hardhat#2126]
There seems to be a bug in Hardhat's forked mode where a `call` is sometimes not executed when its return value is not used. At least that is my best guess for what's happening. I've created a repo to reproduce this bug here:

https://github.com/Bobface/hardhat-bug-report

It creates a small contract `Bug.sol` which just transfers 1 `WETH` to the `msg.sender` when it is called. When you run the unit test as described in the README, it succeeds. Interestingly however, comment-out the 20th line in `Bug.sol` (`revert(0, 0)` -> `//revert(0, 0)`) and you will see that when you run it again the unit test fails and the tokens did not get transferred, even though the `call` must have succeeded as we saw in the previous run.

**Comment by alcuadrado** [comment]
Are you sure this doesn't work the same in mainnet?

**Comment by Bobface** [comment]
Yes, I'm pretty sure this is not normal mainnet behaviour, since it would mean that when I make a `CALL` to another contract, state changes made in that other contract during the `CALL`  (e.g. `SSTORE`s) will only be commited if I do something with the success value pushed onto the stack after the `CALL` is completed. 

My best guess regarding the potential cause for this: In forked mode, Hardhat does not detect the external contract as "touched" after the transaction is complete *if I didn't use the success value*,  thus does not store the updated state locally, and subsequent read-only calls to it, such as `balanceOf`, will get passed through to the RPC which of course has the real chain state where nothing changed.

**Comment by alcuadrado** [comment]
The same behavior is present without forking, using WETH9 with the same compiler version and settings as the mainnet deployment.

Updated hardhat config:

```ts
import "@nomiclabs/hardhat-waffle";

/**
 * @type import('hardhat/config').HardhatUserConfig
 */
module.exports = {
  solidity: {
    compilers: [
      {
        version: "0.8.4",
      },
      {
        version: "0.4.19",
      },
    ],
  },
  networks: {
    hardhat: {
      loggingEnabled: true,
    },
  },
};
```

Updated test:
```ts
const { BigNumber } = require("ethers");
const { ethers, network, artifacts } = require("hardhat");
const { expect } = require("chai");

describe("Bug", () => {
  it("Bug", async () => {
    const LocalWeth = await ethers.getContractFactory("WETH9");
    const localWeth = await LocalWeth.deploy();

    const WETH_ADDRESS = localWeth.address;
    await localWeth.deposit({ value: ethers.utils.parseEther("100.0") });
    const [richWETHSigner] = await ethers.getSigners();

    // Deploy the bug contract
    const factory = await ethers.getContractFactory("Bug");
    const bug = await factory.connect(richWETHSigner).deploy();

    // Send 1 WETH to the buggy contract
    const IERC20 = await artifacts.readArtifact("IERC20");
    const weth = new ethers.Contract(WETH_ADDRESS, IERC20.abi, richWETHSigner);
    await weth
      .connect(richWETHSigner)
      .transfer(bug.address, ethers.utils.parseEther("1.0"));

    console.log(await weth.balanceOf(bug.address));

    // Call the buggy contract
    await richWETHSigner.sendTransaction({
      to: bug.address,
    });

    console.log(await weth.balanceOf(bug.address));

    // Get the WETH balance of the buggy contract after the call
    // It should be zero
    const balanceBefore = await weth.balanceOf(bug.address);
    expect(balanceBefore.toString()).to.equal("0");
  });
});
```

Weth.sol: https://etherscan.io/address/0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2#code

This may be a bug in ethereumjs. I'll dig deeper soon.

**Comment by Bobface** [comment]
Interesting that it also happens in non-forked mode. Thanks for having a look!

**Comment by alcuadrado** [comment]
Surprisingly, the test also fails with the `revert(0,0)` without forking.

**Comment by Bobface** [comment]
> Surprisingly, the test also fails with the `revert(0,0)` without forking.

There is a small issue with the updated test above, in that the mainnet WETH9 address is hardcoded into the `Bug` contract. Try this setup (with your updated Hardhat config) in non forked mode. It sends the address of the WETH9 contract in the calldata:

*Bug.sol*:
```
pragma solidity 0.8.4;

contract Bug {
    fallback() external {
        assembly {
            // Read the WETH address from calldata
            let weth := shr(0x60, calldataload(0x0))
            // Load the pointer to free memory
            let free_mem_ptr := mload(0x40)
            // Store the function signature for transfer(address,uint256)
            mstore(free_mem_ptr, 0xa9059cbb00000000000000000000000000000000000000000000000000000000)
            // Store the address of the recipient, msg.sender
            mstore(add(free_mem_ptr, 0x4), caller())
            // Store the amount of WETH to send, 10^18
            mstore(add(free_mem_ptr, 0x24), 1000000000000000000)
            // Execute the transfer function on the WETH contract 
            // with msg.sender as the recipient and 
            // 10^18 as the amount of WETH to send
            let r := call(gas(), weth, 0x0, free_mem_ptr, 0x44, 0x0, 0x0)
            // Check whether the call succeeded
            if eq(r, 0x0) {
                revert(0, 0)
            }
        }
    }
}
```

*Test*:
```
const { BigNumber } = require("ethers");
const { ethers, network, artifacts } = require("hardhat");
const { expect } = require("chai");

describe("Bug", () => {
  it("Bug", async () => {
    const LocalWeth = await ethers.getContractFactory("WETH9");
    const localWeth = await LocalWeth.deploy();

    const WETH_ADDRESS = localWeth.address;
    await localWeth.deposit({ value: ethers.utils.parseEther("100.0") });
    const [richWETHSigner] = await ethers.getSigners();

    // Deploy the bug contract
    const factory = await ethers.getContractFactory("Bug");
    const bug = await factory.connect(richWETHSigner).deploy();

    // Send 1 WETH to the buggy contract
    const IERC20 = await artifacts.readArtifact("IERC20");
    const weth = new ethers.Contract(WETH_ADDRESS, IERC20.abi, richWETHSigner);
    await weth
      .connect(richWETHSigner)
      .transfer(bug.address, ethers.utils.parseEther("1.0"));

    console.log(await weth.balanceOf(bug.address));

    // Call the buggy contract
    await richWETHSigner.sendTransaction({
      to: bug.address,
      data: WETH_ADDRESS
    });
    console.log(await weth.balanceOf(bug.address));

    // Get the WETH balance of the buggy contract after the call
    // It should be zero
    const balanceBefore = await weth.balanceOf(bug.address);
    expect(balanceBefore.toString()).to.equal("0");
  });
});
```

For me this results in the same behaviour as in forking: With the `revert(0,0)` the test passes. Without it, it fails. 

On a side note I also saw that the logs which are emitted by the WETH9 contract are missing in the transaction receipt when the `revert(0,0)` is commented out. Maybe that helps a bit with finding the root cause for this.
