### ISSUE TITLE
`ethers.getContractAt` should validate that the address is actually a contract

### ISSUE THREAD

**Issue by alcuadrado** [NomicFoundation/hardhat#2170]
`const myContract = await ethers.getContractAt("MyContract", addr);` should fail if `addr` does not belong to a contract.

**Comment by kanej** [comment]
@alcuadrado is the idea here to use something like ethers [getCode](https://docs.ethers.io/v5/api/providers/provider/#Provider-getCode) to verify there is contract code and warn otherwise?

**Comment by webdevabhijit** [comment]
@alcuadrado can I work in this issue if it is not assigned yet.

**Comment by alcuadrado** [comment]
> @alcuadrado is the idea here to use something like ethers [getCode](https://docs.ethers.io/v5/api/providers/provider/#Provider-getCode) to verify there is contract code and warn otherwise?

The former.

> @alcuadrado can I work in this issue if it is not assigned yet.

Sure! Thanks

**Comment by SfyMantissa** [comment]
@alcuadrado Hello!
Can I also join the current assignees?
I would really like to contribute. I am sure I can do this.

**Comment by kanej** [comment]
> @alcuadrado Hello! Can I also join the current assignees? I would really like to contribute. I am sure I can do this.

Unless @ethabhijit wants to shout, I think you can work on it. Thanks.

**Comment by feuGeneA** [comment]
Fixed via #2916

**Comment by fvictorio** [comment]
Fixed in [hardhat-ethers v2.1.1](https://github.com/NomicFoundation/hardhat/releases/tag/%40nomiclabs%2Fhardhat-ethers%402.1.1)
