### ISSUE TITLE
Vyper binary downloader can't handle >100 vyper releases

### ISSUE THREAD

**Issue by morgansliman** [NomicFoundation/hardhat#2184]
Currently the `hardhat-vyper` plugin is hardcoded to request the first 100 releases from the vyper github repo. This is fine for the time being as they aren't anywhere near 100 releases yet, but it should be refactored to handle a possibly paginated response from github.

Ideally it would aggregate all results from all pages returned from github before saving the `list.json` file.

**Comment by sambacha** [comment]
100 is the default github limit for unauthenticated requests

**Comment by morgansliman** [comment]
Correct. We're in the process of [updating our vyper plugin](#2160), so this is a ticket for once that update gets merged. 

Eventually we'll want to add the ability for the new code to handle paginated results from github (i.e. releases > 100). This is a ticket for that future development.

**Comment by sambacha** [comment]
> Correct. We're in the process of [updating our vyper plugin](#2160), so this is a ticket for once that update gets merged.
> 
> Eventually we'll want to add the ability for the new code to handle paginated results from github (i.e. releases > 100). This is a ticket for that future development.

heads up :O
