### ISSUE TITLE
Add the raw return data to our SolidityError class

### ISSUE THREAD

**Issue by alcuadrado** [NomicFoundation/hardhat#2211]
Hardhat Network throws a `SolidityError` class when an execution fails. We should add a field to it containing the raw returndata so that libraries can parse it.

See: #1882

**Comment by fvictorio** [comment]
@alcuadrado does https://github.com/NomicFoundation/hardhat/pull/2553 fix this?

**Comment by fvictorio** [comment]
Closing becaue I think the return data is now accessible in the returned error.
