### ISSUE TITLE
Unexpected "npx hardhat compile" error on start > "Carl Pilcher"

### ISSUE THREAD

**Issue by geode-main** [NomicFoundation/hardhat#2235]
When we are using hardhat for our contracts we faced with an infinite loop on terminal when we tried to update every package with 

```npm install```

weird texts in sample output can be seen here:
```
undefined
undefined
undefined
                                   !             H|H|H|H|H           H__________________________________             H|§|§|§|H           H|* * * * * *|---------------------|             H|§|∞|§|H           H| * * * * * |---------------------|             H|§|§|§|H           H|* * * * * *|---------------------|             H|H|H|H|H           H| * * * * * |---------------------|             H|H|H|H|H           H|---------------------------------|          ===============        H|---------------------------------|            /| _   _ |          H|---------------------------------|            (| O   O |)          H|---------------------------------|            /|   U   |          H-----------------------------------             |  =/  |           H              _..._/            H              _|I/|_            H      _______/| H |/_______    H     /           / /          H    |          | | /         |  H    |          ||o||          |  H    |    |     ||o||     |    |  H    |    |     ||o||     |    |  H   Carl Pilcher  
te sting tes ting testing  tes ti n g t esting te ҉ st i ng testing
testing te st ing t estin g t esting  testing testin g  tes ting 
testing  testing testing te sting testing  ҉ testing testing
...
```
> Notably there is a name in the output: "Carl Pilcher"

Issue resisted with different computers and node versions also on different terminals.

Afterwards, we tried to create a new hardhat example project and tested it with:
( choose Create an advanced sample project)
```
npm install --save-dev hardhat 
npx hardhat
npx hardhat compile
```
Issue resisted.

hardhat version : v2.8.2 
node version: v16.13.1
npm -v : 8.1.2

Please reproduce the issue and let us know how to fix it.

**Comment by geode-main** [comment]
Seems like the issue is about 
https://github.com/Marak/colors.js/issues/289

Which is dependent to:  
https://github.com/Marak/faker.js

**Comment by geode-main** [comment]
Please downgrade any "faker.js" dependency to faker@5.5.3 to fix the problem.

**Comment by jummy123** [comment]
Another workaround is adding the following to package.json
```
  "resolutions": {
    "**/colors": "1.4.0"
  }
```

**Comment by ChristopherTrimboli** [comment]
yeah can confirm same issue, `npm run compile` gives me this:
![Screenshot 2022-01-09 163040](https://user-images.githubusercontent.com/27584221/148707404-5681b8d2-a6bc-4d16-a810-a8f9035c8907.png)

**Comment by cgewecke** [comment]
I think this is actually coming from eth-gas-reporter (which depends on `colors` - an npm package that [broke over the weekend][1] as noted in comments above).

The latest release of hardhat-gas-reporter (1.0.7) patches it and pins colors to 1.4.0.   

AFAIK hardhat uses chalk & isn't directly affected by this bug. 

[1]: https://github.com/Marak/colors.js/commit/074a0f8ed0c31c35d13d28632bd8a049ff136fb6

**Comment by geode-main** [comment]
Yes, the issue is about gas reporter but still, hardhat needs to fix this and not be dependent to such failure on such a small task.

**Comment by cgewecke** [comment]
@geode-main For context this bug was introduced intentionally by the package maintainer and designed to cause problems for anyone who imported it at the file level. It broke hundreds of major projects across the node ecosystem and resulted in interventions by npm and github to roll back the package version and freeze the maintainer's OSS account. It's an unusual event.

The main issue thread in the repo is here: https://github.com/Marak/colors.js/issues/285

**Comment by ThePredators** [comment]
This is why even its not good practice, i add lock files to make sure right version are used not latest !
