### ISSUE TITLE
hardhat-etherscan verify not working on Moonbase Alpha

### ISSUE THREAD

**Issue by gtsui** [NomicFoundation/hardhat#2237]
Hi, when I try verifying my smart contracts on the moonbase alpha testnet using hardhat-etherscan plugin I'm getting error "Invalid API Key".
Not having any issues with this whenever deploying to ethereum testnets.
Is there any work being done on getting this supported? 
Thanks.

**Comment by alcuadrado** [comment]
Hey @gtsui,

Are you using the latest version of the plugin?

**Comment by gtsui** [comment]
Hi @alcuadrado 

I updated to the latest version - which should be @nomiclabs/hardhat-etherscan^3.0.0 if I'm not mistaken. Unfortunately still getting the same issue:

NomicLabsHardhatPluginError: Invalid API Key

The standard API key that I'm using on etherscan that works with the ethereum testnets is the correct one to use here right?

**Comment by gtsui** [comment]
Hello,

Any updates to this? Is moonbase alpha not supported yet or is there something wrong on my side?

**Comment by albertov19** [comment]
Hey @gtsui - check my answer here: https://github.com/nomiclabs/hardhat/pull/2046#issuecomment-1027638917 - Hope it helps

**Comment by gtsui** [comment]
Copying my reply from the other thread

> @lee-rand ahh you need to provide the API key with the following object (readme of the hardhat-etherscan package):
> 
> ```
> etherscan: {
>     apiKey: {
>         moonbaseAlpha: "YOUR_MOONBEAM_MOONSCAN_API_KEY",
>     }
>   }
> ```
> 
> Give it s shot and let me know if it worked. For the future, you should open a GitHub issue

@albertov19 Can unfortunately confirm that I tried this just now as well and still running into "Invalid API Key" as well. Using hardhat-etherscan v3.0.0

**Comment by npty** [comment]
any update on this?
