### ISSUE TITLE
Asserting revert reasons while using hardhat node with interval mining

### ISSUE THREAD

**Issue by kavsky02** [NomicFoundation/hardhat#2238]
I'm using the below code as an example to test assertions for transactions reverting with a specific error:

```
import {ErrorsTest} from "../../typechain";
import {SignerWithAddress} from "@nomiclabs/hardhat-ethers/signers";
import {getFixedGasSigners} from "../_helpers";
import ErrorsTestArtifact from '../../artifacts/contracts/ErrorsTest.sol/ErrorsTest.json';
import {waffle} from "hardhat";

const {deployContract} = waffle;
import {syncTime} from "../_syncTime"
import {solidity} from "ethereum-waffle";
import chai, {expect} from 'chai'
chai.use(solidity);

describe('Smart loan', () => {
before("Synchronize blockchain time", async () => {
await syncTime();
});

describe('Test ErrorsTest', () => {
    let contract: ErrorsTest,
        owner: SignerWithAddress

    before("deploy contract", async () => {
        [owner] = await getFixedGasSigners(10000000);
        contract = (await deployContract(owner, ErrorsTestArtifact)) as ErrorsTest;

    });

    it("should revert with a message - external function", async () => {
        await expect(contract.publicFunction()).to.be.revertedWith("Our error message - public");
    });

    it("should revert with a message - external function", async () => {
        await expect(contract.externalFunction()).to.be.revertedWith("Our error message - external");
    });


});
});
```

It works as expecred while using the **automining** setting for a hardhat node.
However when I switch to **interval mining** those tests no longer work as the transactions (from the test code perspective) do not revert.

Is it possible to use interval mining-enabled hardhat node for running tests (to be as close to (Avalanche) mainnet as possible) and still be able to use expect statements for making assertions about transactions' revert messages?

I've tried the same scenario on the Avalanche testnet (Fuji) and it is possible to obtain the revert message after waiting for the transaction receipt.

Thank you in advance for you support.

**Comment by zengxinhai** [comment]
I ran into the same problem.
