### ISSUE TITLE
Hardhat and localhost with node@17 results in `HH108: Cannot connect to the network`

### ISSUE THREAD

**Issue by trozler** [NomicFoundation/hardhat#2239]
Following up from this stackoverflow issue:

https://stackoverflow.com/questions/68513645/error-connecting-to-localhost-after-npm-hardhat-run

Today I bumped my node version to nodeV17.3.0 and immeidatly began experiencing issues with hardhat, when trying to test using localhost. 

I downgraded my version of node and everything worked well again. Is there a way to make hardhat compatible with node@17 ?

**Comment by mastermice** [comment]
+1

**Comment by feuGeneA** [comment]
There are some localhost-related fixes in the PR to add support for Node 18: https://github.com/NomicFoundation/hardhat/pull/2705
