### ISSUE TITLE
How to get more accounts for waffle tests?

### ISSUE THREAD

**Issue by StErMi** [NomicFoundation/hardhat#2262]
Hi there, 

I need to test my contracts with more than 500 users, which is the correct way to allow hardhat to generate more than 20 accounts with enough funds?

**Comment by dsmitchell** [comment]
I've tests with that many wallets, by using mainnet forking and hardhat_impersonateAccount.  e.g.

`
async function impersonate(account: string): Promise<SignerWithAddress> {
    await ethers.provider.send("hardhat_impersonateAccount", [account]);
    return ethers.getSigner(account)
}
`

Then in the test you can use the method like this:

`
 const onlyOwner = "Ownable: caller is not the owner"
 const { hacker } = await getNamedAccounts() // This is an example from .namedAccounts in hardhat.config
 const impersonatedSigner = await impersonate(hacker)
 await expect(myContract.connect(impersonatedSigner).someMethod()).to.be.revertedWith(onlyOwner)
 `

**Comment by fvictorio** [comment]
Hi, you can also use the `count` setting in the `accounts` section of the Hardhat Network config: https://hardhat.org/hardhat-network/reference/#accounts

Closing this for now, but let us know if that doesn't answer your question.

**Comment by m1cm1c** [comment]
For anyone coming across this: The documentation that @fvictorio linked to appears to have been moved to https://hardhat.org/hardhat-runner/docs/config#hd-wallet-config.
