### ISSUE TITLE
The node/recommended plugin in the advanced typescript template breaks eslint

### ISSUE THREAD

**Issue by ArshanKhanifar** [NomicFoundation/hardhat#2266]
# What's Wrong
The `node/recommended` plugin only does `js` import files, it complains with `node/no-missing-import` messages if the module is a typescript module. 

# Steps to Reproduce
1. make a new hardhat typescript project
2. make a new `hello.ts` file under `./scripts/hello.ts`
```
export const hello = () => console.log("hello");
```
3. import that file in the default `./scripts/deploy.ts` file:
```
import { ethers } from "hardhat";
import { sayshi } from "./sayshi";

async function main() {
// etc. etc.
```
4. At this point, my ide (Webstorm) complains: 

![image](https://user-images.githubusercontent.com/10492324/149679811-c02c197b-f666-44a3-baf2-f84749ee3e6b.png)
If you try running eslint, it will complain too... 

```
yarn eslint scripts/*.ts
# yada yada
/Users/arshankhanifar/hardhat-debug/scripts/deploy.ts
  7:23  error  "./hello" is not found  node/no-missing-import

✖ 1 problem (1 error, 0 warnings)
```

# Repo That Shows This
Here's a [repo that shows this](https://github.com/ArshanKhanifar/hardhat-bug-demo)

# Proposed Fix
Maybe use `plugin:@typescript-eslint/recommended` instead? That's what [nounsdao ](https://github.com/nounsDAO/nouns-monorepo/blob/master/.eslintrc.js#L9) is doing.

**Comment by ArshanKhanifar** [comment]
Sorry couldn't find the typescript template repo, so thought I'd put it here...

**Comment by vcheeney** [comment]
@ArshanKhanifar Thank you! I was experiencing a similar problem while importing the type of my token. Removing the _plugin:node/recommended_ plugin from the ESLint extends array resolved the linting issue.

**Comment by alcuadrado** [comment]
Thanks for opening this issue, @ArshanKhanifar.

**Comment by the-vampiire** [comment]
is this the intended behavior for a typescript project? can the codegen be updated to include the correct plugin?
