### ISSUE TITLE
In-process Hardhat Network can use a gas limit higher than the user's balance

### ISSUE THREAD

**Issue by molfar** [NomicFoundation/hardhat#2278]
I forked Polygon mainnet and tried to send all ethers from account and got an error:

`sender doesn't have enough funds to send tx. The max upfront cost is: 3690252990028643482 and the sender's account only has: 3690252390028643482`

There is definitely something wrong. Because I tried the same transaction at Polygon mainnet and it works as expected.

Here my sample code with ethers.js

```
provider
        .getBalance(w.address)
        .then((b) =>
          w.connect(provider).sendTransaction({
            to: sponsorAddress,
            value: b.sub(parseUnits("600", "gwei").mul(21_000)),
            gasPrice: parseUnits("600", "gwei"),
          })
        )
        .then((tx) => tx.wait())
        .then((rc) => [w.address, rc.transactionHash])
```

**Comment by alcuadrado** [comment]
Hey @molfar,

Have you impersonated an account?

**Comment by molfar** [comment]
@alcuadrado I run a fork with hardhat node. And then connected to it with separate ethers.js script. Account I tried to send ether **from** had positive balance **before** actual fork.

**Comment by alcuadrado** [comment]
Thanks for the explanation. I believe there's an off-by-one error somewhere.

**Comment by alcuadrado** [comment]
@molfar can you try explicitly setting the `gasLimit` to 21k?

**Comment by molfar** [comment]
@alcuadrado Just tried and it worked!

```
w.connect(provider).sendTransaction({
  to: sponsorAddress,
  value: b.sub(parseUnits("600", "gwei").mul(21_000)),
  gasPrice: parseUnits("600", "gwei"),
  gasLimit: 21_000,
})
```
