### ISSUE TITLE
hardhat verify command doesn't accept tuples/arrays as constructor arguments 

### ISSUE THREAD

**Issue by ewilz** [NomicFoundation/hardhat#2298]
Maybe I'm missing the correct instruction, but I was running the command 

```
npx hardhat verify $CONTRACT_ADDRESS ['0x15c3ee6ef9a83ce4fbb0621d6cf3b2692d7a6090','0xe7bec27f2b6ac5a16e8e8dc86ca54844b6422dfa']
```

But I noticed my argument was being stringified instead of being passed as an array:
```
// console.log(constructorArguments)
constructorArguments [
  "['0x15c3ee6ef9a83ce4fbb0621d6cf3b2692d7a6090','0xe7bec27f2b6ac5a16e8e8dc86ca54844b6422dfa']"
]
```

```
Error in plugin @nomiclabs/hardhat-etherscan: Value ['0x15c3ee6ef9a83ce4fbb0621d6cf3b2692d7a6090','0xe7bec27f2b6ac5a16e8e8dc86ca54844b6422dfa'] cannot be encoded for the parameter tuple
```

When I manually edited the code inside node-modules to make this argument an array instead of a string I was able to successfully verify my contract that accepts a struct in the constructor.

**Comment by itirabasso** [comment]
You can use `--constructor-args` from hardhat-etherscan and place your args on a .js/.ts file.

https://hardhat.org/plugins/nomiclabs-hardhat-etherscan.html#complex-arguments

**Comment by EduardoMeloDev** [comment]
thanks @itirabasso , this help me a lot !!!
