### ISSUE TITLE
Hardhat >2.7.1 breaks `ECDSA.recover(hash, v, r, s)` signature checks

### ISSUE THREAD

**Issue by BarnabyBob** [NomicFoundation/hardhat#2302]
This is actually a long-standing problem, but I had never bothered to upgrade Hardhat to ^2.8.0 yet.

It's also easily reproducible, below I will be using:
- `ethers`: `5.5.3`
- `ethereumjs-util`: `7.1.3`
- `hardhat`: `2.7.1` & `2.8.3`

So, let's take the ERC20Permit implementation from OZ: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/draft-ERC20Permit.sol

And let's write a simple test suite for the `permit` function:
```typescript
	it('permit', async () => {
		const PERMIT_TYPEHASH = keccak256(toUtf8Bytes('Permit(address owner,address spender,uint256 value,uint256 nonce,uint256 deadline)'));

		const nonce = await ERC20Mock.nonces(owner.address);
		const deadline = ethers.constants.MaxUint256;
		const domSep = await ERC20Mock.DOMAIN_SEPARATOR();
		const digest = keccak256(
			solidityPack(
				['bytes1', 'bytes1', 'bytes32', 'bytes32'],
				[
					'0x19',
					'0x01',
					domSep,
					keccak256(
						defaultAbiCoder.encode(
							['bytes32', 'address', 'address', 'uint256', 'uint256', 'uint256'],
							[PERMIT_TYPEHASH, owner, spender, value, nonce, deadline]
						)
					),
				]
			)
		);
		
		const PK = getPrivateKey(PrivateKeys.OWNER, true);
		const { v, r, s } = ecsign(Buffer.from(digest.slice(2), 'hex'), Buffer.from(PK, 'hex'));

		await expect(ERC20Mock.permit(owner.address, spender.address, TEST_AMOUNT, deadline, v, hexlify(r), hexlify(s)))
			.to.emit(ERC20Mock, 'Approval')
			.withArgs(owner.address, spender.address, TEST_AMOUNT);
		expect(await ERC20Mock.allowance(owner.address, spender.address)).to.eq(TEST_AMOUNT);
		expect(await ERC20Mock.nonces(owner.address)).to.eq(BigNumber.from(1));
	});
```

This test suite succeeds with Hardhat <=2.7.1 but fails with Hardhat ^2.8.0. In the latter case, the sig recovered by the contract differs. 

@frangio @alcuadrado @fvictorio

**Comment by fvictorio** [comment]
Hey @BarnabyBob, I cannot reproduce this. The test fails for me both with Hardhat v2.7.1 and with the latest version. I had to guess some values here since your snippet is not a complete example, but I don't think they are relevant.

Please re-open if you can give us a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that triggers the problem.
