### ISSUE TITLE
Typos in Documentation

### ISSUE THREAD

**Issue by thecodingcrow** [NomicFoundation/hardhat#2315]
Two small typos in the docs navigation

builder --> builder

<img width="272" alt="image" src="https://user-images.githubusercontent.com/53899975/151681351-e6f44fce-7f88-42a3-ad57-83a60de43cb2.png">

**Comment by sisco0** [comment]
Kindly take a look at https://www.npmjs.com/package/@nomiclabs/buidler, the package name matches as expected.

**Comment by sisco0** [comment]
@thecodingcrow Could you kindly check the current issue feedback?
