### ISSUE TITLE
`hardhat test` should support pass-through of mocha arguments

### ISSUE THREAD

**Issue by tmpfs** [NomicFoundation/hardhat#2316]
In my terminal using the solarized color theme I cannot see the stack trace due to [this long-standing issue](https://github.com/mochajs/mocha/issues/3183) that nobody wants to resolve. Also see [this issue](https://github.com/mochajs/mocha/issues/1200).

Normally I pass `--no-color` to mocha to bypass this problem but I cannot when executed via hardhat.

I was expecting `npx hardhat test -- --no-color` to pass the additional options to `mocha(1)` but it doesn't work.

Currently, I cannot read stack traces. Allowing additional custom mocha options would fix this issue 🙏

**Comment by tmpfs** [comment]
FYI, I tried adding a `.mocharc.json` and configuring `mocha` in `package.json` but neithr appear to work either.

**Comment by tmpfs** [comment]
Ok, so my workaround for now so that my `.mocharc.js` file is respected is to call `mocha` directly rather than `hardhat test`.

**Comment by feuGeneA** [comment]
Can you clarify your actual request here? :pray:

**Comment by tmpfs** [comment]
@feuGeneA, sure, I would like it if we could pass options to the mocha executable when running `hardhat test` in the standard manner:

```
hardhat test -- --no-color
```

Thanks 🙏

**Comment by lino-silva** [comment]
+1 to this - I want to use custom test reporters (Jenkins), and the arguments are not being passed through to mocha
