### ISSUE TITLE
Unable to impersonate contract address in fork mode

### ISSUE THREAD

**Issue by skozin** [NomicFoundation/hardhat#2322]
**Update by @alcuadrado: This issue is no longer present. Delete your `package-lock.json`/`yarn.lock` and reinstall hardhat to fix it.**

---

The [documentation](https://hardhat.org/hardhat-network/reference/#hardhat-impersonateaccount) says that:

> Hardhat Network allows you to send transactions impersonating specific account **and contract addresses**.

This was indeed the case previously. However, when using Hardhat v2.8.3, sending a transaction from an impersonated contract address produces the following error:

> invalid sender address, address is not EOA (EIP-3607)

The code that throws the error is located in the `@ethereumjs/vm` package: [src/runTx.ts#L305](https://github.com/ethereumjs/ethereumjs-monorepo/blob/64b48b0/packages/vm/src/runTx.ts#L305-L309) and was added in [`2e92010`](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1568/commits/2e92010224a172d50afa044bc19b624a29047b44) as a part of https://github.com/ethereumjs/ethereumjs-monorepo/pull/1568. Notice that there's no check for whether [EIP-3607](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-3607.md) is implemented in the network.

Trying to manually remove the code at the address being impersonated via the `hardhat_setCode` RPC call allows to do simple transfers from that address, but contract calls for some reason fail without a revert reason.

I think that an exception should be made for an impersonated contract address even if EIP-3607 is implemented in the network being forked since impersonating a contract is a very useful technique that makes writing fork tests much easier. We use this technique a lot across our test codebase.

**Comment by alcuadrado** [comment]
Thanks for reporting this and taking the time to analyze the situation. I agree with your take and I'm discussing this with ethereumjs.

**Comment by ryanio** [comment]
hey all, thanks for your patience. I just released [`@ethereumjs/vm v5.7.1`](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fvm%405.7.1) and [`@ethereumjs/common v2.6.2`](https://github.com/ethereumjs/ethereumjs-monorepo/releases/tag/%40ethereumjs%2Fcommon%402.6.2) which should solve this problem. please let me know if you see any other issues.

**Comment by skozin** [comment]
Awesome, thank you so much! We'll check it out in our setup in a few days and I'll hopefully close the issue.

**Comment by fvictorio** [comment]
@skozin do you think we can close this now?

**Comment by fvictorio** [comment]
Actually, we are going to keep this open until we can upgrade our dependencies on ethereumjs to the latest versions.

If anyone runs into this issue, you can fix this issue by removing your lock file (`yarn.lock` or `package-lock.json`) and re-installing your dependencies.

If you don't want to do that and you are using yarn, check [this](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to learn how to override specific dependencies. I think the latest versions of npm also support this, but I haven't tried it.
