### ISSUE TITLE
Feature request: Support mocha v8's parallel test execution

### ISSUE THREAD

**Issue by Ramarti** [NomicFoundation/hardhat#2331]
Hi all,

Just wanted to point out that [Mocha's v8 advertises the possibility to run test in parallel](https://mochajs.org/#parallel-tests) via `--parallel` flag.

This could potentially speed up development, especially for "bigger" smart contract suites.

Please consider, and thanks for the awesome tools!

**Comment by alcuadrado** [comment]
This was released in v2.9.0.
