### ISSUE TITLE
Hardhat Account Impersonation on Arbitrum forks not working correctly

### ISSUE THREAD

**Issue by 0xTimepunk** [NomicFoundation/hardhat#2345]
When trying to impersonate an account with Link tokens either on Arbitrum or Rinkeby Arbitrum no transactions can be sent with that impersonated account because the following error returns:

'(node:36286) UnhandledPromiseRejectionWarning: ProviderError: sender doesn't have enough funds to send tx. The max upfront cost is: 68185536000000000 and the sender's account only has: 0'

Even though I know the user I'm impersonating has both ETH and Link to support what I need to do (as you can check in https://testnet.arbiscan.io/address/0x2c6d750d5a9193ad079885ecb6efc9c591bfc687 this is a valid whale address with ETH and Link holdings)

The code below is the function being used to impersonate and access an account's funds:

```
const hardhat = require('hardhat');

const linkAddressArbitrumRinkeby = '0x615fBe6372676474d9e6933d310469c9b68e9726;
const erc20Factory = await ethers.getContractFactory('ERC20');
const token = (await erc20Factory.attach(linkAddressArbitrumRinkeby)) as ERC20;

const whale = '0x2C6D750d5a9193ad079885ECB6efC9c591bfc687' 

const getTokenForAccount = async (token: ERC20, amountConverted: string, user: string, whale: string) => {
    // ETH whale
    await hardhat.network.provider.request({
      method: 'hardhat_impersonateAccount',
      params: [whale],
    });
    const whaleSigner = await hardhat.ethers.provider.getSigner(whale);
    
    await token.connect(whaleSigner).transfer(user, amountConverted);
    // Stop Impersonating ETH whale
    await hardhat.network.provider.request({
      method: 'hardhat_stopImpersonatingAccount',
      params: [whale],
    });
};

```

even actions like getting the balance of the whale address stop the hardhat code. For e.g.
```
  const balance = await hardhat.ethers.provider.getBalance(user);
  console.log({ balance });
```

This code above does not run (is stuck in the await call)

What could be wrong?

Using https://arb-rinkeby.g.alchemy.com/v2/KEY_HERE as a provider

**Comment by ClementWalter** [comment]
I was having the same issue that I eventually solved sending some eth first from an UnnammedAccount to the contract
