### ISSUE TITLE
mocha types missing / unnecessary references

### ISSUE THREAD

**Issue by 3commascapital** [NomicFoundation/hardhat#2353]
it seems like hardhat test types (mocha) are being included in the build when i would presume that they would not be needed. I am simply importing hardhat into a ts file and running a build as can be seen below
```bash
yarn run v1.22.15
$ tsc -p .
node_modules/hardhat/types/config.d.ts:1:23 - error TS2688: Cannot find type definition file for 'mocha'.

1 /// <reference types="mocha" />
                        ~~~~~

node_modules/hardhat/types/config.d.ts:197:13 - error TS2503: Cannot find namespace 'Mocha'.

197     mocha?: Mocha.MochaOptions;
                ~~~~~

node_modules/hardhat/types/config.d.ts:204:12 - error TS2503: Cannot find namespace 'Mocha'.

204     mocha: Mocha.MochaOptions;
               ~~~~~


Found 3 errors.
```

**Comment by 3commascapital** [comment]
installing `@types/mocha` seems to fix the issue

**Comment by alcuadrado** [comment]
This is a known limitation. Including them by default would lead to hardhat being incompatible with jest.

**Comment by 3commascapital** [comment]
well, does the mocha requirement need to be included at all in hardhat?

**Comment by alcuadrado** [comment]
It's a mistake, for sure. We are keeping it for backward compatibility. We may go through a deprecation process soon.
