### ISSUE TITLE
cmd: export: does not generate `bytecode` field & uses different format

### ISSUE THREAD

**Issue by Dentrax** [NomicFoundation/hardhat#2358]
I'm not sure whether this is an intentional or bug but, throwing an issue to discuss.

What I expect after issuing the following command is that the _output_ JSON file should have an `bytecode` field in the `contracts:<NAME>` field. Notice that there is no `bytecode` field in the `contracts:Foo` level:

```
$ npx hardhat export --export output.json

$ cat output.json
{
  "contracts": {
    "Foo": {
      "address": "<REDACTED>",
      "abi": [...]
    }
  }
}
```

Format of `./artifacts/contracts/Foo.json` file is slightly different from _exported_ file.

```
$ cat ./artifacts/contracts/Foo.json
{
  "_format": "hh-sol-artifact-1",
  "contractName": "Foo",
  "sourceName": "contracts/Foo.sol",
  "abi": [...],
  "bytecode": "...",
  "linkReferences": {},
  "deployedLinkReferences": {}
}
```

By running `export` command, I'm exporting the current deployment. I expect a `bytecode` field, so we can easily use the _exported_ file to migrate with `web3.js`. In the _actual_ scenario, I can not use this file directly since there is no byte code representation.

Any thoughts?

**Comment by fvictorio** [comment]
Hi @Dentrax, the `export` task is added by the `hardhat-deploy` plugin, which is a community plugin not maintained by us. You can create an issue about it in [its repo](https://github.com/wighawag/hardhat-deploy).
