### ISSUE TITLE
Add support for Truffle's assert.sol

### ISSUE THREAD

**Issue by alcuadrado** [NomicFoundation/hardhat#236]

**Comment by alcuadrado** [comment]
The cleanest way of doing this would be to create an internal task for resolving solidity paths. This way it can be overloaded.

**Comment by mariocao** [comment]
Any update on this?
I was assessing the migration of one project from truffle to hardhat, but there are some tests written in solidity.

> The cleanest way of doing this would be to create an internal task for resolving solidity paths. This way it can be overloaded.

Do you know any example I could use as inspiration? Thanks in advance! :blush:

**Comment by fvictorio** [comment]
Closing because we probably won't do this.
