### ISSUE TITLE
Internal Compiler Error?  

### ISSUE THREAD

**Issue by grapevinegizmos** [NomicFoundation/hardhat#2361]
I ge the following error when attempting to compile my contract:

Compiling 1 file with 0.8.7
InternalCompilerError: Internal compiler error (/Users/distiller/project/libsolidity/codegen/CompilerUtils.cpp:1116)
Error HH600: Compilation failed

That's a bit more obscure than most message, wondering if it's a problem with my code (below) or something not quite right with the compiler.
 
Attempting to use bytes slice syntax [x:y]to replicate a stirng slice type of function as follows:

```
function slice(string calldata source, uint from, uint to) public pure returns(string memory) {
      bytes calldata b = bytes(source);
      uint len = b.length;
      require(to < len && to>=from, "indexes out of bounds");
    
      string memory retval = string(b[from:to]);
     
      return retval;
    }
```
Some of the docs seemed to say that this works with calldata storage but not memory, but neither is working for me right now.

**Comment by morgansliman** [comment]
Hi @grapevinegizmos , 

This doesn't seem to be an issue with hardhat, but rather with the solidity compiler itself. Please open an issue in the main solidity repo instead as they will better be able to help with your issue.

Thanks!
