### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by CaciqueLarru** [NomicFoundation/hardhat#2369]
Bug encontrado:

HardhatError: HH5: HardhatContext is not created.
  errorDescriptor: {    number: 5,
    message: 'HardhatContext is not created.',    title: "Hardhat wasn't initialized",
    description: 'Hardhat initialization failed. This is a bug.\n' +      '\n' +
      'Please [report it](https://github.com/nomiclabs/hardhat/issues/new) to help us improve Hardhat.',
    shouldBeReported: true
  },
  number: 5,
  messageArguments: {},
  _isHardhatError: true
}

**Comment by morgansliman** [comment]
Hi @CaciqueLarru ,

Could you add any more info on what your code looks like that generated this error?
