### ISSUE TITLE
TYPO in Debugging tutorial

### ISSUE THREAD

**Issue by wardu** [NomicFoundation/hardhat#2397]
As appears in tutorial:

To use it you have to import Hardhat's `console.log` from your contract code.

This is what it looks like:

```
pragma solidity ^0.6.0;

import "hardhat/console.sol";

contract Token {
  //...
}
```
The fix:
To match the code example, the explanation text should refer to `console.sol` and not `console.log`

**Comment by fvictorio** [comment]
Closed by #2398.
