### ISSUE TITLE
Configuration for network `hardhat` not working

### ISSUE THREAD

**Issue by Brunnhild** [NomicFoundation/hardhat#2424]
### Environment:
macOS Monterey 12.1
nodejs 16.13.0
hardhat 2.8.4

### Setup
I generated a sample project using `npx hardhat` and chose `Create a sample project`, then I modified `hardhat.config.js`:
```js
module.exports = {
  solidity: "0.8.6",
  networks: {
    hardhat: {
      chainId: 5678
    }
  }
};
```
I tried to print the chainId in `scripts/sample-script.js`:
```js
console.log(await hre.ethers.getDefaultProvider().getNetwork())
```

### Problems
I ran `npx hardhat scripts/sample-script.js --network hardhat` and got this:
```text
Deploying a Greeter with greeting: Hello, Hardhat!
Greeter deployed to: 0x5FbDB2315678afecb367f032d93F642f64180aa3
{
  name: 'homestead',
  chainId: 1,
  ensAddress: '0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e',
  _defaultProvider: [Function: func] { renetwork: [Function (anonymous)] }
}

```

**Comment by Brunnhild** [comment]
### Expected
The chainId in the output should be 5678

**Comment by morgansliman** [comment]
Hi @Brunnhild ,

I'm not sure whether this is the intended functionality or not, but it does appear to specifically occur when accessing the network info through the ethers object. 

If you need that particular piece of information, you can access it like this:
```js
console.log(hre.network.config.chainId) // logs 5678
```

**Comment by morgansliman** [comment]
I'm going to assume this is intended and close this for now as that data is available through the fields I listed above.

@alcuadrado @fvictorio if this isn't the intended way for the ethers package to work then feel free to comment and we can reopen.

Thanks!
