### ISSUE TITLE
Error HH600: Compilation failed

### ISSUE THREAD

**Issue by karugu7** [NomicFoundation/hardhat#2427]
I ge the following error when attempting to compile my contract:

InternalCompilerError: Error parsing/analyzing inline assembly block:
Invalid assembly generated by code generator.
------------------ Input: -----------------

                {
                        // If code starts at 11, an mstore(0) writes to the full PUSH20 plus data
                        // without the need for a shift.
                        let codepos := 11
                        codecopy(codepos, subOffset, subSize)
                        // Check that the first opcode is a PUSH20
                        if iszero(eq(0x73, byte(0, mload(codepos)))) {
                                mstore(0, 35408467139433450592217433187231851964531694900788300625387963629091585785856)
                                mstore(4, 0)
                                revert(0, 0x24)
                        }
                        mstore(0, address())
                        mstore8(codepos, 0x73)
                        return(codepos, subSize)
                }

------------------ Errors: ----------------
Error: Function "iszero" not found.
 --> @openzeppelin/contracts/utils/Address.sol:9:1:
  |
9 | library Address {
  | ^ (Relevant source part starts here and spans across multiple lines).

Error: Expected expression to evaluate to one value, but got 0 values instead.
 --> @openzeppelin/contracts/utils/Address.sol:9:1:
  |
9 | library Address {
  | ^ (Relevant source part starts here and spans across multiple lines).

-------------------------------------------

Error HH600: Compilation failed

**Comment by morgansliman** [comment]
Hi @karugu7 , 

This doesn't seem like a bug with hardhat, and I'm not sure there's enough info for me to point you in the right direction. I would double check your solidity code and make sure there's no subtle bugs as this can often be the case especially when dealing with inline assembly. 

If you're certain there's no mistakes in your contract, then I'd open an issue in the main solidity repository as this would potentially be an issue in the compiler, not in hardhat.

**Comment by morgansliman** [comment]
Going to close this for now, but feel free to post any more info you have that might indicate an issue in hardhat and we can reopen.

Thanks!

**Comment by iamtortue001101** [comment]
Hello,
I had the same problem. I sent the following command on the server and my problem was solved, good luck!

`export LANG="en_US.UTF-8"`

**Comment by karugu7** [comment]
I already solved this problem, thanks. I was working on linux but when I tried it with windows there was no problem. I think it's a bug caused by the compiler on linux.
