### ISSUE TITLE
Hardhat config should be overridable with env vars

### ISSUE THREAD

**Issue by rhlsthrm** [NomicFoundation/hardhat#2436]
We want to dynamically change the hardhat mainnet forking params in CI tests. Right now we are doing regex and string replacement on the hardhat.config.ts file, which is very annoying. It would make sense for the config itself to be overridable somehow. Even having a CLI arg to point at a specific config file would help.

**Comment by alcuadrado** [comment]
Hey @rhlsthrm!

Do you mean specific bits of the config or the config file?

If the latter, you could do something like this:

```js
module.exports = {
   networks: {
      hardhat: {
         forking: {
            url: process.env.FORK_URL ?? "http://default.url"
         }
      }
   }
}
```

**Comment by rhlsthrm** [comment]
> Hey @rhlsthrm!
> 
> Do you mean specific bits of the config or the config file?
> 
> If the latter, you could do something like this:
> 
> ```js
> module.exports = {
>    networks: {
>       hardhat: {
>          forking: {
>             url: process.env.FORK_URL ?? "http://default.url"
>          }
>       }
>    }
> }
> ```

This would work, but what's the default for forking, if you just want the regular non-forked hardhat node? I guess I could set `forking: undefined`?

**Comment by morgansliman** [comment]
@rhlsthrm if `forking: undefined` doesn't work, you could always do 
```js
module.exports = {
  networks: {
    hardhat: {
      forking: process.env.FORK_URL ? { url: process.env.FORK_URL } : undefined
    }
  }
}
```

**Comment by morgansliman** [comment]
Closing this for now as the original requested use case seems to have been met. If that's not the case, feel free to add some more info on what exactly you're looking for and we can reopen.

Thanks!
