### ISSUE TITLE
hardhat-etherscan should use `'Content-Type': 'application/x-www-form-urlencoded'` header

### ISSUE THREAD

**Issue by gozup** [NomicFoundation/hardhat#2437]
Hi all,

Issue on `hardhat-etherscan` version 3.0.2

I wasted tones of time searching why my contract verification was failing, and I finally found that is comes from the "Content-Type" header sent by hardhat-etherscan. Indeed, by default the plugin is making a POST with encoded string body, but the header is set to `Content-Type: application/json`. So etherscan always answers :

```
{
"status": "0",
"message": "NOTOK",
"result": "Error! Missing Or invalid Module name"
}
```

So, I went into the plugin code straight in the `node_modules` directory and forced the header to `'Content-Type': 'application/x-www-form-urlencoded'` (function `verifyContract` of `EtherscanService`) and it not works like a charm. But obviously, that's not the right solution.

My question is, am I missing something or is there an issue in this package? Someone else has the same issue?

Thank you!

**Comment by oishun1112** [comment]
use 3.0.1 for now

**Comment by rayquaza7** [comment]
I was getting the same error as well. I tried manually implementing the etherscan API and this is what I did:
```
let flattened_code = await hre.run(TASK_FLATTEN_GET_FLATTENED_SOURCE, {
        files: "Pass.sol",
    });

    try {
        const response = await axios.post(
            "https://api-rinkeby.etherscan.io/api",
            {
                apikey: ETHERSCAN_API_KEY,
                module: "contract", //Do not change
                action: "verifysourcecode", //Do not change
                contractaddress: "0x29d2d7a1733ad2b3a87313cf0ab5905819fee728",
                sourceCode: flattened_code,
                contractname: "Pass.sol",
                compilerversion: "v0.8.1+commit.df193b15",
                optimizationUsed: 1,
                runs: 200,
                constructorArguements: args,
                licenseType: 3,
                libraryname1: "X.sol",
                libraryaddress1: "0x85df23dee9f3a86c4fc98c29993bbb8bd1496fd6",
            },
            {
                headers: {
                    "content-type": "application/x-www-form-urlencoded",
                },
            }
        );
        return response;
    } catch (error) {
        console.error(error);
    }
```
Now I've tried removing the `.sol` from the contract/library name, I've tried manually inputting the etherscan key, I've tried getting a new key as well. But I still get,
```
{
  status: '0',
  message: 'NOTOK-Missing/Invalid API Key, rate limit of 1/5sec applied',
  result: 'Error! Missing Or invalid Module name'
}
```
Now, my key still works if i use it on the browser for a get request. So unless i am missing something, I would assume there is something wrong with etherscan's API that causes a bug in this as well

**Comment by alcuadrado** [comment]
Fixed by https://github.com/NomicFoundation/hardhat/releases/tag/%40nomiclabs%2Fhardhat-etherscan%403.0.3
