### ISSUE TITLE
Error in plugin @nomiclabs/hardhat-etherscan: Error! Missing Or invalid Module name

### ISSUE THREAD

**Issue by justChargin** [NomicFoundation/hardhat#2438]
I tried to verify my contract with constructor arguments but hardhat throwing that error everytime

`npx hardhat verify --network rinkeby 0x50a45120252c2FeeD06915F46D8Fbabec1a008df "TestSmartContract" "TSC" "my_ipfs_link1" "my_ipfs_link2"`

these arguments is same as my contract's arguments

**Comment by justChargin** [comment]
![image](https://user-images.githubusercontent.com/46795644/156201180-f3c11457-5967-4425-90d4-26ce00ef3307.png)

**Comment by gokhanmelma** [comment]
I tried to verify the contract that doesn't have any constructor arguments, but getting this error as well.
Any solutions?

**Comment by justChargin** [comment]
I tried to verify the contract without constructor arguments but getting this error again... Last day didn't throw this error to me so weird.

**Comment by justChargin** [comment]
> I tried to verify the contract that doesn't have any constructor arguments, but getting this error as well. Any solutions?

I solved the issue. Latest version of @nomiclabs/hardhat-etherscan is not working properly. So i decided to install it via this command

`npm install @nomiclabs/hardhat-etherscan@3.0.1`

And now i am able to verify my contract.
