### ISSUE TITLE
Etherscan Verify not working on Rinkeby

### ISSUE THREAD

**Issue by Remscar** [NomicFoundation/hardhat#2447]
I deploy a contract on rinkeby.

Immediately afterwards run `verify` with the network set to rinkeby and the contract address.

```
$ hardhat verify --network rinkeby 0x6f49fc3bdd7ab7004e6be1781408b7c51987fc4f
Nothing to compile
No need to generate any newer typings.
Successfully submitted source code for contract
contracts/registrar/Registrar.sol:Registrar at 0x6f49fc3bdd7ab7004e6be1781408b7c51987fc4f
for verification on Etherscan. Waiting for verification result...

We tried verifying your contract Registrar without including any unrelated one, but it failed.
Trying again with the full solc input used to compile and deploy it.
This means that unrelated contracts may be displayed on Etherscan...

Successfully submitted source code for contract
contracts/registrar/Registrar.sol:Registrar at 0x6f49fc3bdd7ab7004e6be1781408b7c51987fc4f
for verification on Etherscan. Waiting for verification result...

*** Hangs for a long time ***

Error in plugin @nomiclabs/hardhat-etherscan: The contract verification failed.       
Reason: Fail - Unable to verify

```

Compiler is `0.8.8` optimization enabled and set to 200 runs.

There were no constructor arguments.

Tried with multiple versions of `@nomiclabs/hardhat-etherscan` such as `2.1.8` and `3.0.3`

**Comment by PatrickAlphaC** [comment]
I also got the same thing.

**Comment by alcuadrado** [comment]
Thanks for reporting this.

I'll run this through Etherscan, as I don't think there's something bad on our end.

**Comment by Alexangelj** [comment]
Got same issue - agree I don't think it's a hardhat issue

**Comment by Remscar** [comment]
I've been having lots of issues with testnet etherscan the last couple months, such as new blocks not getting indexed for hours after they happen, don't know if this is somehow related.

**Comment by cptlchad** [comment]
Run into the exact same issue 12 hours ago. Didn't manage to solve it. I used the versions 2.1.8 and 3.0.1. Worked without problems on Rinkeby around 2 weeks ago

**Comment by DevTenset** [comment]
Probably the problem is bytecode that doesn't contain. I tried do it by manually but with unsuccessful. So I made flatt smart contracts and put to remix IDE, there I compile and deploy. Back to etherscan verify and paste flatten smart contracts and then work correctly

**Comment by alcuadrado** [comment]
This was an issue on Etherscan side. They confirmed it and fixed it.

If someone runs into this or a similar problem, please open a new issue.

**Comment by PatrickAlphaC** [comment]
Thanks @alcuadrado!

**Comment by hahaashton1** [comment]
@alcuadrado The problem seems to be be persisting still. 

How do we get a fix on our side?

Thank you!

**Comment by Remscar** [comment]
Works on Rinkeby for me

**Comment by alcuadrado** [comment]
@hahaashton1 please double-check that everything is correct (i.e. you are actually using the same sources and settings), and if that doesn't help contact Etherscan.

**Comment by vimes-stx** [comment]
Hmm are we sure this is fixed? I'm seeing the same issue.
