### ISSUE TITLE
npx hardhat installation Unexpected token { error

### ISSUE THREAD

**Issue by edwardajohnson** [NomicFoundation/hardhat#2452]
Running MacBook 
Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
Catalina 10.15.2 
Trying to install hardhat looks like v2.9.0
% node -v   is v9.7.1

Error message 
(base) ed@Mac hello-hardhat % npx hardhat -v
Unexpected token {
(node:24549) Warning: N-API is an experimental feature and could change at any time.

Can you help ?

**Comment by alcuadrado** [comment]
Hardhat doesn't support node 9. Take a look at this https://hardhat.org/reference/stability-guarantees.html#node-js-versions-support
