### ISSUE TITLE
Do not override config.mocha.grep when running test without --grep option

### ISSUE THREAD

**Issue by nataouze** [NomicFoundation/hardhat#2459]
The current behavior 

```typescript
      const mochaConfig: MochaOptions = {
        ...config.mocha,
        grep: taskArgs.grep,
      };
```
prevents plugins from making use of `config.mocha.grep` as it will be unset if the option is not coming from the cli.

I would suggest this type of logic instead

```typescript
      if (taskArgs.grep !== undefined) {
        mochaConfig.grep = taskArgs.grep;
      }
```

**Comment by smartcontracts** [comment]
+1 here, this causes issues when used in combination with other plugins
