### ISSUE TITLE
support node version v17.6.0

### ISSUE THREAD

**Issue by ytianhui** [NomicFoundation/hardhat#2461]
You are using a version of Node.js that is not supported by Hardhat, and it may work incorrectly, or not work at all.

Please, make sure you are using a supported version of Node.js.

**Comment by zhyd1997** [comment]
Could you list all supported node versions here?

I'm new to hardhat.

**Comment by fvictorio** [comment]
@zhyd1997 https://hardhat.org/nodejs-versions

**Comment by zhyd1997** [comment]
Thanks @fvictorio  👍

**Comment by landerland12354** [comment]
Hi everyone! 
I've got the same issue "You are using a version of Node.js that is not supported by Hardhat, and it may work incorrectly, or not work at all."

I used to work on v17.5. So if I'm understanding correctly this version supposed to be supported. 
So I've upgraded Node via Brew to v17.6 just in case but nothing changed.
Please  guide me where I've made a mistake?

**Comment by landerland12354** [comment]
Update: I've switched to latest LTS version 16.14 via nvm but getting the same error still.

**Comment by katesonia** [comment]
I am having the same error, version 17.7.1

**Comment by katesonia** [comment]
Change node to v16.14.0 solved the issue

**Comment by mohamedtb20** [comment]
> Could you list all supported node versions here?
> 
> I'm new to hardhat.

https://hardhat.org/nodejs-versions

**Comment by NajibKabir** [comment]
I am using node@16 but I am still having this issue
