### ISSUE TITLE
Uncovered lines counting lines that are covered 

### ISSUE THREAD

**Issue by fulldecent** [NomicFoundation/hardhat#2466]
I have a smart contract and testing setup.

With the command:

```sh
hardhat coverage --testfiles 'contracts/MY_CONTRACT.sol'
```

it is showing several lines under "Uncovered Lines".

However those lines are certainly covered. This is simple to check by putting a `require(false);`  next to any of the reported lines and seeing the tests fail which previously passed before the change.

Sorry to not have a minified test case yet I can share.

But I do have a workaround. Adding an event to the affected contract and putting a `emit` next to that affected line solves the problem.

Wanted to create this issue first because we have a workaround and that might be helpful for others.

---

Version: Hardhat 2.9.1

**Comment by alcuadrado** [comment]
Hey @fulldecent,

Thanks for opening this issue, but it should have been submitted to [this repository](https://github.com/sc-forks/solidity-coverage/) instead.

**Comment by fulldecent** [comment]
Thank you for the pointer! Reported to https://github.com/sc-forks/solidity-coverage/issues/698
