### ISSUE TITLE
`hardhat_mine` produces a failed tx when running in Coverage

### ISSUE THREAD

**Issue by julianmrodri** [NomicFoundation/hardhat#2467]
Hi, we are facing a strange situation using the newly added `hardhat_mine` to mine several blocks at once.

When we use it in our *regular* tests, it works fine. But when running in **coverage** mode (`npx hardhat coverage`) we get in one case the following error in a transaction sent *right after* the blocks are mined:

```
InvalidInputError: Transaction gasPrice (1) is too low for the next block, which has a baseFeePerGas of 7
      at HardhatNode._validateAutominedTx (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1661:17)
      at async HardhatNode.sendTransaction (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:435:5)
      at async EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1496:18)
      at async HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
      at async EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

We created the following auxiliary function to be able to specify in our tests the number of blocks to mine. 

```
export const advanceBlocks = async (blocks: number) => {
  await ethers.provider.send('hardhat_mine', ['0x' + blocks.toString(16)])
}
```

 In this specific test that fails we are calling in in this way:

 ```
 await advanceBlocks(17). // This causes a fail (in a subsequent tx) when running in coverage, but works fine in regular test.
 ```
In order to avoid this issue I can do `await advanceBlocks(1)`, 17 times and that would do the trick and everything works fine even in coverage mode:

```
 await advanceBlocks(1). //  This works when running in coverage, and works fine in regular test.
 await advanceBlocks(1)
 await advanceBlocks(1)
 ....
 .....
 await advanceBlocks(1)   // 17 times..
```

This is the configuration in our `hardhat.config.ts`

```
   hardhat: {
      gas: 999999999999,
      blockGasLimit: 0x1fffffffffffff,
      allowUnlimitedContractSize: true,
    },
```
Any help or guidance in how we can fix this and still use the `hardhat_mine` with multiple blocks would be highly appreciated.

Thanks!
Julian

**Comment by fvictorio** [comment]
Thanks a lot for reporting this @julianmrodri. I think I know what's going on and how to fix it.

For the time being, a workaround is to do this after calling `hardhat_mine`:

```
await network.provider.send('hardhat_setNextBlockBaseFeePerGas', ['0x0'])
```

I know it's not a great solution, but maybe it can help you until we release a fix for this.

**Comment by julianmrodri** [comment]
Thanks, the workaround seems to work!

**Comment by ivelin** [comment]
Hi folks. Thank you for the incredible work.

This particular issues occurs with the latest hardhat v2.9.9 when using xdeployer in test cases. See PR log here:
https://github.com/SporosDAO/sweat-token/runs/7022447221?check_suite_focus=true#step:3:84

The suggested workaround above does not seem to help when used around create2deploy.deploy in test cases.
