### ISSUE TITLE
npx hardhat verify MY_CONTRACT 'MY_IPFS_URL' --network rinkeby. Error

### ISSUE THREAD

**Issue by JetCyC** [NomicFoundation/hardhat#2468]
I try to verify my contract by     npx hardhat verify MY_CONTRACT 'MY_IPFS_URL' --network rinkeby        but there is an error:

Error in plugin @nomiclabs/hardhat-etherscan: Failed to send contract verification request.
Endpoint URL: https://api-rinkeby.etherscan.io/api
Reason: Connect Timeout Error

NomicLabsHardhatPluginError: Failed to send contract verification request.
Endpoint URL: https://api-rinkeby.etherscan.io/api
Reason: Connect Timeout Error

Could you please help me. Thank you

**Comment by morgansliman** [comment]
Hi @JetCyC , it's possible that etherscan's API was down or something similar. Could you please try again and also double check your URL and internet connection?

Closing this for now as it doesn't appear to be a bug in hardhat. If there's more info that alludes to an issue being present then we can reopen. Otherwise please check out our discord server for more general support.

Thanks!

**Comment by JetCyC** [comment]
Thanks!

**Comment by ronneycjm** [comment]
Hi @JetCyC and @morgansliman , I have also met this issue by verifying contract on ropsten:
```log
Nothing to compile
Error in plugin @nomiclabs/hardhat-etherscan: Failed to send contract verification request.
Endpoint URL: https://api-ropsten.etherscan.io/api
Reason: Connect Timeout Error
```
I set up the proxy in vscode and the proxy works fine for me. I have no idea what's up with this issue.....

**Comment by ronneycjm** [comment]
> > Hi @JetCyC and @morgansliman , I have also met this issue by verifying contract on ropsten:
> > ```
> > Nothing to compile
> > Error in plugin @nomiclabs/hardhat-etherscan: Failed to send contract verification request.
> > Endpoint URL: https://api-ropsten.etherscan.io/api
> > Reason: Connect Timeout Error
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I set up the proxy in vscode and the proxy works fine for me. I have no idea what's up with this issue.....
> 
> Would you send me the proxy please?

Proxy works fine when visiting websites and other operations while not working in verifying contract.......
I setup own proxy on localhost port7078 in console like this:

```js
npm config set proxy http://localhost:7078
```

**Comment by JetCyC** [comment]
> proxy

Thank you. So how to set localhost proxy

**Comment by JetCyC** [comment]
> 

hello, have you solve the problem?

**Comment by JetCyC** [comment]
> > > 
> > 
> > 
> > hello, have you solve the problem?
> 
> see solution here: #2348 by @0xleung

tks，bro

**Comment by JetCyC** [comment]
I still have this issue, sad

**Comment by JetCyC** [comment]
Finally, I solved the problem in other way. I verify & publish manually contract source code in etherscan by Standard Json-Input. It is in xxx/artifacts/build-info/xxxx.json, the "input" part. I put the  the "input" part json in etherscan.

**Comment by RoamWang** [comment]
meet same issue, I don't know how the fix this

**Comment by RoamWang** [comment]
> Finally, I solved the problem in other way. I verify & publish manually contract source code in etherscan by Standard Json-Input. It is in xxx/artifacts/build-info/xxxx.json, the "input" part. I put the the "input" part json in etherscan.

sir, can you explain the steps to me? thank you

**Comment by afewnotes** [comment]
use proxychians4 as a global proxy, this network problem solved

**Comment by lightrao** [comment]
proxychains4 npx hardhat verify ...... 
but have this error:
Error in plugin @nomiclabs/hardhat-etherscan: Failed to obtain list of solc versions. Reason: Body Timeout Error
