### ISSUE TITLE
Hardhat >2.7.1 and HVM forking breaks `ecrecover` (with MRE)

### ISSUE THREAD

**Issue by BarnabyBob** [NomicFoundation/hardhat#2482]
In a nutshell, if forking a chain locally with Hardhat VM, while running Hardhat >2.7.1 permit signatures checks seem to fail at `ecrecover`, even though the signature is correctly constructed (and parsed off-chain), as shown in the only test suite. The same situation does not occurr with Hardhat 2.7.1 or lower /

https://github.com/BarnabyBob/hardhat-permit-mre

# hardhat-permit-mre

MRE for Hardhat >2.7.1 permit behavior

## Setup

-   create a `.env` config file and populate at least one of the RPC endpoints
-   update `HARDHAT_BLOCKCHAIN_FORK` accordingly (located in `lib/config.ts`)

### Bug

To reproduce:
1. `npm i && npm run build`
2. `npm run test`
3. observe the behavior on the two different branches:
    - `main` branch runs with `hardhat@2.9.1` and manifests the bug (`vanilla permit` test suite fails with `"ERC20Permit: invalid signature"`)
    - `2.7.1` branch runs with `hardhat@2.7.1` and the test suite passes, the other parameters are exactly the same

**Comment by BarnabyBob** [comment]
references https://github.com/NomicFoundation/hardhat/issues/2302

@alcuadrado @fvictorio can you help confirm what seems to be a Hardhat VM forking bug?

**Comment by alcuadrado** [comment]
Hey @BarnabyBob, sorry for the delay.

`ecrecover` isn't the problem, but the chain id on `eth_call` is.

I created a [new issue](https://github.com/NomicFoundation/hardhat/issues/2591) with a reproduction script, and will assign it the highest priority.
