### ISSUE TITLE
Having "Insufficient funds" in require message causing "insufficient funds for intrinsic transaction cost" unrelated error to be thrown

### ISSUE THREAD

**Issue by ishayhil** [NomicFoundation/hardhat#2489]
# Reproduce steps

run (on hardhat network)
```solidity
require(1 > 2, Insufficient funds)
```

and receive
`Error: insufficient funds for intrinsic transaction cost`
instead of
`Insufficient funds`

For some reason, if the require message contains "insufficient funds", the "insufficient funds for intrinsic transaction cost" pops.

**Comment by ta5een** [comment]
Hi, I'm also getting this unusual error! Seems that if the reason string contains `"Insufficient funds"` anywhere, Hardhat treats it specially. I don't think that's supposed to happen, otherwise the Hardhat documentation would have mentioned this behaviour somewhere.

**Comment by narghev** [comment]
Any news on this?

**Comment by fvictorio** [comment]
It's possible that this is caused by the latest version(s) of ethers. Anyone running into this: can you try downgrading ethers and trying again? Thanks.

**Comment by fvictorio** [comment]
Hmm, it is caused by ethers but it's not a recent change:

https://github.com/ethers-io/ethers.js/blob/ef1b28e958b50cea7ff44da43b3c5ff054e4b483/packages/providers/src.ts/json-rpc-provider.ts#L80

Sadly I can't think of a workaround right now.

**Comment by fvictorio** [comment]
I believe this is a problem in ethers, so I submitted an issue there: https://github.com/ethers-io/ethers.js/issues/2954. Closing this one for now.

**Comment by AliNawaz-777** [comment]
Insufficient balance
Is any help when I try to run the testcase then get the error Insufficient balance'
