### ISSUE TITLE
Allow passing `--slow` param to mocha in `hardhat test`

### ISSUE THREAD

**Issue by samlaf** [NomicFoundation/hardhat#2502]
the hardhat builtin `test` task: https://github.com/NomicFoundation/hardhat/blob/master/packages/hardhat-core/src/builtin-tasks/test.ts
doesn't seem to allow us passing arbitrary mocha arguments to mocha.
I personally really like calling mocha with ``--slow 0``, which shows the time each test took (not only those considered slow by mocha).
It would be nice to either add this as a param to the `hardhat test` task, or otherwise to have this task read from `.mocharc.json` or some other mocha config file.

**Comment by feuGeneA** [comment]
See also https://github.com/NomicFoundation/hardhat/pull/2359
