### ISSUE TITLE
Verification of contract failed on snowtrace without any changes

### ISSUE THREAD

**Issue by bbeldame** [NomicFoundation/hardhat#2511]
When verifying my contract 3 days ago it worked fine, and it's also working fine on fuji (Avalanche testnet - testnet.snowtrace) but it doesn't work now on the mainnet (snowtrace.io)

I guess there is something wrong from the snowtrace side, and I see with others issues on the same subject that I should create an issue to be solved.

Here is the exact error:

```
We tried verifying your contract [...] without including any unrelated one, but it failed.
Trying again with the full solc input used to compile and deploy it.
This means that unrelated contracts may be displayed on Etherscan...

Successfully submitted source code for contract
[...]
for verification on the block explorer. Waiting for verification result...

Error in plugin @nomiclabs/hardhat-etherscan: The contract verification failed.
Reason: Fail - Unable to verify
```

**Comment by merlincdj** [comment]
Same error here, but I don't have access to Linear workspace.

**Comment by Vanclief** [comment]
Same error, any insights on this?

**Comment by feuGeneA** [comment]
Thank you for using Hardhat. In general, if there is a problem in Hardhat, we will need a minimal reproducible example in order to investigate it. See https://stackoverflow.com/help/minimal-reproducible-example
