### ISSUE TITLE
Support state overrides in eth_call

### ISSUE THREAD

**Issue by WyseNynja** [NomicFoundation/hardhat#2513]
Geth has support for "state overrides" that make eth_call even more powerful than it already is.

Geth's docs go into detail: https://geth.ethereum.org/docs/rpc/ns-eth#3-object---state-override-set.

Ganache is likely to merge their PR before the next version: https://github.com/trufflesuite/ganache/pull/2565

A similar change in hardhat would bring it to feature parity.

Brownie already supports state overrides, and I am working on a PR that uses them so that multicall is available on any block on any chain without needing to deploy anything.

**Comment by WyseNynja** [comment]
As-is, if you try to set the override argument in eth_call, the error is: `ValueError: {'code': -32602, 'message': 'Expected between 1 and 2 arguments and got 3'}`

**Comment by fvictorio** [comment]
Still relevant, although we probably won't be able to work on this at least for some months.

**Comment by drortirosh** [comment]
Any chance state overrides in eth_call is implemented in the near future?
It is already available in ganache, foundry/anvil, and of course on production nodes (geth, erigon, bor, etc)
