### ISSUE TITLE
Dependencies in sample project

### ISSUE THREAD

**Issue by shlok2740** [NomicFoundation/hardhat#2515]
I want to install Hardhat with sample project with TypeScript but there is too much dependencies. I want a simple command which can install dependencies automatically like "install-dep" or some other thing. It would be easy than this "npm i --save-dev hardhat@^2.9.1 @nomiclabs/hardhat-waffle@^2.0.0 ethereum-waffle@^3.0.0 chai@^4.2.0 @nomiclabs/hardhat-ethers@^2.0.0 ethers@^5.0.0 @nomiclabs/hardhat-etherscan@^3.0.0 dotenv@^10.0.0 eslint@^7.29.0 eslint-config-prettier@^8.3.0 eslint-config-standard@^16.0.3 eslint-plugin-import@^2.23.4 eslint-plugin-node@^11.1.0 eslint-plugin-prettier@^3.4.0 eslint-plugin-promise@^5.1.0 hardhat-gas-reporter@^1.0.4 prettier@^2.3.2 prettier-plugin-solidity@^1.0.0-beta.13 solhint@^3.3.6 solidity-coverage@^0.7.16 @typechain/ethers-v5@^7.0.1 @typechain/hardhat@^2.3.0 --legacy-peer-deps"

**Comment by fvictorio** [comment]
I'm not sure I understand this. When you create a sample project, the final step installs the dependencies, you don't have to do anything except select "Yes" when asked if you want to install the sample project's dependencies.

**Comment by shlok2740** [comment]
![Capture](https://user-images.githubusercontent.com/77238805/159627299-6363d68b-0b01-4577-a2db-1056194ad8a3.PNG)

why this extra step

**Comment by fvictorio** [comment]
Oh, I think that only happens on windows, although to be honest I don't remember why exactly, nor if it always happens. But you should be able to just copy and paste that command.

We are working on a way to have a single meta-dependency that includes all the necessary dependencies. That should make this part of the project creation way easier.

**Comment by shlok2740** [comment]
Thanks for the reply. I appreciate the effort you guys are doing. But I just want to give one feedback that don't include versions  in the single meta-dependency that you guys will create because sometimes I have to upgrade the version of a dependency  so that it will work correctly.

**Comment by fvictorio** [comment]
Closing this for now. Thanks for the feedback @shlok2740.
