### ISSUE TITLE
The contract you want to verify was compiled with solidity 0.8.2, but your configured compiler version is: 0.8.7

### ISSUE THREAD

**Issue by henry-fi** [NomicFoundation/hardhat#2518]
when I use @nomiclabs/hardhat-etherscan verify a proxy contract，throw an error:

```
Error in plugin @nomiclabs/hardhat-etherscan: The contract you want to verify was compiled with solidity 0.8.2, but your configured compiler version is: 0.8.7.

Possible causes are:
  - You are not in the same commit that was used to deploy the contract.
  - Wrong compiler version selected in hardhat config.
  - The given address is wrong.
  - The selected network (rinkeby) is wrong.
```

I Find the proxy contract's solidity version is ^0.8.0,and my implemention contract is 0.8.7, but the proxy contract is create by @openzeppelin/hardhat-upgrades

Please how can I solve the problem of this verification contract, thank you！

**Comment by alcuadrado** [comment]
This is not an bug in hardhat. Make sure you are verifying your proxy and implementation with the correct compiler versions

**Comment by henry-fi** [comment]
But I can't specify a different version when validating the proxy contract.

```
npx hardhat verify --network mainnet DEPLOYED_PROXY_CONTRACT_ADDRESS
```

**Comment by rubydog** [comment]
@henry-fi Did you find a solution for this? I am having same issue.

**Comment by 0x3bfc** [comment]
@henry-fi I am also still experiencing the same issue. The proxy pattern is `UUPS`.

**Comment by alcuadrado** [comment]
You are trying to verify the proxy, but you want to verify the implementation instead.

**Comment by 0x3bfc** [comment]
Yes, I did that and it worked and the nice thing about the Etherscan that it is also automatically match the bytecode of the proxy contract. So no need to verify the proxy.
