### ISSUE TITLE
How To Clean Hardhat's Cache

### ISSUE THREAD

**Issue by justChargin** [NomicFoundation/hardhat#2519]
I deployed and verifyed a contract then i want to deploy and verify another contract but hardhat verify method is throwing an error because its looking for old contracts artifacts/build-info/xx.json

How can i clean cache? I tried to run npx hardhat clean before tring to verify and deploy another contract

**Comment by matt-user** [comment]
Hardhat clean and hardhat compile should generate new build artifacts in the artfacts folder.  You should then be able to use these new build artifacts to deploy your updated contracts.  You can then use you verify the new addresses of your updated contracts.  What is the exact error you are getting?
