### ISSUE TITLE
Impossible to run forked node on latest HH version

### ISSUE THREAD

**Issue by VasilyGerrans** [NomicFoundation/hardhat#2528]
**Steps to reproduce:**

1. `npm init -y`
2. `npx hardhat` and select to create a config file
3. `npm i hardhat`
4. `npx hardhat node --fork https://eth-mainnet.alchemyapi.io/v2/<key>` as per https://hardhat.org/hardhat-network/guides/mainnet-forking.html#forking-from-mainnet

Output: `Error HH604: Error running JSON-RPC server: Expected 'isActivatedEIP' to only be called with 2930 or 1559`

Never had this error before. I can only assume this is some sort of problem with either the latest Hardhat or the latest Ethereumjs.

**Comment by yellowBirdy** [comment]
if you fork a blockNumber from before London (e.g. 12964900)  it works

**Comment by asafyish** [comment]
Using an old blockNumber indeed solves the problem, but that's a really old blockNumber, dates back to Apr-07-2021

**Comment by ezynda3** [comment]
I get the same issue when trying to fork from Polygon as well.

**Comment by asafyish** [comment]
I just run another project of mine, which forks ethereum, something that worked till now and now it's also getting that error.

**Comment by asafyish** [comment]
Tried with moralis, same error. Tried hardhat version 2.8 and 2.7, same error. I am guessing the issue is in one of the dependencies.

**Comment by VasilyGerrans** [comment]
> Tried with moralis, same error. Tried hardhat version 2.8 and 2.7, same error. I am guessing the issue is in one of the dependencies.

You are correct. @fvictorio confirmed to me on Discord that this is an issue with the recent ethereumjs release.

Although I may not be the most qualified to make this claim, I believe the cause to be the line here: https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/tx/src/eip1559Transaction.ts#L238-L240

The eip1559Transaction.ts constructor always calls `this.common.isActivatedEIP(3860)`. 

However, Hardhat extends `isActivatedEIP` to always fail for any numbers other than 2930 or 1559: https://github.com/NomicFoundation/hardhat/blob/master/packages/hardhat-core/src/internal/hardhat-network/provider/transactions/ReadOnlyValidEIP1559Transaction.ts#L65-L77

In any case, I was advised to use Yarn resolutions to downgrade to an earlier version of ethereumjs.

**Comment by asafyish** [comment]
The solution is to do:
"@ethereumjs/tx": "3.5.0"
in package.json.
that solved my issue.

**Comment by ezynda3** [comment]
Adding this to my `package.json` worked for me.
```
"resolutions": {
    "hardhat/**/@ethereumjs/tx": "3.5.0"
},
```

**Comment by aliveli186** [comment]
> > Tried with moralis, same error. Tried hardhat version 2.8 and 2.7, same error. I am guessing the issue is in one of the dependencies.
> 
> @asafyish You are correct. @fvictorio confirmed to me on Discord that this is an issue with the recent ethereumjs release.
> 
> Although I may not be the most qualified to make this claim, I believe the cause to be the line here: https://github.com/ethereumjs/ethereumjs-monorepo/blob/master/packages/tx/src/eip1559Transaction.ts#L238-L240
> 
> The eip1559Transaction.ts constructor always calls `this.common.isActivatedEIP(3860)`.
> 
> However, Hardhat extends `isActivatedEIP` to always fail for any numbers other than 2930 or 1559: https://github.com/NomicFoundation/hardhat/blob/master/packages/hardhat-core/src/internal/hardhat-network/provider/transactions/ReadOnlyValidEIP1559Transaction.ts#L65-L77
> 
> In any case, I was advised to use Yarn resolutions to downgrade to an earlier version of ethereumjs.

Upgrading nodejs to v16.14.2 solved the problem for me.
Also sometimes, forking with the same parameters (for alchemy, moralis) more than one instance causes similar issues... Make sure you're forking from only once machine.
