### ISSUE TITLE
hardhat-etherscan: NOTOK, Fail - Unable to verify

### ISSUE THREAD

**Issue by 134dd3v** [NomicFoundation/hardhat#2531]
Trying to verify our contract on arbitrum testnet, it fails displaying the following:

```
verifying ClearingHouseLogic (0x4602af97388bCc1e2249e3bbF012F9217359c5A4) ...
waiting for result...
Failed to verify contract ClearingHouseLogic: NOTOK, Fail - Unable to verify
{
  "apikey": "XXXXXX",
  "module": "contract",
  "action": "verifysourcecode",
  "contractaddress": "0x4602af97388bCc1e2249e3bbF012F9217359c5A4",
  "sourceCode": "...",
  "codeformat": "solidity-standard-json-input",
  "contractname": "contracts/protocol/clearinghouse/ClearingHouse.sol:ClearingHouse",
  "compilerversion": "v0.8.13+commit.abaa5c0e",
  "licenseType": 14
}
Etherscan sometime fails to verify when only metadata sources are given. See https://github.com/ethereum/solidity/issues/9573. You can add the option --solc-input to try with full solc-input sources. This will include all contract source in the etherscan result, even the one not relevant to the contract being verified
```

Not sure what is the reason, tried with `hardhat etherscan --network arbtest  --solc-input`, it failed with another error which makes sense, our repo contains a lot of code.

```
verifying ClearingHouseLogic (0x4602af97388bCc1e2249e3bbF012F9217359c5A4) ...
contract ClearingHouseLogic failed to submit : "NOTOK" : "Source code exceeds max accepted (500k chars) length" [object Object]
```

### Reproduction

1. git clone https://github.com/rage-trade/perpswap-contracts
2. yarn install
3. yarn etherscan --network arbtest

**Comment by 134dd3v** [comment]
This seems to be an issue with hardhat-deploy. I tried with hardhat's verify task and seems to work atm.

**Comment by PhilBrk8** [comment]
I had the same problem with hardhat. - luckily on rinkeby.
The error only got thrown for 1 of 2 contracts.

Did not change a single thing, but I tried to re-deploy and re-verify - it reused the already verified contract, deployed the other one again and verification than worked. Don´t ask me why, but maybe it helps if you just try again.
