### ISSUE TITLE
Tutorial links to depleted Ropsten faucet

### ISSUE THREAD

**Issue by tangjm** [NomicFoundation/hardhat#2533]
![Section 7 of the tutorial](https://hardhat.org/tutorial/deploying-to-a-live-network.html)
The link to a Ropsten faucet at the bottom links to a depleted faucet.

**Comment by alcuadrado** [comment]
Hey @tangjm,

The image is broken. Can you explain what you wanted to show or post a new one?

**Comment by tangjm** [comment]
> 

It was this one. https://hardhat.org/tutorial/deploying-to-a-live-network.html

![image](https://user-images.githubusercontent.com/91475630/161822166-9d41616f-2ffc-43af-8b7b-11ba5965423b.png)

The "Here's the one for Ropsten" link links to a depleted faucet as shown in the image above.

**Comment by fvictorio** [comment]
Still relevant, but I can't find a working Ropsten faucet. Maybe we should use another testnet in the tutorial?

**Comment by tangjm** [comment]
> Still relevant, but I can't find a working Ropsten faucet. Maybe we should use another testnet in the tutorial?

Perhaps put a placeholder to let readers know about this for now and add the link a working testnet later on?
