### ISSUE TITLE
error hh600:compilation failed 

### ISSUE THREAD

**Issue by KarenRozario** [NomicFoundation/hardhat#2535]

**Comment by KarenRozario** [comment]
Error hh600 , undeclared identifier

**Comment by KarenRozario** [comment]
My code:

//SPDX-License-Identifier: MIT

pragma solidity ^0.8.1;

//import some open zeppelin contracts\
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/utils/Counters.sol";

import "hardhat/console.sol";

contract MyEpicNFT is ERC721URIStorage {

  using Counters for Counters.Counter;
  Counters.Counter private_tokenIds;

  constructor() ERC721 ("SquareNFT", "SQUARE") {
    console.log("This is my NFT contract! :) ");
  }
  function makeAnEpicNft() public {
    uint256 newItemId = _tokenIds.current();

    _safeMint(msg.sender, newItemId);

    _setTokenURI(newItemId, "INSERT_YOUR_JSON_URL_HERE");
    console.log("An NFT w/ ID %s has been minted to %s", newItemId, msg.sender);

    _tokenIds.increment();
  }
}

**Comment by alcuadrado** [comment]
Hi there, and thanks for using Hardhat!

We don't use Github issues for support about how to use it, but exclusively for bugs and feature requests. If you need help, please use [our Discord server](https://hardhat.org/discord) instead.
