### ISSUE TITLE
[hardhat-solpp] Custom compilation path

### ISSUE THREAD

**Issue by rafagalan** [NomicFoundation/hardhat#2538]
Feature request:

I've encountered a problem while using this plugin: I need to **specify the destination folder** for the compiled contracts (some params depend on the chain), but I can't since the **path is hardcoded**. It's fairly simple to solve, just adding an optional param for the path and defaulting it to the actual path should make it, I guess I could even do it myself.

**Comment by alcuadrado** [comment]
Hi there, and thanks for using Hardhat!

We don't use Github issues for support about how to use it, but exclusively for bugs and feature requests. If you need help, please use [our Discord server](https://hardhat.org/discord) instead.

Note that this feature has been available from day 1 though. https://hardhat.org/config/#path-configuration

**Comment by rafagalan** [comment]
Sorry, I don't think I explained myself well, I was refering to the [solpp plugin ](https://www.npmjs.com/package/@nomiclabs/hardhat-solpp). The feature request is to add an option to specfify the path of the processed contracts (cache/solpp-generated-contracts). I could do it myself

**Comment by alcuadrado** [comment]
Oh, I see! If you look at the Hardhat plugin sample there's an example about how to add a new path to the config. Happy to review a pr for this!
