### ISSUE TITLE
how to verify transparent proxy  plugin hardhat-etherscan

### ISSUE THREAD

**Issue by henry-fi** [NomicFoundation/hardhat#2539]
When I deploy the upgradeable contract using @openzeppelin/hardhat-upgrades, there will be 3 contracts, transparentProx & ProxyAdmin & LogicContract, how do I verify these 3 contracts, especially the proxy contract?

```
npx hardhat verify --network mainnet DEPLOYED_CONTRACT_ADDRESS
```
I changed the contract address to the logical contract, the verification is successful, but I can't see the "Read as Proxy" and "Write as Proxy" buttons on etherscan.

How to realize the association between the proxy contract and the logic contract？

Thanks!

**Comment by fvictorio** [comment]
Hey @henry-fi, can you share the address of the contract?

**Comment by henry-fi** [comment]
> 

proxy contract: https://kovan.etherscan.io/address/0xfcd4e4154e736348c18771d701d6af184fc6fdac
implemention contract: https://kovan.etherscan.io/address/0x3cf1d2ecc94da77f663adad5ca09dc099ec2b925

**Comment by fvictorio** [comment]
Hmm, I see.

@Enigmatic331 sorry for the tag, but could you explain how this works? Here both the proxy and the implementation are verified, but the "Read/Write as proxy" don't show up. It does show up in the contract linked in the "Similar Match Source Code" contract.

My guess is that the proxy contract is not actually verified here, so you get a preview of another source code that produces the same bytecode, but that the "Read/write as proxy" tabs won't show up until the proxy is actually verified. Is that correct?

**Comment by henry-fi** [comment]
> Hmm, I see.
> 
> @Enigmatic331 sorry for the tag, but could you explain how this works? Here the implementation is verified, but the "Read/Write as proxy" tabs don't show up. It does show up in the contract linked in the "Similar Match Source Code" contract.
> 
> My guess is that the proxy contract is not actually verified here, so you get a preview of another source code that produces the same bytecode, but that the "Read/write as proxy" tabs won't show up until the proxy is actually verified. Is that correct?

When we normally deploy an upgradeable contract, the proxy contract will have two extra buttons, but it does not appear, as shown below:
![11](https://user-images.githubusercontent.com/94779913/161600769-5fc75e5f-b099-4623-b738-7a8496426074.jpg)

But the contract I deployed and verified with hardhat doesn't work.

**Comment by henry-fi** [comment]
> @henry-fi On your proxy's Contract tab (as in your screenshot), on the right side, click "More Options" -> "Is this a proxy?", then click Verify with that proxy's address.
> 
> ![Screen Shot 2022-04-04 at 2 00 48 PM](https://user-images.githubusercontent.com/29640130/161604028-388b425e-1ca7-4635-8834-24e36d6abaf9.png)

wow! It works to me, you saved my time. But do I have to do this every time I verify, is my verification method wrong?

**Comment by ericglau** [comment]
@henry-fi Your verification method looks right. 
Usually you would only need to verify your implementation contract, since the proxy contract should have a similar match on the network (as seen in your example).  But the above manual step is still needed for your proxy to be recognized in Etherscan.  For reference, [here](https://forum.openzeppelin.com/t/how-to-verify-a-contract-on-etherscan-bscscan-polygonscan/14225#upgradeable-contracts-and-proxies-11) is some additional info about proxy verification.

**Comment by henry-fi** [comment]
> here

However, when using truffle to deploy the contract and truffle-plugin-verify for verification, the proxy contract can be specified directly in the parameters, and the verification can be completed, and the association has been automatically completed on etherscan.

**Comment by jcbdev** [comment]
I have this at the bottom of my upgrade script to get around this issue but there is no reason why this could not be implemented in the verify function
```
const requestUrl = `${apiUrl}?module=contract&action=verifyproxycontract&apiKey=${process.env.ETHERSCAN_API_KEY}`;
const response = await axios.post(requestUrl, `address=${proxyAddress}`);
```

**Comment by ericglau** [comment]
I am working on adding proxy verification to the @openzeppelin/hardhat-upgrades plugin, and plan to override the `verify` command to include verification of the proxy contracts, implementation, as well as calling Etherscan's verifyproxycontract API to link the proxy to the implementation.  Feel free to subscribe to or provide comments on the issue at https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/242

**Comment by ericglau** [comment]
Proxy verification is now available with the latest version of [`@openzeppelin/hardhat-upgrades`](https://docs.openzeppelin.com/upgrades-plugins/1.x/hardhat-upgrades) with its [`verify` task](https://docs.openzeppelin.com/upgrades-plugins/1.x/api-hardhat-upgrades#verify) which extends hardhat-etherscan's `verify`.
