### ISSUE TITLE
NPX Hardhat Not Inititating 

### ISSUE THREAD

**Issue by Centori** [NomicFoundation/hardhat#2543]
Hi,I followed all the installation steps steps but when i run npx harhat i dont get a prompt to initiate a new project, I get this :

Hardhat version 2.9.2

Usage: hardhat [GLOBAL OPTIONS] <TASK> [TASK OPTIONS]

GLOBAL OPTIONS:

  --config              A Hardhat config file. 
  --emoji               Use emoji in messages. 
  --help                Shows this message, or a task's help if its name is provided 
  --max-memory          The maximum amount of memory that Hardhat can use. 
  --network             The network to connect to. 
  --show-stack-traces   Show stack traces. 
  --tsconfig            A TypeScript config file. 
  --verbose             Enables Hardhat verbose logging 
  --version             Shows hardhat's version. 

AVAILABLE TASKS:

  accounts      Prints the list of accounts
  check         Check whatever you need
  clean         Clears the cache and deletes all artifacts
  compile       Compiles the entire project, building all artifacts
  console       Opens a hardhat console
  flatten       Flattens and prints contracts and their dependencies
  help          Prints this message
  node          Starts a JSON-RPC server on top of Hardhat Network
  run           Runs a user-defined script after compiling the project
  test          Runs mocha tests

To get help for a specific task run: npx hardhat help [task]

How can I resolve this please?Ive been grappling with it for a while.Thanks

**Comment by alcuadrado** [comment]
Hi there, and thanks for using Hardhat!

We don't use Github issues for support about how to use it, but exclusively for bugs and feature requests. If you need help, please use [our Discord server](https://hardhat.org/discord) instead.

You are getting that because you have a config file already. Use `--verbose` to figure out where and delete it.
