### ISSUE TITLE
What are the parameters needed to verify an address via a task?

### ISSUE THREAD

**Issue by defido** [NomicFoundation/hardhat#2547]
`NomicLabsHardhatPluginError: The selected network is hardhat. Please select a network supported by Etherscan.`

```
task("verifytest",
"Verify all the contracts on all the networks!").setAction(async (_, hre) => {
  try {
      await hre.run(`verify:verify`, { <----- This is in the documents, but there's nothing about setting a specific network such as bscTestnet, mumbai etc.
      address: process.env.VERIFY_THIS_ADDRESS,
      network: hre.config.networks[0],
      constructorArguments: args,
    });
  } catch (error) {
    console.log(error)
  }
});
```

```
await hre.run(`verify:bscTestnet` <--- Is this it?
await hre.run(`verify:verify:bscTestnet` <--- Or this? 
```

Just want to be able to set which network to verify, such as bscTestnet, mumbai etc

[DOCS](https://hardhat.org/plugins/nomiclabs-hardhat-etherscan.html) <-- I've read the docs on this, but nothing specific about setting a chain.
```
await hre.run("verify:verify", {
  address: contractAddress,
  constructorArguments: [
    50,
    "a string argument",
    {
      x: 10,
      y: 5,
    },
    "0xabcdef",
  ],
});
```

**Comment by defido** [comment]
[Found more completed tutorial here](https://docs.avax.network/build/tutorials/smart-contracts/verify-smart-contract-using-hardhat-and-snowtrace/)

Network comes from the terminal input `--network <NETWORK>` ie `--network <mumbai>`

**Comment by albatros-github** [comment]
this worked for me:

HARDHAT_NETWORK=mumbai ts-node utils/verify.ts 0xabDFaaaaae232abc3Ed...


* verify.ts script:
`
import { run } from "hardhat"

const verify = async (contractAddress: string, args: any[], contract?: string) => {
  console.log("Verifying contract...")
  try {
    if (typeof contract !== 'undefined') {
      await run("verify:verify", {
        address: contractAddress,
        constructorArguments: args,
        contract,
      })  
    } else {
      await run("verify:verify", {
        address: contractAddress,
        constructorArguments: [], //args
      })
    }
  } catch (e: any) {
    if (e.message.toLowerCase().includes("already verified")) {
      console.log("Already verified!")
    } else {
      console.log(e)
    }
  }
}

export default verify



verify(process.argv[2], [process.argv[3]])
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error)
        process.exit(1)
    })
`
