### ISSUE TITLE
Undefined on Hardhat Using Different Account

### ISSUE THREAD

**Issue by gungunfebrianza** [NomicFoundation/hardhat#2550]
Hello guys

i am trying to use different account for testing, then i follow the examples here : 
https://hardhat.org/tutorial/testing-contracts.html#using-a-different-account

but when i am debugging the variables seems its not exist, i got undefined look here :
![gambar](https://user-images.githubusercontent.com/5908094/160891391-1470d849-2c0c-4895-be1b-8aa924b68fb7.png)

do i miss the steps to config the addresses ?  

thank you

**Comment by fvictorio** [comment]
I think the debugger is stopping at the second assignment (see the little arrow next to `addr1`), so those variables are not assigned yet.
