### ISSUE TITLE
`hh node` logging doesn't work by default

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#2551]
I think this was broken by https://github.com/NomicFoundation/hardhat/pull/2477

It does work if you explicitly set `loggingEnabled: true`

**Comment by kenxdrgn** [comment]
> I think this was broken by #2477
> 
> It does work if you explicitly set `loggingEnabled: true`

Even I set `loggingEnabled: true`, logging is still working for me.
Could you share your hardhat.config.js?

**Comment by fvictorio** [comment]
Fixed in [`hardhat@2.9.3`](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.9.3).
