### ISSUE TITLE
Error in plugin @nomiclabs/hardhat-etherscan: Failed to send contract verification request 

### ISSUE THREAD

**Issue by mastercheff-alfajor** [NomicFoundation/hardhat#2555]
I am trying to verify smartcontracts with the plugin hardhat verify but I am not able to do it.
I got this and issue that the contract doesn't have bitecode.
Could you please help on this?
s
PS C:\Users\Alan\projects\rockfinance-contracts> npx hardhat verify --network bscmainnet 0x975315C1c0b6A621B4fDB3EA3Db873add0d2a22a 0x9D251697Fa46d91161490bCF72871A72b32865ab
Nothing to compile
Error in plugin @nomiclabs/hardhat-etherscan: Failed to send contract verification request.
Endpoint URL: https://api.bscscan.com/api
Reason: The Etherscan API responded that the address 0x975315C1c0b6A621B4fDB3EA3Db873add0d2a22a does not have bytecode.
This can happen if the contract was recently deployed and this fact hasn't propagated to the backend yet.
Try waiting for a minute before verifying your contract. If you are invoking this from a script,
try to wait for five confirmations of your contract deployment transaction before running the verification subtask.

Thanks

**Comment by alcuadrado** [comment]
Hola,

Are you running behind a proxy? Have you waited a few minutes and tried again?

**Comment by mastercheff-alfajor** [comment]
Hola Patricio,
Veo que sos argentino al igual que yo.
No estoy corriendo detras de ningun proxy. Solo desde la conexion de mi casa.
El contrato lo deploye ya hace un rato. Tambien ejecute npx hardhat clean y verify otra vez pero lo mismo.
Corri las verificaciones en testnet y va bien.
No se me ocurre que mas puede ser.

**Comment by alcuadrado** [comment]
(Let's keep the conversation in English so that other team members and stakeholders can join)

Can you please provide a step-by-step guide to reproduce this?

**Comment by ezeamaka2** [comment]
For some time now, this has been an issue. I have tried multiple times and failed. So, recently I started using Remix to verify my smart contract on Etherscan using the Etherscan Verification Plugin on Remix IDE. All you need is to provide your Ettherscan API, and the smart contract address, and pass in the required parameters (if the constructor requires it). However, I have written a detailed guide on how to do this here ([How to verify smart contract on Etherscan with Remix IDE](https://bit.ly/3u2fk4A))

**Comment by codingwithdidem** [comment]
I'm getting the same error. 

If you are invoking this from a script,
try to wait for five confirmations of your contract deployment transaction before running the verification subtask


Can anyone tell me how to wait for 5 confirmations?

**Comment by mastercheff-alfajor** [comment]
Hi,
I am using hardhat-deploy script. I created 3 js deploy scripts in which ones I am using for deploying the contracts.
The workaround I found to this is to remove the folder created under deployments for the network we want to deploy.
Once we remove this folder we compile and run deploy scripts again so the network folder is created with all the content in there. 
I was able to verify the contracts following this instructions.

**Comment by alcuadrado** [comment]
Do you have a link to reproduce this, @mastercheff-alfajor ?

**Comment by mastercheff-alfajor** [comment]
Hi @alcuadrado ,
I attach screenshots with my  scripts.
![1](https://user-images.githubusercontent.com/83844431/161851115-f2a9c974-50bb-47e9-a662-4575a09ade83.png)
![2](https://user-images.githubusercontent.com/83844431/161851125-60f4a353-4ac5-4448-9018-53a11eb5fae4.png)
![3](https://user-images.githubusercontent.com/83844431/161851138-7733ad2b-372d-44c9-af91-b7fffc9b5485.png)

So then I run the scripts:
npx hardhat deploy --network bmainet
and then to verify them I run the command:
npx hardhat verify --network bmainet 0x8B1209Bf46b18a9aC5AaaD7bC2e2D256710c51f6
Then I got this issue

**Comment by alcuadrado** [comment]
I'm closing this issue as it doesn't have a useful reproduction. We don't have enough time to re-type everything from your screenshots, sorry. Please feel free to open a new one if you create a repro with a to reproduce it.

**Comment by donlaiq** [comment]
I had the same problem with the plugin hardhat.
For me, it worked by deleting the folders 'artifacts' and 'cache' and rerunning the script.
I hope it helps.

**Comment by progressaded** [comment]
Hi everyone  , 
I had the same issue and I solved this by just running "yarn deploy --network truffle" again  , I got a new contract adress and verifying the new contact adress worked just fine  .

Hope it helps someone

**Comment by one-pack-stomach-man** [comment]
when i wrote script code in package.json
`"verify": "hardhat verify --network rinkeby 0xf6263ca43806ceafe1fcb77656b3d03fa43c00cb 'hello world!'",`
i met the same problem.
later I change it to 
`"verify": "hardhat verify --network rinkeby 0xf6263ca43806ceafe1fcb77656b3d03fa43c00cb 'hello world!'",`
It's worked.

**Comment by ezeamaka2** [comment]
This is interesting. I will have to try it

**Comment by SakanaSachi** [comment]
> Hola,
> 
> Are you running behind a proxy? Have you waited a few minutes and tried again?

Hi, I  am getting the same error, but I am living in China so I have to use a proxy, does that mean I can never get my contract verified?

**Comment by Mmmintaka** [comment]
> > Hola,
> > Are you running behind a proxy? Have you waited a few minutes and tried again?
> 
> Hi, I am getting the same error, but I am living in China so I have to use a proxy, does that mean I can never get my contract verified?

G!

**Comment by alcuadrado** [comment]
Can you please open a new issue about using this extension behind a proxy? Thanks!
