### ISSUE TITLE
Is it possible to automate multiple chains at one time?

### ISSUE THREAD

**Issue by defido** [NomicFoundation/hardhat#2557]
Currently I have a task that allows me to pull the constructor & address, but not the networks. Which would be handy to verify multiple chains. 

Is there anyway to input the chains name into the task instead of the terminal?

```npx hardhat verify --network bscTestnet```

Lets say I want to do 

``` npx hardhat verify --network bscTestnet mumbai fantomTestnet```

Or

``` npx hardhat verify --network chains```

Where chains was an array or chains.

But to do more then one chain on a loop, there is no `network` key in the object or array that you look for in the verification script.

**Comment by lucas-janon** [comment]
Hi @defido, looking to do the same, did you find anything?

Thanks
