### ISSUE TITLE
It's not possible to mine multiple blocks with the same timestamp

### ISSUE THREAD

**Issue by alexdupre** [NomicFoundation/hardhat#2560]
There are EVM blockchains with sub-second block production frequency. It'd be very useful if hardhat could be configured to mine blocks with the same timestamp instead of always requiring increasing timestamps.

**Comment by alexdupre** [comment]
I might have a patch ready in the next days. I was thinking to add a new rpc command like `evm_noTimeIncrement` to have all blocks mined with the same timestamp. This would be ideal for any time based testing, that can then leverage the `evm_setNextBlockTimestamp` and `evm_increaseTime` to have fully deterministic test cases.

**Comment by alexdupre** [comment]
The issue is still relevant, WDYT @feuGeneA ?

**Comment by alcuadrado** [comment]
@alexdupre, i think this would better fix a hardhat network config, more than an RPC method. WDYT?

**Comment by alexdupre** [comment]
@alcuadrado the PR includes both a hardhat network config param and an RPC method, for maximum flexibility.
