### ISSUE TITLE
Extremely slow test startup

### ISSUE THREAD

**Issue by kenvogg** [NomicFoundation/hardhat#2562]
Started experiencing really slow test execution `npx hardhat test` / `hh test` recently. With verbose it looks like:
```
hh test --no-compile --verbose --show-stack-traces
  hardhat:core:config Loading Hardhat config from /path/to/hardhat.config.ts +0ms
  hardhat:core:global-dir Looking up Client Id at /root/.local/share/hardhat-nodejs/analytics.json +0ms
  hardhat:core:global-dir Client Id found: 2814fd0c-5d4e-4ee7-b334-24c0cd19c176 +1ms
  hardhat:core:analytics Sending hit for /task/builtin +0ms
  hardhat:core:analytics Hit payload: {"v":"1","t":"pageview","tid":"UA-117628706-3","cid":"28142d0c-5d4e-4ee7-b334-24cadaa2576","dp":"/task/builtin","dh":"cli.hardhat.org","ua":"Node/v16.13.2 (X11; Linux x86_64)","cs":"Developer","cm":"User Type","cd1":"hardhat-project","cd2":"Developer","cd3":"Hardhat 2.9.2"} +1ms
  hardhat:core:hre Creating HardhatRuntimeEnvironment +0ms
  hardhat:core:hre Running task test +789ms
  hardhat:core:hre Running test's super +1ms
  hardhat:core:hre Running task test:get-test-files +0ms
  hardhat:core:analytics Hit for "/task/builtin" sent successfully +908ms
  hardhat:core:hre Running task test:setup-test-environment +125ms
  hardhat:core:hre Running task test:show-fork-recommendations +1ms
  hardhat:core:hre Running task test:run-mocha-tests +0ms
  hardhat:core:hre Running test:run-mocha-tests's super +1s
  hardhat:core:hre Creating provider for network hardhat +16s

  // ... 5 minutes later ...
  // describe(), context(), it() mocha test output starts to run/print 
```
I had no idea what is happening in the `5 minutes later` section. 

**Environment**: 

WSL2 / Windows 11
Hardhat 2.9.2 (also tried 2.9.1, same issue)
TypeScript exclusively
Yarn
Using some hardhat extensions, full list of dependencies w/ versions are are:
```
        "@ethersproject/hardware-wallets": "^5.6.0",
        "@nomiclabs/hardhat-ethers": "^2.0.5",
        "@nomiclabs/hardhat-etherscan": "^3.0.0",
        "@nomiclabs/hardhat-solhint": "^2.0.0",
        "@nomiclabs/hardhat-waffle": "^2.0.2",
        "@typechain/ethers-v5": "^9.0.0",
        "@typechain/hardhat": "^4.0.0",
        "@types/bn.js": "^5.1.0",
        "@types/bs58": "^4.0.1",
        "@types/chai": "^4.3.0",
        "@types/mocha": "^9.1.0",
        "@types/node": "^17.0.10",
        "@types/readline-sync": "^1.4.4",
        "base64-sol": "^1.1.0",
        "chai": "^4.3.4",
        "cross-env": "^7.0.3",
        "dotenv": "^16.0.0",
        "ethereum-waffle": "^3.4.0",
        "ethers": "^5.5.4",
        "hardhat": "^2.9.2",
        "hardhat-contract-sizer": "^2.4.0",
        "hardhat-gas-reporter": "^1.0.7",
        "hardhat-tracer": "^1.0.0-alpha.6",
        "husky": "^7.0.1",
        "prb-math": "^2.4.3",
        "prettier": "^2.5.1",
        "prettier-plugin-solidity": "^1.0.0-beta.19",
        "readline-sync": "^1.4.10",
        "solhint-plugin-prettier": "^0.0.5",
        "solidity-coverage": "^0.7.18",
        "ts-node": "^10.4.0",
        "tsconfig-paths": "^3.12.0",
        "typechain": "^7.0.0",
        "typescript": "^4.5.5",
        "yarn-upgrade-all": "^0.6.1"
```

Would love to know how to get more information about what is taking so long (what's happening in the `5 minutes later` step), and any possible solutions to this issue. Thanks!

**Comment by alcuadrado** [comment]
Hi @kenvogg,

I suspect you do a lot of slow things in your before/beforeEach blocks.

Which plugins are you using?

**Comment by dminglv** [comment]
Hello! @kenvogg @alcuadrado 

I found the same problem in myself and decided to figure out what happened...

I noticed that the tester performs a huge number of requests to the Web3 node. Hundreds!

I discovered this through the Alchemy interface and carefully looked at what it was trying to do. So, he's trying to get the status of S**OMEONE ELSE's transactions**! And this significantly slows down the testing process.

**Comment by alcuadrado** [comment]
Can you provide steps to reproduce it, @dminglv?

Starting a forked hardhat network does make a few requests, but it's definitely not 100s.

**Comment by kenvogg** [comment]
Actually, I think the issue *was* with my environment, but it was very random for me which made it hard to track down (some times it would be immediate, other times it would be slow like this). I was able to permanently solve by reducing some of the other processes going on in my computer.

Still it might be useful to get some debug info *when this is the case* during that verbosity output.

**Comment by ljw2652552** [comment]
I found the same problem too... 
Is now the problem solved?

**Comment by RevolutionWind** [comment]
same problem + 1.
I saw u closed this issue, have u solved this forever? I can reproduce this situation which costed me 100 seconds every time

**Comment by fvictorio** [comment]
@RevolutionWind can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by RevolutionWind** [comment]
> @RevolutionWind can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?
Thx🥰. `https://github.com/RevolutionWind/hardhat-fund-me-js`

**Comment by RevolutionWind** [comment]
> @RevolutionWind can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?



> > @RevolutionWind can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?
> > Thx🥰. `https://github.com/RevolutionWind/hardhat-fund-me-js`

U can just run with ` yarn hardhat test`

**Comment by fvictorio** [comment]
@RevolutionWind do you have Rosetta installed?

**Comment by RevolutionWind** [comment]
> @RevolutionWind do you have [Rosetta](https://support.apple.com/en-us/HT211861) installed?

Yes.

**Comment by fvictorio** [comment]
@RevolutionWind hey, sorry for not responding before. I don't know what could be the reason here.

Can you open a new issue about this? Please include:

1) The repo that reproduces the problem. If possible, try to remove all the code and plugins you can until you have the smaller possible code that reproduces the problem. I know this is a bit involved, but it would help us immensely.
2) All the details you can about the systems you are using (OS, version, hardware, etc.)

Thanks!
