### ISSUE TITLE
problem installing hardhat.  node version 17.8.0

### ISSUE THREAD

**Issue by donyetun** [NomicFoundation/hardhat#2570]
hi,

I just got new mac book and just installed node from "brew install node"
and I got node v17.8.0 and npm v8.6.0

now, when I do npm install --save-dev hardhat.. I got the following warnning 

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'hardhat@2.9.3',
npm WARN EBADENGINE   required: { node: '^12.0.0 || ^14.0.0 || ^16.0.0' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.6.0' }
npm WARN EBADENGINE }

and when I run hardhat, i got the following error..

You are using a version of Node.js that is not supported by Hardhat, and it may work incorrectly, or not work at all.

Please, make sure you are using a supported version of Node.js.

To learn more about which versions of Node.js are supported go to https://hardhat.org/nodejs-versions

how do I downgrade node or upgrade hardhat?

Cheers,

ye

**Comment by dminglv** [comment]
@donyetun you can to select node version, like a `brew install node@16`.

You should to delete your current version:` brew uninstall node`
After make unlink `brew unlink node`
And install stable version  `brew install node@16`

If you have problem with run 16 version, link it `brew link node@16`

**Comment by donyetun** [comment]
thanks.. it work on node uninstall and re-install.

now, I have another stupid problem.  I installed hardhad in $HOME but I want to uninstall it and install again in different sub-directory.   I couldn't find any documents on how to uninstall

**Comment by dminglv** [comment]
@donyetun 
`npm uninstall -g hardhat`

**Comment by donyetun** [comment]
thank you

**Comment by Elishaokon13** [comment]
I have same problem on my Android termux
