### ISSUE TITLE
📜 :docs hardhat-ethers plugin should be at the forefront of the documentation

### ISSUE THREAD

**Issue by AlphaDio** [NomicFoundation/hardhat#2574]
I just spent close to an hour searching for information about the elements exported by the ethers instance in the Hardhat Runtime.

I think this info should be at the forefront of your doc, since hre.ethers (alongside hre.provider and hre.providers) is one of the most important object your users will interact with.

Thank you,

**Comment by fvictorio** [comment]
Hi @AlphaDio, this is a really good point. The reason it's done like that is that `hardhat-ethers` is a plugin, and you don't _have_ to use it to use Hardhat (for example, you could use `hardhat-web3`). But that was the original reasoning. Nowadays the vast majority of users of Hardhat also use ethers, so it doesn't make sense to have a "plugin neutral" documentation.

Soon we are going to work on revamping our docs, and part of that is being more opinionated on things like these. I'm pretty sure that this suggestion will be included, so I'm going to close this issue for bookkeeping reasons. Thanks a lot for the feedback!
