### ISSUE TITLE
Ability to verify on other chains like Cronos, Milkomeda, etc.

### ISSUE THREAD

**Issue by githubuserpro12345** [NomicFoundation/hardhat#2575]
etherscan currently can only verify contracts on a set of predefined chains. Please update etherscan to be able to verify on any chain for example Cronos, Milkomeda etc.

**Comment by fvictorio** [comment]
For the record: there is a Release Candidate version of hardhat-etherscan that has support for custom explorers. Check [this comment](https://github.com/NomicFoundation/hardhat/pull/2441#issuecomment-1116382707) to learn more.
