### ISSUE TITLE
HardhatError: HH110: Invalid JSON-RPC response received: Apikey missed

### ISSUE THREAD

**Issue by Arrjun-Pradeep** [NomicFoundation/hardhat#2577]

**Comment by Arrjun-Pradeep** [comment]
> _No description provided._

Got fixed by changing the provider

**Comment by tenuki** [comment]
> > _No description provided._
> 
> Got fixed by changing the provider

That doesn't look like a fix for the issue...  same is happening to me with getblock.io provider.

**Comment by sturmenta** [comment]
same here, with getblock provider

**Comment by sturmenta** [comment]
I was able to get it working using [`httpHeaders`](https://hardhat.org/config#json-rpc-based-networks) field


from
```js
  networks: {
    bttc: {
      url: "https://bttc.getblock.io/mainnet/?api_key=" + BTTC_RPC_API_KEY,
      accounts: [PRIVATE_KEY],
      chainId: 199,
    },
  },
```

to
```js
  networks: {
    bttc: {
      url: "https://bttc.getblock.io/mainnet/",
      accounts: [PRIVATE_KEY],
      chainId: 199,
      httpHeaders: { "x-api-key": BTTC_RPC_API_KEY },
    },
  },
```

**Comment by tenuki** [comment]
> I was able to get it working using [httpHeaders](https://hardhat.org/config#json-rpc-based-networks) field

Yes, same here.. but.. still wonder why full url doesn't work..  (sorry I forgot to comment header solution!)
