### ISSUE TITLE
Running hardhat node asks me to create a project

### ISSUE THREAD

**Issue by incrypto32** [NomicFoundation/hardhat#2579]
Running `npx hardhat node` asks to create a new project instead of just running the node

<img width="520" alt="Screenshot 2022-04-08 at 10 25 20 AM" src="https://user-images.githubusercontent.com/44740264/162367498-66a70355-80f4-4b8f-bec5-24a1c54b0e30.png">

Expected behaviour : 
It should just run the node

**Comment by feuGeneA** [comment]
At this time you cannot run Hardhat Network (`npx hardhat node`) outside of a Hardhat project. However, we do have on our roadmap the intention to do what you're asking for, and it would be a part of https://github.com/NomicFoundation/hardhat/issues/2080

**Comment by jaysnel** [comment]
Getting this same issue at the moment. Did you ever find a solution?
