### ISSUE TITLE
Add `src/tsconfig.json` to an `.npmignore` file in relevant packages

### ISSUE THREAD

**Issue by prestwich** [NomicFoundation/hardhat#2582]
Because hardhat `tsconfig.json` files extend a base config that is outside the package, they cause TS language servers (e.g. in VSCode) to error, as the base config they extend is unavailable

example file:
https://github.com/NomicFoundation/hardhat/blob/48df7d37cccc8ce72233d73f2866c159c4212b74/packages/hardhat-core/src/tsconfig.json

To solve this, introduce a `.npmignore` file that excludes the tsconfig.json

**Comment by alcuadrado** [comment]
That's a good point! Thanks
