### ISSUE TITLE
Aurora testnet invalid API key

### ISSUE THREAD

**Issue by vladikopl01** [NomicFoundation/hardhat#2589]
I constantly get an error about the wrong key, I even recreated it several times and declared several keys at once, one for eth and aurora, I thought maybe this was the problem, but it still didn’t help.

Here is an example of an error:
_Error in plugin @nomiclabs/hardhat-etherscan: Invalid API Key_

**Comment by alcuadrado** [comment]
Hi,

Thanks for opening this issue. It seems to be an etherscan issue though. Can you get in contact with them instead?

Thanks!
