### ISSUE TITLE
Unexpected revert when testing library functions with struct parameters

### ISSUE THREAD

**Issue by murderteeth** [NomicFoundation/hardhat#2592]
I have a solidity library containing a function that takes a struct as a parameter. I can call this function from a contract without a problem. But when I try testing this function directly I get an error. Further, if I copy the same function to a contract and test it, it works. Here's an example:

### contracts/library/Example.sol
```solidity
//SPDX-License-Identifier: MIT
pragma solidity ^0.8.7;

struct AB {
  uint8 a;
  uint8 b;
}

contract TheContract {
  function add(AB memory ab) public pure returns(uint8) {
    return ab.a + ab.b;
  }
}

library TheLibrary {
  function add(AB memory ab) public pure returns(uint8) {
    return ab.a + ab.b;
  }
}
```

### mocha tests
```ts
import { expect } from 'chai'
import { smock } from '@defi-wonderland/smock'
import { TheContract__factory, TheLibrary__factory } from '../../typechain/library'

describe.only('Calling with struct params', function () {
  before(async function () {
    this.theContract = await(await smock.mock<TheContract__factory>('contracts/library/Example.sol:TheContract')).deploy()
    this.theLibrary = await(await smock.mock<TheLibrary__factory>('contracts/library/Example.sol:TheLibrary')).deploy()
  })

  it('add AB struct with the contract', async function () {
    expect(await this.theContract.add([1, 1])).to.eq(2)
  })

  it('add AB struct with the library', async function () {
    expect(await this.theLibrary.add([1, 1])).to.eq(2)
  })
})
```

### result
```console
  Calling with struct params
    ✔ add AB struct with the contract (73ms)
    1) add AB struct with the library


  1 passing (5s)
  1 failing

  1) Calling with struct params
       add AB struct with the library:
     Error: Transaction reverted: library was called directly
    at TheLibrary.<unknown> (contracts/library/Example.sol:15)
    at HardhatNode._gatherTraces (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1652:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)
    at async HardhatNode.runCall (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:615:20)
    at async EthModule._callAction (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:353:9)

```

The contract test passes, but the library test fails. I've tested many library functions without a problem in the past, so I believe the error `Transaction reverted: library was called directly` is a mislead per https://github.com/NomicFoundation/hardhat/issues/1873

**Comment by ClementWalter** [comment]
same problem using solidity 0.8.12 and hardhat 2.8.0

**Comment by ClementWalter** [comment]
Is there any news on this? @murderteeth did you have a workaround? this is becoming critical for me atm.

**Comment by murderteeth** [comment]
> Is there any news on this? @murderteeth did you have a workaround? this is becoming critical for me atm.

In my case, I use a wrapper function that "destructures" the struct's fields.. for example:

```solidity
library TheLibrary {
  function add(AB memory ab) public pure returns(uint8) {
    return ab.a + ab.b;
  }

  function add_test_wrapper(uint8 a, uint8 b) public pure returns(uint8) {
    return add(AB(a, b));
  }
}
```

This is fine for me because my struct's don't have too many fields. If your struct has more than 16 though, you'll run out of stack.

**Comment by ClementWalter** [comment]
ok thanks for sharing, I have quite a lot of these so I'm not going to make it this way; will try to spend some time investigating this this week hopefully

**Comment by ClementWalter** [comment]
actually I'm not sure that this is a hardhat issue; I asked the question on SO as well https://ethereum.stackexchange.com/questions/126507/can-a-library-have-a-public-function-using-struct-memory

**Comment by hroussille** [comment]
> Solidity libraries are not designed to be called off-chain. Smart contracts call library functions. That's why you are getting this error: `Transaction reverted: library was called directly`

That partly contradicts the [documentation](https://solidity-fr.readthedocs.io/fr/latest/contracts.html?highlight=libraries#libraries) : 

>  Library functions can only be called directly (i.e. without the use of DELEGATECALL) if they do not modify the state (i.e. if they are view or pure functions), because libraries are assumed to be stateless.

This function is pure, and should be allowed to be called directly.

After taking a look to the following library from @ClementWalter post on Ethereum Stack Exchange : 

```solidity
library TheLibrary {
  function add(AB memory ab) public pure returns(uint8) {
    return ab.a + ab.b;
  }
```

It seemed to me more like an error in the ABI encoding than anything else.

The compiler checks for the following signature in the generated bytecode : `0x70c40302` which is the first 4 bytes of `keccak256("add(AB)")`. From Remix (using the generated ABI), the calldata contains the following signature : `0x2f563ac4` which is the first 4 bytes of `keccak256("add((uint8, uint8))")`

And indeed, if you were to craft the following message to call `add(AB)` with both member set to 1 : 

`0x70c4030200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001`

The result is `0x0000000000000000000000000000000000000000000000000000000000000002` as expected.

The same doesn't happen with contracts where the generated byte code check for what  the ABI exposes, I submitted [an issue](https://github.com/ethereum/solidity/issues/12947) on the solidity repo.

**Comment by murderteeth** [comment]
> Solidity libraries are not designed to be called off-chain. Smart contracts call library functions. That's why you are getting this error: `Transaction reverted: library was called directly`

See https://github.com/NomicFoundation/hardhat/issues/1873

**Comment by ClementWalter** [comment]
So I guess that a workaround could be to add a `fallback` function to redirect the call?

**Comment by nicolasguasca1** [comment]
Hey! :) any updates on this?
