### ISSUE TITLE
Add `hh init` command

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#2594]
A new hardhat project can be initialized by running `npx hardhat`. But running the same command inside a Hardhat project does something different (it prints the help). This results in a lot of users being confused when they try to initialize a project without realizing that some parent directory has a Hardhat config, because then they get the help info instead of the project initialization prompt. This happens a lot.

Instead of that behavior, we should have an explicit `npx hardhat init` command (it can be called some other way, but `init` is the obvious choice). If you **are not** inside a Hardhat project, then the usual project initialization stuff is shown. If you **are** inside a project, an error message would be shown, indicating the location of the detected Hardhat config.

`npx hardhat` will continue to have the same behavior when you are inside a project. If you **are not** inside a project, then a proper error message should be shown, explaining this and suggesting the user to run `npx hardhat init` if their intention was to initialize a project. This is very important because there is a lot of documentation and educational material out there that has the plain `npx hardhat` step.

Of course, as part of this we should also update all the relevant parts of our documentation, and let people know about this change so that they can update their docs or articles.

- [x] Merge a PR to add `init` command
- [ ] Merge a PR to update the docs. This PR should be merged after that the code is released (Docs PRs are instantly released)
- [ ] Reach out to the main tutorials/docs that are using hardhat to inform about the deprecation

**Comment by AbhinavMir** [comment]
I highly suggest this! 

Today, I had a root folder which (somehow) had a dummy `hardhat.config.js` file lying around. Because of this, in the subfolders, the help was being printed. It is probably better dev-experience to support `npx hardhat init` - happy to be assigned this if needed.

**Comment by fvictorio** [comment]
Not stale.
