### ISSUE TITLE
"anonymous crash reports and basic usage data" what?

### ISSUE THREAD

**Issue by wuya666** [NomicFoundation/hardhat#2611]
Sometimes when I create a new sample project with `npx hardhat`, I see this option in the prompted messages, but I can't seem to find any information at all in the documentations about what these "anonymous crash reports and basic usage data" are? Also there's no instruction whatsoever on how to turn this thing on/off with an already created project, and last but not the least, it seems this prompt just appears randomly, that when creating the same sample projects with exactly the same steps (`mkdir` a new folder, `npm init` in the new folder, ` npm install --save-dev hardhat` in the new folder, and run `npx hardhat` in the new folder), sometimes I get this prompt while other times the process just finishes without showing this prompt.

So anyone can explain what these "crash reports and usage data" really include? Is there anyway to turn it on/of with an existing project? And why it appears sometimes but not others when creating new sample projects? Even better if there can be something in the official documentations on this? Thanks.

**Comment by alcuadrado** [comment]
The prompt is shown once per computer. You can read what we track in our [privacy policy](https://hardhat.org/privacy-policy.html), but it's not a lot of data. We try to be as minimal with tracking as possible, respecting our users' privacy.

If you want to reset it you can run `npx hardhat --verbose`, and you'll see a log like this

```
  hardhat:core:global-dir Looking up Client Id at /Users/pato/Library/Application Support/hardhat-nodejs/analytics.json +0ms
``` 

Then, delete that file.

**Comment by wuya666** [comment]
@alcuadrado I have deleted the `analytics.json` file like you suggested, but still the "anonymous crash reports and basic usage data" prompt is not shown during the creation of a new hardhat sample project. And when I run `npx hardhat --verbose` in the newly created project, it shows the following message:

```
  hardhat:core:config Loading Hardhat config from /Users/xxx/Workspaces/solidity/hardhatsimpletest/hardhat.config.js +0ms
  hardhat:core:global-dir Looking up Client Id at /Users/xxx/Library/Application Support/hardhat-nodejs/analytics.json +0ms
  hardhat:core:global-dir Looking up Client Id at /Users/xxx/Library/Application Support/buidler-nodejs/analytics.json +5ms
  hardhat:core:global-dir Looking up Client Id at /Users/xxx/.buidler/config.json +0ms
  hardhat:core:analytics Client Id not found, generating a new one +0ms
  hardhat:core:global-dir Stored clientId xxxxxxxx-xxxx-xxx-xxxx-xxxxxxxxxxxx +3ms
  hardhat:core:hre Creating HardhatRuntimeEnvironment +0ms
  hardhat:core:hre Running task help +143ms
```

And a new file with the new `clientId` is generated at `/Users/xxx/Library/Application Support/hardhat-nodejs/analytics.json`
Are you sure this is the correct file for storing the yes/no choice of the telemetry option? It seems to store only the `clientId`, not any boolean information which may represent the yes/no choice of the option?

**Comment by KCKCC** [comment]
I'm facing the same problem, and It keeps asking me "Help us improve Hardhat with anonymous crash reports & basic usage data? (Y/n) · y" after every command.

I'm using vscode's terminal. How to store the setting? and prevent It show again. Thanks.
