### ISSUE TITLE
I'am facing this problem when trying to run my hardhat.config.js

### ISSUE THREAD

**Issue by mohamedtb20** [NomicFoundation/hardhat#2616]
C:\Users\DELL\nft_marketplace>npx hardhat test
Error HH8: There's one or more errors in your config file:

Invalid account: #0 for network: mumbai - Expected string, received function
Invalid account: #0 for network: mainnet - Expected string, received function
To learn more about Hardhat's configuration, please go to [https://hardhat.org/config/``](https://hardhat.org/config/%60%60)

**Comment by aliveli186** [comment]
Can you post your config file?

**Comment by aliveli186** [comment]
> const privatekey = fs.readFileSync(".secret").toString

Probably because you forgot the function call "()" at the end of toString(). Because of that it takes the function not the result of the functuon.

`const privatekey = fs.readFileSync(".secret").toString()`

**Comment by fvictorio** [comment]
> Probably because you forgot the function call "()" at the end of toString().

Yes, that seems to be the case. Thanks a lot for chiming in to help, @aliveli186!
