### ISSUE TITLE
Hardhat-etherscan verifying unrelated contracts

### ISSUE THREAD

**Issue by RayXpub** [NomicFoundation/hardhat#2619]
Hi,

I am running into an issue with hardhat-etherscan when verifying contracts programatically. For some of my contracts after the verification is done successfully etherscan shows completely unrelated contracts on top of the actual contract, sometimes even all my repo's contracts, even mock contracts only used for testing (sometimes ending up with 100+ contracts attached). So it seems that in some cases (I do not know what triggers it) hardhat-etherscan will attach all artifacts contract to the verification.

Surfing the web to find a solution I saw that a lot of docs like the one from [Binance](https://docs.binance.org/smart-chain/developer/deploy/hardhat-verify.html) mention this warning : "Remove any unnecessary contracts and clear the artifacts otherwise these will also be part of the verified contract." , which I have not seen in the hardhat official documentation.

The only way I see to achieve this programatically is to remove the compile task from the plugin and run it in a separate script followed by some kind of artifact clean up task removing all unrelated contracts from the folder before actually calling `verify:verify`. The problem with this approach is that it would mean retrieving each contract dependencies (contracts + libs) which would mean rewriting a lot of the plugin logic. Plus when trying to verify a batch of contracts, it would also mean doing a clean up after each verification.

I am not sure I have a good understanding of the issue nor of the potential approach to solve it. Really hope I can get some clarification and hopefully a solution.

compiler version : 0.6.12
hardhat-etherscan version : 3.0.3

**Comment by feuGeneA** [comment]
Thank you for using Hardhat. GitHub Issues are intended to be used only for known or suspected problems with Hardhat, or for feature requests.  For questions or other help, please use either [our Discord server](https://hardhat.org/discord) or [the GitHub Discussions feature](https://github.com/nomiclabs/hardhat/discussions/) instead.
