### ISSUE TITLE
Wallet addresses should print in checksum format

### ISSUE THREAD

**Issue by aathan** [NomicFoundation/hardhat#2620]
When you start a hardhat node you get wallet addresses:

```
Started HTTP and WebSocket JSON-RPC server at http://127.0.0.1:8545/

Accounts
========

WARNING: These accounts, and their private keys, are publicly known.
Any funds sent to them on Mainnet or any other live network WILL BE LOST.

Account #0: 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 (10000 ETH)
Private Key: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

```

However, those are not printed out in checksummed format. Perhaps they should be.

**Comment by feuGeneA** [comment]
Hi, and thank you for using Hardhat.

What additional value would it add to your use case if that address were to be given in a checksummed format?

**Comment by aathan** [comment]
Convenience.

Sometimes you just want to copy/paste the generated wallets somewhere. Most such places require checksummed strings these days.
