### ISSUE TITLE
unable verify for Astar network

### ISSUE THREAD

**Issue by 0xkaz** [NomicFoundation/hardhat#2622]
hardhat-verify doesn't work because not supporting for Astar.
I will create a PR for it, later. 

ref: https://docs.astar.network/integration/network-details

**Comment by fvictorio** [comment]
Hi @0xkaz, we are going to stop adding new networks to the core of `hardhat-etherscan`. Instead, we are about to release a feature that lets you add any network in your config.

You can read more about that [here](https://github.com/NomicFoundation/hardhat/tree/hardhat-etherscan-custom-explorer/packages/hardhat-etherscan#adding-support-for-other-networks). Notice that this isn't released yet, but you can install it with the `rc` branch: `npm i @nomiclabs/hardhat-etherscan@rc`

This can also be packaged into a community plugin, check [this example](https://github.com/fvictorio/hardhat-custom-chain-plugin-example) to learn how. I would wait until the feature is properly released in the `latest` tag before doing that though.

**Comment by andabakus** [comment]
Hi @fvictorio - the link you mention with more details about the feature "that lets you add any network in your config" is broken. Can you share an update about what is current way of work for new networks? Thank you!

**Comment by fvictorio** [comment]
Sorry about that @andabakus, I fixed the link in my comment.
