### ISSUE TITLE
When using with `@typechain/hardhat`, vyper files are compiled after types are generated.

### ISSUE THREAD

**Issue by penandlim** [NomicFoundation/hardhat#2632]
I've reported this on typechain repo but thought it might be relevant here too.
https://github.com/dethcrypto/TypeChain/issues/676

> I was able to replicate this with typechain 8.0.0, @nomiclabs/hardhat-vyper 3.0.0, 
> 
> https://github.com/penandlim/TestVyperPlugins
> 
> Compiling the repo will result in correct artifacts from both solidity and vyper files but only has types from solidity.
> ```bash
> npm ci
> npx hardhat compile
> ```
> The workaround I found is to run typechain after the compile task.
> ```
> npm ci
> npx hardhat compile --no-typechain && npx hardhat typechain
> ```
> This correctly adds any types generated from vyper into the typechain output folder.

**Comment by fvictorio** [comment]
Hi @penandlim, thanks for reporting this.

I think this is only relevant for `typechain`. I'm going to tentatively close this, but please feel free to re-open it if it turns out to be a problem on our side.
