### ISSUE TITLE
hardhat-etherscan - wrong parsing boolean in constructor parameters when using cli arguments false

### ISSUE THREAD

**Issue by chervyachok** [NomicFoundation/hardhat#2635]
I have contract with bool in constructor parameters:
constructor(
  address p1,
  address p2,
  bool p3
)
Same contract deployed with p3 true for first and p3 false for second
First one with p3 true is verifying fine
Second with p3 false not
After quick researches I figured out that third parameter "false" always parsing as true and gives 1 in encoded parameters
I tried:
npx hardhat verify --network opera 0xd9...3F6 "0x3A...62" "0x86...83" "false"
npx hardhat verify --network opera 0xd9...3F6 "0x3A...62" "0x86...83" false
npx hardhat verify --network opera 0xd9...3F6 "0x3A...62" "0x86...83" "0"
npx hardhat verify --network opera 0xd9...3F6 "0x3A...62" "0x86...83" 0
All gives ...1 instead ...0 in parameters
However when I'm using --constructor-args with separate file for parameters it works like expected.

**Comment by feuGeneA** [comment]
Thank you for using Hardhat. In general, if there is a problem in Hardhat, we will need a minimal reproducible example in order to investigate it. See https://stackoverflow.com/help/minimal-reproducible-example
