### ISSUE TITLE
Network rinkeby doesn't exist

### ISSUE THREAD

**Issue by rushikeshmane10** [NomicFoundation/hardhat#2641]

**Comment by ihorbond** [comment]
@rushikeshmane10 are you sure you have it in your networks list in the hardhat.config.js file ?

**Comment by feuGeneA** [comment]
Thank you for using Hardhat. In general, if there is a problem in Hardhat, we will need a minimal reproducible example in order to investigate it. See https://stackoverflow.com/help/minimal-reproducible-example
