### ISSUE TITLE
Vyper contract function is undefined

### ISSUE THREAD

**Issue by DegenCryptoMonkey** [NomicFoundation/hardhat#2643]
After deploying a Vyper contract and calling its `deposit` function, the following error message appears:
![image](https://user-images.githubusercontent.com/100947820/165326342-635eb5a8-ef51-4cae-bff5-b5730b1367a5.png)

After logging the deployed `Reproduce.vy` contract, function `deposit` doesn't exist:
![image](https://user-images.githubusercontent.com/100947820/165326157-a90fbb87-1dd9-4347-94f8-fe1fa19a93fc.png)
As soon as we remove the optional parameter `_amount`, everything seems to be working fine.

Steps to reproduce:
1. Clone the following Github repo: https://github.com/DegenCryptoMonkey/hardhat-vyper-bug
2. Follow the instructions inside the README.md file
3. You should receive the above error after executing command `npm run reproduce`

Any idea what might have caused this 'bug'?

**Comment by fvictorio** [comment]
Are you using ethers? If so, read [this](https://docs.ethers.io/v5/single-page/#/v5/migration/web3/-%23-migration-from-web3-js--contracts--overloaded-functions).
