### ISSUE TITLE
Allow to unit test private/internal methods

### ISSUE THREAD

**Issue by rellfy** [NomicFoundation/hardhat#2645]
I would like to be able to directly test private and internal methods of contracts using the hardhat test runner.

One possible way to implement this could be to convert `internal` and `private` methods in the contracts to `public`, internally, only when running `npx hardhat test`, so that unit tests can be written for functions that can't be accessed otherwise.

It doesn't seem to be a way around this other than always using `internal` rather than `private` and also writing a mock contract that inherits the `internal` and makes it public. Hardhat should be able to do something like that for the developer and inject it in the `ethers` contract object during unit tests.

**Comment by wuya666** [comment]
I guess converting all `internal` functions to `public payable` should be fine, but I think `private` functions could be tricky since there could be multiple private functions with the same signature due to contract inheritance, and you can't override them since you shouldn't change their logic in parent contracts...

**Comment by rellfy** [comment]
> I guess converting all `internal` functions to `public payable` should be fine, but I think `private` functions could be tricky since there could be multiple private functions with the same signature due to contract inheritance, and you can't override them since you shouldn't change their logic in parent contracts...

That's a fair point. I'm aware the implementation for this would be hacky.
Maybe instead of converting the functions, a preprocessor could copy them into new `public payable` functions prefixed with the contract name and function visibility. For example:

```solidity
pragma solidity ^0.8.0;
contract Contract {
    uint256 public value;
    constructor() {
        value = squareOf(2);
    }
    function squareOf(uint256 input) private returns (uint256) {
        return input**2;
    }
}
```

becomes:

```solidity
pragma solidity ^0.8.0;
contract Contract {
    uint256 public value;
    constructor() {
        value = squareOf(2);
    }
    function squareOf(uint256 input) private returns (uint256) {
        return input**2;
    }
    function Contract__private__squareOf(uint256 input) public payable returns (uint256) {
        return input**2;
    }
}
```

**Comment by rellfy** [comment]
#relevant

**Comment by rellfy** [comment]
#stillrelevant

**Comment by feuGeneA** [comment]
Please consider using https://www.npmjs.com/package/hardhat-exposed
