### ISSUE TITLE
optimizer runs affecting tests involving custom errors.

### ISSUE THREAD

**Issue by mejango** [NomicFoundation/hardhat#2657]
`yarn test` works on this repo with optimizer runs of 1000000 in hardhat.config.js. breaks with optimizer runs is 10000. Problem seems to be in custom error encoded or something. https://github.com/jbx-protocol/juice-contracts-v2

**Comment by mejango** [comment]
any updates? eta on looking into this? thanks.

**Comment by feuGeneA** [comment]
Thank you for using Hardhat. If there is a problem in Hardhat, we will need to be able to reproduce it before we can fix it. Please provide more information. See https://stackoverflow.com/help/minimal-reproducible-example

**Comment by mejango** [comment]
yeah. pull down the repo linked and try to `yarn compile` and `yarn test` with runs set to 1000000 and then try with runs set to 10000. The tests will fail with runs of 10000, and there will be spurious dragon compile warnings on non-test contracts with runs set to 1000000.

Our work around was to run tests at 1000000, then switch runs to 10000 for deploying.

**Comment by feuGeneA** [comment]
Thanks for the reply.

Sorry for my generic response. It was a GitHub "saved reply".

What I'm looking for is a _minimal_ reproducible example. In general, while it may be easy to _reproduce_ a problem within a larger project like that, it's often times not practical to diagnose and debug in such a project.

I will try to get to reproducing this next week, but it will be easier to find the time if there's a minimized example. Thanks again.
