### ISSUE TITLE
problem with apikey not found 

### ISSUE THREAD

**Issue by JBobznfts** [NomicFoundation/hardhat#2659]
im currently using vs code to make an web 3 webpage but when im trying to verify my contract i keep getting this error 

`Error in plugin @nomiclabs/hardhat-etherscan: Please provide an Etherscan API token via hardhat config. For example:

{
  ...
  etherscan: {
    apiKey: {
      rinkeby: 'your API key'
    }
  }
}

See https://etherscan.io/apis`

this is my hardhat config file i have my api in my env so it does fork to github i just dont understand whats going wrong i keep trying everything can someone please give me some advice 

`module.exports = {
  solidity: "0.8.4",
  networks:{
    rinkeby: {
      url: process.env.REACT_APP_RINKEBY_RPC_URL,
      accounts: [process.env.REACT_APP_PRIVATE_KEY]
    },
  },
  etherscan: {
    apikey: process.env.REACT_APP_ETHERSCAN_KEY
  },
};`

**Comment by cristianbuta** [comment]
Any update on this issue?

**Comment by scnale** [comment]
Javascript object keys are case sensitive. `apikey` is not the same as `apiKey`.
