### ISSUE TITLE
console.log signatures are not ABI-compliant

### ISSUE THREAD

**Issue by charles-cooper** [NomicFoundation/hardhat#2666]
`console.log` works by encoding the payload with an ABI signature. however, in some cases the types used are the type aliases, instead of the ABI types. for instance, the following signature uses `(uint)` instead of `(uint256)`:

https://github.com/NomicFoundation/hardhat/blob/fd1f7f8cdb06d8e4ee7fb5fce15c4c48730ca45c/packages/hardhat-core/console.sol#L24-L26

currently, vyper's `print` function uses the standard ABI types for calculating method IDs. we could hardcode workaround rules specifically for the `print` function, but as a matter of cross-language/tooling compatibility it seems it would be better to use the standard ABI types!

**Comment by charles-cooper** [comment]
I guess a more general design would be for the console address to expose a single method whose signature is `log(string,bytes)`. The first argument is a string containing the signature of the data to be decoded (e.g. `"(uint256)"`, or `"(string,uint256)"`), and the second is the ABI encoded payload. This would allow hardhat to decode any kind of logged data, instead of just the existing hardcoded signatures.

**Comment by charles-cooper** [comment]
bump

**Comment by charles-cooper** [comment]
Been thinking about this, and it might be good to use a special "Print" event instead of a special console address. The reason is that it's much easier to deal with event logs than tracing contract calls.

**Comment by meetmangukiya** [comment]
I think one downside is with current `console.log`s are `staticcall`s which allows them to be used in view functions as well. Moment we use events, we'd need to remove view from the methods when debugging and re-add later, leaves room for missing out removing the view modifiers, etc. and just generally a comparatively bad devex.

**Comment by charles-cooper** [comment]
> I think one downside is with current `console.log`s are `staticcall`s which allows them to be used in view functions as well. Moment we use events, we'd need to remove view from the methods when debugging and re-add later, leaves room for missing out removing the view modifiers, etc. and just generally a comparatively bad devex debugging view methods.

Gotcha, and a note for our future selves - even if you were able to emit logs from a view fn (e.g. with fn pointers in solidity or compiler support for print as in vyper) a runtime revert would still be issued if it were run within a static call context.

**Comment by charles-cooper** [comment]
note: vyper will support both modes for the time being but eventually we want to migrate to the generic signature.

also - the implementation of the generic decoder is very simple, here is a reference: https://github.com/vyperlang/titanoboa/blob/6085b0819030b44d1f83f2e0458bf53160487bc8/boa/env.py#L60-L68

(ccing @davidmurdoch)
