### ISSUE TITLE
Force send transaction without "debug" on node

### ISSUE THREAD

**Issue by inwady** [NomicFoundation/hardhat#2668]
Hello, I received a weird case. I'm sending the wrong transaction (I know about it, but want to see it on etherscan).

This code returned an error before sending:

```
await dt.callSomeMethod(1)
Uncaught ProviderError: The execution failed due to an exception.
...
```

For this transaction, the code is working (and I can look on the transaction):
```
await contract.callSomeMethod(1, {gasLimit: 30000000})
{
  hash: '...',
  type: 2,
  accessList: []
...
```

How can I force send a transaction (if I know about it)? Or is it a problem on the node side?

**Comment by alcuadrado** [comment]
Hi there, and thanks for using Hardhat!

We don't use Github issues for support about how to use it, but exclusively for bugs and feature requests. If you need help, please use [our Discord server](https://hardhat.org/discord) instead.

I believe what's going on here is that in the first case ethers won't send the transaction if the gas estimation fails. In the second case, there's no gas estimation, so it sends it.
