### ISSUE TITLE
Hardhat tries to import the ts configuration file when running on a built ts project

### ISSUE THREAD

**Issue by marian2js** [NomicFoundation/hardhat#2669]
I have a monorepo with hardhat using typescript and a node app also using typescript. I need to import hardhat from the node project to invoke a task programmatically.
Everything works fine when running the app in dev (with ts-node). However, when I build the ts app into a js file for production, importing hardhat fails.

The error happens because when importing hardhat, it [looks for the configuration file](https://github.com/NomicFoundation/hardhat/blob/767f68dee84d6a47cd40153a8ab8552f41a95d5e/packages/hardhat-core/src/internal/core/project-structure.ts#L19), and, since hardhat.config.ts exists, it tries to import it. However, this fails with the error: 

```
/hardhat-test/hardhat.config.ts:1
import * as dotenv from "dotenv";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

The problem is that hardhat always tries to import "hardhat.config.ts" before "hardhat.config.js". So, as long as the .ts file exists, importing hardhat will fail.
As a workaround, the build script has to compile hardhat.config.ts and then remove it.
But in some cases, this error can also happen in non-production environments, for instance, when importing hardhat from a nest.js app on dev mode.

# Reproduction steps:

```
$ npx hardhat
> Create an advanced sample project that uses TypeScript
```

create app.ts
```ts
import hre from 'hardhat'

async function main() {
  await hre.run('help')
}
```

add build script to package.json:
```json
"scripts": {
  "build": "tsc app.ts"
}
```

build and run:
```
$ npm run build
$ node app.js
/hardhat-test/hardhat.config.ts:1
import * as dotenv from "dotenv";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

# Proposed solutions

1. Catching the error when [requiring](https://github.com/NomicFoundation/hardhat/blob/23567bbf220ba9708362b8a59b86e78a269dde05/packages/hardhat-core/src/internal/core/config/config-loading.ts#L28) "hardhat.config.ts", and if the error message matches "SyntaxError: Cannot use import statement outside a module", require hardhat.config.js. I personally prefer this solution since it requires no extra configuration.
2. Add an optional env variable that allows specifying the hardhat config path. This will allow us to run the .ts config on dev mode and the .js file on production.

If any of these solutions are acceptable, I can prepare a PR.

**Comment by fvictorio** [comment]
> 2\. Add an optional env variable that allows specifying the hardhat config path. This will allow us to run the .ts config on dev mode and the .js file on production.

This is already possible (although not very well documented): you can use the `HARDHAT_CONFIG` environment variable.

**Comment by fvictorio** [comment]
That being said, I would like to understand under which circumstances you need to build a typescript hardhat project. Could you explain your scenario (ideally in a simplified way)? In my mind, the main reason not to use ts-node is that it adds significant startup time, is that your main problem with using it?

**Comment by moconnell** [comment]
Co-sign. Have the same scenario [here](https://github.com/moconnell/alliance/tree/monorepo) where I'm also trying to set-up a .ts monorepo.

I already have the back-end running fine on .ts with `"compilerOptions": {"module": "commonjs"}` in `package.json`, but `create-react-app` seems to overwrite this with `"module": "esnext"`, which then leads to the above error.

**Comment by marian2js** [comment]
@fvictorio We have a monorepo with a nestjs app and hardhat (both using typescript). One of our workflows running on the nestjs app needed to run on demand a hardhat task that uses a forked chain to test a few things.

I ended up solving it using child_process to call hardhat instead of trying to import it. The downside of this approach is that our fleet was using boxes with 1 vcpu, but this execution requires at least 2 vcpu.

**Comment by fvictorio** [comment]
I see, thanks for the explanation. I don't really know what we should do here though. Maybe Hardhat should at least throw an error if there are both `hardhat.config.ts` and a `hardhat.config.js` files? Or maybe we should prefer the `.js` one for scenarios like this? I'm not sure.

**Comment by Vratislav** [comment]
I think a step in the right direction would be to take the closest config file no matter whether it is .js or .ts.

That would allow having a `./build` folder where a compiled project could function.

Right now the behavior is:
1. Scan for a .ts config file all the way up in the directory hierarchy, if it is found, use it
2. If no .ts config file is found, look for .js

That means that if you have a .ts config file anywhere up in the dir structure, it is preferred over the closer compiled .js config file.

Better behavior would be:
1. Start at the CWD
2.  Is there a config file? 
 * If there is one, use it. 
 * If there are both .ts  and .js, throw an error
 * if there is none look into the parent directory, repeat 2.

**Comment by fvictorio** [comment]
Closing this in favor of https://github.com/NomicFoundation/hardhat/issues/3477.
