### ISSUE TITLE
Error: Contract at 0x8A791620dd6260079BF849Dc5567aDC3F2FdC318 doesn't look like an ERC 1967 proxy with a logic contract address

### ISSUE THREAD

**Issue by stzengh** [NomicFoundation/hardhat#2673]
Hi

I upgrade the hardhat version to 2.9.3.
And I got an error when I upgrade my contract.
Error: Contract at 0x8A791620dd6260079BF849Dc5567aDC3F2FdC318 doesn't look like an ERC 1967 proxy with a logic contract address.

But it is ok if I change the version to 2.6.x.

My test contract source code:

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.2;

import "@openzeppelin/contracts-upgradeable/token/ERC721/ERC721Upgradeable.sol";
import "@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol";
import "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol";

contract TestUpgrade is Initializable, ERC721Upgradeable, OwnableUpgradeable, UUPSUpgradeable {
    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor() initializer {}

    function initialize() initializer public {
        __ERC721_init("MyToken", "MTK");
        __Ownable_init();
        __UUPSUpgradeable_init();
    }

    function _authorizeUpgrade(address newImplementation)
        internal
        onlyOwner
        override
    {}
}

**Comment by iners-max** [comment]
I face the same issue for these 2 weeks.

I have deployed a new proxy contract this morning and wanted to upgrade the contract.

Polygon:
Proxy contract: 0x4509FF645838230Dd7B225E9dB9B3CD26dcC254b
Implementation: 0x865D1d34Aac83E83b41EC0918eEfB6408B133f76

I saw this error:
`Error: Contract at 0x4509FF645838230Dd7B225E9dB9B3CD26dcC254b doesn't look like an ERC 1967 proxy with a logic contract address`

I can see this entry in my `unknown-80001.json`

```
"proxies":[
    {
      "address": "0x4509FF645838230Dd7B225E9dB9B3CD26dcC254b",
      "txHash": "0x3bf0bfceb744ffa2f0e26829a3d6848a1ae743edc8db499a2770f001ab878e38",
      "kind": "transparent"
    }
]
```

my package.json

```
  "devDependencies": {
    "@nomiclabs/hardhat-ethers": "^2.0.5",
    "@nomiclabs/hardhat-etherscan": "^3.0.0",
    "@nomiclabs/hardhat-ganache": "^2.0.1",
    "@openzeppelin/hardhat-upgrades": "^1.15.0",
    "ethers": "^5.5.4",
    "hardhat": "^2.9.1",
    "hardhat-contract-sizer": "^2.5.1"
  }
 "dependencies": {
    "@nomiclabs/hardhat-waffle": "^2.0.2",
    "@openzeppelin/contracts": "^4.4.2",
    "@openzeppelin/contracts-upgradeable": "^4.5.2",
    "@testing-library/jest-dom": "^5.16.1",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0",
    "axios": "^0.27.2",
    "chai": "^4.3.6",
    "dotenv": "^15.0.0",
    "ethereum-waffle": "^3.4.0",
    "moment": "^2.29.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "5.0.0",
    "web-vitals": "^2.1.4"
}
```

**Comment by stzengh** [comment]
> I face the same issue for these 2 weeks.
> 
> I have deployed a new proxy contract this morning and wanted to upgrade the contract.
> 
> Polygon: Proxy contract: 0x4509FF645838230Dd7B225E9dB9B3CD26dcC254b Implementation: 0x865D1d34Aac83E83b41EC0918eEfB6408B133f76
> 
> I saw this error: `Error: Contract at 0x4509FF645838230Dd7B225E9dB9B3CD26dcC254b doesn't look like an ERC 1967 proxy with a logic contract address`
> 
> I can see this entry in my `unknown-80001.json`
> 
> ```
> "proxies":[
>     {
>       "address": "0x4509FF645838230Dd7B225E9dB9B3CD26dcC254b",
>       "txHash": "0x3bf0bfceb744ffa2f0e26829a3d6848a1ae743edc8db499a2770f001ab878e38",
>       "kind": "transparent"
>     }
> ]
> ```
> 
> my package.json
> 
> ```
>   "devDependencies": {
>     "@nomiclabs/hardhat-ethers": "^2.0.5",
>     "@nomiclabs/hardhat-etherscan": "^3.0.0",
>     "@nomiclabs/hardhat-ganache": "^2.0.1",
>     "@openzeppelin/hardhat-upgrades": "^1.15.0",
>     "ethers": "^5.5.4",
>     "hardhat": "^2.9.1",
>     "hardhat-contract-sizer": "^2.5.1"
>   }
>  "dependencies": {
>     "@nomiclabs/hardhat-waffle": "^2.0.2",
>     "@openzeppelin/contracts": "^4.4.2",
>     "@openzeppelin/contracts-upgradeable": "^4.5.2",
>     "@testing-library/jest-dom": "^5.16.1",
>     "@testing-library/react": "^12.1.2",
>     "@testing-library/user-event": "^13.5.0",
>     "axios": "^0.27.2",
>     "chai": "^4.3.6",
>     "dotenv": "^15.0.0",
>     "ethereum-waffle": "^3.4.0",
>     "moment": "^2.29.3",
>     "react": "^17.0.2",
>     "react-dom": "^17.0.2",
>     "react-scripts": "5.0.0",
>     "web-vitals": "^2.1.4"
> }
> ```

Yes. The same issue.
I have no idea.

**Comment by iners-max** [comment]
Are you using hardhat tasks? I have been diagnosing the issue today.
I feel like (not 100% remember) the issue started once I switched my logic to hardhat tasks from simple scripts.

Updates:
I have tried to use simple scripts like the one I found from OZ website
(https://docs.openzeppelin.com/learn/upgrading-smart-contracts#upgrading-a-contract-via-plugins)
```
// scripts/upgrade_box.js
const { ethers, upgrades } = require('hardhat');

async function main () {
  const BoxV2 = await ethers.getContractFactory('BoxV2');
  console.log('Upgrading Box...');
  await upgrades.upgradeProxy('0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0', BoxV2);
  console.log('Box upgraded');
}

main();
```
It works and upgraded my contract. When I use hardhat tasks it still fails.

It is likely a bug regarding hardhat tasks?

**Comment by iners-max** [comment]
Realized I made a terrible mistake when I started using hardhat tasks to upgrade my contract.

**I forgot to specify the network.** I can now upgrade my contract in Polygon Mumbai. Hope this is the same issue and same solution for you.

**Comment by fvictorio** [comment]
Yes, this seems like a case of forgetting to specify a network. That means that an in-process, temporary Hardhat Network will be used. This network is empty (unless you are using mainnet forking), and therefore any address will be also empty.

Going to close this one now, but please let me know if you think there's a problem on our side here.
