### ISSUE TITLE
evm_mine does not work the same as Ganache

### ISSUE THREAD

**Issue by unparalleled-js** [NomicFoundation/hardhat#2677]
The documentation for `evm_mine` says "Same as Ganache". However, In Ganache, I can pass in the number of blocks as the argument: https://trufflesuite.com/blog/introducing-ganache-7/#5-mine-blocks-instantly-at-interval-or-on-demand

e.g. I can do `[{"blocks": 100}]` as my arguments to the RPC call.

When I try to do this using `hardhat node`, I get the following error:

```
Errors encountered in param 0: Invalid value {"blocks":100} supplied to : (QUANTITY | number)/0
```

It looks like it does not handle a JSON object with `blocks` keys and instead treats it like a timestamp.

I would like to be able to mine more than one block without using timestamps.

:)

**Comment by alcuadrado** [comment]
Thanks for reporting this, @unparalleled-js. You are right.

You can use [`hardhat_mine`](https://hardhat.org/hardhat-network/reference/#hardhat-mine) instead.

**Comment by alcuadrado** [comment]
Closing in favor of https://github.com/NomicFoundation/hardhat/issues/2686

Thanks!

**Comment by mikeshultz** [comment]
It might not be a compelling reason to change this, but it's worth mentioning that some things like `solidity-coverage` [do not currently play nicely with `hardhat_mine`](https://github.com/sc-forks/solidity-coverage/issues/707).   Would be nice to have `evm_mine` work with multiple block minting per RPC call the same as Ganache if possible.
