### ISSUE TITLE
Allow multiple typechain outdir inside hardhat.config 

### ISSUE THREAD

**Issue by myhendry** [NomicFoundation/hardhat#2678]
It would be excellent if we can pass in an array of directories that will output the types directory to several locations at one go

This way, we can use the types easily inside our front end and back end (meaning blockchain dev) even though the front end and back end are in 2 separate folders and when new types are generated, it will be update both folders

I have done a demo that uses hardhat, typechain and added a front end (github repo)[https://github.com/myhendry/OPEN]. If types generated can be outputted to various directories, it will be available on both front and back end and makes type checking easier

**Comment by fvictorio** [comment]
Hi @myhendry, shouldn't this be reported in the https://github.com/dethcrypto/TypeChain repo?

**Comment by fvictorio** [comment]
Tentatively closing this, please let me know if you think it belongs in our issue tracker.
