### ISSUE TITLE
Circular problem when using Typechain types.

### ISSUE THREAD

**Issue by hickscorp** [NomicFoundation/hardhat#2681]
Disclaimer notice - I'm fairly new to Hardhat - I've previously used other frameworks.

There's something that I'm either confused about, or that could be an issue with the current architecture of Hardhat.

I have this task defined:

```ts
import { task, types } from "hardhat/config";
import "@openzeppelin/hardhat-upgrades";
import { checkNetwork } from "../utils";
import { StateManager } from '../StateManager';
import { HardhatRuntimeEnvironment } from "hardhat/types";
// import { Spc } from "../../typechain-types";

interface SpcDeployParams {
  readonly governor: string;
};

task("spc-deploy", "Deploys the main SPC contract")
  .addParam('governor', 'The SPC governor address', undefined, types.string)
  .setAction(async (params: SpcDeployParams, hre) => {
    checkNetwork(hre);

    const stateManager = new StateManager(31337);
    // Check for libraries...
    if (!stateManager.state.AddressSetLib) { throw 'Missing AddressSetLib library' }
    // Already deployed?
    else if (stateManager.state.Spc) { throw `Already deployed at ${stateManager.state.Spc}` }

    const addressSetLibAddr: string = stateManager.state.AddressSetLib;
    const spc = await deploySpc(hre, addressSetLibAddr, params.governor);
    // We keep track of its address in our state file.
    stateManager.state = { ...stateManager.state, Spc: spc.address };
    console.log('Deployed Spc', spc.address);
  });

async function deploySpc(
  { ethers, upgrades }: HardhatRuntimeEnvironment,
  addressSetLibAddr: string,
  governor: string): Promise<Spc> {
  // We deploy our SPC contract.
  const libraries = { AddressSetLib: addressSetLibAddr }
  const Spc = await ethers.getContractFactory("Spc", { libraries });
  return await upgrades.deployProxy(Spc, [governor]) as Spc;
}

export { deploySpc };
```

It became a thing organically - and it uses typings generated via `hardhat typechain`.
Everything is great until I run `hardhat clean` - now, the typechain types are gone, and I cannot run any `hardhat` command anymore - because even the `hard typechain` task requires that my typescript files are correct - and since the types are gone, it cannot generate them.

I'm not sure whether this is a configuration problem on my end, or something that needs fixing with Hardhat.

Another thing - that might be related - I cannot find much documentation how how one would use the Typechain types in a Hardhat project. I followed the instructions from `@typechain/hardhat` (I'll include my `hardhat.config.ts` and `tsconfig.json` at the end of this issue), but somehow I still have to manually type things (For example, `return await upgrades.deployProxy(Spc, [governor]) as Spc;`) where I thought that the goal of Typechain with Hardhat was exactly to prevent this kind of possible mistake. Is there something I'm doing wrong here, or is it the architecture that is purposefully designed in such way? For example, I noticed that a `Spc__factory` type was being  generated - but it seems that I cannot use it while also using `openzeppelin`'s `upgrades.deployProxy(...)` method?

`hardhat.config.ts`:
```ts
import * as dotenv from 'dotenv';
import { HardhatUserConfig } from 'hardhat/config';
import '@openzeppelin/hardhat-upgrades';
import '@typechain/hardhat';
import '@nomiclabs/hardhat-ethers';
import '@nomiclabs/hardhat-waffle';
import 'hardhat-gas-reporter';
import 'solidity-coverage';

// Loads `.env` file into `process.env`.
dotenv.config();

// Import all of our tasks here!
import './src/tasks/accounts';
import './src/tasks/libraries';
import './src/tasks/spc';
import './src/tasks/fast';
import './src/tasks/bootstrap';

const config: HardhatUserConfig = {
  solidity: '0.8.4',
  networks: {
    ropsten: {
      url: process.env.ROPSTEN_URL || '',
      accounts: process.env.PRIVATE_KEY !== undefined ? [process.env.PRIVATE_KEY] : [],
    },
  },
  gasReporter: {
    enabled: process.env.REPORT_GAS !== undefined,
    currency: 'EUR',
  }
};
export default config;
```

`tsconfig.json` (Note that my stuff is in `src`, not top-level):
```json
{
  "compilerOptions": {
    "target": "es2018",
    "module": "commonjs",
    "strict": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "outDir": "dist",
    "declaration": true
  },
  "include": [
    "./src",
    "./src/tasks",
    "./src/scripts",
    "./test",
    "./typechain-types"
  ],
  "files": [
    "./hardhat.config.ts",
    "./typings.d.ts"
  ]
}
```

**Comment by hickscorp** [comment]
Bump? How can you run `hardhat compile` if tasks use Typescript, but the `typechain-types` isn't populated yet?

**Comment by fvictorio** [comment]
Hi @hickscorp, thanks for sharing the solution. We'll be working soon in some improvements that will make even that unnecessary, but for the time being that's probably the correct approach.

I'm going to close this issue now, but let me know if you have more concerns.

**Comment by marcelomorgado** [comment]
For whom that may facing this issue just use `import type { ... } from "../typechain-types"`
