### ISSUE TITLE
Error in plugin @nomiclabs/hardhat-etherscan: Failed to obtain list of solc versions. Reason: connect ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by dyx52** [NomicFoundation/hardhat#2684]

**Comment by shiruitao** [comment]
me too
Error in plugin @nomiclabs/hardhat-etherscan: Failed to obtain list of solc versions. Reason: getaddrinfo ENOTFOUND solc-bin.ethereum.org

**Comment by dyx52** [comment]
> 我也是 插件 @nomiclabs/hardhat-etherscan 中的错误：无法获取 solc 版本列表。原因：getaddrinfo ENOTFOUND solc-bin.ethereum.org

did you solve it

**Comment by shiruitao** [comment]
> > 我也是 插件 @nomiclabs/hardhat-etherscan 中的错误：无法获取 solc 版本列表。原因：getaddrinfo ENOTFOUND solc-bin.ethereum.org
> 
> did you solve it

no

**Comment by fvictorio** [comment]
This seems like a connection error, so there's nothing we can do on our side.

**Comment by Trifida** [comment]
Error in plugin @nomiclabs/hardhat-etherscan: Failed to obtain list of solc versions. Reason: connect ECONNREFUSED 127.0.0.1:443

**Comment by Ayuilos** [comment]
I got the same problem, and I just fetch data from `COMPILERS_LIST_URL` manually from `node_modules/@nomiclabs/hardhat-etherscan/dist/src/solc/version.js`, and just directly return that data wrapped in Promise in `getVersions` function.
This will solve the problem for the time being and make sure that this is a `undici` problem.
Take me so much time to figure out what's going on with my system setting. Sad.

**Comment by daocore** [comment]
You can add youself proxy config in the "hardhat.config.js" file:
```js
// set proxy
const proxyUrl = 'http://127.0.0.1:7890';   // change to yours, With the global proxy enabled, change the proxyUrl to your own proxy link. The port may be different for each client.
const { ProxyAgent, setGlobalDispatcher } = require("undici");
const proxyAgent = new ProxyAgent(proxyUrl);
setGlobalDispatcher(proxyAgent);
```

**Comment by sclongyang** [comment]
> You can add youself proxy config in the "hardhat.config.js" file:
> 
> ```js
> // set proxy
> const proxyUrl = 'http://127.0.0.1:7890';   // change to yours, With the global proxy enabled, change the proxyUrl to your own proxy link. The port may be different for each client.
> const { ProxyAgent, setGlobalDispatcher } = require("undici");
> const proxyAgent = new ProxyAgent(proxyUrl);
> setGlobalDispatcher(proxyAgent);
> ```
Thanks a lot, it works!

**Comment by rao261488647** [comment]
> You can add youself proxy config in the "hardhat.config.js" file:
> 
> ```js
> // set proxy
> const proxyUrl = 'http://127.0.0.1:7890';   // change to yours, With the global proxy enabled, change the proxyUrl to your own proxy link. The port may be different for each client.
> const { ProxyAgent, setGlobalDispatcher } = require("undici");
> const proxyAgent = new ProxyAgent(proxyUrl);
> setGlobalDispatcher(proxyAgent);
> ```

Thanks, is't cool~

**Comment by rao261488647** [comment]
> You can add youself proxy config in the "hardhat.config.js" file:
> 
> ```js
> // set proxy
> const proxyUrl = 'http://127.0.0.1:7890';   // change to yours, With the global proxy enabled, change the proxyUrl to your own proxy link. The port may be different for each client.
> const { ProxyAgent, setGlobalDispatcher } = require("undici");
> const proxyAgent = new ProxyAgent(proxyUrl);
> setGlobalDispatcher(proxyAgent);
> ```

Thanks, it's cool~!

**Comment by vivostar** [comment]
> You can add youself proxy config in the "hardhat.config.js" file:
> 
> ```js
> // set proxy
> const proxyUrl = 'http://127.0.0.1:7890';   // change to yours, With the global proxy enabled, change the proxyUrl to your own proxy link. The port may be different for each client.
> const { ProxyAgent, setGlobalDispatcher } = require("undici");
> const proxyAgent = new ProxyAgent(proxyUrl);
> setGlobalDispatcher(proxyAgent);
> ```

Only in china we will come across such network problems. Thanks!

**Comment by scuwmm** [comment]
I got this error：
Error in plugin @nomiclabs/hardhat-etherscan: Failed to obtain list of solc versions. Reason: 4408526208:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:332:

anybody can help?

**Comment by fvictorio** [comment]
Locking this because there are a lot of unrelated comments.

If someone has a problem and you think it's a bug in Hardhat and not a problem with your network, a firewall or whatever, please open a new issue.
