### ISSUE TITLE
Unable to verify contracts on snowtrace

### ISSUE THREAD

**Issue by ShivamArora** [NomicFoundation/hardhat#2685]
I'm unable to verify contracts on Snowtrace.

I've generated and included an API key from snowtrace to `hardhat.config.ts` as below:
```json
{
  "etherscan": {
     "apiKey": {
        "avalancheFujiTestnet": <MY_SNOWTRACE_KEY>
        }
     }
}
```

I've tried verifying the contract using the following command:
```bash
hardhat verify --network avalancheFujiTestnet <CONTRACT_ADDRESS>
```

And I always get the following error:
```
Error in plugin @nomiclabs/hardhat-etherscan: Invalid API Key
```

I've also tried the programmatic way by creating a custom task and running `verify:verify` with the contract address and network name. But still get the same error.

**Comment by feuGeneA** [comment]
Thank you for using Hardhat. If there is a problem in Hardhat, we will need to be able to reproduce it before we can fix it. Please provide more information. See https://stackoverflow.com/help/minimal-reproducible-example

**Comment by ShivamArora** [comment]
Hi @feuGeneA , seems like the issue was probably on the Snowtrace testnet API. I've just tried verifying three contracts without upgrading the plugin today and didn't get this issue.

Thanks for your support. I'll close this issue now.
