### ISSUE TITLE
Incompatibility with `cast storage`

### ISSUE THREAD

**Issue by jamierumbelow** [NomicFoundation/hardhat#2698]
When calling `eth_getStorageAt`, the parameter validation in `isRpcQuantityString` (src/internal/core/jsonrpc/types/base-types.ts:127) uses the following regex to validate the 1st-place parameter (the storage location):

    /^0x(?:0|(?:[1-9a-fA-F][0-9a-fA-F]*))$/

This regex won't match values with leading zeros. Thus, the following is a valid string:

    0x1

And this is not:

    0x0000000000000000000000000000000000000000000000000000000000000001

The superb `cast` utility from [Foundry](https://github.com/foundry-rs/foundry) left-zero-pads its parameters. This leads to the following frustrating error:

    $ cast storage 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2 0x1
    
    Error:
      0: (code: -32602, message: Errors encountered in param 1: Invalid value "0x0000000000000000000000000000000000000000000000000000000000000001" supplied to : QUANTITY, data: None)

The [spec](https://eips.ethereum.org/EIPS/eip-1474#quantity) appears to reject leading zeros, so it looks like Hardhat is implementing the spec correctly.

But other RPC endpoints appear to be more forgiving:

    $ cast storage 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2 0 --rpc-url https://eth-mainnet.alchemyapi.io/v2/blah
    
    0x577261707065642045746865720000000000000000000000000000000000001a

I'll cross-post this with the Foundry team, but wanted to raise it with the Hardhat team too, in case it makes more sense to allow Hardhat to deviate from the spec a little and strip the leading zeros.

**Comment by fvictorio** [comment]
Hey @jamierumbelow, thanks for opening this and sorry for the auto-close.

I'm re-opening this just in case, but it seems like now `forge` is spec-compliant, so maybe this is not longer an issue?
