### ISSUE TITLE
hardhat test stops working

### ISSUE THREAD

**Issue by rayyan808** [NomicFoundation/hardhat#2699]
I have fully functional tests that run fine, but after a while of coding hardhat simply stops doing anything. I know this isn't any faulty code, because I revert back to a commit that was working and it still will not work anymore. The only thing that makes sense is bad cache, but I've repeatedly tried `yarn cache clean` aswell as `yarn hardhat clean` . To be honest this is extremely frustrating to not be able to seamlessly test. I'm running `2.9.0`. I pulled the same repo and commit into another device, and it would work fine! But again, as I progressed with my work it just suddenly stops again with no outputs or explanations. I use `yarn hardhat node` to spool up the local instance before calling the test.

```
yarn hardhat test ./test/unit/x.js --network localhost
yarn run v1.22.18
$ /media/rayyan808/5011995d-72e1-4299-bff9-8e7e5d313863/rayyan808/Documents/ELYXR/elyxr-deploy/node_modules/.bin/hardhat test ./test/unit/x.js --network localhost


  0 passing (0ms)

Done in 1.35s.
```

**Comment by ddnexus** [comment]
What was the issue? 

I have the same problem after installing and trying `yarn`, `pnpm` and back to `npm`. Mocha works, but `npx hardhat test` does not anymore.

**Comment by rayyan808** [comment]
Hello,

For my issue, I realized that hardhat does not provide any errors within
your test code, and if a certain value is undefined it will not state this
(along with many other types of errors). Going through my code for logical
JavaScript errors was enough to solve the problem!

**Comment by ddnexus** [comment]
@rayyan808 yup, something similar happened here.

@fvictorio Using latest version. You can get the same running the tests with this configuration:

```
paths: {
    tests: "a/non/existent/path"
}
```
HH will not check, nor complain about it, returning a green `0 passing` to be interpreted.

My specific problem was that I got a typo in a git ignored `.env` file used in the tests path that didn't reverted after my tries, so finding it took some more digging.

More feedback from HH would be very welcomed.

**Comment by fvictorio** [comment]
Opened https://github.com/NomicFoundation/hardhat/issues/2784 for this.

**Comment by ddnexus** [comment]
Thanks!
