### ISSUE TITLE
Adding Gather support for hardhat-etherscan

### ISSUE THREAD

**Issue by scream4ik** [NomicFoundation/hardhat#2706]
Hi,

We've added support for hardhat-etherscan on Gather and created a small patch to support the Gather network (change in two files, chainconfig.ts and types.ts). I would like to push this as a PR as a lot of developers have been asking for hardhat-etherscan support to make contract verification much easier on the Gather network.

Fork commit: https://github.com/scream4ik/hardhat/commit/b0bb744ae21c090cdd54bfaf08132b240082b4c9

**Comment by feuGeneA** [comment]
Thank you for your contribution. Please submit a PR rather than an Issue.
