### ISSUE TITLE
Nothing to compile error on Windows

### ISSUE THREAD

**Issue by ihorbond** [NomicFoundation/hardhat#2712]
Running `npx hh compile --force` still results in "Nothing to compile".
Multiple people reporting the same issue. Here is repro repo:
https://github.com/ihorbond/hardhat-test

**Comment by thinkingchain** [comment]
Got the same issue.

**Comment by thinkingchain** [comment]
Even roll back to previous successful version ("hardhat": "^2.8.4"), It still doesn't work~

**Comment by lukastanisic99** [comment]
Same error on the latest version - reverting back to 2.9.3 doesn't fix it. 
It fails even on the sample project.
Luckily I've ran it successfully before on an older version so I could do npm list --depth=0 to see the installed packages

Only difference was hardhat@2.9.3 and @nomiclabs/hardhat-ethers@2.0.5 instead of hardhat@2.9.5 and @nomiclabs/hardhat-ethers@2.0.6

Installing those same versions in the new project still couldn't resolve the problem.
Running npm list --depth=0 in both the working and non-working project returned the same output and yet it still didn't work....

 - So I just copied the entire node_modules folder from the project that was working and it works....

**Comment by yy940997492** [comment]
一样的问题，但是使用以前的工程，就可以compile

**Comment by ProvokerDave** [comment]
> Same error on the latest version - reverting back to 2.9.3 doesn't fix it. It fails even on the sample project. Luckily I've ran it successfully before on an older version so I could do npm list --depth=0 to see the installed packages
> 
> Only difference was hardhat@2.9.3 and @nomiclabs/hardhat-ethers@2.0.5 instead of hardhat@2.9.5 and @nomiclabs/hardhat-ethers@2.0.6
> 
> Installing those same versions in the new project still couldn't resolve the problem. Running npm list --depth=0 in both the working and non-working project returned the same output and yet it still didn't work....
> 
>     * So I just copied the entire node_modules folder from the project that was working and it works....

Brilliant, I took the caret off the hardhat-ethers version and my build is working again!  Thank you, big brain friend!

    "@nomiclabs/hardhat-ethers": "2.0.5"

**Comment by TheyCallMeCheng** [comment]
Did anyone else find another solution? I don't see copying the node folder as a long term solution

**Comment by jamesbachini** [comment]
I'm trying to figure it out too. So far have tried:
Setting the dependencies to hardhat@2.9.3 and @nomiclabs/hardhat-ethers@2.0.5 in package.json
Deleting cache/ and node_modules/
npm install
npx hardhat compile

Still get the nothing to compile error.

**Comment by TheyCallMeCheng** [comment]
Somehow hardhat isn't seeing the /contracts/ folder. I'm wondering if this is due to some accessibility permissions.
If you noticed when you compile it's not saving in the cache the folder info, also it doesn't create the /artifacts/ folder.

I tried rolling back to v 2.9.3 (which is working fine on my mac) but still having the same issue, so I'm also wondering if this issue is only in Windows.

**Comment by jamesbachini** [comment]
Yeah you are right. A quick fix is to run commands from WSL (Windows subsystem for Linux). It runs fine from there.

Thanks for your help @TheyCallMeCheng

**Comment by dragondyt** [comment]
tryThis
![image](https://user-images.githubusercontent.com/20499679/168428618-bb483221-45a2-4beb-8a93-7df76ebae203.png)

**Comment by tylerK1294** [comment]
I finally found it.
glob@7.2.2 <- This is problem

I haven't looked for it exactly from what point, but it's version 7.2.0 in the package at the point where that package works well, and version 7.2.2 in the "nothing to compile" version.

copy glob@7.2.0 to /node_modules/hardhat/node_modules/glob

**Comment by dragondyt** [comment]
tryThis
![image](https://user-images.githubusercontent.com/20499679/168428679-c8947bfd-153f-4f51-92f9-71d52721836b.png)

**Comment by dragondyt** [comment]
[try this,it easy
](https://github.com/NomicFoundation/hardhat/issues/2142#issuecomment-1126719376)

**Comment by TheyCallMeCheng** [comment]
> I finally found it. glob@7.2.2 <- This is problem
> 
> I haven't looked for it exactly from what point, but it's version 7.2.0 in the package at the point where that package works well, and version 7.2.2 in the "nothing to compile" version.
> 
> * Type the "npm intstall glob@7.2.0" into an empty project and copy /node_modules/glob
> * copy /node_modules/glob to YOUR_HARDHAT_PROJECT/node_modules/hardhat/node_modules/glob
> 
> It works.

Seems to work fine if you just do `npm install glob@7.2.0` in a current hardhat project, thank you

**Comment by austinjblake** [comment]
> > I finally found it. glob@7.2.2 <- This is problem
> > I haven't looked for it exactly from what point, but it's version 7.2.0 in the package at the point where that package works well, and version 7.2.2 in the "nothing to compile" version.
> > 
> > * Type the "npm intstall glob@7.2.0" into an empty project and copy /node_modules/glob
> > * copy /node_modules/glob to YOUR_HARDHAT_PROJECT/node_modules/hardhat/node_modules/glob
> > 
> > It works.
> 
> Seems to work fine if you just do `npm install glob@7.2.0` in a current hardhat project, thank you

Yes this fixes it for me also. Thanks

**Comment by MrBuluc** [comment]
> 

Thank you. This fixes it for me too.

**Comment by ihorbond** [comment]
> 

I just compiled with visual studio solidity extension for now, it places result into bin folder. It does seem like a Windows issue cause it does work on Linux

**Comment by thinkingchain** [comment]
> npm install glob@7.2.0
Thank you , That is working .

**Comment by IMPranshu** [comment]
> I finally found it. glob@7.2.2 <- This is problem
> 
> I haven't looked for it exactly from what point, but it's version 7.2.0 in the package at the point where that package works well, and version 7.2.2 in the "nothing to compile" version.
> 
> * Type the "npm intstall glob@7.2.0" into an empty project and copy /node_modules/glob
> * copy /node_modules/glob to YOUR_HARDHAT_PROJECT/node_modules/hardhat/node_modules/glob
> 
> It works.

This fixed the issue

**Comment by AbhimanyuDatta** [comment]
> I finally found it. glob@7.2.2 <- This is problem
> 
> I haven't looked for it exactly from what point, but it's version 7.2.0 in the package at the point where that package works well, and version 7.2.2 in the "nothing to compile" version.
> 
> * Type the "npm intstall glob@7.2.0" into an empty project and copy /node_modules/glob
> * copy /node_modules/glob to YOUR_HARDHAT_PROJECT/node_modules/hardhat/node_modules/glob
> 
> It works.

Thanks for this.

**Comment by HydraRichie** [comment]
> > I finally found it. glob@7.2.2 <- This is problem
> > I haven't looked for it exactly from what point, but it's version 7.2.0 in the package at the point where that package works well, and version 7.2.2 in the "nothing to compile" version.
> > 
> > * Type the "npm intstall glob@7.2.0" into an empty project and copy /node_modules/glob
> > * copy /node_modules/glob to YOUR_HARDHAT_PROJECT/node_modules/hardhat/node_modules/glob
> > 
> > It works.
> 
> Seems to work fine if you just do `npm install glob@7.2.0` in a current hardhat project, thank you

Yeah these solved my issue THANK YOU!

**Comment by boldrack** [comment]
> 

This mostly will install glob under your project `node_modules ` but you need the correct glob under hardhat node_modules like 

`projectpath/node_modules/hardhat/node_modules/glob` is what need to be replaced . 

At least that was what worked for me.

**Comment by abondance68** [comment]
Issue solved as today, thank you glob trotter...

**Comment by zepgursoy** [comment]
> I finally found it. glob@7.2.2 <- This is problem
> 
> I haven't looked for it exactly from what point, but it's version 7.2.0 in the package at the point where that package works well, and version 7.2.2 in the "nothing to compile" version.
> 
> * Type the "npm intstall glob@7.2.0" into an empty project and copy /node_modules/glob
> * copy /node_modules/glob to YOUR_HARDHAT_PROJECT/node_modules/hardhat/node_modules/glob
> 
> It works.

It works, thanks for this.

**Comment by Maznuel** [comment]
> > I finally found it. glob@7.2.2 <- This is problem
> > I haven't looked for it exactly from what point, but it's version 7.2.0 in the package at the point where that package works well, and version 7.2.2 in the "nothing to compile" version.
> > 
> > * Type the "npm intstall glob@7.2.0" into an empty project and copy /node_modules/glob
> > * copy /node_modules/glob to YOUR_HARDHAT_PROJECT/node_modules/hardhat/node_modules/glob
> > 
> > It works.
> 
> Seems to work fine if you just do `npm install glob@7.2.0` in a current hardhat project, thank you

+1

**Comment by yasurid** [comment]
> I finally found it. glob@7.2.2 <- This is problem
> 
> I haven't looked for it exactly from what point, but it's version 7.2.0 in the package at the point where that package works well, and version 7.2.2 in the "nothing to compile" version.
> 
> * Type the "npm intstall glob@7.2.0" into an empty project and copy /node_modules/glob
> * copy /node_modules/glob to YOUR_HARDHAT_PROJECT/node_modules/hardhat/node_modules/glob
> 
> It works.

Yes it is working. Thank you so much..!

**Comment by LanreAkintayo** [comment]
> I finally found it. glob@7.2.2 <- This is problem
> 
> I haven't looked for it exactly from what point, but it's version 7.2.0 in the package at the point where that package works well, and version 7.2.2 in the "nothing to compile" version.
> 
> * Type the "npm intstall glob@7.2.0" into an empty project and copy /node_modules/glob
> * copy /node_modules/glob to YOUR_HARDHAT_PROJECT/node_modules/hardhat/node_modules/glob
> 
> It works.

It worked. Thanks

**Comment by AnujChandel** [comment]
YOUR_HARDHAT_PROJECT/node_modules/hardhat/node_modules/glob 
I don't have  node_modules/glob inside hardhat folder.

please tell me how did you downloaded hardhat

I downloaded it by following the instructions from 

https://hardhat.org/getting-started/

**Comment by yasurid** [comment]
> YOUR_HARDHAT_PROJECT/node_modules/hardhat/node_modules/glob I don't have node_modules/glob inside hardhat folder.
> 
> please tell me how did you downloaded hardhat
> 
> I downloaded it by following the instructions from
> 
> https://hardhat.org/getting-started/

No that will not placed like that you can find glob folder in YOUR_HARDHAT_PROJECT/node_modules folder.

**Comment by AnujChandel** [comment]
Replaced in it but doesn't work

**Comment by yasurid** [comment]
> Replaced in it but doesn't work

Delete the node_modules folder and run `npm install` command.

**Comment by AnujChandel** [comment]
> > Replaced in it but doesn't work
> 
> Delete the node_modules folder and run `npm install` command.

Can you specify the command

**Comment by yasurid** [comment]
npm install is the command.

**Comment by fvictorio** [comment]
Thanks @tylerK1294 for figuring that out. We'll look into this.

To clarify: this is only happening on windows, or is anyone facing this in other OS?

**Comment by fvictorio** [comment]
Hi everyone, I published a version of hardhat with the version of the `glob` dependency fixed to `7.2.0`.

Please try it with `npm i hardhat@dev` and let me know if it fixes this issue for you.

**Comment by ihorbond** [comment]
@fvictorio confirm, works for me

**Comment by fvictorio** [comment]
Hi everyone, we just released [`hardhat@2.9.6`](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.9.6), which fixes this issue. Please try it out and let us know if you are still getting the same problem. Thanks!
