### ISSUE TITLE
Using console.log() prints undefined to terminal

### ISSUE THREAD

**Issue by icepaq** [NomicFoundation/hardhat#2721]
This issue is regarding `console.sol` found at `packages/hardhat-core/console.sol`

Steps to Reproduce
1. Create or find an existing smart contract which you can run on a Hardhat network.
2. Add a `console.log()` anywhere in the contract.
3. Deploy your contract and call the function in which you added your blank log.

Expected: You see nothing (or a new line)
Actual: You see the word undefined being printed to your screen

Often to keep my JS logs organized, I will put a blank `console.log()` to create a new line in my terminal. However, doing so in Solidity code will result in `undefined` being printed to the screen. Below is a proposed solution that I have tested and found to work. I'll be creating a PR for this as well.

In `packages/hardhat-core/console.sol` on line 17

Replace `_sendLogPayload(abi.encodeWithSignature("log()"));` with `_sendLogPayload(abi.encodeWithSignature("log(string)", ""));`

**Comment by fvictorio** [comment]
Hey @icepaq, sorry for the auto-close, this is a great issue and I'm surprised no one has mentioned it before (that I can recall).

**Comment by fvictorio** [comment]
Fixed in [Hardhat v2.10.2](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.10.2). Thank you @icepaq for reporting this.
