### ISSUE TITLE
Random delay to a public node (while forking)

### ISSUE THREAD

**Issue by Nighrix** [NomicFoundation/hardhat#2740]
After setting up a forking project I run into this issue:

after a random amount of resets (sometimes on start up too) does hardhat face long waiting times, it can go from 100 ms up to 2 seconds per requests (this delay exists as long as the hardhat session is running)
I then tried to send a lot of requests to this node directly but never faced such long delays.

Results of testing:
80% of tests did take around 5 seconds to go through which is fine
but around 20% took 20 to 40 seconds
No changes to the code or anything just random delay
changing nodes didnt help either

**Comment by fvictorio** [comment]
Hi @Nighrix, thanks for reporting this. Could you help us reproduce this?

- Are you using a provider like Alchemy or Infura? Which one?
- Do you think you could create a reproduction example, even if the reproduction is "run this command 10 times and 2 of those times you'll notice a different duration"?

Thank you!
