### ISSUE TITLE
hardhat-etherscan detects wrong compiler version

### ISSUE THREAD

**Issue by thecodingcrow** [NomicFoundation/hardhat#2749]
Im trying to verify my contracts programmatically like its described in the hardhat-etherscan documentation, but it fails saying the detected compiler version doesnt match the specified one.

I specified ```pragma solidity ^0.8.4;``` in the contract in question and the following compiler versions in the hardhat config
```
solidity: {
  settings: {
    optimizer: {
      enabled: true,
      runs: 50,
    },
  },
  compilers: [
    {
      version: '0.8.4',
    },
    {
      version: '0.8.6',
    },
  ],
},
```
solc version
```
➜ npx solc -V   
0.8.13+commit.abaa5c0e.Emscripten.clang
```

hardhat-etherscan version
```
"@nomiclabs/hardhat-etherscan": "3.0.1",
```

Programmatic implementation of the verification:
<img width="258" alt="image" src="https://user-images.githubusercontent.com/53899975/170003816-4b1106a8-4aa8-4207-9064-b6b723714bc2.png">

```
Error: ERROR processing /Users/thedoc/ME/castle-webapp/deploy/01_deploy_crowns.ts:
NomicLabsHardhatPluginError: The contract you want to verify was compiled with solidity 0.7.6, but your configured compiler versions are: 0.8.4, 0.8.6.
```
**Full error log**
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/53899975/170005284-3b9fab02-da5b-4820-b15d-3501067bc1f3.png">

BUT, when I deploy the contract and try to verify it from the command line it works just fine:

```
hh verify --network rinkeby 0xB003C6336A1d671DC4839151bDc665f96c9dc201
```
<img width="629" alt="image" src="https://user-images.githubusercontent.com/53899975/170006457-32173156-023e-43ac-82a5-fc6b6aeeb4b5.png">

There is no place in my project where Im using solidity version 0.7.6, nor did I specify it anywhere.

**Comment by alcuadrado** [comment]
Hey @thecodingcrow, You are trying to verify a proxy, when you want to verify the implementation instead.

**Comment by thecodingcrow** [comment]
damn, youre right! I invested hours into this, turns out its being such a small error
