### ISSUE TITLE
ChainId opcode returns unexpected value

### ISSUE THREAD

**Issue by kasperpawlowski** [NomicFoundation/hardhat#2753]
Hi!

After the latest hardhat release (2.9.6), I noticed that some tests for the project I work for began to fail. After investigation it appeared that the following assembly code no longer returns chainId value that is configured in the `hardhat.config.js`:

```
assembly {
   id := chainid()
}
```

You can find minimal reproducible example in this repository: 
https://github.com/kasperpawlowski/hardhat-mre

I believe that this is pure oversight. The logic is written in a way that when `_forkBlockNumber` is undefined, `_forkNetworkId` is returned as `chainId` which shouldn't be the case I guess. I noticed that the bug was introduced in the following commit:
https://github.com/NomicFoundation/hardhat/commit/0d4a30f535a9c5ea196ce1da8e1d6de0a88418c3

It seems that the bug is simple to fix, take a look here:
https://github.com/NomicFoundation/hardhat/compare/master...kasperpawlowski:fix-chainId?expand=1

It went unnoticed because the tests for `chainId` are currently skipped for the non-fork mode. Please look at the branch I linked above. If you agree with my analysis I'll be happy to create PR.

**Comment by kasperpawlowski** [comment]
hey @alcuadrado. friendly reminder to take a look as promised in #2325 :)

**Comment by fvictorio** [comment]
Hey @kasperpawlowski, it's possible that this was fixed in [Hardhat v2.9.7](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.9.7). Could you please check if that's the case? Thanks!

**Comment by kasperpawlowski** [comment]
Hey @fvictorio. indeed, the issue was fixed in v2.9.6. thanks!
