### ISSUE TITLE
Add support for adding new JSON-RPC endpoints

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#2767]
(I believe we don't have an issue for this yet, so opening this one)

Plugins cannot add new JSON-RPC endpoints, but it would be great if they could. There are two interesting scenarios:

- Providers like Alchemy have some custom endpoints (for example, `alchemy_getTokenBalances`). This means that, if an app relies on those, the app won't work when connected to Hardhat Node. Allowing custom endpoints would let Alchemy create a `hardhat-alchemy` plugin that adds this.
- Flashpots has some custom endpoints too. See [this issue](https://github.com/NomicFoundation/hardhat/issues/2759) for more details.

**Comment by kanej** [comment]
Hardhat 3 supports plugins adding network hooks in request resolution. I am going to close this issue.
