### ISSUE TITLE
`console.log` does not work in `assembly` blocks

### ISSUE THREAD

**Issue by lukehutch** [NomicFoundation/hardhat#2770]
`console.log` statements do not work in `assembly` blocks. Is there any feasible way to add this?

**Comment by alcuadrado** [comment]
You can't really call a function like that in assembly, but you could imitate what console.log does inside.

**Comment by lukehutch** [comment]
Right, but maybe Yul could be extended somehow to add console.log?

**Comment by alcuadrado** [comment]
That's outside of the scope of this project though.

I would support adding native logging to Solidity/yul. You can propose it [here](https://github.com/ethereum/solidity/).
