### ISSUE TITLE
hardhat.config.ts:XX error TS2304: Cannot find name 'web3' [bug]

### ISSUE THREAD

**Issue by GeraldRyan** [NomicFoundation/hardhat#2774]
NOt a support ticket, I solved the issue for myself by explicitly importing hre in 2nd arg of task and namespacing web3, but the issue is 

Doing this tutorial: https://hardhat.org/guides/create-task.html
Having set up a typescript app as opposed to JS,
But otherwise following instructions to the letter, 
Running import "@nomiclabs/hardhat-web3"; 

web3 and Web3 objects fail to exist in my task scope.
VS code doesn't see these objects and running npx hardhat balance --account xyz also fails.
hardhat.config.ts:26:19 - error TS2304: Cannot find name 'web3'.
One can't run import 'hardhat' in the config file 
as Import 'hardhat' not allowed in config. 

As stated above I solved the issue issue for myself by explicitly importing hre in 2nd arg of task and namespacing web3

task("balance", "Prints an account's balance")
.addParam("account", "The account's address")
.setAction(async (taskArgs, hre)=>{
  const account = hre.web3.utils.toChecksumAddress(taskArgs.account)
  const balance = await hre.web3.eth.getBalance(account);
  console.log("Balance: ", hre.web3.utils.fromWei(balance, "ether"), "ETH")
})

But this wasn't part of the docs and I didn't find much help for this online, and I don't know what caused the docs and my local environment to be out of sync. 

Thank you

**Comment by fvictorio** [comment]
Hi @GeraldRyan. Thanks for the issue, but I'm going to close it because we recently re-wrote that guide and it doesn't use web3 anymore, so I'm going to guess that this is not a problem anymore. Please let me know if you disagree!
