### ISSUE TITLE
Hardhat Verification keeps failing

### ISSUE THREAD

**Issue by Talented-Developer** [NomicFoundation/hardhat#2776]
Hello
I am trying to deploy a contract and verify in one script but it throws following error, but sometimes it succeeds verifying.
```
NomicLabsHardhatPluginError: Failure during etherscan status polling. The verification may still succeed but
should be checked manually.
Endpoint URL: https://api-testnet.bscscan.com/api?apikey=J4FYAHY2MZAZHNY4YJFIQ6KT43AQFYA2VU&module=contract&action=checkverifystatus&guid=b9iapyku3d7utgn5pi3w3jmkjdjckecuitscabmjkhfp6g26zt
Reason: The HTTP server response is not ok. Status code: 403 Response text: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>403 - Forbidden: Access is denied.</title>
...
```

I would like to know when this happens.

**Comment by Talented-Developer** [comment]
https://linear.app/nomic-foundation/issue/HH-741/hardhat-verification-keeps-failing-%5Bnomicfoundationhardhat2776%5D

This link does not allow me to login.

**Comment by ezeamaka2** [comment]
For quite sometime now, Hardhat has been throwing error when trying to verify smart contract. However, I discovered a walk around and have even written an article about it.

Here how to verify your smart  contract on Etherscan using Remix IDE - https://medium.com/@ezeamaka2/how-to-verify-smart-contracts-on-etherscan-in-remix-ide-92f6354933b4

Just hit follow on medium to follow me. That's all I ask in return

**Comment by caoxmm** [comment]
have this problem too, tried many times

**Comment by ezeamaka2** [comment]
> have this problem too, tried many times

Well, I posted the solution above

**Comment by fvictorio** [comment]
Can someone provide reproduction steps?
