### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by ANMOLCODES** [NomicFoundation/hardhat#2780]
This issue is regarding a typo in <code>docs/guides/truffle-testing.md</code>.

In the '**Writing a test**' section, <code>const greeter2 = await Greeter.new("Hola, mundo!");</code> is mentioned in **line 94** which is incorrect because that line of code intends to set a new greeting. 

For that <code>setGreeting()</code> should be utilised.

**Correct code:-**
<code>const greeter2 = await Greeter.setGreeting("Hola, mundo!");</code>

**Comment by fvictorio** [comment]
Hi @ANMOLCODES. I'm not sure I understand what you are saying. Do you mean this test?

```js
  describe("Deployment", function () {
    it("Should deploy with the right greeting", async function () {
      const greeter = await Greeter.new("Hello, world!");
      assert.equal(await greeter.greet(), "Hello, world!");

      const greeter2 = await Greeter.new("Hola, mundo!");
      assert.equal(await greeter2.greet(), "Hola, mundo!");
    });
  });
```

If that's the case, I think it is correct: you are testing that the constructor argument is correctly reflected in the resulting `greet` variable.

**Comment by fvictorio** [comment]
Closing this because I think there's nothing wrong with the example. Please let me know if I'm missing something.
