### ISSUE TITLE
Does hardhat implement chai-as-promised or why do docs alude to it?

### ISSUE THREAD

**Issue by TimDaub** [NomicFoundation/hardhat#2791]
- from what I understand, to `await` expect, `chai` needs an extra plugin: https://www.chaijs.com/plugins/chai-as-promised/
- however, e.g. the hardhat docs https://hardhat.org/tutorial/testing-contracts show how to test with `await expect` without explicitly using chai-as-promised

```
await expect(
        hardhatToken.connect(addr1).transfer(owner.address, 1)
      ).to.be.revertedWith("Not enough tokens");
```

instead, only chai's expect is required

```
const { expect } = require("chai");
```

Is this a mistake in the documentation or is hardhat monkeypatching chai? Or does chai now implement awaitable `expect`?

**Comment by fvictorio** [comment]
> * from what I understand, to `await` expect, `chai` needs an extra plugin

Not exactly. If a custom matcher (like `revertedWith`) "returns" a promise, then it can be awaited. That's how waffle matchers are implemented under the hood.

So what's going on here is: you are using `hardhat-waffle`, which includes Waffle's chai matchers, which has matchers like `revertedWith`, that are "promise-like" and therefore can be awaited.

As far as I know, waffle doesn't add `chai-as-promised`. You should be able to double-check this by doing `await expect(Promise.resolve(1)).to.eventually.equal(1)`

Hope this answers your question, let me know if it doesn't.

(As a side note: we are working on [our own chai matchers](https://www.notion.so/nomiclabs/Public-Hardhat-Chai-Matchers-11feb9185dd54591999f4e813f90c10c) and they _will_ include `chai-as-promised`. Do you think there's a problem with that, or it's just something you'd expect to see explicitly documented?)
