### ISSUE TITLE
Etherscan verification broken (Ropsten)

### ISSUE THREAD

**Issue by lucas-janon** [NomicFoundation/hardhat#2794]
Hi, I'm trying to verify contracts on Ropsten and getting the following error:

```
Error in plugin @nomiclabs/hardhat-etherscan: The contract verification failed.
Reason: Fail - Unable to verify
```

To make sure the problem wasn't my setup, I tried to verify the Greeter contract from Hardhat's scaffolding.

To reproduce:
* `npx hardhat init`
* Choose `Create an advanced sample project that uses TypeScript`
* Add your environment variables to `.env` (Private key + Etherscan)
* In `contracts/Greeter.sol` add a dumb function or do any small change, this is so Etherscan doesn't match your bytecode to an existing, similar deploy
* Deploy your contract `npx hardhat run scripts/deploy.ts --network ropsten`
* Add a `scripts/ropsten.js` file with the following contents `module.exports = ["Hello, Hardhat!"];`
* Run `npx hardhat verify --network ropsten --constructor-args scripts/ropsten.js <address>`

This is probably an Etherscan issue, but I wanted to leave it here so people don't lose time thinking there's an issue with their setup like I did yesterday.

**Comment by ezeamaka2** [comment]
Hardhat have been throwing error for quite sometime now when trying to verify smart contracts. However, I discovered a walk around and have even written an article about it on medium. 

Here is a link to article - https://medium.com/@ezeamaka2/how-to-verify-smart-contracts-on-etherscan-in-remix-ide-92f6354933b4

Just hit follow, that's all I ask in return
