### ISSUE TITLE
sh: hardhat: command not found

### ISSUE THREAD

**Issue by fennar01** [NomicFoundation/hardhat#2798]
Hi there, I think I've managed to stumble upon a bit of an obscure bug. 

I've been working on fixing it for the past couple of days and I've also had some assistance - it appears to be a HH issue but we're having trouble reproducing it anywhere outside of my local machine.

Essentially I keep getting the error "sh: hardhat: command not found" when issuing a "npx hardhat clear" command from my HH directory.

I've been installing it using both npm and yarn (independently at first, I've also tested together) using dev flags, and both installs exit with code 127 at different places. 

I can get hardhat to fire if I install it in a parent directory, however, it only fires once, then after that, it just gives me a HH12 error even though I've not got HH installed globally.

After reading the install logs, it appears "utf-8-validate" can't install correctly via npm or yarn which is a bit annoying.

Heads up I'm using:
macOS Monterey V12.4
node v16

We've also tried [cloning a repo we know is working](https://github.com/YonTracks/smartcontracts), and after trying to build from there, it's giving us the same output "sh: hardhat: command not found".

I've also tried totally reinstalling node and nvm.

I've been having a bit of trouble with this one, and even after investigation, I'm coming up blank - the only deduction myself and [another dev](https://github.com/YonTracks) have made is that it appears to be localized to my machine, difficult to reproduce and have something to do with node and hardhat. We're not sure why it's happening, but after looking on [stack exchange](https://stackoverflow.com/questions/70858571/sh-hardhat-command-not-found-when-installing-hardhat), I'm not the only one who's experiencing it!

**Comment by fennar01** [comment]
Resolved

**Comment by davidAI04** [comment]
@fennar01  how do you resolved this problem? I'm faced the same problem since several hours.

I'm using: 
MacBook Pro (M1, 2020)
macOS Monterey V12..2.1
node 16.6.0
nvm 0.39.1

Thank u

**Comment by fennar01** [comment]
Okay, I didn't post this before because to be honest... It's rule #1 😅

I rebooted my pc...

Hope it helps!

F

**Comment by davidAI04** [comment]
@fennar01. I already found a solution for this... using NPX.
The Node Package eXecute allows us to directly access and execute a package stored (or not) in `$ ./node_modules/.bin/your-package`.

Using `npx hardhat [GLOBAL OPTIONS] <TASK>` everything works fine!
