### ISSUE TITLE
stand-alone "hardhat node"

### ISSUE THREAD

**Issue by drortirosh** [NomicFoundation/hardhat#2804]
running `hardhat node` is great, and we use it a lot.

However, it requires a hardhat project, and some parameters are only read from the hardhat.config file, and not from command-line.

In the past you mentioned ([here..](https://github.com/NomicFoundation/hardhat/issues/2167#issuecomment-1007510137)) that you intend to release a standalone command-line to start a node.

When will such a standalone command-line be available?

**Comment by fvictorio** [comment]
Hi @drortirosh, the issue tracking that is #2080. It's high on our priority list, but I don't have an ETA of when it will be ready. We'll post any updates we have on that issue if you want to subscribe to it.
