### ISSUE TITLE
Problem with apiKey , i am getting Invalid API key everytime

### ISSUE THREAD

**Issue by anjanayraina** [NomicFoundation/hardhat#2823]
```
require("@nomiclabs/hardhat-waffle");
require("@nomiclabs/hardhat-etherscan");
const dotEnv = require("dotenv");
dotEnv.config();

// This is a sample Hardhat task. To learn how to create your own go to
// https://hardhat.org/guides/create-task.html
task("accounts", "Prints the list of accounts", async (taskArgs, hre) => {
  const accounts = await hre.ethers.getSigners();

  for (const account of accounts) {
    console.log(account.address);
  }
});

// You need to export an object to set up your config
// Go to https://hardhat.org/config/ to learn more

/**
 * @type import('hardhat/config').HardhatUserConfig
 */
module.exports = {
  solidity: "0.8.7",
  networks: {
mumbai : {

  url : process.env.POLYGON_MUMBAI,
  accounts : [process.env.PRIVATE_KEY]
},

  },

  etherscan : {
apiKey : process.env.PRIVATE_KEY 

  } ,
};

```

**Comment by neoplastic** [comment]
Yeah, I'm receiving this problem as well trying to use the rinkeby network.

**Comment by iKausik** [comment]
@anjanayraina  @neoplastic  Which API key you're using here?

**Comment by Aubuga** [comment]
seems that hardhat guys couldnt solve this issue yet, i ve tracked opened issue and in none of them a solution was provided

**Comment by fvictorio** [comment]
@anjanayraina this is wrong:

```
apiKey : process.env.PRIVATE_KEY 
```

You are using a private key as the API key. Instead, you have to register an account in Etherscan and obtain an API key.

@neoplastic @Aubuga I'm not sure about your problems, but an invalid API key is just that. It can be an error in your config (in which case you can add a console.log somewhere to print the API key you are ending up with) or it could be that you are using an API key from another etherscan-powered explorer (for example, if you use an API key for mainnet to verify a contract in BSC, you'll get this error message too).

**Comment by FrankFan** [comment]
the same issue to me with rinkeby network, ervery time when I run command: `npx hardhat verify --network rinkeby xxxxx` error was: `Error in plugin @nomiclabs/hardhat-etherscan: Invalid API Key`.

My apiKey was created from `etherscan.io`: `API keys created on Etherscan.io can be used for the Kovan, Rinkeby, Ropsten, Sepolia and Goerli Testnets.`

and test my apiKey with : `https://api.etherscan.io/api?module=account&action=balance&address=0xa9Aa4613FAdA2287935xxxxxx8b5b50&tag=latest&apikey=xxxxx ` , result was OK.

but why hardhat command result was `Invalid API Key` ? 😭

**Comment by fvictorio** [comment]
@FrankFan that might be the same problem as in https://github.com/NomicFoundation/hardhat/issues/2849. We need to look into that.
