### ISSUE TITLE
hardhat-chai-matchers depends on sinon-chai

### ISSUE THREAD

**Issue by vimwitch** [NomicFoundation/hardhat#2836]
The @nomicfoundation/hardhat-chai-matchers package currently includes a `types.d.ts` file with this line:
```
/// <reference types="sinon-chai" />
```

This causes a build error when the `@types/sinon-chai` package isn't available. Ideally we wouldn't install this package, is it possible to remove this from the output?

**Comment by alcuadrado** [comment]
Thanks for this bug report, @vimwitch! I fixed it. You can read how that package ended up there in the PR.

**Comment by vimwitch** [comment]
Thanks @alcuadrado, great response time 🤩
