### ISSUE TITLE
docs: links pointing to sections are broken

### ISSUE THREAD

**Issue by s1na** [NomicFoundation/hardhat#2850]
Hey there! I was going through the docs and noticed links that point to a specific section of a page are broken. E.g. in [hardhat-network](https://hardhat.org/hardhat-network) page, there are a couple links like: https://hardhat.org/hardhat-network/reference.md#debug-tracetransaction, https://hardhat.org/config.md#hardhat-network, and https://hardhat.org/hardhat-network/reference.md#console-log (notice the extra `.md`).

Also the "Help us improve this page" link is broken 😄

**Comment by alcuadrado** [comment]
Hey @s1na! 👋

We actually fixed this bug a few days ago, but I guess the fix landed in our `next-version` branch.

Can you take a look at this, @fvictorio?

**Comment by fvictorio** [comment]
@s1na indeed, this will be fixed when we release the next version of our documentation (which we'll do within the next week).

I'm going to close this now, but thanks a lot for noticing and reporting this!
