### ISSUE TITLE
receive/fallback function revert issue:

### ISSUE THREAD

**Issue by Flame57** [NomicFoundation/hardhat#2880]
I forked from mainnet, and when the contract received transfer, it always revert, even for some simple code like below.

Error: Transaction reverted and Hardhat couldn't infer the reason.

```
    receive() external payable {
        console.log("! ! ! received ! ! !", address(this));
        console.log("receive amount ", msg.value);
        console.log("from ", msg.sender);
        console.log("balance now ", address(this));
    }
```

**Comment by feuGeneA** [comment]
Thank you for using Hardhat.

In general, if there is a problem in Hardhat, we will need a minimal reproducible example in order to investigate it. See https://stackoverflow.com/help/minimal-reproducible-example

Can you provide us with a minimal reproducible example?
