### ISSUE TITLE
Hardhat Svelte code: 'ERR_REQUIRE_ESM' error.

### ISSUE THREAD

**Issue by cagrigit-hub** [NomicFoundation/hardhat#2882]
I created my svelte app by writing to command line 
`npm init svelte app-name ` 

Than I initialized Hardhat by `npx hardhat` and choosed Basic Sample Project template to get started.

Than I wrote my Smart Contract and tried to deploy it to local network after I started local node by 
`npx hardhat node --network localhost`
`npx hardhat run . \scripts\deploy.js`

Than this error occured: 
![image](https://user-images.githubusercontent.com/77447064/176016793-13edeeb5-1a58-4a8a-8d35-2946b36ca713.png)

Then I tried some configuration settings, changing require statements to import statements. Changed module type. But none of them has worked. 
I thought maybe I got the problem so I didn't change anything at all and I used completely default setting, default contract created by Basic Sample Project. And I got same errors. So I googled it and I saw people like me on the internet have same problem with SvelteKit + Hardhat.

So I seperated my hardhat and sveltekit folders to solve this problem and as I expected It worked. But clearly there is a problem with hardhat+SvelteKit. How we can solve that problem? 

I saw at your website that you're hiring. I really love using Hardhat and I would want to work on that problem with SvelteKit+Hardhat (Or maybe some other problems with other web frameworks). As far as I know It works great with NextJS, ReactJS. I couldn't try it with Vue & Angular.

**Comment by cagrigit-hub** [comment]
![image](https://user-images.githubusercontent.com/77447064/176018212-fe8c2d09-1912-41b6-a2f2-294e8273a76d.png)
This is the working version, for whom looking for valid solution rn

**Comment by alcuadrado** [comment]
Thanks for opening this issue. Can you share your frontend's `package.json` file?

**Comment by cagrigit-hub** [comment]
![image](https://user-images.githubusercontent.com/77447064/176228346-68325b3b-0b3f-4f5f-89c9-65a7433e6a69.png)
Here it is. @alcuadrado

**Comment by alcuadrado** [comment]
The problem is that you are using `"type": "module"`, so node.js interprets your config file as an ESM module, and Hardhat doesn't currently support ESM.

**Comment by alcuadrado** [comment]
Oh, I see. Sorry, I thought you didn't understand what was going on.

Yes, unfortunately, you need to use it like that. I think in the meantime, we can detect that error when loading the config, and replace it for something clearer. If you feel like sending a PR doing this, I can give you pointers.

Adding support for ESM is more complex than it seems, as ESM doesn't evaluate imported modules in order, whereas CJS does, and our plugin system depends on that. So it needs a breaking change, and not a small one.

**Comment by cagrigit-hub** [comment]
Which topic should I PR to?

**Comment by ajcwebdev** [comment]
Probably not going to be telling you anything you don't already know, but just want to +1 that I've encountered these same issues and this is something that I think is going to be a hard blocker for many JavaScript developers wanting to use Hardhat. The integration is difficult enough that a lot of people will decide to say screw it and swap out a piece of the stack.

It's not impossible, of course, but you need to create a clean boundary between the parts of the project that are CommonJS (Hardhat) versus the parts of the project that are ESM (everything else). You almost need a monorepo tool to pull it off at which point you've stopped being a tool that makes devs life easier and have become one that makes it harder.

> See [this StackOverflow issue](https://stackoverflow.com/questions/70714785/use-hardhat-es5-together-with-sveltekit-es6) for a thorough description of why finding a workable solution with SvelteKit today is nearly impossible. I was [able to get Astro working](https://github.com/ajcwebdev/taking-astro-to-the-moon) by changing `astro.config.js` to `astro.config.mjs` and omitting `type` in `package.json` but SvelteKit doesn't like `svelte.config.mjs` for some reason.

If a developer has already decided they want a particular metaframework that is based on ESM (which is going to be almost all of them in the next year or two) then the decision to use a different tool that won't completely blow up your build tooling like Foundry becomes almost a given.

I totally agree that adding ESM support is more complex than almost anyone realizes unless they've had to migrate a framework from CommonJS to ESM. But if adding proper ESM support is going to be a long ways out (like more than 2 or 3 months), then I'd recommend providing a boilerplate example app to address this issue.

It would need to be built with the assumption that the frontend has its own cleanly separated repo from the Hardhat project files where are in their own different repo. Sounds like @cagrigit-hub already has a working implementation and you should jump at the opportunity to make that official.

**Comment by ajcwebdev** [comment]
Here's an example repo using Vite's Svelte template for anyone's reference: [svelte-vite-web3](https://github.com/ajcwebdev/svelte-vite-web3)

**Comment by fvictorio** [comment]
Hi folks, please check my comment [here](https://github.com/NomicFoundation/hardhat/issues/957#issuecomment-1256094430). The tl;dr is that we published a version of Hardhat with basic support for ESM. You can try it with `npm i hardhat@esm`.
