### ISSUE TITLE
Hardhat Tutorial Step 6 `console.log` docs link broken

### ISSUE THREAD

**Issue by abidsikder** [NomicFoundation/hardhat#2884]
On step 6 of the hardhat tutorial https://hardhat.org/tutorial/debugging-with-hardhat-network , the link at the bottom 
![image](https://user-images.githubusercontent.com/41392423/176266101-97c06d92-98fe-4b02-90db-7ece8add43ef.png)

to find out more about the hardhat network `console.log` feature is broken as it redirects to https://hardhat.org/hardhat-network/index.md#console-log which gives a 404.

That link should instead be replaced with https://hardhat.org/hardhat-network/reference#console-log

**Comment by feuGeneA** [comment]
This was fixed in a recent overhaul of the documentation, but thank you for reporting it!
