### ISSUE TITLE
chainId returns "31337" on Mainnet fork

### ISSUE THREAD

**Issue by rodrigoherrerai** [NomicFoundation/hardhat#2892]
### I tried different ways of returning chainId but they all failed to return the correct number. 

```js 

function getChainId() external view returns (uint chainId) {
        assembly {
            chainId := chainid()
        }
    }

    function getChainId() external view returns (uint chainId) {
        return block.chainid;
    }

    function getChainId() external returns (uint chainId) {
        return block.chainid;
    }
  
const chainId = await ethers.provider.getNetwork(); 

```

**Comment by feuGeneA** [comment]
Thank you for using Hardhat.

We do have tests of this functionality, [here](https://github.com/NomicFoundation/hardhat/blob/master/packages/hardhat-core/test/internal/hardhat-network/provider/modules/eth/chainId.ts#L26), which use the contract [here](https://github.com/NomicFoundation/hardhat/blob/master/packages/hardhat-core/test/internal/hardhat-network/helpers/contracts.ts#L435), which were seen to be working most recently via CI [here](https://github.com/NomicFoundation/hardhat/runs/7239394168?check_suite_focus=true#step:6:1387).

What version of Hardhat were you using? Can you try with the latest release? If that doesn't solve it, can you provide a minimal reproducible example? See https://stackoverflow.com/help/minimal-reproducible-example

**Comment by rodrigoherrerai** [comment]
Here is the minimal reproducible example: https://github.com/rodrigoherrerai/HARDHAT-CHAIN-ID

The example is in the last version '2.9.9'. 

But I also tried it with the latest release and it fails as well.

**Comment by rodrigoherrerai** [comment]
@SfyMantissa  How did you fix it ? I believe it is a Hardhat issue. Did you modify their codebase?

**Comment by alcuadrado** [comment]
Hey, sorry for the late reply.

Hardhat network always uses the chain id from your config, which defaults to 31337.

We decided to do this, including when forking a network, as signing txs with another network's id is a security risk. For example, a malicious test could steal your funds.

If you really need to use the remote network's id, you should set it in your config.

**Comment by peetzweg** [comment]
@alcuadrado setting it in the `hardhat.config.ts` works flawlessly. However, I would like to start a fork local node using the `hardhat node --fork` cli flag. It will pick up the chainId from the config, but I would rather pass in the also the `chainId` dynamically on the cli, with an argument like `--chain-id`.

Can we get a feature like that?

**Comment by fvictorio** [comment]
@peetzweg that feature request is being tracked [here](https://github.com/NomicFoundation/hardhat/issues/2305).
