### ISSUE TITLE
HardhatNetworkHelpersError: Invalid timestamp 1657236743 is not larger than current timestamp 1716852786

### ISSUE THREAD

**Issue by Hirama** [NomicFoundation/hardhat#2906]
Cant manipulate with correct timestamp.

_"hardhat": "^2.10.0"
"@nomicfoundation/hardhat-network-helpers": "^1.0.2"_

The code
```
console.log("Now:", Math.floor(Date.now() / 1000))
console.log("Latest:", await time.latest());
await time.setNextBlockTimestamp(Math.floor(Date.now() / 1000));
```
Console
```
Now: 1657236743
Latest: 1716852786
```
Error
**HardhatNetworkHelpersError: Invalid timestamp 1657236743 is not larger than current timestamp 1716852786**

**Comment by alcuadrado** [comment]
Hey! Thanks for reporting this issue so quickly 🙌

Are you forking a remote network?

**Comment by Hirama** [comment]
> 

Hey! Nope, just running the tests

**Comment by feuGeneA** [comment]
> > 
> 
> Hey! Nope, just running the tests

Which tests? Something you can point us to?

**Comment by Hirama** [comment]
> > > 
> > 
> > 
> > Hey! Nope, just running the tests
> 
> Which tests? Something you can point us to?

`npx hardhat test`

The problem is that `block.timestamp` returns time from distant future
<img width="587" alt="image" src="https://user-images.githubusercontent.com/2853815/178283454-b01803f9-425e-4470-8189-dc1652f11563.png">

**Comment by joglea** [comment]
@feuGeneA  My hardhat project has similar problem . I run the "npx hardhat node" .
When I repeat test my script "test/Lock.js" ,the local hardhat node's block.timestamp is bigger and bigger than my local timestamp.
first the block.timestamp is smaller than my local timestamp:
npx hardhat test test/Lock.js

![1](https://user-images.githubusercontent.com/2239700/178896113-196f013c-132a-4599-9b95-fff07a909157.png)

![2](https://user-images.githubusercontent.com/2239700/178896262-d2e1b7b4-1893-4704-b9b7-2933f281f3e5.png)
![3](https://user-images.githubusercontent.com/2239700/178897332-6805691f-7ed5-4fdf-84d3-3933f765c850.png)
![4](https://user-images.githubusercontent.com/2239700/178897341-073fe71b-0003-4ccd-bde0-aba15225341b.png)

...
after run my test script for several times, the block.timestamp is bigger than my local timestamp:

![6](https://user-images.githubusercontent.com/2239700/178897369-62469bd6-e106-43af-9786-a45072a30d5a.png)
![7](https://user-images.githubusercontent.com/2239700/178897633-b6fa2731-9920-45fa-88fd-62375f0917a9.png)


the block.timestamp will get bigger

my test project's zip file :

[test-hardhat.zip](https://github.com/NomicFoundation/hardhat/files/9108351/test-hardhat.zip)

**Comment by kasoqian** [comment]
I meet this problem too.

**Comment by kasoqian** [comment]
The reason I found this solution is because there is another test file which is named `Lock.sol` and this file has a modified timestamp in it. Just comment out this default file.

like this:
````js
 // const unlockTime = (await time.latest()) + ONE_YEAR_IN_SECS;
````

@alcuadrado @joglea @Hirama @feuGeneA

**Comment by kasoqian** [comment]
> @feuGeneA My hardhat project has similar problem . I run the "npx hardhat node" . When I repeat test my script "test/Lock.js" ,the local hardhat node's block.timestamp is bigger and bigger than my local timestamp. first the block.timestamp is smaller than my local timestamp: npx hardhat test test/Lock.js
> 
> ![1](https://user-images.githubusercontent.com/2239700/178896113-196f013c-132a-4599-9b95-fff07a909157.png)
> 
> ![2](https://user-images.githubusercontent.com/2239700/178896262-d2e1b7b4-1893-4704-b9b7-2933f281f3e5.png) ![3](https://user-images.githubusercontent.com/2239700/178897332-6805691f-7ed5-4fdf-84d3-3933f765c850.png) ![4](https://user-images.githubusercontent.com/2239700/178897341-073fe71b-0003-4ccd-bde0-aba15225341b.png)
> 
> ... after run my test script for several times, the block.timestamp is bigger than my local timestamp:
> 
> ![6](https://user-images.githubusercontent.com/2239700/178897369-62469bd6-e106-43af-9786-a45072a30d5a.png) ![7](https://user-images.githubusercontent.com/2239700/178897633-b6fa2731-9920-45fa-88fd-62375f0917a9.png)
> 
> the block.timestamp will get bigger
> 
> my test project's zip file :
> 
> [test-hardhat.zip](https://github.com/NomicFoundation/hardhat/files/9108351/test-hardhat.zip)

look! You have the `Lock` test file, delete it that will work!

**Comment by vladikopl01** [comment]
I had the same problem while running tests. Every test with expected equals for `latest()` and the computer's timestamp causes test failure and has a difference in time of 1 sec. I make data struct on contract based on computer's timestamp and then get back this struct to expect creating process was performed without issues, but get the difference in time.

**Comment by vladikopl01** [comment]
> I had the same problem while running tests. Every test with expected equals for `latest()` and the `block.timestamp` causes test failure and has a difference in time of 1 sec. I make data struct on contract based on `latest()` timestamp and then get back this struct to expect creating process was performed without issues, but get the difference in time.
> 
> Here is my test case:
> 
> ```ts
> it('fail - invalid start date', async () => {
>       const actionWallet: SignerWithAddress = bcdOwnerWallet;
>       const saleInfo: SaleInfo = {
>         ...defaultSaleInfo,
>         startDate: toBN((await latest()) - 1000),
>       };
> 
>       const salesCounterBefore = await bcdContract.connect(actionWallet).getSaleCount();
> 
>       await checkContractOwner(actionWallet.address, bcdContract, true);
> 
>       await expect(createSale(bcdContract, actionWallet, saleInfo))
>         .to.be.revertedWithCustomError(bcdContract, CustomErrors.INVALID_START_DATE)
>         .withArgs(saleInfo.startDate, await latest());
> 
>       const salesCounterAfter = await bcdContract.connect(actionWallet).getSaleCount();
>       expect(salesCounterAfter).to.be.eq(salesCounterBefore);
>     });
> ```
> 
> So, I had a `saleInfo` data object which I expected not to be added as Sale struct to the contract's state, because of raised custom error on contract. It should be reverted with such parameters as `saleInfo.startDate` and `block.timestamp` which should be equal in test to `saleInfo.startDate` and `latest()`, as `latest()` should return `block.timestamp` time, but it differs just for 1 sec.

I realized that `latest()` function returns the latest block timestamp and my custom error returns `block.timestamp` of the possible next block, so there is a difference in 1 sec between them. 

It will be great to have such a function to get the next possible timestamp of the block, which is proceeded by the current transaction, if it is possible at all. Anyways, I will be glad to hear any ideas on how to resolve my problem appropriately.
