### ISSUE TITLE
Use blockscout when using `customChains` in the etherscan plugin

### ISSUE THREAD

**Issue by clemsos** [NomicFoundation/hardhat#2924]
I am trying to add Celo to my wokflow, so I added this to my hardhat config:

```js
const etherscan = {
  apiKey: {
    celo: 'api-key',
  },
  customChains: [
    {
      network: 'celo',
      chainId: 42220,
      urls: {
        apiURL: 'https://explorer.celo.org/api',
        browserURL: 'https://explorer.celo.org/',
      },
    },
  ],
}
```

Then when verifying a contract, I got the following error

```
Error in plugin @nomiclabs/hardhat-etherscan: Failed to send contract verification request.
Endpoint URL: https://explorer.celo.org/api
The HTTP server response is not ok. Status code: 400 Response text: {"message":"Unknown action","result":null,"status":"0"}
```

The [Celo explorer is using blockscout](https://explorer.celo.org/), which is already impemented in the plugin so I was wondering if there will be a way to specify it when adding custom chains.

Many thanks !

**Comment by fvictorio** [comment]
Hi @clemsos. Blockscout has a etherscan-compatible API for verification, so this looks like it should work.

Maybe you can open an issue on [their explorer's repo](https://github.com/celo-org/blockscout)?

**Comment by clemsos** [comment]
thank you for the answer, I'll try that !

**Comment by clemsos** [comment]
> Hey checkout the PR #2933

thanks @therealharpaljadeja that seems to work. Actually shame on me... I was using some outdated urls for the api and browser.
