### ISSUE TITLE
[chai-matcher] Feature request: `withArgs` should compare arguments of an event using `deep` equal

### ISSUE THREAD

**Issue by songhobby** [NomicFoundation/hardhat#2926]
Currently I don't know how to check an emitted event having `struct` as one of its arguments.
I was thinking of a solution like custom predicates for individual arguments 
```
    await expect(contract.someFunction)
      .to.emit(contract, "SomeEvent")
      .withArgs(
        someAddress,
        (value: any) => {
          expect(value).to.deep.equal(someStruct);
          return true;
        }
      )
```

**Comment by feuGeneA** [comment]
Thank you for using Hardhat. GitHub Issues are intended to be used only for known or suspected problems with Hardhat, or for feature requests.  For questions or other help, please use either [our Discord server](https://hardhat.org/discord) or [the GitHub Discussions feature](https://github.com/nomiclabs/hardhat/discussions/) instead.

Please note that there are existing tests of using structs with `withArgs`, [here](https://github.com/NomicFoundation/hardhat/blob/master/packages/hardhat-chai-matchers/test/events.ts#L373-L390), and those tests use the contract method defined [here](https://github.com/NomicFoundation/hardhat/blob/master/packages/hardhat-chai-matchers/test/fixture-projects/hardhat-project/contracts/Events.sol#L85).

Also note that there existing tests that use custom predicated [here](https://github.com/NomicFoundation/hardhat/blob/master/packages/hardhat-chai-matchers/test/events.ts#L443-L495).
