### ISSUE TITLE
Add Celo and Alfajores in networks available to verify contracts via `hardhat verify`

### ISSUE THREAD

**Issue by therealharpaljadeja** [NomicFoundation/hardhat#2932]
## Description of the issue
At [CELO](https://github.com/celo-org), we are looking to easily + automatically verify contracts on the Celo and Alfajores network.

Verifying contracts via the RPC endpoint of the Celo Blockscout instance is quite complicated. We currently rely on manual verification by flattening Solidity files.

It would be great if we could add the Celo and Alfajores network to the list of networks available on the [hardhat-etherscan](https://github.com/NomicFoundation/hardhat/tree/master/packages/hardhat-etherscan) package.

This would help us (the team) tremendously and would provide a better developer experience for people building on Celo. Verifying contracts on Celo and Alfajores from any hardhat project would be as simple as running the command

`npx hardhat verify --network celo`

It would then be more developer/user friendly to interact with them via the Celoscan explorer using the contract methods fields.

## Proposed solution
Add the Celo and Alfajores network to the list of networks under the @nomiclabs/hardhat-etherscan package.

#2933

**Comment by ericnakagawa** [comment]
Would love to see this PR accepted. It is the top feature request from the many hackathons we have supported this year.

Improving the verification process for Celo devs helps increase quality and security of our community!

**Comment by tab00** [comment]
I get error "Network alfajores doesn't exist". What's the status of this issue?

**Comment by fvictorio** [comment]
Closing this since in general we are not adding new networks to `hardhat-verify`.

Adding support for a new network is simple, check [here](https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-verify#adding-support-for-other-networks). This can then be easily packaged in a `hardhat-celo` plugin. Happy to answer questions/light review that if someone implements it.
