### ISSUE TITLE
[hardhat-etherscan] hangs indefinitely with no timeout/error after "Successfully submitted source code for contract"

### ISSUE THREAD

**Issue by stevieraykatz** [NomicFoundation/hardhat#2942]
I'll preface by saying that this worked for me last week and reverting to an older branch demonstrates the same behavior. 

After deploying my contracts and verifying that they exist on the block explorer, I'm calling the verify task against the attached contracts. 

I get the following: 
`Nothing to compile
No need to generate any newer typings.
Successfully submitted source code for contract
contracts/SeasonOne.sol:SeasonOne at 0xd6837D0A13678fAeC5bF7A8720463Ed92C9B07cF
for verification on the block explorer. Waiting for verification result...`

This will hang indefinitely until killed. No error is returned and it doesn't seem to time out either. I will submit manually but figured that this at least shows that there needs to be a timeout. Not sure if there are other uncaught errors causing this to hang. I'll happily share anything else necessary to help reproduce. 

Other information: 

Repo: https://github.com/coinlander/Coinlander/
Branch: main
Network: Arbitrum Testnet

**Comment by Archethect** [comment]
I have the same issue. Still not resolved but arbiscan status seems to be up gain.

**Comment by stevieraykatz** [comment]
Works now! Thank you @Enigmatic331 ! 

I still think that hardhat should more gracefully handle a hung request. Will leave open unless someone suggests otherwise.
