### ISSUE TITLE
Blind "reverted with an unrecognized custom error"

### ISSUE THREAD

**Issue by k06a** [NomicFoundation/hardhat#2948]
Please add hex representation of "unrecognized custom error". Sometimes revert comes from external smart contract, we have no source code. Especially when we fork mainnet.

**Comment by alcuadrado** [comment]
That's a really good point.

Would you prefer having it as part of the error message, as a field of the error, or both?

**Comment by k06a** [comment]
@alcuadrado having just `(0x***)` at the end of the error message would be just amazing. Now we are putting `console.logBytes()` before bubble revert to see an actual revert reasons :(

**Comment by alcuadrado** [comment]
Great idea! @feuGeneA will implement this asap
