### ISSUE TITLE
Where did `advanced typescript project` go?

### ISSUE THREAD

**Issue by masafumimori** [NomicFoundation/hardhat#2956]
There used to be a choice for `advanced typescript project` (it might be different if I remember it wrong) when starting a project wit `npx hardhat`.

But there is no choice for the advanced anymore and in [the doc](https://hardhat.org/hardhat-runner/docs/guides/project-setup), nothing is mentioned about it.

It was helpful for me so I liked it and used it.

Has it been removed for some reasons?

**Comment by alcuadrado** [comment]
Hey @masafumimori,

We removed it to create a more streamlined initial experience. If you install the `typescript` project you get almost the same.

The only missing things are:
* `prettier` and `prettier-solidity` are not installed — You can get them using [our VSCode extension](https://marketplace.visualstudio.com/items?itemName=NomicFoundation.hardhat-solidity).
* `dotenv` is not installed.
* `eslint` is not installed.
* `solhint` is not installed.

Some of these things, like `solhint` and `prettier-solidity` will be integrated through plugins, and added to the Hardhat Toolbox. Others, like `dotenv`, will be replaced with built-in alternatives in Hardhat.

**Comment by fvictorio** [comment]
For anyone landing here: we are going to create some GitHub templates to cover this need. We'll comment here when they are ready.
