### ISSUE TITLE
Set ETH balance when impersonateAccount is called.

### ISSUE THREAD

**Issue by rokso** [NomicFoundation/hardhat#2963]
While `helpers.impersonateAccount()` and `ethers.getImpersonatedSigner()` are very useful and reduced my code by few lines and it will be better to set some ether balance after impersonate is called. It will help with impersonating contract with 0 ETH balance. 
I am currently explicitly calling `setBalance()` after each call to impersonate.

**Comment by feuGeneA** [comment]
Thank you for using Hardhat, and for sharing your suggestions.

Please note that in @nomiclabs/hardhat-ethers v2.1.0 we "added new helper getImpersonatedSigner(), a shorthand for invoking the hardhat_impersonateAccount JSON-RPC method followed immediately by ethers.getSigner()."

I do not foresee us adding an _additional_ helper that also sets the balance, but if it's important to you and others we would certainly consider it, so feel free to re-open this if you feel strongly about it.

**Comment by rokso** [comment]
I am aware of `getImpersonatedSigner`. 
FYI I was not asking to add another helper. What I was asking is to set ETH balance by default when someone calls `getImpersonatedSigner` or `hardhat_impersonateAccount`. But I get it that it is not looking useful/promising to you. I have my workaround in place so I am fine anyway. Thanks for your response.
