### ISSUE TITLE
Error: "setData is assigned a value but never used"

### ISSUE THREAD

**Issue by mvwmotor** [NomicFoundation/hardhat#2972]
Hello,
Excuse me for disturbing you,

I meet a problem when I start the react app, the app start without any problems but the number of the NFT already sold don't appears and the price also (you can see on the screen).

<img width="483" alt="Capture d’écran 2022-07-20 à 22 23 42" src="https://user-images.githubusercontent.com/103935978/180055075-6822e8eb-e7a6-423b-beae-ea51c6891c2f.png">

This is the warn message:
Line 22:16: 'setData' is assigned a value but never used no-unused-vars
Line 35:15: 'object' is assigned a value but never used no-unused-vars

**This the App.js code:**

<img width="761" alt="Capture d’écran 2022-07-20 à 22 09 36" src="https://user-images.githubusercontent.com/103935978/180053591-d4412151-2ff0-43c9-9af5-95595bc350cf.png">

<img width="692" alt="Capture d’écran 2022-07-20 à 22 10 34" src="https://user-images.githubusercontent.com/103935978/180053654-ba8cf2e9-18fc-4219-8fad-4707e47a23a1.png">

<img width="900" alt="Capture d’écran 2022-07-20 à 22 10 57" src="https://user-images.githubusercontent.com/103935978/180053679-e2b9efb3-13eb-4544-bdf7-82b4d538019a.png">

**Contract code:**

<img width="717" alt="Capture d’écran 2022-07-20 à 22 11 39" src="https://user-images.githubusercontent.com/103935978/180053992-ec22bdad-6838-42c7-bfb9-1b8f150156be.png">

<img width="662" alt="Capture d’écran 2022-07-20 à 22 13 50" src="https://user-images.githubusercontent.com/103935978/180054037-b89c12b3-fd6e-45bb-981b-b677a930043e.png">

<img width="662" alt="Capture d’écran 2022-07-20 à 22 14 39" src="https://user-images.githubusercontent.com/103935978/180054072-e4b0cce6-0291-4888-b24b-5842aca338be.png">

Thanks for reading and your time
Hope you will be able to help me (And I'm in the good category) ;)

**Comment by fvictorio** [comment]
Hi @mvwmotor, the "'setData' is assigned a value but never used no-unused-vars" is a linter warning. It might be a hint about your issue, or it could be not.

Anyway, we can't help you with this since it seems to be a problem with your frontend, probably unrelated to Hardhat.
