### ISSUE TITLE
Failed to generate stack traces.

### ISSUE THREAD

**Issue by wisdant** [NomicFoundation/hardhat#2986]
This issue is the same as https://github.com/NomicFoundation/hardhat/issues/1874. Since that one was closed for a lack of detail, I am starting a new one. 

After a recent change, I start to get "Failed to generate x stack traces. Run Hardhat with --verbose to learn more" when I run my test. I have captured the relevant error message in this [google doc](https://docs.google.com/document/d/1Ot8FDZb9Ymx2c-RSHCXDwp_pJV5y65kFv2K-cK06e_s/edit): 

I know what changes had left to this error. I can reliably reproduce it, but have not got chance to produce a public environment to reproduce. If someone wants to look into this, happy to give you temp access to our private repo.

**Comment by fvictorio** [comment]
> If someone wants to look into this, happy to give you temp access to our private repo.

If you can do that, and tell me how to reproduce it with that repo, that would be great.

I don't think I'll be able to take a look this week, but I can probably do it next neew.

**Comment by fvictorio** [comment]
@wisdant any chance of sharing your repo?

**Comment by fvictorio** [comment]
Closing this for lack of reproduction steps.
