### ISSUE TITLE
Error HH307: Missing positional argument script

### ISSUE THREAD

**Issue by christopher-cialone** [NomicFoundation/hardhat#2990]

**Comment by Quanhua-Guan** [comment]
any workaround? bump into this problem, too.

**Comment by Quanhua-Guan** [comment]
https://github.com/scaffold-eth/scaffold-eth/issues/701#issuecomment-1202057194
Here is the solution for me, hope it helps.

**Comment by fvictorio** [comment]
If someone runs into this: the problem is likely that you are doing `npx hardhat run` without specifying a path to a script file. You have to do something like `npx hardhat run scripts/my-script.js`.

This error is not great though. I will create a new issue to improve it.

**Comment by diegomunozme** [comment]
> If someone runs into this: the problem is likely that you are doing `npx hardhat run` without specifying a path to a script file. You have to do something like `npx hardhat run scripts/my-script.js`.
> 
> This error is not great though. I will create a new issue to improve it.

"You have to do something like **npx hardhat run scripts/my-script.js**." 
This worked for me. Adding my deploy scripts
