### ISSUE TITLE
How do I add all the old features of hardhat-waffle `npx hardhat create

### ISSUE THREAD

**Issue by Andriy-Kulak** [NomicFoundation/hardhat#2994]
I noticed that when I run `npx hardhat create`, `@nomicfoundation/hardhat-toolbox` is installed with a typescript project. But you removed many amazing features that made the old configuration great.

For instance, how do I add the following in an easy way?
- eslint configs
- automatic solidity formatting with prettier
- solhint configuration

Is there hardhat config that helps set this up? It can take hours to figure out how to make prettier work with eslint so it would save programmers valuable time.

**Comment by fvictorio** [comment]
Hi @Andriy-Kulak. This is a good point, especially considering how hard it's to configure eslint with typescript. We are going to create a GitHub template repo for this. I can't promise a date, but we'll let you know here when it's ready.

**Comment by fvictorio** [comment]
Closing in favor of #3472.
