### ISSUE TITLE
Add flag to ignore unknown EIP-2718 types when forking

### ISSUE THREAD

**Issue by gzeoneth** [NomicFoundation/hardhat#2995]
> Note to reader: hardhat published a beta to fix this https://github.com/NomicFoundation/hardhat/issues/2995#issuecomment-1288811331

Certain EVM blockchain (e.g. Arbitrum Nitro) have non-standard [EIP-2718](https://eips.ethereum.org/EIPS/eip-2718) typed transaction that would prevent hardhat fork from working due to [Error HH604: Error running JSON-RPC server: Unknown transaction type 106](https://github.com/NomicFoundation/hardhat/blob/db1bbcea3c9113f1b9aa2873a1e865c22739384b/packages/hardhat-core/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts#L298-L300)

While it is rarely a good idea to use hardhat fork with these blockchain due to chain specific behavior and precompiles as discussed in https://github.com/NomicFoundation/hardhat/issues/1902, some devs found it helpful to test non-chain specific logic with existing states using hardhat fork. To workaround the `Unknown transaction type` error, I am proposing to add an optional `--fork-ignore-unknown-tx-type` flag to skip those transactions. 

You can reproduce the error with
```
hardhat node --fork https://goerli-rollup.arbitrum.io/rpc
```

* Arbitrum Nitro specific EIP-2718 types
https://github.com/OffchainLabs/go-ethereum/blob/141b0fcdf0e4d8e9e5de3f0466533b86563f2d29/core/types/transaction.go#L48-L54
```solidity
	ArbitrumDepositTxType         = 100
	ArbitrumUnsignedTxType        = 101
	ArbitrumContractTxType        = 102
	ArbitrumRetryTxType           = 104
	ArbitrumSubmitRetryableTxType = 105
	ArbitrumInternalTxType        = 106
	ArbitrumLegacyTxType          = 120
```

Here is a draft implementation: https://github.com/gzeoneth/hardhat/tree/2.10.2-gzeon

```
$ git clone --branch 2.10.2-gzeon https://github.com/gzeoneth/hardhat.git
$ cd hardhat
$ yarn install
$ yarn build
$ touch hardhat.config.js
$ yarn hardhat node --fork https://rinkeby.arbitrum.io/rpc --fork-ignore-unknown-tx-type true
```

Also published on npm and can be installed with yarn alias
```
$ yarn add -D hardhat@npm:@gzeoneth/hardhat@2.10.2-gzeon-e972f1dda
$ yarn hardhat node --fork https://rinkeby.arbitrum.io/rpc --fork-ignore-unknown-tx-type true
```

27/8/2022:
I have upload a patch file here if you don't want to install my package, this is also compatible with a few more hardhat version e.g. 2.9.9, 2.10.2
https://gist.github.com/gzeoneth/99ac30932bf07f91661d7bc621ba1f50

You can install it using [patch-package](https://www.npmjs.com/package/patch-package), just follow the step there and put [hardhat+2.10.2.patch](https://gist.github.com/gzeoneth/99ac30932bf07f91661d7bc621ba1f50) into the `patches` folder and run `yarn install` again. Please note that I did not update the source mapping in this patch file to improve compatibility but it might cause some issue debugging.

10/9/2022:
Fixed a few bug with `2.10.2-gzeon-e972f1dda`, updated link above

24/10/2022: https://github.com/NomicFoundation/hardhat/issues/2995#issuecomment-1288811331
A beta version of Hardhat is published that should fix this issue.
```
npm install hardhat@unknown-txs
```
(If you are using npm 7 or later, you might get some warnings about unsatisfied peer dependencies, but you can ignore those.)

**Comment by gzeoneth** [comment]
Hey @feuGeneA any opinion on this? Can I move on to create a PR if this approach is ok?

**Comment by feuGeneA** [comment]
Hi @gzeoneth . Thank you for the thoughtful and complete submission. I've just solicited more input from the team. We'll follow up soon.

**Comment by lzalvin** [comment]
Would really like to be able to fork chains like arbitrum with the introduction of arbitrum nitro.

**Comment by feuGeneA** [comment]
This issue has been added to our internal backlog. I can't say when we'll be able to prioritize it. But I can say that the more interest is shown here, the more likely we are to work on it sooner rather than later :)

**Comment by rafinskipg** [comment]
Hey, i assumed it was supported to fork arbitrum rinkeby for testing... I am surprised it does not work :( (i based my entire work on this working)

**Comment by gzeoneth** [comment]
> Hey, i assumed it was supported to fork arbitrum rinkeby for testing... I am surprised it does not work :( (i based my entire work on this working)

just fyi you can use this as a workaround for now
```
$ yarn add -D hardhat@npm:@gzeoneth/hardhat@2.10.1-gzeon-c8fe47dd4
$ yarn hardhat node --fork https://rinkeby.arbitrum.io/rpc --fork-ignore-unknown-tx-type true
```

**Comment by N00000b** [comment]
Yes I also need this. I am trying to test on a fork of Wanchain and am having the same issue. Thanks!

**Comment by lzalvin** [comment]
looks great. works with hardhat_reset.
```
await hre.network.provider.request({
                method: 'hardhat_reset',
                params: [
                    {
                        forking: {
                            jsonRpcUrl: rpc,
                            enabled: true,
                            ignoreUnknownTxType: true,
                        },
                    },
                ],
            })
```

**Comment by gzeoneth** [comment]
I have upload a patch file here if you don't want to install my package, this is also compatible with a few more hardhat version e.g. `2.9.9`, `2.10.2`
https://gist.github.com/gzeoneth/195cb16f00eaa32fa868e6c0192616c1

You can install it using [patch-package](https://www.npmjs.com/package/patch-package#why-use-postinstall-postinstall-with-yarn), just follow the step there and put [hardhat+2.10.1.patch](https://gist.githubusercontent.com/gzeoneth/195cb16f00eaa32fa868e6c0192616c1/raw/21e12b42e31675eefa2d05deb2e8b9d6157b3ec1/hardhat+2.10.1.patch) into a `patches` folder and run `yarn install` again

**Comment by tom-s07** [comment]
This is absolutely needed, Arbitrum is starting to be one of the most active networks after Ethereum Mainnet. Thanks @gzeoneth for providing an interim solution, will give it a try!

**Comment by xcellsior** [comment]
Definitely a needed change.

**Comment by ryandgoulding** [comment]
Patch works for me.  Any update on this making it into an official release?

**Comment by 0xyqrz** [comment]
> This issue has been added to our internal backlog. I can't say when we'll be able to prioritize it. But I can say that the more interest is shown here, the more likely we are to work on it sooner rather than later :)

> interest is shown

**Comment by Zalexios** [comment]
My infura and quicknodes Arbitrum mainnet RPC's stopped forking on Friday with this issue. I'm going to try the patch now, just showing interest @0xyqrz. Thanks everyone.

**Comment by Preston-Harrison** [comment]
> > Hey, i assumed it was supported to fork arbitrum rinkeby for testing... I am surprised it does not work :( (i based my entire work on this working)
> 
> just fyi you can use this as a workaround for now
> 
> ```
> $ yarn add -D hardhat@npm:@gzeoneth/hardhat@2.10.1-gzeon-c8fe47dd4
> $ yarn hardhat node --fork https://rinkeby.arbitrum.io/rpc --fork-ignore-unknown-tx-type true
> ```

How can this be used with hardhat tests?

**Comment by gzeoneth** [comment]
> > > Hey, i assumed it was supported to fork arbitrum rinkeby for testing... I am surprised it does not work :( (i based my entire work on this working)
> > 
> > 
> > just fyi you can use this as a workaround for now
> > ```
> > $ yarn add -D hardhat@npm:@gzeoneth/hardhat@2.10.1-gzeon-c8fe47dd4
> > $ yarn hardhat node --fork https://rinkeby.arbitrum.io/rpc --fork-ignore-unknown-tx-type true
> > ```
> 
> How can this be used with hardhat tests?

see the first post you can use my patched hardhat or apply the patch file

**Comment by jacques-martin10** [comment]
@feuGeneA :+1: interest. thanks!

**Comment by 0xchoripan** [comment]
The patch is not working for me when using `hardhat_reset` like this
```
  await network.provider.request({
    method: "hardhat_reset",
    params: [
      {
        forking: {
          jsonRpcUrl: config.networks.hardhat.forking.url,
          blockNumber,
          ignoreUnknownTxType: true,
        },
      },
    ],
  });
```
Before applying the patch
```
InternalError: Unknown transaction type 106
```
After applying the patch + adding `ignoreUnknownTxType: true` to `hardhat_reset`
```
InternalError: Unknown transaction type 106, set --fork-ignore-unknown-tx-type true to ignore
```
Using hardhat `2.10.1`

**Comment by gzeoneth** [comment]
> await network.provider.request({
>     method: "hardhat_reset",
>     params: [
>       {
>         forking: {
>           jsonRpcUrl: config.networks.hardhat.forking.url,
>           blockNumber,
>           ignoreUnknownTxType: true,
>         },
>       },
>     ],
>   });

Working fine with me 

> Unknown transaction type 106, set --fork-ignore-unknown-tx-type true to ignore

working fine with me, do you have a sample script?

**Comment by AbigailTCameron** [comment]
> ```
>   await network.provider.request({
>     method: "hardhat_reset",
>     params: [
>       {
>         forking: {
>           jsonRpcUrl: "https://rinkeby.arbitrum.io/rpc",
>           blockNumber: 15216420,
>           ignoreUnknownTxType: true,
>         },
>       },
>     ],
>   });
> ```
> 


where exactly are we supposed to add this aforementioned file if trying to run hardhat tests?

Since the Arbitrum nitro upgrade I have installed the patch, as well as followed the steps laid out above but keep getting an ` InternalError: Unknown transaction type 106, set --fork-ignore-unknown-tx-type true to ignore` error.

**Comment by gzeoneth** [comment]
> > ```
> >   await network.provider.request({
> >     method: "hardhat_reset",
> >     params: [
> >       {
> >         forking: {
> >           jsonRpcUrl: "https://rinkeby.arbitrum.io/rpc",
> >           blockNumber: 15216420,
> >           ignoreUnknownTxType: true,
> >         },
> >       },
> >     ],
> >   });
> > ```
> 
> where exactly are we supposed to add this aforementioned file if trying to run hardhat tests?
> 
> Since the Arbitrum nitro upgrade I have installed the patch, as well as followed the steps laid out above but keep getting an ` InternalError: Unknown transaction type 106, set --fork-ignore-unknown-tx-type true to ignore` error.

I have no idea why it is not working, you can try [this alternative patch](https://gist.github.com/gzeoneth/54e9eaee0a3f1e0f7a60deb2db90220b) where it always ignore unknown tx type.

**Comment by AbigailTCameron** [comment]
> ```
>   await network.provider.request({
>     method: "hardhat_reset",
>     params: [
>       {
>         forking: {
>           jsonRpcUrl: "https://rinkeby.arbitrum.io/rpc",
>           blockNumber: 15216420,
>           ignoreUnknownTxType: true,
>         },
>       },
>     ],
>   });
> ```
but which file are we adding the above stipulation to?

**Comment by gzeoneth** [comment]
> > ```
> >   await network.provider.request({
> >     method: "hardhat_reset",
> >     params: [
> >       {
> >         forking: {
> >           jsonRpcUrl: "https://rinkeby.arbitrum.io/rpc",
> >           blockNumber: 15216420,
> >           ignoreUnknownTxType: true,
> >         },
> >       },
> >     ],
> >   });
> > ```
> 
> but which file are we adding the above stipulation to?

Fixed a few bug with 2.10.2-gzeon-e972f1dda, you can use this patch file
https://gist.github.com/gzeoneth/99ac30932bf07f91661d7bc621ba1f50

In hardhat.confg.ts you need something like
```
  networks: {
    hardhat: {
      forking: {
        url: "https://rinkeby.arbitrum.io/rpc",
        ignoreUnknownTxType: true
      }
    }
  },
```

Then it should work when using the hardhat network.

**Comment by adichess** [comment]
> 

Thank you so much this latest patch finally works.

**Comment by kjmagill** [comment]
> > > ```
> > >   await network.provider.request({
> > >     method: "hardhat_reset",
> > >     params: [
> > >       {
> > >         forking: {
> > >           jsonRpcUrl: "https://rinkeby.arbitrum.io/rpc",
> > >           blockNumber: 15216420,
> > >           ignoreUnknownTxType: true,
> > >         },
> > >       },
> > >     ],
> > >   });
> > > ```
> > 
> > 
> > where exactly are we supposed to add this aforementioned file if trying to run hardhat tests?
> > Since the Arbitrum nitro upgrade I have installed the patch, as well as followed the steps laid out above but keep getting an ` InternalError: Unknown transaction type 106, set --fork-ignore-unknown-tx-type true to ignore` error.
> 
> I have no idea why it is not working, you can try [this alternative patch](https://gist.github.com/gzeoneth/54e9eaee0a3f1e0f7a60deb2db90220b) where it always ignore unknown tx type.

Could you share your Hardhat config file? I've installed this alternative patch in your latest reply, which helped me bypass the same `InternalError: Unknown transaction type 106` as Abbie is experiencing above. This patch has successfully ignored the unknown type 106 error, but now we're getting `Error HH604: Error running JSON-RPC server: Invalid URL` and I'm assuming it's a configuration issue. We're currently using the following URL for Hardhat forking: https://rinkeby.arbitrum.io/rpc

**Comment by gzeoneth** [comment]
> > > > ```
> 
> > > >   await network.provider.request({
> 
> > > >     method: "hardhat_reset",
> 
> > > >     params: [
> 
> > > >       {
> 
> > > >         forking: {
> 
> > > >           jsonRpcUrl: "https://rinkeby.arbitrum.io/rpc",
> 
> > > >           blockNumber: 15216420,
> 
> > > >           ignoreUnknownTxType: true,
> 
> > > >         },
> 
> > > >       },
> 
> > > >     ],
> 
> > > >   });
> 
> > > > ```
> 
> > > 
> 
> > > 
> 
> > > where exactly are we supposed to add this aforementioned file if trying to run hardhat tests?
> 
> > > Since the Arbitrum nitro upgrade I have installed the patch, as well as followed the steps laid out above but keep getting an ` InternalError: Unknown transaction type 106, set --fork-ignore-unknown-tx-type true to ignore` error.
> 
> > 
> 
> > I have no idea why it is not working, you can try [this alternative patch](https://gist.github.com/gzeoneth/54e9eaee0a3f1e0f7a60deb2db90220b) where it always ignore unknown tx type.
> 
> 
> 
> Could you share your Hardhat config file? I've installed this alternative patch in your latest reply, which helped me bypass the same `InternalError: Unknown transaction type 106` as Abbie is experiencing above. This patch has successfully ignored the unknown type 106 error, but now we're getting `Error HH604: Error running JSON-RPC server: Invalid URL` and I'm assuming it's a configuration issue. We're currently using the following URL for Hardhat forking: https://rinkeby.arbitrum.io/rpc

See my previous reply.

**Comment by penandlim** [comment]
https://gist.github.com/penandlim/790cebc4ddf204410654624aacb2efb4

Same patch as the one posted in the OP but for hardhat 2.11.1 code

**Comment by gzeoneth** [comment]
> https://gist.github.com/penandlim/790cebc4ddf204410654624aacb2efb4
> 
> 
> 
> I tried to forked the patch posted by @gzeoneth and update it for hardhat 2.11.1 code
> 
> Seemed to work for me.

Nice, ya there was a breaking change in 2.11.1

**Comment by arcpinus** [comment]
```
        await provider.request({
            method: "hardhat_reset",
            params: [
                {
                    forking: {
                        jsonRpcUrl: forkUrl,
                        blockNumber: forkBlockNumber,
                        ignoreUnknownTxType: true,
                    },
                },
            ],
        });
```
i've set to true always, but fails with `Error HH604: Error running JSON-RPC server: Unknown transaction type 106, set --fork-ignore-unknown-tx-type true to ignore`

**Comment by gzeoneth** [comment]
@arcpinus can you try my 2.10.2 patch?

**Comment by arcpinus** [comment]
> @arcpinus can you try my 2.10.2 patch?

@gzeoneth , it's not working :( 
```
$ yarn hardhat node --fork https://rinkeby.arbitrum.io/rpc --fork-ignore-unknown-tx-type true

yarn run v1.22.19
$ /home/ubuntu/Work/test/node_modules/.bin/hardhat node --fork https://rinkeby.arbitrum.io/rpc --fork-ignore-unknown-tx-type true
hardhat_reset

  Unknown transaction type 106, set --fork-ignore-unknown-tx-type true to ignore

Error HH604: Error running JSON-RPC server: Unknown transaction type 106, set --fork-ignore-unknown-tx-type true to ignore

For more info go to https://hardhat.org/HH604 or run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by zbirenbaum** [comment]
None of the linked patches work when trying to set                    `ignoreUnknownTxType: true,` from within hardhat.config, and most of them don't seem to work for me even when passing the cli parameters as was the case for others here. 

This issue has caused me no shortage of headaches and has been really frustrating for my team. I hope this gets resolved soon, but in the meantime, for anyone desperate to get this working and sick of patches breaking, inside of
`node_modules/hardhat/internal/hardhat-network/provider/fork/ForkBlockchain.js` 

change: 
```
class ForkBlockchain extends BlockchainBase_1.BlockchainBase {
    constructor(_jsonRpcClient, _forkBlockNumber, common, _forkIgnoreUnknownTxType) {
        super(common);
        this._jsonRpcClient = _jsonRpcClient;
        this._forkBlockNumber = _forkBlockNumber;
        this._forkIgnoreUnknownTxType = _forkIgnoreUnknownTxType;
        this._latestBlockNumber = this._forkBlockNumber;
    }
```
to:
```
class ForkBlockchain extends BlockchainBase_1.BlockchainBase {
    constructor(_jsonRpcClient, _forkBlockNumber, common, _forkIgnoreUnknownTxType) {
        super(common);
        this._jsonRpcClient = _jsonRpcClient;
        this._forkBlockNumber = _forkBlockNumber;
        this._forkIgnoreUnknownTxType = true;
        this._latestBlockNumber = this._forkBlockNumber;
    }
```

If you want to have a copy that is persistent across compilations so you can fork this repo and have it, just change `node_modules/hardhat/src/internal/hardhat-network/provider/fork/ForkBlockchain.ts` instead and recompile. Putting `this._forkIgnoreUnknownTxType = true;`  will probably suffice.

To give some info that might help with a real solution: Its a bit of a pain to debug, but by the time `node_modules/hardhat/internal/hardhat-network/provider/fork/ForkBlockchain.js` is reachedthe network configuration has completely discarded the field. Printing the value of the network config at multiple points in the callstack shows that the field is discarded even after going in and manually setting it across numerous files within the callstack. I have no idea what possible reason there could be for this, but whoever wants to PR this definitely has their work cut out for them. The fact that the docs don't mention that major chains like arbitrum can't be forked properly (on the contrary they make it sound like anything with an infura node works fine) is an absolute joke and wasted a whole week of my time before finding this issue.

**Comment by gzeoneth** [comment]
@zbirenbaum mind to share your setup / repo that's not working with the above patches? Myself and a few others have been able to use it with hardhat.config but since I am not that familiar with hardhat I probably have missed something. It seems that hardhat will initialize the fork with the config but then do another hardhat_reset to change the blocknumber, but it won't have the ignore flag set, so I have to fix it by removing the ability to change the ignore flag using hardhat_reset https://github.com/gzeoneth/hardhat/commit/e972f1ddabf695c4475b7fc44ed459c3a5c2c2e0, but it might have caused issue in other codepath.

Also @feuGeneA I think there are enough interest is shown here, when can we get a proper fix?

**Comment by zbirenbaum** [comment]
> @zbirenbaum mind to share your setup / repo that's not working with the above patches? Myself and a few others have been able to use it with hardhat.config but since I am not that familiar with hardhat I probably have missed something. It seems that hardhat will initialize the fork with the config but then do another hardhat_reset to change the blocknumber, but it won't have the ignore flag set, so I have to fix it by removing the ability to change the ignore flag using hardhat_reset [gzeoneth@e972f1d](https://github.com/gzeoneth/hardhat/commit/e972f1ddabf695c4475b7fc44ed459c3a5c2c2e0), but it might have caused issue in other codepath.
> 
> Also @feuGeneA I think there are enough interest is shown here, when can we get a proper fix?

I'll make a proper patch file tomorrow, it's late here rn

**Comment by fvictorio** [comment]
> @zbirenbaum mind to share your setup / repo that's not working with the above patches? Myself and a few others have been able to use it with hardhat.config but since I am not that familiar with hardhat I probably have missed something. It seems that hardhat will initialize the fork with the config but then do another hardhat_reset to change the blocknumber, but it won't have the ignore flag set, so I have to fix it by removing the ability to change the ignore flag using hardhat_reset [gzeoneth@e972f1d](https://github.com/gzeoneth/hardhat/commit/e972f1ddabf695c4475b7fc44ed459c3a5c2c2e0), but it might have caused issue in other codepath.
> 
> Also @feuGeneA I think there are enough interest is shown here, when can we get a proper fix?

We'll definitely prioritize this. Sorry everyone for not responding sooner!

Since a lot of you are struggling with this, maybe we can publish a `dev` version with _some_ fix to be used in the meantime, until we can be confident we have a proper solution to release as a stable version. I'll let you all know when/if we do that.

**Comment by hugoroussel** [comment]
Any news on this? The patches do not work for me :(

**Comment by zbirenbaum** [comment]
With the 2.11.2 patch, and most of the others I believe, if you have 
```
  networks: {
    hardhat: {
      forking: {
        url: "https://rinkeby.arbitrum.io/rpc",
        ignoreUnknownTxType: true
      }
    }
  },
```
defined in your hardhat config, `npx hardhat node --fork-ignore-unknown-tx-type true` will fail, but if it is not defined, the command will work. Regardless, any attempt to set the flag from your hardhat config will fail.

**Comment by QuiNoah00** [comment]
`**ERROR** Failed to apply patch for package hardhat at path
  
    node_modules/hardhat

  This error was caused because hardhat has changed since you
  made the patch file for it. This introduced conflicts with your patch,
  just like a merge conflict in Git when separate incompatible changes are
  made to the same piece of code.

  Maybe this means your patch file is no longer necessary, in which case
  hooray! Just delete it!

  Otherwise, you need to generate a new patch file.

  To generate a new one, just repeat the steps you made to generate the first
  one.

  i.e. manually make the appropriate file changes, then run 

    patch-package hardhat

  Info:
    Patch file: patches/hardhat+2.10.2.patch
    Patch was made for version: 2.10.2
    Installed version: 2.11.2

---
patch-package finished with 1 error(s).`

Getting this kind of error right now. It worked fine few hours ago. What should I do?

**Comment by gzeoneth** [comment]
@QuiNoah00 you don't need the patch if you are installing my npm package

**Comment by zbirenbaum** [comment]
For anyone still struggling with this, I found a way to set up your project with the 2.11.2 patch here so that every time you run `npx hardhat node` it will automatically set up the network correctly for you, without having to worry about cli args or anything. You will need to create a .env file that contains the line
`export `INFURA_API_KEY='<you-api-key>'` in the root of your project, or just change the `jsonRpcUrl` const to whatever rpc you use.

Just drop this in your hardhat.config, change it however you need to, and then run `npx hardhat run --network localhost <your-script-here>`
```
import '@nomicfoundation/hardhat-toolbox';
import { task } from "hardhat/config";
import { HardhatUserConfig } from 'hardhat/config';
import dotenv = require('dotenv');
dotenv.config();

import '@nomiclabs/hardhat-ethers'
import { TASK_NODE_SERVER_READY, } from "hardhat/builtin-tasks/task-names";
const INFURA_API_KEY = process.env.INFURA_API_KEY;
const jsonRpcUrl = `https://arbitrum-mainnet.infura.io/v3/${INFURA_API_KEY}`

const config: HardhatUserConfig = {
  defaultNetwork: "localhost",
  networks: {
    localhost: {
      forking: {
        url: jsonRpcUrl,
        enabled: true,
        ignoreUnknownTxType: true,
      }
    }
  },
  solidity: '0.8.9',
};

task(TASK_NODE_SERVER_READY).setAction(async (taskArgs, hre, runSuper) => {
  await hre.network.provider.request({
    method: 'hardhat_reset',
    params: [
      {
        forking: {
          jsonRpcUrl: jsonRpcUrl,
          enabled: true,
          ignoreUnknownTxType: true,
        },
      },
    ],
  })
  console.log('Set up forked network');
  runSuper(taskArgs);
});

export default config;
```

**Comment by b-pmcg** [comment]
any chance to get this working with `ignoreUnknownTxType: true` in the config?

**Comment by CodeLarkin** [comment]
> This issue has been added to our internal backlog. I can't say when we'll be able to prioritize it. But I can say that the more interest is shown here, the more likely we are to work on it sooner rather than later :)

@feuGeneA Quite a bit of continued interest in this good ser!

**Comment by CodeLarkin** [comment]
> any chance to get this working with `ignoreUnknownTxType: true` in the config?

I couldn't get it to work with the 2.11.2 patch file provided so I modified it to use `true` in a bunch of places instead of that cli arg. Basically I hardcoded it to true. I am not sure how to create a github gist link like the others here, but here is my patch file: https://github.com/CodeLarkin/hardhat-patch-arbitrum/blob/main/hardhat%2B2.11.2.patch

My `package.json` deps include the following (and other stuff too ofc)
```
    "hardhat": "2.11.2",
    "patch-package": "^6.4.7",
    "postinstall-postinstall": "^2.1.0",
```

and then i have the following in the scripts section:
```
  "scripts": {
    "postinstall": "patch-package",
...
```

**Comment by vonhathanh** [comment]
I'm testing smart contract on arbitrum now, this feature is really need to simulate test cases

**Comment by gzeoneth** [comment]
> I'm testing smart contract on arbitrum now, this feature is really needed to simulate test cases

Try to use the 2.10.2 patch in the original post.

**Comment by gzeoneth** [comment]
@fvictorio updates?

**Comment by fvictorio** [comment]
Hi everyone. We just published a beta version of Hardhat that should fix this issue. I would appreciate it if you can give it a try:

```
npm install hardhat@unknown-txs
```

(If you are using npm 7 or later, you might get some warnings about unsatisfied peer dependencies, but you can ignore those.)

If this seems to be working fine, we'll publish a stable version with this change as soon as possible.

Please try it out and let us know if it works (or doesn't!)

**Comment by b-pmcg** [comment]
ty @fvictorio! the beta is working for me, I'm able to fork the goerli arbitrum network successfully using the hardhat config. Will keep testing with this package and let you know if I run into issues.

**Comment by andy191x** [comment]
Nice job! The beta is working for me as well.

Installing the beta alone seems to hiccup on the `hardhat-toolbox` requirement, but I was able to workaround by installing the latest hardhat stable first, then `hardhat-toolbox`, then finally the beta. For example:

```
npm install hardhat
npx hardhat
# ... setup project with defaults
npm install hardhat@unknown-txs
```

**Comment by fvictorio** [comment]
@andy191x yes, that's an unfortunate side effect of the way npm 7+ handles peer dependencies combined with how semver handles prerelease versions :disappointed:

**Comment by sashaaldrick** [comment]
> Hi everyone. We just published a beta version of Hardhat that should fix this issue. I would appreciate it if you can give it a try:
> 
> ```
> npm install hardhat@unknown-txs
> ```
> 
> (If you are using npm 7 or later, you might get some warnings about unsatisfied peer dependencies, but you can ignore those.)
> 
> If this seems to be working fine, we'll publish a stable version with this change as soon as possible.
> 
> Please try it out and let us know if it works (or doesn't!)

Worked perfectly for me! Forking now works with Arbitrum Goerli as usual. Thanks so much @fvictorio 👍

**Comment by fvictorio** [comment]
This fix is now included in the [latest release](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.12.2).
