### ISSUE TITLE
Forked Hardhat running extremely slow.

### ISSUE THREAD

**Issue by madpower2000** [NomicFoundation/hardhat#3002]
I have deployed a contract with view function that collects some data from blockchain -  lets say, about 1000 internal contract calls and packs it into an array and returns it back into my script.
On the live Polygon network my script works just fine, but on the forked localhost network (I spin up a local node and fork Polygon from Alchemy) it starts to work extremely slow, even with raised timeout settings.
What can be the reason for such behaviour? 
I'm just not sure this is bug or feature...

**Comment by Whynot63** [comment]
Does this bug is resolved?
