### ISSUE TITLE
typescript error in hardhat/src/internal/lib/hardhat-lib.ts

### ISSUE THREAD

**Issue by guotie** [NomicFoundation/hardhat#3004]
FILE: hardhat/src/internal/lib/hardhat-lib.ts
```
Export assignment cannot be used when targeting ECMAScript modules. Consider using 'export default' or another module format instead.ts(1203)
```

**Comment by guotie** [comment]
typescript version: 4.7.4
hardhat: 2.10.1

**Comment by fvictorio** [comment]
Hi @guotie, we don't support ES modules yet, and probably won't until the next major version.

Does changing your `tsconfig.json` to use `"module": "commonjs"` fixes the issue, or do you need to use ES modules?

**Comment by guotie** [comment]
OK
