### ISSUE TITLE
How to run multiple hardhat node at the same time

### ISSUE THREAD

**Issue by behnammohammadkhani** [NomicFoundation/hardhat#3009]
How to run multiple hardhat nodes at the same time, in the case that I am trying to fork ethereum, polygon, and arbitrum at the same time.

Is it possible? o is there any way to handle this case?
Hardhat could not start two nodes at the same port.

**Comment by feuGeneA** [comment]
Thank you for using Hardhat. GitHub Issues are intended to be used only for known or suspected problems with Hardhat, or for feature requests.  For questions or other help, please use either [our Discord server](https://hardhat.org/discord) or [the GitHub Discussions feature](https://github.com/nomiclabs/hardhat/discussions/) instead.

Two applications (even two instances of the same application) cannot run on the same port on the same system. At first glance you might consider having two separate network sections in your config, with different ports, and start each instance of Hardhat Node with `--network`. If you need more help, please reach out through Discussions or Discord.
