### ISSUE TITLE
unable to test function with multiple return values

### ISSUE THREAD

**Issue by fibo** [NomicFoundation/hardhat#3013]
I am new to Solidity and HardHat, so maybe this issue is due to my lack of experience but I could not find a solution to this in the documentation.

With Node.JS `v18.6.0` and `@nomicfoundation/hardhat-toolbox` package `v1.0.2`

I created a simple **solidity function that returns two values** and a simple test. 

Given contract *contracts/MyContract.sol*

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;

contract MyContract {
    function foo (uint8 n) public pure returns (uint8, uint8) {
        return (n, n);
    }
}
```

and *test/MyContract.ts*

```ts
import { loadFixture } from "@nomicfoundation/hardhat-network-helpers";
import { expect } from "chai";
import { ethers } from "hardhat";

describe("MyContract", function () {
  async function fixture() {
    const MyContract = await ethers.getContractFactory("MyContract");
    const contract = await MyContract.deploy();

    return { contract };
  }

  describe("foo", async function () {
    it("works", async function () {
      const { contract } = await loadFixture(fixture);
      expect(await contract.foo(1)).to.equal([1, 1]);
    });
  });
});

```

I get this error

```
AssertionError: expected [ 1, 1 ] to equal [ 1, 1 ]
```

<img width="712" alt="Screenshot 2022-08-04 at 20 55 44" src="https://user-images.githubusercontent.com/176730/182931403-8ff7f13d-6a93-4a5c-b1fd-6565f00bedb4.png">

**Comment by fvictorio** [comment]
Hy @fibo. In Mocha, when you want to compare things like arrays or objects, you have to use `.deep.equal`, because otherwise Mocha will just compare the values by reference.

I agree that we should mention this somewhere in the docs. Where do you think would be a good place to do it?

**Comment by fibo** [comment]
thanks @fvictorio I was looking for some `deepEqual` function using completion but I could not find it at first.

I do not know if it is worth to add it here https://hardhat.org/hardhat-runner/docs/guides/test-contracts
since it is a specific use case.

If you have some examples/ folder some where it could be an examples/testMultipleReturnFunction/

**Comment by fvictorio** [comment]
Thanks, those are good points.

> the equal function should not accept nested structures like arrays or objects

Hmm, there are some cases where you _do_ want to do the comparison-by-reference thing, so a PR changing that would probably be rejected.
