### ISSUE TITLE
Is it possible to set optimizer values for contracts individually?

### ISSUE THREAD

**Issue by migoldfinger** [NomicFoundation/hardhat#3020]
Is there any build in function where I can choose the optimizer settings based on contracts.
I have some very big contracts that need low runs values while others do not.

**Comment by fvictorio** [comment]
Hi @migoldfinger. You can do this with `overrides`. Check [this guide](https://hardhat.org/hardhat-runner/docs/advanced/multiple-solidity-versions) (even if you are not using multiple versions of solidity). Let me know if that works or if you need more help.

**Comment by migoldfinger** [comment]
@fvictorio Well...
Technically it is working and it is exactly the settings I was looking for.
Practically there are to many complex dependencies between my contracts with address precalculation and so on. That it is way to much effort to compile the contracts with different settings and get them to work together.
For short my Test shows as long as I compile everything with fore example runs: 100 all works fine.
But If I compile one contract with runs: 100 and the others with runs: 10000 the test failes....
