### ISSUE TITLE
Long list of security issues after installing hardhat-waffle

### ISSUE THREAD

**Issue by gionn** [NomicFoundation/hardhat#3035]
Hello,

after installing hardhat-waffle latest package as per [docs](https://hardhat.org/hardhat-runner/plugins/nomiclabs-hardhat-waffle):

```sh
npm install --save-dev @nomiclabs/hardhat-waffle 'ethereum-waffle@^3.0.0' @nomiclabs/hardhat-ethers 'ethers@^5.0.0'
```

I get 51 (!!) security vulnerability reports in npm:

```
npm WARN deprecated ganache-core@2.13.2: ganache-core is now ganache; visit https://trfl.io/g7 for details
npm WARN deprecated ganache-core@2.13.2: ganache-core is now ganache; visit https://trfl.io/g7 for details
npm WARN deprecated testrpc@0.0.1: testrpc has been renamed to ganache-cli, please use this package from now on.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @ensdomains/ens@0.4.5: Please use @ensdomains/ens-contracts
npm WARN deprecated @ensdomains/resolver@0.2.4: Please use @ensdomains/ens-contracts

added 1081 packages, and audited 1417 packages in 30s

120 packages are looking for funding
  run `npm fund` for details

51 vulnerabilities (11 moderate, 37 high, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

**Comment by fvictorio** [comment]
Hi @gionn, we recently released an alternative to `hardhat-waffle` that has way fewer dependencies. If you are interested, you can learn how to migrate [here](https://hardhat.org/hardhat-runner/docs/guides/migrating-from-hardhat-waffle).

Anyway, more generally, the result of `npm audit` tends to be misleading. You can read [this](https://overreacted.io/npm-audit-broken-by-design/) to learn why.

**Comment by gionn** [comment]
> Hi @gionn, we recently released an alternative to `hardhat-waffle` that has way fewer dependencies. If you are interested, you can learn how to migrate [here](https://hardhat.org/hardhat-runner/docs/guides/migrating-from-hardhat-waffle).

That looks cool, I will give a try, thanks for the pointer!
 
> Anyway, more generally, the result of `npm audit` tends to be misleading. You can read [this](https://overreacted.io/npm-audit-broken-by-design/) to learn why.

Thanks again, I am a casual npm user and I know that vulnerabilities has different impacts depending on where they are run, but I was more concerned that was a sign of an unmaintained project rather than a critical security risk (even that working on crypto projects made me A LOT more paranoid than before).
