### ISSUE TITLE
Install dependencies with pnpm seems not working

### ISSUE THREAD

**Issue by caoyifeng007** [NomicFoundation/hardhat#3037]
![image](https://user-images.githubusercontent.com/8067217/184453529-ee74e173-3190-4edb-8462-24166d30f656.png)

When I changed to npm install, this error won't comes out.

**Comment by fvictorio** [comment]
@caoyifeng007 are you talking about the project initialization with `npx hardhat`? In that case, that assumes you are using either npm or yarn.

But you should be able to use `pnpm` anyway. Check the instructions [here](https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-toolbox) and use the command for older versions of npm or yarn, replacing the command with `pnpm install --save-dev`.
