### ISSUE TITLE
Parser Error: Expected pragma... Receving this error in HH but not on Remix

### ISSUE THREAD

**Issue by JEflyer** [NomicFoundation/hardhat#3038]
I'm editing uniswap v2 to work with solidity 0.8.15.
The edited code shows no error in Remix on compile but on compile in Hardhat the error appears.

Error:
ParserError: Expected pragma, import directive or contract/interface/library/struct/enum/constant/function/error definition.

[FlatFactory.txt](https://github.com/NomicFoundation/hardhat/files/9332092/FlatFactory.txt)

Any help on this would be appreciated.

**Comment by fvictorio** [comment]
This file compiles fine for me in a Hardhat project (with `solidity: "0.8.15"` configured). Please comment if you can provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that triggers your issue and I'll re-open the issue.
