### ISSUE TITLE
what does the new '@nomicfoundation/hardhat-toolbox' do?

### ISSUE THREAD

**Issue by shinjiikari256** [NomicFoundation/hardhat#3041]
![image](https://user-images.githubusercontent.com/39000784/184629306-94c4248f-fbb1-4e6d-beac-a89285638fd1.png)

Does this mean that the new '@nomicfoundation/hardhat-toolbox' does not install these packages?
Why is it needed?

When hardhat proposed to install all the necessary dependencies during initialization, it was objectively better

**Comment by feuGeneA** [comment]
Thank you for using Hardhat. GitHub Issues are intended to be used only for known or suspected problems with Hardhat, or for feature requests.  For questions or other help, please use either [our Discord server](https://hardhat.org/discord) or [the GitHub Discussions feature](https://github.com/nomiclabs/hardhat/discussions/) instead.

To make an initial attempt to answer your question, I'll excerpt a few quotes from [the toolbox documentation](https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-toolbox#installation). 
If you feel that further discussion is warranted, please use the communication channels mentioned above.

"The @nomicfoundation/hardhat-toolbox plugin bundles all the commonly used packages and Hardhat plugins we recommend to start developing with Hardhat."

"We recommend using npm 7 or later. If you do that, then you just need to install the plugin itself. ... If you are using an older version of npm, you'll also need to install all the packages used by the toolbox. ... That's also the case if you are using yarn."

**Comment by shinjiikari256** [comment]
Oh, sorry, I found that it occurred when using hardhat with yarn.
But npm is too slow.
But the [bun](https://github.com/oven-sh/bun.git) seems to work fast and doesn't break anything.
