### ISSUE TITLE
Add support to deploying contracts on a submodule

### ISSUE THREAD

**Issue by OxMarco** [NomicFoundation/hardhat#3054]
I currently have a hardhat project with deployment and verification scripts and a submodule containing the contracts code and tests.
I'd like to deploy and verify such contracts with the _hardhat-etherscan_ plugin but I get the following error:
`Error in plugin @nomiclabs/hardhat-etherscan: The contract ../v1/contracts/mocks/MockERC20.sol: MockERC20 is not present in your project.`

Dir structure:

> /
> /hardhat.config.js
> /v1-core/
> /v1-core/contracts
> /v1-core/hardhat.config.js

I tried to add 
```
  paths: {
    artifacts: "./v1/artifacts",
    cache: "./v1/cache",
    sources: "./v1/contracts",
    tests: "./v1/test",
  },
```
  
  In the root hardhat config file but the plugin still tries to compile contracts locally and fails with the aforementioned error

**Comment by fvictorio** [comment]
> ```
>   paths: {
>     artifacts: "./v1/artifacts",
>     cache: "./v1/cache",
>     sources: "./v1/contracts",
>     tests: "./v1/test",
>   },
> ```

Is that correct? Before that you said that the directory is `v1-core`, not `v1`.

If you used the correct directory, then... I'm not sure. That should work IMO, but maybe having an inner Hardhat config is causing some issue. If that's the case, I think I would consider it a bug.

**Comment by OxMarco** [comment]
I tried without success, the plugin still complains about the project files being in a subfolder

**Comment by fvictorio** [comment]
Thanks. I'll add this to our backlog. To clarify, a minimal reproduction would be:

1. Create two hardhat projects with some contracts
2. Make one of those projects a submodule of the other
3. Try to change Hardhat's paths to use the submodule's contracts, and compile
4. This should work but it doesn't.

Can you confirm this?

**Comment by fvictorio** [comment]
Closing for lack of response.

**Comment by 0xKarl98** [comment]
Is this issue resolved yet , anywhere else ?
i have come into the same situation .
