### ISSUE TITLE
Verification failures

### ISSUE THREAD

**Issue by Archethect** [NomicFoundation/hardhat#3062]
Suddenly getting verification problems on both Arbitrum One and Arbitrum Rinkeby since 2 days.
Nothing changed on the code side and I immediately run the verification after deploy.

Error message I'm getting:

`
NomicLabsHardhatPluginError: The contract verification failed.
Reason: Fail - Unable to verify
`

**Comment by Enigmatic331** [comment]
Hey @Archethect - Could you try rerunning for Arbitrum One again please? One of our verification nodes for the API endpoint went down without notice, and am currently having it routed to a backup.

As for Arbitrum Rinkeby, all looks fine so far and I can see new contracts being verified via API. Perhaps you can share some details and I could help take a look.

Cheers.

**Comment by fvictorio** [comment]
Tentatively closing this. Please comment if you think it's still an issue.

**Comment by JoshDAO** [comment]
I am having this same error when verifying on Arbitrum One, using an almost identical deploy/verify script and the same Arbiscan API key as I have been using for Arbitrum Rinkeby that works fine.

```
NomicLabsHardhatPluginError: The contract verification failed.
Reason: Fail - Unable to verify
    at SimpleTaskDefinition.verifySubtask [as action] (/<xxx>/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:330:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Environment._runTaskDefinition (/<xxx>/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at async Environment.run (/<xxx>/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
 ```
 
 Not sure what could be causing the difference in behaviour between Arb Rinkeby and Arbitrum One
