### ISSUE TITLE
Hardhat refuse to include two transactions in one block even when possible

### ISSUE THREAD

**Issue by wuya666** [NomicFoundation/hardhat#3075]
Currently I need to test a use case where two transactions are mined in the same block, while I can make that happen with "real" networks like Ethereum testnets and such, the hardhat network somehow refuses to mine them in the same block which makes the test extremely tedious and harder to debug.

I use something like the following code

```
      let beforeBlock, afterBlock;
      let tasks;

      console.log("Block gas limit:", config.networks.hardhat.blockGasLimit);

      if (network.name === "hardhat") {
        await network.provider.send("evm_setAutomine", [false]);
        await network.provider.send("evm_setIntervalMining", [5000]);
      }

      beforeBlock = (await ethers.provider.getBlock("latest")).number;

      console.log("Before sending txs block:", beforeBlock);

      tasks = [];
      tasks.push(
        (await testContract.connect(user1).testMethod(1)).wait()
      );
      tasks.push(
        (await testContract.connect(user2).testMethod(2)).wait()
      );
      afterBlock = (await ethers.provider.getBlock("latest")).number;

      console.log("After sending txs block:", afterBlock);

      expect(beforeBlock).to.equal(
        afterBlock,
        "Block number should not change at this time"
      );

      const results = await Promise.allSettled(tasks);

      console.log("After mining txs block:", (await ethers.provider.getBlock("latest")).number);

      if (network.name === "hardhat") {
        await network.provider.send("evm_setAutomine", [
          config.networks.hardhat.mining.auto,
        ]);
        await network.provider.send("evm_setIntervalMining", [
          config.networks.hardhat.mining.interval,
        ]);
      }

      console.log( "Results:",
        results.map(
          ({
            value: {
              transactionHash,
              blockNumber,
              gasUsed,
              transactionIndex,
              status,
            },
          }) => ({
            transactionHash,
            blockNumber,
            gasUsed,
            transactionIndex,
            status,
          })
        )
      );
```

And the output is like this:

```
Block gas limit: 30000000
Before sending txs block: 205
After sending txs block: 205
After mining txs block: 207
Results: [
  {
    transactionHash: '0xf890d736fec520f902b8603f06613666158bf8f75bac6c7e0f72e46375ba7b26',
    blockNumber: 206,
    gasUsed: BigNumber { value: "1335713" },
    transactionIndex: 0,
    status: 1
  },
  {
    transactionHash: '0x2c77e963ef123ed1a1c829d65aff6af052b9cdf5d11e7dcbec6c1c1eeab2daa1',
    blockNumber: 207,
    gasUsed: BigNumber { value: "1239907" },
    transactionIndex: 0,
    status: 1
  }
]
```

As you can see, the configured block gas limit is shown to be 30M, while each transaction uses less than 1.5M gas, so the two transactions should be able to get mined within the same block, however hardhat network somehow cannot do that.

I also tried some cheaper transactions, something that uses less than 100K gas, and it seems that multiple transactions can be included in one block by hardhat alright. But at some point around 1M gas usage, the transactions will not be mined within the same block despite how high the block gas limit is configured.

So I wonder if this is a bug in the hardhat network, or there's some hidden configuration somewhere that sets some gas limit at around 1M that when gas usage in one block is over this limit, hardhat will always wait for a new block to include the next transaction (even when the current block gas limit is not reached yet)?

**Comment by vladyan18** [comment]
I ran into a similar issue. Transactions were not included in the block until I explicitly set a gasLimit for them

**Comment by feuGeneA** [comment]
This is expected behavior, because by default the gas limit for a transaction is very high. You can either specify a lower gas limit for the transaction, or you can configure the network to have `gas: auto`.
