### ISSUE TITLE
hardhat-chai-matchers - false positive for withArgs(array)

### ISSUE THREAD

**Issue by frontier159** [NomicFoundation/hardhat#3080]
The `withArgs` matcher on events incorrectly passes if the arg is an array of unequal size

eg in:
https://github.com/NomicFoundation/hardhat/blob/master/packages/hardhat-chai-matchers/test/events.ts#L317

I would expect this new test case to fail `[1,2] != [1]`:
```
        it("Should fail when expectations are not met - unequal array", async function () {
          await expect(contract.emitUintArray(1, 2))
              .to.emit(contract, "WithUintArray")
              .withArgs([1]);
        });
```
But it succeeds.

**Comment by frontier159** [comment]
Note: This case does fail:
```
        it("Should fail when expectations are not met - unequal array", async function () {
          await expect(contract.emitUintArray(1, 2))
              .to.emit(contract, "WithUintArray")
              .withArgs([1, 2, 3]);
````

So only an issue when the expected array size < actual array size

**Comment by feuGeneA** [comment]
This issue has been added to our internal backlog, meaning that we intend to work on it, but that it has not yet been scheduled.

**Comment by stevieraykatz** [comment]
Hi hi, I've run into this issue when writing tests for an event that returns a custom struct. This struct has a nested array. Upon assertion, the struct looks like an Array with a member that is an Array. Has someone found a way to work around this so that individual members can be tested while others are ignored? Or is there a way to explicitly trigger deepEquals on the `withArgs` call?

**Comment by fvictorio** [comment]
> Has someone found a way to work around this so that individual members can be tested while others are ignored?

You mean asserting that some arg of the event matches some value, and ignoring the other args? You can use the [`anyValue` predicate](https://hardhat.org/hardhat-chai-matchers/docs/reference#.withargs) for that. And if you need more control, you can write your own predicate.

**Comment by Oni-giri** [comment]
I can attest that this issue is still going on, a dev friend also mentioned it to me today. It's really a shame that deprecating Waffle meant a downgrade of Chai, both in reliability and in functionality.

**Comment by ryanio** [comment]
> This struct has a nested array. Upon assertion, the struct looks like an Array with a member that is an Array. Has someone found a way to work around this so that individual members can be tested while others are ignored? Or is there a way to explicitly assert using deepEquals on the `withArgs` call?

I'm also running into this:
```
      AssertionError: expected [] to equal []
      + expected - actual
```

Using like this:
```
.withArgs(owner.address, [[], 0, 0, 0, 0, 0, 0]);
```

**Comment by fvictorio** [comment]
Hi, I think #3832 will fix this. I published a dev version with that change. I'd appreciate it if you can give it a try and tell me if it solves the problem for you. Just run `npm i @nomicfoundation/hardhat-chai-matchers@dev` to install it.

@ryanio I suspect yours is a different problem. Can you open a new issue about it? Please include the definition of the event. I guess it's something like `Event(address, SomeStructThatStartsWithAnArray)`?

**Comment by ryanio** [comment]
@fvictorio happy to, just opened https://github.com/NomicFoundation/hardhat/issues/3833 with reproduction contract+test
