### ISSUE TITLE
abi.decode results in an error that HardHat cannot decode the reason for

### ISSUE THREAD

**Issue by aaronbuchwald** [NomicFoundation/hardhat#3084]
<img width="957" alt="Screen Shot 2022-08-26 at 18 59 42" src="https://user-images.githubusercontent.com/24684335/187000977-fb877c92-20f2-421d-8720-f28ce1740f0b.png">

Hey guys, I'm testing some error handling within HardHat and have found that the function `abi.decode(...)` has an unexpected behavior that results in an error message saying that I should report it to HardHat.

The code that's causing this is here:

```
(bool success, bytes memory data) = callee.call(abi.encodeWithSignature("performRevert(bool)", true));
.
.
.
// an error has occurred, so unpacking the error from the return data (still working on the correct way to do this)
(bytes4 functionSelector, string memory revertReason) = abi.decode(data, (bytes4, string));
```

Making this issue because the error reported said it was behavior worth mentioning. If you happen to know how to properly decode the revert error from a reverted call operation, I've been trying to figure this out for a little while and am not sure why this is incorrect, so would appreciate any advice there if you have an idea of how to properly extract the complete string from the return data.

My understanding is that the return data from a contract call in Solidity will be: `abi.encodePacked(functionSelector, errMsg)`, but am still struggling to decode this correctly.

**Comment by fvictorio** [comment]
Hi @aaronbuchwald, thanks for reporting this. We should be showing a better error in this case (assuming you have the optimizer disabled, can you confirm that's the case?)

With respect to your question:

> (bytes4 functionSelector, string memory revertReason) = abi.decode(data, (bytes4, string));

That won't work. Check [this comment](https://github.com/ethereum/solidity/issues/9439#issuecomment-660039240) for an explanation.

If `data` is `bytes calldata`, you can do this instead:

```solidity
string memory revertReason = abi.decode(data[:4], (string));
```

**Comment by fvictorio** [comment]
Yes, the defaults have the optimizer disabled. Thank you!

**Comment by fvictorio** [comment]
Closing in favor of https://github.com/NomicFoundation/hardhat/issues/3475.
