### ISSUE TITLE
on both the Linux and Mac hh doesn't seem to work... 

### ISSUE THREAD

**Issue by 0xYomari** [NomicFoundation/hardhat#3095]
OS: Linux 21.10 and Mac Monterey
command: yarn global add hardhat-shorthand

**Comment by feuGeneA** [comment]
Thank you for using Hardhat. GitHub Issues are intended to be used only for known or suspected problems with Hardhat, or for feature requests.  For questions or other help, please use either [our Discord server](https://hardhat.org/discord) or [the GitHub Discussions feature](https://github.com/nomiclabs/hardhat/discussions/) instead.

A quick googling turns this up: https://ethereum.stackexchange.com/questions/132148/hardhat-shorthand-is-not-working
Did you try using `npm` or `npx`?
