### ISSUE TITLE
I am having the following errors when running testing contracts with the --parallel option. It actually tries to re-acquire the lock on openzappelin manifest file and fails. I have no clue at all what to do!

### ISSUE THREAD

**Issue by DanyalKhawaja** [NomicFoundation/hardhat#3096]
I am having the following errors when testing contracts with the --parallel option. It actually tries to re-acquire the lock on openzappelin manifest file and fails. I have no clue at all what is happening!

![image](https://user-images.githubusercontent.com/42298472/187088395-530ec0b1-53db-4fab-b35c-c15a60abbb2b.png)
![image](https://user-images.githubusercontent.com/42298472/187088440-615a2fb1-4caf-44da-89a4-545485d27689.png)

_Originally posted by @DanyalKhawaja in https://github.com/NomicFoundation/hardhat/discussions/3093_

**Comment by fvictorio** [comment]
As explained [here](https://github.com/NomicFoundation/hardhat/discussions/3093#discussioncomment-3500732), at the moment parallel tests don't work well with OZ Upgrades. We'll be working with the OZ team to fix this.

**Comment by fvictorio** [comment]
Closing this because there's already an issue about this in the OZ Upgrades repo: https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/645
