### ISSUE TITLE
Add confirmations to deployed

### ISSUE THREAD

**Issue by GeraldHost** [NomicFoundation/hardhat#3102]
Currently to wait for a contract deployment in hardhat-ethers you do something like this:

```js
const contract = Contract.deploy();
await contract.deployed();
```

Underneath I imagine this `deployed` function calls `wait` which accepts an argument of number of confirmations. It would be nice if we could pass nConfirmations into `deployed` to be passed into `wait` to end up with something like:

```js
const contract = Contract.deploy();
// wait for 4 confirmations
await contract.deployed(4);
```

**Comment by alcuadrado** [comment]
Hey, thanks for reporting this. Note that it is an ethers API, so you should open the issue [here](https://github.com/ethers-io/ethers.js) instead.
