### ISSUE TITLE
No proper error message when encoding/decoding struct(tuple) with invalid enum 

### ISSUE THREAD

**Issue by ethereumdegen** [NomicFoundation/hardhat#3103]
If you pass an enum uint in a struct into a method in solidity and the uint is larger than the enum could possibly be (invalid enum input) then when you encode/decode that struct execution will revert and hardhat+ethers will not tell you why!

HOW TO REPLICATE:  

Create an enum
 MyEnum {
STATE_ZERO, STATE_ONE
}

Create a struct with that enum 
MyStruct{
MyEnum enum;
}

Create a method that inputs that struct 
 function foo(MStruct memory s) public {} 

Devise an invalid value tuple for the struct such as  [  ( 3 )  ]  where you are passing in the enum with an invalid number like 3   (valids are only 0 and 1 of course) 

Now if you pass in that invalid instance of that tuple to the method foo while it is configured as 'memory', it will revert but hardhat will NOT tell you the reason for the error ! it SHOULD tell you the reason like... 'malformed tuple' or cannot 'deserialize enum' .   

Even worse yet if you pass in an instance of that tuple to the method foo with it being 'calldata', it will NOT error until a point in your execution where the calldata tuple is serialized and deserialized such as being converted to memory.  When the execution environment (at runtime) tries to deserialize the data to memory it will fail as it cannot cast the number '3' to that enum since the only valid values for the enum are 0 or 1.  

I lost 16 hours of my life on this lack of an error message.

**Comment by fvictorio** [comment]
Hi @apexmfer, thanks for reporting this and sorry for not responding before.

For the record, I get this message:

> Error: Transaction reverted: function was called with incorrect parameters

Which is not ideal, but it points to the line number of the signature. Were you getting something worse than that?

Note for ourselves:

I wonder why this doesn't cause the correct panic code (`0x21 (Tried to convert a value into an enum, but the value was too big or negative)`). Maybe we are ignoring the panic code when we shouldn't? If not, this might be a thing that solc could improve. In both cases, it's worth looking into it.

**Comment by fvictorio** [comment]
Closing in favor of #13832.
