### ISSUE TITLE
Hardhat crashes when bit left shifting

### ISSUE THREAD

**Issue by cdgmachado0** [NomicFoundation/hardhat#3108]
Hardhat crashes with the error `Error: Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.` 100% of the times when attempting a left bit shift operation in this code: 
```js
function _toggleBit(uint bitmap_, uint index_) internal {
        s.bitLocks[bitmap_] ^= (1 << index_);
    }
```

If I put a `console.log` before the operation, it crashes around 30% of the times but it still crashes when it shouldn't:
```js
function _toggleBit(uint bitmap_, uint index_) internal {
        console.log(' ');
        s.bitLocks[bitmap_] ^= (1 << index_);
    }
```

Full error:
```
Error: Transaction reverted and Hardhat couldn't infer the reason. Please report this to help us improve Hardhat.
      at OZLFacet._toggleBit (contracts/arbitrum/Bits.sol:19)
      at OZLFacet.noReentrancy (contracts/Modifiers.sol:20)
      at OZLFacet.exchangeToUserToken (contracts/arbitrum/facets/OZLFacet.sol:42)
      at Diamond.<fallback> (contracts/arbitrum/Diamond.sol:71)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at HardhatNode._mineBlockWithPendingTxs (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1582:23)
      at HardhatNode.mineBlock (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:435:16)
      at EthModule._sendTransactionAndReturnHash (node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1494:18)
      at HardhatNetworkProvider.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:108:18)
      at EthersProviderWrapper.send (node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

All of `OZLFacet` methods and `Diamond` are mine. 

Sol v0.8.14

**Comment by fvictorio** [comment]
@cdgmachado0 can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)?

I tried this:

```solidity
contract Foo {
  uint public x = 1;

  function f(uint index) public {
    x = x << index;
  }
}
```

with values for index of 0, 1, 2, 100 and 1000 and they all worked.

**Comment by fvictorio** [comment]
I see, but without a way to reproduce it there's not much I can do, sorry.

If your repo is public, sharing it and the _minimal_ steps to reproduce it (for example, removing/skipping tests that are not relevant) would be enough.

If you can't share your repo, then what you can do is to start removing code until you have something simple enough that reproduces the problem and can be turned into an MRE. In fact, this would be even better than the whole project.

**Comment by sisco0** [comment]
I tried to reproduce the issue in the following repository without success. Even when using forked networks, the test fails.
Could you kindly help with a minimal reproducible example @cdgmachado0 ?
https://github.com/sisco0/hardhat-test-3108

**Comment by cdgmachado0** [comment]
If the test fails, you're reproducing the issue @sisco0 . The test is designed to pass (`test/arb-tests/ozel-index.js`) without the `console.log()`.

I'm not really sure -without any ts knowledge- how to build a minimal reproducible example since it's only one test that does 18 txs, and the bug can come in tx #4 or #11 or #14 or not come at all.

It's an on/off behavior that doesn't happen all the time, so I'm doubting of having a piece of code -from my end- that could always reproduce it. If you tried it out using my repo and the test succeeded (meaning, the issue wasn't thrown), try running it several times to see if you catch the doggy behavior.

I'm currently finishing up with the development of a part of the larger project. Once I finish it, I'll try to bring a minimum example.

**Comment by fvictorio** [comment]
I'm going to close this one for bookkeeping reasons. If someone can provide a reproduction example, I will re-open it.
