### ISSUE TITLE
Unable to connect to Localhost 8545

### ISSUE THREAD

**Issue by MuskaanMunu** [NomicFoundation/hardhat#3109]
I am using Metamask with Hardhat network and I have not been able to connect to the network. I keep getting the following message:-
![error4](https://user-images.githubusercontent.com/109667951/187678672-0c57e0dc-9962-4c61-b7bb-6d7c34600a61.png)
Can somebody please help?

**Comment by woojiq** [comment]
Do you have a hardhat node running when you try to connect?
If yes, try this [stackoverflow](https://ethereum.stackexchange.com/questions/94231/how-can-i-connect-a-local-hardhat-network-to-metamask).

**Comment by MuskaanMunu** [comment]
So, when I do that I get a reference error saying hhprivKey is not defined.

**Comment by MuskaanMunu** [comment]
Also, I had cross-checked and changed the chainId accordingly but the issue persisted.

**Comment by MuskaanMunu** [comment]
I cannot thus see any of the accounts with their private keys and I am using another wallet on metamask so I haven't imported any of the accounts. When I previously had this issue I imported a new account and was somehow able to connect to the node again.

**Comment by woojiq** [comment]
Share your _hardhat.config_ and _package.json_.

**Comment by MuskaanMunu** [comment]
**Hardhat.config** 

```
require("@nomiclabs/hardhat-waffle");

module.exports = {
  defaultNetwork: "hardhat",
  networks: {
    hardhat: {
      chainId: 31337,
      url: "http://node.a3b.io:8545",
      accounts: [hhprivKey]
    },
    mumbai: {
      chainId: 80001,
      url: "https://rpc-mumbai.matic.today",
      accounts: [ethprivKey]
    },
    polygon: {
      chainId: 137,
      url: "https://rpc-mainnet.maticvigil.com",
      accounts: [ethprivKey]
    },
    ethereum: {
      chainId: 1,
      url: "https://main-rpc.linkpool.io",
      accounts: [ethprivKey]
    },
    binance: {
      chainId: 57,
      url: "https://bscrpc.com",
      accounts: [ethprivKey]
    },
    bsctest: {
      chainId: 97,
      url: "https://data-seed-prebsc-1-s3.binance.org:8545",
      accounts: [ethprivKey]
    },
    kovan: {
      chainId: 42,
      url: "https://kovan.infura.io/v3/3cf2d8833a2143b795b7796087fff369",
      accounts: [ethprivKey]
    }
  },
  solidity: {
    version: "^0.8.4",
    settings: {
      optimizer: {
        enabled: true,
        runs: 200
      }
    }
  }
};

```


**Package.json** 

```
{
  "name": "mymarketplace",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@metamask/detect-provider": "^1.2.0",
    "@nextui-org/react": "^1.0.0-beta.9",
    "axios": "^0.27.2",
    "canvas-confetti": "^1.5.1",
    "ipfs-http-client": "^57.0.3",
    "next": "12.2.5",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-multi-carousel": "^2.8.2",
    "sf-font": "^1.0.0",
    "simple-crypto-js": "^3.0.1",
    "web3": "^1.7.5",
    "web3modal": "^1.9.8"
  },
  "devDependencies": {
    "@nomiclabs/hardhat-ethers": "^2.1.1",
    "@nomiclabs/hardhat-waffle": "^2.0.3",
    "@types/canvas-confetti": "^1.4.3",
    "@types/react": "^18.0.17",
    "chai": "^4.3.6",
    "eslint": "8.22.0",
    "eslint-config-next": "12.2.5",
    "ethereum-waffle": "^3.4.4",
    "ethers": "^5.7.0",
    "hardhat": "^2.10.2"
  }
}

```

**Comment by woojiq** [comment]
**First**, you can't have `url` property inside hardhat built-in network (inside others you can).
These are all property inside *hardhat built-in network*
``` ts
export interface HardhatNetworkConfig {
  chainId: number;
  from?: string;
  gas: "auto" | number;
  gasPrice: "auto" | number;
  gasMultiplier: number;
  initialBaseFeePerGas?: number;
  hardfork: string;
  mining: HardhatNetworkMiningConfig;
  accounts: HardhatNetworkAccountsConfig;
  blockGasLimit: number;
  minGasPrice: BN;
  throwOnTransactionFailures: boolean;
  throwOnCallFailures: boolean;
  allowUnlimitedContractSize: boolean;
  initialDate: string;
  loggingEnabled: boolean;
  forking?: HardhatNetworkForkingConfig;
  coinbase?: string;
  chains: HardhatNetworkChainsConfig;
}
```
So to add private key to your accounts you should have syntax like this:
``` ts
hardhat: {
	chainId: 31337,
	accounts: [
	{
		privateKey:
		    "0x56289e99c94b6912bfc12adc093c9b51124f0dc54ac7a766b2bc5ccf558d8027",
		balance: "100",
	},
	],
},
```

**Second**, save and run next command inside your terminal: `yarn hardhat node`(for yarn) or `npx hardhat node`(for npm).

**Third**, add this [custom ](https://support.chainstack.com/hc/en-us/articles/4408642503449-Using-MetaMask-with-a-Hardhat-node)network to metamask: 
![image](https://user-images.githubusercontent.com/97038258/187879793-18a1beff-085f-4ce0-a940-fa6a1beab2bf.png)

I hope this will help.

P.S. Im not hardhat dev, so maybe I'm wrong somewhere

**Comment by feuGeneA** [comment]
Thank you for using Hardhat. GitHub Issues are intended to be used only for known or suspected problems with Hardhat, or for feature requests.  For questions or other help, please use either [our Discord server](https://hardhat.org/discord) or [the GitHub Discussions feature](https://github.com/nomiclabs/hardhat/discussions/) instead.

**Comment by ygit1** [comment]
How do I connect hardhat to my own private geth chain?
