### ISSUE TITLE
[feature request] Add option: "Create new project with installing open-zeppeline"

### ISSUE THREAD

**Issue by JackBekket** [NomicFoundation/hardhat#3113]
I would like to see option to create a new js/ts project with installing open-zeppeline right away
` $ npm install @openzeppelin/contracts `

**Comment by fvictorio** [comment]
Do you mean a sample project that already has the OpenZeppelin contracts dependency? If that's what you mean, I don't think we'd do it. We are trying to keep the list of sample projects short, and adding one sample project just with an extra dependency wouldn't be very valuable.

**Comment by fvictorio** [comment]
Closing this assuming that that's what you meant.
