### ISSUE TITLE
Can we have full raw revert reason?

### ISSUE THREAD

**Issue by k06a** [NomicFoundation/hardhat#3115]
We have only selector now: https://github.com/NomicFoundation/hardhat/issues/2948

**Comment by alcuadrado** [comment]
Out of curiosity: Do you see clashes of error signatures that you can't debug just with that data?

Do you think this would be best in the error message or in an error field?

**Comment by k06a** [comment]
@alcuadrado we get different reverts from main net fork. Sometimes revert selector is not enough to understand what exactly was wrong.
