### ISSUE TITLE
hardhat test doesn't run any tests?

### ISSUE THREAD

**Issue by JimLynchCodes** [NomicFoundation/hardhat#3117]
Hi, when I point directly to my file with tests in it I get the output `0 passing`

```
const { ethers } = require("hardhat");
const { use, expect } = require("chai");
const { solidity } = require("ethereum-waffle");

use(solidity);

describe("APPLE", async function () {
  let apple;

  const [owner, user1, user2] = await ethers.getSigners();

  beforeEach(async () => {
    const AppleContract = await ethers.getContractFactory('APPLE');
    apple = await AppleContract.deploy()
  })

  describe("init", function () {

    it('initializes everyone owning zero apples', async () => {

      expect(await apple.balanceOf(owner.address)).to.equal(0);
      expect(await apple.balanceOf(user1.address)).to.equal(0);
      expect(await apple.balanceOf(user2.address)).to.equal(0);

    })

    it('initializes all nutrition scores to zero', async () => {

      expect(await apple.get_nutrition_score(owner.address)).to.equal(0);
      expect(await apple.get_nutrition_score(user1.address)).to.equal(0);
      expect(await apple.get_nutrition_score(user2.address)).to.equal(0);

    })

    it('initializes total supply of apples to zero (none minted up front)', async () => {

      expect(await apple.totalSupply()).to.equal(0);

    })

  });

  describe('minting apple', () => {

    it('can\'t be called by owner or user addresses', async () => {

      await expect(apple.mint(owner.address, 1)).to.be.revertedWith('Only the TREE contract can call this function');

    })

    describe('called by TREE contract', () => {

      it('mints apple to the specified user', () => {
        // TODO
      })

    })

  })


});
```

```
 yarn test ./test/APPLE.test.js
```

Why does it not see any of my tests???

![Screen Shot 2022-09-02 at 2 17 14 AM](https://user-images.githubusercontent.com/5354163/188071141-032bde56-a432-465f-933c-13efb3ba509f.png)

**Comment by woojiq** [comment]
Do you have any script (shortcut) for `yarn test`, because basically you need to write `yarn hardhat test`?

**Comment by woojiq** [comment]
Create new test file, paste this:
``` js
describe("testDesc", function () {
	it("testIt", async () => {
		console.log("Works!");
	});
});
```
Run command: `yarn hardhat test`.
Does it work and pass 1 test?

**Comment by alcuadrado** [comment]
Hey @JimLynchCodes,

The problem here is that you are using an async function within a describe, and that's not supported by mocha. Your `describe` callbacks need to be synchronous.

Thanks @woojiq for helping :)

**Comment by woojiq** [comment]
> The problem here is that you are using an async function within a describe, and that's not supported by mocha. Your `describe` callbacks need to be synchronous.

I didn't think _async describe_ was an issue before, because if I changed to async everything worked for me as before. But now I realized that this word means nothing if we do not cause anything asynchronous in the body. So I added _const test = ethers.getSigner()_ and now I have _0 passing_. +1 point to understanding asynchrony.

**Comment by JimLynchCodes** [comment]
@alcuadrado @woojiq  I need to call "ethers.getSigners()" in my code, which is an async function.

Why is mocha not supporting async describe? It doesn't make any sense to me... 👎

**Comment by JimLynchCodes** [comment]
@alcuadrado - I just removed the async from the describe. However, it is still not picked up by the test runner... 😭

WTF??

**Comment by woojiq** [comment]
> This is kind of a problem though bc I need to call "ethers.getSigners()" in my code, which is an async function.
> 
> Why is mocha not supporting async describe? It doesn't make any sense to me... 👎

What is the problem to do async code in beforeEach?
Instead of `const [owner, user1, user2] = await ethers.getSigners();`, do smth like this:
``` javascript
let owner, user1, user2;
beforeEach() {
     [owner, user1, user2] = await ethers.getSigners();
}
```
P.S. didn't test
