### ISSUE TITLE
coverage Error: Transaction reverted: trying to deploy a contract whose code is too large

### ISSUE THREAD

**Issue by jmendiola222** [NomicFoundation/hardhat#3121]
I have a project with a bunch of +10Kb sized contracts, and many tests that work fine. But when I run `hardhat coverage`, I first get the warning, which would be fine:
`Warning: Contract code size is 26746 bytes and exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.`
but later on, the actual tests fail because of
```
Error: Transaction reverted: trying to deploy a contract whose code is too large
    at X.constructor (X.sol:16)
    at async HardhatNode._mineBlockWithPendingTxs (~/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1773:23)
    at async HardhatNode.mineBlock (~/node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:466:16)
    at async EthModule._sendTransactionAndReturnHash (~/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:1504:18)
    at async HardhatNetworkProvider.request (~//node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:118:18)
```

I've tried the "fixes" suggested on issues [1430](https://github.com/NomicFoundation/hardhat/issues/1430) and [660](https://github.com/NomicFoundation/hardhat/issues/660) modifying both the hardhat.config with:
```
hardhat: {
      ...
      gas: 12000000,
      blockGasLimit: 0x1fffffffffffff,
      allowUnlimitedContractSize: true,
    },
```
And the `solcover.js` file (which would had been ideal as I DO want this to fail when not in coverage):
```
 providerOptions: {
    allowUnlimitedContractSize: true,
    blockGasLimit: 0x1fffffffffffff,
    gas: 12000000,
  },
```
But none did the trick. None of those issues mention anything about coverage tho. 

I'm using the latest versions:
```
    "hardhat": "2.10.2",
    "hardhat-deploy": "0.11.12",
    "solc": "0.8.16"
```
which yields:
```
Network Info
============
> HardhatEVM: v2.10.2
> network:    hardhat

> solidity-coverage: v0.7.21
```

**Comment by jmendiola222** [comment]
Ok, I found I way to make it work, but using a higher `gasLimit` on each deploy transaction of the deploy folder section. I do think there is a bug anyway, at least on the way this error is reported.

**Comment by jason0x0y** [comment]
> hardhat coverage

I also encountered the same problem when running hardhat coverage. how did you solve it?

**Comment by jmendiola222** [comment]
> > hardhat coverage
> 
> I also encountered the same problem when running hardhat coverage. how did you solve it?

As I said, for me, he issue was not as the error stated "code is too large" but a gasLimit problem that gets shadowed by it. I solve it increasing the gasLimit wherever required. ;)

**Comment by fvictorio** [comment]
Hey @jmendiola222, sorry for not responding before. Any chance you can create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for this? I would like to be able to reproduce it and understand the problem better.

**Comment by fvictorio** [comment]
Closing for lack of reproduction example.
