### ISSUE TITLE
`setStorageAt` helper makes slot index param wrong in some cases

### ISSUE THREAD

**Issue by farwayer** [NomicFoundation/hardhat#3122]
For example trying to change `0x0000bfcb6aad3f76fe8f641cee078635dc66e705d9289f78b52da608de318155` slot throws an error 
```js
InvalidArgumentsError: Errors encountered in param 1: Invalid value "0x000bfcb6aad3f76fe8f641cee078635dc66e705d9289f78b52da608de318155" supplied to : QUANTITY
```

**Comment by farwayer** [comment]
The problem is in this line https://github.com/NomicFoundation/hardhat/blob/4cce02506b662518d994a9992a52b7ff7bb1767f/packages/hardhat-network-helpers/src/utils.ts#L72

**Comment by alcuadrado** [comment]
Thanks, @farwayer! That sounds correct! How do you feel about sending a PR for it? :)
