### ISSUE TITLE
Error HH11: An internal invariant was violated: WASM build of solc 0.8.9 isn't working

### ISSUE THREAD

**Issue by KhanaropThongplave** [NomicFoundation/hardhat#3139]
So, I just created hardhat project by using "npx hardhat" command and select create a TypeScript project then when I'm trying to run "npx hardhat compile" this error shows up. Currently, I have no clue how to solve this problem since there aren't any case open about this problem.

<img width="1206" alt="Screen Shot 2565-09-06 at 11 13 02" src="https://user-images.githubusercontent.com/47390151/188545676-c398cf56-a221-4934-89b6-fda79e73ae8f.png">

This is my hardhat.config.ts:
<img width="633" alt="Screen Shot 2565-09-06 at 11 15 12" src="https://user-images.githubusercontent.com/47390151/188545793-2f56a091-9328-4ce7-b208-0571b0321a9a.png">

This is my package.json:
<img width="524" alt="Screen Shot 2565-09-06 at 11 17 17" src="https://user-images.githubusercontent.com/47390151/188545946-04a14da7-47fa-4d3c-8827-9774a2475ef6.png">

This is my tsconfig.json:
<img width="593" alt="Screen Shot 2565-09-06 at 11 18 13" src="https://user-images.githubusercontent.com/47390151/188546032-bccd8856-e741-4df2-91f4-ef2d3c228572.png">

Hardhat documentation suggests opening an issue https://hardhat.org/hardhat-runner/docs/errors#HH11

**Comment by fvictorio** [comment]
Thank you @KhanaropThongplave. Can you tell us more about your environment? Which OS and which node version?

Also, does this happen if you install `hardhat@2.10.1` and initialize a project in the same way?

**Comment by fvictorio** [comment]
Also, can you try running `npx hardhat clean --global` and then trying again (with the latest version)?

**Comment by fvictorio** [comment]
This should work with `hardhat@2.11.1`. Please upgrade and let us know if the issue is still there.
