### ISSUE TITLE
The "npx hardhat compile" is failing to compile solidity file

### ISSUE THREAD

**Issue by UjjwalThakur065** [NomicFoundation/hardhat#3144]
Whenever I am trying to start a new project and trying to compile a new solidity file, it is showing the same error again and again.
what I tried to fix it:
-I re-install the node
--Many times I started a new project

Here is error which I am getting:

![Screenshot 2022-09-06 122446](https://user-images.githubusercontent.com/105385470/188684576-cf767cd6-ce67-42f5-9018-c6396ed0df96.png)

**Comment by alcuadrado** [comment]
Hey, thanks for opening the issue.

Can you give us more information about your system? 
Which version of windows are you using? 
Which terminal are you using? 
Do you use WSL? WSL2? 
Is your computer x86 (32 or 64bits?)? Is it ARM? 
Does the file that ends with `.node` in the error message exist in your filesystem?

Thanks!

**Comment by UjjwalThakur065** [comment]
I am using windows 11 and I have v16.17.0 of node and my computer is 64bits.Other info about my system is given below:


Processor	Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz   1.80 GHz
Installed RAM	8.00 GB (7.88 GB usable)
Device ID	F5D09154-B2C1-47B7-B54B-6DB87AEF1DB7
Product ID	00327-35827-84369-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

I am not using WSL and that .node file is there whenever I installed the hardhat but it is is in corrupted form.

**Comment by alcuadrado** [comment]
I believe this is what's happening: https://github.com/parcel-bundler/parcel/issues/7104#issuecomment-967260755 

Can you try the solution there and tell us if it worked?

You can learn more about this here: https://georgik.rocks/how-to-statically-link-rust-application-for-windows/

**Comment by UjjwalThakur065** [comment]
Great! it worked for me.
Thank you so much for all your help.
Now you can close this issue.

**Comment by alcuadrado** [comment]
Thanks for testing it! Now that we understand what's going on, [we are fixing it](https://github.com/NomicFoundation/solidity-analyzer/commit/fb44483a0edf5dcc3048390dfc29ada18d4c0c9d) so that a separate installation is not needed.
