### ISSUE TITLE
Use official ethereumjs packages

### ISSUE THREAD

**Issue by wong2** [NomicFoundation/hardhat#3152]
Since EthereumJS VM v6 is published https://twitter.com/EFJavaScript/status/1567445968529784832 there is no need to use the forked version

**Comment by fvictorio** [comment]
Hi @wong2, we are still using our forked versions because there is a performance regression that makes Hardhat run two times slower for some payloads (e.g., OpenZeppelin's test suite takes exactly 2x the time). Until we figure out what to do about that, we'll have to continue using our fork.

**Comment by wong2** [comment]
Got it!

**Comment by wong2** [comment]
Any progress?

**Comment by fvictorio** [comment]
Not yet. We are unlikely to stop using our fork for a while, to be honest.

Can you tell us why you need this? That would help us prioritize the effort on dropping our fork.

**Comment by wong2** [comment]
Never mind, it's not a big issue. Just want to keep things cleaner 😄
