### ISSUE TITLE
Goerli Contract Verification Task Fails

### ISSUE THREAD

**Issue by 0xMoJo7** [NomicFoundation/hardhat#3154]
A friend of mine asked me to see if I could verify a contract on Goerli via Hardhat as it was failing for him. The task fails for both of us. But manual verification on Goerli etherscan works fine. The same deploy script works fine on Polygon and Rinkeby.

I am trying to deploy and verify [this contract (deployArrow.js)]( https://github.com/0xMoJo7/snowComputerHardhat)

Here is the stack:

```
Successfully submitted source code for contract
contracts/Arrow.sol:Arrow at 0xfAD0594B39Ec05035678879048A64f44535AB4d5
for verification on the block explorer. Waiting for verification result...

We tried verifying your contract Arrow without including any unrelated one, but it failed.
Trying again with the full solc input used to compile and deploy it.
This means that unrelated contracts may be displayed on Etherscan...

Successfully submitted source code for contract
contracts/Arrow.sol:Arrow at 0xfAD0594B39Ec05035678879048A64f44535AB4d5
for verification on the block explorer. Waiting for verification result...

NomicLabsHardhatPluginError: The contract verification failed.
Reason: Fail - Unable to verify
    at SimpleTaskDefinition.verifySubtask [as action] (/Users/mojo/bin/snowInterface/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:350:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Environment._runTaskDefinition (/Users/mojo/bin/snowInterface/node_modules/hardhat/src/internal/core/runtime-environment.ts:219:14)
    at Environment.run (/Users/mojo/bin/snowInterface/node_modules/hardhat/src/internal/core/runtime-environment.ts:131:14)
    at main (/Users/mojo/bin/snowInterface/scripts/deployArrow.js:18:5)
```

**Comment by alcuadrado** [comment]
Hey @0xMoJo7,

We've seen a few issues related to this lately. We are talking with the Etherscan team, as we suspect it's an issue on their end. We'll keep you posted.

**Comment by 0xMoJo7** [comment]
Thanks!

**Comment by alcuadrado** [comment]
Etherscan fixed this. Now your contract is verified!

**Comment by stephanepericat** [comment]
I still have this issue, can someone please help ?

**Comment by baileynottingham** [comment]
I'm seeing the same issue that just started last night. A couple of days ago I was able to deploy the same contract and verify on Goerli with no issues. Now the script just hangs on this line

`Waiting for verification result...`

**Comment by backseats** [comment]
This started for me this morning. I can't verify anything, from complex to contracts to a simple one

**Comment by mihaic195** [comment]
It's happening to me as well.

**Comment by fvictorio** [comment]
@mihaic195 I don't think this is a problem with Hardhat, so I can't re-open it. This is normally an intermittent issue in the Etherscan servers, as you can guess from the dates of the comments on this issue and the fact that no one comes back after a couple of days saying that the problem persists.

Of course, if you have proof that the bug is in Hardhat (say, you can verify something directly through the API but not with the `verify` task), then that would be a valid issue. But in that case, please open a new one.
