### ISSUE TITLE
Can't Run All Tests

### ISSUE THREAD

**Issue by JimLynchCodes** [NomicFoundation/hardhat#3159]
How tf do I run ALL my tests??

"hard test" runs nothing...

![Screen Shot 2022-09-09 at 10 30 05 AM](https://user-images.githubusercontent.com/5354163/189373862-b2ef0cdf-b207-481b-8182-ed1afa55ce54.png)

"hardhat test" pointed at the test folder runs nothing...

![Screen Shot 2022-09-09 at 10 29 27 AM](https://user-images.githubusercontent.com/5354163/189373747-39848494-bbf4-46b2-966c-6d9ec9550c6e.png)

ONLY hardhat pointed at one single specific file runs anything.

![Screen Shot 2022-09-09 at 10 30 58 AM](https://user-images.githubusercontent.com/5354163/189374040-b6fc5536-b5b0-4f49-986e-fff457189df4.png)

So I am wondering- wtf is wrong with this buggy pos hardhat cli???

**Comment by JimLynchCodes** [comment]
hardhat is absolute GARBAGE... I am very disappointed 😢

**Comment by alcuadrado** [comment]
We don't give support here, especially to rude people. You are doing something wrong, double check your settings and project structure.

**Comment by JimLynchCodes** [comment]
@alcuadrado thank you for being a human fart
