### ISSUE TITLE
Grammar error on hardhat.org/tutorial

### ISSUE THREAD

**Issue by ololade97** [NomicFoundation/hardhat#3168]
Hi,

I noticed a grammar error on hardhat.org/tutorial in the second paragraph - "to easily introducing more functionality".

It should be "to easily introduce more functionality". 

Could you look into this?

Thanks.

**Comment by alcuadrado** [comment]
Hey! Thanks for pointing this out! You can send a pr and win a gitpoap. You can correct this error from github. The website is in /docs/src/content/tutorial

**Comment by alcuadrado** [comment]
Thanks for fixing this 🙌
