### ISSUE TITLE
`verify:verify` task usage causes duplicated runs of `compile` task

### ISSUE THREAD

**Issue by nkuba** [NomicFoundation/hardhat#3173]
Currently when the `verify:verify` subtask is executed programmatically to verify contracts (e.g. in a deployment script) it runs the `compile` task as well. The compilation is rerun multiple times during the deployment process, which is not necessary as it's assumed the compilation was already called before running the deployment. 

In the example below I want to deploy three contracts (with `hardhat-deploy` plugin) and then verify them. The contracts will be compiled before the deployment and then each `verify:verify` execution will compile them again.
```
const ContractA = await hre.deployments.deploy("ContractA")
const ContractB = await hre.deployments.deploy("ContractB")
const ContractC = await hre.deployments.deploy("ContractC")

await hre.run("verify:verify", { address: ContractA.address })
await hre.run("verify:verify", { address: ContractB.address })
await hre.run("verify:verify", { address: ContractC.address })
```

**Comment by fvictorio** [comment]
Hi @nkuba, the `verify:verify` task now accepts a `noCompile` flag. Do you think that is enough to close this issue?
