### ISSUE TITLE
v2.11.1-MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by Track7Dev** [NomicFoundation/hardhat#3176]
#### Win 10 - Node v18.9.0
***Issue: '@nomicfoundation\solidity-analyzer-win32-x64-msvc' Module_Not_Found error present upon a clean install of the hardhat v2.11.1 even though the module is present within node_modules (seems to be a compiling issue)***

***Workaround: Install hardhat v2.10.2 and compile using the previous version first, then proceed to update to v2.11.1 for testing***
> $ npm i hardhat@2.10.2
> $ npx hardhat compile
> $ npm i hardhat@2.11.1
> $ npx hardhat test

#### v2.11.1 ERROR:
![hardhat_2 11 1_issue](https://user-images.githubusercontent.com/30492636/190053235-e2db5ca1-76c0-4378-a15b-4ef9a6f4bddb.png)

#### After v2.10.2 Workaround:
![hardhat_2 11 1_workaround](https://user-images.githubusercontent.com/30492636/190055678-b765f5d3-52ae-4141-9901-0f28d50aad69.png)

**Comment by alcuadrado** [comment]
Hey, can you please try reinstalling all your packages (deleting your `package-lock.json` and re-running `npm i`), and then sharing the output of `npm ls -a`?

I believe this bug has been fixed and that you have an older version of `@nomicfoundation/solidity-analyzer`.

**Comment by Arashi-H** [comment]
Hi. @alcuadrado.
This is fairly a great repo. I appreciate your effort and impressed by your skill.
And I've got the same error with @Track7Dev.
![image](https://user-images.githubusercontent.com/112880817/190474376-0d2de8b2-5beb-4753-aa67-da7a46282c1b.png)
And here is output of `npm ls -a` about `@nomicfoundation/solidity-analyzer`.
![image](https://user-images.githubusercontent.com/112880817/190475107-4461b5d9-e7f1-4015-ba62-323e37ec123f.png)
I'd like you to help me out.

**Comment by alcuadrado** [comment]
I identified the root of the issue, and I'm working on a workaround. You can read more details about it [here](https://github.com/napi-rs/napi-rs/issues/1316).

I'm working on a workaround, which will hopefully be shipped tomorrow. I'll keep you posted.

**Comment by alcuadrado** [comment]
PS: I think I may have confused your issue for another one. Our publish of version 0.0.4 of the library failed. I'm running it again now. You should be able to reinstall it in a few minutes, which should work.

@Arashi-H @Track7Dev

**Comment by alcuadrado** [comment]
Can you delete your `package-lock.json`/`yarn.lock`, reinstall, and try again?

**Comment by Arashi-H** [comment]
Thanks for your response.
I've started a new project with hardhat from scratch.
I initialized npm, installed hardhat, initialized hardhat framework and still have solidity-analyzer 0.0.3 not 0.0.4.
![image](https://user-images.githubusercontent.com/112880817/190533764-4c5f31da-24b2-4f38-aef0-1c0c08f09351.png)
This is killing my time. Please help me.

**Comment by alcuadrado** [comment]
Can you please try installing `hardhat@2.11.3-dev.0`? This one should fix it. If you confirm that it works I'll release it as final ASAP. @Arashi-H

**Comment by alcuadrado** [comment]
Thanks! I'll release it as stable today.

**Comment by Arashi-H** [comment]
@alcuadrado.
Sorry for late answer.
Now it's fixed and thank you for your effort.
I will keep in touch with you.

**Comment by fullkomnun** [comment]
@alcuadrado Thanks! when will this be released as stable?
