### ISSUE TITLE
Should fix the example code of `.changeEtherBalance`

### ISSUE THREAD

**Issue by innocentguy** [NomicFoundation/hardhat#3181]
As the [example](https://hardhat.org/hardhat-chai-matchers/docs/reference#.changeetherbalance) shows, we use this format to check if the balance changed as expected.
```javascript
await expect(
  sender.sendTransaction({ to: receiver, value: 1000 })
).to.changeEtherBalance(sender, -1000);
```
However, it'll get an error message `TypeError: txResponse.wait is not a function`

After I traced the code, I found the root cause in the waffle matchers ():
```javascript
// node_modules/@ethereum-waffle/chai/dist/esm/matchers/changeEtherBalances.js
export async function getBalanceChanges(transaction, accounts, options) {
    let txResponse;
    if (typeof transaction === 'function') {
        txResponse = await transaction();
    }
    else {
        txResponse = transaction;
    }

    // this line
    const txReceipt = await txResponse.wait();

    const txBlockNumber = txReceipt.blockNumber;
    const balancesAfter = await getBalances(accounts, txBlockNumber);
    const balancesBefore = await getBalances(accounts, txBlockNumber - 1);
    const txFees = await getTxFees(accounts, txResponse, options);
    return balancesAfter.map((balance, ind) => balance.add(txFees[ind]).sub(balancesBefore[ind]));
}
```
It seems that the input in `expect()` should be a function or a resolved transaction, 
so I modify the code as below and it works:

```javascript
// input a function
await expect(
  () => sender.sendTransaction({ to: receiver, value: 1000 })
).to.changeEtherBalance(sender, -1000);

// or resolve it instead
await expect(
  await sender.sendTransaction({ to: receiver, value: 1000 })
).to.changeEtherBalance(sender, -1000);
```

**Comment by alcuadrado** [comment]
I think you are conflicting two projects: `hardhat-chai-matchers` and `hardhat-waffle`. The example you linked is from `hardhat-chai-matcher`. Maker sure you don't have `hardhat-waffle` installed.

**Comment by innocentguy** [comment]
Got it. I think you're right, the hardhat version I'm using is not the newest one. 
Once I use the newest version, it actually link to the new implementation under `hardhat-chai-matchers`.

Thanks a lot!
