### ISSUE TITLE
We couldn't initialize the sample project because this file already exists ERROR

### ISSUE THREAD

**Issue by BerkKaanVAN** [NomicFoundation/hardhat#3200]
hi, i am having this error in hardhat v2.11.2 version. I get this warning after npx hardhat -> create a javascript project " We couldn't initialize the sample project because this file already exists: README.md" "Please delete or move them and try again."

**Comment by H20119** [comment]
> hi, i am having this error in hardhat v2.11.2 version. I get this warning after npx hardhat -> create a javascript project " We couldn't initialize the sample project because this file already exists: README.md" "Please delete or move them and try again."



> hi, i am having this error in hardhat v2.11.2 version. I get this warning after npx hardhat -> create a javascript project " We couldn't initialize the sample project because this file already exists: README.md" "Please delete or move them and try again."

having the same issue, did you find a solution yet ?

**Comment by H20119** [comment]
having the same issue, did you find a solution yet ?

**Comment by H20119** [comment]
having the same issue, did you find a solution yet ?

**Comment by fvictorio** [comment]
The project initialization tries to avoid overwriting files, and so it stops if there are existing files that clash with the ones that Hardhat would create. In this case, you can do something like this:

```
mv README.md README.md.bak
npx hardhat # initialize project
rm README.md # remove the readme that Hardhat created
mv README.md.bak README.md
```

The project initialization could be smarter here though, but we already have an issue open about that, so I'm going to close this one.
