### ISSUE TITLE
Hardhat-core `internal/cli/cli.js` is not executable anymore

### ISSUE THREAD

**Issue by ottodevs** [NomicFoundation/hardhat#3201]
Recent versions of hardhat changed the way `cli.js` is built, so it has not executable permission anymore, that causes new installations to fail while trying to call any `hardhat` command with `Permission denied`. It is specially disturbing in CI environments.

To reproduce, just install an older version of hardhat in an empty node project (ensure you are not caching dependencies) and run `ls -ll ./node_modules/hardhat/internal/cli/cli.js`

The output permissions show:
`lrwxr-xr-x` (note the x that allows the program to be executable)

Now try with the latest version and the output for  `ls -ll ./node_modules/hardhat/internal/cli/cli.js` is now:
`-rw-r--r--` so the command hardhat that is just an alias for cli.js is not working anymore until making it executable

**Comment by ottodevs** [comment]
To add more context, I am testing several versions, and this issue does not happen with `2.11.0` so the regression was probably introduced in the version `2.11.1`

**Comment by ottodevs** [comment]
It does seem related with our code environment, because I tried several versions and all fail with the same issue, also with github actions:
![image](https://user-images.githubusercontent.com/5030059/191529845-993bcea9-1817-4c6b-a443-893d2d98cb3d.png)

Maybe it is related to pnpm or because I am using hardhat as a regular dependency instead of devDependency, I will keep trying and updating

**Comment by fvictorio** [comment]
Hi @ottodevs, do you think there's something we can do on our side?

**Comment by ottodevs** [comment]
> Hi @ottodevs, do you think there's something we can do on our side?

Maybe there is a potential solution to generate the correct executable permissions for symlinked executables, as there are so many libraries that work correctly that way, but at this moment I am not sure what would be the potential fix... right now the workaround is adding that `.npmrc` flag, but that is probably degrading pnpm experience, since preventing symlinked executables will use more disk space.

I don't know the correct answer, so maybe for now it is ok to close this, unless you have any idea on what is happening or enough amount of devs demand this to consider adding some priority.

**Comment by fvictorio** [comment]
Thank you. I'm going to close it mainly for bookkeeping reasons but we do monitor closed issues. If you or anyone else has any idea of how to approach this, please leave a comment here.
