### ISSUE TITLE
Verify doesn't work for ArbitrumOne

### ISSUE THREAD

**Issue by tom-s07** [NomicFoundation/hardhat#3204]
```
npx hardhat verify --network arbitrum 0xfoo "0xbar"
Nothing to compile
Successfully submitted source code for contract
contracts/MyContract.sol:MyContract at 0xfoo
for verification on the block explorer. Waiting for verification result...

We tried verifying your contract MyContract without including any unrelated one, but it failed.
Trying again with the full solc input used to compile and deploy it.
This means that unrelated contracts may be displayed on Etherscan...

Successfully submitted source code for contract
contracts/MyContract.sol:MyContract at 0xfoo
for verification on the block explorer. Waiting for verification result...

Error in plugin @nomiclabs/hardhat-etherscan: The contract verification failed.
Reason: Fail - Unable to verify

```

Discord is full of people having the same issue.

API key is correct and configured properly.
No changes were made to the contracts, this was run immediately after deploying.

`"devDependencies": {
    "@nomicfoundation/hardhat-toolbox": "^1.0.2",
    "@nomiclabs/hardhat-etherscan": "^3.1.0",
    "hardhat": "^2.10.2",
   ...
  },`

Solidity `pragma solidity ^0.8.17;`

Error message really doesn't help tracking the problem down ¯\_(ツ)_/¯ 

Would appreciate any feedback since this seems to be ignored in discord.

**Comment by fvictorio** [comment]
Summoning @Enigmatic331

**Comment by Enigmatic331** [comment]
Hi @tom-s07 - Could you give it another try please? We were having some issues with verification earlier but have taken remedial action, and should work out now.

Thanks and sorry for the inconvenience. 🙇

**Comment by tom-s07** [comment]
`Error in plugin @nomiclabs/hardhat-etherscan: Contract source code already verified`
😂 

Seems like the error was the error and it worked after all? 🤷‍♂️

**Comment by kabaluyot** [comment]
@tom-s07 you can try this workaround in your contract. Basically just need some difference in bytecode.

```
// Etherscan trick. Increment the build number every deployment.
function _delBuildNumber6() internal pure {}
```

**Comment by tom-s07** [comment]
No, it seems it worked despite throwing that error initially. I didn't manually verify the contracts or anything, it must have been the `verify` call that threw the error.

**Comment by fvictorio** [comment]
Thanks for chiming in @Enigmatic331!

I'm gonna assume that this is fixed then and close this issue, but @tom-s07 please let us know if that's not the case.
