### ISSUE TITLE
etherscan verify doesn't support goerli-optimism (chainid:420)

### ISSUE THREAD

**Issue by rube-de** [NomicFoundation/hardhat#3212]
I can't verify contracts on optimism testnet goerli.

running etherscan-verify 
``yarn hardhat etherscan-verify --network goerliOptimsm``
results in
"Network with chainId: 420 not supported"

my hardhat config:
```
module.exports = {
  networks: {
    goerliOptimism: {
      url: 'https://goerli.optimism.io',
      accounts: accounts("optimism_goerli"),
      chainId: 420,
      live: true,
      saveDeployments: true,
      tags: ["staging"],
      deploy: ['deploy_optimism']
    },
    etherscan: {
      apiKey: {
        mainnet: process.env.ETHERSCAN_API_KEY,
        goerliOptimism: process.env.OPTIMISM_ETHERSCAN_API_KEY,
      },
      customChains: [
        {
          network: "goerliOptimism",
          chainId: 420,
          urls: {
            apiURL: "https://api-goerli-optimism.etherscan.io/api",
            browserURL: "https://goerli-optimism.etherscan.io"
          }
        }
      ]
  }
```

**Comment by fvictorio** [comment]
Your `etherscan` config is within the `networks` object, but it should be at the top of the config:

```js
module.exports = {
  networks: {
    goerliOptimism: {
      url: "https://goerli.optimism.io",
      accounts: accounts("optimism_goerli"),
      chainId: 420,
      live: true,
      saveDeployments: true,
      tags: ["staging"],
      deploy: ["deploy_optimism"]
    }
  },
  etherscan: {
    apiKey: {
      mainnet: process.env.ETHERSCAN_API_KEY,
      goerliOptimism: process.env.OPTIMISM_ETHERSCAN_API_KEY
    },
    customChains: [
      {
        network: "goerliOptimism",
        chainId: 420,
        urls: {
          apiURL: "https://api-goerli-optimism.etherscan.io/api",
          browserURL: "https://goerli-optimism.etherscan.io"
        }
      }
    ]
  }
};
```

**Comment by rube-de** [comment]
I wish that this would be the issue, but sadly I just copied it in my post just wrongly together.
I have etherscan on the top level , same as networks.

**Comment by fvictorio** [comment]
Oh damn. Can you share the updated version of the hardhat config then?

**Comment by henry-wrightman** [comment]
why was this closed? i'm facing the same issue - has this been resolved?

**Comment by bghughes** [comment]
> Sorry, I just realized that, while support for optimistic Goerli is merged, we haven't released it yet 🤦‍♂️
> 
> I'll re-open this and close it when we release that (I'll try to do it early next week).

Looking forward to this as our team needs `chainID 420` support 🙌

**Comment by WarTech9** [comment]
> Sorry, I just realized that, while support for optimistic Goerli is merged, we haven't released it yet 🤦‍♂️
> 
> I'll re-open this and close it when we release that (I'll try to do it early next week).

But ser, wen release?

**Comment by fvictorio** [comment]
Sorry, I forgot to mention that we already [released this](https://github.com/NomicFoundation/hardhat/releases/tag/%40nomiclabs%2Fhardhat-etherscan%403.1.1).

**Comment by wei3erHase** [comment]
still cannot achieve it, changed the order of the config declaration, updated it to v3.1.1, but still ignores the request.
detail, my network is not called `optimisticGoerli`, but called `receiver`, still points to 420. same setup works for goerli verifications, which network is called `sender`

**Comment by WarTech9** [comment]
> Sorry, I forgot to mention that we already [released this](https://github.com/NomicFoundation/hardhat/releases/tag/%40nomiclabs%2Fhardhat-etherscan%403.1.1).

Awesome! Great news. Works as expected but one cosmetic issue with the URL displayed to etherscan page being wrong. Opened an issue here: https://github.com/NomicFoundation/hardhat/issues/3288

**Comment by 0xFloyd** [comment]
@fvictorio  Followed your info above, seems I am still running into this same issue
running `yarn verify --network optimisticGoerli`
`Network with chainId: 420 not supported. You can specify the url manually via --api-url <url>.`

running `npx hardhat verify --list-networks` shows `optimisticGoerli` as  chain id `420`

yarn script:
```
  "scripts": {
    "verify": "hardhat etherscan-verify"
  }
```

version in package.json:
` "@nomiclabs/hardhat-etherscan": "^3.1.1",`

hardhat.config.js:
```
module.exports = {
  networks: {
    optimisticGoerli: {
      url: "https://goerli.optimism.io",
      accounts: [process.env.PRIVATE_KEY],
      live: true,
      saveDeployments: true,
    },
  },
  etherscan: {
    apiKey: [process.env.ETHERSCAN_API_KEY],
  },
};
```

To make sure I actually did indeed update to the correct package version of hardhat-etherescan, ran the command below: 
`yarn list --pattern @nomiclabs/hardhat-etherscan`

```
yarn list v1.22.19
├─ @nomiclabs/hardhat-etherscan@3.1.2
└─ @scaffold-eth/hardhat@1.0.0
   └─ @nomiclabs/hardhat-etherscan@3.1.2
✨  Done in 0.74s.
```

**Comment by fvictorio** [comment]
@0xFloyd The `etherscan-verify` is a task added by [hardhat-deploy](https://github.com/wighawag/hardhat-deploy). To verify using `hardhat-etherscan`, you have to use the plain `verify` task. [Docs](https://hardhat.org/hardhat-runner/plugins/nomiclabs-hardhat-etherscan).
