### ISSUE TITLE
Documentation not works even for simplest project on typescript

### ISSUE THREAD

**Issue by iraklid** [NomicFoundation/hardhat#3213]
https://hardhat.org/hardhat-runner/docs/guides/typescript#installing-dependencies

Following documentation here and can't even run the simplest project. 

installing `hardhat-toolbox` not gives anything and there is no resource to what should be done in this case.

<img width="745" alt="CleanShot 2022-09-26 at 23 15 39@2x" src="https://user-images.githubusercontent.com/91540149/192361068-1b609711-6ae0-4b56-9ce0-39799fc3bf04.png">

<img width="466" alt="CleanShot 2022-09-26 at 23 15 51@2x" src="https://user-images.githubusercontent.com/91540149/192361119-55384d75-e71c-424f-8e5a-c11872b5da40.png">

<img width="564" alt="CleanShot 2022-09-26 at 23 16 11@2x" src="https://user-images.githubusercontent.com/91540149/192361170-f748cfe7-92a3-4851-923b-3dfe9f094466.png">

Still 

<img width="811" alt="CleanShot 2022-09-26 at 23 16 29@2x" src="https://user-images.githubusercontent.com/91540149/192361219-cc13d3cb-8679-45e9-b880-f5340a21ae55.png">

**Comment by iraklid** [comment]
Seems like very simple issue, yet cant find any doc to tell what to do in this case. `hardhat-toolbox` is magical box without any proper documentation...

**Comment by fvictorio** [comment]
@iraklid which version of `npm` are you using? Please share the output of `npm --version`

**Comment by iraklid** [comment]
<img width="830" alt="CleanShot 2022-09-27 at 16 38 38@2x" src="https://user-images.githubusercontent.com/91540149/192528428-6e160bd5-63f4-4d53-9d61-b1ce6168cf2c.png">
 
Hey @fvictorio thanks for quick reply. Here is the `npm` version I am using, documentation says version 7 and higher, so it should be fine

**Comment by fvictorio** [comment]
And `npm install` doesn't fix the problem? That's weird. Any chance you can share your repo?

**Comment by iraklid** [comment]
Sure, https://github.com/idarbuashvili/hardhat-simple. 

But the thing is that, it contains nothing extra, its boilerplate generated by `npx hardhat`. So what I did is: 

`mkdir hardhat-tut`

`cd hardhat-tut`

`npm init -y`

`npx hardhat` - Here choose typescript project and install `hardhat-toolbox` as well.

Running `npx hardhat compile` throws above error. 

I am on MacOS Monterey, m1 macbook pro.

**Comment by fvictorio** [comment]
If I clone that project, use `npm@8.19.2` (the one you have), and install the dependencies. I indeed get an error, but not the one about typescript not being installed. I get an ESM error, because your `package.json` has `"type": "module"`. I guess you added it manually, because `npm init -y` doesn't include that. We don't support ESM yet, but we are [working on it](https://github.com/NomicFoundation/hardhat/pull/3211).

Removing the `"type": "module"` entry makes everything work.

I really don't know why you got the missing typescript error the first time. Maybe you were using an older version of npm without realizing it, or yarn?

In any case, can you try running this from scratch in an empty directory and telling me if you still get the error?

> So what I did is:
> 
> `mkdir hardhat-tut`
> 
> `cd hardhat-tut`
> 
> `npm init -y`
> 
> `npx hardhat` - Here choose typescript project and install `hardhat-toolbox` as well.
> 
> Running `npx hardhat compile` throws above error.

**Comment by iraklid** [comment]
Created clean dir on desktop, and got same error (https://cln.sh/VCQBQG), after running clean hardhat setup with typescript. Must be some edge case on my system. Here the list of global packages I have installed and npm version, maybe something is messing with hardhat internals. 

<img width="373" alt="CleanShot 2022-10-01 at 19 22 52@2x" src="https://user-images.githubusercontent.com/91540149/193416434-9dcf58f9-5ee4-422a-886e-cbb46c941be6.png">

**Comment by iraklid** [comment]
I am generally updating node using nvm and moving the global packages from previous node install, nvm does global package move automatically. Maybe that is causing an issue, bit later will install clean node version and try above setup again. Do I need any global packages preinstall,  or clean node/npm should be enough, for `hardhat-toolbox` to work out of the box?

**Comment by fvictorio** [comment]
Clean node should be enough.

I wonder if the problem is that you have `typescript` globally installed. If that's the case, it would a bug on our side.

**Comment by fvictorio** [comment]
Hey @iraklid, did you figure this out?
