### ISSUE TITLE
proposal to support import remapping using remappings.txt

### ISSUE THREAD

**Issue by kennysliding** [NomicFoundation/hardhat#3231]
Proposal: when compiling the contracts, hardhat should look for the path alias defined in remappings.txt, and replace the path as defined in the solidity [docs](https://docs.soliditylang.org/en/v0.8.17/path-resolution.html#import-remapping)

a simple example,

`remappings.txt`:
```txt
@sample-project/="./sample-project/contracts/"
```
and in the contracts:
```solidity
import "@sample-project/sample-contract.sol"

**Comment by Ayuilos** [comment]
Hello, is there a ETA for this feature? I sufferred when I wanna migrate some project with `remapping.txt` to Hardhat.

**Comment by ankurdubey521** [comment]
AFAIK this can be achieved currently by using https://www.npmjs.com/package/hardhat-preprocessor

**Comment by Ayuilos** [comment]
@ankurdubey521 yeah I've found this solution on https://book.getfoundry.sh/config/hardhat#instructions , this very fragmented development experience is very inconvenient

**Comment by fvictorio** [comment]
Our recommended way to do this is using our [`hardhat-foundry`](https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-foundry) plugin.

If that's not enough for some use case, please let me know and I'll open a new issue about it.
