### ISSUE TITLE
Small typo on website

### ISSUE THREAD

**Issue by JussaMouse** [NomicFoundation/hardhat#3244]
There is a small typo in the code presented in the [Full Coverage section of the Testing Contracts page of the tutorial](https://hardhat.org/tutorial/testing-contracts#full-coverage)

(line 31):
`    // its deployed() method, which happens onces its transaction has been`

As you can see, the word "once" has a trailing "s".

**Comment by fvictorio** [comment]
Thanks a lot @JussaMouse. This is especially important, I'm glad that you reported it:

> The "Help us improve this page" link at the bottom of the page is dead
