### ISSUE TITLE
Hardhat RPC eth_getStorageAt Invalid value supplied

### ISSUE THREAD

**Issue by fastchain** [NomicFoundation/hardhat#3254]
Hello,

```
npx hardhat --version
2.11.2
```

How to reproduce:

Deploy gnosis-safe  with hardhat  (from this repo https://github.com/5afe/safe-tasks ) . Please setup your private key and  hardhat rpc in .env file.

```
npx hardhat create  --factory  [your factory address] 
npx hardhat info [your safe address]
```

on ` npx hardhat info` I get this :

```
npx  hardhat info  0xF58681d366Afb34a3490862C39282FC2D938CCe5 

Checking Safe at 0xF58681d366Afb34a3490862C39282FC2D938CCe5
(node:870) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
An unexpected error occurred:

ProviderError: HttpProviderError
    at HttpProvider.request (/offchain/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
    at LocalAccountsProvider.request (/offchain/node_modules/hardhat/src/internal/core/providers/accounts.ts:187:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async EthersProviderWrapper.send (/offchain/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

also see this in  virtualnode RPC logs 

```
eth_chainId (2)
hardhat1        | eth_getStorageAt
hardhat1        | 
hardhat1        |   Errors encountered in param 1: Invalid value "0x0000000000000000000000000000000000000000000000000000000000000000" supplied to : QUANTITY
hardhat1        | 
```

I've  also  checked this behavior on public testnets, and it worked fine, as intended. So it seems to be hardhat  virtualnode problem.

Thank you.

**Comment by fastchain** [comment]
@fvictorio  hi!  I have no permissions to see the bug in Linear

**Comment by fvictorio** [comment]
Hi @fastchain, thanks for opening this, I will take a look as soon as I have some time.

> I have no permissions to see the bug in Linear

That's our internal issue tracker, but I'll post here anything I find.

**Comment by fvictorio** [comment]
Hi @fastchain, can you give me more detailed reproduction steps? What would be an example of a factory address here? Is this meant to be run in a fork?

If you can give me a detailed list of steps so I don't have to figure out how the project works, that would be ideal.

**Comment by fvictorio** [comment]
Hi @fastchain, any chances of giving me detailed steps or, even better, creating a minimal reproduction example?

**Comment by fastchain** [comment]
Hi! Sorry for delay,I was on vacation. I'll back with details in 2-3 days.

**Comment by fvictorio** [comment]
Closing for lack of reproduction steps. Happy to re-open if someone can provide them.
