### ISSUE TITLE
Hardhat node is not able to fork network

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [NomicFoundation/hardhat#3267]
I am forking a node using `yarn hardhat node --fork https://astar-mainnet.g.alchemy.com/v2/<api_key>` but it's giving me this error:
```
Error HH604: Error running JSON-RPC server: Invalid JSON-RPC response's result.

Errors: Invalid value null supplied to : RpcBlockWithTransactions | null/transactions: RpcTransaction Array/0: RpcTransaction/accessList: Array<{ address: DATA, storageKeys: Array<DATA> | null }> | undefined, Invalid value null supplied to : RpcBlockWithTransactions | null/transactions: RpcTransaction Array/1: RpcTransaction/accessList: Array<{ address: DATA, storageKeys: Array<DATA> | null }> | undefined, Invalid value null supplied to : RpcBlockWithTransactions | null/transactions: RpcTransaction Array/2: RpcTransaction/accessList: Array<{ address: DATA, storageKeys: Array<DATA> | null }> | undefined, Invalid value null supplied to : RpcBlockWithTransactions | null/transactions: RpcTransaction Array/5: RpcTransaction/accessList: Array<{ address: DATA, storageKeys: Array<DATA> | null }> | undefined
```

The node is working correctly as I am able to query the node using the `curl` command. 

Sometimes even the `yarn hardhat node` works and sometimes doesn't work. 

This is very strange for me as I have used hardhat on my machine but I haven't run into such a problem.

Similar issue: https://stackoverflow.com/questions/69659558/error-hh604-error-running-json-rpc-server-error0308010cdigital-envelope-rout

My machine specs:
OS: Ubuntu 22.04
Node: v16.16.0 
Hardhat: 2.11.2

**Comment by fvictorio** [comment]
The node seems to be returning a transaction object where `accessList` is null (for a legacy transaction). As far as I can tell, this is [not spec compliant](https://ethereum.github.io/execution-apis/api-documentation/). Legacy transactions shouldn't include the `accessList` property.

I'm going to keep the issue open for now, but it's not very likely that we'll adapt our code to this response. Instead, I suggest reaching to the team developing the client (I have no idea who that would be for Astar) and ask them to follow the spec. There's also a slight chance that this is a problem with Alchemy's backend, but it would be weird if it worked fine with Ethereum but not with other networks.

**Comment by fvictorio** [comment]
Closing because I don't think there's much we can do here.
