### ISSUE TITLE
Global typecheck opt-in

### ISSUE THREAD

**Issue by olehmisar** [NomicFoundation/hardhat#3279]
In hardhat 2.11 projects are not checked by typescript unless `--typecheck` flag is specified. Is there a way to enable typecheck globally, so I don't have to specify it for each command I run (I prefer correctness over speed). If not, could this be implemented?

**Comment by olehmisar** [comment]
Ah, I see the problem. A "hacky" way to make the `typecheck` config variable would be to run `tsc --noEmit` after `hardhat.config.ts` is loaded and abort if type errors were found.

However, I am not sure whether it's worth doing that as my use case may be pretty rare.

Also, seeing this change as minor change might be confusing to some users(as it was for me). It looks more like a major(breaking) change to me.

**Comment by fvictorio** [comment]
> Also, seeing this change as minor change might be confusing to some users(as it was for me). It looks more like a major(breaking) change to me.

I agree with this, this certainly can be considered a breaking change. In this case we considered that the potential benefit for users (way faster in the general case) was worth not waiting for the next major, since we don't do that often. It might've been the wrong call though :sweat_smile:

**Comment by fvictorio** [comment]
I'm going to close this because I don't think there's much we can do :slightly_frowning_face:
