### ISSUE TITLE
The Hardhat Network tracing engine could not be initialized.

### ISSUE THREAD

**Issue by jasonthehung** [NomicFoundation/hardhat#3286]

**Comment by fvictorio** [comment]
@jasonthehung do you have reproduction steps?

**Comment by Fabien-Morrow** [comment]
I'm having this error too. Steps to reproduce :

- create an empty hardhat project, with the following package.json for example
```js
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@nomicfoundation/hardhat-toolbox": "^2.0.0",
    "hardhat": "^2.12.4"
  }
}
```
- Create a sol file using console.sol, for example
```js
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "../node_modules/hardhat/console.sol";
```
- pnpm hardhat compile
- pnpm hardhat console
- const value = ethers.pro <- wait for autocompletion and throw warning about tracing engine

![image](https://user-images.githubusercontent.com/91032561/208257079-ce2617f0-9a3d-46ca-b747-5608e5c6ab8a.png)

Thank you for your amazing product guys !

**Comment by fvictorio** [comment]
@Fabien-Morrow change `import "../node_modules/hardhat/console.sol";` to `import "hardhat/console.sol"` and it should work.

We should handle those scenarios differently though. It should either work or throw a proper error. I opened #3445 to track that, so I'm going to close this issue in favor of that one.
