### ISSUE TITLE
Hardhat Tutorial is Break

### ISSUE THREAD

**Issue by Cryptolibertarian-id** [NomicFoundation/hardhat#3293]
Hello Teams, we just follow the tutorial from here :

https://hardhat.org/tutorial

After the step of installing Hardhat Toolbox we are going to make testing using chai,
but when we run : 

`npx hardhat test`

the result is : 

`ReferenceError: chai is not defined`

My Operating system is Windows 10, 
My node js version is v 16.16.0
My npm version is 8.19.2

**Comment by fvictorio** [comment]
@Cryptolibertarian-id can you share the output of `npm ls`?

**Comment by fvictorio** [comment]
Closing for lack of response.
