### ISSUE TITLE
Remove mention of "underflow" in error messages

### ISSUE THREAD

**Issue by frangio** [NomicFoundation/hardhat#3309]
"Underflowed" should be removed from the error message below. The correct term for integer arithmetic is "overflow" even if the number goes below 0. [Underflow](https://en.wikipedia.org/wiki/Arithmetic_underflow) refers to a floating point number becoming too small.

https://github.com/NomicFoundation/hardhat/blob/dbf7c0b33001ebca01ac3737e8599ef251cf0de7/packages/hardhat-core/src/internal/hardhat-network/stack-traces/panic-errors.ts#L16

https://github.com/NomicFoundation/hardhat/blob/dbf7c0b33001ebca01ac3737e8599ef251cf0de7/packages/hardhat-chai-matchers/src/internal/reverted/panic.ts#L23

**Comment by fvictorio** [comment]
TIL. Thank you.
