### ISSUE TITLE
Error in plugin @nomiclabs/hardhat-etherscan: Invalid API Key 2

### ISSUE THREAD

**Issue by azerpas** [NomicFoundation/hardhat#3314]
## Reproductible 
```
npx hardhat verify --network optimismGoerli 0x0000000...
```

## Error 
```
Error in plugin @nomiclabs/hardhat-etherscan: Invalid API Key 2
```

I've tried with two different API keys from Etherscan.

**Comment by fvictorio** [comment]
@azerpas can you share how your Hardhat config looks like (without sharing the actual API keys, of course, just replace the value with `xxxxx` )?

**Comment by azerpas** [comment]
Sure, sorry:
```ts
import { HardhatUserConfig } from 'hardhat/config'
import '@nomicfoundation/hardhat-toolbox'
import '@nomicfoundation/hardhat-chai-matchers'
import "@nomiclabs/hardhat-etherscan"
import '@nomiclabs/hardhat-ethers'
import '@typechain/hardhat'
import '@openzeppelin/hardhat-upgrades'
import "hardhat-gas-reporter"
import * as dotenv from 'dotenv'

dotenv.config()
const ALCHEMY_API_KEY = process.env.ALCHEMY_API_KEY
const GOERLI_PRIVATE_KEY = process.env.GOERLI_PRIVATE_KEY!
const ALCHEMY_OPTIMISM_GOERLI_API_KEY = process.env.ALCHEMY_OPTIMISM_GOERLI_API_KEY

const config: HardhatUserConfig = {
    solidity: {
        version: '0.8.17',
        settings: {
            optimizer: {
                enabled: true,
                runs: 200
            }
        },
    },
    typechain: {
        outDir: 'typesDir/contracts'
    },
    networks: {
        hardhat: {
            allowUnlimitedContractSize: true
        },
        localhost: {
            allowUnlimitedContractSize: true
        },
        goerli: {
            url: `https://eth-goerli.alchemyapi.io/v2/${ALCHEMY_API_KEY}`,
            accounts: [GOERLI_PRIVATE_KEY],
            allowUnlimitedContractSize: true,
            timeout: 1000000
        },
        optimismGoerli: {
            url: `https://opt-goerli.g.alchemy.com/v2/${ALCHEMY_OPTIMISM_GOERLI_API_KEY}`,
            accounts: [GOERLI_PRIVATE_KEY],
            allowUnlimitedContractSize: true,
            timeout: 1000000
        }
    },
    etherscan: {
        apiKey: process.env.ETHERSCAN_API_KEY
    },
    gasReporter: {
        enabled: (process.env.REPORT_GAS) ? true : false,
        coinmarketcap: process.env.COINMARKETCAP_API_KEY,
        outputFile: 'gas-report.txt',
        noColors: true,
        showTimeSpent: true,
        token: "ETH",
        gasPriceApi: "https://api-optimistic.etherscan.io/api?module=proxy&action=eth_gasPrice"
    }
}
```

Note that the verify is working on Ethereum Goerli

**Comment by azerpas** [comment]
@fvictorio I've also tried with etherscan set to something like this:
```ts
etherscan: {
        apiKey: process.env.ETHERSCAN_API_KEY,
        customChains: [
            {
                network: 'optimismGoerli',
                chainId: 420
                urls: {
                    apiURL: 'https://api-goerli-optimism.etherscan.io/api',
                    browserURL: 'https://api-goerli-optimism.etherscan.io'
                }
            }
        ]
    }
```

**Comment by azerpas** [comment]
@fvictorio I've just printed it inside `hardhat.config.ts` just above the config definition and the `ETHERSCAN_API_KEY` env is set correctly. Note that the verify is working on Ethereum Goerli

**Comment by fvictorio** [comment]
Oh wait, I don't think you can use the same API key for both the mainnet/goerli explorer and for the optimism/optimism goerli explorers. Maybe that's the problem. Check [this](https://hardhat.org/hardhat-runner/plugins/nomiclabs-hardhat-etherscan#multiple-api-keys-and-alternative-block-explorers) to learn how to set different api keys for different networks.

That being said, the error you get seems wrong, doesn't it? cc @Enigmatic331

**Comment by azerpas** [comment]
> Oh wait, I don't think you can use the same API key for both the mainnet/goerli explorer and for the optimism/optimism goerli explorers. Maybe that's the problem. Check [this](https://hardhat.org/hardhat-runner/plugins/nomiclabs-hardhat-etherscan#multiple-api-keys-and-alternative-block-explorers) to learn how to set different api keys for different networks.
> 
> That being said, the error you get seems wrong, doesn't it? cc @Enigmatic331

That was indeed the issue. I didn't notice that Etherscan accounts were different for the mainnet and Optimism. Thanks a lot, closing. 😃
