### ISSUE TITLE
Docs claim accounts in hardhat.config.js can take an array of objects, but it takes an array of strings

### ISSUE THREAD

**Issue by kf106** [NomicFoundation/hardhat#3325]
https://hardhat.org/hardhat-network/docs/reference#hd-wallet-config states that accounts can be

"An array of the initial accounts that the Hardhat Network will create. Each of them must be an object with privateKey and balance fields."

But if I supply such an array, then I receive the error, "Invalid account: #0 for network: coverage - Expected string, received object"
```
    coverage: {
      url: "http://127.0.0.1:8555",
      gas: 0xfffffffffff,
      gasPrice: 0x01,
      accounts: [
        {
          privateKey: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80", 
          balance: "333333"
        }
      ]
    },
```

An array of string of private keys works, but does not set the balance I want, of course:
```
    coverage: {
      url: "http://127.0.0.1:8555",
      gas: 0xfffffffffff,
      gasPrice: 0x01,
      accounts: [ "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" ]
    },
```

Similarly, if you provide an HD wallet object, which is the other option described in the docs, the accountsBalance field is ignored, and all the addresses have a balance of zero:
```
    coverage: {
      url: "http://127.0.0.1:8555",
      gas: 0xfffffffffff,
      gasPrice: 0x01,
      accounts:
        {
          mnemonic: "test test test test test test test test test test test junk",
          initialIndex: 0,
          path: "m/44'/60'/0'/0",
          count: 20,
          accountsBalance: "333333",
          passphrase: ""
        }
    },
```

results in things like:
`sender doesn't have enough funds to send tx. The upfront cost is: 4291662 and the sender's account only has: 0
`Hardhat version: 2.12.2

**Comment by fvictorio** [comment]
Hi @kf106, that only applies to the `hardhat` network, which is the only case where we have control over the balances of the accounts.

Other networks have a different configuration, you can check it [here](https://hardhat.org/hardhat-runner/docs/config#json-rpc-based-networks).
