### ISSUE TITLE
Hardhat bug

### ISSUE THREAD

**Issue by Programmer001-JS** [NomicFoundation/hardhat#3326]
Pease help me!!

When l try to send some eth between teo accounts via metamask, i have this message in my terminal.

eth_estimateGas

  If you think this is a bug in Hardhat, please report it here: https://hardhat.org/reportbug

**Comment by fvictorio** [comment]
Try [resetting](https://metamask.zendesk.com/hc/en-us/articles/360015488891-How-to-reset-an-account) your MetaMask accounts.

Closing this because I believe we already have an issue tracking this problem.
