### ISSUE TITLE
`changeEtherBalance` doesn't work with contracts.

### ISSUE THREAD

**Issue by alcuadrado** [NomicFoundation/hardhat#3338]
As reported here, this helper, and possibly others, doesn't work when using contracts instead of signers. I think this should be supported, or clearly forbidden.

![telegram-cloud-photo-size-2-5436084856544150878-y](https://user-images.githubusercontent.com/176499/201218019-37999fca-aa8e-4ac9-83f5-96465e39be4a.jpg)

**Comment by RenanSouza2** [comment]
Hey @fvictorio, I think this issue can be closed, I tested it now and it works fine for contracts

**Comment by fvictorio** [comment]
You are right, I think this should work with the ethers v6-based version. Thanks!
