### ISSUE TITLE
`deployContract` missing from `hardhat-ethers` readme

### ISSUE THREAD

**Issue by ItsNickBarry** [NomicFoundation/hardhat#3355]
I would PR, but the function appears to be overloaded and I'm not sure to document it.

**Comment by fvictorio** [comment]
Thank you @ItsNickBarry. That readme is not great tbh. I opened https://github.com/NomicFoundation/hardhat/pull/3359 to improve it.

**Comment by fvictorio** [comment]
You probably have one already, but just in case:

@gitpoap-bot @ItsNickBarry deserves a gitpoap
