### ISSUE TITLE
@nomiclabs/hardhat-etherscan: Source code exceeds max accepted (500k chars) length

### ISSUE THREAD

**Issue by GopherJ** [NomicFoundation/hardhat#3363]
ref: https://github.com/NomicFoundation/hardhat/issues/2475

**Comment by GopherJ** [comment]
FYI, I dont have hardhat-deploy, the contract doesn't have any constructor parameters  and we use hardhat factory for the deployment. I've gone through all the issues but didn't find a solution

**Comment by GopherJ** [comment]
Many unresolved issues are closed. Not sure if it's a good practice.

**Comment by fvictorio** [comment]
@GopherJ can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? I guess I can just deploy a huge contract and try to verify it, but having an MRE would be ideal.

> Many unresolved issues are closed. Not sure if it's a good practice.

We experimented for a whle with auto-closing old issues, which probably resulted in some valid issues being closed. It was a mistake and we are not doing it anymore.

**Comment by fvictorio** [comment]
I'm going to close this until we have a reproduction example. I would like to look into this though, so I'll happily re-open it when someone can provide that.
