### ISSUE TITLE
[Chai Matchers] Error when chai-matchers are used with `chai`, `chai-ethers` and `@types/chai`

### ISSUE THREAD

**Issue by 0xdavinchee** [NomicFoundation/hardhat#3364]
Versions: 
```
"@nomicfoundation/hardhat-chai-matchers": "^1.0.4",
"hardhat": "^2.12.2",
"@types/chai": "^4.3.4",
"chai": "^4.3.7",
"chai-ethers": "^0.0.1",
```

Note that I think that there are issues with types as a result of having both of these and they interfere with each other. The solution for me was to simply remove:

```
"@types/chai": "^4.3.4",
"chai": "^4.3.7",
"chai-ethers": "^0.0.1",
```

**Comment by fvictorio** [comment]
Hi @0xdavinchee, thanks for letting us know.

From what I can tell, chai-ethers is a kind of fork of waffle so it won't be compatible with our matchers. Plus, it doesn't seem to be maintained anymore.

I'm going to close this because I don't think there's much we can do here.
