### ISSUE TITLE
Hardhat test environment uses wrong chainId

### ISSUE THREAD

**Issue by izcoser** [NomicFoundation/hardhat#3366]
Hi everyone.
I am forking Arbitrum mainnet through Alchemy and in my hardhat config I set the chainId accordingly.
However when running hardhat test and impersonating someone, technique shown in the docs, the provider associated with that signer is still on chainId 31337, despite the fact that I set chainId 42161.
This causes bugs when dealing with contracts that check for signatures, as they use the chainId.
Is this expected behavior?
Thank you.

**Comment by fvictorio** [comment]
@izcoser can you share the relevant parts of your Hardhat config? (Don't include private information like API keys or private keys)

**Comment by fvictorio** [comment]
I think chainId should be under `networks.hardhat`, not under `networks.hardhat.forking`. Can you try that?

**Comment by fvictorio** [comment]
Closing for lack of response.
