### ISSUE TITLE
Forking mainnet and getBlockNumber

### ISSUE THREAD

**Issue by viktorcortess** [NomicFoundation/hardhat#3374]
Hello. Last days I'm trying to check how my project would work with block from the past. And I decided to check the blocknumber that I have forking mainnet in Hardhat. As I see in docs hardhat forks the latest block : "Hardhat Network will by default fork from the latest mainnet block". But what I received:

```
const provider = new ethers.providers.JsonRpcProvider("https://mainnet.infura.io/v3/%22);

const { ethers } = require("hardhat")

block = await provider.getBlockNumber()
```
16034315 from provider.getBlockNumber //current block from provider

`block = await ethers.provider.getBlockNumber()`
16034309 from ethers.provider.getBlockNumber // minus 6 blocks

And if I understand it correctly `ethers.provider.getBlockNumber()` shows a forking mainnet.
Why do I have this difference in 6 blocks if I didn't pin a block from the past?

**Comment by fvictorio** [comment]
Good question, that part of the docs is a bit misleading. We actually fork the latest block minus [some value](https://github.com/NomicFoundation/hardhat/blob/421898ea284ef323bc0d9d00c73d0c750051b810/packages/hardhat-core/src/internal/hardhat-network/provider/utils/reorgs-protection.ts#L8) (that depends on the network) to avoid reorg issues.

Do you think that sentence would be more accurate if it said something like "Hardhat Network will by default fork from a recent mainnet block"?

**Comment by viktorcortess** [comment]
Thanks for your answer. I asked the same question in discord yesterday, but nobody knew for sure why does this difference exist. Yes recent would be better, I'm sure that many people think that latest means current block.

**Comment by fvictorio** [comment]
Thank you!
