### ISSUE TITLE
Can't send ETH to contract  in Hardhat node using Metamask

### ISSUE THREAD

**Issue by RedHeadphone** [NomicFoundation/hardhat#3380]
The solidity code of contract

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;


contract Test {
    receive() external payable {   
    }
}
```

Created network using command `npx hardhat node`, deployed above contract in that network. After that when I try to send ETH to the contract, by loading one of the hardhat node Accounts into the Metamask it gives me "Error: Transaction reverted: function selector was not recognized and there's no fallback function"

![image](https://user-images.githubusercontent.com/55500003/204329619-89fd838b-c180-4f12-94d3-52720fd5968e.png)
![image](https://user-images.githubusercontent.com/55500003/204329707-9cca4431-faa6-41d6-86fa-8a7d0f98a6e0.png)

when I tried to send token using following script it worked

```
const test = await hre.ethers.getContractAt("Test","0x5fbdb2315678afecb367f032d93f642f64180aa3");
const [owner, addr1, addr2] = await hre.ethers.getSigners();
owner.sendTransaction({from: owner.address, to: test.address, value: hre.ethers.utils.parseEther("1.0")});
```

![image](https://user-images.githubusercontent.com/55500003/204329979-73636938-8249-4842-b296-7806856b35da.png)

but even here there is "unrecognized-selector"

**Comment by RedHeadphone** [comment]
I changed contract to following
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;


contract Test {
    receive() external payable {   
    }
    fallback() external payable {
    }
}
```

and started getting this new error "TransactionExecutionError: Transaction ran out of gas"
![image](https://user-images.githubusercontent.com/55500003/204353734-8fffee73-8ea7-4c80-9df8-b32db506a18c.png)

@fvictorio

**Comment by RedHeadphone** [comment]
No chainId in Metamask is same as configured in hardhat, Also transfer between wallet works @fvictorio 
Try recreating the setup.

**Comment by RedHeadphone** [comment]
> I did, and I was able to send the transaction.
Can you send send your metamask and hardhat version

**Comment by fvictorio** [comment]
Metamask: 10.22.1
Hardhat: 2.12.2
Solc: 0.8.13

**Comment by RedHeadphone** [comment]
> Metamask: 10.22.1 Hardhat: 2.12.2 Solc: 0.8.13

@fvictorio I have same configuration and version, still I am getting error. Can you share exact step by step how you recreated my scenario

**Comment by fvictorio** [comment]
Ugh, sorry, I forgot to mention that Metamask for some reason is not estimating the gas correctly, so I also had to modify the gas limit to be higher (30_000 is enough IIRC).

This seems to be a bug in Metamask, because no `eth_estimateGas` are received by the node.

**Comment by RedHeadphone** [comment]
But the error I received was this
![image](https://user-images.githubusercontent.com/55500003/204717538-2afb7782-906b-4d3e-8478-d88b36efd8ba.png)
I didn't get different chainID error or low gas error.
When you tried this first did you get this error?
