### ISSUE TITLE
Allow plugins to declare themselves via a `buidler` field in their package.json

### ISSUE THREAD

**Issue by cgewecke** [NomicFoundation/hardhat#339]
I help maintain [solidity-coverage](https://github.com/sc-forks/solidity-coverage) and we are contemplating a substantial [rewrite](https://github.com/sc-forks/solidity-coverage/issues/346) over the next couple of months. I'd like to make the new version available as a buidler plugin (multi-platform accessibility is a [long-standing issue](https://github.com/sc-forks/solidity-coverage/issues/216) at SC), but I'd also like to export its sub-components in an `index.js` so people can write:
```javascript
const coverage = require("solidity-coverage");
```
and do whatever they want with those pieces. Additionally it might be easiest if we didn't have to maintain different modules for each development platform we integrate with. 

Buidler loads plugins from their package `main` 
```
"main": "dist/src/index.js",
```

Would you be open to allowing plugins to declare something like a 'buidler' field in their package.json as an alternative to `main`?

**Comment by alcuadrado** [comment]
I'm glad to see that solidity-coverage is getting updated! Thanks for working on it :)

This is a very interesting idea and should be fairly easy to implement. I will do some research about using custom entries on `package.json`, but on a first glance, it doesn't seem problematic.

**Comment by fvictorio** [comment]
Closing this because I don't think is possible with Hardhat's plugin system.
