### ISSUE TITLE
The flatten task results are not deterministic

### ISSUE THREAD

**Issue by ByteGreen** [NomicFoundation/hardhat#3390]
**The generated file of `flatten` is difference between two times `flatten`.**

I use  `npx hardhat flatten xxx.sol > xxx_flat.sol` generate flat sol file.

But I run this command tow or more times,  the generated file is difference.

xxx.sol isn't changed.

Dependece File is unordered.

i'm sorry, my english is weak.

**Comment by alcuadrado** [comment]
Thanks for catching this error, @ByteGreen!

@fvictorio this seems like another instance of #1090
