### ISSUE TITLE
reported blocktime.timestamp on localhost hardhat node is not close to real UTC time.

### ISSUE THREAD

**Issue by grapevinegizmos** [NomicFoundation/hardhat#3396]
I am attempting to determine whether or not a transaction is occurring within a known interval from current blocktime.  I understand that block.timestamp is not precise, but it should be accurate to at least the interval between blocks written to the chain (about 8 minutes +/- perhaps).  I am only looking to compare actual time to blocktime within a range of about 1 hour, so that shouldn't be a problem.    But block.timestamp reported on a local node running in my terminal reports block.timestamp as much as 40 hours different than UTC. I am not sure how the node calculates the block.timestamp when the node is running for a locally for a long time, but very few transactions are processed,  but it would be good if  the hardhat node was reporting time similar to what a live blockchain would report, so I can test smart contract functions which check time based on a range around the reported block.timestamp.  (i.e. closer to the real world experience.)

**Comment by fvictorio** [comment]
@grapevinegizmos how can I reproduce this? Does this only happen when you have a long-lived Hardhat node? How often are you mining new blocks? Also, are you using interval mining?

**Comment by grapevinegizmos** [comment]
I suspect it has soemthing to do with a long lived node, yes.  Like if I leave then node running in the terminal, and then don’t execute any writable transactions for 24 hours or something, I think somehow the blocktime doesn’t update, because no transaction has required a write?

I’m not certain that’s what I makes it happen but it seems to happen regularly when I leave the node idle for a long period of time.


From: Franco Victorio ***@***.***>
Reply-To: NomicFoundation/hardhat ***@***.***>
Date: Monday, December 5, 2022 at 1:25 AM
To: NomicFoundation/hardhat ***@***.***>
Cc: Josh Kramer ***@***.***>, Mention ***@***.***>
Subject: Re: [NomicFoundation/hardhat] reported blocktime.timestamp on localhost hardhat node is not close to real UTC time. (Issue #3396)


@grapevinegizmos<https://github.com/grapevinegizmos> how can I reproduce this? Does this only happen when you have a long-lived Hardhat node? How often are you mining new blocks? Also, are you using interval mining?

**Comment by grapevinegizmos** [comment]
Having trouble reproducing -- closing
