### ISSUE TITLE
Strange code size too large error

### ISSUE THREAD

**Issue by 0xdavinchee** [NomicFoundation/hardhat#3404]
Commit: https://github.com/superfluid-finance/protocol-monorepo/commit/677048c5819900bbac3f5a0eefd31f0807a8d77b#diff-86c81041870e5b8a71779503041e9e4b65805426e763829d48e99a8e707ea8a2R799-R804

To reproduce:
- git clone the monorepo
- do yarn install && yarn build
- cd into packages/sdk-core and run `yarn test`
- it will revert with: "Transaction reverted: trying to deploy a contract whose code is too large"

I have tried setting `allowUnlimitedContractSize` to true and it still breaks.

So from what I can tell, this is occurring when I try to deploy a contract which is **`120894`** bytes.

This is understandable given that the size of the contract exceeds the 24kb maximum contract size constraint. 

However, the previous size of the contract was: **`120709`** and there were no errors being thrown even though `allowUnlimitedContractSize` was unset (`false` by default).

The highlighted code linked above leads to this error, if you comment out the code, the code size is reduced and it works as expected again, even though the code size is still well above the limit.

**Comment by fvictorio** [comment]
> However, the previous size of the contract was: **`120709`** and there were no errors being thrown even though `allowUnlimitedContractSize` was unset (`false` by default).

My guess is this: the contract size limit is about the size of a _deployed_ contract, not the _deployment_ contract. The latter can be bigger than 24K as long as the resulting, deployed bytecode is under that limit.

But the deployment bytecode cannot exceed the block gas limit of the block. I think that's what's going on here. Try increasing the `blockGasLimit` in the Hardhat network config and see if that fixes it.

Of course, the error that Hardhat is returning to you is wrong. I'm going to open an issue about that.

**Comment by fvictorio** [comment]
I'm going to assume that that's the underlying reason here, and close this one in favor of #3420.

**Comment by 0xdavinchee** [comment]
just saw this-thank you!
