### ISSUE TITLE
Making contribution/PR

### ISSUE THREAD

**Issue by junqinghua** [NomicFoundation/hardhat#3409]
Hi, I'm really interested in this project and I would like to make some contribution for this community.

As a Chinese software engineer, I'm thinking maybe I can make a Chinese language version of README so that more people in the world can get a better understanding of this project.

If you guys think its a good idea, I will start translating right away! Otherwise let me know and that's all fine for me.

Thankyou!

**Comment by fvictorio** [comment]
Closing this for bookkeeping reasons, but we can continue talking about this in #3413.
