### ISSUE TITLE
"Sorry you have been blocked" when attempting to verify contract on PolygonScan

### ISSUE THREAD

**Issue by grapevinegizmos** [NomicFoundation/hardhat#3425]
Hi I'm running a script to verify a contract deployed to Polygon Mumbai:

Here's the script:

```
async function main() {
    console.log("foo");
    await hardhat.run("verify:verify", {
        address: '0xf6943e4E99f27a2A4E49C7Af51CB252eFBcf9B1A',
        constructorArguments: [
            'Foo',
            'FOO',
            { 
              id: "AB9C939X",
              name: 'Foo', 
              symbol: 'FOO', 
              publisher: '0x59F5B98D5b5fc01c8aE10238b93618053E62BE20', 
              royaltyAccount: '0x59F5B98D5b5fc01c8aE10238b93618053E62BE20', 
              royaltyBasisPoints: 0,
              editionLimit: 10, 
              premint: 'false',
              licenseAddress: '0x7A843257128b46C757B89a49b3495A45e43219f8', 
              rootTemplateName: 'bknft_agreement_template.0.0.1', 
              requiresSignature: 'true', 
            },
            ['PrivateViewingEntitlement'],
        ]
    })
}
```

I've tried two different api keys, it keeps returning
```
NomicLabsHardhatPluginError: Failed to send contract verification request.
Endpoint URL: https://api-testnet.polygonscan.com/api
The HTTP server response is not ok. Status code: 403 Response text: <!DOCTYPE html>
````
And then a webpage that looks like this:
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/8684037/207523490-719af2fd-8088-4cdd-b4fb-5b8ca99a15af.png">

No obvious way for me to contact Polyganscan directly to ask them, so any ideas you might have would be great.

**Comment by grapevinegizmos** [comment]
I am hoping that there is some kind of workaround for this problem possible from NomicLabs -- not with respect to the cloudflare block but alternate ways to get my contract verified..

A few things -- I have determined that it not my particular IP address that is being blocked, it something about either the script or the contract.  I have been able to successfully verify other contracts using the normal command line syntax

I was attempting to see if I could use the command line syntax to validate the contract in question (0x6B5daC3c722B799967480824e216fCfa26597c6a( (origianlly authored in Hardhat), but the command line does not appear to have any means for entering tuples as constructor argument on the command line., and one of the constructor argument is a struct.  As far as I can tell from other issues here what that problem is mentioned, there doesn't seem to be any method of encoding structs to use the command line form `hh verify [contract address] constructor args'

But maybe there is a workaround?  I have been able successfully verify other contracts on the command line.

The other approach I was trying was to use the webform on ehterscan, but that form requires a flattened version of the file because it refers to more than 10 other contracts.    And unforunately flatten doesn't work on my contract because it has cyclic dependencies.  Those dependencies don't interfere with the operation of the contract which works fine, but they do prevent me from using the flattener tool.  Its also true that cyclic dependencies are not a blocker to verification:  contracts which contain them are verified without issue using the command line tool.  (See examples here:  0x70A3DB6b7C748631E1cec30aE15E3f2c46F85EbF & 0xeda45fb71013167E88587db0aFd6030Dc9C86572 on polygon mumbai -- these two depend on each other, and i verified using hh verify)

The graph is quite deep on this contract, I think there are something like 12 contracts involved (including several open Zep  conxtracts) so I seem to be stymied on that path as well.  

Unless perhaps you can tell me if its possible to manually produce a flattened version notwithstanding the cyclic dependencies (and the fact that the spx license is different between some of these contracts which seems to upset the hardhat compiler.)

 If it wasn't critical that I be able to verify, I would just let it go, but unforunately I need verification for my clients.

Thanks.  In the meanwhile I will continue to pursue etherscan to see if they can help me identify the cause of the cloudflare block.  Many thanks.



The script I tried:

async function main() {
    console.log("foo");
    await hardhat.run("verify:verify", {
        address: '0x6B5daC3c722B799967480824e216fCfa26597c6a',
        constructorArguments: [
            'Stack',//'Foo',
            'hill',//"FOO"',
            { 
              id: "AB9C939X",
              name: 'Nonce', //Foo', 
              symbol: 'GMD', //FOO 
              publisher: '0x59F5B98D5b5fc01c8aE10238b93618053E62BE20', 
              royaltyAccount: '0x59F5B98D5b5fc01c8aE10238b93618053E62BE20', 
              royaltyBasisPoints: 0,
              editionLimit: 10, 
              premint: 'false',
              licenseAddress: '0x7A843257128b46C757B89a49b3495A45e43219f8', 
              rootTemplateName: 'bknft_agreement_template.0.0.1', 
              requiresSignature: 'true', 
            },
            ['PrivateViewingEntitlement'],
        ]
    })
}

**Comment by fvictorio** [comment]
> but the command line does not appear to have any means for entering tuples as constructor argument on the command line.

https://hardhat.org/hardhat-runner/plugins/nomiclabs-hardhat-etherscan#complex-arguments

**Comment by grapevinegizmos** [comment]
I'm well aware of this option Franco.   In my comment above you can see that I used this technique for complex arguments in my verify script.   My question was whether there is a way to enter complex arguments directly on the command line -something like 'hh verify [address] "{name: "John smith", age: 42}".  The script is what keeps getting blocked by cloud flare.  Running verify on the command line does not.
