### ISSUE TITLE
current npm installation approach for hardhat results in Error.

### ISSUE THREAD

**Issue by femo1olu** [NomicFoundation/hardhat#3431]
Error HH12: Trying to use a non-local installation of Hardhat, which is not supported. Please install Hardhat locally using npm or Yarn, and try again.

Until I installed from " npm install --save-dev @nomicfoundation/hardhat-toolbox"... before I was able to complete the example.

Good luck.

**Comment by fvictorio** [comment]
@femo1olu I'm not sure I understand. Can you tell what you did to get that error? What do you mean by "current npm installation approach"? Were you following our docs or some other resource?

**Comment by femo1olu** [comment]
Hi,Yes I followed the steps outlined. But running "npx hardhat" failed with the Error I shared instead of showing me the tasks available.I had to get the package from a network before I could make progress.Thanks,Femi

Sent from Yahoo Mail on Android 
 
  On Thu, Dec 15, 2022 at 2:09 PM, Franco ***@***.***> wrote:   


@femo1olu I'm not sure I understand. Can you tell what you did to get that error? What do you mean by "current npm installation approach"? Were you following our docs or some other resource?

**Comment by 4everme** [comment]
did you figure this out?

**Comment by 4everme** [comment]
I believe it is a simple fix , use this video to guide you : https://www.google.com/search?q=code+to+install+nmp+install+hardhat&rlz=1C1CHBF_enUS952US952&oq=code+to+install+nmp+install+hardhat&aqs=chrome..69i57j33i10i160.10364j0j7&sourceid=chrome&ie=UTF-8#kpvalbx=_Kg-jY8nHNMCK0PEPwcGD8A0_27

**Comment by fvictorio** [comment]
I'm not sure what to do about this issue, to be honest. I think the instructions in our docs are correct, and that the error message when this happens for some reason are clear enough. If someone can clearly show that there are misleading instructions in our docs, or think that the error message can be improved, please comment here or open a new issue.
