### ISSUE TITLE
Sorting issue with compilation on MacOS 

### ISSUE THREAD

**Issue by Korkey128k** [NomicFoundation/hardhat#3434]
There's a sorting issue when compiling a multi-file project in version `2.12.2` that does not exist in version `2.12.1` on my machine.

I've created a minimal hardhat project to demonstrate the difference. 
https://github.com/Korkey128k/hardhat_v2.12.2-sorting-issue/tags

You'll see under each tag that the `artifacts/build-info` `json` file has the two sources flipped.
Version `2.12.1` is correct while `2.12.2` places the library file before the main file.

Using node `v18.12.1`

**Comment by fvictorio** [comment]
@Korkey128k in version [2.12.2](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.12.2) we fixed a problem that was causing build info files (and therefore their hash-based names) to not be deterministic. This means that, starting from that version, sources in build infos are sorted.

Is there a reason why this is a problem for you? If it is, please tell me more about your use case and maybe we can find a workaround.

**Comment by Korkey128k** [comment]
Yes; if the main file has a signature or some other kind of identifier, it’d be preferable if it was displayed first on blockchain explorers when you verify the contract.  
Also it improves readability of the contract if libraries are listed in an order that makes sense for the particular contract.  

When troubleshooting this originally, I was hoping that I could specify the order using the `solidity` configuration in `hardhat.config.ts` but I couldn’t make sense of the solidity documentation and/or how it affected hardhat’s output of the contracts. Could there be a way to set it there?

**Comment by Korkey128k** [comment]
I’d also like to point out that I went with Remix (*it had the correct order*) recently to compile a contract for this specific reason.

**Comment by fvictorio** [comment]
I don't think there's a "correct' order, unless I'm missing something. But I do see your point about the order of the contracts having an impact on the readability of the verified contracts. Let me think about that.

**Comment by fvictorio** [comment]
Hey @Korkey128k, I think something doable and reasonable that we can do is to modify the `hardhat-etherscan` plugin so that the source of the verified contract is the first one to show up in the Etherscan contract code page. Do you think this would be enough?

More generally, I think we could do something so that you can provide a sorting function that lets you define the order of the shown contracts. But this is a bit harder to do and less valuable IMO.

**Comment by fvictorio** [comment]
Closing this in favor of #3455, which is only about showing the file of the verified contract first.
