### ISSUE TITLE
Transaction may fail or may require manual gas limit

### ISSUE THREAD

**Issue by joelamouche** [NomicFoundation/hardhat#3457]
I am using `await expect(programs.store(55)).to.be.reverted` with the following function:

```
    function store(uint256 newValue) public onlyOwner {
        value = newValue;
        emit ValueChanged(newValue);
    }
```

`onlyOwner` comes from `@openzeppelin/contracts/access/Ownable.sol`

I am expecting it to revert with "Ownable: caller is not the owner" but instead it says:

```
     Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"name":"ProviderError","_stack":"ProviderError: HttpProviderError\n    at HttpProvider.request (/Users/antoineestienne/Github_Files/contracts/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)\n    at AutomaticSenderProvider.request (/Users/antoineestienne/Github_Files/contracts/node_modules/hardhat/src/internal/core/providers/accounts.ts:344:34)\n    at AutomaticGasProvider.request (/Users/antoineestienne/Github_Files/contracts/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:135:34)\n    at FixedGasPriceProvider.request (/Users/antoineestienne/Github_Files/contracts/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:54:34)\n    at BackwardsCompatibilityProviderAdapter.send (/Users/antoineestienne/Github_Files/contracts/node_modules/hardhat/src/internal/core/providers/backwards-compatibility.ts:36:27)\n    at EthersProviderWrapper.send (/Users/antoineestienne/Github_Files/contracts/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:48)\n    at EthersProviderWrapper.<anonymous> (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:640:31)\n    at step (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)\n    at Object.next (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)\n    at /Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:23:71\n    at new Promise (<anonymous>)\n    at __awaiter (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:19:12)\n    at EthersProviderWrapper.JsonRpcProvider.perform (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:720:16)\n    at EthersProviderWrapper.<anonymous> (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1738:35)\n    at step (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/lib/base-provider.js:48:23)\n    at Object.next (/Users/antoineestienne/Github_Files/contracts/node_modules/@ethersproject/providers/lib/base-provider.js:29:53)","code":-32000,"_isProviderError":true,"data":{"stack":"RuntimeError: VM Exception while processing transaction: revert Ownable: caller is not the owner\n    at Function.RuntimeError.fromResults (/Users/antoineestienne/Github_Files/contracts/node_modules/ganache-core/lib/utils/runtimeerror.js:94:13)\n    at module.exports (/Users/antoineestienne/Github_Files/contracts/node_modules/ganache-core/lib/utils/gas/guestimation.js:142:32)","name":"RuntimeError"}}, method="estimateGas", transaction={"from":"0xB3a3d099Fb8107Ef20D1C05Cc77a70c835B17d61","to":"0xd8A1F31905F526CCeca3C873A2822d06C7Ba4d63","data":"0x6057361d0000000000000000000000000000000000000000000000000000000000000037","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
```

**Comment by fvictorio** [comment]
@joelamouche are you using the latest versions of Hardhat, ethers and the Chai Matchers plugin?

**Comment by joelamouche** [comment]
Yes :
    "ethers": "^5.7.2",
    "hardhat": "^2.12.5",
    "@nomicfoundation/hardhat-chai-matchers": "^1.0.5",

**Comment by joelamouche** [comment]
Oh sorry I forgot to mention something important: I am using `npx hardhat  --network ganache test` with     "@nomiclabs/hardhat-ganache": "^2.0.1",

**Comment by fvictorio** [comment]
Oh, sorry, the Hardhat Chai Matchers are only meant to be used with the Hardhat network :slightly_frowning_face:

Maybe there are some things Ganache could do to work with our matchers, but we should discuss that on their issue tracker. Feel free to tag me if you open an issue for that.

**Comment by antoine-dowgo** [comment]
@fvictorio 
Okay but if I wrap the call in a try catch:
````
const Programs = await ethers.getContractFactory("Programs");
const programs = (await Programs.deploy()) as Programs;
try{
  await programs.store(55)
} catch(e){
  console.log(e)
}
````

I still get
` Error: cannot estimate gas; transaction may fail or may require manual gas limit`

Which means that the hardhat version of ethers runs estimateGas and that's a problem because I can't get the revert reason, even manually

**Comment by fvictorio** [comment]
@antoine-dowgo I'm not sure I follow. That's ethers default behavior if you don't pass a `gasLimit` value, isn't it? I don't think our version of ethers does anything different.

**Comment by antoine-dowgo** [comment]
I don't think it's about the gas limit but rather about the "may fail'.
I think the hardhat verison of the contract run gas estimation which verifies wether the call with revert or not. Since the call is supposed to revert, it throws this error. But the problem is that I don't get the error message.

If I run the exact same test with hardhat testnet I get `Error: VM Exception while processing transaction: reverted with reason string 'Ownable: caller is not the owner'`

**Comment by fvictorio** [comment]
Oh, I see what's going on. The in-process Hardhat network, by default, sets the transactions gas limits to the value of the block gas limit. This means that ethers doesn't perform a gas estimation and you get that error. If you change your settings to:

```
networks: {
  hardhat: {
    gas: "auto"
  }
}
```

then ethers will perform a gas estimation and you'll get the same result for Hardhat and for external networks.

If you want to get the same behavior in both networks you have to either 1) set Hardhat's gas behavior to `"auto"` (as shown in the previous snippet), in which case you will get the "cannot estimate gas" error from ethers or 2) set the `gas` entry in the `ganache` network config to a fixed value.

**Comment by antoine-dowgo** [comment]
OKay thanks so If I set it to 1M it does throw this error: `Error: missing revert data in call exception; Transaction reverted without a reason string` which is a progress. Butt how do I change the setting for `@nomiclabs/hardhat-ganache`?
The instructions here https://hardhat.org/hardhat-runner/plugins/nomiclabs-hardhat-ganache don't work of are not up to date

**Comment by fvictorio** [comment]
Try something like this:

```
    ganache: {
      url: "http://localhost:8545",
      gas: 30_000_000,
      gasLimit: 30_000_000,
    }
```

`gasLimit` will configure the block gas limit of the ganache network that the plugin starts. `gas` should configure the default gas sent in each transaction.

**Comment by antoine-dowgo** [comment]
Wow thanks not only does it work but it even logs the revert reason :D
HOwever I had to add `@ts-ignore` : 

````
ganache: {
      url: "http://localhost:8545",
      gas: 30_000_000,
      //@ts-ignore
      gasLimit: 30_000_000,
    },
````

The typings are not up to date it seems
