### ISSUE TITLE
`evm_mine` not adding block reward to the miner's balance

### ISSUE THREAD

**Issue by kushalbabel** [NomicFoundation/hardhat#3460]
Version 2.9.9 adds block reward to the miner's balance upon calling evm_mine
Version 2.12.2 does not do so. 
Is this a bug, or a planned backward incompatible change? What is the rationale here? Thanks

**Comment by fvictorio** [comment]
Confirmed. Thanks for reporting @kushalbabel!

**Comment by kushalbabel** [comment]
Thanks @fvictorio for checking. wondering if it can be moved to higher priority since it is indeed a breaking change at a high level.
