### ISSUE TITLE
Broken GitHub link in the docs

### ISSUE THREAD

**Issue by ilovehackathons** [NomicFoundation/hardhat#3462]
I wanted to edit the [Hardhat errors](https://hardhat.org/hardhat-runner/docs/errors) page, but its [Help us improve this page](https://github.com/NomicFoundation/hardhat/edit/main/docs/src/content/hardhat-runner/docs/errors/index.md) link is broken:

<img width="738" alt="Hardhat errors page" src="https://user-images.githubusercontent.com/106395723/209523127-3c9b8a18-ed83-4e55-b794-4b888a3b8317.png">

<img width="883" alt="404" src="https://user-images.githubusercontent.com/106395723/209523269-f47c46b9-7686-4a37-8d6e-0ac3d6d1ab5c.png">

**Comment by fvictorio** [comment]
Great catch, thank you!
