### ISSUE TITLE
Improve error message when a directory is imported

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#3490]
If you do something like (notice that it's a directory and not a file):

```
import "@openzeppelin/contracts/proxy";
```

you get this error:

```
An unexpected error occurred:

[Error: EISDIR: illegal operation on a directory, read] {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
```

We should show a better error in these cases.

**Comment by mwawrusch** [comment]
This should bumped in priority. I have a project with 50+ contracts. Will take forever to figure out what the problem is.

**Comment by alcuadrado** [comment]
@fvictorio this could be a good issue to introduce someone to HH's codebase.
