### ISSUE TITLE
Unable to import OpenZeppelin contracts to Hardhat 

### ISSUE THREAD

**Issue by GratefulLion21** [NomicFoundation/hardhat#3495]
When I try npm install @openzeppelin/contracts or npm install @openzeppelin/contracts@0.8.7 

I continue to get error these error messages, it looks like i need to update but not sure. 

<img width="1095" alt="Screen Shot 2022-12-29 at 10 14 03 AM" src="https://user-images.githubusercontent.com/77343843/209973886-9576ea9a-ef96-48c9-9092-3961145af45d.png">

<img width="909" alt="Screen Shot 2022-12-29 at 10 15 08 AM" src="https://user-images.githubusercontent.com/77343843/209973945-b1e9faa2-b029-4ccf-9a42-d0e35325350c.png">

**Comment by fvictorio** [comment]
Can you share all the dependencies in your `package.json`?

**Comment by GratefulLion21** [comment]
Yes package.json below:

<img width="738" alt="Screen Shot 2022-12-29 at 12 26 07 PM" src="https://user-images.githubusercontent.com/77343843/209988497-ac69589d-8b4c-49b6-a506-fb4695c8c992.png">

**Comment by GratefulLion21** [comment]
Thanks for replying I added the details in the forum.

**Comment by GratefulLion21** [comment]
Thank you for your email Franco,

I added the details in the Forum.

Please let me know.

**Comment by fvictorio** [comment]
`hardhat-deploy-ethers` is not compatible with `@nomicfoundation/hardhat-toolbox`. We are working on fixing that, but for now you'll have to uninstall one of those.

**Comment by GratefulLion21** [comment]
Thanks fvictorio 

That did the trick here is the output once I removed hardhat -deploy-ethers 
Is there anything I should do as a next step based on the output response 

<img width="575" alt="Screen Shot 2022-12-29 at 2 07 39 PM" src="https://user-images.githubusercontent.com/77343843/209998934-a45db2b0-5623-42dc-979c-3daa8ddcb5ed.png">

**Comment by fvictorio** [comment]
No, you can ignore those for a Hardhat app. Read [this](https://overreacted.io/npm-audit-broken-by-design/) to learn more.
