### ISSUE TITLE
Getting error: network goerli doesn't exist

### ISSUE THREAD

**Issue by GratefulLion21** [NomicFoundation/hardhat#3497]
Getting error when trying code npx hardhat run --network goerli scripts/deploy.js or npx hardhat run script/deploy.js --network goerli

Terminal Error:  Error HH100: Network goerli doesn't exist

HardHat.config.js:

<img width="535" alt="Screen Shot 2022-12-29 at 9 59 53 AM" src="https://user-images.githubusercontent.com/77343843/210007658-f50b48af-8fda-4078-938b-8ce5f9e978f8.png">

**Comment by fvictorio** [comment]
You have an error in your config. It should be:

```
hardhat: { ... }
goerli: { ... }
```

But your goerli config is inside the hardhat network config.

**Comment by GratefulLion21** [comment]
Thank you fvictorio. 

I'm a bit confused as I believe that I already have hardhat:{} & goerli:{} in place. 

Where would I find the hardhat network config file/folder as I'm unable to locate one. 

Please let me know.

**Comment by Sol-Devloper** [comment]
Try this, if your issue is not resolved:

module.exports = {
  defaultNetwork: "hardhat",
  networks: {
    goerli: {
      url: GOERLI_RPC_URL,
      accounts:[`0x${PRIVATE_KEY}`],
      chainID: 5,
    }
  },
  solidity: "0.8.8",
};
