### ISSUE TITLE
fork local erigon archive node failed

### ISSUE THREAD

**Issue by TangMonk** [NomicFoundation/hardhat#3509]
I have a local erigon archive mainnet node:

```
geth attach http://192.168.50.159:7546
Welcome to the Geth JavaScript console!

instance: erigon/2.30.0/linux-amd64/go1.18.1
at block: 16317128 (Mon Jan 02 2023 13:54:11 GMT+0800 (CST))
 modules: admin:1.0 debug:1.0 erigon:1.0 eth:1.0 net:1.0 rpc:1.0 trace:1.0 txpool:1.0 web3:1.0
```

However when I fork with my local node with failed: `npx hardhat node --fork http://192.168.50.159:7546 --port 8548`:

```
Error HH604: Error running JSON-RPC server: read ECONNRESET
```

**Comment by fvictorio** [comment]
@TangMonk that's a connection error, are you sure the node is available?

Try doing:

```
curl -s -X POST -H 'Content-Type: application/json' --data '{"jsonrpc": "2.0", "id": 1, "method": "eth_blockNumber", "params": []}' http://192.168.50.159:7546
```

**Comment by TangMonk** [comment]
@fvictorio I am sure the node is avaliable, I have tried run `npx hardhat node --fork http://192.168.50.159:7546 --port 8548` multiple times, it works. 

Sometimes I tried run `npx hardhat node` once and it works, sometimes twice, sometime third times. 

So it is seems random and weird to work

**Comment by TangMonk** [comment]
And please check this screen record(I have tried few times, and it works):

https://user-images.githubusercontent.com/3498786/210243145-b8acacad-3f37-4598-a05a-16e55b44be0a.mov

**Comment by fvictorio** [comment]
Ugh, sorry, I just realized that your first snippet was already showing that the node was available.

Do you know if there's an easy way for me to reproduce this without having to sync a node? AFAIK erigon doesn't have a `--dev` flag like geth has.

**Comment by fvictorio** [comment]
Closing until we have some easy way to reproduce.
