### ISSUE TITLE
Replace yarn with pnpm

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#3521]
- [ ] Use pnpm as our package manager
- [ ] Remove all usages of yarn in scripts, CI, contributing docs, etc.

**Comment by Confucian-e** [comment]
pnpm is good, but considering bun as well?

**Comment by Confucian-e** [comment]
> Not really. Changing the package manager is one thing, but moving to a different runtime would be a huge breaking change that we are not considering right now.

Thanks and good luck
