### ISSUE TITLE
Reduce warnings during sample project installation

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#3525]
Most warnings come from third-party plugins (solidity-coverage and gas-reporter). If we update some dependencies in those repos, the warnings will go away.

According to @alcuadrado, this is what we need to do:

```
soldity-coverage > detect-port (Upgrade / Vendor as its tiny and pulls deps)
solidity-coverage > @truffle/provider (Replace)
hardhat-gas-reporter > eth-gas-reporter > mocha (Upgrade)
hardhat-gas-reporter > eth-gas-reporter > request-promise-native (Replace)
hardhat-gas-reporter > eth-gas-reporter > request (Replace)
```

TODO:

eth-gas-reporter package:
- bump ethers version: https://github.com/cgewecke/eth-gas-reporter/pull/296
- request: it seems that the request package is not used, it should be removed: https://github.com/cgewecke/eth-gas-reporter/pull/297
- request-promise-native: https://github.com/cgewecke/eth-gas-reporter/pull/298

solidity-coverage:
- update mocha version: [https://github.com/sc-forks/solidity-coverage/pull/810](https://github.com/sc-forks/solidity-coverage/pull/810)

After these changes the packages with the newer and correct versions should be automatically downloaded during the installation.

**Comment by ChristopherDedominici** [comment]
External PRs have been merged and the warnings are no longer appearing during the sample project installation.
