### ISSUE TITLE
Support creating project using pnpm as the package manager

### ISSUE THREAD

**Issue by Hopsken** [NomicFoundation/hardhat#3549]
### Describe the feature

When initializing a hardhat project (with `hardhat` command) using pnpm, `hardhat` will still try to use `npm` to install dependencies which may be considered an issue.

Besides, `pnpm` by default wouldn't install peer dependencies unless `auto-install-peers` is [configured](https://pnpm.io/npmrc#auto-install-peers). It would be better if `hardhat` could prompt to help add those dependencies for the user if `auto-install-peers` is not enabled.

We may also need to update the docs showing how to use `pnpm` to create a hardhat project.

**Comment by fvictorio** [comment]
Thanks for opening this @Hopsken. Do you mind if we make this issue explicitly about installing dependencies with pnpm during project creation? We can open a separate issue for a pnpm guide, although I'm not sure how much content that would have.

With respect to using pnpm during the project creation, I think it should be fairly easy to do? I'll leave some notes in case you or someone else wants to give it a try.

We should add a `isPnpmProject` function similar to this one:

https://github.com/NomicFoundation/hardhat/blob/4d7f911a53fdde847b67a6024a8ebd896278e58a/packages/hardhat-core/src/internal/cli/project-creation.ts#L429-L431

And then use it here to generate the right params:

https://github.com/NomicFoundation/hardhat/blob/4d7f911a53fdde847b67a6024a8ebd896278e58a/packages/hardhat-core/src/internal/cli/project-creation.ts#L487-L500

This part of the code is not very testable, so we usually do it manually. There are some tips about testing local changes [here](https://github.com/NomicFoundation/hardhat/blob/main/CONTRIBUTING.md#developing-locally).

**Comment by Hopsken** [comment]
Thanks, @fvictorio. I would be happy to help implement this feature. It totally makes sense to separate docs changes to another issue.
