### ISSUE TITLE
@nomiclabs/hardhat-ganache : support getProof

### ISSUE THREAD

**Issue by joelamouche** [NomicFoundation/hardhat#3556]
### Describe the feature

It seems that even though ganache by itself does support getProof, the `@nomiclabs/hardhat-ganache` plugin does not support eth_getProof.

Maybe it needs to be updated? Thanks in advance

### Search terms

hardhat-ganache getProof

**Comment by fvictorio** [comment]
I guess the fix is to update the ganache dependency in the plugin. We are using `ganache-core` right now, but that has been deprecated and the `ganache` package should be used instead. This surely means some code changes too.

PRs welcome for this.

**Comment by antoine-dowgo** [comment]
I can give it a shot...

**Comment by joelamouche** [comment]
I can give it a shot...

**Comment by fvictorio** [comment]
Closing this since we removed the plugin from our repo.
