### ISSUE TITLE
Github Actions locked issues wont reopen after issue has been re-opened

### ISSUE THREAD

**Issue by sambacha** [NomicFoundation/hardhat#3557]
### Version of Hardhat

0.0.0

### What happened?

When the automated GitHub Actions bot closes a 'stale' issue, and an admin for the repo reopens the issue, the issue still remains locked to previous contributors to that issue before the inital closing of the issue. 

see https://github.com/NomicFoundation/hardhat/issues/2178 as an example of a reopened issue that is closed to new comments 

Also unsure if this qualifies as the proper category to file such reports as it is a 'bug' but not directly related to hardhat per se!

### Minimal reproduction steps

check out https://github.com/NomicFoundation/hardhat/issues/2178

**Comment by fvictorio** [comment]
Hey @sambacha, thanks for letting us know. I unlocked the conversation in that issue.

I think this can be solved by automation (every time an issue is re-opened, we also unlock it), but tbh I expect this to be a fairly infrequent thing, so I'll try to just, you know, remember to unlock conversations if I re-open an old issue.

To anyone reading this: if this happens again, feel free to open an issue saying "please unlock issue #X".

**Comment by sambacha** [comment]
> Hey @sambacha, thanks for letting us know. I unlocked the conversation in that issue.
> 
> 
> 
> I think this can be solved by automation (every time an issue is re-opened, we also unlock it), but tbh I expect this to be a fairly infrequent thing, so I'll try to just, you know, remember to unlock conversations if I re-open an old issue.
> 
> 
> 
> To anyone reading this: if this happens again, feel free to open an issue saying "please unlock issue #X".

💯🙏🫡
