### ISSUE TITLE
Init script doesn't work when set optional parameters like "gasPrice"

### ISSUE THREAD

**Issue by gfijrb** [NomicFoundation/hardhat#3567]
### Version of Hardhat

2.12.3

### What happened?

When I set any optional parameters to contract deploy method, script failed with this error

```bash
ProviderError: HttpProviderError
    at HttpProvider.request (/home/user/Desktop/project-A/node_modules/hardhat/src/internal/core/providers/http.ts:78:19)
    at LocalAccountsProvider.request (/home/user/Desktop/project-A/node_modules/hardhat/src/internal/core/providers/accounts.ts:187:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async EthersProviderWrapper.send (/home/user/Desktop/project-A/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)

```

But when optional parameters didn't changed, it works!

### Minimal reproduction steps

```typescript
import hre from "hardhat";
const ethers = hre.ethers;

async function main() {
    const [owner] = await ethers.getSigners();
    console.log(owner.address)

    const overridesOptions = {
        // maxFeePerGas: parseUnits('15', 9),
        // maxPriorityFeePerGas: parseUnits('1', 9)
        // or
        // gasPrice: parseUnits('5', 9)
    }
    
    const ERC20Mock = await ethers.getContractFactory("ERC20Mock");
    
    let token = await ERC20Mock.deploy(overridesOptions)
    await token.deployed()
    console.log(`Token: ${token.address}`)
}

// We recommend this pattern to be able to use async/await everywhere
// and properly handle errors.
main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error);
        process.exit(1);
    });
```

### Search terms

ProviderError: HttpProviderError when set optional parameter in init script

**Comment by fvictorio** [comment]
I guess you are connecting to some network when doing this, right? That is, you are not using the in-process hardhat network.

In that case, what's probably happening is that the gas price you are setting is lower than the base fee of the network you are connecting to. You _should've_ been shown a better error message though; that's a problem we are aware of and that is high on our priority list.

Closing this for now, but if that's not what happened, then I will need more complete reproduction steps.
