### ISSUE TITLE
Property 'revertedWithCustomError' does not exist on type 'Assertion'

### ISSUE THREAD

**Issue by advra** [NomicFoundation/hardhat#3580]
### Describe the feature

Im updating my project from Javascript to Typescript. Up until now I had no issues using `revertedWithCustomError`. When trying to assert with `revertedWithCustomError` I get the following linter error messaged "Property 'revertedWithCustomError' does not exist on type 'Assertion'."

The header imports in my TS look like:
```typescript
const ethers = require("ethers");
import { loadFixture } from "@nomicfoundation/hardhat-network-helpers";
import { expect } from "chai";
import { BigNumber, constants } from "ethers";
```
Here is an example test snippet:
```Tyypescript
    it("Should validate list errors 721", async function () {
      const { Marketplace, Rentable4907Nft, Rentable1155Nft, Rentable721Nft } = await loadFixture(deployFixture);
      await expect(marketplace.connect(USER).listNFT(
        marketplace.address, 
        BigNumber.from(1), 
        ethers.utils.parseEther("1"), 
        TOMORROW, IN_FIVE_DAYS, 
        { value: listingFee}
      )).to.be.revertedWithCustomError(marketplace, "UnsupportedNftInterface");
  });
```
What am I doing incorrectly? 

### Search terms

typescript revertedWithCustomError

**Comment by fvictorio** [comment]
@advra do you have a `tsconfig.json`? Can you share its contents?

**Comment by advra** [comment]
Hi this is my tsconfig.json
```
{
  "compilerOptions": {
    "target": "es2020",
    "module": "commonjs",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true
  },
  "exclude": ["dist", "node_modules"],
  "include": ["./src", "./scripts"],
  "files": ["./hardhat.config.ts"]
}
```

**Comment by advra** [comment]
Okay I fixed the issue. The documentation in the hardhat website uses `hre` since types arent shared globally like it is in javascript. The documentation shows [a test file imports](https://hardhat.org/hardhat-runner/docs/guides/test-contracts): 
```
import { expect } from "chai";
import hre from "hardhat";
import { time } from "@nomicfoundation/hardhat-network-helpers";
```

So my resulting code below works using hre:
```javascript
import { loadFixture } from "@nomicfoundation/hardhat-network-helpers";
import "@nomicfoundation/hardhat-chai-matchers"; //Added for revertWithCustomErrors
import { expect } from "chai";
import { BigNumber, constants } from "ethers";
import hre from "hardhat";

// within test code using hre.ethers
await expect(marketplace.connect(USER).listNFT(
    marketplace.address, 
    hre.ethers.utils.parseEther("1"), 
    { value: listingFee}
)).to.be.revertedWithCustomError(marketplace, "UnsupportedNftInterface");
```

Alternatively I found you can do this  import without hre like below though I am unsure of the correctness:
```javascript
import { ethers } from "hardhat";

// within test code using ethers
await expect(marketplace.connect(USER).listNFT(
    marketplace.address, 
    ethers.utils.parseEther("1"), 
    { value: listingFee}
)).to.be.revertedWithCustomError(marketplace, "UnsupportedNftInterface");
```

**Comment by fvictorio** [comment]
To clarify, it wasn't working for you before because you were not importing the `"hardhat"` module anywhere in your test? That makes sense, but at the same time I wonder how you managed to do anything in your test without using at least something from the HRE.

I also think that the reason might be related to the `include`/`exclude`/`files` fields in your tsconfig.json, but I'm not 100% sure. For the record, our recommended ts config is [here](https://hardhat.org/hardhat-runner/docs/guides/typescript#typescript-configuration).

I'm going to close this issue now because I'm not sure if there's something to do on our side. Please let me know if you disagree.

**Comment by doublesharp** [comment]
I had a conflict with `hardhat-waffle`, once it was removed with `import "@nomicfoundation/hardhat-chai-matchers";` in the Hardhat config file, all worked as expected.
