### ISSUE TITLE
Show a better error message than `HttpProviderError` when a transaction fails

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#3581]
When Hardhat is connected to a network and a transaction reverts, the error shown is just `HttpProviderError`. This is obviously not helpful at all.

In the case where the connected network is an instance of `hh node`, you can at least see the error there. But this is not a good experience: if the failure is not the last transaction sent, you have to guess which part of the node's output corresponds to the failed transaction.

This is even worse for testnets, since in this case you don't have any information at all.

This happens both when ethers is used and when raw JSON-RPC transactions are sent. And it happens for `eth_estimateGas`, `eth_call` and `eth_sendTransaction`

**Comment by alexanderattar** [comment]
Currently also running up against this issue when trying to deploy to local hardhat network. The `HttpProviderError` is not very illuminating of what the actual issue is and this has even been misleading
