### ISSUE TITLE
Task pre hook

### ISSUE THREAD

**Issue by sunliang711** [NomicFoundation/hardhat#3585]
### Describe the feature

Hello, I hava a lot of networks in hardhat.config.js, when I run a task, I pass --network <NETWORK> to specify a network, so I want to show the current network in console, how do I do to achieve this ? Is there anything like "pre hook" in hardhat ?

**Comment by fvictorio** [comment]
There aren't pre-hooks, but you can run some code before or after a task by overriding it and calling `runSuper`. Check [this example](https://github.com/fvictorio/hardhat-examples/tree/master/hooks) to learn more.
