### ISSUE TITLE
pnpx hardhat compile: Trying to use a non-local installation of Hardhat, which is not supported

### ISSUE THREAD

**Issue by fabianorodrigo** [NomicFoundation/hardhat#3588]
### Version of Hardhat

2.12.6

### What happened?

I've created a new project using pnpm/pnpx: 

```
pnpx hardhat
```
Besides some 'deprecated' warnings and this strange message log like if npm has been executed in spite of pnpm, everything seems fine `npm install --save-dev hardhat@^2.12.6 @nomicfoundation/hardhat-toolbox@^2.0.0`.

However, when I try to compile with `pnpx hardhat compile`, I got the error message: `HH12: Trying to use a non-local installation of Hardhat, which is not supported`.

The release v2.12.6 introduced the support to pnpm, didn't it?

### Minimal reproduction steps

> pnpx hardhat 
Choose Create a TypeScript project
> pnpx hardhat compile

### Search terms

pnpm

**Comment by fvictorio** [comment]
Hi @fabianorodrigo, I couldn't reproduce this. I used somewhat different steps because `pnpx` seems to be [deprecated](https://pnpm.io/6.x/pnpx-cli), but this is what I did:

```
pnpm init
pnpm install hardhat
pnpm exec hardhat # install stuf
pnpm exec hardhat compile
```

**Comment by fabianorodrigo** [comment]
@fvictorio , it works! I have no idea that `pnpx` was deprecated. 
Thank you very much!
