### ISSUE TITLE
unable to verify a contract in etherscan - goerli

### ISSUE THREAD

**Issue by rjoshig** [NomicFoundation/hardhat#3597]
I use hardhat-toolbox. I have been unable to verify a contract in etherscan. **The error is below and it happens only in goerli testnet**.
I am pretty sure I checked the arguments and such and this same deploy code worked about 10 days ago in gorli.

I can still deploy the same contract in bsctestnet and  verify it successfully which rules out any issues i have with the code. I double checked the  etherscan api key and even used a new apiKey for goerli.

```
Error in plugin @nomiclabs/hardhat-etherscan: The Etherscan API responded with a failure status.
The verification may still succeed but should be checked manually.
Reason: Fail - Unable to verify. Compiled contract runtime bytecode does NOT match the on-chain runtime bytecode.

For more info run Hardhat with --show-stack-traces
```

Any pointers? Could this be an issue with etherscan goerli testnet api itself?

**{Edit-adding additional info below]**
**Stack trace for the error is below:** 
```

Successfully submitted source code for contract
contracts/Source.sol:ContractName at 0xAexxxxxxxxxxxxxxxxxxxxx2baxx5xxxxxxxxxx
for verification on the block explorer. Waiting for verification result...


npx hardhat verify --contract contracts/Source.sol:ContractName --constructor-args arguments1.js "0xAexxxxxxxxxxxxxxxxxxxxx2baxx5xxxxxxxxxx"  --network goerli


Error in plugin @nomiclabs/hardhat-etherscan: The Etherscan API responded with a failure status.
The verification may still succeed but should be checked manually.
Reason: Fail - Unable to verify. Compiled contract runtime bytecode does NOT match the on-chain runtime bytecode.

NomicLabsHardhatPluginError: The Etherscan API responded with a failure status.
The verification may still succeed but should be checked manually.
Reason: Fail - Unable to verify. Compiled contract runtime bytecode does NOT match the on-chain runtime bytecode.
    at getVerificationStatus (/home/john/private/sandbox/eth/code_directory/node_modules/@nomiclabs/hardhat-etherscan/src/etherscan/EtherscanService.ts:123:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at attemptVerification (/home/john/private/sandbox/eth/code_directory/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:490:30)
    at SimpleTaskDefinition.action (/home/john/private/sandbox/eth/code_directory/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:778:48)
    at Environment._runTaskDefinition (/home/john/private/sandbox/eth/code_directory/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at Environment.run (/home/john/private/sandbox/eth/code_directory/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at SimpleTaskDefinition.verifySubtask [as action] (/home/john/private/sandbox/eth/code_directory/node_modules/@nomiclabs/hardhat-etherscan/src/index.ts:312:28)
    at Environment._runTaskDefinition (/home/john/private/sandbox/eth/code_directory/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)
    at Environment.run (/home/john/private/sandbox/eth/code_directory/node_modules/hardhat/src/internal/core/runtime-environment.ts:156:14)
    at Environment._runTaskDefinition (/home/john/private/sandbox/eth/code_directory/node_modules/hardhat/src/internal/core/runtime-environment.ts:308:14)



```

**Comment by Andriy-Kulak** [comment]
i have the same exact issue. had no problems until today. i am guessing it's a goerli etherscan issue but a little frustrating cuz there is no heads up on it from that team.

**Comment by Andriy-Kulak** [comment]
i tried validating via hardhat cli and via `hre.run("verify:verify",` ...

neither worked while previously it was all fine

**Comment by fvictorio** [comment]
Hey @Enigmatic331, is this a known issue in the goerli explorer?

**Comment by Enigmatic331** [comment]
Yeap, our Goerli node is very intermittently going down again over the past week (yay), in a different fashion that our verification error capturing isn't anticipating (so that's an improvement on our end to do - Soon), so it's returning a vague `Compiled contract runtime bytecode does NOT match the on-chain runtime bytecode.` error.

Should be alright now, can give it another shot. I'll personally keep an eye on this too.

Thanks for the ping Franco.

**Comment by fvictorio** [comment]
Thanks as always! I'm going to close this now then.

**Comment by owemeister** [comment]
Thanks @Enigmatic331  and @fvictorio for looking into this. Knowing the source of the error helps.

**Comment by Andriy-Kulak** [comment]
@Enigmatic331  I just tried and I am still getting the error. is there a place I can track this so I know when it's fixed?

**Comment by Enigmatic331** [comment]
Could you pass along the contract address you're trying to verify? I will take a look.

**Comment by Andriy-Kulak** [comment]
I just tried again cli and it worked. it was this contract: https://goerli.etherscan.io/address/0xEa1B8Fc3d207839A3Ceb2fa8f7Eafc1063e2517c#code

**Comment by sataqi** [comment]
FYI: this is happening again, any help plz?

**Comment by Enigmatic331** [comment]
Was pushing out a couple fixes last night around the time, feel free to retry and ping if you might be having any issues. :)

**Comment by tomdickharryeth** [comment]
> Was pushing out a couple fixes last night around the time, feel free to retry and ping if you might be having any issues. :)

Hello, i am still getting the error this morning, here is my contract: https://goerli.etherscan.io/address/0x7752ab36C35116Ec8D29c7d6241f013516dA39C7#code

**Comment by barubora3** [comment]
I am in a similar situation.

`Error in plugin @nomiclabs/hardhat-etherscan: The Etherscan API responded with a failure status.
The verification may still succeed but should be checked manually.
Reason: Fail - Unable to verify. Compiled contract runtime bytecode does NOT match the on-chain runtime bytecode.`

Please check.
https://goerli.etherscan.io/address/0x393db526a8679785697f54d43699e6b3dade7e13

**Comment by tomdickharryeth** [comment]
> > Was pushing out a couple fixes last night around the time, feel free to retry and ping if you might be having any issues. :)
> 
> Hello, i am still getting the error this morning, here is my contract: https://goerli.etherscan.io/address/0x7752ab36C35116Ec8D29c7d6241f013516dA39C7#code

Ok it seems to work now after I tried again, thanks
