### ISSUE TITLE
Updated version implementation of console.log

### ISSUE THREAD

**Issue by justcode740** [NomicFoundation/hardhat#3613]
### Describe the feature

currently console.sol is <0.8.0 which makes it impossible to use for contracts ^0.8.0, is it possible to have an upgraded version of console.sol?

**Comment by fvictorio** [comment]
The pragma version of console.sol is:

```
pragma solidity >= 0.4.22 <0.9.0;
```

and it has been that way for a couple of years. Maybe you are using a really old version of Hardhat?
