### ISSUE TITLE
 Fail - Unable to verify. This could be a temporary error, please retry or contact us (Error Code 10003) 

### ISSUE THREAD

**Issue by lixiaolongxl** [NomicFoundation/hardhat#3621]
### Version of Hardhat

2.12.5

### What happened?

 Fail - Unable to verify. This could be a temporary error, please retry or contact us (Error Code 10003)
NomicLabsHardhatPluginError: The Etherscan API responded with a failure status

### Minimal reproduction steps

I execute npx hardhat verify --network goerli xxxx prompt information

### Search terms

verify

**Comment by fvictorio** [comment]
As the error message says, this was probably a temporary thing. Please let us know if that's not the case.
