### ISSUE TITLE
Bool returned in solidity is resulted as some object in NodeJs

### ISSUE THREAD

**Issue by m-waqas88** [NomicFoundation/hardhat#3622]
### What I am doing?
I am writing a simple basic smart contract for certificate verification. 

### Facts
The `verifyCertificate` function returns bool (true or false).

`
function verifyCertificate(bytes32 _certificateHash) public returns(bool){
        bool verified = certificates[_certificateHash];    
        if(verified){
            emit CertificateVerified(_certificateHash);
        }
        return verified;
}
`

I am using `ethers` from `hardhat` and JsonRpcProvider.
`const { ethers } = require("hardhat");
const provider = new ethers.providers.JsonRpcProvider("http://localhost:8545");`

I am invoking the function `verifyCertificate`
`wallet = await contract.connect(issuer);
 const success = await wallet.verifyCertificate(CERTIFICATE_HASH);`

### Issue
This is supposed to return a boolean value as it is returned in the smart contract using Solidity.

But when I log the returned value in the console
`console.log(success);`

I receive below object (that looks like transaction object but does not have status property)
`{
  hash: '0x36d8b777081a954bda09e7deb9ed6fc101afe180b7a5626c0f0b5b5e492f6cb6',
  type: 2,
  accessList: [],
  blockHash: '0x8c3a34e313d5791f26fe63e2637ec6fc482f917f0774c8228597d92e205920a2',
  blockNumber: 3,
  transactionIndex: 0,
  confirmations: 1,
  from: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
  gasPrice: BigNumber { value: "1672290038" },
  maxPriorityFeePerGas: BigNumber { value: "1000000000" },
  maxFeePerGas: BigNumber { value: "2344580076" },
  gasLimit: BigNumber { value: "29023448" },
  to: '0x5FbDB2315678afecb367f032d93F642f64180aa3',
  value: BigNumber { value: "0" },
  nonce: 2,
  data: '0x850c1768e1f5fdfc4ea680634168535290f8a5ec6b9bcdddfd975ce1bb3fbbf7e82da5c7',
  r: '0xa332ed542f6271a6b9628cd1c3aebe2aa0d88751161bbec07e541fba91736782',
  s: '0x1be6b67869003e50b4c22e7defb023b096da2a2f2f1c51733621766aaaca8343',
  v: 0,
  creates: null,
  chainId: 31337,
  wait: [Function (anonymous)]
}`

### Possible Solution
When I specify the `verifyCertificate` function as `view` then I get the boolean value in NodeJs environment as required and expected. But I need to emit the event when the certificate is verified, that is why I cannot specify this function as `view`
 

### Expected
I want the resulted boolean value not this object.

#### Additional Information:
hardhat.config.js:
`require("@nomicfoundation/hardhat-toolbox");

/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  solidity: "0.8.17",
};`

package.json
`{
  "name": "CertificateManagementPlatform",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "hardhat": "^2.12.6"
  },
  "devDependencies": {
    "@ethersproject/abi": "^5.4.7",
    "@ethersproject/providers": "^5.4.7",
    "@nomicfoundation/hardhat-chai-matchers": "^1.0.0",
    "@nomicfoundation/hardhat-network-helpers": "^1.0.0",
    "@nomicfoundation/hardhat-toolbox": "^2.0.0",
    "@nomiclabs/hardhat-ethers": "^2.0.0",
    "@nomiclabs/hardhat-etherscan": "^3.0.0",
    "@typechain/ethers-v5": "^10.1.0",
    "@typechain/hardhat": "^6.1.2",
    "chai": "^4.2.0",
    "ethers": "^5.4.7",
    "hardhat-gas-reporter": "^1.0.8",
    "solidity-coverage": "^0.8.0",
    "typechain": "^8.1.0"
  }
}`

Certificate.sol
`// SPDX-License-Identifier: SEE LICENSE IN LICENSE
pragma solidity ^0.8.0;

contract Certificate{

    address public issuer;
    mapping(bytes32 => bool) public certificates;
    
    event CertificateIssued(bytes32 indexed CertificateHash);
    event CertificateVerified(bytes32 indexed CertificateHash);

    constructor(address _issuer) {
        issuer = _issuer;
    }

    function issueCertificate(bytes32 _certificateHash) public returns(bool) {
        require(msg.sender == issuer, "Only issuer can issue the certificate");
        certificates[_certificateHash] = true;
        emit CertificateIssued(_certificateHash);
        return true;
    }

    function verifyCertificate(bytes32 _certificateHash) public returns(bool){
        bool verified = certificates[_certificateHash];
        
        if(verified){
            emit CertificateVerified(_certificateHash);
        }

        
        return verified;
    }

}`

contract ABI
`"abi": [
    {
      "inputs": [
        {
          "internalType": "address",
          "name": "_issuer",
          "type": "address"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "constructor"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "CertificateHash",
          "type": "bytes32"
        }
      ],
      "name": "CertificateIssued",
      "type": "event"
    },
    {
      "anonymous": false,
      "inputs": [
        {
          "indexed": true,
          "internalType": "bytes32",
          "name": "CertificateHash",
          "type": "bytes32"
        }
      ],
      "name": "CertificateVerified",
      "type": "event"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "",
          "type": "bytes32"
        }
      ],
      "name": "certificates",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "_certificateHash",
          "type": "bytes32"
        }
      ],
      "name": "issueCertificate",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    },
    {
      "inputs": [],
      "name": "issuer",
      "outputs": [
        {
          "internalType": "address",
          "name": "",
          "type": "address"
        }
      ],
      "stateMutability": "view",
      "type": "function"
    },
    {
      "inputs": [
        {
          "internalType": "bytes32",
          "name": "_certificateHash",
          "type": "bytes32"
        }
      ],
      "name": "verifyCertificate",
      "outputs": [
        {
          "internalType": "bool",
          "name": "",
          "type": "bool"
        }
      ],
      "stateMutability": "nonpayable",
      "type": "function"
    }
  ],`

**Comment by m-waqas88** [comment]
### Suggested Solution
When there is an explicit return value in a function then that value must be returned not the transaction object. If there is no explicit return value then by default Transaction Object can be returned. There must however be an optional argument if the caller of the function wants the Transaction Object in return or the explicit returned value.

**Comment by fvictorio** [comment]
Hi @m-waqas88. Getting the value of a function like that is only possible if the function is `view` or `pure`, which is not the case of the function you shared.

When the function is not `view` or `pure`, a transaction is sent and mined, and the return value cannot be (easily) recovered. This is just how the JSON-RPC layer of ethereum works.

You have some options here:
- Add `view` or `pure` to that function if possible.
- Instead of returning the value, emit it in an event, capture the event and extract the value.
- Keep the function as is if you can't change it. In that case, to recover the value you have to use the `debug_traceTransaction` RPC method, extract the `returnValue` and parse it. This is very involved, but doable.

The first option is by far the best one if you can do it.

**Comment by m-waqas88** [comment]
@fvictorio thanks for your response. I will go with the second option. This best suits my current need.
