### ISSUE TITLE
HH412 Invalid import error, introduced 2.12.3

### ISSUE THREAD

**Issue by hensha256** [NomicFoundation/hardhat#3624]
### Version of Hardhat

2.12.3 onwards

### What happened?

Getting the following error:
```
Error HH412: Invalid import solmate/src/tokens/ERC721.sol from contracts/base/X.sol. Trying to import file using the own package's name.
```

I have `solmate` as a file in the root of the directory through submodules, and previous hardhat versions used to compile correctly. Version 2.12.2 did not have this issue - however from 2.12.3-2.12.6 this bug has been present.

### Minimal reproduction steps

The repo in question I used is Uniswap's [UniversalRouter](https://github.com/Uniswap/universal-router/)

**Comment by hensha256** [comment]
Could well be the same bug as #3623

**Comment by fvictorio** [comment]
Hi, thanks for opening this. Please see my comment [here](https://github.com/NomicFoundation/hardhat/issues/3623).
