### ISSUE TITLE
console.log on a custom node

### ISSUE THREAD

**Issue by delaaxe** [NomicFoundation/hardhat#3633]
How would I go about implementing console.log on a custom node (like a zkEVM node)? Where is the current implementation where the smart contract calls originating from ˋconsole.sol` go to?

**Comment by fvictorio** [comment]
Hi @delaaxe. The way console.log works is that static calls are sent to a well-known address (`0x000000000000000000636F6e736F6c652e6c6f67`) and the calldata has the necessary encoded information. For example, when you do `console.log(3)`, then the calldata is `abi.encodeWithSignature("log(int256)", 3)`, which is `0x2d5b6cb9000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000`.

We then analyze all calls to that address, decode the data, and log the proper thing.

Chances are that some details of this will change in the future, but this is the way it currently works.

Let me know if you have more questions about this.

**Comment by delaaxe** [comment]
Hi and thanks for your response.

I understand the sending part, I'm looking for the code of the receiving part, ie: 

> We then analyze all calls to that address, decode the data, and log the proper thing.

Is this open source?

**Comment by fvictorio** [comment]
Oh yes. I think you should start reading from here:

https://github.com/NomicFoundation/hardhat/blob/07e4693021aed05baa34a18f76475a7103a9ee04/packages/hardhat-core/src/internal/hardhat-network/stack-traces/consoleLogger.ts#L128

Notice that first the signature is obtained (first 4 bytes), that is mapped to a list of known signatures, and then used to parse the data in the `_decode` function.
