### ISSUE TITLE
Warning about node version using Node 19.6.0?

### ISSUE THREAD

**Issue by grapevinegizmos** [NomicFoundation/hardhat#3641]
### Version of Hardhat

9.4.0

### What happened?

I"m kind of confused actually.  when I run `npm hardhat --version` I get **9.4.0**, but the npm page says the latest version is **2.12.6?**

The reason I started looking whether to update is because I started getting this message:  **_You are using a version of Node.js that is not supported by Hardhat, and it may work incorrectly, or not work at all. Please, make sure you are using a supported version of Node.js.To learn more about which versions of Node.js are supported go to https://hardhat.org/nodejs-versions_**

So I upgraded node to version 19.6.0, which I gather is current, but I'm still getting that same message. 

I tried to upgrade hardhat but got this message: 
```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'hardhat@2.12.6',
npm WARN EBADENGINE   required: { node: '^14.0.0 || ^16.0.0 || ^18.0.0' },
npm WARN EBADENGINE   current: { node: 'v19.6.0', npm: '9.4.0' }
npm WARN EBADENGINE }
```

### Minimal reproduction steps

`hh test` produces this error in vs code, or `npx hardhat node` in the terminal.

**Comment by grapevinegizmos** [comment]
OK, I see part of the problem, which when I run `**npx** hardhat --version` I get 2.12.6, but when i run `**npm** hardhat version` I get 9.4.0.  I gather `npx` is the way to go, although I don't understand what result npm is giving me.

But the warning still confuses me, since I am using both current version of node and hardhat.  Why do I get the warning about using a version of node.js not supproted by hardhat?

**Comment by fvictorio** [comment]
I don't think we support node 19 yet. Check [this part of our docs](https://hardhat.org/hardhat-runner/docs/reference/stability-guarantees#node.js-versions-support).

> although I don't understand what result npm is giving me.

You are getting the same result you'd get if you run `npm --version`. That is, the npm version (that is not the same as the node version).

**Comment by grapevinegizmos** [comment]
Yeah, I downgraded node to the TLS version which is what your documentation says we should use, but I am still getting this message:

```
nft-contracts % node --version
v18.14.0
nft-contracts % npx hardhat node
You are using a version of Node.js that is not supported by Hardhat, and it may work incorrectly, or not work at all.

Please, make sure you are using a supported version of Node.js.
```
To learn more about which versions of Node.js are supported go to https://hardhat.org/nodejs-versions

**Comment by TumTum23** [comment]
@grapevinegizmos Did you find a resolution to this issue? 

I am getting the same error with npm and node installed to latest versions.

**Comment by TumTum23** [comment]
Are you also getting a HH8 error? (Config related)
