### ISSUE TITLE
hard node on localhost fails gives unusual timeout error?

### ISSUE THREAD

**Issue by grapevinegizmos** [NomicFoundation/hardhat#3642]
### Version of Hardhat

2.12.6

### What happened?

When running a fairly long script (about 3.5 minutes) using `--network localhost` with a node running in terminal started with `npx hardhat node`, the script fails with the following error:

```
HeadersTimeoutError: Headers Timeout Error
    at Timeout.onParserTimeout [as _onTimeout] (/Users/joshkramer/Documents/VSCodeProjects/BKopy/bkopy-nft-contracts/node_modules/undici/lib/client.js:905:28)
    at listOnTimeout (node:internal/timers:570:11)
    at processTimers (node:internal/timers:511:7) {
  code: 'UND_ERR_HEADERS_TIMEOUT'
```

The same script complete normally however, when running on the internal hardhat node when run without the '--network`
specifier, or when run on the polygon mumbai test net.    

In an effort to fix it, I added the following to my hardhat.config:  "networks" key:
```
local: {
      url: "http://localhost:8545",
      timeout: 100_000_000
    },
```
but no help.

### Minimal reproduction steps

hh run scripts/[scriptname].ts

**Comment by alcuadrado** [comment]
I think you are setting the wrong name in your config. It should be `localhost`, not `localhost`. [This PR](https://github.com/NomicFoundation/hardhat/pull/3665) may help, but double check your config.

**Comment by grapevinegizmos** [comment]
Did you mean it should be 'localhost' not 'local'?

**Comment by grapevinegizmos** [comment]
I can no longer reproduce the error because I've made the long running process more efficient, but I'll try that change and let you know if it pops up again.  Sounds like that's what the problem is.

**Comment by alcuadrado** [comment]
> Did you mean it should be 'localhost' not 'local'?

Right.

Thanks for helping us reproduce it.

**Comment by fvictorio** [comment]
I guess we can close this until you can build a reproduction example?

**Comment by grapevinegizmos** [comment]
Yes thanks for your hlep.
