### ISSUE TITLE
How to made Hardhat networking always sync with mainnet?

### ISSUE THREAD

**Issue by TangMonk** [NomicFoundation/hardhat#3644]
I wanna to create an application for simulate transacation with Hardhat networking forking feature (check the ERC20 token buy and sell tax fee)

I try to config `mining mode` to `auto` or `interval`. But it just mine a fake block (not real sync with mainnet), So I cannot get real data from mainnet.

In order to always sync with mainnet, I have to restart hardhat networking forking every `12s`(the normal block generation time in ethereum). It is painful.

Thanks

**Comment by fvictorio** [comment]
@TangMonk opening both a discussion and an issue with the same question is spammy and wastes our time. Please don't do that.
