### ISSUE TITLE
Should add ENV variables http_proxy and https_proxy

### ISSUE THREAD

**Issue by HAYWAEL** [NomicFoundation/hardhat#3651]
### Describe the feature

Http_proxy lowercase is also very common, including some proxy tools, such as ClashX, copying terminal commands also use http_proxy；
[code](https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-core/src/internal/util/download.ts#L30)

### Search terms

Headers Timeout Error,  connect ECONNREFUSED

**Comment by fvictorio** [comment]
This will be fixed by https://github.com/NomicFoundation/hardhat/pull/3432

**Comment by fvictorio** [comment]
Closed by #3432.
