### ISSUE TITLE
Forbid chaining incompatible chai matchers

### ISSUE THREAD

**Issue by VVander** [NomicFoundation/hardhat#3667]
### Version of Hardhat

2.12.7

### What happened?

I'm running into an issue where only the last chai matcher is being applied.

In my case,  `changeEtherBalances` and `changeTokenBalance` aren't being chained correctly:

```
await expect(lock.withdraw()).to.changeEtherBalances(
          [owner, lock],
          [lockedAmount, -lockedAmount]
        )
        .and.to.changeTokenBalance(
            token, "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045", 1
        );
```

In this case, only the last condition is actually checked and the first one appears to be skipped entirely. I've attached a minimal reproducible based on the default HH project which demonstrates this.

I'm definitely not an expert with Mocha/Chai, so I'm assuming there's something I'm doing wrong, but it appears as if there's an issue chaining the matchers since it also happens with other HH matchers like `reverted` and `changeEtherBalances`:

```
await expect(lock.withdraw())
          .to.be.reverted // this is ignored
          .and.to.changeEtherBalances(
            [owner, lock],
            [lockedAmount, -lockedAmount]
          );
```

### Minimal reproduction steps

See reproducible project:
[reproducible.zip](https://github.com/NomicFoundation/hardhat/files/10714922/reproducible.zip)

Note that I removed the `node_modules` directory for the upload so you'll have to reinstall those.

### Search terms

chai matcher

**Comment by alcuadrado** [comment]
Thanks for reporting this. I believe it's a bug on our end.

Is there a way to forbid this, @fvictorio ?

**Comment by fvictorio** [comment]
I'm pretty sure there is. We should add some contextual flag that says that we already added a matcher to the chain, and check it in each other matcher. It's a shitty solution, but I don't think chai has a better mechanism for that.

We have similar things that are duplicated across matchers, so I feel we should invest in some indirection (like a matcher-adder interface) that handles these kind of things.

**Comment by VVander** [comment]
@fvictorio does this title change imply that `changeEtherBalances()` and `changeTokenBalance()` are incompatible? What is the right way to write a unit test for a function which does both?

Regardless, thanks for taking a look at this. I'm now faced with the prospect of going back through all of my many dozens of unit tests and manually checking if they use multiple matchers... This has set my schedule back dramatically :(

**Comment by MuhammadWajidShahid** [comment]
@fvictorio 
I am facing the same problem. It only checks the last chained condition.
The first `event` is being ignored also the first `changeTokenBalance` is also being ignored.

``` 
 await expect(masterchef.deposit(0, parseUnits("1"), owner.address))
              .to.emit(rewarder, "LogOnReward")
              .withArgs(owner.address, 0, parseUnits("1"), owner.address).and
              .to.emit(tokenRewarder, "LogOnReward")
              .withArgs(owner.address, 0, parseUnits("1"), owner.address)
              .to.changeTokenBalance(token, owner.address, parseUnits("1"))
              .and.to.changeTokenBalance(rewardToken, owner.address, parseUnits("1"));
```
