### ISSUE TITLE
Ethers is configured for the wrong network when running a task

### ISSUE THREAD

**Issue by SleepingShell** [NomicFoundation/hardhat#3678]
### Version of Hardhat

2.12.5

### What happened?

I am attempting to use hardhat tasks to perform various functions on deployed contracts on the Sepolia network. However, the HRE ethers instance does not seem to be configured with the correct network info, or perhaps I am misreading the hre object and getting a different kind of bug.

I have this configured network in my ``hardhat.config.ts``
```
networks: {
    sepolia: {
      url: "https://rpc.sepolia.org/",
      chainId: 11155111,
      accounts: {
        mnemonic: MNEMONIC,
        path: MNEMONIC_PATH,
        initialIndex: 1,
      },
    },
  },
``` 

This is an example task I have in my project as a file in ``scripts/deployMockToken.ts`` (these are the complete contents of the file):

```
import { task } from "hardhat/config";

task("deployMock", "Deploy a mock token that anyone can mint").setAction(async (args, hre) => {
  const mock = await (await ethers.getContractFactory("MockERC20")).deploy("Mock", "MCK");
  console.log(hre.network);
  console.log("-------");
  console.log(hre.ethers.provider);
  console.log(`Token deployed to: ${mock.address}`);
});
```
Run with ``npx hardhat --network sepolia deployMock``

The print statement from ``hre.network`` shows Sepolia correctly. However, printing out ``hre.ethers.provider`` shows the following properties
```
...
  anyNetwork: false,
  _networkPromise: Promise {
    {
      name: 'sepolia',
      chainId: 11155111,
      ensAddress: null,
      _defaultProvider: [Function]
    }
  },
  _maxInternalBlockNumber: 2909837,
  _lastBlockNumber: -2,
  _maxFilterBlockRange: 10,
  _pollingInterval: 4000,
  _fastQueryDate: 1676515914423,
  connection: { url: 'http://localhost:8545' },
...
```
As such, the token is being deployed not to the real Sepolia network and does not show up in etherscan.

### Minimal reproduction steps

1. Write a hardhat task
2. Attempt to run it with the ``--network`` flag

### Search terms

ethers network configuration hre wrong

**Comment by SleepingShell** [comment]
Okay, perhaps the RPC endpoint I was using just happened to not be working correctly, as now all the transactions I created in the past 2 days executed. So am I right that the connection of the ethers object *is* supposed to be localhost, and not the actual endpoint?

**Comment by fvictorio** [comment]
The provider was probably correct. If you are talking about the `url: 'http://localhost:8545'` part, that is just a misleading output (see https://github.com/NomicFoundation/hardhat/issues/1138)
