### ISSUE TITLE
Error while installing hardhat

### ISSUE THREAD

**Issue by zenc0derr** [NomicFoundation/hardhat#3689]
When I'm Installing Hardhat using `yarn add --dev hardhat`, there is an error:
```
error ./node_modules/classic-level: Command failed.
Exit code: 127
Command: node-gyp-build
```
Even tried using npm, Got same error.

Error while using npm:
```
npm ERR! code 127
npm ERR! path ./node_modules/classic-level
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! sh: 1: node-gyp-build: not found
```
My Node version: v18.14.1

**Comment by sshmaxime** [comment]
What is your OS ? What is your node version ?

It might be because you are missing some packages on your machine.

Here are some links that might be useful to you: 
- https://github.com/nodejs/node-gyp/issues/809#issuecomment-166704390
- https://github.com/nodejs/node-gyp/issues/809#issuecomment-170033534 (another comment)
- https://stackoverflow.com/a/39674502/6796428

**Comment by fvictorio** [comment]
Yeah, this seems like an environment problem. Happy to help if I can (if you can share more about your setup, like your OS and if you are using a node version manager), but I'm going to close the issue because it's unrelated to Hardhat itself.

**Comment by zenc0derr** [comment]
> What is your OS ? What is your node version ?
> 
> It might be because you are missing some packages on your machine.
> 
> Here are some links that might be useful to you:
> 
> * [trying to 'npm install', getting node-gyp rebuild errors nodejs/node-gyp#809 (comment)](https://github.com/nodejs/node-gyp/issues/809#issuecomment-166704390)
> * [trying to 'npm install', getting node-gyp rebuild errors nodejs/node-gyp#809 (comment)](https://github.com/nodejs/node-gyp/issues/809#issuecomment-170033534) (another comment)
> * https://stackoverflow.com/a/39674502/6796428

The comment in the second link solved the issue for. @sshmaxime thanks for your help.
