### ISSUE TITLE
Feature: Show appropriate error when a contract has several functions with the same name

### ISSUE THREAD

**Issue by Allarious** [NomicFoundation/hardhat#3695]
### Describe the feature

Whenever a contract has several functions with the same name and different signatures, the functions are only accessible if called by their signature. In such cases, when a function is called as a function of the contract object, it throws the error of `TypeError: <function name> is not a function`. Instead, it could be helpful to show a more appropriate Error message where it points the user towards using the signature.

**Comment by fvictorio** [comment]
Hi @Allarious, I think you are talking about an ethers thing, which is not part of Hardhat. That is a known issue (see https://github.com/ethers-io/ethers.js/issues/407, for example), and I think v6 will handle it better. But there isn't much we can do on our side.
