### ISSUE TITLE
Cannot compile vyper contract: Bad CPU type in executable

### ISSUE THREAD

**Issue by Wootroo** [NomicFoundation/hardhat#3702]
### Version of Hardhat

2.12.7

### What happened?

Recently moved from my Windows 11 device to my new Apple Macbook pro with a **M2** chip.

Installed all dependencies through `npm install` and tried to compile the solidity and vyper files, but received the following error message:

```
Compiled 54 Solidity files successfully
Downloading compiler 0.3.1
An unexpected error occurred:
Error: Command failed: /Users/user/Library/Caches/hardhat-nodejs/compilers-v2/vyper/darwin/0.3.1 -f combined_json /Users/user/vyperContract.vy
/bin/sh: /Users/user/Library/Caches/hardhat-nodejs/compilers-v2/vyper/darwin/0.3.1: Bad CPU type in executable

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12) {
  code: 126,
  killed: false,
  signal: null,
  cmd: '/Users/user/Library/Caches/hardhat-nodejs/compilers-v2/vyper/darwin/0.3.1 -f combined_json /Users/user/vyperContract.vy'
}
```

The solidity files are successfully compiled but the vyper contract cannot be compiled. Any suggestions?
I guess this has something to do with the new macbook M2 chip?

Extra info:

- Vyper plugin: @nomiclabs/hardhat-vyper: 3.0.2
- Target vyper version: 0.3.1
- Device specs : Macbook pro with macOS Ventura

### Minimal reproduction steps

Simply create a new hardhat project, add the hardhat vyper plugin and try to compile a vyper file on a Mac with a M2 chip.

### Search terms

Bad CPU type, Cannot compile vyper contract

**Comment by fvictorio** [comment]
@alcuadrado can you confirm this?

**Comment by Wootroo** [comment]
Solved this problem by installing the `Rosetta` sofware through command line:
`softwareupdate --install-rosetta`

Seems like the Vyper compiler can only run default on macbooks with an `Intel` processor...

**Comment by fvictorio** [comment]
Oh nice, thanks for letting us know!
