### ISSUE TITLE
[Confused] What is the mechanism of local test network?

### ISSUE THREAD

**Issue by aitimate** [NomicFoundation/hardhat#3703]
When I use `@openzeppelin/hardhat-upgrades` to deploy conntracts, I encountered a confusing situation, here it is:
```typscript
    // deploy.ts
    const ITToken = await ethers.getContractFactory('ITToken')
    console.log(await ethers.provider.getTransactionCount(owner.address))
    const itToken1 = await upgrades.deployProxy(ITToken, [])
    console.log(await ethers.provider.getTransactionCount(owner.address))
    const itToken2 = await upgrades.deployProxy(ITToken, [])
    console.log(await ethers.provider.getTransactionCount(owner.address))
```

```cmd
0
ITToken 0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0
3
ITToken 0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9
4
```

see! The second deployed only  has one contract! **Whether there is a configuration to ensure the complete deployment of each execution of deploy.ts? I have a code that predicts the contract address that doesn't work well**, like this: 
ps: targetContract and ProxyAdmin are reused in the second execution, so I have to modifier the nonce to `nocne+1` or reboot network node to ensure `expectPledgeNftPool` is correct...a little annoying...
```typescript
    const expectPledgeNftPool = ethers.utils.getContractAddress({
        from: owner.address,
        nonce: await ethers.provider.getTransactionCount(owner.address) + 3,
    });
```

**Comment by sshmaxime** [comment]
Hey @aitimate, 3 things: 

1 - It's a bit hard to understand your issue which is making it difficult to answer properly.
2 - This is not really related to Hardhat but rather related to OpenZeppelin so the issue should have been opened there.
3 - That being said, I'll help you out:

Firstly, I guess you know it but `getTransactionCount` returns `the number of transactions sent from this address` so it has nothing to do with the number of contract one deployed.

Then, calling twice `deployProxy` with the same implementation will only [deploy another proxy contract](https://docs.openzeppelin.com/upgrades-plugins/1.x/faq#what-is-an-implementation-contract). So it's pretty normal that the second call to `deployProxy` deployed only one contract.

I hope that helps, if not, please clarify the issue you are facing.

**Comment by aitimate** [comment]
> Hey @aitimate, 3 things:
> 
> 1 - It's a bit hard to understand your issue which is making it difficult to answer properly. 2 - This is not really related to Hardhat but rather related to OpenZeppelin so the issue should have been opened there. 3 - That being said, I'll help you out:
> 
> Firstly, I guess you know it but `getTransactionCount` returns `the number of transactions sent from this address` so it has nothing to do with the number of contract the given address has deployed.
> 
> Then, calling twice `deployProxy` with the same implementation will only [deploy another proxy contract](https://docs.openzeppelin.com/upgrades-plugins/1.x/faq#what-is-an-implementation-contract). So it's pretty normal that the second call to `deployProxy` deployed only one contract.
> 
> I hope that helps, if not, please clarify the issue you are facing.

Thanks a lot! Two inconsistent behaviors make me unable to predict the contract address with fixed `getContractAddress`, As you said, it's related to OpenZeppelin, thanks again!
