### ISSUE TITLE
Compiling Hardhat project using Solang compiler

### ISSUE THREAD

**Issue by joshuacheong** [NomicFoundation/hardhat#3711]
### Describe the feature

As a developer on new blockchain stacks I want to develop the ability to compile solidity for Solana and Substrate (Polkadot, Astar network, and many more). This will help developers like myself reach a much bigger market for smart contract deployment.

As a result I have to use the [Solang](https://github.com/hyperledger/solang) compiler.

Hardhat has made majority of the deployment work across multiple files extremely easy, especially when these files have address inputs that are dependencies upon other files being deployed upon creation.

- Would there be any interest to include Solang compiler instead of Solc for deployment
- What would be the best way to include Solang?

**Comment by alcuadrado** [comment]
hey @joshuacheong

Compiling with a different compiler should be doable by a plugin. Note that Hardhat is built for the EVM though, so the compilation results of that compiler won't be as compatible. For example, Hardhat Network won't be able to run them, nor ethers will be able to use the generated artifacts, etc.

**Comment by fvictorio** [comment]
Closing this since it's unlikely to happen in Hardhat core.
