### ISSUE TITLE
Support Solidity 0.8.19

### ISSUE THREAD

**Issue by eladiosch** [NomicFoundation/hardhat#3713]
New Solidity version released: 0.8.19

https://github.com/ethereum/solidity/releases/tag/v0.8.19

Creating this issue to request support for it

**Comment by fvictorio** [comment]
We just released [Hardhat v2.17.0](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.17.0), which adds support for solc 0.8.19.
