### ISSUE TITLE
Flattening Files brings a 'Network Doesn't Exist' Error

### ISSUE THREAD

**Issue by ibraziz21** [NomicFoundation/hardhat#3720]
### Version of Hardhat

2.12.7

### What happened?

Added Matic Mumbai Network config to config.js and deployed smart contracts.
I was trying to flatten the files and verify on polygon scan it brought an Error:
Network  Matic Doesn’t Exist

The flattening worked after taking out the network config

### Minimal reproduction steps

set Network configuration (in my case, Polygon Mumbai)
Deploy Smart contracts
Flatten files

### Search terms

Network Doesn’t Exist Flattening

**Comment by ibraziz21** [comment]
npx hardhat flatten filexyz.sol > flat.sol

**Comment by fvictorio** [comment]
@ibraziz21 the only way I can see this happening is if you have a `defaultNetwork: "Matic"` entry in your Hardhat config but you don't have a `Matic` network defined in there.

In that case, the solution is either to remove the `defaultNetwork` or to define that network.

Please let us know if that's not what's going on.
