### ISSUE TITLE
AssertionError: Expected transaction to be reverted with custom error 'IncorrectRange', but it reverted without a reason

### ISSUE THREAD

**Issue by k06a** [NomicFoundation/hardhat#3732]
### Version of Hardhat

2.12.7

### What happened?

We faced issue when running hardhat tests SECOND time or SECOND time after cleaning:
- `yarn test:ci` - works fine
- `yarn test:ci` - **FAILS!**
- `yarn clean`
- `yarn test:ci` - works fine
- `yarn test:ci` - **FAILS!**

With the following error:
```
  2) RangeAmountCalculator
       Fill by taker asset
         Revert with incorrect prices:
     AssertionError: Expected transaction to be reverted with custom error 'IncorrectRange', but it reverted without a reason
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at runNextTicks (node:internal/process/task_queues:64:3)
      at listOnTimeout (node:internal/timers:538:9)
      at processTimers (node:internal/timers:512:7)
      at Context.<anonymous> (test/RangeAmountCalculator.js:63:13)
```

### Minimal reproduction steps

Clone repo: https://github.com/1inch/limit-order-protocol/
Use commit: `a0aea48ba19e38107fa6cfcfdc8ca2369b89e729`
Install deps: `yarn` or `nom install`
Run tests: `yarn test:ci` or `nom run test:ci`

**Comment by k06a** [comment]
Still valid for recent version `2.13.0`

**Comment by fvictorio** [comment]
Hey @k06a, the problem seems to be with the version of `hardhat-tracer` you are using. Upgrading to the latest version seems to produce consistent results.

Notice though that the consistent result is for the test to fail, but at least it's deterministic.

I'm going to tentatively close this, but let me know if you think there's a problem on our side.

**Comment by k06a** [comment]
@fvictorio thank you
