### ISSUE TITLE
Cannot create simple project on hardhat

### ISSUE THREAD

**Issue by Kriptocourier** [NomicFoundation/hardhat#3733]
I can't seem to find out how to start a new simple project. Somebody said something about it being in an upper directory, which i finally found, and i tried to move it down farther in the directory but it didnt help.      

  I ran npx hardhat --verbose , checked the messages, and attached is a pic. I'm SUPER new to coding and trying to do a course, any idea what to do next so that I can start a new simple project? There's not much help on hardhat that I can find.
![scrnsht10](https://user-images.githubusercontent.com/125918199/222596662-bc232959-22ab-4053-ab08-859dcc0be546.png)

_Originally posted by @Kriptocourier in https://github.com/NomicFoundation/hardhat/discussions/3313#discussioncomment-5184458_

**Comment by sshmaxime** [comment]
Hey @Kriptocourier , have you tried to follow the tutorial, here: https://hardhat.org/tutorial ?

**Comment by Kriptocourier** [comment]
Thanks for the reply!

I had a couple operator errors - I am super new to programming. I ended up figuring it out though, now everything is humming along nicely.
Thanks again for the reply!
Regards

-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



Mar 6, 2023, 12:37 by ***@***.***:

**Comment by sshmaxime** [comment]
@Kriptocourier No problem,  I'm glad to hear it ! If it solved please close the issue 😄
