### ISSUE TITLE
Support http proxy without http:// prefix

### ISSUE THREAD

**Issue by zjpetersen** [NomicFoundation/hardhat#3736]
### Describe the feature

When I try to run npx hardhat compile --show-stack-traces over a corporate proxy, I get the following error.  

Error HH502: Couldn't download compiler versions list. Please check your connection.
Caused by: InvalidArgumentError: invalid protocol
at parseURL (/path/node_modules/undici/lib/core/util.js:78:11)

This turned out to be due to having my http_proxy as http_proxy=proxy.company.com:port
Instead, the undici library which gets called was expecting it to have http:// at the start. http_proxy=http://proxy.company.com:port/

https://github.com/nodejs/undici/blob/4885b11dd60b4d1a785c4e5a519ad87920549d1c/lib/core/util.js#L81-L83

I don't think undici is willing to update their library, since this parseURL method could be used all over the place.  Instead an easy fix would be to append http:// to the http_proxy if it's not present.

https://github.com/NomicFoundation/hardhat/blob/57c56d2353da8828d6b2c167b24bd70b6298a8cc/packages/hardhat-core/src/internal/util/download.ts#L35

**Comment by fvictorio** [comment]
I feel like doing this would be overstepping. But I agree that that error message is very confusing. I'm going to open a new issue about validating the value of the proxy URL and showing a better error message.
