### ISSUE TITLE
Best practices on how to organize tasks?

### ISSUE THREAD

**Issue by itinance** [NomicFoundation/hardhat#3742]
Hi guys. How do you organize tasks? Putting them all into the `hardhat.config.ts` feels wrong, so I am interested in how others deal with that. Many thanks for any helpful hint

**Comment by sshmaxime** [comment]
Hey @itinance, why don't you create a `task` folder and store your tasks there ?

**Comment by fvictorio** [comment]
We don't have any official recommendation, but as @sshmaxime suggested, you can just import other modules from your config, so you can have a `tasks.ts` file (if you have few tasks) or a directory with a file for each task.
