### ISSUE TITLE
in first steps error  Error: Cannot find module '@nomicfoundation/hardhat-toolbox'

### ISSUE THREAD

**Issue by loveyandex** [NomicFoundation/hardhat#3749]
### Version of Hardhat

latest

### What happened?

i am followed getting started :https://hardhat.org/hardhat-runner/docs/getting-started

but after `npm install --save-dev hardhat` and  `npx hardhat` 
 i am running `npx hardhat` anf get this error 

> 
> An unexpected error occurred:
> 
> Error: Cannot find module '@nomicfoundation/hardhat-toolbox'
> Require stack:
> - F:\ethereum\hardhat-example\hardhat.config.js
> - F:\ethereum\hardhat-example\node_modules\hardhat\internal\core\config\config-loading.js
> - F:\ethereum\hardhat-example\node_modules\hardhat\internal\cli\cli.js
> - F:\ethereum\hardhat-example\node_modules\hardhat\internal\cli\bootstrap.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (F:\ethereum\hardhat-example\hardhat.config.js:1:1)
>     at Module._compile (node:internal/modules/cjs/loader:1105:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     'F:\\ethereum\\hardhat-example\\hardhat.config.js',
>     'F:\\ethereum\\hardhat-example\\node_modules\\hardhat\\internal\\core\\config\\config-loading.js',
>     'F:\\ethereum\\hardhat-example\\node_modules\\hardhat\\internal\\cli\\cli.js',
>     'F:\\ethereum\\hardhat-example\\node_modules\\hardhat\\internal\\cli\\bootstrap.js'
>   ]
> }

### Minimal reproduction steps

xxxxxxxxxxxxx

**Comment by sshmaxime** [comment]
It seems that you are on Windows, are you using `WSL 2` as it is recommended ?

**Comment by fvictorio** [comment]
You are missing some packages. During installation, you should've gotten a message explaining the necessary dependencies and how to install them. Alterantively, as @sshmaxime said, if you use WSL then they will be automatically installed.

**Comment by kuzdogan** [comment]
I am encountering the same problem on MacOS. Tried both with node v16 npm v8 as well as node v18 npm v9. 

In addition after installing `hardhat` I get this message:
```
$ npx hardhat
Error HH14: Your Hardhat project uses typescript, but it's not installed.

Please run: npm install --save-dev typescript

For more info go to https://hardhat.org/HH14 or run Hardhat with --show-stack-traces
```

But after installing `typescript` and `ts-node` I get the same error above

**Comment by kaxxa123** [comment]
When working on Windows (not WSL2) I get this error randomly. Sometimes it just works other times I get:
"Your Hardhat project uses typescript, but it's not installed"

The workaround I use is to simply recreate the directory "somewhere else ". For example if I was getting the error when trying to create the project under:
c:\Programming\Test

I  just go and create the project under:
c:\Other\Test

And it magically works. The I just move the folder to:
c:\Programming\Test

I also I noticed that on Windows this problem very often happens when using Git Bash, rather than Power Shell or the cmd.
