### ISSUE TITLE
Error when specifying solidity compiler version (with the commit)

### ISSUE THREAD

**Issue by adjisb** [NomicFoundation/hardhat#3754]
### Version of Hardhat

6.1.5

### What happened?

My platrform is linux, I'm trying to use a specific commit version of the compiler that only exists on solcjs, but as the code tries the native version first I get the following error: 

```
Error HH500: Solidity version v0.5.9+commit.e560f70d is invalid or hasn't been released yet.
If you are certain it has been released, run "npx hardhat clean --global" and try again
```
My conf looks like:
```
  solidity: {
    compilers: [
      {
        version: 'v0.5.9+commit.e560f70d',
```

### Minimal reproduction steps

Configure hardhat to use  version: 'v0.5.9+commit.e560f70d'

**Comment by fvictorio** [comment]
This is not supported by Hardhat. If you want to use a specific version of solc that is not a "stable" version, you have to download it manually and do something like [this](https://github.com/fvictorio/hardhat-examples/tree/master/custom-solc).
