### ISSUE TITLE
eth_estimateGas

### ISSUE THREAD

**Issue by knaranje** [NomicFoundation/hardhat#3759]
### Version of Hardhat

2.12.4

### What happened?

The transaction is not proceeding. It shows the eth_estimateGas on Hardhat network

### Minimal reproduction steps

0

**Comment by fvictorio** [comment]
Hey @knaranje, there isn't much we can do without reproduction steps. I'm going to tentatively close this, but I'll re-open if you can provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
