### ISSUE TITLE
Hardhat wasn't initialized

### ISSUE THREAD

**Issue by a-god-of-death** [NomicFoundation/hardhat#3765]
### Version of Hardhat

2.13.0

### What happened?

I can't load the .env file.
And when I use console.log(process.env) 
It shows that Hardhat initialization failed. 
HardhatContext is not created.

### Minimal reproduction steps

require("@nomicfoundation/hardhat-toolbox");
require('dotenv').config({path:".env"});

const PRIVATE_KEY = process.env.PRIVATE_KEY;

module.exports = {
  solidity: "0.8.9",
  networks: {
    goerli: {
      url: QUICKNODE_HTTP_URL,
      accounts: [PRIVATE_KEY],
    },
  },
};
console.log(process.env)

### Search terms

.env;hardhat

**Comment by fvictorio** [comment]
That example works fine for me. The only problem is that `QUICKNODE_HTTP_URL` is not defined, but if I define it (and I create a `.env` file with a `PRIVATE_KEY`), then it works.

Tentatively closing. I'll re-open if you can provide reproduction steps.
