### ISSUE TITLE
viaIR-mode does not inline insided solidity libraries

### ISSUE THREAD

**Issue by SevenSwen** [NomicFoundation/hardhat#3782]
### Version of Hardhat

2.13.0

### What happened?

Solidity-coverage has broken inliner optimization.
When I run coverage with optimizerSteps:
```
"dhfoDgvlfnTUtnIf" +
"[" +
    "xa[r]EscLM" +
    "cCTUtTOntnfDIl" +
    "Lcl" +
    "Vcl [j]" +
    "Tpel" +
    "xa[rl]" +
    "xa[r]cL" +
    "gvif" +
    "CTUca[r]LSsTFOtfDnca[r]Ilc"
"]" +
  "jml[jl] VcTOcl jml",
```
(default settings without u instrumentation in all steps) than all tests will be finished success. But If I remove "gvif" step (inliner optimization) then I will have error:
`NomicLabsHardhatPluginError: The contract <contract_name> is missing links for the following libraries: @openzeppelin/contracts/utils/math/Math.sol:Math`
Repo/branch:
https://github.com/1inch/farming/tree/feature/enable_viaIR

Same my issue into [ethereum/solidity](https://github.com/ethereum/solidity/issues/14055)

### Minimal reproduction steps

- clone repo
- yarn
- yarn coverage

### Search terms

viaIR, inliner, link library

**Comment by fvictorio** [comment]
Hey @SevenSwen, are you sure this issue shouldn't be reported in the [`solidity-coverage`](https://github.com/sc-forks/solidity-coverage) repo?

**Comment by SevenSwen** [comment]
Hmm, maybe you right @fvictorio, sorry for this.
I have created [issue](https://github.com/sc-forks/solidity-coverage/issues/790) to solidity-coverage. 

I'll close this issue for now
