### ISSUE TITLE
How sync local node with system time?

### ISSUE THREAD

**Issue by shinjiikari256** [NomicFoundation/hardhat#3785]
When testing time-dependent functions or testing the frontend, I see the lag of the node's timestamp from the system time, which is quite unpleasant.

**Comment by fvictorio** [comment]
I think that if you are using the Hardhat node to test a frontend, the best thing you can do is to enable [interval mining](https://hardhat.org/hardhat-network/docs/explanation/mining-modes). Is that enough for you or it doesn't quite fit your use case?

**Comment by fvictorio** [comment]
Closing for lack of response.
