### ISSUE TITLE
I cannot compile my ERC721A contract with Hardhat.

### ISSUE THREAD

**Issue by justChargin** [NomicFoundation/hardhat#3787]
Hi, i can compile my contract on Remix but i cannot with Hardhat.

**My imports**
![image](https://user-images.githubusercontent.com/46795644/226988307-556c1ca3-94cb-44a1-a4ac-990b4df0f514.png)

**ERROR**
![image](https://user-images.githubusercontent.com/46795644/226988501-72f26c8c-effe-4afe-9628-68573d14037e.png)
![image](https://user-images.githubusercontent.com/46795644/226988536-b9f9b76f-1b7e-4a22-8482-8ecd3e8e0f97.png)

**Hardhat Config File**
![image](https://user-images.githubusercontent.com/46795644/226988768-c2c2c945-a2f6-4486-aa7d-8e69c8774a6a.png)

**Comment by sshmaxime** [comment]
Hey @justChargin, first of all I'd suggest you to update your NodeJs version as it is stated. In a second step, do you have a repo for me to check what is going on ?

**Comment by fvictorio** [comment]
Agree, it's super hard to figure out what's happening with screenshots. I'm going to tentatively close this, but I'll re-open if you can provide a
[minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).
