### ISSUE TITLE
OnlyHardhatNetworkError: This helper can only be used with Hardhat Network. You are connected to 'localhost'.

### ISSUE THREAD

**Issue by mjczz** [NomicFoundation/hardhat#3788]
### Version of Hardhat

2.13.0

### What happened?

I use ganache ui app,
and I run ```npx hardhat --network localhost test``` to run the test
and I got this error below

```
OnlyHardhatNetworkError: This helper can only be used with Hardhat Network. You are connected to 'localhost', whose identifier is 'Ganache/v7.7.3/EthereumJS TestRPC/v7.7.3/ethereum-js'
```

### Minimal reproduction steps

<img width="1207" alt="WeChatd320bcd498db5c33600d3d5551a19ebf" src="https://user-images.githubusercontent.com/26185772/227119722-07024517-9d4a-4541-9e4b-d470b6033ff3.png">
<img width="1342" alt="WeChat9670d1b33db2b4113b0d01ae403d02d3" src="https://user-images.githubusercontent.com/26185772/227119776-6aee49c7-1ea6-4b74-a32f-95321927b676.png">
<img width="964" alt="WeChat0f74042ed46d250390a013e8c09bdeb0" src="https://user-images.githubusercontent.com/26185772/227120190-f315659f-9316-4f01-9da7-91364903471e.png">

### Search terms

ganache

**Comment by sshmaxime** [comment]
This is because you used `loadFixture` from `@nomicfoundation/hardhat-network-helpers`

**Comment by mjczz** [comment]
@sshmaxime yes, I know that. Does any solution can  solove this when use ```hardhat-network-helpers```

**Comment by fvictorio** [comment]
Sorry @mjczz, but as @sshmaxime explained, those helpers only work with the Hardhat network for now. The reason is that we rely on some specific JSON-RPC methods that don't exist in other networks.
