### ISSUE TITLE
Forking BSC node is not working 

### ISSUE THREAD

**Issue by xsaad67** [NomicFoundation/hardhat#3791]
I'm forking BSC Node through 
`npx hardhat node --fork https://bsc-dataseed1.binance.org --fork-block-number 26769200`

My script code is 

```
async function checkBalance() {
    const provider = new ethers.providers.JsonRpcProvider("http://localhost:8545");
    const wbnbAddress = "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c";
    const wbnbContract = await ethers.getContractAt("IERC20", wbnbAddress);
    const balance = await wbnbContract.balanceOf("0x32596E35eE58e46421585483e5463bc559A4037C");
    console.log(`WBNB balance: ${ethers.utils.formatEther(balance)} `);
}


checkBalance();
```
If i run it through it will give me an exact balance of wbnb 
`npx hardhat run scripts/bscbalance.js --network bsc`

But if i try to run it with the bsc fork it gives me an error of 
`Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="balanceOf(address)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)`

Any advice on this?

**Comment by fvictorio** [comment]
> But if i try to run it with the bsc fork it gives me an error of

How are you doing that, exactly?

Just in case, I think this is usually an error:

> const provider = new ethers.providers.JsonRpcProvider("http://localhost:8545");

You should use `hre.ethers.provider` instead. That provider will be connected to the network you chose. So, when you are using `--network bsc`, it will connect to BSC, and when you don't specify a network it will use the Hardhat network by default.

**Comment by rickuser9600** [comment]
Hi everybody, I've faced same error with you. I've tried several operations to fix it but it didn't work.
The Key to fixing this is hardhat config.
You should run in hardhat config.
```
  defaultNetwork: "hardhat",
  networks: {
    hardhat: {
      forking: {
        // enabled: true,
        // url: "https://arb1.arbitrum.io/rpc",
        url: "https://data-seed-prebsc-1-s1.binance.org:8545",
        // blockNumber: 104886305,
      }
    }, 
```
Try  "npx hardhat test"   It will be ok.   Hope your success! 
If this comment works, please follow me!
