### ISSUE TITLE
revertedWithCustomError for truffle contracts and web3

### ISSUE THREAD

**Issue by lhemerly** [NomicFoundation/hardhat#3792]
### Describe the feature

**Issue:**
The revertedWithCustomError helper in chai matchers calls .interface from the contract, but this property only exists in Ethers. It is usual to run tests with truffle contract abstractions. Making it a web3.js contract won't work either.

**Suggested fix:**
The revertedWithCustomError should receive the contract ABI, not the contract object, as the contract ABI is default for all libraries.

If you agree I can start working on the fix.

### Search terms

custom error truffle web3

**Comment by fvictorio** [comment]
Hi @lhemerly. The chai matchers are meant to be used with ethers, and we don't have plans to add support for web3 or truffle contracts. We should be clearer about that in our docs (I created [an issue](https://github.com/NomicFoundation/hardhat/issues/3812) for that), but right now we consider this out of scope for the plugin. Sorry!
