### ISSUE TITLE
A bug with deployments and getNamedAccounts

### ISSUE THREAD

**Issue by VasKonstV** [NomicFoundation/hardhat#3796]
### Version of Hardhat

2.13.0

### What happened?

Here is the code of my smart contract deployment:
`import { HardhatRuntimeEnvironment } from "hardhat/types";`
`import { DeployFunction } from "hardhat-deploy/types";`
`import { ethers } from "hardhat";`

`const func: DeployFunction = async function(hre: HardhatRuntimeEnvironment) {`
`    const {deployments, getNamedAccounts} = hre;`

`    const {deploy} = deployments;`

`    const {deployer} = await getNamedAccounts();`

`    await deploy('Vault',{`
`        from: deployer,`
`        args: ethers.utils.formatBytes32String("secret"),`
`        log: true,`
`    })`

`}`
Here is an error:

Property 'deployments' does not exist on type 'HardhatRuntimeEnvironment'.ts(2339)
Property 'getNamedAccounts' does not exist on type 'HardhatRuntimeEnvironment'.ts(2339)

### Minimal reproduction steps

Create a general TypeScript project in Hardhat and try to deploy any smart contract

**Comment by fvictorio** [comment]
Are you sure you are importing `hardhat-deploy` in your hardhat config file?

**Comment by fvictorio** [comment]
> Those errors I get in my IDE Visual Studio code. What config issue must present in this IDE?

Open a terminal and run the deployment. If you don't get those same errors, then it's probably an IDE config thing. I can't help you with that though because it depends a lot on your specific IDE and your setup.

**Comment by VasKonstV** [comment]
Here is the screen of my terminal:
![image](https://user-images.githubusercontent.com/128475226/228011886-f5fd1e8e-ee6f-44fc-9583-1eb547a54fa9.png)
No adress of the smart contract Vault

**Comment by VasKonstV** [comment]
So In my opinion, the problem is not in IDE settings

**Comment by VasKonstV** [comment]
Here is my hardhat.config.ts file:
`import { HardhatUserConfig } from "hardhat/config";`
`import "@nomicfoundation/hardhat-toolbox";`
`import './tasks/sample_tasks';`

`const config: HardhatUserConfig = {`
`  solidity: "0.8.18",`
`};`

`export default config;`

**Comment by fvictorio** [comment]
You need to add `import "hardhat-deploy;"` to enable the `hardhat-deploy` plugin. Check their docs.
