### ISSUE TITLE
Add Base Goerli support

### ISSUE THREAD

**Issue by bghughes** [NomicFoundation/hardhat#3803]
### Describe the feature

Please add support for Coinbase's [Base](https://base.org/) Goerli chain into `hardhat-etherscan`.

`Error in plugin @nomiclabs/hardhat-etherscan: Trying to verify a contract in a network with chain id 84531, but the plugin doesn't recognize it as a supported chain.`

For your reference, [here are the network details](https://docs.base.org/network-information/). Thank you! Love the plugin 🚀 

### Search terms

**Based**

**Comment by Saty248** [comment]
@fvictorio i am working on this issue.

**Comment by NickSolante** [comment]
hey is this going out any time soon?

**Comment by fvictorio** [comment]
@NickSolante this will be included in our next release (probably on Thursday, worst case next week).

**Comment by fvictorio** [comment]
Released in [`hardhat-verify@1.0.4`](https://github.com/NomicFoundation/hardhat/releases/tag/%40nomicfoundation%2Fhardhat-verify%401.0.4). Sorry for the wait!
