### ISSUE TITLE
Hardhat Etherscan API failing

### ISSUE THREAD

**Issue by quanndh** [NomicFoundation/hardhat#3805]
### Version of Hardhat

3.1.7

### What happened?

I had deployed an contract: `0x9E06904E30C2013D6454A374450d2fDa755c270F`.

But I cant verify it on etherscan. Worked on bsc testnet though.

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/47892926/228822353-35124d7b-174f-4811-9a3e-75463db4a829.png">

### Minimal reproduction steps

npx hardhat run --network mainnet scripts/deploy.js

npx hardhat verify --contract contracts/Coconut.sol:CONUT --network mainnet 0x9E06904E30C2013D6454A374450d2fDa755c270F

### Search terms

etherscan

**Comment by 0xV4L3NT1N3** [comment]
gm @quanndh, this may have been due to a small maintenance window we had on our end, it does appear your contract verification eventually went through 

https://etherscan.io/address/0x9E06904E30C2013D6454A374450d2fDa755c270F#code

**Comment by fvictorio** [comment]
Thanks for chiming in @0xV4L3NT1N3!
