### ISSUE TITLE
npx hardhat compile Nothing to compile

### ISSUE THREAD

**Issue by Aroon4020** [NomicFoundation/hardhat#3807]
### Version of Hardhat

2.12.2

### What happened?

npx hardhat compile
Nothing to compile

### Minimal reproduction steps

Steps can be found here
https://hardhat.org/hardhat-runner/docs/guides/project-setup

### Search terms

nothing to compile error

**Comment by fvictorio** [comment]
What is your issue? That message just means what it says: that there's nothing to compile. That can happen because you don't have any contracts, or because you already compiled.

Tentatively closing.
