### ISSUE TITLE
 Module '"hardhat"' has no exported member 'upgrades'.

### ISSUE THREAD

**Issue by honigkuchenbaer** [NomicFoundation/hardhat#3811]
I suddenly get the following error on running unit-tests in my 1-years-old hardhat based project using Upgradables:

> error TS2305: Module '"hardhat"' has no exported member 'upgrades'.

This happens when importing:

`import {ethers, upgrades} from 'hardhat';`

The difference between my last successful run and the latest attempt is that I have installed node_modules from scratch.
According to what I [read about](https://forum.openzeppelin.com/t/openzeppelin-upgrades-step-by-step-tutorial-for-hardhat/3580) how to use Hardhat with OpenZeppelin Upgradables, these libraries should provide everything:

```
  "devDependencies": {
    "@nomicfoundation/hardhat-network-helpers": "^1.0.6",
    "@nomiclabs/buidler": "^1.4.8",
    "@nomiclabs/hardhat-ethers": "^2.1.1",
    "@nomiclabs/hardhat-etherscan": "^3.0.3",
    "@nomiclabs/hardhat-waffle": "^2.0.3",
    "@openzeppelin/hardhat-upgrades": "^1.21.0",
    "@openzeppelin/test-helpers": "^0.5.15",
```

Apparently, the `upgrades`-object has been removed from hardhat. 

Is there any replacement?

**Comment by fvictorio** [comment]
Are you sure you're importing the plugin in the Hardhat config? You should have a `import "@openzeppelin/hardhat-upgrades"` line there.

**Comment by honigkuchenbaer** [comment]
Damn yes. This `import`-statement has been moved in my case to the end of all other imports. Putting it more to the top, it compiles again. Thank you!
