### ISSUE TITLE
Peer dependency: @types/mocha

### ISSUE THREAD

**Issue by Melty-melts** [NomicFoundation/hardhat#3826]
### Version of Hardhat

2.13.0

### What happened?

I have read through all of the `npm` dependency issue fixes I can find here in the issues and elsewhere and I'm at a total loss. I have tried forcing fixes, I've tried installing individual versions of mocha. I can't run a single script in my program except to initialize a hardhat node. I just keep getting this error:

### NPM ERR: ERESOLVE
```
npm resolution error report

While resolving: @nomicfoundation/hardhat-toolbox@1.0.2
Found: @types/mocha@10.0.1
node_modules/@types/mocha
  dev @types/mocha@"^10.0.1" from the root project

Could not resolve dependency:
peer @types/mocha@"^9.1.0" from @nomicfoundation/hardhat-toolbox@1.0.2
node_modules/@nomicfoundation/hardhat-toolbox
  dev @nomicfoundation/hardhat-toolbox@"^1.0.2" from the root project

Conflicting peer dependency: @types/mocha@9.1.1
node_modules/@types/mocha
  peer @types/mocha@"^9.1.0" from @nomicfoundation/hardhat-toolbox@1.0.2
  node_modules/@nomicfoundation/hardhat-toolbox
    dev @nomicfoundation/hardhat-toolbox@"^1.0.2" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

Any idea for a fix would be greatly appreciated.

### Minimal reproduction steps

Running any script except installing hardhat and running a hardhat node.

### Search terms

Dependency, Mocha, Conflicting

**Comment by Saty248** [comment]
did you try  installing  hardhat/toolbox individually?

**Comment by Melty-melts** [comment]
Thank you. I believe installing the latest toolbox solved it.
