### ISSUE TITLE
🔥 hardhat-foundry 👉 unable to resolve dependency tree

### ISSUE THREAD

**Issue by PedroReyes** [NomicFoundation/hardhat#3834]
### Version of Hardhat

$ npx hardhat --version
2.10.0

### Version of Forge
$ forge --version
forge 0.2.0 (388c3c0 2023-04-10T09:31:50.093051900Z)

### What happened?

Hello,

I am trying to install hardhat-foundry. 

### Minimal reproduction steps

I have already [installed build sources from Foundry following the next guide for Windows](https://getfoundry.sh/). However, when I try to install Foundry NPM package from hardhat using the next command:

`npm i @nomicfoundation/hardhat-foundry`

I get the next output:

``` bash
# npm resolution error report

While resolving: reinvestor@1.0.0
Found: hardhat@2.10.0
node_modules/hardhat
  dev hardhat@"2.10.0" from the root project

Could not resolve dependency:
peer hardhat@"^2.12.6" from @nomicfoundation/hardhat-foundry@1.0.1
node_modules/@nomicfoundation/hardhat-foundry
  @nomicfoundation/hardhat-foundry@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

### Search terms

hardhat, foundry, testing

**Comment by PedroReyes** [comment]
Hello,

Simply updating hardhat to the latest version was solved—no need to open a ticket for this. I rushed to create it. 

`"hardhat": "2.13.1",`

**Comment by fvictorio** [comment]
Thanks for closing it and letting us know!
