### ISSUE TITLE
Type addressish

### ISSUE THREAD

**Issue by RenanSouza2** [NomicFoundation/hardhat#3856]
### Describe the feature

Has there been a discussion of creating an address like type?
This way an argument could be an string address or an signer so it wouldn't be needed to use signer.address everytime

thank you

### Search terms

typescript

**Comment by fvictorio** [comment]
Hi @RenanSouza2, the new major version of ethers (v6) has [exactly that](https://docs.ethers.org/v6/api/address/#AddressLike). We are working on adding support for it, check this issue for more info: https://github.com/NomicFoundation/hardhat/issues/3639
