### ISSUE TITLE
"^2.13.1,  errors in your config file

### ISSUE THREAD

**Issue by boxingcoder00** [NomicFoundation/hardhat#3860]
### Version of Hardhat

2.13.1 

### What happened?

Issue : " errors in your config file " . 

I was doing "npx hardhat compile" and module was not being found so I did  " _npm install --save-dev @nomicfoundation/hardhat-toolbox_" then

 _" __npm install --save-dev @nomicfoundation/hardhat-toolbox @nomicfoundation/hardhat-network-helpers @nomicfoundation/hardhat-chai-matchers @nomiclabs/hardhat-ethers @nomiclabs/hardhat-etherscan chai ethers hardhat-gas-reporter solidity-coverage @typechain/hardhat typechain @typechain/ethers-v5 @ethersproject/abi @ethersproject/providers___

then i got the error in the picture, could it be the code in the picture below ?? since i couldnt deploy it because of the error to compile. 

![s4](https://user-images.githubusercontent.com/111091683/232180386-28557d7a-5209-4a25-afc0-1d21be5f80d5.png)
 
![errpr5](https://user-images.githubusercontent.com/111091683/232180533-0439ccee-aab9-48d1-9c1c-62a681323d42.png)

### Minimal reproduction steps

npx hardhat compile 

### Search terms

hardhat

**Comment by JoeyKhd** [comment]
@boxingcoder00 

This is not a Hardhat issue it seems, please use the config() function after importing dotenv (as per their documentation)

Please try the following:
```
const dotenv = require('dotenv');
dotenv.config();
```

or 

```
require('dotenv').config()
```

Good luck! :)

**Comment by fvictorio** [comment]
Thanks for responding @JoeyKhd!
