### ISSUE TITLE
Next.js HH5: HardhatContext is not created.

### ISSUE THREAD

**Issue by paradise** [NomicFoundation/hardhat#3878]
Hi, I'm trying to use hardhat in my nextjs application. I need to deploy contracts from my TS code during runtime (when user goes to `/api/contract/create` page). 

I'm trying to do it with HRE, but I receive HH5: HardhatContext is not created. Is there any way to create this context manually? 

In other words, I don't want to use scripts/tasks (moreover, I can not do it on my Vercel servless hosting), I want to run code by myself.

**Comment by fvictorio** [comment]
Creating an HRE programmatically is not possible right now (see https://github.com/NomicFoundation/hardhat/issues/3042).
