### ISSUE TITLE
Chaining event matchers with balance changing matchers 

### ISSUE THREAD

**Issue by Hicham010** [NomicFoundation/hardhat#3879]
### Version of Hardhat

2.12.6

### What happened?

Combing event matchers with balance-changing matchers will ignore the event matchers. 

The example below should throw an error because `WithdrawPaymentt` is misspelt and the second event argument should be 500 instead of 5000. But when this test is run it will pass.

### Minimal reproduction steps

```
    it("Should withdraw the payment for the tokenizer", async function () {
      const { farmer, tradeCoinProduct } = await loadFixture(
        deployTradeCoinWith5Products
      );

      expect(
        await tradeCoinProduct.pendingWeiForWithdrawal(farmer.address)
      ).to.eq(ethers.BigNumber.from(500));

      await expect(tradeCoinProduct.connect(farmer).withdrawPayment())
        .to.emit(tradeCoinProduct, "WithdrawPaymentt")
        .withArgs(farmer.address, 5000)
        .to.changeEtherBalances(
          [tradeCoinProduct.address, farmer.address],
          [-500, 500]
        );

      expect(
        await tradeCoinProduct.pendingWeiForWithdrawal(farmer.address)
      ).to.eq(ethers.BigNumber.from(0));

      await expect(tradeCoinProduct.connect(farmer).withdrawPayment())
        .to.emit(tradeCoinProduct, "WithdrawPayment")
        .withArgs(farmer.address, 0)
        .to.changeEtherBalances(
          [tradeCoinProduct.address, farmer.address],
          [0, 0]
        );
    });
```

### Search terms

Chai Matchers

**Comment by fvictorio** [comment]
Thanks for reporting this @Hicham010. The underlying issue here is the same as in https://github.com/NomicFoundation/hardhat/issues/3667; we should throw an error when different matchers are chained (for now, maybe later we'll allow that, but chaining async stuff in chai is surprisingly hard). I'm going to close this issue on favor of that one.
