### ISSUE TITLE
hardhat-ethers signer.sendTransaction() does not correctly estimate gas, but does not OOG

### ISSUE THREAD

**Issue by pmckelvy1** [NomicFoundation/hardhat#3880]
### Version of Hardhat

2.12.2

### What happened?

When using signer.sendTransaction(), the transaction will run without failure and will commit state that is updated during the course of the transaction, but the transaction will not run to completion (certain state that should have been updated at the end of the tx is not updated) and does not throw any errors.

I noticed the bug when using an empty `try/catch` block inside of a loop that iterates over an array of addresses an makes calls to external contracts to update state.  the transaction has the above behavior until I do one of two things:
1) add an event after the loop
2) add `gasLimit: ethers.BigNumber.from('1000000')` to the tx

### Minimal reproduction steps

package.json:
```
    "@nomicfoundation/hardhat-chai-matchers": "^1.0.3",
    "@nomicfoundation/hardhat-network-helpers": "^1.0.8",
    "@nomicfoundation/hardhat-toolbox": "^2.0.1",
    "@nomiclabs/hardhat-ethers": "^2.0.3",
    "@typechain/ethers-v5": "^7.2.0",
    "@typechain/hardhat": "^2.3.1",
"hardhat": "^2.12.2",
"@nomicfoundation/hardhat-toolbox": "^2.0.1"
"ethers": "^5.5.2",
    "typechain": "^5.2.0",
    "typescript": "^4.4.2",
"chai": "^4.3.4",
    "@types/chai": "^4.3.0",
    "@types/mocha": "^9.0.0",
```

solidity:
```
pragma solidity 0.8.17;
import "hardhat/console.sol";

contract Counter {
    uint256 public counter;
    constructor() {}

    function count() external {
        console.log("count start");
        counter += 1;
        console.log("count end");
    }
}

contract CounterBroken {
    uint256 public counter;
    constructor() {}
}

contract TryCatchBug {
    event Done();

    address[] public addys;

    constructor(address[] memory _addys) {
        addys = _addys;
    }

    function bug() external {
        bugInternal();
    }

    function bugInternal() internal {
        for (uint256 i = 0; i < addys.length; i++) {
            try Counter(addys[i]).count() {} catch {}
        }
        // uncomment this line to allow the tests to pass
        // emit Done();
    }
}
```
typescript test:
```
import { expect } from 'chai'
import { ethers } from 'hardhat'
import {
    Counter,
    CounterBroken,
    TryCatchBug
} from '../typechain'

describe('TryCatchBug', () => {
    // Assets
    let tryCatchBug: TryCatchBug
    let countersBroken: CounterBroken[] = []
    let counters: Counter[] = []

    let numBroken = 10
    let num = 2

    beforeEach(async () => {
        const counterBrokenFactory = await ethers.getContractFactory('CounterBroken')
        for (let i = 0; i < numBroken; i++) {
            countersBroken.push(await counterBrokenFactory.deploy())
        }

        const counterFactory = await ethers.getContractFactory('Counter')
        for (let i = 0; i < num; i++) {
            counters.push(await counterFactory.deploy())
        }

        const tryCatchBugFactory = await ethers.getContractFactory('TryCatchBug')
        tryCatchBug = await tryCatchBugFactory.deploy([...countersBroken.map(o => o.address), ...counters.map(o => o.address)])
    })

    describe('Does it have a bug', () => {
        it('does not have a bug', async () => {
            const tx = await tryCatchBug.populateTransaction.bug()
            
            const signers = await ethers.getSigners()
            const alice = signers[0]

            await alice.sendTransaction({
                data: tx.data,
                to: tx.to,
                // uncomment this line to allow the tests to pass
                // gasLimit: ethers.BigNumber.from('1000000')
            })

            for (const o of countersBroken) {
                expect(await o.counter()).equal(0)
            }
            for (const o of counters) {
                expect(await o.counter()).equal(1)
            }
        })
    })
})
```

the solidity has console.log statements to show where the transaction stops executing. the output should look like:
```
  TryCatchBug
    Does it have a bug
count start
count end
count start
      1) does not have a bug
```

there is 1 line in the solidity file and 1 line in the test file that, if either is uncommented, will make things work and allow the tests to pass (they are each marked with a comment detailing this).

### Search terms

hardhat, hardhat-ethers, ethers, gas estimation, try, catch, try/catch

**Comment by fvictorio** [comment]
Hey @pmckelvy1, thanks for opening this and sorry for not responding before.

To clarify: there isn't a bug related to the execution here. The result is correct. What's happening is that one of the external calls that are executed inside the transaction produces an OOG, but since it's inside a try/catch, the "main" transaction succeeds. (Hopefully this makes sense, but if it doesn't, I can explain it in more detail.)

That being said, I think hardhat could produce a better gas estimation that doesn't produce internal OOGs. I opened https://github.com/NomicFoundation/hardhat/issues/4078 to track that, so I'm going to close this issue in favor of that one.

**Comment by fvictorio** [comment]
Actually, I take it back: the `eth_estimateGas` behavior is fine because it matches what geth does, which is our policy in these cases. We could maybe give a "better" estimate by taking into account internal OOGs, but that would mean that the same tests wouldn't pass in a geth node, which is not ideal.
