### ISSUE TITLE
Shanghai support is missing PUSH0 support.

### ISSUE THREAD

**Issue by ekpyron** [NomicFoundation/hardhat#3883]
The latest release is supposedly supporting Shanghai, but from what I can tell (see e.g. CI in https://github.com/ethereum/solidity/pull/14158, in particular https://app.circleci.com/jobs/github/ethereum/solidity/1307176) indicates to me that there is no full support for PUSH0 just yet.

**Comment by fvictorio** [comment]
Hey @ekpyron, the Shanghai support is there, the problem was that those tests were still using an older hardfork. I fixed that now and confirmed locally that they pass with solc's nightly build.
