### ISSUE TITLE
Network time in different test files are not independent

### ISSUE THREAD

**Issue by akkien** [NomicFoundation/hardhat#3898]
My project has 2 test files. Both of them use follow rpc to increase the timestamp in test:
```solidity
await network.provider.send("evm_increaseTime", [timeAmount]);
await network.provider.send("evm_mine");
```
It works well if I run: `hardhat test A.test.ts` or `hardhat test B.test.ts`. But when I run both of them `hardhat test`. The time is not manipulate right anymore and the test failed.

Is there any way to make 2 test files run independent from each other? 

Thank you!

**Comment by fvictorio** [comment]
> Is there any way to make 2 test files run independent from each other?

Hey @akkien, running tests in parallel (`npx hardhat test --parallel`) will create a different network for each test file.

Alternatively, you can reset the network with `hardhat_reset` in a `before` hook of each test.

**Comment by akkien** [comment]
Thank you, @fvictorio!
