### ISSUE TITLE
Attach deployed contract to ContractFactory including sourceMap

### ISSUE THREAD

**Issue by vsmelov** [NomicFoundation/hardhat#3902]
## My goal:

run tests on blockchain-fork (e.g. BSC-mainnet fork)
interact with already deployed contracts on blockchain (e.g. MasterChefV3 - https://bscscan.com/address/0x556b9306565093c855aea9ae92a594704c2cd59e#code )

in case if during a test some error appeared inside deployed 0x556b9306565093c855aea9ae92a594704c2cd59e I want to see this error location inside sources

## What do I have now:

> npx hardhat test

```
  1) SpotV2MasterchefV3
       With deposit
         Should withdraw liquidity:
     Error: VM Exception while processing transaction: reverted with an unrecognized custom error
      at <UnrecognizedContract>.<unknown> (0x556b9306565093c855aea9ae92a594704c2cd59e)
      at SpotV2MasterchefV3._decreaseLiquidityNFT (src/DeFi/Spot/SpotV2MasterchefV3.sol:698)
      at SpotV2MasterchefV3.withdrawEntireDeposit (src/DeFi/Spot/SpotV2MasterchefV3.sol:534)
      at HardhatNode._mineBlockWithPendingTxs (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:1815:23)
      at HardhatNode.mineBlock (node_modules/hardhat/src/internal/hardhat-network/provider/node.ts:504:16)
```

I don't like this

```
      at <UnrecognizedContract>.<unknown> (0x556b9306565093c855aea9ae92a594704c2cd59e)
```

it's impossible to debug

I would like to have error message and pointer to source line with a failing code

## What did I try:

I tried to download sources from bscscan and compile it by myself

I got theses artifacts

MasterChefV3.json:
```
{'_format': 'hh-sol-artifact-1',
 'abi': [...],
 'bytecode': '...',
 'contractName': 'MasterChefV3',
 'deployedBytecode': '...',
 'deployedLinkReferences': {},
 'linkReferences': {},
 'sourceName': 'src/external/downloads/MasterChefV3/MasterChefV3.sol'
}
```

MasterChefV3.dbg.json:
```
{
  "_format": "hh-sol-dbg-1",
  "buildInfo": "../../../../../build-info/b2a005c7913e2c839de483c0b16d6d24.json"
}
```

inside my test I do this

```
  const masterchefAddress = "0x556b9306565093c855aea9ae92a594704c2cd59e";
  before(async function () {
    ...
    const MasterChefV3 = await ethers.getContractFactory('MasterChefV3');
    const masterchef = MasterChefV3.attach(masterchefAddress);
  }
```

so I expected hardhat to fetch all info about the contract from Artifact including SourceMap and give me detailed transaction error message and solidity traceback, but it did not help

## Question

How can I get detailed transaction error message and solidity traceback in my test for external contract for which I have all sources?

**Comment by fvictorio** [comment]
Hi @vsmelov, make sure that you are compiling the contract with the same settings. In this case this means using solc 0.8.10 and 999 optimizer runs. You might need to use [overrides](https://hardhat.org/hardhat-runner/docs/advanced/multiple-solidity-versions#multiple-solidity-versions) to get this done.
