### ISSUE TITLE
I can't fork zkSync ERA ?

### ISSUE THREAD

**Issue by ubnta** [NomicFoundation/hardhat#3903]
### Version of Hardhat

2.14.0

### What happened?

When I fork the zksync era network, I can't connect to any dApp.

```javascript
require("@nomicfoundation/hardhat-toolbox");

/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  solidity: "0.8.18",
  networks: {
    hardhat: {
      chainId: 324,
      forking: {
        url: "https://mainnet.era.zksync.io",
        blockNumber: 2865600,
      }
    }
  }
};
```

that my `hardhat.config.js` file and i get this error : 
![Screenshot from 2023-05-07 17-12-49](https://user-images.githubusercontent.com/132830524/236682785-1e7da1a3-0e6d-4781-8b9f-355f7cd87092.png)

### Minimal reproduction steps

`npx hardhat node`

the last block number seems to be correct, but I can't interact with any contracts
![Screenshot from 2023-05-07 17-12-11](https://user-images.githubusercontent.com/132830524/236682739-d9409c9f-80be-41fc-b9b5-e0ee1b85c9c5.png)

### Search terms

hardhat-zksync fork-zksync

**Comment by fvictorio** [comment]
@ubnta the error you are getting doesn't (necessarily) mean that forking is not working, it just means that the call failed. This could be expected or not.

Can you provide a more complete example? For example, which address you are interacting with, which method you are calling and with what arguments.

**Comment by dutterbutter** [comment]
Current zksync implementation does not support `--fork` feature. This is intended to be implemented in the future.
