### ISSUE TITLE
Unable to verify contract on Sepolia due to Error HH210: Redefinition of task verify failed.

### ISSUE THREAD

**Issue by oliviertruquet** [NomicFoundation/hardhat#3904]
Hardhat version: 2.14.0
Solidity Version:0.8.18

How to reproduce?

Create a simple ERC 20 token (ownable) and follow the steps to deploy and verify the token on Sepolia as described in this [article](https://hardhat.org/hardhat-runner/docs/guides/verifying).

If you include the following line in your JS config: "require("@nomicfoundation/hardhat-verify");", you get the following error: Error HH210: Redefinition of task verify failed.

If you do not include it, you get a timeout error. 

**Question**
How to solve this issue?

**Comment by fvictorio** [comment]
Hey @oliviertruquet, what probably happened is that you had `hardhat-toolbox` already required. The current version of the Toolbox uses the old `@nomiclabs/hardhat-etherscan` plugin, which also defines a `verify` task, and taht causes an error.

We are going to release a new version of the Toolbox this week that includes the new verification plugin.
