### ISSUE TITLE
Add Infura Sepolia Faucet link to Tutorial deploying-to-a-live-network

### ISSUE THREAD

**Issue by anataliocs** [NomicFoundation/hardhat#3906]
### Describe the feature

Adding url to Infura faucet, https://www.infura.io/faucet/sepolia to:

https://hardhat.org/tutorial/deploying-to-a-live-network

<img width="647" alt="image" src="https://user-images.githubusercontent.com/4750426/236892325-bcd700ad-baa2-49d8-a126-b8424ec0796b.png">

**Comment by fvictorio** [comment]
Closed by #3907 I think?
