### ISSUE TITLE
[Hardhat-Toolbox] Can not import deployMockContract from ethereum-waffle

### ISSUE THREAD

**Issue by vladikopl01** [NomicFoundation/hardhat#3909]
### Version of Hardhat

2.14.0

### What happened?

I have been creating some tests and wanted to import `deployMockContract` from `ethereum-waffle`. 

It seems `ethereum-waffle` is already installed in `@nomicfoundation/hardhat-toolbox` which has inside `@nomicfoundation/hardhat-chai-matchers` which has inside `ethereum-waffle`. But I tried to look through the packages and did not find any of the needed export. So I have tried to install `ethereum-waffle` on my own. 

Then get an error from `@nomicfoundation/hardhat-chai-matchers` that I had already two instances of `ethereum-waffle` and followed me to look at migrating docs. There are suggestions, firstly, uninstall `ethereum-waffle`, and then, install `@nomicfoundation/hardhat-chai-matchers`. So, as it said, I uninstalled `ethereum-waffle`, but then reinstalled a `@nomicfoundation/hardhat-toolbox` to update it if my workarounds could break something. As you might expect, this did not help me at all.

Please, provide a description or reference of how these packages are working and if there is a way to import `deployMockContract` from `ethereum-waffle`. Would appreciate any help 

### Minimal reproduction steps

1. Create hardhat typescript project template from `npx hardhat` command.
2. Make sure to use `hardhat-toolbox` package in this project.
3. Try to import `deployMockContract` in any typescript file in this project from `hardhat-toolbox` package.

### Search terms

Hardhat-toolbox, mock, deployMockContract, MockContract, ethereum-waffle, hardhat-chai-matchers

**Comment by fvictorio** [comment]
> It seems ethereum-waffle is already installed in @nomicfoundation/hardhat-toolbox which has inside @nomicfoundation/hardhat-chai-matchers which has inside ethereum-waffle. 

I don't think this is correct? The chai matchers don't depend on `ethereum-waffle`.

**Comment by vladikopl01** [comment]
Thought `hardhat-chai-matchers` depends on `ethereum-waffle` as it provides some similar interfaces with chai
