### ISSUE TITLE
verification is not usable comparing to foundry

### ISSUE THREAD

**Issue by GopherJ** [NomicFoundation/hardhat#3911]
### Describe the feature

hardhat contract verification speed is too slow which makes it unusable comparing to foundry. For the same contracts, foundry takes a few seconds to verify while hardhat takes minutes

**Comment by fvictorio** [comment]
Hey @GopherJ, thanks for reporting this. We recently re-wrote our verification plugin and I don't see how it could take _minutes_ to verify something. Every time I've used it the verification worked in seconds (even with the previous version).

But if this happens to you again and you can provide some way to reproduce it, I'll re-open this issue.
