### ISSUE TITLE
BUG REPORT 

### ISSUE THREAD

**Issue by karnel24** [NomicFoundation/hardhat#3933]
### Version of Hardhat

2.14.0

### What happened?

I tried to run the command 
*/
npx hardhat init 
/*
It shows error

### Minimal reproduction steps

Provide a source code to avoid such bug

**Comment by HFFP** [comment]
just run
`npx hardhat`

**Comment by fvictorio** [comment]
As @HFFP said, `npx hardhat init` doesn't exist. If you saw that command in a tutorial or something, please let me know.
