### ISSUE TITLE
Access List (EIP-2930)

### ISSUE THREAD

**Issue by barakman** [NomicFoundation/hardhat#3934]
### Describe the feature

[EIP 2930](https://eips.ethereum.org/EIPS/eip-2930) adds a transaction type which contains a list of addresses and storage keys that the transaction plans to access, AKA *Access List*.

All slots in the list are paid in advance, at a discount relative to the cost of accessing those not in the list.
Of course, any slot specified in the list but not accessed during the transaction, will be "paid for nothing".

An example of a transaction which specifies an access list:
```
const tx = {
    from: walletAddress,
    to: contractAddress,
    data: transactionData,
    value: 0,
    type: 1,
    accessList: [
        {
            address: contractAddress,
            storageKeys: [
                "0x0000000000000000000000000000000000000000000000000000000000000042",
                "0x0000000000000000000000000000000000000000000000000000000000000053",
            ],
        },
        {
            address: usdcTokenAddress,
            storageKeys: [
                "0x0000000000000000000000000000000000000000000000000000000000000000",
                "0x0000000000000000000000000000000000000000000000000000000000000001",
                "0x0000000000000000000000000000000000000000000000000000000000000002",
            ],
        },
    ],
};
```

The primary difficulty is of course computing the access-list for a specific transaction in advance, as there may be several different contracts involved in the transaction, and in each one of them, different storage slots may be accessed depending on the specific details of the transaction.

Luckily, the Go-Ethereum (GETH) client supports the `eth_createAccessList` RPC method for conveniently determining the list of all storage slots expected to be accessed during a given transaction.

You can find an example of this in [web3.js](https://web3js.readthedocs.io/en/v1.7.0/web3-eth.html#createaccesslist).
I'm not sure whether or not ethers.js (which HardHat relies on as its Web3 backbone) supports this method as well.

HardHat already supports [various JSON RPC methods](https://hardhat.org/hardhat-network/docs/reference#json-rpc-methods-support).

I would like to request adding support also for the `eth_createAccessList` RPC method.

Thanks

### Search terms

EIP-2930, Access List, eth_createAccessList

**Comment by fvictorio** [comment]
Hi @barakman, https://github.com/NomicFoundation/hardhat/issues/1423 already tracks this. I'm going to close this as a duplicate, but please upvote/comment there to signal that you want this.
