### ISSUE TITLE
Events are not emitted when running Hardhat local node

### ISSUE THREAD

**Issue by CristianRicharte6** [NomicFoundation/hardhat#3935]
### Version of Hardhat

^2.14.0

### What happened?

When I run a local node with Hardhat using `npx hardhat node`, deploy contracts and interact with them, they do not emit any event. The events do not appear on the terminal and I also have a script listening for the events, and It does not get any (I tried already in testnet, and the script gets all the events, but not in the local hardhat node)

I adjusted the JSON-RPC to url: `HTTP://127.0.0.1:8545` to retrieve the events. Is it something Hardhat does not support?

![image](https://github.com/NomicFoundation/hardhat/assets/102038261/3957a7d1-77fb-492e-b42f-c00d6e9850c4)

Thanks in advance.

### Minimal reproduction steps

- Run: `npx hardhat node` .
- Set new URL to deploy the contracts to the local node. (JSON-Provider)
- Deploy contracts.
- Run a server to listen for the events & subscribe to the events.
- Call a Smart contract function that will trigger the events.
- Events are not picked up by the listener. (It works in testnet)

**Comment by CristianRG4AL** [comment]
Solved!

**Comment by RevanthGundala** [comment]
> Solved!

How were you able to fix this?

**Comment by CristianRicharte6** [comment]
> > Solved!
> 
> How were you able to fix this?

@RevanthGundala 
The problem was very simple, I just needed to remove the last `/` from the HTTP JSON-RPC server (`http://127.0.0.1:8545/`). As with the slash symbol, it was not able to identify the URL correctly.
