### ISSUE TITLE
 Failed to send contract verification request:-32700

### ISSUE THREAD

**Issue by JoscelynFarr** [NomicFoundation/hardhat#3943]
### Version of Hardhat

2.14.0

### What happened?

when I try to using hardhat to verify my deployed contract, it shows:

Error in plugin @nomiclabs/hardhat-etherscan: Failed to send contract verification request.
Endpoint URL: xxxx
The HTTP server response is not ok. Status code: 400 Response text: {"jsonrpc":"2.0","id":null,"error":{"code":-32700,"message":"Parse error"}}

The command is  `npx hardhat verify --network arbitrumtest`

### Minimal reproduction steps

This is the hardhat.config.ts
`import { HardhatUserConfig } from "hardhat/config";
import "@nomicfoundation/hardhat-toolbox";

module.exports = {
  solidity: {
    version: "0.8.9",
    settings: {
      optimizer: {
        enabled: true,
        runs: 200,
      },

    },
  },
  networks: {
    arbitrumtest: {
      chainId: 421613,
      url: "xxx",
      accounts: ["xxx"],
      gas: 2100000,
      gasPrice: 8000000000,
      allowUnlimitedContractSize: true
    }
  },
  etherscan: {
    apiKey: {
      arbitrumtest: "xxx",
    },
    customChains: [
      {
        network: "arbitrumtest",
        chainId: 421613,
        urls: {
          apiURL: "xxx",
        },
      },
    ],
  },
};

`

**Comment by fvictorio** [comment]
Hi @JoscelynFarr, are you sure that this wasn't a temporary problem in the explorer?

And if it's not, those reproduction steps are not enough for us to look into this. At the very least you should include the code of the contract you are trying to verify (ideally a very minimal version of it)

Tentatively closing this, but will re-open if you can confirm that this still happens and you can provide complete reproduction steps.

**Comment by JoscelynFarr** [comment]
Sure
But I am just trying to verify the example contract which still has this problems. I will submit the contract address and the original code.

The address is on arbitrum testnet: 0xb60Be2a034CD239149159D59a3D0EE20bBd5f84F
Ande the command is ` npx hardhat verify --network arbitrumtest 0xb60Be2a034CD239149159D59a3D0EE20bBd5f84F 1684426253`

**Comment by JoscelynFarr** [comment]
```
// SPDX-License-Identifier: UNLICENSED

pragma solidity ^0.8.9;
// Uncomment this line to use console.log
// import "hardhat/console.sol";
contract Lock {

    uint public unlockTime;

    address payable public owner;

    event Withdrawal(uint amount, uint when);

    constructor(uint _unlockTime) payable {
        require(
            block.timestamp < _unlockTime,
            "Unlock time should be in the future"
        );

        unlockTime = _unlockTime;
        owner = payable(msg.sender);
    }

    function withdraw() public {
        // Uncomment this line, and the import of "hardhat/console.sol", to print a log in your terminal
        // console.log("Unlock time is %o and block timestamp is %o", unlockTime, block.timestamp);

        require(block.timestamp >= unlockTime, "You can't withdraw yet");
        require(msg.sender == owner, "You aren't the owner");

        emit Withdrawal(address(this).balance, block.timestamp);

        owner.transfer(address(this).balance);
    }
}

**Comment by JoscelynFarr** [comment]
@fvictorio Is that info enough?

**Comment by fvictorio** [comment]
I'll take a look.

**Comment by fvictorio** [comment]
Hi @JoscelynFarr, I gave this a try and was able to verify a contract in the Arbitrum testnet.

Please try upgrading to the latest version of the `hardhat-verify` plugin and try again.

If you are still running into issues, please create a *minimal* reproduction example and open a new issue.
