### ISSUE TITLE
Contract verification is failing with "Unexpected token < in JSON at position 4" on custom chains

### ISSUE THREAD

**Issue by beshup** [NomicFoundation/hardhat#3957]
### Version of Hardhat

2.10.1

### What happened?

I'm trying to verify a contract on Arbitrum Goerli (https://chainlist.org/chain/421613) and Optimism Goerli (https://chainlist.org/chain/420), but keep getting this error: `Unexpected token < in JSON at position 4`. I've tried the programmatic verification task ("verify:verify") as well as verifying via the CLI, and get the same error each time. 

Optimism Goerli API endpoint docs: https://docs.optimism.etherscan.io/v/optimistic-goerli-etherscan
Arbitrum Goerli API endpoint docs: https://docs.arbiscan.io/getting-started/endpoint-urls

### Minimal reproduction steps

In your hardhat config, you need something along the lines of:

```
etherscan: {
    apiKey: {
      goerliOptimism: process.env.OPTIMISMSCAN_API_KEY || "",
      goerliArbitrum: process.env.ARBITRUMSCAN_API_KEY || "",
    },
    customChains: [
      {
        network: "goerliOptimism",
        chainId: 420,
        urls: {
          apiURL: "https://api-goerli-optimistic.etherscan.io/",
          browserURL: "https://goerli-optimism.etherscan.io/",
        },
      },
      {
        network: "goerliArbitrum",
        chainId: 421613,
        urls: {
          apiURL: "https://api-goerli.arbiscan.io/",
          browserURL: "https://goerli.arbiscan.io/",
        },
      },
    ],
  }
```

and you can attempt to verify:

Arbitrum Goerli: `0xAA45a6e4e1E6e43c14B366Dd0228874fb1DC0eF9` (no constructor args)
CLI: `npx hardhat verify --network goerliArbitrum 0xAA45a6e4e1E6e43c14B366Dd0228874fb1DC0eF9`

Optimism Goerli: `0x4e0AfBa59894060369881f4Bc9ba05731A4119f1` (no constructor args)
CLI: `npx hardhat verify --network goerliOptimism 0x4e0AfBa59894060369881f4Bc9ba05731A4119f1`

### Search terms

verification arbitrum goerli optimism goerli

**Comment by beshup** [comment]
Looks like I just resolved this, the api urls on both optimism and arbitrum's docs were wrong, they needed "/api" appended

**Comment by n00b21337** [comment]
I had the same problem when I was using wrong url for Gnosis chain had
`"apiURL: "https://api.gnosisscan.io/"
`
needed to be

`apiURL: "https://api.gnosisscan.io/api",`

**Comment by fvictorio** [comment]
We should show a better error in these cases, I opened https://github.com/NomicFoundation/hardhat/issues/3997 to track that.
