### ISSUE TITLE
Hardhat not supporting export

### ISSUE THREAD

**Issue by galadd** [NomicFoundation/hardhat#3963]
The issue title doesn’t do justice. I am writing a javascript program that generates sdk api code for Solidity programs in hardhat environment, but it seems like the hardhat config file doesn’t support export. My assumption is that there's a restriction in hardhat, so I thought it might be best to open an issue about it to support programs that want to function in hardhat environment

**Comment by galadd** [comment]
Dear @fvictorio,

I sincerely apologize for missing your comment earlier. I am currently working on developing an SDK generator for Solidity programs, beginning with the Hardhat framework. Initially, I took a wrong approach and mistakenly believed it was a restricted error specific to Hardhat for network uri export. However, I soon realized that I could find a solution by adjusting my approach. I regret the delay in my response and appreciate your understanding.

Thank you

**Comment by fvictorio** [comment]
No problem at all, thanks for responding!
