### ISSUE TITLE
TypeError when try to deploy using Hardhat: "TypeError: this._read is not a function"

### ISSUE THREAD

**Issue by akachi1409** [NomicFoundation/hardhat#3971]
### Version of Hardhat

2.14.1

### What happened?

I installed hardhat and wrote the simple smart contract.

I have succeed in deploying the contract some days ago, but when I try it now it has the following error.

```
TypeError: this._read is not a function
    at BodyReadable.Readable.read (internal/streams/readable.js:465:10)
    at maybeReadMore_ (internal/streams/readable.js:615:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Please check and help me how to fix this, thank you.

### Minimal reproduction steps

It's simple to reproduce the bug

`yarn hardhat run scripts/deploy.js --network testnet`

**Comment by fvictorio** [comment]
Hi @akachi1409, sorry but those reproduction steps are not enough. Please share all the relevant code or (even better) create a repo with a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

Tentatively closing this, but I'll re-open if you can provide that.
