### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'startsWith')

### ISSUE THREAD

**Issue by tovarnakM** [NomicFoundation/hardhat#3976]
Hi, after the contract is successfully deployed and I try to verify it using `npx hardhat verify --network customNetwork 0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9` I see:

<img width="1532" alt="Screenshot 2023-06-02 at 15 36 11" src="https://github.com/NomicFoundation/hardhat/assets/36849758/575bb45a-359d-4be9-a4b4-74cdd8f7ce15">

This is my `hardhat.config.ts` file:

<img width="775" alt="Screenshot 2023-06-02 at 17 35 24" src="https://github.com/NomicFoundation/hardhat/assets/36849758/dc4080b2-8573-4843-a6ed-9ea275807ee2">

The endpoint is called and the code under the endpoint is executed properly.

Thanks a lot for any help.

**Comment by fvictorio** [comment]
Hey @tovarnakM, we recently published a new version of this plugin, can you give it a try?

It's not included in the toolbox yet, so you'll have to install it manually and avoid including the toolbox or the previous version of the plugin. Assuming npm 7 or later, you can do it like this:

```
npm i hardhat @nomicfoundation/hardhat-verify
```

and then using this hardhat config:

```js
require("@nomicfoundation/hardhat-verify")

module.exports = // ...
```

Of course, if you need to use some other plugin, like `hardhat-ethers`, you'll have to install it too.

**Comment by fvictorio** [comment]
I'm going to assume this is working now. Please comment if it isn't.
