### ISSUE TITLE
there should be a way to disable the prompt for telemetry without asking the user

### ISSUE THREAD

**Issue by wighawag** [NomicFoundation/hardhat#4012]
### Version of Hardhat

2.14.1

### What happened?

I have a template, that setup everything on one command
It run several process in parallele including one process to watch and compile contracts and other watching for artifact and deploying 

The issue is that if someone use this template and have never used hardhat before, the 2 processes will ask the user the same question

Furthermore, it is not that clear to the user why its process is waiting for.

I tried to set in my template's config but it still ask the user the question

```
analytics: {enabled: false},
```

### Minimal reproduction steps

This assume you have zellij installed but you could follow the README instruction and run each process separately

```bash
rm ~/.config/hardhat-nodejs/telemetry-consent.json
npx degit wighawag/jolly-roger your-app-folder
cd your-app-folder
# edit contracts/hardhat.config.ts to add `analytics: {enabled: false},`
pnpm i
pnpm start
```

Actually if you want to test without zellij, pnpm offer a parallel mode to execute multiple task and here the issue would be even worse, as there would be no way for the user to interact with the questions

**Comment by fvictorio** [comment]
Makes sense. Would an environment variable do the trick for you? Something like `HARDHAT_DISABLE_TELEMETRY_PROMPT`

**Comment by wighawag** [comment]
yes, that should do it
