### ISSUE TITLE
Hardhat Verify list networks expecting address parameter 

### ISSUE THREAD

**Issue by clauBv23** [NomicFoundation/hardhat#4023]
### Version of Hardhat

2.15.0

### What happened?

In the hardhat-verify documentation when explaining [Multiple API keys and alternative block explorers](https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-verify#multiple-api-keys-and-alternative-block-explorers) says that the way to see the entire supported networks list is running:

`npx hardhat verify --list-networks`

But when using that command the following error is received:
```
 Error in plugin @nomicfoundation/hardhat-verify: You didn’t provide any address. Please re-run the 'verify' task with the address of the contract you want to verify.

MissingAddressError: You didn’t provide any address. Please re-run the 'verify' task with the address of the contract you want to verify.
    at SimpleTaskDefinition.action (/home/claudia/projects/clau/usingHardhatVerify/node_modules/@nomicfoundation/hardhat-verify/src/index.ts:206:9)
    at Environment._runTaskDefinition (/home/claudia/projects/clau/usingHardhatVerify/node_modules/hardhat/src/internal/core/runtime-environment.ts:330:35)
    at Environment.run (/home/claudia/projects/clau/usingHardhatVerify/node_modules/hardhat/src/internal/core/runtime-environment.ts:163:25)
    at /home/claudia/projects/clau/usingHardhatVerify/node_modules/hardhat/src/internal/core/runtime-environment.ts:289:29
    at SimpleTaskDefinition.action (/home/claudia/projects/clau/usingHardhatVerify/node_modules/@nomicfoundation/hardhat-verify/src/index.ts:155:44)
    at Environment._runTaskDefinition (/home/claudia/projects/clau/usingHardhatVerify/node_modules/hardhat/src/internal/core/runtime-environment.ts:330:35)
    at Environment.run (/home/claudia/projects/clau/usingHardhatVerify/node_modules/hardhat/src/internal/core/runtime-environment.ts:163:25)
    at main (/home/claudia/projects/clau/usingHardhatVerify/node_modules/hardhat/src/internal/cli/cli.ts:277:17)```
```

By following the traces I realized that it happens because in the [main task](https://github.com/NomicFoundation/hardhat/blob/e6802042f635c0694324ab96a124c4b42abab9d2/packages/hardhat-verify/src/index.ts#L150-L161) before listing the networks or before checking if the networks should be listed, [the address is being checked](https://github.com/NomicFoundation/hardhat/blob/e6802042f635c0694324ab96a124c4b42abab9d2/packages/hardhat-verify/src/index.ts#L180-L182)  and due to is not being provided it fails. 

Effectively after adding an address in the command it works as expected

`npx hardhat verify <any-address> --list-networks`

```
Networks supported by hardhat-etherscan:

╔══════════════════════╤════════════╗
║ network              │ chain id   ║
╟──────────────────────┼────────────╢
║ mainnet              │ 1          ║
╟──────────────────────┼────────────╢
║ ropsten              │ 3          ║
╟──────────────────────┼────────────╢
║ rinkeby              │ 4          ║
║              ...                  ║
╟──────────────────────┼────────────╢
║ harmonyTest          │ 1666700000 ║
╚══════════════════════╧════════════╝


Custom networks added by you or by plugins:

╔═══════════════════════════════╗
║ No custom networks were added ║
╚═══════════════════════════════╝
```

It doesn't feel natural for me to have to provide the contract address to verify the supported networks list, but in case it is the expected behaviour I would consider modifying it in the documentation. 

### Minimal reproduction steps

1.  Create a simple hardhat project:
         `npx hardhat `

2.  Add hardhat-verify to the project :
         `npm install --save-dev @nomicfoundation/hardhat-verify`

3. Modify the hardhat configuration file as described in [the documentation](https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-verify#usage)

4. Run `npx hardhat verify --list-networks`

### Search terms

hardhat-verify list networks

**Comment by fvictorio** [comment]
Oh damn. Thanks, this should be an easy fix.

**Comment by clauBv23** [comment]
Indeed, I would like to contribute to this task, if possible, I already pointed up what is the problem and where it is. I would just have a question: should there be automated tests to check it works?

**Comment by fvictorio** [comment]
Yes, we should add a test for this. It should be easy, but let me know if you need pointers!

**Comment by clauBv23** [comment]
Thanks @fvictorio!! I created this PR #4030 with a really simple test, I wasn't sure how it should be tested and I think it was not been done, if you could give me some feedback and guidance on how it should be done I would appreciate it.

there is also a typo on the[ test file ](https://github.com/NomicFoundation/hardhat/blob/e6802042f635c0694324ab96a124c4b42abab9d2/packages/hardhat-verify/test/unit/index.ts#LL45C27-L45C36) not sure how should I proceed? create a new PR to fix it, or only do it on the one already created?
