### ISSUE TITLE
Make compilation subtasks more flexible

### ISSUE THREAD

**Issue by adjisb** [NomicFoundation/hardhat#4031]
### Describe the feature

The compilation workflow has a lot of subtasks, to make the code more reusable is better if they take arguments instead of taking info from hre.config.* so we can override some subtasks. 
We have a use which is compiling source code that came from other packages (via npm dependencies).
[Our current solution](https://github.com/thesandboxgame/sandbox-smart-contracts/blob/feat/signedMultiGiveaway_package_deploy/packages/deploy/tasks/importedPackages.ts). can benefit from this reusability.

**Comment by fvictorio** [comment]
I'm gonna assume this was fixed by your PR. There probably are other subtasks where this can also be done, but let's create a separate issue if that happen.
