### ISSUE TITLE
Issue preventing killing the process

### ISSUE THREAD

**Issue by antazoey** [NomicFoundation/hardhat#4036]
### Version of Hardhat

2.15.0

### What happened?

Normally, I have Python code for starting various nodes and tearing them down.
Up until like a month ago, the code worked for all processes: geth, anvil, hardhat, and ganache.
Suddenly, hardhat was no longer able to shut down from this code.

to sum it up, I am calling `process.kill()` in Python. The process is the hardhat node process, managed as a subprocess.

Now, `process.kill()` kinda kills the process but the port is still occupied by another process.
I can force kill the process in the terminal but I am not sure how to properly kill the process now.

Did anything change in Hardhat, regarding the node daemon, that would cause this??

### Minimal reproduction steps

* Start process in Python (roughly):

```python
pre_exec_fn = _linux_set_death_signal if platform.uname().system == "Linux" else None
self.process = Popen(
    self.build_command(), preexec_fn=pre_exec_fn, stdout=out_file, stderr=out_file
)
```

then stop it:

```python
process.kill()
```

This used to work, and it works on Anvil and Ganache... but it no longer works for Hardhat and I am not sure what to do.

### Search terms

process, kill, node, python

**Comment by fvictorio** [comment]
This also happens if you have a `"node": "hardhat node"` script in your `package.json` and run `npm run node`, at least with my version of npm (9.5.0).

The only reliable way I can think of right now is to run the `hardhat` binary directly, which normally is something like:

```
node node_modules/.bin/hardhat node
```

**Comment by fvictorio** [comment]
This might also work, depending on your use case:

```bash
node -e 'require("hardhat").run("node")'
```

**Comment by antazoey** [comment]
> node node_modules/.bin/hardhat node

This worked! Thank you so much
