### ISSUE TITLE
`Yarn Hardhat Node` is generating only 1 address without key

### ISSUE THREAD

**Issue by DorianDaSilva** [NomicFoundation/hardhat#4038]
After updating hardhat to the latest version, every time I run a hardhat node I get only 1 account without keys instead of the usual dozen of accounts.

Is this part of the update or is there an issue with my hardhat install?

![image](https://github.com/NomicFoundation/hardhat/assets/80294826/b9389751-a11d-43b8-a472-935bf7d4527d)

I am trying to test a swap function but I am unable to test it because there are not enough accounts

thank you!

**Comment by fvictorio** [comment]
Can you share your hardhat config (anonymizing any private data you might have)?

**Comment by fvictorio** [comment]
Closing for lack of response.
