### ISSUE TITLE
upfront cost is calculated incorrectly in HH

### ISSUE THREAD

**Issue by Samboy76** [NomicFoundation/hardhat#4040]
### Version of Hardhat

2.13.0

### What happened?

When I try to run transaction it screams about setting a hugh upfront cost in my account when attempt to run it.
It seems to be taking from the feeData, maxFeePerGas * gasLimit which in my case, since I have had to recalculate maxFeePerGas for my developed smart contract method to run against, it is asking me to lay down upfront cost of almost 1240074063290634200000 wei almost $2-2.5M. How can I resolve this ludricous amount?

Thank you

### Minimal reproduction steps

When I try to run transaction it screams about setting a hugh upfront cost in my account when attempt to run it.
It seems to be taking from the feeData, maxFeePerGas * gasLimit which in my case, since I have had to recalculate maxFeePerGas for my developed smart contract method to run against, it is asking me to lay down upfront cost of almost 1240074063290634200000 wei almost $2-2.5M. How can I resolve this ludricous amount?

Thank you

### Search terms

hardhat, gasLimit, upfront cost

**Comment by fvictorio** [comment]
Can you provide minimal reproduction steps please?

**Comment by Samboy76** [comment]
Please close the issue. I was incorrectly calculating gasLimit by multiplying gas limit * maxFeePerGas.
