### ISSUE TITLE
[hardhat-toolbox] helpers.reset wrongfully provides withdrawalsRoot as header

### ISSUE THREAD

**Issue by dominikpre** [NomicFoundation/hardhat#4072]
### Version of Hardhat

2.15.0

### What happened?

Using `helpers.reset(ROC_URL, block_height)` gives me the following error: `A withdrawalsRoot for a header can only be provided with EIP4895 being activated`.

This only happens for some block_heights like `17394208`, `17364206` or `17274264` for example. Usually around and after the shanghai upgrade.

As soon as I get the error, my fork seems to be broken and I can't reset to block heights before shanghai or any block heights to be exact.  

### Minimal reproduction steps

Init fork at block height `17394208` using `helpers.reset` or by sending `hardhat_reset` to fork. 

Try to reset to any block height.

### Search terms

EIP 4895 withdrawalsRoot hardhat_reset helpers.reset

**Comment by fvictorio** [comment]
Hi @dominikpre, I tried several combinations of resetting to different block heights (including of course the ones you provided) and I didn't get this error.

I'm tentatively closing this, but I'll re-open if you can provider more detailed reproduction steps. Thanks!
