### ISSUE TITLE
vyper already supports 0.3.9, but hardhat-vyper can't it be compile and downloaded 0.3.9

### ISSUE THREAD

**Issue by liny52** [NomicFoundation/hardhat#4079]
### Version of Hardhat

2.14.3

### What happened?

vyper already supports 0.3.9, but hardhat-vyper can't it be compile and downloaded 0.3.9

<img width="600" alt="image" src="https://github.com/NomicFoundation/hardhat/assets/40197424/81923928-5d81-4e2e-8472-628eda682e80">

### Minimal reproduction steps

package:
`{
  "name": "zksync-hardhat-template",
  "version": "1.0.0",
  "main": "index.js",
  "author": "Antonio <aug@matterlabs.dev>",
  "license": "MIT",
  "devDependencies": {
    "@matterlabs/hardhat-zksync-deploy": "^0.6.3",
    "@matterlabs/hardhat-zksync-solc": "^0.4.0",
    "@matterlabs/hardhat-zksync-verify": "^0.1.8",
    "@matterlabs/hardhat-zksync-vyper": "^0.2.0",
    "@nomiclabs/hardhat-etherscan": "^3.1.7",
    "@nomiclabs/hardhat-vyper": "^3.0.3",
    "@types/chai": "^4.3.4",
    "@types/mocha": "^10.0.1",
    "chai": "^4.3.7",
    "dotenv": "^16.0.3",
    "ethers": "^5.7.2",
    "hardhat": "^2.12.4",
    "mocha": "^10.2.0",
    "ts-node": "^10.9.1",
    "typescript": "^4.9.4",
    "zksync-web3": "^0.14.3"
  },
  "scripts": {
    "test": "NODE_ENV=test hardhat test --network zkSyncTestnet",
    "deploy": "yarn hardhat deploy-zksync --script deploy-greeter.ts",
    "greet": "yarn hardhat deploy-zksync --script use-greeter.ts"
  }
}`

hardhat.config.ts:
`import { HardhatUserConfig } from "hardhat/config";

import "@nomiclabs/hardhat-vyper";
import "@matterlabs/hardhat-zksync-vyper";
import "@matterlabs/hardhat-zksync-deploy";

const config: HardhatUserConfig = {
  zkvyper: {
    version: "latest", // Uses latest available in https://github.com/matter-labs/zkvyper-bin/
    settings: {
      // compilerPath: "zkvyper", // optional field with the path to the `zkvyper` binary.
      libraries: {}, // optional. References to non-inlinable libraries
    },
  },
  defaultNetwork: "zkSyncTestnet",
  networks: {
    hardhat: {
      zksync: true, // enables zksync in hardhat local network
    },
    zkSyncTestnet: {
      url: "https://testnet.era.zksync.dev",
      ethNetwork: "goerli",
      zksync: true,
    },
  },
  // Currently only Vyper v0.3.3 and v0.3.9 versions are supported.
  vyper: {
    // version: "0.3.3",
    compilers: [
      {
        version: "0.3.3",
      },
      {
        version: "0.3.9",
      },
    ],
  },
};

export default config;
`

### Search terms

vyper 0.3.9

**Comment by fvictorio** [comment]
Hi @liny52, thanks for reporting this. Can you try again? The problem was that the latest versions weren't added to the repository that we use to download the compilers.

**Comment by liny52** [comment]
> Hi @liny52, thanks for reporting this. Can you try again? The problem was that the latest versions weren't added to the repository that we use to download the compilers.

Am I going to downgrade the version of hardhat vyper? Which version supports it?

**Comment by fvictorio** [comment]
No, I meant to try again with 0.3.9

**Comment by liny52** [comment]
> No, I meant to try again with 0.3.9

OK, thank you. I tried it.

**Comment by fvictorio** [comment]
I guess it worked? I'm going to close this issue now, but let me know if it didn't work.
