### ISSUE TITLE
Could not download compiler list

### ISSUE THREAD

**Issue by leeronkit** [NomicFoundation/hardhat#4082]
### Version of Hardhat

2.16.1

### What happened?

Hi, I am unable to compile the project follows the tutorial

![image](https://github.com/NomicFoundation/hardhat/assets/25733356/092ee087-0804-4b1a-85f7-d6fece26cf96)

Already set ssl to false using command `npm set strict-ssl false`
Any idea?

### Minimal reproduction steps

Follow tutorial here
https://docs.openzeppelin.com/learn/developing-smart-contracts?pref=hardhat

### Search terms

compile

**Comment by fvictorio** [comment]
Hey @leeronkit, can you install Hardaht v2.16.0 (`npm install hardhat@2.16.0`) and try again?

We changed something in the downloader in the latest version and, while I don't see how it could cause this problem, I want to double check first.

**Comment by fvictorio** [comment]
Closing for lack of response.
