### ISSUE TITLE
Loaders not working for nomic foundation/ hardhat packages

### ISSUE THREAD

**Issue by ArthurBonsu** [NomicFoundation/hardhat#4092]
### Version of Hardhat

^2.13.0

### What happened?

I have configured these loaders, but they are unable to work with the hardhat packages here. I tried multiple loaders in that attempt:
webpack.js 
module: {
      noParse: /browserfs\.js/,
    rules: [{
      test:  /\.js$, \.ts$, \.tsx$, \.jsx$\.(node)$/,
      exclude: /node_modules/,
      use: 'raw-loader' ,
      use: 'node-loader',
      use: {
        //loader: 'babel-loader',
        loader: 'babel-loader',

      }
    },
    {
      test: /\.(node)$/,
      loader: 'babel-loader',
    },
  
  
  ]
    
  
  },
Error: 
Failed to compile.

./node_modules/@nomicfoundation/solidity-analyzer-win32-x64-msvc/solidity-analyz
er.win32-x64-msvc.node
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loader
s are configured to process this file. See https://webpack.js.org/concepts#loade
rs
(Source code omitted for this binary file)

Import trace for requested module:
./node_modules/@nomicfoundation/solidity-analyzer-win32-x64-msvc/solidity-analyz
er.win32-x64-msvc.node
./node_modules/@nomicfoundation/solidity-analyzer/index.js
./node_modules/hardhat/internal/solidity/parse.js
./node_modules/hardhat/builtin-tasks/compile.js
./node_modules/hardhat/internal/core/tasks/builtin-tasks.js
./node_modules/hardhat/internal/core/config/config-loading.js
./node_modules/hardhat/internal/lib/hardhat-lib.js

./node_modules/hardhat/internal/artifacts.js

### Minimal reproduction steps

1. npm install
2. configure hardhat and compile
3. utilize next. js
4. attempt to run to production using the next.js build
5. configure webpack including loaders
6. even with all packages installed, the error is produced
7. tried after several attempts, checked the node version, reinstalled packages, multiple attempts, and something not working with the packages in the nomic foundation files. 

### Search terms

webpack, hardhat errors, nomic foundation errors

**Comment by fvictorio** [comment]
Hi @ArthurBonsu, assuming you are bundling your project to use it in the browser: Hardhat only works in a node.js context.

The reason you get this error is that one of Hardhat's dependencies is a native module, which cannot be bundled with Webpack.

Of course, there are other reasons for bundling other than using something in the browser. If that's the case, then you need to configure the bundler to not load the `@nomicfoundation/solidity-analyzer` package and to treat it as an external dependency. I know this can be done with Webpack, but I don't remember the details.
