### ISSUE TITLE
wait() after a deployment didn't work

### ISSUE THREAD

**Issue by FournyP** [NomicFoundation/hardhat#4093]
### Version of Hardhat

2.15.0

### What happened?

Durring a task to deploy on mumbai testnet, I want to wait for 5 or 20 transactions before to run the verify task.

But it's seem that the wait function doesn't work.
I've try to put 100 in the wait function but the programm pass directly to the next steps...

My dependencies : 
```
"dependencies": {
    "@nomicfoundation/hardhat-toolbox": "^3.0.0",
    "@openzeppelin/contracts": "^4.9.1"
  },
  "devDependencies": {
    "@nomicfoundation/hardhat-chai-matchers": "2.0.1",
    "@nomicfoundation/hardhat-ethers": "3.0.2",
    "@nomicfoundation/hardhat-network-helpers": "1.0.8",
    "@nomicfoundation/hardhat-verify": "1.0.2",
    "@nomiclabs/hardhat-etherscan": "^3.1.7",
    "@typechain/ethers-v6": "0.4.0",
    "@typechain/hardhat": "8.0.0",
    "@types/chai": "^4.3.5",
    "@types/mocha": "^10.0.1",
    "chai": "4.2.0",
    "dotenv": "^16.1.4",
    "ethers": "^6.6.0",
    "hardhat": "^2.15.0",
    "hardhat-gas-reporter": "1.0.8",
    "mocha": "^10.2.0",
    "solidity-coverage": "0.8.1",
    "ts-node": "^10.9.1",
    "typechain": "8.2.0",
    "typescript": "^5.1.3"
  }
```

I've check the `wait` function and I found that the `confirms` param is not used :
<img width="290" alt="image" src="https://github.com/NomicFoundation/hardhat/assets/64586968/51d86fe1-b13a-470e-92e3-99295e8ea7b8">

Maybe by passing the argument to the super function it will work ? I've never really use classes in TS

### Minimal reproduction steps

Write a task to deploy on the mumbai network like this :

```
import { task } from "hardhat/config";

...

task("deploy-collection-generator")
  .setAction(async (taskArgs, hre) => {
    const CollectionGenerator = await hre.ethers.getContractFactory(
      "CollectionGenerator"
    );
    const collectionGenerator = await CollectionGenerator.deploy();
    await collectionGenerator.waitForDeployment();

    let collectionGeneratorAddress = await collectionGenerator.getAddress();

    console.log("CollectionGenerator deployed to:", collectionGeneratorAddress);

    let res = await collectionGenerator.deploymentTransaction()?.wait(20);

    console.log(res);

    await hre.run("verify:verify", {
      address: collectionGeneratorAddress,
      constructorArguments: [controller6022Address, wETHAddress],
    });
  });
```

The res variable will be display a millisecond after the collection address. To my opinions, it didn't wait

As a result, I got the following error from the verify task :
<img width="364" alt="image" src="https://github.com/NomicFoundation/hardhat/assets/64586968/1a7a6c8e-3370-4f08-aa82-ce7f1dd44c37">

Thanks for this librarie, it's awesome

Have a good day ;)

### Search terms

wait deploy deployement hardhat

**Comment by FournyP** [comment]
For the moment, to bypass the issue, i've write something like this :
```
// Wait for 5 blocks
let currentBlock = await hre.ethers.provider.getBlockNumber();
while (currentBlock + 5 > (await hre.ethers.provider.getBlockNumber())) {}
```

And it's work perfectly, the verify task work

**Comment by fvictorio** [comment]
Confirmed, thanks. I'll work on this asap.

**Comment by fvictorio** [comment]
Hi @FournyP, I took another look into this and apparently this is an upstream bug in ethers. I opened an issue about it: https://github.com/ethers-io/ethers.js/issues/4212

I'm going to mark this issue as blocked and close it after ethers releases a fix for that.

**Comment by fvictorio** [comment]
In the meantime, this workaround might be useful:

```js
const deploymentTx = contract.deploymentTransaction();

await provider.waitForTransaction(deploymentTx.hash, 3);
```

**Comment by fvictorio** [comment]
This is working now with `ethers@6.6.4`.
