### ISSUE TITLE
Update hardhat-ethers package on npm

### ISSUE THREAD

**Issue by 2manslkh** [NomicFoundation/hardhat#4102]
### Describe the feature

npm latest version still shows 3.0.0-beta0

### Search terms

package hardhat-ethers npm

**Comment by fvictorio** [comment]
You might be using `@nomiclabs/hardhat-thers`. We renamed the package to `@nomicfoundation/hardhat-ethers`. (You can learn more about the Labs -> Foundation change [here](https://medium.com/nomic-foundation-blog/introducing-the-nomic-foundation-an-ethereum-public-goods-organization-31012af67df9.)

**Comment by fvictorio** [comment]
I also removed the `beta` tag from `@nomiclabs/hardhat-ethers` to prevent this confusion.
