### ISSUE TITLE
Tests work with 2.10.2 but exactly one test fails with 2.11.0 ("SafeERC20: low-level call failed")

### ISSUE THREAD

**Issue by andersaamodt** [NomicFoundation/hardhat#4103]
### Version of Hardhat

2.11.0

### What happened?

With Hardhat 2.10.2, all 70 of my tests succeed. But when I upgrade Hardhat one version to 2.11.0, exactly one test fails. The line that is reverting is a call to safeTransferFrom OpenZeppelin's SafeERC20 in my contract. It throws a "SafeERC20: low-level call failed" error which is vague but usually indicates a gas problem. I already checked every possible assumption and the contract has sufficient gas.

Is there anything that could have changed from version 2.10.2 to version 2.11.0 that could have introduced this bug, or revealed a bug already existing in my contract? I need to run this bug down because it could be a problem in the contract that is being revealed by some change in that hardhat version. (Versions after 2.11.0 also have the same error).

### Minimal reproduction steps

1. Install Hardhat v2.11.0.
2. With solidity version 0.8.2, in a contract, run SafeERC20.safeTransferFrom(IERC20(tokenContract), _msgSender(), address(this), amountOfTokens) (with appropriate allowance set beforehand and gas and tokens in wallets as appropriate for transfering).
3. Call fails with "SafeERC20: low-level call failed".
4. Repeating steps with v2.10.2, the same line succeeds.

### Search terms

Hardhat SafeERC20 OpenZeppelin

**Comment by andersaamodt** [comment]
Maybe it could be something in Solidity or a standard that Hardhat implements that changed between those versions?

**Comment by fvictorio** [comment]
The first thing that comes to mind is that the latest versions of Hardhat change the default hardfork that is used, although I don't know in this particular case why a tx would start succeeding.

@andersaamodt any chance you can create a complete (but minimal) reproduction repo? I'm really curious about this but I'm not sure I'll be able to reproduce it with your instructions.

**Comment by andersaamodt** [comment]
The forking is specified in hardhat.config.js in networks.hardhat.forking.url, so the default fork should affect it, right? I will see about getting a minimal reproduction repo (or if very short will just post the snippet here). Is there any way to see the log output of the simulated network that is set up when the tests are run? I am not manually launching the hardhat node, so I don't know where the output is. If I could see the log output on the hardhat node side when it crashes, that might help debug.

**Comment by fvictorio** [comment]
> If I could see the log output on the hardhat node side when it crashes, that might help debug.

The Hardhat node uses the same configuration as the in-process Hardhat network, so you can just run `hh node` in some terminal and then use `--network localhost` in another and you should get a similar result than the one you get by just running your task without a network.

> I will see about getting a minimal reproduction repo (or if very short will just post the snippet here).

Thank you! That would be great.

**Comment by fvictorio** [comment]
Hey @andersaamodt, were you able to make that minimal reproduction?

**Comment by andersaamodt** [comment]
Thank you so much for your patience. I did isolate the bug. This contract and the corresponding test work on hardhat 2.10.2 but not on hardhat 2.11.0 and later, it throws "SafeERC20: low-level call failed".

contracts/TokenMover.js

`pragma solidity 0.8.2;
pragma abicoder v2;

import '@openzeppelin/contracts/token/ERC20/ERC20.sol';
import '@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol';
import '@openzeppelin/contracts/token/ERC20/IERC20.sol';

contract TokenMover is ERC20 {
	constructor() ERC20("TokenMover", "TM") {
	}
	
	function moveTokens(uint256 tokenAmount, address tokenContract) external {
		SafeERC20.safeTransferFrom(IERC20(tokenContract), msg.sender, address(this), tokenAmount);
	}
}`

test/verify-contract.js

`const chai = require("chai")
const { expect } = chai
const { ethers, waffle, } = require("hardhat")

// Enable and inject BN dependency
chai.use(require("chai-bn")(ethers.BigNumber))

// These wallet addresses are real addresses on the Ethereum mainnet. Anonymize or change to other wallet containing at least 0.01 WBTC before publishing
const SENDING_WALLET = "0xDBca354Aa9D55D9BB2D3588ceCb43A56eb2D0057"
const WBTC_CONTRACT = "0x2260fac5e5542a773aa44fbcfedf7c193bc2c599"

// Custom suite of unit tests follows
describe("Verifying contract", function () {
    let tokenMoverContract
    let deployAddress
    let myAccount
    let myAddress
    let secondAddress
   
    describe("Test that fails on version 2.11.0 and later", function () {
        it("Should transfer some WBTC", async function () {
            // Test for correct block number
            const blockNumber = await ethers.provider.getBlockNumber()
            expect(blockNumber).to.equal(12548539)

            // Deploy the contract
            tokenMoverContract = await ethers.deployContract("TokenMover", [], {
                unsafeAllow: ["delegatecall"],
            })

            const deployed = await tokenMoverContract.deployed()
            deployAddress = deployed.address
            console.log("\tContract deployed to", deployAddress)
            expect(deployAddress).to.exist

            // Set up variables
            const accounts = await ethers.getSigners()
            myAccount = accounts[0]
            myAddress = myAccount.address
            const mySigner = await ethers.provider.getSigner(myAddress)
            secondAddress = accounts[2].address
            console.log("\tDeployer's address is", myAddress)
           
            // Check contract ETH balance
            let contractWeiBefore = await ethers.provider.getBalance(myAddress)
            let contractEthBefore = ethers.utils.formatEther(contractWeiBefore)
            console.log("CONTRACT ITSELF HAS ", ethers.utils.commify(contractEthBefore.toString()), "ETH")
           
            // Make sure sending wallet has enough ETH to call the moveTokens function
            let testWeiBefore = await ethers.provider.getBalance(SENDING_WALLET)
            let testEthBefore = ethers.utils.formatEther(testWeiBefore)
            console.log("SENDING_WALLET HAS ", ethers.utils.commify(testEthBefore.toString()), "ETH")

            // Send gas money to SENDING_WALLET
            await mySigner.sendTransaction({
                to: SENDING_WALLET,
                value: ethers.BigNumber.from("100000000000000000000"),
            })
           
            let testWei = await ethers.provider.getBalance(SENDING_WALLET)
            let testEth = ethers.utils.formatEther(testWei)
           
            expect(testWei).to.be.a.bignumber.above(
                ethers.BigNumber.from("100000000000000000000")
            )
           
            // Check ETH balance of SENDING_WALLET
            await hre.network.provider.request({
                method: "hardhat_impersonateAccount",
                params: [SENDING_WALLET],
            })
            const sendingWalletSigner = await ethers.provider.getSigner(SENDING_WALLET)
            expect(sendingWalletSigner._address).to.equal(SENDING_WALLET)
            const abi = [
                "function balanceOf(address account) public view returns (uint256)",
                "function approve(address _spender, uint256 _value) public returns (bool success)",
            ]
           
            let beforeWalletWei = await ethers.provider.getBalance(SENDING_WALLET)
            let beforeWalletEth = ethers.utils.formatEther(beforeWalletWei)
            console.log(
                "\tETH balance of WBTC Test wallet before moveTokens is",
                ethers.utils.commify(beforeWalletEth.toString()),
                "ETH"
            )
           
            // Check WBTC balance of SENDING_WALLET
            let wbtcSenderWallet = await ethers.getContractAt(abi, WBTC_CONTRACT, sendingWalletSigner)
            const wbtcBefore = await wbtcSenderWallet.balanceOf(SENDING_WALLET)
            const tokenBefore = await tokenMoverContract.balanceOf(
                SENDING_WALLET
            )

            console.log(
                "\tWBTC balance of SENDING_WALLET before moveTokens is",
                ethers.utils.commify(wbtcBefore.toString()),
                "WBTC"
            )
           
            let beforeReserveWei = await ethers.provider.getBalance(
                secondAddress
            )
            let beforeReserveEth = ethers.utils.formatEther(beforeReserveWei)

            // Approve from SEND_WALLET to our contract
            const maxApprove = "9999999999999999999"
            wbtcSenderWallet.approve(deployAddress, maxApprove)

            // Get a contract object with the SENDING_WALLET signer
           
            let sendingWalletContract = await ethers.getContractAt(
                "TokenMover",
                deployAddress,
                sendingWalletSigner
            )
           
            console.log("Address of loaded deployed contract is ", sendingWalletContract.address)
            await sendingWalletContract.moveTokens(
                ethers.BigNumber.from("88778"),
                WBTC_CONTRACT
            )
           
            let afterWalletWei = await ethers.provider.getBalance(SENDING_WALLET)
            const diffWalletWei = beforeWalletWei.sub(afterWalletWei)
            let diffWalletEth = ethers.utils.formatEther(diffWalletWei)

            console.log(
                "\tETH balance of WBTC Test wallet after moveTokens decreased by",
                ethers.utils.commify(diffWalletEth.toString()),
                "ETH"
            )

            const wbtcAfter = await wbtcSenderWallet.balanceOf(SENDING_WALLET)
            expect(wbtcAfter).to.be.bignumber.below(wbtcBefore)

            await hre.network.provider.request({
                method: "hardhat_stopImpersonatingAccount",
                params: [SENDING_WALLET],
            })
        })
    })
})`

Let me know if you can replicate the bug with this code!

**Comment by schaable** [comment]
Hi @andersaamodt,

I tried to reproduce the issue using the code you provided for both versions, but the test fails with an assertion error in both cases. Can you share the repo either as a zip file or by pushing it to GitHub to investigate it further?

**Comment by andersaamodt** [comment]
Thanks so much.

I think I reproduced the assertion you got. I am running from blockNumber=12548539 in hardhat.config.js. Maybe that wallet doesn't have WBTC in it anymore. Can you try using that blockNumber and see if it fixes the assertion you are getting?

I have the above contract and verify code in a blank project, so hardhat.config.js would be the only other thing I haven't shared. If that blockNumber doesn't fix the assertion and let you reproduce the bug, let me know and I will set up a full exact repo!

**Comment by schaable** [comment]
Hi @andersaamodt, thanks for the clarification. However, to avoid having to guess the details, it would be ideal if you could provide the full repo. That way, we can be more productive and address this faster.

**Comment by fvictorio** [comment]
Closing this for lack of response, happy to re-open it when a 
[minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) is available.
