### ISSUE TITLE
Consider dropping the `abort-controller` dependency

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#4110]
I'm not really sure why we use this dependency. It might be because node v12 doesn't have a global `AbortController` class.

We should check if having the dependency is still necessary given we only support node >= 16.

**Comment by orlandoortegajr** [comment]
Hi, @fvictorio. Could you assign this to me? It's my first time trying to contribute to this project, and I figured this is probably something I can tackle.

**Comment by alcuadrado** [comment]
Go ahead, @orlandoortegajr! 😍

I think @fvictorio's reasoning is correct. When we added that we wanted to abort slow requests if we already finished running the main task. The only way we found that worked well with `node-fetch` (which we used to use) was that.

**Comment by orlandoortegajr** [comment]
@alcuadrado I see that makes a lot sense, I just scanned node-fetch's documentation pretty quickly and saw that they recommend adding this dependency. I'll see what I can do, like @fvictorio mentioned in node 15 the AbortController was introduced and it looks like it might be a direct replacement shouldn't take long.

**Comment by alcuadrado** [comment]
Fixed by @orlandoortegajr 🚀
