### ISSUE TITLE
running tests doesn't work on test networks

### ISSUE THREAD

**Issue by bullishgopher** [NomicFoundation/hardhat#4120]
### Version of Hardhat

2.13.0

### What happened?

https://github.com/PaulRBerg/hardhat-template/issues/166

If I run the tests on the hardhat local network, it works fine.
But if I try it on Goerli or Sepolia network, it fails due to "@nomicfoundation/hardhat-network-helpers" package.
Can you please provide me with a solution?
![image](https://github.com/NomicFoundation/hardhat/assets/49041460/a9434bc2-b28c-4382-ba76-c8c10294e59c)

### Minimal reproduction steps

- add some tests with `loadFixture` function from `@nomicfoundation/hardhat-network-helpers` package
- run tests
- it fails with `OnlyHardhatNetworkError: This helper can only be used with Hardhat Network. You are connected to 'sepolia'.`

### Search terms

hardhat test

**Comment by fvictorio** [comment]
Hey @bullishgopher, as the error message says, these helpers can only be used in the local Hardhat network. They let you do non-standard things like mining new blocks or altering the balance of an account, and these things are obviously not possible in more realistic live networks, even if they are testnets.

**Comment by bullishgopher** [comment]
Makes sense! Thank you
