### ISSUE TITLE
Custom error not decoded until after compile --force

### ISSUE THREAD

**Issue by frangio** [NomicFoundation/hardhat#4123]
### Version of Hardhat

2.14.1

### What happened?

After making a change to a contract (unrelated to custom errors) tests failed to decode a custom error ("unrecognized custom error"). Without changing anything in the Solidity code, after running `hardhat compile --force`, the custom error was properly decoded.

I'm just guessing here but I assume that Hardhat refuses to decode the custom error because it sees multiple candidates that match the selector coming from different compilation artifacts, however in this case the two conflicting errors are the same.

### Minimal reproduction steps

Can provide reproduction steps later.

### Search terms

unrecognized custom error

**Comment by fvictorio** [comment]
> Can provide reproduction steps later.

:eyes:

**Comment by frangio** [comment]
I tried but I can't reproduce it in a minimal setting now. Will report if it happens again.

**Comment by schaable** [comment]
Closing the issue but feel free to reopen if it happens again.
