### ISSUE TITLE
Using Solidity 0.8.20 throws warning even though Hardhat website says it's supported.

### ISSUE THREAD

**Issue by jhubbardsf** [NomicFoundation/hardhat#4146]
### Version of Hardhat

2.26.1

### What happened?

When changing the default solidity version from 0.8.18 to 0.8.20 (on a new scaffolded TS project using `npx hardhat`), I get an error that 0.8.20 isn't supported although the hardhat website says the up to 20 is supported.

### Minimal reproduction steps

Create a new typescript HH project from scratch using `npx create`, change `0.8.18` to `0.8.20` in hardhat.config. Run `hh clean && hh compile` and you'll see the warning.

**Comment by alcuadrado** [comment]
Good catch! The support was added to Hardhat and merged, so the website got updated, but it hasn't been released yet.

It'll be released after [this PR gets merged](https://github.com/NomicFoundation/hardhat/pull/4088).

**Comment by jhubbardsf** [comment]
@alcuadrado Can I point my package.json to a specific git repo/branch to get that functionality early?

**Comment by fvictorio** [comment]
@jhubbardsf AFAIK that's not possible with packages inside a monorepo :slightly_frowning_face: At least it wasn't possible the last time I checked.

But I'll make a release today.

**Comment by fvictorio** [comment]
Thanks for pointing this out @jhubbardsf. We just released [Hardhat v2.17.0](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.17.0) which includes this change.
