### ISSUE TITLE
<file_name> is treated as local but is inside a node_modules directory

### ISSUE THREAD

**Issue by cooopermaira** [NomicFoundation/hardhat#4147]
### Version of Hardhat

2.16.1

### What happened?

While trying to compile a contract in a hardhat project, I received this error. I see that this issue has been raised before but is closed as resolved. It appears to be tracked on Linear but it seems outside users don't have access to this workspace. 

### Minimal reproduction steps

Error HH1006: The file /Users/coopermaira/Documents/GitHub/ethernaut-master/attempt1/node_modules/eth-gas-reporter/mock/contracts/ConvertLib.sol is treated as local but is inside a node_modules directory

HardhatError: HH1006: The file /Users/coopermaira/Documents/GitHub/ethernaut-master/attempt1/node_modules/eth-gas-reporter/mock/contracts/ConvertLib.sol is treated as local but is inside a node_modules directory
    at localPathToSourceName (/Users/coopermaira/Documents/GitHub/ethernaut-master/attempt1/node_modules/hardhat/src/utils/source-names.ts:132:11)
    at /Users/coopermaira/Documents/GitHub/ethernaut-master/attempt1/node_modules/hardhat/src/builtin-tasks/compile.ts:154:32
    at Array.map (<anonymous>)
    at SimpleTaskDefinition.action (/Users/coopermaira/Documents/GitHub/ethernaut-master/attempt1/node_modules/hardhat/src/builtin-tasks/compile.ts:153:21)
    at Environment._runTaskDefinition (/Users/coopermaira/Documents/GitHub/ethernaut-master/attempt1/node_modules/hardhat/src/internal/core/runtime-environment.ts:333:35)
    at Environment.run (/Users/coopermaira/Documents/GitHub/ethernaut-master/attempt1/node_modules/hardhat/src/internal/core/runtime-environment.ts:166:25)
    at /Users/coopermaira/Documents/GitHub/ethernaut-master/attempt1/node_modules/hardhat/src/internal/core/runtime-environment.ts:292:29
    at SimpleTaskDefinition.action (/Users/coopermaira/Documents/GitHub/ethernaut-master/attempt1/node_modules/hardhat/src/builtin-tasks/compile.ts:1304:43)
    at async Environment._runTaskDefinition (/Users/coopermaira/Documents/GitHub/ethernaut-master/attempt1/node_modules/hardhat/src/internal/core/runtime-environment.ts:333:14)
    at async Environment.run (/Users/coopermaira/Documents/GitHub/ethernaut-master/attempt1/node_modules/hardhat/src/internal/core/runtime-environment.ts:166:14)

### Search terms

is treated as local but is inside a node_modules directory

**Comment by schaable** [comment]
Hi @cooopermaira, thank you for submitting this issue.

If you haven't already, you can try importing the file using the following syntax: `import "eth-gas-reporter/mock/contracts/ConvertLib.sol";`. This should work in most cases.

However, if that doesn't work for you, it would be helpful if you could provide us with detailed step-by-step instructions to reproduce the issue on our end. This will allow us to investigate further and provide you with an appropriate solution.

**Comment by cooopermaira** [comment]
Hi Luis,
Does that import statement need to be in hardhat.ts.config or is that in a solidity file?

**Comment by alcuadrado** [comment]
In your solidity files.

@fvictorio I don't think importing contracts from npm modules is explained anywhere in our docs. Should we create a task about it?

**Comment by fvictorio** [comment]
Yes: https://github.com/NomicFoundation/hardhat/issues/4158

**Comment by cooopermaira** [comment]
Hi Luis,

So I'm trying to set up the ethernaut challenge set pointed at a locally running network. Within the ethernaut folder I ran:

>>yarn network
>>yarn compile:contracts
>>yarn deploy:contracts

then I created a hardhat project within the ethernaut-master folder. It was a typescript project. This installed the hardhat-toolbox@2.0.0 which I have since updated to @3.0.0. In the project this created is a file called Lock.sol. I changed the code in this file to solve the challenge I am trying to address. My new Lock.sol file is attached. This is the only code I changed from what hardhat created. When I then try to run:

>> npx hardhat run ./scripts/deploy.ts --show-stack-traces --network localhost

I get the error originally reported. 

[Lock.sol.zip](https://github.com/NomicFoundation/hardhat/files/12115843/Lock.sol.zip)

**Comment by schaable** [comment]
Hi @cooopermaira, sorry for the delay. Are you still experiencing this issue? Unfortunately, I'm not familiar with the ethernaut contracts. Could you please upload or share the repository link containing the code so that I can review it further?

**Comment by cooopermaira** [comment]
Yes, it seems this issue comes from how node dependencies are imported in the solidity file. I believe this is a solidity compiler issue. If a node.js package is referenced by its local path rather than "@local_path_from_project_root" this error can occur. I would say hardhat's documentation saying this problem is a bug is maybe a bit misleading since it seems to be more of a syntax error than a bug.

**Comment by cooopermaira** [comment]
@fvictorio Is there a more appropriate venue I could ask a few questions about hardhat? I'm running into several other issues I haven't been able to resolve through google and stack exchange.

**Comment by fvictorio** [comment]
You can try asking in [our Discord server](https://hardhat.org/discord).

I'm closing this issue for now.
