### ISSUE TITLE
getting wrong type after .connect()

### ISSUE THREAD

**Issue by gameblock1** [NomicFoundation/hardhat#4160]
Hi
I have the following type:
```
import { InputFacet1, InputFacet2} from '../typechain-types';
type Facets = InputFacet1 & InputFacet2;
```
then using the `hardhat-diamond-abi` I combine all facets abis into one file:
```
const allFacets = (await ethers.getContractAt(abi, Diamond.address)) as BaseContract as Facets;
```
`allFacets` have type of `Facets` which is correct. but when I connect to a different runner:
```
const changedAccount = allFacets.connect(acc2);
```
now `changedAccount` type is `InputFacet1` and not the `Facets`.
Also the typechain type for connect() method becomes this:
`connect(runner?: ContractRunner | null): InputFacet1;`

It seems that `.connect()` returns the contract with the first type of the combination.

**Comment by alcuadrado** [comment]
Hey @gameblock1,

I'm not sure if what you expect would actually be correct wrt to types. Can you poste an example snippet so that we can try it out?

**Comment by gameblock1** [comment]
It's simple, `allFacets` has type of `Facets` but when you add .connect() to it, it will be of type `InputFacet1`

`allFacets.connect(...) // Now the type is changed`

**Comment by alcuadrado** [comment]
Your high level description is not precise enough, please provide a code sample as this kind of things normally go wrong because of tiny details.

**Comment by gameblock1** [comment]
@alcuadrado Check if this helps? else I upload to a repo
```
import { ethers } from "hardhat";
import {Lock, Lock2} from "../typechain-types"

type Lock1AndLock2 = Lock2 & Lock

describe("Sample", function() {
    it("Should have the same type", async function() {
        const Lock = (await ethers.getContractFactory("Lock")) as unknown as Lock1AndLock2; // type: Lock1AndLock2
        const LockWithDifferentRunner = Lock.connect(undefined); // type: Lock2

        /*
          Currently:
            Lock: Lock1AndLock2
            LockWithDifferentRunner: Lock2
        */

        /*
          Expected:
            Lock: Lock1AndLock2
            LockWithDifferentRunner: Lock1AndLock2

            why the type of LockWithDifferentRunner changed after conencting to a different runenr?
        */
    })
})

```

**Comment by fvictorio** [comment]
The problem here is that the types of the contracts are something like this:

```ts
type Lock = {
  connect(...): Lock
}

type Lock2 = {
  connect(...): Lock2
}
```

So when you do `type Lock1AndLock2 = Lock1 & Lock2`, the resulting type has a `connect(...): Lock` function (the first one "wins").

Maybe if typechain returned `this` for those types this would work, but that needs some testing. I suggest opening and issue in the typechain repo about this, because there isn't much we can do on Hardhat's side.

Tentatively closing, I'll re-open if there is something we can do on our side.
