### ISSUE TITLE
HH11: Invariant violation when running hh converage 

### ISSUE THREAD

**Issue by clauBv23** [NomicFoundation/hardhat#4174]
### Version of Hardhat

2.12.2

### What happened?

I got this error when running ` hh coverage`
```
Error in plugin solidity-coverage: HardhatError: HH11: An internal invariant was violated: Invalid harfork name shanghai
```
it failed when compiling in the coverage plugin, and `hh compile` works fine. 

I think it might be due to Im using solidity-coverage `v0.8.4` (the latest version that supports new hardhat versions),
But in that case, is there a workaround to use latest solidity-coverage version without updating hardhat?

**NOTE**: open an issue cuz is the suggestion in the HH11 error doc

> #[HH11: Invariant violation](https://hardhat.org/hardhat-runner/docs/errors#HH11)
An internal invariant was violated. This is probably caused by a programming error in hardhat or in one of the used plugins.
> Please [report it](https://github.com/nomiclabs/hardhat/issues/new) to help us improve Hardhat.
### Minimal reproduction steps

Haven't tried it in a template project

**Comment by fvictorio** [comment]
Hi @clauBv23, can you try downgrading the hardfork like this?

```
networks: {
  hardhat: {
    hardfork: "london"
```

I don't know why solidity-coverage would change the hardfork though, but that's what the error message seems to suggest.

**Comment by clauBv23** [comment]
Hi @fvictorio thanks for the quick response, adding the hardfork solved it.

I was using a linked solidity-coverage dependency and the hardhat version(2.11.0) it had was different than the one defined on the project (2.12.2), I think that might be the reason for the error, actually, I tried upgrading the hardhat version in the solidity-coverage repo and also solved the issue without having to add the hardfork.
