### ISSUE TITLE
can't fork moonbeam mainnet and do unit test

### ISSUE THREAD

**Issue by conlotor** [NomicFoundation/hardhat#4187]
### Describe the feature

I'm going to write unit test by forking moonbeam mainnet.
I tried to change moonbeam rpc URL several times, but am getting same error like below.

```
InvalidResponseError: Invalid JSON-RPC response's result.

Errors: Invalid value null supplied to : RpcBlockWithTransactions | null/mixHash: HASH | undefined
```

**Comment by fvictorio** [comment]
Can you share your config?

**Comment by fvictorio** [comment]
Closing for lack of response.
