### ISSUE TITLE
Network Missmatch

### ISSUE THREAD

**Issue by Brianspha** [NomicFoundation/hardhat#4193]
### Version of Hardhat

2.17.0

### What happened?

Network Mismatch Error - Your provider network chainId is: 31337 whereas your desired chainId is: 31337 I'm not sure what else I could do to resolve this 

### Minimal reproduction steps

```
hardhat: {
      chainId: 31337,
      forking: {
        url: "Polygon node url",
      },
      accounts: {
        accountsBalance: "1000000000000000000000000",
       
    }
```

### Search terms

Network, hardhat

**Comment by alcuadrado** [comment]
Hey, thanks for submitting this issue! Can you post the entire stack trace?
