### ISSUE TITLE
hre.ethers giving undefined 

### ISSUE THREAD

**Issue by PrakharSharma888** [NomicFoundation/hardhat#4196]
### Version of Hardhat

2.12.7

### What happened?

```
const hre = require("hardhat");

async function main() {
  console.log(hre.ethers);
  const ContractFactory = await hre.ethers.getContractFactory("MyContract");
  const contract = await ContractFactory.deploy("Prakhs, PS");
  await contract.deployed();

  console.log("Contract deployed to:", contract.address);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
```

### Minimal reproduction steps

- Set up a Hardhat project.
- Add the provided deployment script to the project.
- Compile the smart contract using npx hardhat compile.
- Attempt to deploy the contract with npx hardhat run --network <network_name> scripts/deploy.js.
- Observe the output and error messages.

### Search terms

hre.ethers, hardhat ethers, getContractFactory

**Comment by PrakharSharma888** [comment]
Hardhat should revert back when change with the environment like i mistakenly removed this from config file
`require("@nomicfoundation/hardhat-toolbox");` 

Which took my 2 hours

**Comment by Pranjay4** [comment]
I am getting the same issue even with requre statement in the cofig file, please help
