### ISSUE TITLE
Functions that use assembly create/create2 and return the address don't get the right return type

### ISSUE THREAD

**Issue by ndavd** [NomicFoundation/hardhat#4203]
In a basic setup of Hardhat, ethers and TypeChain if we deploy a contract and proceed to call a function in the tests it normally looks something like this:
```ts
import { deployments } from 'hardhat';
import { MyContract } from '../typechain';
await deployments.fixture(['myContract']);
const myContract: MyContract = await ethers.getContract('MyContract');
const addr = myContract.foo()
// Say foo returns some address, we will notice that the type of addr is string, as it should
```
But if that function (say `foo()`) was to get that address from a create or create2 call in yul assembly (something like the `deploy` function from https://solidity-by-example.org/app/create2), then we'd see something like this instead:
```ts
const addr = myContract.foo()
// The type of addr is ContractTransactionResponse
```
And if we do `addr.wait()` and get a receipt we notice that `contractAddress` is null.
However, if we do call `myContract.foo.staticCall()` instead, we then actually get back a string (the actual address).

**Comment by ndavd** [comment]
Apparently related with https://ethereum.stackexchange.com/questions/66869/unable-to-fetch-output-from-a-public-function-in-solidity

**Comment by fvictorio** [comment]
Hi @ndavd, I think the answer to that question explains the situation correctly. The reason the type changed is because you changed a function from view to non-view. Happy to explain this further if you have questions, but for now I'm closing this issue because there isn't much we can do.

**Comment by ndavd** [comment]
> Hi @ndavd, I think the answer to that question explains the situation correctly. The reason the type changed is because you changed a function from view to non-view. Happy to explain this further if you have questions, but for now I'm closing this issue because there isn't much we can do.

Hi, thanks for the reply. Indeed. The reason I re-opened the issue was in hopes of knowing whether a hardhat native solution for this issue was in development. I am aware of hardhat-exposed which creates a copy of the original contracts with the private and internal functions as public so that we can use them in our tests but currently it doesn't seem to work with TypeChain https://github.com/dethcrypto/TypeChain/issues/691. It only seems natural to be able to test all kinds of functions without recurring to third party plugins.

**Comment by fvictorio** [comment]
That's fair! I opened https://github.com/NomicFoundation/hardhat/issues/4223 to think about that.
