### ISSUE TITLE
Tests hanging when running on live networks

### ISSUE THREAD

**Issue by sebastiantf** [NomicFoundation/hardhat#4222]
### Version of Hardhat

2.14.0

### What happened?

When running existing test suites that run fine on local networks, on live networks like goerli, arbitrum goerli, etc. the tests do not exit as soon as all lines of code are executed. It just hangs for a long time making the test suite unnecessarily slow. But all the test setups and assertions are running fine and fast, only the test just wont exit

### Minimal reproduction steps

Run a test suite that involves deploying new contracts, executing transactions and performing assertions, on a live network like goerli, arbitrum goerli, etc.

### Search terms

test, hang, exit, live network, testnet

**Comment by fvictorio** [comment]
@sebastiantf can you tell us if this happen with the latest versions of whatever plugins you are using?

I'm pretty sure running the sample project tests in a live network works fine, but I might be wrong. If the sample project with the latest dependencies indeed works, then we'll need a proper reproduction repo to be able to look into this.

**Comment by fvictorio** [comment]
In that case we'll need some way to reproduce it, sorry. If your project is public we can take a look.

**Comment by sebastiantf** [comment]
Its in a private monorepo 😕. I'll try upgrading the deps

**Comment by sebastiantf** [comment]
I tried upgrading deps including hardhat from 2.14.0 to 2.17.1 and typescript to 5.1.6. Also tried changing the RPC from alchemy to blastapi. But still facing the same issue - test wont exit right after the last line

**Comment by fvictorio** [comment]
Can you share how you are running your tests?

**Comment by sebastiantf** [comment]
> Can you share how you are running your tests?

Sorry about the delay. Will share soon

**Comment by sebastiantf** [comment]
But, i just tried running the same test suite on Base Goerli (with a few modifications like using ethers' [NonceManger](https://docs.ethers.org/v5/api/experimental/#experimental-noncemanager) and hardcoded gas price), and it doesn't seem to hang for so long. Test is exiting faster than Arbitrum Goerli

**Comment by fvictorio** [comment]
@sebastiantf do you mean that it's not happening anymore? Maybe it was a temporary issue related to the nodes?

**Comment by sebastiantf** [comment]
Apologies for the delay. For clarity, these were the things I tested and ran into:

Older Repo A on Arbitrum Goerli: test hanging for long time and not exiting faster
Older Repo A on Base Goerli: test does not hang and exits faster
Newer Repo B on Arbitrum Goerli: test does not hang and exits faster
Newer Repo B on Base Goerli: test does not hang and exits faster

**Comment by fvictorio** [comment]
Ah, I see. We are not really maintaining `hardhat-waffle` anymore, so I think we can close this issue?

**Comment by sebastiantf** [comment]
I suppose so. I'll try migrating to toolbox and see. Closing for now
