### ISSUE TITLE
 'customChains' does not exist in type 'EtherscanConfig'

### ISSUE THREAD

**Issue by Osub** [NomicFoundation/hardhat#4228]
### Version of Hardhat

 npx hardhat --version 2.9.3

### What happened?

 'customChains' does not exist in type 'EtherscanConfig'

### Minimal reproduction steps

![image](https://github.com/NomicFoundation/hardhat/assets/7599190/4e384b32-9b08-4fe0-b2ab-bc788744bf1c)

**Comment by schaable** [comment]
Hi @Osub, that's a pretty old hardhat version which uses `hardhat-etherscan`. The plugin was revamped a couple of months ago and is now called `hardhat-verify`. Can you try installing the latest hardhat version along with `hardhat-verify`? If that doesn't work, we're going to need more info to debug it. A minimal repo should work.

**Comment by Osub** [comment]
thanks
