### ISSUE TITLE
Add support for Base Mainnet

### ISSUE THREAD

**Issue by bghughes** [NomicFoundation/hardhat#4260]
### Describe the feature

Note #3803. [Please add support for Base Mainnet](https://docs.base.org/network-information) with the network information hot-linked.

![Screen Shot 2023-08-08 at 3 50 42 PM](https://github.com/NomicFoundation/hardhat/assets/32072172/4e0fc4bd-7c80-4282-b1a2-f8aa5bea3d67)

Onwards and upwards

### Search terms

Based

**Comment by schaable** [comment]
Hi @bghughes, can you share which version of `hardhat-verify` you are using? From the screenshot, it seems like you're using `hardhat-etherscan`, which is the old plugin and is no longer maintained.

**Comment by schaable** [comment]
@bghughes were you able to fix it? 

To debug the issue, I'm going to need you to provide me with the versions of `hardhat` and `hardhat-verify`. To find the hardhat version you can do `npx hardhat --version`. Then you can check your `package.json` to get the `hardhat-verify` version. If you didn't install `hardhat-verify` manually, it was most likely added through the `@nomicfoundation/hardhat-toolbox` package, so you can share its version instead.

**Comment by bghughes** [comment]
> @bghughes were you able to fix it?
> 
> To debug the issue, I'm going to need you to provide me with the versions of `hardhat` and `hardhat-verify`. To find the hardhat version you can do `npx hardhat --version`. Then you can check your `package.json` to get the `hardhat-verify` version. If you didn't install `hardhat-verify` manually, it was most likely added through the `@nomicfoundation/hardhat-toolbox` package, so you can share its version instead.

Thank you for your support @schaable - I was by using the custom chain plugin functionality for that package. Apologies for the confusion on my end.

**Comment by schaable** [comment]
No worries. Thanks for the update.
