### ISSUE TITLE
RpcTransactionReceipt response validation issue with Alchemy

### ISSUE THREAD

**Issue by fredwes** [NomicFoundation/hardhat#4271]
### Version of Hardhat

2.12.7

### What happened?

When running hardhat network forked from Arbitrum One, using Alchemy provider. Calling `getTransactionReceipt` fails due to the response from Alchemy failing the validation done by Hardhat. This issue appears to be limited to querying a transaction hash that is a contract deployment, in this case it appears that Alchemy omits the `to` property from the response rather than setting the property to null as the validation function expects.

I was able to solve the issue for myself locally by making a modification to the validation logic [here](https://github.com/NomicFoundation/hardhat/blob/7197a6c141068e240c316f7de8486777e78c05c4/packages/hardhat-core/src/internal/core/jsonrpc/types/output/receipt.ts#L22)

current: `to: nullable(rpcAddress),`
changed (and working): `to: optional(nullable(rpcAddress)),`

### Minimal reproduction steps

1. Hardhat config
```
module.exports = {
  solidity: "0.8.4",
  networks: {
    hardhat: {
      forking: {
        url: "https://arb-mainnet.g.alchemy.com/v2/<YOUR_ALCHEMY_API_KEY>",
        blockNumber: 1250000,
        enabled: true,
      },
      accounts: {
        count: 0,
      },
    },
  },
};
```

2. Prepare a simple script:
```
import { ethers } from "hardhat";

const main = async () => {
     console.log(await ethers.provider.getTransactionReceipt("0x44a7f70cf843d696d1254ef8d359ca60fececfa2b8f5278f932735409c19c377"));
};

main().catch(error => {
    console.error(error);
    process.exitCode = 1;
});
```

3. Run local node and script:
```
npx hardhat node --network hardhat
...
npx hardhat run --network localhost <script.js>
```
4. Result:
```
ProviderError: Invalid JSON-RPC response's result.

Errors: Invalid value undefined supplied to : RpcTransactionReceipt | null/to: ADDRESS | null
    at HttpProvider.request (/Users/wesleyfrederickson/repos/rnglabs/gmx-vault-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async EthersProviderWrapper.send (/Users/wesleyfrederickson/repos/rnglabs/gmx-vault-contracts/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
```

**Comment by fvictorio** [comment]
Hmm, I think they are not following the spec correctly in this case. Check the response to the `eth_getTransactionReceipt` method [here](https://ethereum.github.io/execution-apis/api-documentation/).

I wrote to them let them know about this.

I'm tentatively closing this issue because we normally try to avoid relaxing validations to accommodate the quirks of RPC providers. But I will re-consider it if they don't fix it quickly enough. Please ping me here if that's the case!

**Comment by fvictorio** [comment]
I sent them an email (I've done it in the past and they've been responsive), I'm not sure if they have a public issue tracker.
