### ISSUE TITLE
hardhat-viem: deploy contracts and get contract instances

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#4274]
Support for deploying contracts and getting contract instances using the project's contract names/FQNs. This does **not** include generating the declaration files.

**Comment by Saty248** [comment]
hi @fvictorio , i think first of all we need to create the walletClient using viem and for that we need to add the providers object of viem to hre. 
 then we can use viem's  deploy function   to deploy the contracts with an account which we get from the modified hre.

**Comment by Saty248** [comment]
i would love to contribute to hardhat-viem feature. kindly help me if am going wrong.

**Comment by dataexcess** [comment]
How can we do this ? Please add deployment to live network to the docs!
