### ISSUE TITLE
Publish a new version of `hardhat-etherscan` with a deprecation warning

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#4285]
TBD if we show it all the time or only when the verification fails.

The message should instruct the user to migrate to `hardhat-verify`. We don't really have documentation for that. We should do it too, even if it's kind of obvious. I would add it in the `hardhat-etherscan`'s readme.

**Comment by alcuadrado** [comment]
The rationale for only showing it on failures: if it ain't broke, don't fix it

**Comment by schaable** [comment]
We should put a notice at the beginning of the README and mark the package as [deprecated on npm](https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions). This should help reduce confusion among new users over which package to use, which could lead to incorrectly installing `hardhat-etherscan`.
