### ISSUE TITLE
I have error like you! and i check import file of SMC

### ISSUE THREAD

**Issue by msapple0338** [NomicFoundation/hardhat#4291]
I have error like you! and i check import file of SMC 
![image](https://user-images.githubusercontent.com/96694773/192185687-1e3958fe-ea9d-454d-9305-4d9c038c101a.png)

resolve:
![image](https://user-images.githubusercontent.com/96694773/192185756-bccad09a-a9e2-4d2c-8345-5350a3e0092f.png)

_Originally posted by @Lasang3012 in https://github.com/NomicFoundation/hardhat/issues/1439#issuecomment-1257411419_

**Comment by schaable** [comment]
Hi @msapple0338, can you try upgrading to the lastest hardhat version? If it is happening with the lastest version, I'm going to need the reproduction steps or a repo to start troubleshooting.

**Comment by msapple0338** [comment]
Hi @schaable, Thanks for your reply.
Now I`m upgrading the hardhat with some problem, but now is working well. 
Further I hope to keep the relationship with you.
Thanks.

**Comment by schaable** [comment]
Thanks for the update.

**Comment by msapple0338** [comment]
Hi @schaable, Can I contact you with gmail?
