### ISSUE TITLE
.connect not working in test

### ISSUE THREAD

**Issue by Dobermensch** [NomicFoundation/hardhat#4313]
### Version of Hardhat

2.17.1

### What happened?

I'm writing a test and .connect didn't change the msg.sender. More info: https://stackoverflow.com/questions/76919562/solidity-hardhat-testing-nft-transfer/76926496#76926496

### Minimal reproduction steps

Hard to say because initially the first `.connect` worked (await token.connect(otherAccount.address)) but the subsequent lines of approve and transferFrom indicated that the second .connect didn't work.

### Search terms

connect, test

**Comment by fvictorio** [comment]
@Dobermensch `.connect` is not stateful ([docs](https://docs.ethers.org/v6/single-page/#BaseContract-connect)). That is, doing `token.connect(...)` won't change the address used by `token`. You have to either assign it to a new variable, or re-assign `token = token.connect(...)`.
