### ISSUE TITLE
Replaying Transaction using hardhat

### ISSUE THREAD

**Issue by vpahari** [NomicFoundation/hardhat#4327]
Hi there, I am trying to replay past transactions using hardhat, and trying to check what happens for different orderings of transactions. I took a random block number 16906390 (https://etherscan.io/block/16906390), and wanted to replay txs 0,1 with different orderings (https://etherscan.io/tx/0x502cace0340dcb9d9f999e6797ce0f1003e2dac056cad3e1672cbe6a28781aa7, https://etherscan.io/tx/0x1536d47619aceab144d0cfe1c093ebbe1130242f134c4b1550aea3707008a7aa). 

I forked the chain using "hardhat_reset" to block 16906389 (one block before). Then I used the "hardhat_impersonateAccount" to the sender of the tx (tx.from). I gathered the from, to, gasLimit, gasPrice, and data from an Ethereum node to create a tx. Then I use signer.sendTransaction to send the transaction. 

However, I encounter an error when trying to execute the 1st tx. 

"Error: VM Exception while processing transaction: reverted with an unrecognized custom error (return data: 0x815e1d64)". 

The transaction should execute without error because it is the first transaction in the next block in Ethereum, but it gives this error. 

I encounter the same error if I do the following method as well:

 await hre.network.provider.request({
  method: "eth_call",
  params: [currentTx, {"blockNumber" : "0x" + (16906389).toString(16)}],
    });

Not quite sure why this is happening, because if I call "eth_call" directly to the Ethereum node client using http and provide the same parameters, it does not error.  

Any idea why hardhat is showing this error even though I provide the same transaction and try to execute it at the place where it was executed in the chain.

**Comment by fvictorio** [comment]
That makes sense. I guess we can close this issue then, right?

**Comment by jacob-thrackle** [comment]
To confirm: you set the chain ID to 1, correct?

(I'm also experiencing the same thing but need to try and catch it dynamically).
