### ISSUE TITLE
eth_estimateGas Errors occur on other chains

### ISSUE THREAD

**Issue by LiHang941** [NomicFoundation/hardhat#4332]
### Version of Hardhat

2.17.1

### What happened?

ProviderError: too many arguments, want at most 1

### Minimal reproduction steps

I have encountered the same issue as described in this GitHub thread: https://github.com/NomicFoundation/hardhat/issues/4010. Upon referencing the ether.js library, I noticed that they do not pass the second parameter. Here is the link to the code: https://github.com/ethers-io/ethers.js/blob/main/src.ts/providers/provider-jsonrpc.ts#L862. I wonder if we should align with their approach. Currently, it seems that only the mainnet is functioning correctly, while other networks encounter this error.

hardhat-ethers The location that needs to be modified
https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-ethers/src/internal/hardhat-ethers-provider.ts#L237

**Comment by fvictorio** [comment]
As mentioned in the other issue, the problem seems to be that the node doesn't accept the block tag parameter, but this is part of the spec so there isn't much we can do. We can't adapt our code to work with a (single, apparently) non-compliant node implementation.
