### ISSUE TITLE
noticed an inconsistency within the docs:

### ISSUE THREAD

**Issue by mattjaf** [NomicFoundation/hardhat#4350]
### Version of Hardhat

docs

### What happened?

![image](https://github.com/NomicFoundation/hardhat/assets/5776918/eb27e541-147a-407d-9be3-8ea55054d47a)

![image](https://github.com/NomicFoundation/hardhat/assets/5776918/cc96d9a9-dc4f-489a-907b-e32001c33db6)

### Minimal reproduction steps

what's the difference?

https://hardhat.org/hardhat-runner/docs/config

https://hardhat.org/hardhat-network/docs/reference

**Comment by mattjaf** [comment]
oh, one might be docs for the hardhat network and the other for other networks?

**Comment by fvictorio** [comment]
Yes, exactly. The default behavior for the `gas` config is different for the Hardhat network and for other networks.
