### ISSUE TITLE
Unable to deploy to BSC Testnet

### ISSUE THREAD

**Issue by tdev00** [NomicFoundation/hardhat#4351]
### Version of Hardhat

2.12.6

### What happened?

My code cannot deploy a smart contract to BSC Testnet. Everything was working as it should before August 29th, 2023, but now, deployment to BSC Testnet doesn't work. I should note that it does work for other chains e.g. Goerli ETH.

Is anyone else experiencing this issue?

### Minimal reproduction steps

`hardhat version 2.12.6`
`@nomicfoundation/hardhat-toolbox version 2.0.1`
`@nomiclabs/hardhat-ethers version: 2.2.3`
`ethers version: 5.7.2`

`const hre = require("hardhat");`

// any bsc rpc can be used eg. quick node, public node etc.
`const provider = new hre.ethers.providers.JsonRpcProvider('https://bsc-testnet.publicnode.com');`
`const signer = new hre.ethers.Wallet(process.env.PRIVATE_KEY, provider);`

`const tokenContract = await hre.ethers.getContractFactory('MyContract', signer);`
`deployedToken = await tokenContract.deploy();`

**Comment by ubudragon** [comment]
Same here.
BSC testnet deploy doesn't work

factory.deploy() always fails with an error: ProviderError: transaction overpriced

**Comment by osirustwits** [comment]
Could you let me know if you saw what version of EVM you are deploying with?

Most aren't PARIS compatible.

**Comment by fvictorio** [comment]
I cannot reproduce this with the latest version of Hardhat. Happy to re-open if someone can provide up to date reproduction steps.
