### ISSUE TITLE
Hardhat is replaying all blocks when forking mainnet

### ISSUE THREAD

**Issue by antoinedc** [NomicFoundation/hardhat#4358]
### Version of Hardhat

2.17.2

### What happened?

When starting/stopping a node setup with a mainnet fork multiple times, instead of emitting the `block` event only for the latest, Hardhat is going to emit it for all past events since the last emitted one.
For example:
- I start the node with a fork that is at block 1000
- I stop it
- 5 blocks go by
- I start it again
- Blocks 1001 to 1005 are going to be emitted

I don't know if this is expected, but this is annoying as the main purpose of mainnet forks is to get the state, not to synchronize blocks & transactions. For my specific use case ([Ethernal](https://www.tryethernal.com)), this causes issues for users, as when they reset their node, they end up with tons of mainnet blocks/transactions in their backend, instead of just theirs.

Interestingly, this doesn't happen when a block number is specified for the fork.

### Minimal reproduction steps

Here is a repo that reproduces the issue, instructions are in the README: https://github.com/tryethernal/repro-hardhat-bug

### Search terms

replay, blocks, fork, mainnet

**Comment by antoinedc** [comment]
Also, it seems like those events are only emitted outside of the Hardhat environment.
A plugin using `hre.provider` is not going to catch them, only something listening from the outside.

**Comment by antoinedc** [comment]
Thanks! Good to know at least that this is actually a bug and not a hidden feature ahah

**Comment by fvictorio** [comment]
Actually, I believe this might be a feature of ethers :grimacing: 

https://github.com/ethers-io/ethers.js/blob/32915634bef5b81c6d9998f4e9ad812ffe721954/src.ts/providers/subscriber-polling.ts#L71-L80

**Comment by antoinedc** [comment]
Oh wow, great find! And here is the reason: https://github.com/ethers-io/ethers.js/issues/3924#issuecomment-1481906862

**Comment by fvictorio** [comment]
Makes sense. I don't think there's much we can do on our side though, right? Do you mind if we close this?

**Comment by antoinedc** [comment]
Yes, we can definitely close this. I'm opening an issue on their end. Thanks a lot for tracking this down though, it was super helpful!
