### ISSUE TITLE
`npx hardhat` hangs when initializing repo

### ISSUE THREAD

**Issue by kuzdogan** [NomicFoundation/hardhat#4359]
### Version of Hardhat

2.17.2

### What happened?

EDIT: I was actually able to resolve the issue myself but still writing for documentation purposes.

When initializing a new repository with `npx hardhat` the command hangs and does not initialize a hardhat projects.

`npx hardhat --help` also hangs but `npx hardhat --version` does indeed return the version number.

### Minimal reproduction steps

System: MacBook M1 Pro 14"
node version: v18.14.2 (npm v9.5.0)
also reproduced with v16.15.1 (npm v8.11.0)

Steps:
```bash
mkdir hardhat-test
cd hardhat-test
npm init -y
npm i -d hardhat
npx hardhat --version
npx hardhat
```

Last command returns: `Error HH14: Your Hardhat project uses typescript, but it's not installed.` Note that this is an empty project. No typescript installed. No npm projects initialized in the parent package either. The folder is a sibling of many other hardhat folders though:
```
├── hardhat-metacoin-sourcify
├── hardhat-network
├── hardhat-network-v2.14.0
├── hardhat-template
├── hardhat-test
```

```
npm i -d typescript
npx hardhat
```

Now I get `Error HH13: Your Hardhat project uses typescript, but ts-node is not installed.`

```
npm i -d ts-node
npx hardhat
```

Now the process just hangs.

Edit: Ok while writing the "The folder is a sibling of many other hardhat folders though" part I was able to debug and resolve the problem. There happened to be a `hardhat.config.ts` file in `../../`. Running `rm ../../hardhat-config.ts` resolved the issue for me.

Still opening the issue if this is something you want to look into and for others to potentially search if they come across this. Feel free to close.

### Search terms

npx hardhat hangs

**Comment by fvictorio** [comment]
Thank you @kuzdogan. I think this class of issues will go away when we have an explicit `init` command instead of initializing projects just with `npx hardhat`, which is confusing. See #2594 for the tracking issue.
