### ISSUE TITLE
verify contract issue on Binance Testnet

### ISSUE THREAD

**Issue by zmeditation** [NomicFoundation/hardhat#4381]
### Describe the feature

I am going to verify my smart contract.

`//SPDX-License-Identifier: Unlicense
pragma solidity =0.8.0;

abstract contract Context {
    function _msgSender() internal view virtual returns (address) {
        return msg.sender;
    }

    function _msgData() internal view virtual returns (bytes calldata) {
        return msg.data;
    }
}

interface IERC20 {
    /**
     * @dev Returns the amount of tokens in existence.
     */
    function totalSupply() external view returns (uint256);

    /**
     * @dev Returns the amount of tokens owned by `account`.
     */
    function balanceOf(address account) external view returns (uint256);...`
    
I've compiled this contract and got address.
0xcf26cc106e09539f9aEf871c9D27390Ee48C6ec3

Then I have error when I run verify contract.
`npx hardhat verify --network testnet "0xcf26cc106e09539f9aEf871c9D27390Ee48C6ec3"`

module.exports = {
  defaultNetwork: "mainnet",
  networks: {
    testnet: {
      url: "https://data-seed-prebsc-1-s1.binance.org:8545",
      chainId: 97,
      gasPrice: 20000000000,
      accounts: { mnemonic: mnemonic },
    },
  },
  etherscan: {
    apiKey: bscscanApiKey,
  },
  solidity: {
    version: "0.8.0",
    settings: {
      optimizer: {
        enabled: false,
      },
    },
  },
  paths: {
    sources: "./contracts",
    tests: "./test",
    cache: "./cache",
    artifacts: "./artifacts",
  },
  mocha: {
    timeout: 20000,
  },
};

This is additional information.

Hardhat version: 2.13.0
And this is error message.
`SyntaxError: Unexpected token < in JSON at position 0 at JSON.parse (<anonymous>) at consumeEnd (D:\projects\14_Scadsdex\source\Hardhat-test\node_modules\undici\lib\api\readable.js:253:20) at BodyReadable.<anonymous> (D:\projects\14_Scadsdex\source\Hardhat-test\node_modules\undici\lib\api\readable.js:235:7) at BodyReadable.emit (node:events:513:28) at BodyReadable.emit (D:\projects\14_Scadsdex\source\Hardhat-test\node_modules\undici\lib\api\readable.js:66:18) at endReadableNT (node:internal/streams/readable:1358:12) at processTicksAndRejections (node:internal/process/task_queues:83:21)`

How to fix it?

**Comment by zmeditation** [comment]
Sorry.
This is additional information.

Hardhat version: 2.13.0
And this is error message.
`SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at consumeEnd (D:\projects\14_Scadsdex\source\Hardhat-test\node_modules\undici\lib\api\readable.js:253:20)
    at BodyReadable.<anonymous> (D:\projects\14_Scadsdex\source\Hardhat-test\node_modules\undici\lib\api\readable.js:235:7)
    at BodyReadable.emit (node:events:513:28)
    at BodyReadable.emit (D:\projects\14_Scadsdex\source\Hardhat-test\node_modules\undici\lib\api\readable.js:66:18)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)`

**Comment by fvictorio** [comment]
I believe this happens when the explorer URL is wrong, or perhaps because it returned an error (although if it's the latter, we are doing something wrong).

Is this still happening to you or was it a temporary thing?
