### ISSUE TITLE
ClonesUpgradeable.clone generates the same address every time

### ISSUE THREAD

**Issue by hawkofsky** [NomicFoundation/hardhat#4395]
### Version of Hardhat

2.13.0

### What happened?

this is a part of my smart contract.
````
import "@openzeppelin/contracts-upgradeable/proxy/ClonesUpgradeable.sol";
...
contract Test {
...
  function createVault(uint256 vaultId) {
    ...
    address vault = ClonesUpgradeable.clone(vaultImplementation);
    console.log(vault);
    emit VaultCreated(msg.sender, vault);
  }
}
````
And I called `createVault()` function several times using scripts(javascript) in one test file.
it should've generated different address of vaults each time but all addresses are the same so i can't do further test on behavior of those vaults.
````
Test.connect(alice).createVault(1);
Test.connect(bob).createVault(2);
````

### Minimal reproduction steps

run `npx hardhat test` to check the generated addresses in the console.
They are always the same.

### Search terms

clone same address

**Comment by fvictorio** [comment]
Hey @hawkofsky, I tried to reproduce this but I couldn't. Here's what I tried.

I have this solidity code:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts-upgradeable/proxy/ClonesUpgradeable.sol";

import "hardhat/console.sol";

contract Foo {}

contract Test {
  function createClone(address implementation) public {
    address clone = ClonesUpgradeable.clone(implementation);
    console.log(clone);
  }
}
```

and this test:

```js
const { expect } = require("chai");

describe("clones", function () {
  it("test", async function () {
    const foo = await ethers.deployContract("Foo");
    const test = await ethers.deployContract("Test");

    await test.createClone(foo.target);
  });

  it("test 2", async function () {
    const foo = await ethers.deployContract("Foo");
    const test = await ethers.deployContract("Test");

    await test.createClone(foo.target);
  });
});
```

And two different addresses are logged.

One reason why this could be happening to you is if you are resetting the network, for example doing something like:

```js
  // reset the network before each test
  beforeEach(async function () {
    await network.provider.send("hardhat_reset", [])
  });
```

The other reason this could be happening is if you are using [fixtures](https://hardhat.org/hardhat-runner/docs/guides/test-contracts#using-fixtures), which use snapshots under the hood.

If neither of those is the case, then we'll need a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to be able to look into this.

**Comment by hawkofsky** [comment]
Oh, you're right. It works now. Thank you.
