### ISSUE TITLE
In delegatecall, target contract state variables are incorrect when doing unit test.

### ISSUE THREAD

**Issue by hawkofsky** [NomicFoundation/hardhat#4402]
### Version of Hardhat

2.17.3

### What happened?

In delegatecall, target contract state variables are incorrect when doing unit test.
Here is a simplified version of smart contract for reproduction.
````
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "hardhat/console.sol";

contract Foo {
  address public masterChef;
  
  constructor() {
    masterChef = address(0x9BA666165867E916Ee7Ed3a3aE6C19415C2fBDDD);
  }
  
  function stake() external view {
    console.log(masterChef);
  }
}

contract Test {
  address strategy;

  function setStrategy(address _strategy) external {
    strategy = _strategy;
  }

  function callStrategy() public {
    bytes memory performData = abi.encodeWithSignature("stake()");
    (bool success, ) = strategy.delegatecall(performData);
    require(success == true, "delegatecall failed");
  }
}

````
And this is a test file in javascript.
````

describe("test", function () {
  it("test", async function () {
    const foo = await ethers.deployContract("Foo");
    const test = await ethers.deployContract("Test");
    
    await test.setStrategy(foo.target);

    await test.callStrategy();
  });
});
````
It should print the masterchef address i hardcoded but see different address(it seems the deployed address of foo contract).

### Minimal reproduction steps

Just run `npx hardhat test` with the above the code.

### Search terms

delegatecall

**Comment by hawkofsky** [comment]
@fvictorio @ChristopherDedominici any comments on this issue?

**Comment by fvictorio** [comment]
That behavior is correct, unless I'm missing something.

The way delegate call works is that the storage of the *calling* contract will be used with the logic of the *called* contract. In this case, the logic says "log the first address in the storage", but since the storage of `Test` is being used for that, you get a log with the `strategy` address.

Tentatively closing because I think this is working as expected.
