### ISSUE TITLE
Update default hardhat.config.js

### ISSUE THREAD

**Issue by SKYBITDev3** [NomicFoundation/hardhat#4424]
### Describe the feature

Currently the default contents of hardhat.config.js just after a user runs `yarn hardhat init` is

```js
require("@nomicfoundation/hardhat-toolbox");

/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  solidity: "0.8.19",
};
```

It'd be good to update it to include other very important settings like `optimizer` and `evmVersion` e.g.:

```js
solidity: {
    compilers: [
      {
        version: `0.8.21`,
        settings: {
          optimizer: {
            enabled: true,
            runs: 1000
          },
          evmVersion: `shanghai`, // downgrade to `paris` if you encounter 'invalid opcode' error
        }
      },
    ],
  },
```

**Comment by fvictorio** [comment]
Thanks for the suggestion @SKYBITDev3, but we discussed this and we think that being more explicit in the output (which we are doing now) is enough for now. Having a more verbose config by default doesn't seem worth it.

We might re-consider our whole approach to the default EVM target later, as Shanghai gets more adoption.

**Comment by SKYBITDev3** [comment]
OK though I thought it'd be a good idea to set recommended settings, especially enabling `optimizer`.
