### ISSUE TITLE
Compiles Every Time

### ISSUE THREAD

**Issue by amarpatel** [NomicFoundation/hardhat#4439]
### Version of Hardhat

2.17.4 + 2.17.1

### What happened?

After compiling, when running tests, HH used to say some message like "nothing to compile".  That isn't happening anymore.

I ran the following command:
```
npx hardhat clean && npx hardhat clean --global && rm -rf node_modules && yarn install && npx hardhat compile;
npx hardhat test;
npx hardhat test;
```

<img width="630" alt="image" src="https://github.com/NomicFoundation/hardhat/assets/5858247/a8067ed0-0bcc-4e4a-bff8-f7d643e3252b">

Unless `--no-compile` is specified, this behavior adds ~60s to each test run.  It's impractical to update all the callsites to address this regression.

### Minimal reproduction steps

```
npx hardhat clean && npx hardhat clean --global && rm -rf node_modules && yarn install && npx hardhat compile;
npx hardhat test;
npx hardhat test;
```

### Search terms

hardhat compile every time, hardhat compile before testing

**Comment by ChristopherDedominici** [comment]
Hi @amarpatel, I tried to repro but for me it works correctly. 
Could you please provide the code example that you used so I can repro the exact scenario? Thanks.

**Comment by amarpatel** [comment]
My team is working on a private repo, so I'm not able to provide a link.

Are there any limitations that cause compiles to run _on every action_? (EG: memory limits, quantity of solidity files, etc.).  My dev environment includes the following:

```bash
export HARDHAT_MAX_MEMORY=4096
export NODE_OPTIONS=--max_old_space_size=4096
```

**Comment by fvictorio** [comment]
Hey @amarpatel, if you are running `npx hardhat compile` twice and it's compiling both times, then that's either a bug in Hardhat or something strange in your setup. The reasons why Hardhat would compile the second time are that you changed something in the files or in the solidity config, or that the cache directory was removed, or something like that.

If this is a bug, then we'll need some way to reproduce it. If you can give me or @ChristopherDedominici temporary access to your repo, we can take a look. If that's not possible, then the only thing you could do is try to create a separate reproduction repo that you can share (for example, by eliminating all the code you can while preserving the unexpected behavior).
