### ISSUE TITLE
hardhat test doesn't run any tests and ends with passing 0

### ISSUE THREAD

**Issue by 0x0OZ** [NomicFoundation/hardhat#4464]
### Version of Hardhat

2.18.0

### What happened?

The long version: I have a hardhat project with foundry, I followed instructions in _both_ foundrybook and hardhat docs and things were going well after I removed the contract and the test Lock.sol, Lock.ts the tests stopped working and started giving 0 passing.

![image](https://github.com/NomicFoundation/hardhat/assets/52073989/2196ffbb-9b87-4b67-9c0a-8f89436cc738)

After I found the cause (I didn't know removing lock.ts is the cause at first ), I made a simple hardhat project with my contract and test and I was able to reproduce the bug when I remove the test lock.ts .

### Minimal reproduction steps

Create a simple TS hardhat project, add any contract with test then remove the test for Lock.ts .

You can also just clone the repo that has this issue and try to run the test with and without the Lock.ts test
https://github.com/0x0OZ/freeflow-taxableToken/tree/0c74903012bb0ecefc68568fd693787917817c5f

### Search terms

hardhat test passing zero / fix hardhat test /  hardhat test doesn't run

**Comment by 0x0OZ** [comment]
Hey @fvictorio,

You don't need to debug this I found the main cause
In my Token.ts I was using async with the first `describe` which caused no test to be really executed before the program exits...
and when having the Lock.ts test this gives the execution enough time to run the Async tests to give the results.

### Solution:
To solve this I just need to remove the **async** from the main `describe` statement and fix any following-up errors by removing it.

This is a native JS behavior and not a hardhat bug, So I will close it as it doesn't require any further actions from your side.

**Comment by fvictorio** [comment]
Thanks for letting us know!
