### ISSUE TITLE
allow for hardhat local node port flag

### ISSUE THREAD

**Issue by mshakeg** [NomicFoundation/hardhat#4477]
### Describe the feature

I would like to start the hardhat local node at a port other than _8545_.

I would like to start multiple hardhat local nodes each at their own unique port.

#### Suggestion

I suggest adding a `--port` flag to the `hardhat node` command for this purpose.

### Search terms

hardhat network local node port

**Comment by fvictorio** [comment]
The `hh node` command already has a `--port` parameter.

**Comment by mshakeg** [comment]
@fvictorio thanks, though couldn't find it in the docs

**Comment by fvictorio** [comment]
No problem. You can use the `--help` flag with any task to see which parameters they support.

**Comment by 0x-Avant-Garde** [comment]
I just did a search for this same info and it took me about 15 min to land here.  It would be nice if the docs were updated to include this info, even though it is available in --help.
