### ISSUE TITLE
Hardhat not recognizing functions in my contract as functions

### ISSUE THREAD

**Issue by eik-1** [NomicFoundation/hardhat#4478]
### Version of Hardhat

2.18.1

### What happened?

I am writing tests for my smart contracts. 
I am using deployments.get() to get my deployed contracts. 
`fundMe = await deployments.get("FundMe", deployer)`

Now if I use `fundMe.fund()` in the testing code, it will give me an error: 
```error
TypeError: fundMe.fund is not a function
```
While if I use `fundMe.fund` instead, it will work just fine.
So the main problem arises when I have to enter the parameters for a function which I can't without using ().

### Minimal reproduction steps

Add `hardhat-deploy`,`hardhat-deploy-ethers` and `hardhat` using yarn.
Override hardhat-ethers using the command
```
yarn add --dev @nomicfoundation/hardhat-ethers@npm:hardhat-deploy-ethers ethers
```
Write unit test for contracts.
Use the functions inside the contract using () at the end of function name.

### Search terms

Testing

**Comment by fvictorio** [comment]
Hey @eik-1, sorry but we'll need more detailed reproduction steps. Ideally a repository with a
[minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that we can just clone and run some commands to reproduce the problem.
