### ISSUE TITLE
Error HH801: Plugin @nomicfoundation/hardhat-toolbox

### ISSUE THREAD

**Issue by nikitamarcius** [NomicFoundation/hardhat#4479]
Hi,  why does a package @nomicfoundation/hardhat-toolbox with dev dependencies require devDependences to be installed separately in root project?

Error HH801: Plugin @nomicfoundation/hardhat-toolbox requires the following dependencies to be installed: @nomicfoundation/hardhat-network-helpers, @nomicfoundation/hardhat-chai-matchers, @nomicfoundation/hardhat-ethers, @nomicfoundation/hardhat-verify, @types/chai, @types/mocha, @typechain/ethers-v6, @typechain/hardhat, chai, ethers, hardhat-gas-reporter, solidity-coverage, typechain.
Please run: npm install --save-dev "@nomicfoundation/hardhat-network-helpers@^1.0.0" "@nomicfoundation/hardhat-chai-matchers@^2.0.0" "@nomicfoundation/hardhat-ethers@^3.0.0" "@nomicfoundation/hardhat-verify@^1.0.0" "@types/chai@^4.2.0" "@types/mocha@>=9.1.0" "@typechain/ethers-v6@^0.4.0" "@typechain/hardhat@^8.0.0" "chai@^4.2.0" "ethers@^6.4.0" "hardhat-gas-reporter@^1.0.8" "solidity-coverage@^0.8.1" "typechain@^8.2.0"

For more info go to https://hardhat.org/HH801 or run Hardhat with --show-stack-traces

**Comment by fvictorio** [comment]
Those are peer dependencies, not dev dependencies. A peer dependency is something that has to be installed _along_ with the package. If you are using npm 7 or later, these are installed automatically. If you are using yarn or an older version of npm, then you'll need to manually install them. We recommend using a recent version of npm to avoid having to do that.

**Comment by nikitamarcius** [comment]
my version, npm -v 9.6.7
