### ISSUE TITLE
Improve Tasks documentation? (+ suggestion)

### ISSUE THREAD

**Issue by tmilar** [NomicFoundation/hardhat#448]
Currently, the (built-in) [tasks documentation](https://buidler.dev/guides/create-task.html) is a bit... lacking. 
We only have a link to the [src/builtin-tasks](https://github.com/nomiclabs/buidler/tree/master/packages/buidler-core/src/builtin-tasks) folder and that's it. Any user or developer interested would have to look deep into the sources to understand what is going on. 

A suggestion to improve this, could be writing a README doc per task, and bundle it together with the task file, inside a folder of the same name. This way, the task would also gain a "modular-like" feel which could give room for more complex structures in an already familiar way.

Also, we could improve the project tasks documentation by actually enumerating the existing built-in tasks, with links that display the proper doc of the task.

Any feedback?

**Comment by Alexangelj** [comment]
One good note that should be included in the docs is to make sure tasks outside the config file are being `required` in the config file.

**Comment by morgansliman** [comment]
@alcuadrado @fvictorio is this still relevant/something we want to do?
