### ISSUE TITLE
extendProvider is broken with eth_sendTransaction method

### ISSUE THREAD

**Issue by kaliubuntu0206** [NomicFoundation/hardhat#4489]
### Version of Hardhat

2.18.1

### What happened?

extendProvider() should work with 'eth_sendTransaction' request according to the docs https://hardhat.org/hardhat-runner/docs/advanced/building-plugins#extending-the-hardhat-provider however it doesn't.

Overrided 'request' function works with every other methods except the 'eth_sendTransaction' function.

### Minimal reproduction steps

Following the example -> used console.log(args) to check but it didn't work

**Comment by fvictorio** [comment]
Hi @kaliubuntu0206, `extendProvider` works fine for me with `eth_sendTransaction`. Adapting the code from the docs:

```javascript
const { ProviderWrapper } = require( 'hardhat/plugins')

class LogProvider extends ProviderWrapper {
  constructor(
    _wrappedProvider
  ) {
    super(_wrappedProvider);
  }

  async request(args) {
    if (args.method === "eth_sendTransaction") {
      console.log("some eth_sendTransaction")
    }

    return this._wrappedProvider.request(args);
  }
}

extendProvider(async (provider, config, network) => {
  const newProvider = new LogProvider(provider);
  return newProvider;
});
```

I send some transactions and get that log.

I'm tentatively closing this, but I'll re-open if you can give us more precise reproduction steps.

**Comment by kaliubuntu0206** [comment]
@fvictorio It could be reproduced. It happens on non 'hardhat' network
