### ISSUE TITLE
Support N-arity (multi-valued) params for tasks?

### ISSUE THREAD

**Issue by tmilar** [NomicFoundation/hardhat#449]
Currently, valued params (AKA non flags), support only one value. For example:
```
npx buidler mytask --threshold 100
```

Is there any interest from the community on allowing multiple values per-param? Such as:
```
# 'gas-range' would be a 2-value param, imagine [min, max]  
npx buidler mytask --gas-range 100 500
```
Or alternatively:
```
# here the [min, max] param values would be parsed in the same order as they appear
npx buidler mytask --gas-range 100 --gas-range 500
```
A first implementation would allow N-arity params where N is known beforehand, otherwise having _variadic_ param values could lead to ambiguous situations combined with other params.

**Comment by fvictorio** [comment]
Personal opinion:

`--gas-range 100 500` is something you _can_ have, but I think it's not common to use this kind of interface in the command line.

`--gas-range 100 --gas-range 500` is a little better, but the problem for this example is that using a flag multiple times is usually interpreted as a list of values that should probably not be order-dependent. I think of this as similar to sending multiple values in a query string, where `foo=1&foo=2` is usually interpreted as `foo = [1, 2]` in application code. A common example is something like `--ignore-dir`, where you might want to specify it multiple times.

I mean, for the particular case of `--gas-range`, I would suggest using `--gas-range 100,500`, but supporting multiple flags as a way of specifying a list of values seems like a good idea.

**Comment by fvictorio** [comment]
Closing this because it's unlikely will do it.
