### ISSUE TITLE
How to use a custom signer class?

### ISSUE THREAD

**Issue by ViniciusAlberkovics** [NomicFoundation/hardhat#4498]
I'm using a class similar to the one below to try to deploy a contract, but an error occurs when trying to send the transaction.

Error when trying deploy `provider.sendTransaction is not a function`

CustomSigner.js
```
const { getAddress } = require('@ethersproject/address');
const { _TypedDataEncoder } = require('@ethersproject/hash');
const { Signer } = require('@ethersproject/abstract-signer');

class CustomSigner extends Signer {
  provider;
  constructor(provider) {
    super();
    this.provider = provider;
  }

  async signTransaction(tx) {
   // ....
   return 'RAW_TRANSACTION';
  }
}
```

**Comment by fvictorio** [comment]
Hi @ViniciusAlberkovics, I think you should ask this in [ethers' repo](https://github.com/ethers-io/ethers.js)
