### ISSUE TITLE
save the state of hardhat node

### ISSUE THREAD

**Issue by kifah1989** [NomicFoundation/hardhat#4517]
### Describe the feature

i can do this in ganache using the command `ganache --port 8545 --chain.chainId 1337 --db eth_db `. now since truffle and ganache is discontinuing their project and the partnership with hardhat  i would like to achieve the same feature.

### Search terms

how to save hardhat node state?

**Comment by 0xHristo** [comment]
Is such feature planned?

**Comment by schaable** [comment]
Hi @kifah1989, we have it planned, but we don't have an ETA. See: #3504.
