### ISSUE TITLE
Reopening: Hardhat couldn't infer error reason - random revert behaviour

### ISSUE THREAD

**Issue by bibimohamed** [NomicFoundation/hardhat#4518]
### Version of Hardhat

2.17.2

### What happened?

Exact same issue as this: https://github.com/NomicFoundation/hardhat/issues/1904. 

### Minimal reproduction steps

https://github.com/NomicFoundation/hardhat/issues/1904

**Comment by fvictorio** [comment]
Hi @bibimohamed, from skimming the issue you linked, there doesn't seem to be good reproduction steps there. Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) please?

**Comment by hudeintres** [comment]
I am also running into this issue. I believe all you need to do is 
1. clone [Aave's repo](https://github.com/aave/protocol-v2) 
2. run the tests mulitple times using `npm run test`
3. it will fail erratically with the issue linked.

As reported by others, it's extremely difficult to reproduce and isolate. I've tried adding many logs and have isolated the problem to event emssions.

**Comment by fvictorio** [comment]
@hudeintres is the test that fails always the same? If so, could you maybe create a branch that only runs that test, so that it's faster to run multiple times and reproduce?
