### ISSUE TITLE
TransferFrom is failing with insuficient allowance

### ISSUE THREAD

**Issue by Madeindreams** [NomicFoundation/hardhat#4524]
### Version of Hardhat

2.18.2

### What happened?

I'm writing test for my contract and all transferFrom call are failing with insuficient allowance even if the allowance is returning the correct value.

These transferFrom are tested by directly calling the contract as an account or as a contract and both fail.

All the logs indicate that the allowance is set.

For instance:

```
                const balance = await www3Shares.balanceOf(owner)
                console.log("owner balance:", balance)

                await www3Shares.connect(owner).approve(www3Shares.target, ethers.parseEther("100"))
                const allowance = await www3Shares.allowance(owner.address, www3Shares.target)

                console.log("allowance:",allowance)
                expect(await www3Shares.connect(owner).sellShares(ethers.parseEther("25")))
```

The logs are showing the correct balance and allowance.

Even inside the contract itself;
```
        console.log(allowance(_msgSender(), address(this)));  // <-- log the same allowance as the test
        transferFrom(_msgSender(), address(this), amount);
```
The error i'm getting is (depending on the OZ version)
Insufficient allowance with OZ < 5.0.0
and 
`reverted with an unrecognized custom error (return data: 0xfb8f41b2000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb9226600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000015af1d78b58c40000)`

With OZ 5.0.0

### Minimal reproduction steps

This repo his a minimal example of the situation

https://github.com/Madeindreams/transfer-case/tree/main

**Comment by schaable** [comment]
Hi @Madeindreams, this seems to be a problem related to OZ, not Hardhat. You should open an issue on [their Github](https://github.com/OpenZeppelin/openzeppelin-contracts/issues).

**Comment by Madeindreams** [comment]
Found the issue
