### ISSUE TITLE
can I safely use `@nomicfoundation/hardhat-verify@2.0.0` with `hardhat-toolbox 3.0.0` ?

### ISSUE THREAD

**Issue by SvenMeyer** [NomicFoundation/hardhat#4556]
### Version of Hardhat

2.18.3

### What happened?

 WARN  Issues with peer dependencies found
.
└─┬ @nomicfoundation/hardhat-toolbox 3.0.0
  └── ✕ unmet peer @nomicfoundation/hardhat-verify@^1.0.0: found 2.0.0

### Minimal reproduction steps

(How) can I safely use `@nomicfoundation/hardhat-verify@2.0.0` with `hardhat-toolbox 3.0.0` ?

```
$ pnpm up @nomicfoundation/hardhat-verify
 WARN  7 deprecated subdependencies found: debug@3.2.6, fsevents@2.1.3, har-validator@5.1.5, request-promise-native@1.0.9, request@2.88.2, uuid@2.0.1, uuid@3.4.0
Packages: +5 -2
+++++--
Progress: resolved 813, reused 802, downloaded 1, added 5, done

devDependencies:
- @nomicfoundation/hardhat-verify 1.1.1
+ @nomicfoundation/hardhat-verify 2.0.0

 WARN  Issues with peer dependencies found
.
└─┬ @nomicfoundation/hardhat-toolbox 3.0.0
  └── ✕ unmet peer @nomicfoundation/hardhat-verify@^1.0.0: found 2.0.0

```

**Comment by fvictorio** [comment]
Hi @SvenMeyer, we [bumped](https://github.com/NomicFoundation/hardhat/pull/4564) the version of hh-verify in the toolboxes, which should fix your problem. This will be included in the next release, which we'll probably make tomorrow.
