### ISSUE TITLE
ethers import doesn't work properly with commonjs TypeScript

### ISSUE THREAD

**Issue by FFdhorkin** [NomicFoundation/hardhat#4565]
### Version of Hardhat

2.18.0

### What happened?

My package.json does not specify `"type": "module"`.

If I use `import` in my `hardhat.config.ts` file, then hardhat works fine, but nextjs complains "Cannot use import statement outside a module"

As a result, I tried changing my hardhat.config.ts from 

```ts
import '@typechain/hardhat';
import '@nomicfoundation/hardhat-ethers';
import '@nomicfoundation/hardhat-chai-matchers';
import '@nomicfoundation/hardhat-toolbox';

const config = {
    solidity: '0.8.18',
    paths: {
        root: './hardhat',
    },
};

module.exports = config;
```

to

```ts
require('@typechain/hardhat');
require('@nomicfoundation/hardhat-ethers');
require('@nomicfoundation/hardhat-chai-matchers');
require('@nomicfoundation/hardhat-toolbox');

const config = {
    solidity: '0.8.18',
    paths: {
        root: './hardhat',
    },
};

module.exports = config;
```

The [Typescript docs ](https://hardhat.org/hardhat-runner/docs/guides/typescript) say you need to use import instead of require, but given the hardhat.config.ts is going to get transpiled anyway...

Hardhat itself still works when I use require, but now I get a `Module '"hardhat"' has no exported member 'ethers'.ts(2305)` error` in vscode / a bunch of linting errors about unsafe use of any type.

There are a number of similar-sounding issues (#1137 #1279 #1627 #1640 #2291 #3811), but I believe this is distinct, as the issue only happens when using `require` in a `.ts` config file, and it happens even when I include the config file in my `files` section of tsconfig.

The two workarounds I've found so far:
- explicitly include path to the .d.ts file in your tsconfig.json (messy)
- add `/// <reference types="@nomicfoundation/hardhat-ethers" />` at the top of `hardhat.config.ts`
- add `compilerOptions.types` section and include `@nomicfoundation/hardhat-ethers`

### Minimal reproduction steps

Create a Hardhat Typescript project, but use `require` instead of `import` in your `hardhat.config.ts`

### Search terms

ethers, import

**Comment by fvictorio** [comment]
Your first snippet seems wrong to me:

```
import '@typechain/hardhat';
import '@nomicfoundation/hardhat-ethers';
import '@nomicfoundation/hardhat-chai-matchers';
import '@nomicfoundation/hardhat-toolbox';

const config = {
    solidity: '0.8.18',
    paths: {
        root: './hardhat',
    },
};

module.exports = config;
```

That last line should be `export default config` instead.

**Comment by FFdhorkin** [comment]
I believe my original code had that, but I double-checked on the latest version of code and now the original issue doesn't seem to reproduce either way. Not sure why, but I'll take it.

**Comment by FFdhorkin** [comment]
OK, started having this issue again.

hardhat.config.ts:
```
import '@typechain/hardhat';
import '@nomicfoundation/hardhat-ethers';
import '@nomicfoundation/hardhat-chai-matchers';
import '@nomicfoundation/hardhat-toolbox';
import 'tsconfig-paths/register';

import type { HardhatUserConfig } from 'hardhat/config';

const config: HardhatUserConfig = {
    solidity: '0.8.18',
    paths: {
        root: './hardhat',
    },
    typechain: {
        discriminateTypes: true,
    },
};

export default config;
```

trying to do `import hre from 'hardhat';` results in:
```
 ⨯ /home/dhorkin/repos/*****/hardhat.config.ts:1
import '@typechain/hardhat';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.hardhat (/home/dhorkin/repos/*****/nextjs/.next/server/app/[gameType]/[[...gameId]]/page.js:22:18)
    at __webpack_require__ (/home/dhorkin/repos/*****/nextjs/.next/server/webpack-runtime.js:33:43)
    at eval (../game/web3/gameDatabase.ts:11:65)
    at (rsc)/../game/web3/gameDatabase.ts (/home/dhorkin/repos/*****/nextjs/.next/server/_rsc_Game_web3_gameDatabase_ts.js:690:1)
    at Function.__webpack_require__ (/home/dhorkin/repos/*****/nextjs/.next/server/webpack-runtime.js:33:43)
    at async GameDirector (./app/[gameType]/[[...gameId]]/page.tsx:22:286)
 ⨯ /home/dhorkin/repos/*****/hardhat.config.ts:1
```

I suspect this issue has something to do with the fact that the place where I used `import hre from 'hardhat';` is being run through webpack

**Comment by fvictorio** [comment]
> I suspect this issue has something to do with the fact that the place where I used import hre from 'hardhat'; is being run through webpack

That's probably the reason. Hardhat is not meant to be bundled, and if you try you are likely to run into errors like this. If you can, I'd recommend separating the Hardhat part of your project from the part that is processed through nextjs/webpack.

Tentatively closing this for now.
