### ISSUE TITLE
Testing frameworks not working on live networks

### ISSUE THREAD

**Issue by lyh970817** [NomicFoundation/hardhat#4572]
### Version of Hardhat

2.13.0

### What happened?

I can use the expect statement in the following manner when testing with hardhat local network:
```
expect(await goodbye.airnode(), "Airnode address").to.not.equal(ethers.constants.AddressZero);
```
This, however, does not work when the contract is deployed on a live network (`npx hardhat test --network mumbai`. It appears to forever hangs when the statement previous to the `expect` statement finishes running.

### Minimal reproduction steps

Add config for a live network in `hardhat.config.js`, deploy a smart contract on the live network with any public variable and use an `expect` statement similar to the following in a file in the `test` folder: 
```
expect(await CONTRACT.PUBLIC_VARIABLE(), "Public variable").to.not.equal(ethers.constants.AddressZero);
```

### Search terms

test, chai, expect

**Comment by fvictorio** [comment]
Hi @lyh970817, the only reason that statement could hang is if the `goodbye.airnode()` is hanging. That might be related to the node provider you are connecting to or something else, but it's unlikely to be related to Hardhat. Notice that you are using a plain `.to.equal` comparison, so this doesn't even involve our plugins.

Happy to re-open if you can provide specific steps that show that something is not working on our side.
