### ISSUE TITLE
SocketError: other side closed

### ISSUE THREAD

**Issue by GopherJ** [NomicFoundation/hardhat#4601]
### Version of Hardhat

2.17.1

### What happened?

after executing a command using shelljs, I cannot call contract method anymore, it just throws other side closed

### Minimal reproduction steps

1. connect to provider
2. execute a child process and wait for it to end
3. call contract method

**Comment by schaable** [comment]
Closing as we don't have enough information to reproduce it. We can reopen if a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) is provided.
