### ISSUE TITLE
Hardhat Node does not support "input" as field for eth_call input

### ISSUE THREAD

**Issue by rzmahmood** [NomicFoundation/hardhat#4603]
### Version of Hardhat

2.19.1

### What happened?

The go-ethereum team switched to using `input` instead of `data` in their transaction objects in `ethclient`. This caused our `eth_call`s to break since hardhat does not expect `input`. Ideally hardhat node can support both fields.

Hardhat node will instead just set the data field to `0x` which will cause most `eth_call`s to revert with error `Transaction reverted without a reason string`

Their PR: https://github.com/ethereum/go-ethereum/pull/28078

### Minimal reproduction steps

Make a transaction where the data payload is using field `input` instead of `data`.

**Comment by rzmahmood** [comment]
Duplicate of https://github.com/NomicFoundation/hardhat/pull/4438

Feel free to close, but would like visibility on this

**Comment by schaable** [comment]
Closing as duplicate.
