### ISSUE TITLE
`_findVersionRelease` fails for release tag names containing rc

### ISSUE THREAD

**Issue by peterpolman** [NomicFoundation/hardhat#4615]
### Version of Hardhat

2.17.2

### What happened?

On a fresh install with a system that does not have the vyper binary installed, compilation fails when it attempts to download the binary.
```
Uncaught TypeError: Invalid Version: v0.3.10rc5
```
It appears the `semver` dep for `hardhat-vyper` throws the above when it runs semver.eq() while searching through the version list and encountering  prerelease version string `v0.3.10rc5` which is considered to be incorrect semver.

Issue is on this line:
https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-vyper/src/downloader.ts#L133

Fixed with:
```diff
- semver.eq(release.tag_name, version)
+ semver.eq(semver.coerce(release.tag_name).version, version)
```

### Minimal reproduction steps

Run `hardhat compile` a vyper file with no vyper binaries installed in order to trigger the download..

Semver will throw then running this:
```
semver.eq('v0.3.10rc5', '0.3.7')
```

### Search terms

vyper semver download

**Comment by fvictorio** [comment]
Hi @peterpolman, are you sure you are using the latest version of `hardhat-vyper`? That's the error that v3.0.5 of the plugin fixed after this PR: https://github.com/NomicFoundation/hardhat/pull/4552

**Comment by fvictorio** [comment]
Tentatively closing this, will re-open if what I said in the previous comment is wrong.
