### ISSUE TITLE
 Chain Re-org detected

### ISSUE THREAD

**Issue by mafangtao** [NomicFoundation/hardhat#4633]
After the fork of block 18677268, I sent the transactions of block 18677269 to the fork's rpc port in order, and the following problem occurred.

Some transactions are normal, and some prompt Chain Re-org detected. I don’t know why this happens.

这是第 1 笔交易的日志
txhash : 0x8ea73cb11da23513698ff46ee2527df479c41c4e59d8e2f75f44ebedd4df35bd
sendTransaction Error: VM Exception while processing transaction: reverted with reason string 'Chain Re-org detected'
这是第 2 笔交易的日志
txhash : 0xf1b949b09ceb18b10d89b40f7f870d01be1687f4cc24c39be247860fb1aa275f
sendTransaction Error: VM Exception while processing transaction: reverted with reason string 'Chain Re-org detected'
这是第 3 笔交易的日志
txhash : 0x2543e2bd2efd6892697fecf50edebafd186cf186d3f81b0197c4da3c5edd14a7
sendTransaction Error: VM Exception while processing transaction: reverted with reason string 'Chain Re-org detected'

这是第 4 笔交易的日志
txhash : 0x98f4ab09b0054e8cafd76b80f86c01497f1519eb8a458359fe6af9a62a3cbe70
logs [0x4d29de21de555af78a62fc82dd4bc05e9ae5b0660a37f04729527e0f22780cd3]
logs [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0x00000000000000000000000044f12ef573f5a70464b7904e037aff4ec0061c6f 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969]
logs [0x9d9c909296d9c674451c0c24f02cb64981eb3b727f99865939192f880a755dcb 0x00000000000000000000000044f12ef573f5a70464b7904e037aff4ec0061c6f 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969]
logs [0x4d29de21de555af78a62fc82dd4bc05e9ae5b0660a37f04729527e0f22780cd3]
logs [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969 0x000000000000000000000000c8353594eeedc5ce5a4544d3d9907b694c4690ff]
logs [0x9d9c909296d9c674451c0c24f02cb64981eb3b727f99865939192f880a755dcb 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969 0x000000000000000000000000c8353594eeedc5ce5a4544d3d9907b694c4690ff]
logs [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0x000000000000000000000000c8353594eeedc5ce5a4544d3d9907b694c4690ff 0x000000000000000000000000d585aaafa2b58b1cd75092b51ade9fa4ce52f247]
logs [0x9d9c909296d9c674451c0c24f02cb64981eb3b727f99865939192f880a755dcb 0x000000000000000000000000c8353594eeedc5ce5a4544d3d9907b694c4690ff 0x000000000000000000000000d585aaafa2b58b1cd75092b51ade9fa4ce52f247]
logs [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0x0000000000000000000000000000000000000000000000000000000000000000 0x000000000000000000000000c8353594eeedc5ce5a4544d3d9907b694c4690ff]
logs [0x37eeac1c5ccc56f99777b030d55a9e26231d4146475be9fb25f82481a03b7457 0x000000000000000000000000c8353594eeedc5ce5a4544d3d9907b694c4690ff]
logs [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0x000000000000000000000000c8353594eeedc5ce5a4544d3d9907b694c4690ff 0x000000000000000000000000c2966a73bbc53f3c99268ed84d245dbe972ed89e]
logs [0xe7e1af2362367a378dc8f5d7dbedafd63d7a9a11bac7cff67c0e6fd2e4790948 0x000000000000000000000000d585aaafa2b58b1cd75092b51ade9fa4ce52f247]
logs [0x8b2a1e1ad5e0578c3dd82494156e985dade827a87c573b5c1c7716a32162ad64 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969]
logs [0xec0804e8e1decb589af9c4ba8ebfbacd3be98929d4d53457dfd186061f489f04 0x000000000000000000000000c8353594eeedc5ce5a4544d3d9907b694c4690ff]
logs [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0x000000000000000000000000a980d4c0c2e48d305b582aa439a3575e3de06f0e 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969]
logs [0x9d9c909296d9c674451c0c24f02cb64981eb3b727f99865939192f880a755dcb 0x000000000000000000000000a980d4c0c2e48d305b582aa439a3575e3de06f0e 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969]
logs [0xe64f87293a785dc4cbf1b9b65f3cfd04beb2bac2c656aec8f79b2e70be1f8873]
logs [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969 0x00000000000000000000000021e27a5e5513d6e65c4f830167390997aa84843a]
logs [0x9d9c909296d9c674451c0c24f02cb64981eb3b727f99865939192f880a755dcb 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969 0x00000000000000000000000021e27a5e5513d6e65c4f830167390997aa84843a]
logs [0x8b3e96f2b889fa771c53c981b40daf005f63f637f1869f707052d15a3dd97140 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969]
logs [0xe1fffcc4923d04b559f4d29a8bfc6cda04eb5b0d3c460751c2402c5c5cc9109c 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969]
logs [0x4d29de21de555af78a62fc82dd4bc05e9ae5b0660a37f04729527e0f22780cd3]
logs [0x7fcf532c15f0a6db0bd6d0e038bea71d30d808c7d98cb3bf7268a95bf5081b65 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969]
logs [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0x00000000000000000000000088e6a0c2ddd26feeb64f039a2c41296fcb3f5640 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969]
logs [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969 0x00000000000000000000000088e6a0c2ddd26feeb64f039a2c41296fcb3f5640]
logs [0xc42079f94a6350d7e6235f29174924f928cc2ac818eb64fed8004e115fbcca67 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969]
logs [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969 0x0000000000000000000000002673099769201c08e9a5e63b25fbaf25541a6557]
logs [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0x0000000000000000000000002673099769201c08e9a5e63b25fbaf25541a6557 0x000000000000000000000000bebc44782c7db0a1a60cb6fe97d0b483032ff1c7]
logs [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0x0000000000000000000000000000000000000000000000000000000000000000 0x0000000000000000000000002673099769201c08e9a5e63b25fbaf25541a6557]
logs [0x423f6495a08fc652425cf4ed0d1f9e37e571d9b9529b1c1c23cce780b2e7df0d 0x0000000000000000000000002673099769201c08e9a5e63b25fbaf25541a6557]
logs [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0x0000000000000000000000002673099769201c08e9a5e63b25fbaf25541a6557 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969]
logs [0x9d9c909296d9c674451c0c24f02cb64981eb3b727f99865939192f880a755dcb 0x0000000000000000000000002673099769201c08e9a5e63b25fbaf25541a6557 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969]
logs [0xd013ca23e77a65003c2c659c5442c00c805371b7fc1ebd4c206c41d1536bd90b 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969]
logs [0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969 0x00000000000000000000000044f12ef573f5a70464b7904e037aff4ec0061c6f]
logs [0x9d9c909296d9c674451c0c24f02cb64981eb3b727f99865939192f880a755dcb 0x0000000000000000000000006058ff6594bb1643e374eb1fd40f992102735969 0x00000000000000000000000044f12ef573f5a70464b7904e037aff4ec0061c6f]
这是第 5 笔交易的日志
txhash : 0xc2854a1c38f7205f9c12e3a73252e3c8d1db4cd0dc0688d800c15f28d34e6c48
sendTransaction Error: VM Exception while processing transaction: reverted with reason string 'Chain Re-org detected'

**Comment by fvictorio** [comment]
Hi @mafangtao, re-creating a block in a fork is a bit harder than it seems. For example, you need to make sure that the timestamp of the forked block (and subsequent blocks) is correct, since that can affect the execution of the transactions. My guess is that there's something in the state of your local forked chain that it's not 100% the same as in the remote chain, and that causes those transactions to revert.
