### ISSUE TITLE
Add specific HardhatError msgs for hardhat-viem plugin

### ISSUE THREAD

**Issue by Aliceonly** [NomicFoundation/hardhat#4636]
### Describe the feature

Using Viem To deploy contract (or any transaction execution calls) when run into panic, it shows:
TransactionExecutionError: Invalid parameters were provided to the RPC method.
Double check you have provided the correct parameters.

In Hardhat-ethers, it shows:
HardhatEthersError: The contract xxxx is missing links for the following libraries:
* contracts/libs/xxx.sol:xxx

There's no specific Hardhat error, but only TransactionExecutionError and lots of bytecodes which pollute terminal.It's necessary to add a catch of the specific error type in hardhat-viem plugin

**Comment by schaable** [comment]
Hi @Aliceonly, you are correct. Currently, hardhat-viem does not support library linking. I just created another [issue](https://github.com/NomicFoundation/hardhat/issues/4652) to implement it.
