### ISSUE TITLE
how to deploy to test net using hardhat-viem?

### ISSUE THREAD

**Issue by dataexcess** [NomicFoundation/hardhat#4639]
### Version of Hardhat

2.19.1

### What happened?

There is no hardhat-viem documentation on how to deploy a contract to main or test net. 

### Minimal reproduction steps

I need a walletClient to deploy to a live network right?
the examples only showq how a contract is deployed using the PublicClient. How can I do it?

```
    const [testAccount1, testAccount2] = await hre.viem.getWalletClients()

    const myToken = await testAccount1.deployContract('MyToken')
```

**Comment by schaable** [comment]
Hi @dataexcess. Regarding your question on deploying contracts to a testnet using `hardhat-viem`, the official documentation provides some guidance. As per the [hardhat-viem readme](https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-viem#contracts):

> By default, the first wallet client retrieved by hre.viem.getWalletClients() is used to deploy the contract. You can also specify a different wallet client by passing a third parameter, along with other properties, such as gas and value:

```
import hre from "hardhat";

const [_, secondWalletClient] = await hre.viem.getWalletClients();

const contractA = await hre.viem.deployContract(
  "contractName",
  ["arg1", 50, "arg3"],
  {
    walletClient: secondWalletClient,
    gas: 1000000,
    value: parseEther("0.0001"),
    confirmations: 5, // 1 by default
  }
);
```

In this snippet, `secondWalletClient` is used as the wallet for deploying the contract.


Feel free to reach out if you have any issues.

**Comment by dataexcess** [comment]
Yes! sorry. I missed the part where it said that the first account in the config file will be used to deploy it. My bad.
