### ISSUE TITLE
Add support for library linking in hardhat-viem

### ISSUE THREAD

**Issue by schaable** [NomicFoundation/hardhat#4652]
### Describe the feature

The current version of hardhat-viem doesn't support library linking in its `deployContract` and `sendDeploymentTransaction` methods. The API should mirror the approach taken by `hardhat-ethers` for library linking, as outlined [here](https://www.npmjs.com/package/@nomicfoundation/hardhat-ethers#library-linking). A proper error should be displayed if a contract is deployed with an unlinked library.

### Search terms

hardhat-viem viem linking library

**Comment by fvictorio** [comment]
@schaable should this be closed?

**Comment by schaable** [comment]
> @schaable should this be closed?

Yes, it slipped through, thanks for catching it!
