### ISSUE TITLE
issue with ethers when deploying a code 

### ISSUE THREAD

**Issue by BigGod12** [NomicFoundation/hardhat#4670]
hello please i need help with this error when deploying this code"const { ethers } = require("hardhat");

// Contract addresses and other values
const AVA_SEPOLIA_POOL_PROVIDER = "0x012bAC54348C0E635dCAc9D5FB99f06F24136C9A";
const USDC_ADDRESS = "0x94a9D9AC8a22534E3FaCa9F4e7F2E2cf85d5E4C8";
const USDC_DECIMALS = 6;
const FLASHLOAN_AMOUNT = ethers.utils.parseUnits("1000", USDC_DECIMALS);

// USDC tranfer function ABI
const USDC_ABI = ["function transfer(address to, uint256 value) external returns (bool)"];

async function main() {
  try {
    console.log("Deploying FlashLoan contract...");
    const FlashLoan = await ethers.getContractFactory("FlashLoan");
    const flashLoan = await FlashLoan.deploy(AVA_SEPOLIA_POOL_PROVIDER);
    await flashLoan.deployed();
    console.log(`FlashLoan contract deployed at: ${flashLoan.address}`);
    console.log(`View contract at: https://sepolia.etherscan.io/address/${flashLoan.address}`);
    console.log("---------------------------------------------------------------\n");

    // Transfer USDC to the FlashLoan contract
    const erc20 = new ethers.Contract(USDC_ADDRESS, USDC_ABI, ethers.provider.getSigner());
    const amount = ethers.utils.parseUnits("5", USDC_DECIMALS);

    console.log(`Transferring ${amount / 1e6} USDC to the FlashLoan contract...`);
    const transferErc20 = await erc20.transfer(flashLoan.address, amount);
    console.log(`Transferred ${amount / 1e6} USDC tokens to the FlashLoan contract`);

    console.log("Waiting for 1 block to verify the transfer...");
    await transferErc20.wait(1); // Wait 1 block for the transaction to be verified to update the balance
    console.log(`---------------------------------------------------------------\n`);

    // Check USDC balance of the FlashLoan contract
    const usdcBalance = await flashLoan.getBalance(USDC_ADDRESS);
    console.log(`USDC balance of the FlashLoan contract is: ${usdcBalance / 1e6} USDC`);
    console.log("---------------------------------------------------------------\n");

    // Call flash loan
    console.log(`Requesting a flash loan of ${FLASHLOAN_AMOUNT / 1e6} USDC...`);
    const flashloanTx = await flashLoan.requestFlashLoan(USDC_ADDRESS, FLASHLOAN_AMOUNT);
    console.log("Flash loan executed!");
    console.log(`View transaction at: https://sepolia.etherscan.io/tx/${flashloanTx.hash}`);
    await flashloanTx.wait(1); // Wait 1 block for the transaction to be verified to update the balance
    console.log("---------------------------------------------------------------\n");

    // Withdraw remaining USDC
    const remainingUSDC = await flashLoan.getBalance(USDC_ADDRESS);
    console.log(`Withdrawing ${remainingUSDC / 1e6} USDC from the FlashLoan contract...`);

    const withdrawFunds = await flashLoan.withdraw(USDC_ADDRESS);
    await withdrawFunds.wait(1); // Wait 1 block for the transaction to be verified
    console.log(`Funds sent!`)
    console.log(`View transaction at: https://sepolia.etherscan.io/tx/${withdrawFunds.hash}`);

  } catch (error) {

    console.error(error);
    process.exitCode = 1;
  }
}

main();

"

this error keep stopping the code from deploying "~/flash-loan-hardhat$ npx hardhat run --network sepolia scripts/deploy.js

/home/hack/flash-loan-hardhat/scripts/deploy.js:7
const FLASHLOAN_AMOUNT = ethers.utils.parseUnits("1000", USDC_DECIMALS);
                                      ^
TypeError: Cannot read properties of undefined (reading 'parseUnits')
    at Object.<anonymous> (/home/hack/flash-loan-hardhat/scripts/deploy.js:7:39)
    at Module._compile (node:internal/modules/cjs/loader:1198:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47"
i have ethers imported yet i can`t seems to go by the error message

**Comment by fvictorio** [comment]
`Cannot read properties of undefined` is a javascript error. You have some bug in your code. I can't help you with that; this issue tracker is just for bugs/feature requests specific to Hardhat.
