### ISSUE TITLE
Viem 'Quick-Start' Sample Code Documentation Has Bug

### ISSUE THREAD

**Issue by devrony** [NomicFoundation/hardhat#4713]
It appears the Viem quick start code sample at https://hardhat.org/hardhat-runner/docs/advanced/using-viem#quick-start has a bug where it does not assign the "hash" const after calling token function.

This is the orginal code sample in the contracts.ts file which has issue:
await myToken.write.increaseSupply([500_000n]); 

The following code fails to compile because there is no variable defined for "hash"
await publicClient.waitForTransactionReceipt({ hash });

After changing the code to assign the hash value, the code compiles and runs correctly.
const hash = await myToken.write.increaseSupply([500_000n]);

**Comment by schaable** [comment]
hi @devrony, you're 100% correct. Thanks for letting us know. I'll push a fix later today.

**Comment by schaable** [comment]
Fixed in https://github.com/NomicFoundation/hardhat/pull/4717
