### ISSUE TITLE
Don't use latest version of chai in docs/sample projects

### ISSUE THREAD

**Issue by fvictorio** [NomicFoundation/hardhat#4733]
See comment [here](https://github.com/NomicFoundation/hardhat/issues/3385#issuecomment-1873317440).

We should use `chai@4` in every snippet in the docs that shows how to install chai, and make sure that the sample projects don't use the latest version (I'm pretty sure they don't but just in case).

**Comment by lilpolymath** [comment]
@fvictorio i would like to work on this.

**Comment by lilpolymath** [comment]
@fvictorio you can close this.
