### ISSUE TITLE
Hardhat contract safeTrasferFrom with ERC1155 in testing not working 

### ISSUE THREAD

**Issue by ojoaoguilherme** [NomicFoundation/hardhat#4735]
### Version of Hardhat

2.19.4

### What happened?

I created a very simple contract named Marketplace which has 2 function with its main purpose is to receive ERC721 and ERC1155

- deposit
- handleNftTransfer

![Marketplace](https://github.com/NomicFoundation/hardhat/assets/57265920/fc0e5c94-66d9-4478-8da8-b8b33c031ef7)

Deposit should simply receive the parameter for handleNftTransfer which should identify the Token ERC and effectively transfer from `from` to `to`.

Handle NFT Transfer with Remix IDE worked fine

![image](https://github.com/NomicFoundation/hardhat/assets/57265920/3b1b0325-45e7-4868-9fc9-ff1afe75d8ec)

 Testing with Hardhat is throwing the following type error
**TypeError: invalid BigNumberish value (argument="value", value={ "blockTag": 6 }, code=INVALID_ARGUMENT, version=6.4.0)**

![image](https://github.com/NomicFoundation/hardhat/assets/57265920/6872942c-8811-4221-b7ea-9e6592299659)

I am testing the code as follows

![testing](https://github.com/NomicFoundation/hardhat/assets/57265920/32d79384-1d54-437c-b08a-2a12ace231c2)

I expected the test to pass

### Minimal reproduction steps

Clone the project
git clone git@github.com:ojoaoguilherme/hardhat-test.git hardhat-test

Enter folder
cd hardhat-test

Install dependencies
yarn

Run testing script
npx hardhat test

### Search terms

TypeError: invalid BigNumberish value (argument="value", value={ "blockTag": 6 }, code=INVALID_ARGUMENT, version=6.4.0)

**Comment by fvictorio** [comment]
Hey @ojoaoguilherme, sorry for not responding sooner!

The problem here is that `changeTokenBalance[s]` only works for ERC20 tokens. ERC1155 tokens have a different `balanceOf` function, which needs to also receive the `id`. You are getting that error because the block tag is being passed as the second argument to that ethers function, and it's being interpreted as a number (the `id`).
