### ISSUE TITLE
Mainnet Fork not working before block 18856000

### ISSUE THREAD

**Issue by snowkidind** [NomicFoundation/hardhat#4737]
### Version of Hardhat

2.19.4

### What happened?

`% npx hardhat run --network hardhat scripts/deploy.js`

Error: A withdrawalsRoot for a header can only be provided with EIP4895 being activated
    at new BlockHeader ...

This strange behavior occurs when I try to access a block before 18856000
The node I am connecting to is an erigon archival node
In the script i initialize hardhat ethers as so

```
const hre = require("hardhat");
const ethers = hre.ethers
const provider = ethers.provider
```
and in my async function I call getBlock:
`const block = await provider.getBlock(18856000) // does not crash`
`const block = await provider.getBlock(18855999) // crashes with above error`

In my config file:

```
// 18689178 - cannot use block:  "A withdrawalsRoot for a header can only be provided with EIP4895 being activated"
// this was activated more than a year ago
// bug is at 18855999 (no work) 18856000 (work)

const lastBlock = 18856000

module.exports = {
  networks: {
    hardhat: {
      accounts: { mnemonic: process.env.MNEMONIC },
      forking: {
        url: 'http://192.168.1.104:8545',
        blockNumber: lastBlock
      }
    }, 

etc...

```

Expected behavior:

Hardhat mainnet forking should work at any block height

### Minimal reproduction steps

// hardhat.config.js
```
require("@nomicfoundation/hardhat-toolbox");

// note incrementing this to 18856000 resolves the error, yet any earlier block being accessed is then null
const lastBlock = 18855999 

module.exports = {
  solidity: {
    compilers: [
      {
        version: "0.8.20",
        settings: {
          optimizer: {
            enabled: true,
            runs: 200,
          },
        },
      }
    ]
  },
  networks: {
    hardhat: {
      forking: {
        url: 'http://192.168.1.104:8545',
        blockNumber: lastBlock
      }
    }
  }
};

```

script.js

```
const hre = require("hardhat");
const ethers = hre.ethers
const provider = ethers.provider

const run = async () => {
  const block = await provider.getBlock(18855999)
  console.log(block)
}

  ; (async () => {
    try {
      await run()
    } catch (error) {
      console.log(error)
      process.exit(1)
    }
    process.exit(0)
  })()
```

// terminal
npm init -y
npm install  @nomicfoundation/hardhat-toolbox
npx hardhat run --network hardhat script.js

// other info
Mac os Ventura 13.3.1
Node v20.10.0

 

### Search terms

Mainnet fork

**Comment by fvictorio** [comment]
Hey @snowkidind, I cannot reproduce this using an Infura archive node. Can you check if you can reproduce with one too?

If not, then this must be something specific about forking from an Erigon node.

**Comment by schaable** [comment]
Closing due to lack of response. Happy to reopen if more information is provided.
