### ISSUE TITLE
Add support for viem@2

### ISSUE THREAD

**Issue by travs** [NomicFoundation/hardhat#4749]
Viem version 2 just dropped, and would be nice to have support for it in hardhat.

I think a simple version bump won't cut it, given [this issue](https://github.com/wevm/viem/discussions/1494) I experienced installing `viem@2` with `--legacy-peer-deps`.

**Comment by kanej** [comment]
We have shipped `@nomicfoundation/hardhat-viem` version `2.0.0` with `viem@2` support.
We are working through updating the viem toolbox with these updates as well.
