### ISSUE TITLE
Why is contract deployment taking high gas costs when deploying contracts with the help of NodeJS child process ?

### ISSUE THREAD

**Issue by iamgauravpant** [NomicFoundation/hardhat#4779]
### Version of Hardhat

2.19.1

### What happened?

I tried to deploy ERC721 NFT contracts using NodeJS child process and hardhat ( I am creating a NodeJS API to deploy nft contracts for my application ) . For this , I rewrite hardhat.config.js file ( network name , network url , account_private_key ) and deploy.js file ( name and symbol of the token contracts ) . When I deploy contracts using this way , I am getting very high transaction costs ( ~0.3-0.5 ETH per deployment ) . Why is this happening ?
Take these 2 transactions for example : https://sepolia.etherscan.io/tx/0x755dba9b4ba905622c756dd30deb4c994cd5be18a92342189d5c797152801c15
https://sepolia.etherscan.io/tx/0xea5dfe3efe86a41b64a05a4481d63b3f07ee998f7d4441ae53512178a957decb
```
// deploy contract on polygon mumbai

const { spawn } = require("child_process"); // inbuilt

const executeChildProcess = (command, args, options) => {
    return new Promise((resolve, reject) => {
      try {
        const child = spawn(command, args, options);
  
        let dataBuffer = '';
        let errorBuffer = '';
  
        child.stdout.on('data', (data) => {
          dataBuffer += data.toString();
        });
  
        child.stderr.on('data', (data) => {
          errorBuffer += data.toString();
        });
  
        child.on('close', (code) => {
          if (code === 0) {
            resolve(dataBuffer);
          } else {
            reject(new Error(errorBuffer));
          }
        });
      } catch (error) {
        reject(error);
      }
    });
};
  
// this config object gets added to hardhat.config.js file each time I call the api with parameters like network name , network url and account private key 
const hardhatConfig = `
  networks: {
    PolygonMumbai: {
      url: "https://polygon-mumbai.infura.io/v3/infurakey",
      accounts:["account_private_key"]
    }
  }`;

// this is the deploy.js file that is used to deploy contract , it takes file_name , contract_name , contract_symbol as parameters
const scripts = `
  const hre = require("hardhat");
  async function main(file_name, smart_contract_name, smart_contract_symbol) {
  const contract = await hre.ethers.deployContract(file_name, [smart_contract_name,smart_contract_symbol]);
  await contract.waitForDeployment();
  console.log(contract.target);
  return contract.target;
  }
          
  main("CoolNFT","CNFT","CNFT721")
  .then(() => process.exit(0))
  .catch(error => {
  console.error(error);
  process.exit(1);
  });
  `;
const cwd_path = "/home/gauravpant31/721";

const childResponsePromise = executeChildProcess(
    'sh',
    ['./deploy.sh', `'${scripts}'`, `'PolygonMumbai'`,`'${hardhatConfig}'`],
    {
      shell: true,
      cwd: cwd_path,
    }
);

childResponsePromise
.then((childResponse) => {
  console.log("child process :",childResponse);
}).catch(err =>{
  console.log("err :",err);
})
```

Below is the deploy.sh file code that is present besides the hardhat code , this contains instructions to write to deploy.js file and hardhat.config.js file and to deploy the desired contract using npx hardhat run command 

```
echo "require(\"@nomicfoundation/hardhat-toolbox\");" > ./hardhat.config.js
echo "/** @type import('hardhat/config').HardhatUserConfig */" >> ./hardhat.config.js
echo "module.exports = {" >> ./hardhat.config.js
echo "  solidity: {" >> ./hardhat.config.js
echo "    version: \"0.8.11\"" >> ./hardhat.config.js
echo "  }," >> ./hardhat.config.js
echo "$3" >> ./hardhat.config.js  # Append the content from echo "$3"
echo "};" >> ./hardhat.config.js

# Continue with the rest of your script
echo "$1" > ./scripts/deploy.js
npx hardhat run ./scripts/deploy.js --network "$2"
```

### Minimal reproduction steps

Create a hardhat boilerplate code .
Create a ERC-721 NFT contract that takes name and symbol in constructor parameters .
copy paste the deploy.sh file code and paste it at the root level in hardhat boilerplate code . 
create a new js file ( main.js ) , copy paste the child process code and run it .

### Search terms

hardhat , child process

**Comment by fvictorio** [comment]
The transaction you linked has a gas price of 69.3 gwei, which is high but not uncommon. Your transaction also has a gas limit of 4 million, which is also high but makes sense because you seem to be deploying a big contract.

High gas limit + high gas price: high transaction cost. There's nothing unexpected going on here, and the fact that you are using a child process is almost surely completely unrelated.
