### ISSUE TITLE
Error 404 Hardhat.org Errors Docs

### ISSUE THREAD

**Issue by Winter9998** [NomicFoundation/hardhat#4798]
### Version of Hardhat

.

### What happened?

https://hardhat.org/hardhat-runner/docs/errors just throws out an error 404 when on site

### Minimal reproduction steps

go to : [hardhat.org](https://hardhat.org/hardhat-runner/docs/errors)

### Search terms

hardhat errors, docs

**Comment by Winter9998** [comment]
here is proof :
![Uploading Screenshot 2024-01-29 081758.png…]()

**Comment by Winter9998** [comment]
![Screenshot 2024-01-29 081758](https://github.com/NomicFoundation/hardhat/assets/112932882/1ef2fd37-732b-4261-bfe2-08ff5e6cd7da)

**Comment by fvictorio** [comment]
Thanks!
