### ISSUE TITLE
Error HH415 when running hardhat compile

### ISSUE THREAD

**Issue by zain4838** [NomicFoundation/hardhat#4828]
### Version of Hardhat

2.19.5

### What happened?

I'm using openzeppelin/contracts and openzeppelin/contracts-upgradeable together,
when I run `npx hardhat compile` I get this error:

`Error HH415: Two different source names ('@openzeppelin/contracts/utils/Strings.sol' and 'node_modules/@openzeppelin/contracts/utils/Strings.sol') resolve to the same file (/Users/dev/Desktop/hardhat/node_modules/@openzeppelin/contracts/utils/Strings.sol).`

### Minimal reproduction steps

npx hardhat compile

**Comment by fvictorio** [comment]
@zain4838 you'll have to share your code for us to be able to help.

**Comment by schaable** [comment]
Closing for lack of response. Feel free to reopen if you can provide more info.
