### ISSUE TITLE
Verify Smart Contract in custom explorer which apis are restricted with http basic authentication and api key header

### ISSUE THREAD

**Issue by sugalivijaychari** [NomicFoundation/hardhat#4863]
### Describe the feature

npx hardhat verify should be able to pass custom attributes exclusively for etherscan/custom explorer verification APIs.
Blockchain: Private and permissioned (Hyperledger besu client)
Explorer: Customized blockscout explorer.
This explorer is restricted to public access i.e., all explorer APIs especially below API restricted with http basic authentication and api key in header validation.

API:
https://instance_base_url/api
   ?module=contract
   &action=verify
   &addressHash={addressHash}
   &name={name}
   &compilerVersion={compilerVersion}
   &optimization={false}
   &contractSourceCode={contractSourceCode}
   
When we use Curl, we use below command to verify a contract:
curl -d '{"addressHash":"0xc63BB6555C90846afACaC08A0F0Aa5caFCB382a1","compilerVersion":"v0.5.4+commit.9549d8ff", "contractSourceCode":"pragma solidity ^0.5.4; contract Test { }","name":"Test","optimization":false}' -H "Content-Type: application/json" -X POST "https://blockscout.com/poa/sokol/api?module=contract&action=verify"

Since we restricted our own customized blockscout explorer, the curl command should be:
curl -d '{"addressHash":"0xc63BB6555C90846afACaC08A0F0Aa5caFCB382a1","compilerVersion":"v0.5.4+commit.9549d8ff", "contractSourceCode":"pragma solidity ^0.5.4; contract Test { }","name":"Test","optimization":false}' -H "Content-Type: application/json" -X POST "https://blockscout.com/poa/sokol/api?module=contract&action=verify&apikey=xxxxxxx-1695-454e-a369-4501253a120" -u user:pass -H "X-API-Key: my_api_secret_key_here"

Implement a feature in hardhat to add user and pass and my_api_secret_key satisfying above curl.
Implement this mechanism either by adding flags/options in the npx hardhat verify command or by configuring these in hardhat config file.

### Search terms

verify contract in custom explorer which apis are restricted with basic auth and api key header validation

**Comment by ChristopherDedominici** [comment]
Hi @sugalivijaychari, thank you for reporting this. We already have a work item to implement this feature, you can find it here: https://github.com/NomicFoundation/hardhat/issues/3536.
I'm going to close this one as a duplicate. Please follow the linked issue to track the progress. Thanks
