### ISSUE TITLE
Transaction reverted and Hardhat couldn't infer the reason. - Static call to non-static function

### ISSUE THREAD

**Issue by raffle-x-dev** [NomicFoundation/hardhat#4866]
### Version of Hardhat

2.20.0

### What happened?

Trying to execute a contract static call to same contract non-static function from JS app, Hardhat got me the error:

`     ProviderError: Error: Transaction reverted and Hardhat couldn't infer the reason.`

### Minimal reproduction steps

Contract code:

    uint8 public foo = 4;
    
    function perma() public view returns (uint8) {
        return foo;
    }

    function myStatic() public returns (uint8) {       
        (bool success, bytes memory encodedResult) = address(this).staticcall(abi.encodeWithSignature('perma'));
        uint8 staticFoo = abi.decode(encodedResult, (uint8));
        return staticFoo;
    }

JS app FAILING attempts, calling the contract staticCall:

`await contract.myStatic()
`
`await contract.myStatic.staticCall()
`

Succeding attempt, directly calling the non-static function (but this way I can't test if my contract static call works):

`await contract.perma.staticCall()
`

### Search terms

staticCall, non-static, static call, encodeWithSignature, staticcall, contract, Transaction reverted and Hardhat couldn't infer the reason,

**Comment by schaable** [comment]
Hey @raffle-x-dev, there's an error on the first line of the myStatic function. It should be:
```solidity
(bool success, bytes memory encodedResult) = address(this).staticcall(
    abi.encodeWithSignature("perma()")
);
```
With that change, it will work.
