### ISSUE TITLE
Clarify in the documentation that hardhat-chai-matchers is not compatible with hardhat-viem

### ISSUE THREAD

**Issue by schaable** [NomicFoundation/hardhat#4871]
Currently, our `hardhat-chai-matchers` plugin is designed to work with `hardhat-ethers`. Attempting to use it in conjunction with `hardhat-viem` results in compatibility issues. To prevent confusion, we need to explicitly state this limitation in the documentation: [hardhat-chai-matchers Overview](https://hardhat.org/hardhat-chai-matchers/docs/overview).

**Comment by anthonygood** [comment]
This bit me.
