### ISSUE TITLE
Documentation : Deploying to a live network has a huge Security issue

### ISSUE THREAD

**Issue by SvenMeyer** [NomicFoundation/hardhat#4879]
### Version of Hardhat

docs (Last Updated: 12 Feb 2024, 21:35:29)

### What happened?

Reading deployment docs

https://hardhat.org/tutorial/deploying-to-a-live-network

Is is a REALLY BAD idea to have a code example with the private key in plain text in the source !
Somebody pushes his code to github and then its GAME OVER !

I did that last year accidentally just with a Goerli testnet deployment, and even then all my Goerli ETH were gone soon after ... and I had to chase new ones. 

### Minimal reproduction steps

- Push your deployment code (which includes your private key) to github
- Watch your funds disappear ! 

### Search terms

security, private key, deployment

**Comment by SvenMeyer** [comment]
I ended up on the hardhat deployment docs page when I was looking for what I think I had seen a while ago : using a deployment script , but instead of providing the private key "somehow" Metamask would pop-up and I would securely sign the deployment tx with MM. Anybody seen this ?

**Comment by SvenMeyer** [comment]
Found it ! THIS !
https://github.com/deusfinance/Hardhat-metamask-client

**Comment by kanej** [comment]
We will update the **deploying to a live network** to use [configuration variables](https://hardhat.org/hardhat-runner/docs/guides/configuration-variables) in the next few days (a large docs PR is in review that includes these changes).

**Comment by kanej** [comment]
The use of configuration variables in the example has now been rolled out: https://hardhat.org/tutorial/deploying-to-a-live-network#deploying-to-remote-networks
