### ISSUE TITLE
Trouble with forking Calibration network(filecoin testnet) in hardhat test environment.

### ISSUE THREAD

**Issue by parva-jain** [NomicFoundation/hardhat#4892]
I am deploying contracts on filecoin and for testing locally, I'm trying to fork calibration network by adding the following config:

```
forking: {
        url: CALIBRATION_RPC_URL,
        blockNumber: 1369000
},
```
      
But when I run the tests, I get the following error: 

```
An unexpected error occurred:

InvalidResponseError: Invalid JSON-RPC response's result.

Errors: Invalid value undefined supplied to : RpcBlockWithTransactions | null/transactions: RpcTransaction Array/0: RpcTransaction/gasPrice: QUANTITY, Invalid value undefined supplied to : RpcBlockWithTransactions | null/transactions: RpcTransaction Array/1: RpcTransaction/gasPrice: QUANTITY
```

Any help is really appreciated!

**Comment by kanej** [comment]
Hey, Hardhat forking likely won't work against a Filecoin network.

Hardhat is designed to allow development against Ethereum networks, a large part of which is running Solidity in an EVM execution environment - but not all.

You can leverage Hardhat in the Filecoin context for running Solidity code against a development EVM execution environment; but forking implies far more than just mirroring the EVM execution, it gets into replicating the internal details of the network node. I suspect that Filecoin network nodes and Ethereum network nodes are just too different to allow for leveraging of forking.

**Comment by parva-jain** [comment]
The interesting thing is that till few weeks before, the tests were running in the filecoin fork as well(sometimes it was failing with same reason). But now from last 2 weeks, its falling everytime. Let me know if there's any hack around it or how should I test functionalities specific to filecoin??

**Comment by kanej** [comment]
@parva-jain that sounds like something changed about the Filecoin network (rather than Hardhat). We don't have experience with Filecoin, is there any experience or suggestions in the Filecoin community with forking tests?
