### ISSUE TITLE
hardhat-verify is not working with the error of "Compiled contract deployment bytecode does NOT match the transaction deployment bytecode"

### ISSUE THREAD

**Issue by iris112** [NomicFoundation/hardhat#4918]
### Version of Hardhat

2.17.3

### What happened?

I'm using the `hardhat-verify@2.0.4` to verify the deployed contract on the etherscan.
In the past, I can successfully verify every deployed contracts but now I can't verify and I'm getting error.

> Reason: Fail - Unable to verify. Compiled contract deployment bytecode does NOT match the transaction deployment bytecode.

### Minimal reproduction steps

After deploy the contract on the ethereum mainnet using the `hardhat-deploy`, I tried run the following command to verify the contract.
`npx hardhat verify CONTRACT_ADDRESS`

But I'm getting the following error.

```
[INFO] Sourcify Verification Skipped: Sourcify verification is currently disabled. To enable it, add the following entry to your Hardhat configuration:

sourcify: {
  enabled: true
}

Or set 'enabled' to false to hide this message.

For more information, visit https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-verify#verifying-on-sourcify
Successfully submitted source code for contract
contracts/src/leverages/SturdyLeverage.sol:SturdyLeverage at 0xC7a65E66CcBA7499B3CED993195f3670dead97dd
for verification on the block explorer. Waiting for verification result...

hardhat-verify found one or more errors during the verification process:

Etherscan:
An unexpected error occurred during the verification process.
Please report this issue to the Hardhat team.
Error Details: An unexpected error occurred during the verification process.
Please report this issue to the Hardhat team.
Error Details: An unexpected error occurred during the verification process.
Please report this issue to the Hardhat team.
Error Details: An unexpected error occurred during the verification process.
Please report this issue to the Hardhat team.
Error Details: The Etherscan API responded with a failure status.
The verification may still succeed but should be checked manually.
Reason: Fail - Unable to verify. Compiled contract deployment bytecode does NOT match the transaction deployment bytecode.
```

**Comment by kanej** [comment]
Is this repo open source? Can you point us at it, or share the code of the sturdy leverage contract?

**Comment by kanej** [comment]
The bytecode generated subtly changes between tools. If you deployed through HH deploy you should try verifying through [Hardhat deploys verification command](https://github.com/wighawag/hardhat-deploy?tab=readme-ov-file#4-hardhat-etherscan-verify).

**Comment by iris112** [comment]
when we can use the `hardhat-verify`?

**Comment by iris112** [comment]
> The bytecode generated subtly changes between tools. If you deployed through HH deploy you should try verifying through [Hardhat deploys verification command](https://github.com/wighawag/hardhat-deploy?tab=readme-ov-file#4-hardhat-etherscan-verify).

I tried using this tool as well, now I'm getting the following error.

```
verifying SturdyLeverage (0xC7a65E66CcBA7499B3CED993195f3670dead97dd) ...
waiting for result...
Failed to verify contract SturdyLeverage: NOTOK, Fail - Unable to verify. Solidity Compilation Error: Library entry is not a JSON object.
{
  "apikey": "XXXXXX",
  "module": "contract",
  "action": "verifysourcecode",
  "contractaddress": "0xC7a65E66CcBA7499B3CED993195f3670dead97dd",
  "sourceCode": "...",
  "codeformat": "solidity-standard-json-input",
  "contractname": "contracts/src/leverages/SturdyLeverage.sol:SturdyLeverage",
  "compilerversion": "v0.8.21+commit.d9974bed",
  "licenseType": 13
}
Falling back on solcInput. etherscan seems to sometime require full solc-input with all source files, even though this should not be needed. See https://github.com/ethereum/solidity/issues/9573
verifying SturdyLeverage (0xC7a65E66CcBA7499B3CED993195f3670dead97dd) ...
waiting for result...
Failed to verify contract SturdyLeverage: NOTOK, Fail - Unable to verify. Please check for missing Library or invalid name (i.e names are case senstive). Library was required but suitable match not found
{
  "apikey": "XXXXXX",
  "module": "contract",
  "action": "verifysourcecode",
  "contractaddress": "0xC7a65E66CcBA7499B3CED993195f3670dead97dd",
  "sourceCode": "...",
  "codeformat": "solidity-standard-json-input",
  "contractname": "contracts/src/leverages/SturdyLeverage.sol:SturdyLeverage",
  "compilerversion": "v0.8.21+commit.d9974bed",
  "licenseType": 13
}
```

**Comment by kanej** [comment]
I am unsure, the complaint is that the libraries object that is being passed in your json input is invalid, it is missing paths. But I have limited knowledge of `hardhat-deploy`.

I would try on the [#hardhat-deploy discord channel](https://discord.com/channels/750408878008827925/1126579852624011284), and see if the community has any suggestions.

**Comment by iris112** [comment]
I tried using the following command.
`npx hardhat --network main etherscan-verify --contract-name SturdyLeverage --solc-input --write-post-data`
And got the above same error.
But I can get the post-data in etherscan_requests/main/SturdyLeverage.json
[SturdyLeverage.json](https://github.com/NomicFoundation/hardhat/files/14406818/SturdyLeverage.json)
Looks like, in the json file, there is no problem for the libraries.

**Comment by schaable** [comment]
> I tried using the following command.
> npx hardhat --network main etherscan-verify --contract-name SturdyLeverage --solc-input --write-post-data
> And got the above same error.

hi @iris112, that command is part of `hardhat-deploy`, which is a community plugin. If you need more help, I suggest you to ask on the [#hardhat-deploy discord channel](https://discord.com/channels/750408878008827925/1126579852624011284) or to [submit an issue on their repo](https://github.com/wighawag/hardhat-deploy/issues).
