### ISSUE TITLE
Can you set pauses in test script?

### ISSUE THREAD

**Issue by raffle-x-dev** [NomicFoundation/hardhat#4931]
I have a very long testing procedure and would be great if I could pause at the end if every test function, then move on with next one by striking a key, so to be able to see the effects of what happens in the test on the live front-end, as well as reading console output.
This would be great also for demo-ing the product.
Ideas?

**Comment by kanej** [comment]
In this sort of case I would be tempted to use a `script` instead: https://hardhat.org/hardhat-runner/docs/advanced/scripts

You can leverage the same code as you would use in your long test procedure but also include node readline to get user input (and pause the script while you wait for it): https://nodejs.org/en/learn/command-line/accept-input-from-the-command-line-in-nodejs

**Comment by kanej** [comment]
I am closing this as answered.
