### ISSUE TITLE
hardhat chai matchers: `emit(...).withArgs` does not properly work with BigInt `closeTo` in the callback

### ISSUE THREAD

**Issue by WardenJakx** [NomicFoundation/hardhat#4934]
### Version of Hardhat

2.20.1

### What happened?

I am upgrading my codebase from using ethers v5 and hardhat-toolbox v2 to ethers v6 and hardhat toolbox v4. I have most of the codebase updated, but there is a recurring error with event based tests that keep failing unless I remove the `withArgs` part of the chain

Ive tried different versions of the packages responsible for this upgrade but still run into issues. Ive run hardhat clean, deleted node_modules, but still run into the issue

When doing `tx.to.emit(...).withArgs(
...
(value:bigint) => expect(value).to.be.closeTo(value, delta)
)`, the withArgs will not work if with  the closeTo callback (even though it should pass)

eg:

```
tx.to.emit(...).withArgs(
 signerAddress,
 (amount:bigint) => expect(amount).to.be.closeTo(parseEther("1"), parseUnits("1", "gwei"))
)
```

Reverts with
```
 AssertionError: Error in "Swap" event: Error in the 2nd argument assertion: The predicate did not return true
 ```
 
 However, the amount parameter is exactly 1 ETH so this should be passing as true.
 
 If i do
 ```
tx.to.emit(...).withArgs(
 signerAddress,
 parseEther("1")
)

```

it passes successfully

Is this possibly related to https://github.com/chaijs/chai/pull/1606 ?

### Minimal reproduction steps

tx.to.emit(...).withArgs(
...
 (amount:bigint) => expect(amount).to.be.closeTo(parseEther("1"), parseUnits("1", "gwei"))
)

### Search terms

hardhat-chai-matchers, assertions, closeTo

**Comment by WardenJakx** [comment]
@ChristopherDedominici bump on this

**Comment by ChristopherDedominici** [comment]
Hi @WardenJakx. I just took a look at the code. 
Currently the function that you're using is this one:
```
(amount:bigint) => expect(amount).to.be.closeTo(parseEther("1"), parseUnits("1", "gwei"))
```

The function is not returning a boolean value, [see the docs here](https://hardhat.org/hardhat-chai-matchers/docs/reference#.withargs:~:text=function%20isEven(x%3A%20bigint)%3A%20boolean%20%7B%0A%20%20return%20x%20%25%202n%20%3D%3D%3D%200n%3B%0A%7D%0A%0Aawait%20expect(token.transfer(100)).to.emit(token%2C%20%22Transfer%22).withArgs(isEven)%3B) 

If you modify the function to return true, it should work. In case the `expect` check fails, an error will be thrown:
```
(amount: bigint) => {
    expect(amount).to.be.closeTo(
        parseEther("1"),
        parseUnits("1", "gwei")
    );
    return true;
}         
```

**Comment by WardenJakx** [comment]
> Hi @WardenJakx. I just took a look at the code. Currently the function that you're using is this one:
> 
> ```
> (amount:bigint) => expect(amount).to.be.closeTo(parseEther("1"), parseUnits("1", "gwei"))
> ```
> 
> The function is not returning a boolean value, [see the docs here](https://hardhat.org/hardhat-chai-matchers/docs/reference#.withargs:~:text=function%20isEven(x%3A%20bigint)%3A%20boolean%20%7B%0A%20%20return%20x%20%25%202n%20%3D%3D%3D%200n%3B%0A%7D%0A%0Aawait%20expect(token.transfer(100)).to.emit(token%2C%20%22Transfer%22).withArgs(isEven)%3B)
> 
> If you modify the function to return true, it should work. In case the `expect` check fails, an error will be thrown:
> 
> ```
> (amount: bigint) => {
>     expect(amount).to.be.closeTo(
>         parseEther("1"),
>         parseUnits("1", "gwei")
>     );
>     return true;
> }         
> ```

Hi, thanks for the response. This code block worked with previous versions of hardhat and ethers. Also, any callback for events will fail even if it just returns true so unfortunately your proposed fix does not solve the problem

Example:


```
await expect(tx)
          .to.emit(this.multiUserStrategy, "Mint")
          .withArgs(async (data: IMultiUserLLSDStrategy.MintEventDataStruct) => {
            return true;
          }),
``` 

will still fail

**Comment by WardenJakx** [comment]
Hi @ChristopherDedominici, thanks for the suggestion. I tried it on my codebase and it worked properly. 

It seems like there was an unwritten change as before i could pass cases where (num => expect(...)) was all the logic there was in the callback

However, with *some* change, this is no longer possible unless you do num => { expect(...); return true; }

Not sure if this is a change with the hardhat library or chai library but if it is hardhat related it should be documented somewhere to help others facing this migration issue
