### ISSUE TITLE
Forking config seems not working

### ISSUE THREAD

**Issue by VetchM** [NomicFoundation/hardhat#4942]
### Version of Hardhat

2.20.1

### What happened?

I am using this config to start a local hardhat node:

```js
module.exports = {
    defaultNetwork: "hardhat",
    networks: {
        hardhat: {
            chainId: 1,
            loggingEnabled: true,
            forking: {
                url: "https://eth-mainnet.g.alchemy.com/v2/<api_key>",
            }
        },
    },
};
```
This file is working because the chainId of my local node is changed, but i keep getting this error when I ran my test:

```sh
eth_maxPriorityFeePerGas - Method not supported
```
Using `npx hardhat node --forking https://eth-mainnet.g.alchemy.com/v2/<api_key>` has the same behavior.
If I request the "eth_maxPriorityFeePerGas" RPC using the alchemy url, I can get the correct result. Any idea what went wrong?

The node version is v20.11.1, the OS is Windows 10.

### Minimal reproduction steps

Put this config at the root directory:

```js
module.exports = {
    defaultNetwork: "hardhat",
    networks: {
        hardhat: {
            chainId: 1,
            loggingEnabled: true,
            forking: {
                url: "https://eth-mainnet.g.alchemy.com/v2/<api_key>",
            }
        },
    },
};
```

Run `npx hardhat node` to start a node then run this:

```sh
curl --location 'http://127.0.0.01:8545' \
--header 'Content-Type: application/json' \
--data '{
    "jsonrpc": "2.0",
    "method": "eth_maxPriorityFeePerGas",
    "params": [],
    "id": 83
}'
```

The response is: 

```json
{
    "jsonrpc": "2.0",
    "id": 83,
    "error": {
        "code": -32601,
        "message": "Method eth_maxPriorityFeePerGas not found",
        "data": {
            "message": "Method eth_maxPriorityFeePerGas not found"
        }
    }
}
```

### Search terms

Hardnet Forking eth_maxPriorityFeePerGas

**Comment by VetchM** [comment]
Do I need to provide any extar info to help you spot the problem?

**Comment by hawkj** [comment]
i have the same problem

**Comment by phpmac** [comment]
https://github.com/NomicFoundation/hardhat/issues/5187#issuecomment-2108796843

**Comment by kanej** [comment]
I am closing this issue in preference to #4365
