### ISSUE TITLE
An etherscan endpoint could not be found for this network. ChainID: 11155111. The selected network is sepolia.

### ISSUE THREAD

**Issue by fazil1979** [NomicFoundation/hardhat#4966]
### Version of Hardhat

2.0.4

### What happened?

When I try to execute the verify command, always I get error like below: 

Error in plugin @nomiclabs/hardhat-etherscan: An etherscan endpoint could not be found for this network. ChainID: 11155111. The selected network is sepolia.
 
Possible causes are:
  - The selected network (sepolia) is wrong.
  - Faulty hardhat network config.

I have checked the config file and it seems proper so not getting any clue were is the mistake. If anyone can help. 

### Minimal reproduction steps

just try to hit verify command with sepolia network

**Comment by fazil1979** [comment]
![ethurscan](https://github.com/NomicFoundation/hardhat/assets/2875281/b3e0141a-26a1-44a1-aa83-ef494b708fce)

**Comment by fazil1979** [comment]
Above is my config file

**Comment by schaable** [comment]
Hi @fazil1979, `@nomiclabs/hardhat-etherscan` has been deprecated in favor of `@nomicfoundation/hardhat-verify` and it's not longer maintained. The interface for the new plugin is the same as the old one, so you should be able to replace it without issues. You can find more documentation [here](https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-verify). 

Also, you should consider updating hardhat, as the current version is v2.21.0 and you might be missing important updates.

Closing but feel free to reopen if you find any issues after the migration.
