### ISSUE TITLE
Switch the default hardfork to cancun

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat#4976]
Support for `cancun` is already in HH. The default value should be updated in line with the expected date of the hardfork: March 13th 2024.

**Comment by fvictorio** [comment]
Duplicate of https://github.com/NomicFoundation/hardhat/issues/4851 :stuck_out_tongue:

**Comment by kanej** [comment]
Closing in favour of #4851 as someone beat be to it.
