### ISSUE TITLE
Versioning problems.

### ISSUE THREAD

**Issue by Anas-debug** [NomicFoundation/hardhat#4983]
### Version of Hardhat

2.21.0

### What happened?

When I run npx hardhat node this error pops up:
```
anas@DESKTOP-K6N5LEP:/mnt/$ npx hardhat -
-version
WARNING: You are currently using Node.js v21.6.2, which is not supported by Hardhat. This can lead to unexpected behavior. See https://hardhat.org/nodejs-versions
```
Node.js v21.6.2 is an LTS , the documentation doesn't help much.

### Minimal reproduction steps

run ```$npx harhat node`

### Search terms

Versioning probelm

**Comment by kanej** [comment]
This is a bug, we will get the node version support warning removed for node 21.

**Comment by fvictorio** [comment]
Node v21 is not an LTS. Check [here](https://nodejs.org/en/about/previous-releases):

> After six months, odd-numbered releases (9, 11, etc.) become unsupported, and even-numbered releases (10, 12, etc.) move to Active LTS status and are ready for general use.
