### ISSUE TITLE
Run a script using the hardhat network, makes the script to never end if the provider and some promise was used from =>v2.21.0

### ISSUE THREAD

**Issue by invocamanman** [NomicFoundation/hardhat#4997]
### Version of Hardhat

It happens from v2.21.0

### What happened?

Once i run the following script:
```
import {ethers} from "hardhat";

async function main() {
    // Load provider
    const provider = ethers.provider;
    await provider.getBalance(ethers.ZeroAddress);
}

main().catch((e) => {
    console.error(e);
    process.exit(1);
});
```
Using `npx hardhat run script.ts` and having the default network on hardhat.

### Minimal reproduction steps

Open a harhdat repository with  v2.21.0 or higher

- Cerate a script.ts: 
```
import {ethers} from "hardhat";

async function main() {
    // Load provider
    const provider = ethers.provider;
    await provider.getBalance(ethers.ZeroAddress);
}

main().catch((e) => {
    console.error(e);
    process.exit(1);
});
```
- execute it using: `npx hardhat run script.ts`

**Comment by invocamanman** [comment]
Added info: it happens as well with other networks

**Comment by doerfli** [comment]
I can confirm the same issue. Reproduceable on latest dependabot updates of our repo, e.g. https://github.com/etherisc/gif-next/pull/283

**Comment by Wodann** [comment]
A fix to EDR was pushed and we'll publish a new release ASAP
