### ISSUE TITLE
Hardhat version 2.22.2 gas in network config not work

### ISSUE THREAD

**Issue by lolieatapple** [NomicFoundation/hardhat#5021]
### Version of Hardhat

2.22.2

### What happened?

I configured the gas value in the network section to 6000000, but it was not work when deploying with it. it still use the auto estimate gas value not the value I configured.

```
module.exports = {
  solidity: {
    version: "0.8.24",
    settings: {
      evmVersion: "london"
    }
  },
  networks: {
    wan: {
      url: "https://gwan-ssl.wandevs.org:56891",
      accounts: [process.env.PK],
      gasPrice: 2000000000,
      gas: 6000000
    }
  }
};
```

### Minimal reproduction steps

Deploy any contract with gas params.

```
module.exports = {
  solidity: {
    version: "0.8.24",
    settings: {
      evmVersion: "london"
    }
  },
  networks: {
    wan: {
      url: "https://gwan-ssl.wandevs.org:56891",
      accounts: [process.env.PK],
      gasPrice: 2000000000,
      gas: 6000000
    }
  }
};
```

**Comment by kanej** [comment]
Hey @lolieatapple, can I check:

* Was this working in a previous version, or is this the first time you have attempted this?
* Are you doing the deploy through `ethers`?

**Comment by lolieatapple** [comment]
Yes, I use ethers.js inside to deploy contract. and I have tested several version, it seems good in some early v4 versions.

**Comment by kanej** [comment]
I have spoken to the other devs. We expect the `gas` in your network config will be picked up by `ethers@v6`, but not by `ethers@v5`. Which version of `ethers` are you using?

**Comment by schaable** [comment]
I'm closing the issue as we had no further response. Let us know if this is still an issue and we can reopen.
