### ISSUE TITLE
Ganache integration 

### ISSUE THREAD

**Issue by hammersharkfish** [NomicFoundation/hardhat#5029]
### Describe the feature

`Truffle` is sunset and I have already moved my project to `hardhat` . `Ganache` still takes `truffle-config.js` without which it doesn't show `events` . My understanding is `ganache` comes under `truffle-suit` only .

**Comment by kanej** [comment]
Ganache has been sunset as well. We do not intend to integrate with it. We recommend using the built in Hardhat network.
