### ISSUE TITLE
allow to use hardhat-chai-matchers when installed by hardhat-toolbox

### ISSUE THREAD

**Issue by TheSnakeWitcher** [NomicFoundation/hardhat#5038]
Hi mates, currently isn't possible to use `anyValue` or `anyUint` from `chai-matchers/withArgs` when it is installed by `hardhat-toolbox`, maybe these could be tackled as part of #3517, thanks in advanced

**Comment by alcuadrado** [comment]
Hey, what does it mean that it's not possible? Can you clarify a bit more?

**Comment by TheSnakeWitcher** [comment]
Hey, I mean that when I install `hardhat-chai-matchers` via `hardhat-toolbox` I can't use it because `hardhat-chai-matchers` isn't re exported by `hardhat-toolbox`, currently there is a [workaround for network helpers](https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-toolbox#network-helpers) but not for `hardhat-chai-matchers`
I opened the issue because I don't know if these will tackled in #3517, if that's the case these could be closed rigth away or could be seen as a task of it, sorry If I wasn't clear enough 👍🏿

**Comment by TheSnakeWitcher** [comment]
Hi , that works, it just trow some type errors, probably will be solved in #351, thanks
