### ISSUE TITLE
hh shorthand opens HTML help on windows

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat#5040]
If you use the `hh` shorthand cli tool on Windows, it opens the HTML help app:

![image](https://github.com/NomicFoundation/hardhat/assets/24030/666234cd-0e4a-4f13-a0db-596f70162ad3)

Initially raised in this discussion: https://github.com/NomicFoundation/hardhat/discussions/4971

## Reproduction steps

1. Install the `hh` shorthand based [on the setup instructions](https://hardhat.org/hardhat-runner/docs/guides/command-line-completion#installation) of the Hardhat guide: `npm install --global hardhat-shorthand`
2. In a Hardhat project run `hh compile` or `hh test`
3. The HTML Help app will be inexplicable opened

**Comment by jwbda** [comment]
Hi, this is not really a bug. 
The reason why you type `hh` some strange web come up, is that `hh` in windows is point to `C:\Windows\hh.exe` .
`C:\Windows\hh.exe` is the executable file for the helper program (HTML Helper) in Windows. When you open a Help file (usually a file ending with a .chm extension) on Windows, hh.exe is used to open and display the Help content.

So it is conflict with `hh` of hardhat-shorthand.

## How to solve this
1. Install hardhat hh through `npm install --global hardhat-shorthand`, and find it with `npm list -g --depth 0 ` .
2. And change the name `hh/hh.cmd` to `ht/ht.cmd(any name you like)`
3. Use the name `ht/ht.cmd` with step 2 

Hope this answer will help you.
