### ISSUE TITLE
Format of `hre.config.paths.sources` changes when `hardhat-foundry` is in use

### ISSUE THREAD

**Issue by ItsNickBarry** [NomicFoundation/hardhat#5043]
### Version of Hardhat

2.22.2

### What happened?

The `hardhat-foundry` package changes `hre.config.paths.sources` from an absolute path to a relative path.  For example, without the plugin the path is "/home/user/hardhat-project/contracts", but with the plugin it's just "contracts".  This has caused some issues with one of my plugins (https://github.com/ItsNickBarry/hardhat-dependency-compiler/issues/16).

### Minimal reproduction steps

Check the value of `hre.config.paths.sources`.  Install `@nomicfoundation/hardhat-foundry`.  Check the value of `hre.config.paths.sources` again.

### Search terms

foundry, hardhat-foundry, sources, path, absolute, relative

**Comment by schaable** [comment]
Hi @ItsNickBarry, sorry for the delay in reviewing this issue. I can confirm that it's a bug as the paths in `hre.config.paths.sources` are meant to be absolute. `hardhat-foundry` is reassigning this object, but we should make the paths absolute first: https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-foundry/src/index.ts#L62
