### ISSUE TITLE
Error email after opening issue: "Add issue to project: All jobs have failed"

### ISSUE THREAD

**Issue by ItsNickBarry** [NomicFoundation/hardhat#5044]
I received the following email shortly after opening an issue in this repository.  Seems like some kind of CI misconfiguration.
![Screenshot](https://github.com/NomicFoundation/hardhat/assets/1500628/3a1a2c07-4cca-44fa-861a-c708e1946d9e)

**Comment by fvictorio** [comment]
I just fixed this (I think), thanks for letting us know!
