### ISSUE TITLE
[Warning] Invalid Fragment

### ISSUE THREAD

**Issue by xiaoyu1998** [NomicFoundation/hardhat#5046]
### Version of Hardhat

2.22.2

### What happened?

 Invalid Fragment warning, when i use contract as a type to a solidity library function input params. ethers.getContractFactory("library name") will get below warning, but not all functions have this contract as input type in this library have this warning, cuz the other functions were compiled this type DataStore to type address, not as DataStore.

[Warning] Invalid Fragment {"inputs":[{"internalType":"contract DataStore","name":"dataStore","type":"DataStore"},{"internalType":"address","name":"key","type":"address"}],"name":"get","outputs":[{"components":[{"internalType":"address","name":"account","type":"address"},{"internalType":"uint256","name":"collateralAndDebtPools","type":"uint256"}],"internalType":"struct Position.Props","name":"","type":"tuple"}],"stateMutability":"view","type":"function"}: invalid type (argument="type", value="DataStore", code=INVALID_ARGUMENT, version=6.11.1)

### Minimal reproduction steps

1.write the contract(DataStore) and the library(AppUtils),  
AppUtils has  function get(DataStore dataStore, address key) external view returns (Props memory)
2.npx hardhat compile
3.deploy AppUtils in ethers.getContractFactory("AppUtils")  has this warning.

### Search terms

[Warning] Invalid Fragment ethers.js v6.11.1

**Comment by xiaoyu1998** [comment]
I am tracking this issue, it was assert by ethers/lib.commonjs/abi/fragments.js/verifyBasicType
it need '/^(address|bool|bytes([0-9])|string|u?int([0-9]))$/' but get DataStore

**Comment by xiaoyu1998** [comment]
[OracleStoreUtils.json](https://github.com/NomicFoundation/hardhat/files/14838552/OracleStoreUtils.json)
```
  const artifact = await hre.artifacts.readArtifact("OracleStoreUtils");
  const oracle = new ethers.Interface(artifact.abi);
```
the 2nd line will get the warning, I have test in mac and ubuntu

**Comment by ChristopherDedominici** [comment]
Hi @xiaoyu1998, thanks for reporting the issue. This problem is related to ethers.js, not to Hardhat. So you should open a bug for ethers.js.
