### ISSUE TITLE
IgnitionError

### ISSUE THREAD

**Issue by devnkg** [NomicFoundation/hardhat#5071]
An unexpected error occurred:

IgnitionError: IGN1: Internal Hardhat Ignition invariant was violated: validateOverloadedName should only throw IgnitionErrors

**Comment by kanej** [comment]
Hey @iamNickDev, is the repo you are working on open source to help us reproduce the error?

**Comment by ArturVargas** [comment]
Hi Guys I have the same error when I executed:
`npx hardhat ignition deploy ./ignition/modules/VaultCreator.ts --network scrollSepolia`

<img width="1150" alt="Captura de pantalla 2024-04-29 a la(s) 7 25 50 p m" src="https://github.com/NomicFoundation/hardhat/assets/21693926/91953b94-b96d-459e-85a3-3e36d7a2fdcd">

Here's the repo with the code that I try to deploy: https://github.com/fruteroclub/chim_vault/blob/main/ignition/modules/VaultCreator.ts

**Comment by kanej** [comment]
> Hi Guys @iamNickDev @kanej , I have the same error when I executed: `npx hardhat ignition deploy ./ignition/modules/VaultCreator.ts --network scrollSepolia`
> <img alt="Captura de pantalla 2024-04-29 a la(s) 7 25 50 p m" width="1150" src="https://private-user-images.githubusercontent.com/21693926/326634290-91953b94-b96d-459e-85a3-3e36d7a2fdcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzA5ODksIm5iZiI6MTcxNTA3MDY4OSwicGF0aCI6Ii8yMTY5MzkyNi8zMjY2MzQyOTAtOTE5NTNiOTQtYjk2ZC00NTllLTg1YTMtM2UzNmQ3YTJmZGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA4MzEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyMWFjY2U4NmQxNjgzMGIxZjhhMzJlZjA0ZjBmYThlYTgwOWQ3NmNmMTYyODYxZDUyMmI5ZmE4ZjYxNmQ2Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bjKHUMsWB0lG-LLrBebqijeLqNekNWwW9_ckI-cHSEQ">
> 
> Here's the repo with the code that I try to deploy: https://github.com/fruteroclub/chim_vault/blob/main/ignition/modules/VaultCreator.ts

Hey @ArturVargas, I think this is a separate issue. We are obscuring the underlying error (which is often insufficient funds in the account).

You can track the issue here: https://github.com/NomicFoundation/hardhat-ignition/issues/750
