### ISSUE TITLE
HH301: Invalid value 1 for argument value of type int

### ISSUE THREAD

**Issue by ItsNickBarry** [NomicFoundation/hardhat#5089]
### Version of Hardhat

2.22.2

### What happened?

`BigInt` types cannot be passed to tasks.

Maybe this is more of a feature request, but at the very least the error message itself is a bug, because `1` is clearly an `int`.

### Minimal reproduction steps

```
hh console
```

```
const { task, types } = require('hardhat/config');
task('err').addOptionalParam('value', '', 0n, types.int).setAction(async () => {});
await hre.run('err', { value: 1n });
```

**Comment by schaable** [comment]
Hi @ItsNickBarry, thanks for reporting this. You're correct; we currently do not support `BigInt`, and I agree that the error message is confusing.

**Comment by ItsNickBarry** [comment]
Is there anything in particular blocking bigint support?  It seems like a change to the `Number.isInteger` check in `argumentTypes.ts` is all that's needed, and I can't immediately think of any negative consequences to allowing bigints.  Let me know and I'll PR.

**Comment by kanej** [comment]
We should implement the improved error message.
On `bigint` support generally, I think your right @ItsNickBarry that programmatically it is easy to add the support but we would likely want to add cli support for bigints at the same time, and that will need more thought.

**Comment by ItsNickBarry** [comment]
Yeah, I'll look into it.
