### ISSUE TITLE
provider.getFeeData().maxPriorityFeePerGas vs eth_maxPriorityFeePerGas different values

### ISSUE THREAD

**Issue by JeremyX2022** [NomicFoundation/hardhat#5093]
### Version of Hardhat

2.20

### What happened?

Why the value of maxPriorityFeePerGas are different by using these two methods?
I tested it on the Ethereum mainnet

### Minimal reproduction steps

1. config hardhat network:
```
  networks: {
    mainnet: {
      url: "https://eth.llamarpc.com",
    },
  }
```

2. goto hardhat console: `npx hardhat console --network mainnet`

3. using following codes:
```typescript
const p = new ethers.JsonRpcProvider("https://eth.llamarpc.com")

console.log([(await ethers.provider.getFeeData()), Number(await ethers.provider.send('eth_maxPriorityFeePerGas', []))]);
console.log([(await p.getFeeData()), Number(await p.send('eth_maxPriorityFeePerGas', []))]);
```
output:
```
> [
  FeeData {
    gasPrice: 16951633560n,
    maxFeePerGas: 34883267120n,
    maxPriorityFeePerGas: 1000000000n
  },
  10000000
]


> [
  FeeData {
    gasPrice: 16951633560n,
    maxFeePerGas: 33893267120n,
    maxPriorityFeePerGas: 10000000n
  },
  10000000
]
```

You can see 'maxPriorityFeePerGas' in 'getFeeData' is different from the value of 'eth_maxPriorityFeePerGas' by using ethers.provider.

**Comment by kanej** [comment]
Hey @JeremyX2022, can I confirm the version of `ethers` you are using here?

**Comment by JeremyX2022** [comment]
> Hey @JeremyX2022, can I confirm the version of `ethers` you are using here?

> ethers.version
'6.11.1'

**Comment by JeremyX2022** [comment]
I also post in ethers: https://github.com/ethers-io/ethers.js/issues/4656
but the issue seems more related to hardhat

**Comment by kanej** [comment]
I can reproduce this locally. It appears that `ethers` delegates to `eth_maxPriorityFeePerGas` RPC call for calculating gas falling back to a default of `1_000_000_000n` and the Harhdat `hardhat-ethers-provider` always returns the default:

https://github.com/NomicFoundation/hardhat/blob/dc6840c31445398a876813abcda8ba8e5a5796cb/packages/hardhat-ethers/src/internal/hardhat-ethers-provider.ts#L144-L158

We should update this logic to match the `ethers` logic.

**Comment by sambacha** [comment]
it should be noted that eth_maxPriorityFeePerGas was not originally  part of the official Ethereum JSON-RPC specification and originally a go-ethereum only RPC method. It is now part of the execution api spec.
