### ISSUE TITLE
Windows defender detects Trojan:Win32/CoinMiner.N!cl in @nomicfoundation/edr-win32-x64-msvc

### ISSUE THREAD

**Issue by joticajulian** [NomicFoundation/hardhat#5099]
### Version of Hardhat

@nomicfoundation/edr-win32-x64-msvc-0.2.1

### What happened?

Windows defender is detecting `Trojan:Win32/CoinMiner.N!cl` in this file `C:\Users\XXX\AppData\Local\Yarn\Cache\v6\npm-@nomicfoundation-edr-win32-x64-msvc-0.2.1-7b56ff742b2724779cc9f3385815b394f76de8df-integrity\node_modules\@nomicfoundation\edr-win32-x64-msvc\edr.win32-x64-msvc.node`

### Minimal reproduction steps

This appeared after a normal malware check from Windows Defender.

### Search terms

windows defender

**Comment by Wodann** [comment]
Would you be able to submit the `edr.win32-x64-msvc.node` for analysis through this url? 

https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by joticajulian** [comment]
ok, I already submitted the file. It is in progress.

**Comment by Wodann** [comment]
> ok, I already submitted the file. It is in progress.

Thank you!

**Comment by fvictorio** [comment]
Thanks for the update @joticajulian! We are going to check if we can start [signing our EDR binaries](https://github.com/NomicFoundation/edr/issues/380) to prevent this from happening again in the future.
