### ISSUE TITLE
Hardhat wasn't initialized

### ISSUE THREAD

**Issue by huangwei0739** [NomicFoundation/hardhat#5101]
### Version of Hardhat

2.13.1

### What happened?

Hardhat initialization failed. This is a bug.

### Minimal reproduction steps

 _stack: 'HardhatError: HH5: HardhatContext is not created.\n' +
    '    at HardhatContext.getHardhatContext (\node_modules\\hardhat\\internal\\context.js:38:19)\n' +        
    '    at extendEnvironment (\node_modules\\hardhat\\internal\\core\\config\\config-env.js:72:42)\n' +      
    '    at Object.<anonymous> (\node_modules\\@nomicfoundation\\hardhat-ethers\\internal\\index.js:7:32)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n' +
    '    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:1207:32)\n' +
    '    at Module._load (node:internal/modules/cjs/loader:1023:12)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1235:19)\n' +
    '    at require (node:internal/modules/helpers:176:18)\n' +
    '    at Object.<anonymous> (\node_modules\\@nomicfoundation\\hardhat-chai-matchers\\index.js:3:1)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n' +
    '    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:1207:32)\n' +
    '    at Module._load (node:internal/modules/cjs/loader:1023:12)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1235:19)\n' +
    '    at require (node:internal/modules/helpers:176:18)',

### Search terms

HardhatContext is not created.

**Comment by ChristopherDedominici** [comment]
Hi @huangwei0739, are you able to reproduce the issue on the latest Hardhat version? If so, could you share the exact reproduction steps so I can reproduce it on my side? Thanks
