### ISSUE TITLE
Quick start guide doesn't work with Yarn

### ISSUE THREAD

**Issue by wslyvh** [NomicFoundation/hardhat#5105]
### Version of Hardhat

2.22.2

### What happened?

I'm trying to use the quick start guide to setup a project, but with yarn instead of npm.

1. I understand this is because of how npm and yarn resolve their dependencies, but it misses a lot of dependencies.
iirc, you need to

yarn add typescript ts-node @nomicfoundation/hardhat-ignition @nomicfoundation/ignition-core @nomicfoundation/hardhat-ignition-viem @nomicfoundation/hardhat-network-helpers @nomicfoundation/hardhat-verify @nomicfoundation/hardhat-viem @types/chai @types/chai-as-promised @types/mocha chai hardhat-gas-reporter solidity-coverage -D

It would be better to list all dependencies in the guide, or even include everything by default and it works for all package managers.

You then run into the issue #4762
(it works fine with npm)

### Minimal reproduction steps

1. mkdir hardhat && cd hardhat
2. npx hardhat init
  - Create a TypeScript project (with Viem)
  - default project root, gitignore (y), install sample (y)
3. yarn
4. npx hardhat compile

**Comment by ChristopherDedominici** [comment]
Hi @wslyvh, I tried to install Hardhat using the steps in [the docs](https://hardhat.org/hardhat-runner/docs/getting-started) for installing Hardhat via Yarn, and everything worked fine.

However, I also reproduced your error.
My suspicion is that running `npx hardhat init` without Hardhat installed, installs it via npm. Then, running `yarn` reinstalls all packages, likely creating both a `package-lock.json` and a `yarn.lock` file, leading to an "unstable" state and the error.

If you follow these commands in order, everything should work:

- `mkdir hardhat`
- `cd hardhat`
- `yarn add --dev hardhat`
- `npx hardhat init` -> choose "Create a TypeScript project (with Viem)" and answer 'yes' to all questions
- `npx hardhat compile`

I'm closing the issue, but please let me know if this doesn't resolve your problem

**Comment by wslyvh** [comment]
Oh, I see. I must've mixed up some of the steps indeed. My bad! 
I can confirm your steps work! Thanks
