### ISSUE TITLE
Property 'xxx' does not exist on type 'BaseContract' when use connect( )

### ISSUE THREAD

**Issue by CT77777** [NomicFoundation/hardhat#5112]
### Version of Hardhat

2.22.2

### What happened?

```
const depositTokenContract = await ethers.deployContract("depositToken", [swapContractAddress, settlementContractAddress, owner.address])
```
based on above code, write
`await depositTokenContract.mint(wallet1, 10000000)` will pass type check

but connect another runner,
`await depositTokenContract.connect(anotherRunner).mint(wallet1, 10000000)`
will show "Property 'mint' does not exist on type 'BaseContract'"

### Minimal reproduction steps

na

**Comment by kanej** [comment]
Hey @CT77777, that is unexpected. The enhanced types should be coming from Typechain. Have you been able to do a successful build ot the deposit token contract? It is the build that generates the type information.

**Comment by schaable** [comment]
Closing due to lack of response. Happy to reopen if you can provide more info.

**Comment by davidAI04** [comment]
@schaable  This is the second time that I find these errors in the last 2 years. The last time, the error was generated because of an incompatibility between Signer and HardhatEtherSigners instances. This is happening to me again. Now I'm trying to install TypeChain, but an error with ethers dependencies is appearing.

**Comment by kanej** [comment]
> @schaable @kanej This is the second time that I find these errors in the last 2 years. The last time, the error was generated because of an incompatibility between Signer and HardhatEtherSigners instances. This is happening to me again. Now I'm trying to install TypeChain, but an error with ethers dependencies is appearing.

Hey @davidAI04, can we get some more details?

You have a Hardhat project, `hardhat-ethers` is installed and included in the Hardhat config, and you are attempting to install `typechain`, is that correct?

Can I ask:

* what error are you seeing when you attempt the `typechain` install?
* do you also have the toolbox installed?
* what version of Hardhat are you on?

**Comment by davidAI04** [comment]
Some code:

```
//From deploy script
  import { ethers, upgrades } from "hardhat";
  const signers = await ethers.getSigners();
  const owner = signers[0];
  const governance = signers[1];
  
 //From hardhat config
  import { HardhatUserConfig } from "hardhat/config";
import "@nomicfoundation/hardhat-ethers";
import "@nomicfoundation/hardhat-toolbox";
import "@openzeppelin/hardhat-upgrades";

const config: HardhatUserConfig = {
  solidity: {
    version: "0.8.24",
    settings: {
      optimizer: {
        enabled: true,
        runs: 200
      }
    }
  },
  
  //pachake.json
  "devDependencies": {
    "@nomicfoundation/hardhat-ethers": "^3.0.6",
    "@nomicfoundation/hardhat-toolbox": "^5.0.0",
    "ethers": "^5.7.2",
    "hardhat": "^2.22.5"
  },
  "dependencies": {
    "@openzeppelin/contracts-upgradeable": "^5.0.2",
    "@openzeppelin/hardhat-upgrades": "^3.2.0"
  }

```

using ethers 6.13.2
![image](https://github.com/user-attachments/assets/9642e226-c375-417c-9f47-fb92f29fc653)

using ethers 5.7.2
![image](https://github.com/user-attachments/assets/ba2229cb-7a5e-4cdd-a684-aba205ea5451)


Typechain installation error, this error occurred for both ethers versions 

```
npm error code ERESOLVE
npm error ERESOLVE could not resolve
npm error
npm error While resolving: @nomicfoundation/hardhat-chai-matchers@2.0.7
npm error Found: ethers@5.7.2
npm error node_modules/ethers
npm error   ethers@"^5.7.2" from eth-gas-reporter@0.2.27
npm error   node_modules/eth-gas-reporter
npm error     eth-gas-reporter@"^0.2.25" from hardhat-gas-reporter@1.0.10        
npm error     node_modules/hardhat-gas-reporter
npm error       peer hardhat-gas-reporter@"^1.0.8" from @nomicfoundation/hardhat-toolbox@5.0.0
npm error       node_modules/@nomicfoundation/hardhat-toolbox
npm error         dev @nomicfoundation/hardhat-toolbox@"^5.0.0" from the root project
npm error   dev ethers@"^5.7.2" from the root project
npm error
npm error Could not resolve dependency:
npm error peer ethers@"^6.1.0" from @nomicfoundation/hardhat-chai-matchers@2.0.7 
npm error node_modules/@nomicfoundation/hardhat-chai-matchers
npm error   peer @nomicfoundation/hardhat-chai-matchers@"^2.0.0" from @nomicfoundation/hardhat-toolbox@5.0.0
npm error   node_modules/@nomicfoundation/hardhat-toolbox
npm error     dev @nomicfoundation/hardhat-toolbox@"^5.0.0" from the root project
npm error
npm error Conflicting peer dependency: ethers@6.13.2
npm error node_modules/ethers
npm error   peer ethers@"^6.1.0" from @nomicfoundation/hardhat-chai-matchers@2.0.7
npm error   node_modules/@nomicfoundation/hardhat-chai-matchers
npm error     peer @nomicfoundation/hardhat-chai-matchers@"^2.0.0" from @nomicfoundation/hardhat-toolbox@5.0.0
npm error     node_modules/@nomicfoundation/hardhat-toolbox
npm error       dev @nomicfoundation/hardhat-toolbox@"^5.0.0" from the root project
npm error
```

**Comment by kanej** [comment]
You should remove the dev dependency on `@nomicfoundation/hardhat-ethers`, you will get it as a peer dependency of `@nomicfoundation/hardhat-toolbox`.

The toolbox assumes ethers v6.1 or above: "^6.1.0"

So maybe something like:

```json
  "devDependencies": {
    "@nomicfoundation/hardhat-toolbox": "^5.0.0",
    "ethers": "^6.1.0",
    "hardhat": "^2.22.5"
  },
```

If you can't switch to ethers v6, you will need to use an older `hardhat-toolbox`. Version `v2.0.2` was the latest using ethers v5.
