### ISSUE TITLE
any plugin for integration with https://mythx.io  ?

### ISSUE THREAD

**Issue by orenyodfat** [NomicFoundation/hardhat#514]
see https://docs.mythx.io/en/latest/tools/index.html#mythx-tools-integrations .
if not , is there any alternative recommended security tool for using with Buidler.dev ?

**Comment by alcuadrado** [comment]
Hey @orenyodfat,

We don't have a plugin for MythX at the moment. We'll definitely consider building or supporting anyone who wants to build one.
