### ISSUE TITLE
The hardhat node subscription event is not working

### ISSUE THREAD

**Issue by yinchonging** [NomicFoundation/hardhat#5146]
### Version of Hardhat

2.22.2 

### **Step1 (Start hardhat node):** 
![企业微信截图_17135210739300](https://github.com/NomicFoundation/hardhat/assets/2151476/faeff259-d3b7-4f40-9582-675c8c925e72)

### **Step2 (Deploy contract)：**
![企业微信截图_17135211626567](https://github.com/NomicFoundation/hardhat/assets/2151476/3076fdad-b27d-404d-912c-90ec0bb0e025)

### **Step3 (Add listener):**
![企业微信截图_1713521884975](https://github.com/NomicFoundation/hardhat/assets/2151476/59972292-df21-4907-afe9-5aaf33935bf5)

### **Step4 (Hardhat logs show that the subscription was successful):**
![企业微信截图_17135212476053](https://github.com/NomicFoundation/hardhat/assets/2151476/0f72e7ef-5ba3-463f-a6be-d739d544b4bf)

### **Step5(The event was not emitted after being called):**
![企业微信截图_17135214145185](https://github.com/NomicFoundation/hardhat/assets/2151476/0b1132e3-4895-4fb6-b381-494eeae185da)

**Comment by schaable** [comment]
Hi @yinchonging, I'm closing this issue for now since the example you provided seems to be working on my end and we haven't received any additional information from you. I'm happy to reopen it if you can provide more details. Thanks!
