### ISSUE TITLE
Consider modifying your module to remove the inconsistencies with deployed futures.

### ISSUE THREAD

**Issue by phpmac** [NomicFoundation/hardhat#5158]
### Version of Hardhat

2.22.3

### What happened?

```sh

(base) ➜  hardhat git:(dev) ✗ npx hardhat ignition deploy ignition/modules/Fcm.ts --network bsc --verify        

✔ Confirm deploy to network bsc (97)? … yes
[ FcmModule ] reconciliation failed ⛔

The module contains changes to executed futures:

FcmModule#FCM:
 - Artifact bytecodes have been changed

Consider modifying your module to remove the inconsistencies with deployed futures.
(base) ➜  hardhat git:(dev) ✗ 





```

### Minimal reproduction steps

```sh

(base) ➜  hardhat git:(dev) ✗ npx hardhat ignition deploy ignition/modules/Fcm.ts --network bsc --verify        

✔ Confirm deploy to network bsc (97)? … yes
[ FcmModule ] reconciliation failed ⛔

The module contains changes to executed futures:

FcmModule#FCM:
 - Artifact bytecodes have been changed

Consider modifying your module to remove the inconsistencies with deployed futures.
(base) ➜  hardhat git:(dev) ✗ 





```

**Comment by phpmac** [comment]
I tried manually deleting the `ignition/deployments` directory to solve the problem.

**Comment by kanej** [comment]
This message appears when Ignition detects that the deployment has been previously run, a change to the Solidity code of the smart contract has been introduced and the deployment rerun. Ignition sees that the contract it is trying to deploy has previously been deployed, but that the bytecode compiled from the Solidity code is not the same. It therefore stops and lets you decide what to do.

You can `wipe` the state against that contract (i.e. `FcmModule#FCM`) with [the wipe command](https://hardhat.org/ignition/docs/guides/error-handling#wiping-a-previous-execution).

You can run an entirely new deployment by passing a different deployment id:

```
npx hardhat ignition deploy ignition/modules/Fcm.ts --network bsc --verify --deployment-id second-deploy
```

Deleting the `./deployments` folder will allow you to deploy the same module again but it will delete the metadata of the previous deployments (e.g. the deployed addresses of the contracts).
