### ISSUE TITLE
Add verification support for Amoy testnet (Chain ID 80002)

### ISSUE THREAD

**Issue by Nicksart** [NomicFoundation/hardhat#5168]
### Describe the feature

Since the deprecation of the Mumbai testnet and the transition to the Amoy testnet `npx hardhat verify` does not work with Amoy because Chain ID 80002 is not supported. 
It would be cool if hardhat team could include support for Amoy's chain to facilitate contract verification on this network.

### Search terms

amoy verification

**Comment by kanej** [comment]
I think this is resolved by: https://github.com/NomicFoundation/hardhat/pull/5163
