### ISSUE TITLE
[hardhat-ganache] Can't configure Ganache for tests

### ISSUE THREAD

**Issue by nmlinaric** [NomicFoundation/hardhat#518]
Hi, everyone!

We're using a typescript based `buidler.config` and want to configure `ganache` like described [here](https://buidler.dev/plugins/nomiclabs-buidler-ganache.html#installation)
but it doesn't work because `budiler NetworkConfig` and [ganache network config](https://github.com/trufflesuite/ganache-core#options) don't match.

Secondly - tried it inside [this](https://github.com/nomiclabs/buidler-hackathon-boilerplate) `.js` project and get:<br> `Error: BDLR109: Cannot connect to the network ganache.`<br>`Please make sure your node is running, and check your internet connection and networks config`

**Comment by alcuadrado** [comment]
Hey @nmlinaric!

Thanks for trying out Buidler :) 

Do you have a link to your config file so we can help you debug it? Thanks!

**Comment by nmlinaric** [comment]
@alcuadrado thanks for the quick response. It's a private repository so the best i can do is this:
`
import {BuidlerConfig, usePlugin} from "@nomiclabs/buidler/config";

usePlugin("@nomiclabs/buidler-solhint");
usePlugin("@nomiclabs/buidler-waffle");
usePlugin("@nomiclabs/buidler-ethers");
usePlugin("@nomiclabs/buidler-ganache");

usePlugin("solidity-coverage");
usePlugin("buidler-typechain");
usePlugin("buidler-gas-reporter");

const config: BuidlerConfig = {
    defaultNetwork: "buidlerevm",
    solc: {
        version: "0.6.6"
    },
    paths: {
        sources: "./contracts/",
        artifacts: "./artifacts/"
    },
    networks: {
        goerli: {
            url: `https://goerli.infura.io/v3/'${process.env.INFURA_PROJECT_ID}`,
            accounts: {
                mnemonic: `${process.env.GOERLI_MNEMONIC}`
            },
            gas: "auto",
            gasPrice: "auto",
            gasMultiplier: 1
        },
        ganache: {
            gasLimit: 6000000000,
            defaultBalanceEther: 10
        },
        mainnet: {
            url: `https://mainnet.infura.io/v3/${process.env.INFURA_PROJECT_ID}`,
            accounts: {
                mnemonic: `${process.env.MAINNET_MNEMONIC}`
            }
        }
    },
    typechain: {
        outDir: "typechain",
        target: "ethers"
    }
};

export default config;
`

**Comment by marcelomorgado** [comment]
I was able to make it working with this config:

```
const config /*: BuidlerConfig*/ = {
  solc: {
    version: "0.5.15",
  },
  defaultNetwork: "ganache",
  mocha: {
    timeout: 0,
  },
  networks: {
    ganache: {
      url: "http://127.0.0.1:8555",
      fork: https://mainnet.infura.io/v3/${INFURA_ID},
      network_id: 1,
      timeout: 0,
      logger: console,
    },
  },
};
```

**Comment by fvictorio** [comment]
My two cents, this is the type for `NetworkConfig`:

```
export type NetworkConfig = BuidlerNetworkConfig | HttpNetworkConfig;
```

So I guess that should be extended to support some sort of `GanacheConfig`. But this comes from a plugin, so ideally it should be the plugin's responsibility to extend the types accordingly. I think this should be done [in this file](https://github.com/nomiclabs/buidler/blob/master/packages/buidler-ganache/src/type-extensions.d.ts).

**Comment by fvictorio** [comment]
https://github.com/nomiclabs/buidler/issues/412 seems related to this.

**Comment by xuhcc** [comment]
Another workaround is to cast ganache config to any:

```ts
const config: BuidlerConfig = {
  networks: {
    ganache: {
      url: "http://127.0.0.1:8555",
    } as any,
  },
};
```

**Comment by PaulRBerg** [comment]
Casting to any is not great. Here's something better:

```typescript
export type ExtendedNetworkConfig = NetworkConfig & {
  _chainId?: number;
  default_balance_ether?: number,
  gasLimit?: number;
  mnemonic?: string;
  network_id?: number;
  url?: string;
};

export interface ExtendedNetworks extends Networks {
  [networkName: string]: ExtendedNetworkConfig;
}

export interface ExtendedBuidlerConfig extends BuidlerConfig {
  networks?: ExtendedNetworks;
}
```

Although Hardhat should ideally provide some basic types for extending the "ganache" network.

**Comment by fvictorio** [comment]
Closing this because it's unlikely to still be relevant.
