### ISSUE TITLE
npx hardhat init permission denied on WSL 2

### ISSUE THREAD

**Issue by liz7124** [NomicFoundation/hardhat#5183]
### Version of Hardhat

2.12.5

### What happened?

I use WSL 2 to follow [hardhat tutorial](https://hardhat.org/tutorial/creating-a-new-hardhat-project).
When I run `npx hardhat init` returns error `sh: 1: hardhat: Permission denied`.

### Minimal reproduction steps

Using WSL 2 to run npx hardhat init

**Comment by kanej** [comment]
This is likely not a Hardhat issue, but a permission issue with the location you are trying to create your new Hardhat project through the `init` task.
For instance, writing to folders under the windows drive file system from Linux may run into permission issues:

https://learn.microsoft.com/en-us/windows/wsl/file-permissions

**Comment by lyh0515** [comment]
I type `hh init` and it works for me. `hh init`
