### ISSUE TITLE
Question - Check constructorArguments type

### ISSUE THREAD

**Issue by fwx5618177** [NomicFoundation/hardhat#5189]
Question:
1. Why not strictly check the constructorArguments type on this function?
2. Why did we put this check process on the backend?

<img width="564" alt="image" src="https://github.com/NomicFoundation/hardhat/assets/25654385/e56adff3-2ad0-4a26-ae3c-9d5037a40ef8">

**Comment by schaable** [comment]
Hi @fwx5618177! The constructor arguments are required for verifying the contract on Etherscan, and they need to be encoded. Regarding the types, feel free to submit a PR to improve them. I'm closing this as it is not an issue. If you have further questions, feel free to ask in the [discussions](https://github.com/NomicFoundation/hardhat/discussions) tab.

**Comment by schaable** [comment]
That's because the types received from the CLI can be ambiguous. However, if the constructor arguments cannot be encoded using the contract's constructor types, the `encodeDeploy` will fail. If the CLI arguments can be successfully encoded, we consider them valid. How would you verify that the types are valid?

**Comment by fwx5618177** [comment]
> That's because the types received from the CLI can be ambiguous. However, if the constructor arguments cannot be encoded using the contract's constructor types, the `encodeDeploy` will fail. If the CLI arguments can be successfully encoded, we consider them valid. How would you verify that the types are valid?

We might consider referring to the approach in bitcoinlib.js, using Typesforce for strict type checking of constructor parameters. For instance, we could individually check each parameter using `contractInterface.deploy.inputs.type`.

**Comment by schaable** [comment]
I'm not quite following what the issue here is, our current implementation throws an error if the `encodeDeploy` doesn't receive the proper arguments. If you think you can provide an improvement, feel free to submit a PR.

**Comment by fwx5618177** [comment]
> I'm not quite following what the issue here is, our current implementation throws an error if the `encodeDeploy` doesn't receive the proper arguments. If you think you can provide an improvement, feel free to submit a PR.

Not an issue, just I read the code and debug and found this. So I just want to know why the design checks on API response.
