### ISSUE TITLE
Unclear message for missing import error

### ISSUE THREAD

**Issue by scnale** [NomicFoundation/hardhat#519]
If you make a mistake when writing an import, the error message is not immediately clear.
When running the buidler compile task you get:
```shell
$ npx buidler compile
Error BDLR403: Library IMulticaller.so is not installed.

For more info go to https://buidler.dev/BDLR403 or run Buidler with --show-stack-traces
```

When running the solidity compiler instead you get:
```shell
$ solc --allow-paths contracts/ contracts/Multicaller.sol
Error: Source "IMulticaller.sol" not found: File outside of allowed directories.
 --> contracts/Multicaller.sol:3:1:
  |
3 | import "IMulticaller.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The file, line and column where the compiler error is raised would improve the message quite a bit for instance.

**Comment by fvictorio** [comment]
I guess we could have a simple heuristic here where if an import ends in `.sol` and there are no slashes, we add "Did you mean ./IMulticaller.sol" to the error message?

**Comment by cameel** [comment]
I will soon be working on rewording these messages in the compiler. If you have any suggestions on what the message should say so that Hardhat can display it directly without confusing users, please post your feedback in https://github.com/ethereum/solidity/issues/11413.

**Comment by fvictorio** [comment]
Closing in favor of #3499
