### ISSUE TITLE
Pragma Statement Warning on New Hardhat Installation

### ISSUE THREAD

**Issue by JF0001** [NomicFoundation/hardhat#5202]
I have completed a new installation of Hardhat. 
In the hardhat.config.js file, I have this code:
`module.exports = {
  solidity: "0.8.24",
};`

While in the default Lock.sol contract, which is created during the installation, I have this pragma statement:
`pragma solidity ^0.8.24;`

However, I am getting the following warning on my pragma statement:
"Source file requires different compiler version (current compiler is 0.8.19+commit.7dd6d404.Emscripten.clang) - note that nightly builds are considered to be strictly less than the released version(5333)"

_Originally posted by @JF0001 in https://github.com/NomicFoundation/hardhat/discussions/5201_

**Comment by kanej** [comment]
Hey @JF0001, I have created a fresh project with `v2.22.3` of Hardhat. But I have found no warning.

Is this a warning that appears on `npx hardhat compile`? Or shows up inline in your editor? If its in the editor, which plugin/extension do you use?

**Comment by JF0001** [comment]
Hi @kanej I have followed the instructions found at the link hereafter, after which I had the files I have mentioned in my previous post (hardhat.config.js and Lock.sol). I have not modified nor executed anything else. I am on Ubuntu with the latest version of node and all the libraries.

[https://hardhat.org/hardhat-runner/docs/getting-started](url)
