### ISSUE TITLE
Failed to send contract verification request.

### ISSUE THREAD

**Issue by TomWang1** [NomicFoundation/hardhat#5214]
### Version of Hardhat

2.6.2

### What happened?

 hh run scripts/deploynft.js --network bsc                                                     ⬢ system
(node:84862) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Verifying contract
(node:84872) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)

/Users/fly/Deskto/release/node_modules/@nomicfoundation/hardhat-verify/src/internal/etherscan.ts:199
      throw new UnexpectedError(e, "Etherscan.verify");
            ^
UnexpectedError: An unexpected error occurred during the verification process.
Please report this issue to the Hardhat team.
Error Details: Failed to send contract verification request.
Endpoint URL: https://api.bscscan.com/api
Reason: The Etherscan API responded that the address 0x1xxxxxxxxx does not have bytecode.
This can happen if the contract was recently deployed and this fact hasn't propagated to the backend yet.
Try waiting for a minute before verifying your contract. If you are invoking this from a script,
try to wait for five confirmations of your contract deployment transaction before running the verification subtask.
    at Etherscan.verify (/Usersase/node_modules/@nomicfoundation/hardhat-verify/src/internal/etherscan.ts:199:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SimpleTaskDefinition.action (/Users/_sol/release/node_modules/@nomicfoundation/hardhat-verify/src/internal/tasks/etherscan.ts:297:33)
    at Environment._runTaskDefinition (/Usse/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/Users/fly/De/release/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/Userssol/release/node_modules/@nomicfoundation/hardhat-verify/src/internal/tasks/etherscan.ts:155:7)
    at Environment._runTaskDefinition (/Usersse/node_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)
    at Environment.run (/Users/ol/release/node_modules/hardhat/src/internal/core/runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (/Users/fly/Desktdules/@nomicfoundation/hardhat-verify/src/index.ts:284:9)
    at Environment._runTaskDefinition (/Users/de_modules/hardhat/src/internal/core/runtime-environment.ts:217:14)

### Minimal reproduction steps

async function iniNFT () {
  const nftName = [
    "Hera",
    "Demeter",
    "Poseidon",
    "Athena",
    "Apollo",
    "Artemis",
    "Aphrodite",
    "Ares",
    "Hephaestus",
    "Hermes",
    "Hestia",
    "Hades",
    "Pantheon",
    "Zeus"
  ];

  const nftSymble = [
    "Hera",
    "Demeter",
    "Poseidon",
    "Athena",
    "Apollo",
    "Artemis",
    "Aphrodite",
    "Ares",
    "Hephaestus",
    "Hermes",
    "Hestia",
    "Hades",
    "Pantheon",
    "Zeus"];
    const basurls = "https://n?";
    const nftJsonUri = [
      basurls + "coinname=Hera",
      basurls + "coinname=Demeter",
      basurls + "coinname=Poseidon",
      basurls + "coinname=Athena",
      basurls + "coinname=Apollo",
      basurls + "coinname=Artemis",
      basurls + "coinname=Aphrodite",
      basurls + "coinname=Ares",
      basurls + "coinname=Hephaestus",
      basurls + "coinname=Hermes",
      basurls + "coinname=Hestia",
      basurls + "coinname=Hades",
      basurls + "coinname=Pantheon",
      basurls + "coinname=Zeus"
    ]

    const nftAmount = [
      40000,
      40000,
      40000,
      40000,
      40000,
      40000,
      40000,
      40000,
      40000,
      40000,
      40000,
      40000,
      40000,
      20000
    ];

    const nftAddress = [
      "0x1Eed1Def524",
      "0xB5376d5498E6bBA",
      "0x347039FF2106E62",
      "0xFa023d09f6a0f",
      "0x732A5229d9523",
      "0x8d61BAE674bc34",
      "0xFF579bA23916E5",
      "0x20ED69fE9C2Dc8B8cf7a",
      "0xF2f273C9D320BF5E08815F6",
      "0x805472815E5cDC765294",
      "0x8Dd5Bb6dAee6b1f0421",
      "0x08e75FbB9c3CdC4CC4d64",
      "0x14c56e3f6d443d3",
      "0x3A873922967b266279D04805b8",
  ];

    for (let index = 0; index < nftName.length; index++) {
      const name = nftName[index];
      const symbol = nftSymble[index];
      const uri = nftJsonUri[index];
      const amount = nftAmount[index];
      const nfts = nftAddress[index];
      // const Lock = await hre.ethers.getContractFactory("BaseNFT");
      // const lock = await Lock.deploy(name,symbol,uri,amount);
      // await lock.deployed();

      // console.log(
      //   `${name} deployed to ${lock.address}`
      // );

      console.log("Verifying contract");
      const nftC = await hre.ethers.getContractAt("BaseNFT",nfts);
      // const per =  await lock.deployTransaction().wait(6);
      // console.log(`wait time output->`,per);

      await hre.run("verify:verify", {
        address: nftC.address,
        contract: "contracts/NFT/baseNFT.sol:BaseNFT",
        constructorArguments: [
          name,
          symbol,
          uri,
          amount,
        ],
      }); // <----------
      // await hre.run(`npx hardhat verify --network ${hre.network.name} ${wbnb.address}`);
    
      console.log("Contract verified");
      
    }

}

**Comment by kanej** [comment]
This looks like an issue with the bsc explorer. I would try a separate verification for bsc, and failing that fall back to verifying with bscscan directly.

**Comment by schaable** [comment]
This is an issue with the block explorer and usually happens if you try to verify immediately after deploying the contract. You should wait a couple of confirmations before verifying the contract.
