### ISSUE TITLE
Add Blockscout as verification provider 

### ISSUE THREAD

**Issue by rimrakhimov** [NomicFoundation/hardhat#5224]
### Describe the feature

We suggest adding Blockscout as a verification provider to Hardhat. Technically, it is possible right now to verify contracts on blockscout Explorer via etherscan configuration. But we would like to propose adding an explicit blockscout option along with existing sourcify and etherscan providers.

### Motivation

Using etherscan configuration requires specifying an API key even though blockscout does not need one. Users have to select any non-empty key to avoid that limitation. Having blockscout specified explicitly allows them to have blockscout support without any workarounds.

It also helps to integrate blockscout-specific features into the process in the future. For example, for enforcing smart contracts verification, added in https://github.com/NomicFoundation/hardhat/pull/5164, it does not distinguish between partially and fully verified contracts, returning an error if the contract has already been fully verified. We may add that distinction to the usual verification process to avoid using the `--force` flag. Besides, we are currently working on a separate application that will allow us to verify the contracts on several blockscout chains ([link](https://verification-app.k8s-dev.blockscout.com/)). In the future, this could be used to prevent users from specifying the details for the most common chains at all.

We are witnessing an increasing number of users, in general, asking whether hardhat supports blockscout and how to use it for contract verification. And it would be nice if Hardhat could support blockscout as a separate option.

### Suggestion

Our proposal involves creating a separate Blockscout class that would be integrated into the current Hardhat configuration. This class would share most of its methods with the existing Etherscan implementation, with the key difference being the absence of the `api_key` option requirement. Further enhancements can be discussed in separate issues.

If agreed upon, we may work on the corresponding PR with your guidance on how you see that implemented.

**Comment by alcuadrado** [comment]
Hi @rimrakhimov,

We discussed this internally and it looks like something we'd be open to add to the hardhat-verify plugin. We don't have the bandwidth to do it ourselves right now. Will you be open to send a PR?

If so, I think we can start with you providing a list of changes that you think are needed, both at the product/functional level, and technical level. Then we can go through it, and provide feedback and technical guidance.

**Comment by rimrakhimov** [comment]
Hi @alcuadrado, I have the capacity to work on that PR now.

From a functional point of view, I see it this way:

1. Add a new verification provider inside the `hardhat.config` with fields identical to `Etherscan` except for the `apiKey` value, which can be added but is not required to verify the contracts.
2. For the provider, do not require `constructorArguments` during verification, as they are not used by Blockscout anyway.
3. Inside the provider, have a list of the main natively supported networks (e.g., we can add instances hosted by us (Blockscout) ourselves). This way, users can easily enable Blockscout verification for the main networks.
Also, consider adding those supported networks somewhere inside `--list-networks`, or adding a new `--list-blockscout-networks` option.
4. It would be nice if we could enable both Etherscan and Blockscout providers by default and send verification requests to both of them if the corresponding network is supported by both. Consider cases where only one supports the network as not an error for the other.

I've looked over the codebase a little, and my initial suggestion is to add a new Blockscout verification provider which internally uses the Etherscan provider for the main requests (`isVerified`, `verify`, `getVerificationStatus`). This approach prevents duplicating requests to Etherscan-like endpoints and allows for easy updates to Blockscout-specific versions later if required. The same approach may be used with separate Blockscout verification tasks.

**Comment by schaable** [comment]
Released in [@nomicfoundation/hardhat-verify@2.0.11](https://github.com/NomicFoundation/hardhat/releases/tag/%40nomicfoundation%2Fhardhat-verify%402.0.11).
