### ISSUE TITLE
Incorrect HardhatNetworkAccountsUserConfig Type

### ISSUE THREAD

**Issue by zitup** [NomicFoundation/hardhat#5244]
### Version of Hardhat

2.22.4

### What happened?

accounts of hardhat.config must be `HardhatNetworkAccountsUserConfig` type when setting hardhat netowrk, but for other networks such as `arbitrumSepolia`, you should set it to `string[]`, or this error will show up
```
Error HH8: There's one or more errors in your config file:

  * Invalid account: #0 for network: arbitrumSepolia - Expected string, received object
```
What is weried is network url refres to `HttpNetworkUserConfig.url`, but accounts refres to `HardhatUserConfig.accounts`. 

### Minimal reproduction steps

1. npx hardhat init
2. set different account
3. deploy

**Comment by ChristopherDedominici** [comment]
Hi @zitup, thanks for opening the issue.
I'm not sure I understand what the problem is. This behavior is expected, as you can see from the docs: https://hardhat.org/hardhat-runner/docs/config

**Comment by zitup** [comment]
Sorry, it has been a while, and I am not sure if it is a problem with vscode or a type mismatch with hardhat. I will do more research. Before that, I will close the issue.
