### ISSUE TITLE
Getting "TypeError: module.futures is not iterable" on Standard Upgradeable Contract when Deploying

### ISSUE THREAD

**Issue by JF0001** [NomicFoundation/hardhat#5262]
### Version of Hardhat

2.22.4

### What happened?

I have this Openzeppelin Upgradeable contract (extract shown), created using the utility found at the following link: https://wizard.openzeppelin.com/

```
contract MyToken is Initializable, ERC20Upgradeable, ERC20BurnableUpgradeable, ERC20PausableUpgradeable, OwnableUpgradeable, UUPSUpgradeable {
    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor() {
        _disableInitializers();
    }

    function initialize(address initialOwner) initializer public {
        __ERC20_init("MyToken", "MTK");
        __ERC20Burnable_init();
        __ERC20Pausable_init();
        __Ownable_init(initialOwner);
        __UUPSUpgradeable_init();
    }
...
} 
```

I have this deployment script:

```
const { ethers, upgrades } = require("hardhat");

async function main() {
    // Define initial parameters
    const initialOwner = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266";

    // Get contract factory
    const MyToken = await ethers.getContractFactory("MyToken");

    // Deploy proxy with initialization parameters
    const myToken = await upgrades.deployProxy(MyToken, [initialOwner], {
        initializer: "initialize",
    });

    await myToken.deployed();
}

main()
    .then(() => process.exit(0))
    .catch(error => {
        console.error(error);
        process.exit(1);
    });
```

When I run this command after compiling, npx hardhat ignition deploy ./ignition/modules/MyToken.js --network localhost

I get this error: 

```
TypeError: module.futures is not iterable
    at getFuturesFromModule (/node_modules/@nomicfoundation/ignition-core/src/internal/utils/get-futures-from-module.ts:8:21)
    at validate (/node_modules/@nomicfoundation/ignition-core/src/internal/validation/validate.ts:27:39)
    at deploy (/node_modules/@nomicfoundation/ignition-core/src/deploy.ts:92:42)
    at SimpleTaskDefinition.action (/node_modules/@nomicfoundation/hardhat-ignition/src/index.ts:302:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Environment._runTaskDefinition (/node_modules/hardhat/src/internal/core/runtime-environment.ts:359:14)
    at Environment.run (/node_modules/hardhat/src/internal/core/runtime-environment.ts:192:14)
    at main (/node_modules/hardhat/src/internal/cli/cli.ts:323:7)
```

My package.json file contains the following:

  "devDependencies": {
    "@nomicfoundation/hardhat-ethers": "^3.0.5",
    "@nomicfoundation/hardhat-ignition-ethers": "^0.15.3",
    "@nomicfoundation/hardhat-toolbox": "^5.0.0",
    "@openzeppelin/hardhat-upgrades": "^3.1.0",
    "ethers": "^6.12.1",
    "hardhat": "^2.22.3"
  },
  "dependencies": {
    "@openzeppelin/contracts": "^5.0.2",
    "@openzeppelin/contracts-upgradeable": "^5.0.2"
  }

If I do not use an upgradeable contract, the contract deploys without any issue, confirming that all the proper libraries and plug-ins have been installed.

### Minimal reproduction steps

Please see above.

### Search terms

TypeError: module.futures is not iterable Hardhat Upgradeable Contract

**Comment by kanej** [comment]
The upgrade script above is a `./script` and should be invoked with `npx hardhat run`. It is not a Ignition module which is a separate deployment system.

Try moving the deployment upgrade script under a `./scripts` folder and running it with:

```sh
npx hardhat run ./script/upgrade.js --network localhost
```

**Comment by JF0001** [comment]
Got it! Thank you very much @kanej Have a Wonderful day!
