### ISSUE TITLE
Nx/Hardhat Plugin

### ISSUE THREAD

**Issue by thachp** [NomicFoundation/hardhat#5280]
The Nx-Console is a powerful tool that enhances the development experience for Nx workspaces. Currently, Nx supports various plugins such as nx/next and nx/nest, which provide seamless integration and a set of commands for managing Next.js and Nest.js projects, respectively. To extend this functionality and support blockchain development workflows, I propose the addition of a plugin for Hardhat, to support development environment for Ethereum software.

I request the development of an Nx/Hardhat plugin that integrates Hardhat into Nx workspaces. This plugin should offer commands and functionalities similar to existing Nx plugins, streamlining the process of creating, building, testing, and deploying smart contracts within an Nx workspace.

### Acceptance Criteria

- [ ] Command Initialization
	•	The plugin should provide a command to initialize a new Hardhat project within an Nx workspace.
	•	The command should scaffold a basic Hardhat project structure including configurations, scripts, and directories.
	•	Example: nx generate hardhat:init <project-name>
- [ ] Smart Contract Management
	•	The plugin should allow the creation of new smart contract files with boilerplate code.
	•	Example: nx generate hardhat:contract <contract-name>
- [ ] Compilation
	•	The plugin should provide a command to compile smart contracts.
	•	The command should output the compiled artifacts in a specified directory within the workspace.
	•	Example: nx run <project-name>:compile
- [ ] Testing
	•	The plugin should offer commands to run Hardhat tests.
	•	It should support both unit tests and integration tests for smart contracts.
	•	Example: nx run <project-name>:test
- [ ] Deployment
	•	The plugin should include commands for deploying smart contracts to various Ethereum networks (e.g., local, testnet, mainnet).
	•	Example: nx run <project-name>:deploy --network <network-name>
- [ ] Configuration
	•	The plugin should allow configuration of Hardhat settings within the Nx workspace (e.g., networks, compiler settings).
	•	Example: nx run <project-name>:configure
- [ ] Documentation and Help
	•	The plugin should provide detailed documentation and help commands for each functionality.
	•	Example: nx run <project-name>:help
- [ ] Integration with Existing Nx Functionality
	•	The plugin should integrate with existing Nx workspace functionalities such as affected commands, caching, and parallel execution.
	•	It should support the Nx project graph visualization, showing dependencies between Hardhat projects and other Nx projects.
	

### Search terms

nx console, nx workspace

Similar request has been made with the NX Team (https://github.com/nrwl/nx/discussions/26138)

**Comment by alcuadrado** [comment]
Thanks for putting this issue together. Unfortunately, we aren't interested in developing such a plugin at the moment. If you built it yourself, we may be able to provide support around hardhat-specific interactions with the package manager and best practices around it.
