### ISSUE TITLE
error TS2339: Property 'emit' does not exist on type 'Assertion'.

### ISSUE THREAD

**Issue by jwbda** [NomicFoundation/hardhat#5281]
### Version of Hardhat

2.22.4

### What happened?

I did't change test/Lock.ts file, when I run `tsc --build .`, there is error show bellow:
error TS2339: Property 'emit' does not exist on type 'Assertion'.

76                 await expect(h.callByInstance()).to.emit(h, "Message").withArgs(aVar);
![image](https://github.com/NomicFoundation/hardhat/assets/158557429/6e198af6-0cd0-416e-b2ec-5511cee40637)

### Minimal reproduction steps

Sorry, this problem sometimes show, sometimes not.

### Search terms

`error TS2339: Property 'emit' does not exist on type 'Assertion'. `, `TS2339`

**Comment by jwbda** [comment]
Hi, @schaable  if I want to solve this problem, what pre knowledge do I need to learn?

**Comment by itev4n7** [comment]
Make sure you have the './test' folder in include array of tsconfig
example:
{
  "compilerOptions": {
    "target": "es2020",
    "module": "commonjs",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "resolveJsonModule": true
  },
  "include": ["./hardhat.config.ts", "./scripts", "./test"],
  "files": ["./hardhat.config.ts"]
}

**Comment by alcuadrado** [comment]
I believe @itev4n7's suggestion is correct. On top of that, make sure to import the chai matches plugin.

I'm closing it, as I think this resolves it, but pleas feel free to reopen it.
