### ISSUE TITLE
Automatically close `needs-more-info` issues after 2 weeks

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat#5306]
We want to auto-close issues that have moved to `needs-more-info`, but there is no follow up. These are usually support cases.

## TODO

- [ ] Put together a useful comment for this case
- [ ] Investigate the github api to determine how we query for these characteristics

**Comment by sisco0** [comment]
The GitHub API does not provide direct filtering by `updated_at` in the request parameters, but you can retrieve issues and then filter them based on the updated_at field in your code.
Example URL that filters issues by `status:needs-more-info` label:
https://api.github.com/repos/NomicFoundation/hardhat/issues?labels=status:needs-more-info&state=open

**Comment by alcuadrado** [comment]
I thought this would be possible with github actions

**Comment by sisco0** [comment]
I agree @alcuadrado .
The current goal could be also achieved by the usage of a _cron_ scheduled Github Actions Workflow.
I would provide a test Pull Request for such functionality for your evaluation.
