### ISSUE TITLE
Block number persists between tests

### ISSUE THREAD

**Issue by hexcowboy** [NomicFoundation/hardhat#5355]
### Version of Hardhat

2.22.5

### What happened?

Using the viem test client, the block number persists between tests instead of resetting to 0.

### Minimal reproduction steps

```ts
import { expect } from "chai";
import hre from "hardhat";

describe("Block Number Test", function () {
  it("should have block number 1 initially", async function () {
    const client = await hre.viem.getPublicClient();
    const block = await client.getBlock();
    expect(block.number).to.equal(0n);

    const testClient = await hre.viem.getTestClient();
    await testClient.mine({ blocks: 20 });
  });

  it("should have block number 1 in a new test", async function () {
    const client = await hre.viem.getPublicClient();
    const block = await client.getBlock();
    expect(block.number).to.equal(0n);
  });
});
```

### Search terms

viem test client block number

**Comment by alcuadrado** [comment]
This is the default behavior of hardhat, you can reset on a `beforeEach` with this method: https://hardhat.org/hardhat-network-helpers/docs/reference#takesnapshot()

**Comment by alcuadrado** [comment]
Closing this issue as resolved, but feel free to reopen if you think there's a bug.
