### ISSUE TITLE
Environment variable for task parameters

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat#5361]
We should support global parameters being passed as environment variables:

See the [Hardhat docs for full details](https://hardhat.org/hardhat-runner/docs/reference/environment-variables).

```sh
> NETWORK=sepolia hardhat run ./scripts/my-script.js
```

**Comment by alcuadrado** [comment]
Replaced by https://github.com/NomicFoundation/hardhat/issues/5379
