### ISSUE TITLE
error while verifying the smart contract on polygon-amoy network 

### ISSUE THREAD

**Issue by block98ct** [NomicFoundation/hardhat#5374]
You can manually add support for it by following these instructions: https://hardhat.org/verify-custom-networks

To see the list of supported networks, run this command:

  npx hardhat verify --list-networks
hardhat-verify found one or more errors during the verification process:

Etherscan:
Trying to verify a contract in a network with chain id 80002, but the plugin doesn't recognize it as a supported chain.

You can manually add support for it by following these instructions: https://hardhat.org/verify-custom-networks

To see the list of supported networks, run this command:

  npx hardhat verify --list-networks
  
  
  i have checked the list networks but there is no polygon-amoy network

**Comment by schaable** [comment]
Polygon Amoy is indeed a supported network, so you don't need to add it as a custom network. See [here](https://github.com/NomicFoundation/hardhat/blob/53c422c042a527930cae6b5d8cb748bbdbe51b44/packages/hardhat-verify/src/internal/chain-config.ts#L214).

If you run `hh verify --list-networks`, you'll see:
![image](https://github.com/NomicFoundation/hardhat/assets/1165424/4cffbe15-961a-43ab-a061-0e9c600a162b)

It was added in [version 2.0.7](https://github.com/NomicFoundation/hardhat/releases/tag/%40nomicfoundation%2Fhardhat-verify%402.0.7) of the `hardhat-verify` plugin. Maybe you're using an older version?
