### ISSUE TITLE
Complete the implementation and testing of global paramters

### ISSUE THREAD

**Issue by alcuadrado** [NomicFoundation/hardhat#5379]
This issue is to track the global parameter's functionality implementation in core.

They are implemented [here](https://github.com/NomicFoundation/hardhat/blob/3a3de6b20ca9a566e6715e87c7081a07b5c60323/v-next/core/src/internal/global-parameters.ts), but there are some missing parts of its functionality, and it's not tested.

## Missing functionality
- [x] `buildGlobalParameterDefinition`, which is a function to create the config values used to define a new global parameter, should validate its options. 
- [x] `buildGlobalParameterMap`, which reduces those definitions into the actual map into the internal representation of the global params, needs to validate them again (see the comments).
- [x] `resolveGlobalArguments` should try to fetch every missing global parameter value from the env variables. See below.

### Getting global parameters from env variables

You can pass global parameters to hardhat as `--my-global-parameter value` in the CLI, or as an env variable with `HARDHAT_MY_GLOBAL_PARAMETER=value`. The CLI version has presedence over the env variables.

**Comment by schaable** [comment]
@alcuadrado 

The `resolveGlobalArguments` function receives the `globalParametersMap`. I assume this is to validate that the global argument names do not clash with any global parameter names, correct?

> The CLI version has presedence over the env variables.

Should we throw an error if a global argument is passed through the CLI and is also defined as an environment variable?
