### ISSUE TITLE
Docs: Setting up the Environment uses node v22 but warning is produced on usage

### ISSUE THREAD

**Issue by seekayel** [NomicFoundation/hardhat#5407]
### Version of Hardhat

2.22.5

### What happened?

I followed the `2. Setting up the Environment` steps for MacOS (https://hardhat.org/tutorial/setting-up-the-environment) which instructed me to use nvm with node v22. When I then tried `npx hardhat init` in [3. Creating a new Hardhat project](https://hardhat.org/tutorial/creating-a-new-hardhat-project#3.-creating-a-new-hardhat-project) it gave me the following warning:

```
WARNING: You are currently using Node.js v22.3.0, which is not supported by Hardhat. This can lead to unexpected behavior. See https://hardhat.org/nodejs-versions
```

I can open a PR to downgrade docs to instruct newbies to use Node.js v20 if that is the correct fix until 2024-10-29 when v22 goes from `CURRENT` to `LTS` (https://github.com/nodejs/Release)

Also, willing to open PR on hardhat cli to correct the warning message if given some direction as to where/how.

### Minimal reproduction steps

```
nvm install 22
nvm use 22
npm install hardhat
npx hardhat init
```

**Comment by kanej** [comment]
Hey @seekayel, this is an artifact of our release process. The docs have been updated before the Hardhat release with support for v22 has happened.
