### ISSUE TITLE
Signers not working in Ignitioin/modules/abc.js files

### ISSUE THREAD

**Issue by yazibshah** [NomicFoundation/hardhat#5462]
### Describe the feature

const { buildModule } = require("@nomicfoundation/hardhat-ignition/modules");
const {ethers}=require("hardhat")

const multiSigWallet= buildModule("MultiSigWallet", async(m) => {
  // let owner1;
  // let owner2;
  // let owner3;
   let owners;
  // [owner1, owner2, owner3]=await ethers.getSigners()
  owners=["0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266","0x70997970C51812dc3A010C7d01b50e0d17dc79C8","0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"]
  const multiSig = m.contract("MultiSig",[owners,2]);
  console.log(multiSig.contractName)
  return { multiSig };
});

module.exports = multiSigWallet;

i have tried many with different ways but signers not working in sight buildModuler aslo callback func don't accept async javascript.

please  how can use signers in this callback 
and why I can't use async javascrpt.

### Search terms

i have tried many with different ways but signers not working in sight buildModuler aslo callback func don't accept async javascript.  please  how can use signers in this callback  and why I can't use async javascrpt.

**Comment by kanej** [comment]
Hey @yazibshah, you are using Ignition here, you can find our Ignition docs here: https://hardhat.org/ignition/docs/getting-started#overview

An Ignition module is invoked at the command line with the `ignition deploy` task, so something like:

```
npx hardhat ignition deploy ./modules/abc.js
```

This will deploy your multisig against your local node. You can access the accounts defined in your Hardhat config with `getAccount`: https://hardhat.org/ignition/docs/guides/creating-modules#deploying-and-calling-contracts-from-different-accounts

Assuming the first arg of the contract constructor is an array of owner addresses, maybe something like:

```js
const { buildModule } = require("@nomicfoundation/hardhat-ignition/modules");

const multiSigWallet= buildModule("MultiSigWallet", async(m) => {
  let owner1 = m.getAccount(0);
  let owner2 = m.getAccount(1);
  let owner3 = m.getAccount(2);

  const multiSig = m.contract("MultiSig",[ [owner1, owner2, owner3], 2]);
 
  return { multiSig };
});

module.exports = multiSigWallet;
```
