### ISSUE TITLE
when i am trying to deploy smart contract on polygon-amoy i am getting error

### ISSUE THREAD

**Issue by block98ct** [NomicFoundation/hardhat#5475]
npx hardhat run --network polygon-amoy scripts/deploy_upgrade.js
    ^^^^^^^

SyntaxError: Unexpected identifier 'hardhat'

npx hardhat compile working fine

 npx --version
10.8.1

npx hardhat --version
2.22.6

**Comment by kanej** [comment]
Hey @block98ct, the `Unexpected identifier 'hardhat` probable refers to a usage of `hardhat` in the `deploy_upgrade.js` script not on the command line.

**Comment by block98ct** [comment]
@kanej  thanks for the reply 
i am getting another issue while deploying smart contract on bsc network

const { ethers, upgrades } = require("hardhat");
async function main() {
  // CONTRACT DEPLOYER
  const [deployer, deployer1, deployer2, deployer3, deployer4, deployer5, deployer6, deployer7] = await ethers.getSigners();
  console.log(`Deployer account E66 ${deployer5.address}`);

  const balance = await ethers.provider.getBalance(deployer5.address);
  console.log(`Deploying contracts with the account: ${deployer5.address}`);
  console.log(`The balance of account: ${balance}`);
  

  const Token = await ethers.getContractFactory("BTS20")  
  const token = await upgrades.deployProxy(Token, [deployer5.address])
  await token.waitForDeployment()
  console.log(`Token contract deployed to : ${await token.getAddress()}`);

  
}
main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.info("check");
    console.log(error);
    process.exit(1);
  });
  
This is my deployment script. When I try to deploy the smart contract on the BSC network, it gives an 'insufficient balance' error, but I have enough balance to deploy the smart contract.


  Deployer account E66 0x91CCB0C9686a756EB2326afD4E11fdc40e3b0E66
Deploying contracts with the account: 0x91CCB0C9686a756EB2326afD4E11fdc40e3b0E66
The balance of account: 13300000000000000
check
ProviderError: insufficient funds for gas * price + value: balance 0, tx cost 1690420001690420, overshot 1690420001690420


and why it showing 0 balance, I have balance of 13300000000000000

**Comment by kanej** [comment]
I would look on the OpenZeppelin forums for help with OpenZeppelin's upgradable contracts plugin. Maybe `upgrades.deployProxy` is running under the deployer account even though the owner is being set to `deployer5.address`.

**Comment by block98ct** [comment]
@kanej but it deployed on sepolia and polygon-amoy networks
