### ISSUE TITLE
Support using hardhat-verify package without depending on main hardhat package

### ISSUE THREAD

**Issue by numtel** [NomicFoundation/hardhat#5487]
### Describe the feature

I am creating a project called circuitscan.org which needs to submit Solidity sources to Etherscan, Sourcify, and (soon) Blockscan for contract verification. In order to not duplicate efforts, I've used the `hardhat-verify` package but don't want to pull in the main `hardhat` package when it's not really needed.

To work around this, I've created a stub package that can fill in for hardhat: https://github.com/numtel/hardhat-plugin-noop

While this works, it would be nice to have have to do this kind of workaround. If there's interest in this, I could prepare a PR.

**Comment by schaable** [comment]
Hi @numtel, thanks for submitting this issue. I understand the value of having a general-purpose verification library. However, the `hardhat-verify` plugin is designed as a core Hardhat plugin and assumes it is running within the context of a Hardhat project. Changing it to function as a general verification library is not within our current scope, but we may reconsider this in the future.
