### ISSUE TITLE
Need Boilerplate for Starter & Programmers

### ISSUE THREAD

**Issue by 0xapp123** [NomicFoundation/hardhat#5488]
### Describe the feature

Hi, I love working with Hardhat for Solidity code building.
When I start to build Solidity code, then I always followed the tutorials of your docs.

I have some newbies in my team. for them, it would be good to use boilerplate.

I think you can provide boilerplate for starters.

Thanks

### Search terms

boilerplate, newbie, starters, solidity

**Comment by ChristopherDedominici** [comment]
Hi @0xapp123, thanks for reaching out.
We already provide boilerplate code; for example, with the '[hardhat init](https://hardhat.org/tutorial/creating-a-new-hardhat-project)' command, you can create sample projects that include examples of smart contracts, tests, and explanations on how to deploy to live networks.
In addition, we also have [this boilerplate](https://github.com/NomicFoundation/hardhat-boilerplate).

**Comment by ChristopherDedominici** [comment]
Closing it because it has been inactive for more than 2 weeks
