### ISSUE TITLE
IgnitionError: IGN1

### ISSUE THREAD

**Issue by Abhishekkochar** [NomicFoundation/hardhat#5497]
Encountering the below error when trying to run the following code:

````
import { buildModule } from "@nomicfoundation/hardhat-ignition/modules";

const NFTModule = buildModule("Doodle", (m) => {
  const _name = m.getParameter("_name", "Doodle");
  const _symbol = m.getParameter("_symbol", "DD");
  const _oracle = m.getParameter("_oracle", 0xA2F78ab2355fe2f984D808B5CeE7FD0A93D5270E); // USDC/USD - Seploia testnet price oracle
  
  const _tokenAddress = m.getParameter("_tokenAddress", 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48); // USDC - Seploia testnet

  const doodleNft = m.contract("Doodle", [_name, _symbol, _oracle, _tokenAddress]);

  return { doodleNft };
});

export default NFTModule;
````

Error when running `npx hardhat ignition deploy ./ignition/modules/Doodle.ts --network sepolia --verify`
<img width="1465" alt="Screenshot 2024-07-09 at 2 31 43 PM" src="https://github.com/NomicFoundation/hardhat/assets/43106142/d329fd11-1888-407a-82ab-6c99d2719567">

Solidity code:
```
 constructor(string memory _name, string memory _symbol, address _oracle, address _tokenAddress) ERC721(_name, _symbol){
        oracle = IOracle(_oracle);
        supportedToken = IERC20(_tokenAddress);
    }

```

**Comment by kanej** [comment]
I would express the addresses as strings:

```js
"0xA2F78ab2355fe2f984D808B5CeE7FD0A93D5270E"
```

Does the deployment fail on first run?
Does the deployment fail when run against the in-memory Hardhat node?

**Comment by Abhishekkochar** [comment]
> I would express the addresses as strings:
> 
> ```js
> "0xA2F78ab2355fe2f984D808B5CeE7FD0A93D5270E"
> ```
> 
> Does the deployment fail on first run? Does the deployment fail when run against the in-memory Hardhat node?

Deployment succeeds when running on local node. I had to delete the deployment copy to have this work.
