### ISSUE TITLE
IMO, typescript support is somewhat magical and brittle

### ISSUE THREAD

**Issue by jtremback** [NomicFoundation/hardhat#550]
This may just be an issue of me misunderstanding the documentation, but the docs say 

`Buidler detects if typescript and ts-node are installed in its npm project, and automatically enables TypeScript support.`

I didn't know this when I started my project the first time, and so I have now re-initialized the project to make sure that I'm able to get typescript working smoothly by following the instructions to the letter.

I was thinking it might be more convenient for people if typescript was an option in the project initialization instead of being something that is automagically detected from the installed modules.

**Comment by alcuadrado** [comment]
Thanks for your feedback, again, @jtremback! We really appreciate it.

> if typescript was an option in the project initialization

Can you elaborate on what you mean by this?

**Comment by jtremback** [comment]
When you type `npx buidler` it has a list of options in a menu. It would be cool if one of these options was "do you want to use typescript", and if you said yes, it would get the project set up for typescript with all the right files etc

**Comment by alcuadrado** [comment]
Ohh, got it! Great idea!

/cc @viarnes

**Comment by esemeniuc** [comment]
I'd love to see a typescript sample project when making a new project

**Comment by fvictorio** [comment]
This has been supported for a while now.
