### ISSUE TITLE
Smart contract verification error

### ISSUE THREAD

**Issue by sarwat77** [NomicFoundation/hardhat#5521]
I made a smart contract with Remix, it's working fine as a smart contract but this the error on verification in BscScan.

ParserError: Expected pragma, import directive or contract/interface/library/struct/enum/constant/function/error definition.
 --> myc:1:1:
  |
1 | 6080604052348015600e575f80fd5b506128f58061001c5f395ff3fe60 ...
  | ^^^^^^^^^^^^^^^^^^^^^^^

**Comment by schaable** [comment]
Hi @sarwat77, thanks for submitting this issue. Would you be able to share with us the smart contract you're trying to verify?

**Comment by schaable** [comment]
I'm closing this issue due to a lack of response, but I'm happy to reopen it if you can provide more information.
