### ISSUE TITLE
wrong path in Lock.js for hardhat-network-helpers

### ISSUE THREAD

**Issue by gilseg10** [NomicFoundation/hardhat#5547]
### Version of Hardhat

2.22.6

### What happened?

I tried to run npx hardhat test and I got errors. Turns out that the location of hardhat-network-helpers is not as specified in Lock.js

### Minimal reproduction steps

Instead of:
`const {
  time,
  loadFixture,
} = require("@nomicfoundation/hardhat-toolbox/network-helpers");`

Should be: 
`const {
  time,
  loadFixture,
} = require("@nomicfoundation/hardhat-network-helpers");`

**Comment by schaable** [comment]
Hi @gilseg10!

The `hardhat-toolbox` re-exports the network helpers from [/src/network-helpers.ts](https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-toolbox/src/network-helpers.ts). I just double-checked and `npx hardhat test` runs without issues on my end.

Could you please share the error you're seeing? Additionally, have you made any modifications to your `Lock.js` file?

**Comment by schaable** [comment]
I'm closing this for bookkeeping purposes, but if you can provide the requested details, please let us know, and we’ll reopen it. Thanks!
