### ISSUE TITLE
Port base providers

### ISSUE THREAD

**Issue by alcuadrado** [NomicFoundation/hardhat#5549]
We should port over the base providers that we know we'll use in v3, including their tests and public types.

They are:

- [x] `HttpProvider`
- [x] The backward compatibility provider wrapper
- [ ] `ProviderWrapper`, which I believe @fvictorio discovered it's buggy.
- [ ] The gas-related providers
- [ ] The accounts-related providers

Some things to note:

- They should now use our utils package
- They shouldn't use ethereumjs dependencies, in favor of paul miller's.

**Comment by kanej** [comment]
This has been replaced by #5719.
