### ISSUE TITLE
Feature Request: support https imports

### ISSUE THREAD

**Issue by thegostep** [NomicFoundation/hardhat#557]
Would be nice for the compiler to support fetching files from github.
```solidity
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol";
```
I believe Embark has a compiler for this

**Comment by cameel** [comment]
This could be simulated with [Import Remapping](https://docs.soliditylang.org/en/latest/path-resolution.html#import-remapping). The compiler already has a feature that lets you tell it that `https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol` is actually `@openzeppelin/contracts/token/ERC20/ERC20.sol`. This would also solve the niche use case from #1014.

Another way to do this that is already supported by the compiler is a custom [Import Callback](https://docs.soliditylang.org/en/latest/path-resolution.html#import-callback). The advantage of this is that it would not require the user to explicitly say where the file is - the compiler would just ask Hardhat to provide file content and Hardhat could download it in the background. The downside is that only the [JavaScript interface lets you provide a callback](https://github.com/ethereum/solc-js#high-level-api) so this would not work with native compiler binaries via the `--standard-json` option.

**Comment by alcuadrado** [comment]
To give more context: we are not sure we want to add this feature, as it can lead to unreproducible builds, and can also be seen as a security risk.

**Comment by cameel** [comment]
Right. This is exactly why it's not supported out of the box by the default callback built into the compiler. It's still something one could want though and some tools do support it (Remix) so I just wanted to add some info on the compiler side of things in case you wanted to go through with it.

**Comment by fvictorio** [comment]
Closing this because I think it's unlikely we'll do it.
