### ISSUE TITLE
Facing issue while verifying contract 

### ISSUE THREAD

**Issue by shubhamkr95** [NomicFoundation/hardhat#5581]
### Version of Hardhat

2.22.2

### What happened?

While verifying the address on Amoy testnet network using hardhat verify. It was throwing error
``` 
An unexpected error occurred during the verification process.
Please report this issue to the Hardhat team.
Error Details: Unexpected token i in JSON at position 0

hardhat-verify found one or more errors during the verification process:

Etherscan:
Etherscan API call failed with status 415, response: invalid content type, only application/json is supported
```

### Minimal reproduction steps

 Added the amoy  network  in hardhat.config.js
  ```
 etherscan:{
    apiKey: process.env.POLYGONSCAN_KEY,
    customChains: [
      {
        network: "amoy",
        chainId: 80002,
        urls: {
          apiURL: `https://rpc-amoy.polygon.technology`,
          browserURL: "https://amoy.polygonscan.com/"
        }
      },
    ],
  },
  ```

**Comment by schaable** [comment]
Hi @shubhamkr95,

It looks like there's an issue with your `apiURL`. It seems you're using an RPC URL, but you should be using the API URL provided by PolygonScan. You can find more details [here](https://docs.polygonscan.com/v/amoy-polygonscan).

The correct URL to use would be: https://api-amoy.polygonscan.com/api

Hope this helps! Let me know if you have any questions.
