### ISSUE TITLE
Simulating the transaction failed with error: Reverted without reason

### ISSUE THREAD

**Issue by DongAoMainland** [NomicFoundation/hardhat#5588]
### Version of Hardhat

2.22.8

### What happened?

When I deploy the contract,  I get the error:
[ ATBTokenModule ] failed ⛔

Futures failed during execution:
 - ATBTokenModule#ATBToken: Simulating the transaction failed with error: Reverted without reason

To learn how to handle these errors: https://hardhat.org/ignition-errors

### Minimal reproduction steps

Just the command:
npx hardhat ignition deploy ./ignition/modules/ATBToken.js --network tbsc

**Comment by kanej** [comment]
Hey @DongAoMainland, this is expected behaviour. It means the deployment transaction ran Solidity code that reverted.

I would check the constructor of the ATBToken to determine what code was being executed. You should also try it against a local hardhat node to see if that gives more information.

**Comment by DongAoMainland** [comment]
Hi @kanej , the issue is resolved.
The rootcase is the the contract call the pancake router v2. but use the wrong address.
Thank you!
