### ISSUE TITLE
Error `Definition of base has to precede definition of derived` when verifying code on polygonscan amoy

### ISSUE THREAD

**Issue by doerfli** [NomicFoundation/hardhat#5656]
### Version of Hardhat

2.22.8

### What happened?

# Error description
I deployed the project on polygon amoy testnet and when running code verification i get the error `Definition of base has to precede definition of derived`. 
Since compilation and deployment worked without a hitch, i would expect code verification to work as well since this type of error should also pop up during compilation. 

# Background: 
The contract `RiskSet` (https://github.com/etherisc/gif-next/blob/bugfix/circular-dependency-riskset/contracts/instance/RiskSet.sol) inherits from the contract `ObjectSet` (https://github.com/etherisc/gif-next/blob/bugfix/circular-dependency-riskset/contracts/instance/base/ObjectSet.sol). `ObjectSet` has a internal member `_instance` which is of type `IInstance` (https://github.com/etherisc/gif-next/blob/bugfix/circular-dependency-riskset/contracts/instance/IInstance.sol) which has a dependency on `RiskSet`. 

When running `hh compile` everything compiles and is deployable without further issues (script `hh run scripts/deploy_gif.ts`). **But** when I deployed on Polygon Amoy and started a code verification, i got the error `Definition of base has to precede definition of derived` when verifying contract `TargetManagerLib` (https://github.com/etherisc/gif-next/blob/bugfix/circular-dependency-riskset/contracts/staking/TargetManagerLib.sol) which through some other contract depends on `RiskSet`. If found this very peculiar and it took me a long time to figure out what was wrong, but in the end when opening the contract `RiskSet` in VSCode (use devcontainer of the project to reproduce easily) i saw the error message locally too (`Definition of base has to precede definition of derived`). But only as a red underlined error in the VSCode ui, not as a compiler error from `hh compile`.
After some back and forth i detected above mentioned circular dependency and then i was able to resolve it. 

I am unsure if this is a bug in the compiler or if this is just some state that would warrant a warning and polygonscan complains about this and shouldn't. It really confused me and that why i decided to open up an issue and hope you can give me some insight on this? Is there maybe a configuration that would allow me to detect such errors locally using the compiler too? 

Please let me know if you need any more information or if there is any way i can further support with analysing the issue. 

Thanks for your insight and help. 

PS yes, i know the code base is huge and therefor its really hard to strip it down to a small example that is easily read, but i hope by mentioning the 4 contracts that product the loop you can still understand it. 

### Minimal reproduction steps

1. Checkout repository https://github.com/etherisc/gif-next and switch to branch `bugfix/circular-dependency-riskset`
2. Run deployment via `hh run scripts/deploy-gif.ts --network polygonAmoy`
3. Open up file `deployment/80002/verification_queue.json` and delete all objects in the array before the one that contains the field `"contractName": "TargetManagerLib"` (this will force the problem to happen immediately, otherwise many libraries will be verified before that take a long time)
4. Start verification of deployed code via `hh run scripts/verify_deployment.ts --network polygonAmoy`
5. This will fail when verifying contract `TargetManagerLib` with error `Definition of base has to precede definition of derived`

### Search terms

verification verified source polygonscan Definition of base

**Comment by kanej** [comment]
> But only as a red underlined error in the VSCode ui, not as a compiler error from hh compile.

Which VSCode extension is the error coming from?

Our expectation is any error coming from solc, would also show up in `hh compile`.

**Comment by schaable** [comment]
I'm closing this for bookkeeping purposes, but if you can provide the requested details, please let us know, and we’ll reopen it. Thanks!
