### ISSUE TITLE
Add validations for `HardhatUserConfig.paths`

### ISSUE THREAD

**Issue by zoeyTM** [NomicFoundation/hardhat#5665]
The `paths` field was added in parallel with the config validations and slipped through the cracks of being included. We should add some simple validations for them inside `v-next/core/src/internal/config-validation.ts` (probably in the `collectValidationErrorsForUserConfig` function)

**Comment by Tmthang1601** [comment]
Hi @zoeyTM , I cant find any collectValidationErrorsForUserConfig function in config-validation.ts, Can you explain the issue more clearly, I really wanna do it

**Comment by Tmthang1601** [comment]
Hi, I have added validation checks for the paths field in the collectValidationErrorsForUserConfig function. Specifically:

- Check if paths is an object.

- For each path in paths:

1. Check if it is a string.

2. Check if it is an absolute path.

3. Check if the path exists.

Validation errors will be added to the validationErrors array if any of these checks fail.

I am planning to create a pull request for you to review, and I look forward to your feedback as I am eager to have my PR successfully merged.
