### ISSUE TITLE
The `punycode` module is deprecated in NodeJS v22, impacting @nomiclabs/hardhat-truffle5@2.0.7

### ISSUE THREAD

**Issue by barakman** [NomicFoundation/hardhat#5711]
### Version of Hardhat

2.22.10

### What happened?

Executing `hardhat test` yields the following printout:
> (node:66873) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)

The test-suite then continues to run normally.

### Minimal reproduction steps

Install:
- node v22.8.0
- npm v10.8.2 or yarn v1.22.22

In package.json, add the following dev-dependencies:
- `"@nomiclabs/hardhat-truffle5": "2.0.7"`
- `"@nomiclabs/hardhat-web3": "2.0.0"`
- `"hardhat": "2.22.10"`

Run `hardhat test`.

**Comment by iosh** [comment]
Hi Truffle has been archived project, you can migrate  Truffle to Hardhat.This warning currently does not affect your work. The simplest way to resolve this warning is to downgrade your Node.js version, for example, to Node 20.
