### ISSUE TITLE
Hardhat node - Automining produce extra blocks (sometimes)

### ISSUE THREAD

**Issue by zeGzD** [NomicFoundation/hardhat#5737]
### Version of Hardhat

3.0.0-beta.0

### **Statement**
Running an Hardhat node in automining seems to 'randomly' add extra blocks to the chain: it leads to stochastic behavior when running automated tests if the chain height and/or the gasprice/basefee matter.
This seems to be caused by the 'interval mining' if set to something else than 0: this side effect makes no sens and this parameter should simply be ignored if automining is enabled.

### **Workaround**
Setting the 'interval mining' to 0 solves the issue:
```
  before(async function () {
    await ethers.provider.send("evm_setAutomine", [true]);
    await ethers.provider.send("evm_setIntervalMining", [0]);
  });
```

### Minimal reproduction steps

I am currently running mocha tests by just running the command `npx hardhat test` (the same thing will happen using `npx hardhat coverage`) .

Here is are the relevant parts of my `hardhat.config.js`:
1. Hardhat node part
```
    defaultNetwork: 'hardhat',
    networks: {
        hardhat: {
            chainId: 1337,
            gas: 30000000,
            blockGasLimit: 0x1fffffffffffff,
            initialBaseFeePerGas: 20000000000,
            gasPrice: 'auto',
            mining: {
                auto: false,
                interval: 1000,
            },
        },
```
2. Mocha part
```
    mocha: {
        asyncOnly: true,
        jobs: 0,
        timeout: 1000000000,
    },
```

As you can see the automining of the Hardhat node is by default **disabled**.

Prior to run the tests I change this behavior of the node in order to enable the automining:
```
  before(async function () {
    await ethers.provider.send("evm_setAutomine", [true]);
  });
```

Trying to change the behavior of the node in this way seems unfortunately to not be enough.

Here is a comparison of some tests I simply ran twice (and that should be purely deterministic):
![image](https://github.com/user-attachments/assets/3c53fb7b-6f4a-452c-83a0-7cf8a4a301e6)
As you can see on the last test the 'Chain height' has changed for an unknown reason: the automining is inconsistent.

### Search terms

automine

**Comment by fvictorio** [comment]
> this side effect makes no sens and this parameter should simply be ignored if automining is enabled.

That's expected behavior. You can have both automining and interval mining enabled. I guess it's debatable if it makes sense or not (I personally think it does), but changing it would be a breaking change so not something we'd consider doing in v2.

**Comment by fvictorio** [comment]
Btw, just in case: the workaround is to send `evm_setIntervalMining` with 0 along with enabling automining.
