### ISSUE TITLE
Compile contracts outside of `/src` or `/contracts` directories

### ISSUE THREAD

**Issue by RohanNero** [NomicFoundation/hardhat#5760]
### Describe the feature

I am using `hardhat-viem` to generate type definitions for my smart contracts every time they are compiled, however, it only works for contracts inside of my `/src` directory (`/contracts`).

Since I have integrated Hardhat into my Foundry project, I have smart contracts inside my `/script` and `/test` directories as well. Specifically, I'd like to import one of my deploy scripts for testing. It's highly likely that I will create hardhat deploy scripts written in Javascript/Typescript to accompany the hardhat tests, but currently, since all of my deploy scripts are written in Solidity, it would be extremely convenient if I could directly use them in my hardhat Typescript tests.

I know a [similar issue](https://github.com/NomicFoundation/hardhat/issues/959) was also considered in 2020 and was given this code snippet as a part of a possible [solution](https://github.com/NomicFoundation/hardhat/issues/959#issuecomment-717291103): 

```js
subtask(
  TASK_COMPILE_SOLIDITY_GET_SOURCE_PATHS,
  async (_, { config }) => {
    const mainContracts = await glob(path.join(config.paths.root, "contracts/**/*.sol"));
    const testContracts = await glob(path.join(config.paths.root, "test/**/*.sol"));
    // and so on

    return [
      ...mainContracts,
      ...testContracts,
      // and so on
    ].map(path.normalize); // not sure if normalize is needed here
  }
);
```

However, since it is becoming more common for developers to use both Foundry and Hardhat in projects, it might also become more common for users to encounter this issue, see this [StackExchange post](https://ethereum.stackexchange.com/questions/139531/hardhat-multiple-folders-for-compilation) as an example. For this reason, I think it would be beneficial to include support for this natively.

### Search terms

compile artifacts types viem

**Comment by schaable** [comment]
Hi @RohanNero! The team is currently focused on Hardhat 3, but you could create a community plugin to achieve this. Let us know if you need any help! 😊
