### ISSUE TITLE
How to modify the current network and network configuration during script execution

### ISSUE THREAD

**Issue by lanlingxiawu** [NomicFoundation/hardhat#5783]
I need to deploy contracts on different networks and verify the source code in a script. How can I dynamically modify the current network and adjust the network configuration within the script?

**Comment by schaable** [comment]
Hi @lanlingxiawu! If you're looking to deploy the same contracts to different networks, you can simply pass the network name when running your script. For example:

```
npx hardhat run scripts/deploy-and-verify.ts --network goerli
npx hardhat run scripts/deploy-and-verify.ts --network mainnet
```

You can also use the network name within your script to conditionally execute specific logic for certain networks:

```
import { network } from "hardhat";

async function main() {
  const currentNetwork = network.name; // Get the current network
  
  // ...
  
  if (currentNetwork === "goerli") {
   // do something
  }
}
```

However, if what you're asking is about switching networks dynamically within the script, that's currently not possible in Hardhat 2. The good news is that this feature is planned for Hardhat 3, so stay tuned for updates! 🚀

Let me know if you have any other questions! 😊
