### ISSUE TITLE
Displaying inline task action warning

### ISSUE THREAD

**Issue by kanej** [NomicFoundation/hardhat#5896]
With a new Hardhat3 Alpha project, on compile you get inline task warnings:

```shell
> pnpm hardhat3 compile
WARNING: Inline task action found in plugin "builtin:solidity" for task "compile". Use file:// URLs in production.
Compiled 1 Solidity file with solc 0.8.24 (evm target: shanghai)
```

We should suppress those warnings for all the builtin tasks.

**Comment by ChristopherDedominici** [comment]
There are also warnings related to the contracts being compiled:

![image](https://github.com/user-attachments/assets/79e8347a-90b1-4b22-8e96-1cc7f8113c51)
