### ISSUE TITLE
error with etherscan verify "Invalid compiler version"

### ISSUE THREAD

**Issue by JeromeJULIEN** [NomicFoundation/hardhat#5930]
Hello,
i'm struggling with contract verification on etherscan using hardhat verify
The have difficulty to nderstand the issue has i used many time the same process to successfully verify other deployment in the same project.

Here my hardhat.config :
```
const config: HardhatUserConfig = {
  solidity: "0.8.20",
  networks: {
    sepolia: {
      url: `https://eth-sepolia.g.alchemy.com/v2/${process.env.ALCHEMY_API_KEY}`,
      accounts: [`${process.env.PRIVATE_KEY}`],
      chainId: 11155111,
    },
  },
  etherscan: {
    apiKey: process.env.ETHERSCAN_API_KEY,
  },
};```

And my project pragma :
 ```
 // SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;```

My dependency are up to date (hardhat and openzeppelin)

My project compile and deploy successfully. For example, one deployment [here](https://sepolia.etherscan.io/address/0x0356555dad353dd572522936c4ecc5d517e7e059)

When i'm trying to run 
```
npx hardhat verify --network sepolia 0x0356555Dad353dD572522936c4ecC5D517e7e059 --constructor-args ./ignition/modules/{my_args_file}.ts
```

i got this error : 
```Etherscan:
Invalid compiler version. See https://etherscan.io/vyperversions for list of supported solc versions
```
The link provide a 404 page.

As it worked fine several times before (last time was maybe 2 or 3 months ago), i guess maybe some change in the way to use the verification tool was done

**Comment by dglooo** [comment]
have same error via rest api etherscan contract verification on sepolia contract. Few days ago it was normal

**Comment by kanej** [comment]
I suspect this is an error on the etherscan side. Particularly as the error message quoted is referring to vyper, and `hardhat-verify` does not support vyper:

```
See https://etherscan.io/vyperversions for list of supported solc versions
```

@JeromeJULIEN can I confirm you are still seeing the issue when you attempt to verify?

**Comment by JeromeJULIEN** [comment]
hey @kanej ,
i guess it was an temporary issue on etherscan as i just tried one more time, and now it work...
So finger cross to keep it functionnal :)

**Comment by GitGuru7** [comment]
Hey there! I am trying to verify my contracts on unichainsepolia with this configuration
```
 unichainsepolia: {
      url: process.env.ARCHIVE_NODE_unichainsepolia || "https://sepolia.unichain.org",
      chainId: 1301,
      live: true,
      accounts: DEPLOYER_PRIVATE_KEY ? [`0x${DEPLOYER_PRIVATE_KEY}`] : [],
    },
    
     etherscan: {
    customChains: [
       {
        network: "unichainsepolia",
        chainId: 1301,
        urls: {
          apiURL: `https://api-sepolia.uniscan.xyz/api/`,
          browserURL: "https://sepolia.uniscan.xyz/",
        },
      },
    ],
    apiKey: {
      unichainsepolia: process.env.ETHERSCAN_API_KEY || "ETHERSCAN_API_KEY",
    },
```

But I am getting the same error, I have tried with both hardhat verify and hardhat etherscan .
I am getting this error message: `DEPRECATION WARNING: 'hardhat-etherscan' has been deprecated in favor of 'hardhat-verify'. You can find more information about the migration in the readme.
Error in plugin @nomiclabs/hardhat-etherscan: Invalid compiler version. See https://etherscan.io/vyperversions for list of supported Vyper versions

For more info run Hardhat with --show-stack-traces`

Can you please help me with it. It was fine before few days

**Comment by kanej** [comment]
> Hey there! I am trying to verify my contracts on unichainsepolia with this configuration
> 
> ```
>  unichainsepolia: {
>       url: process.env.ARCHIVE_NODE_unichainsepolia || "https://sepolia.unichain.org",
>       chainId: 1301,
>       live: true,
>       accounts: DEPLOYER_PRIVATE_KEY ? [`0x${DEPLOYER_PRIVATE_KEY}`] : [],
>     },
>     
>      etherscan: {
>     customChains: [
>        {
>         network: "unichainsepolia",
>         chainId: 1301,
>         urls: {
>           apiURL: `https://api-sepolia.uniscan.xyz/api/`,
>           browserURL: "https://sepolia.uniscan.xyz/",
>         },
>       },
>     ],
>     apiKey: {
>       unichainsepolia: process.env.ETHERSCAN_API_KEY || "ETHERSCAN_API_KEY",
>     },
> ```
> 
> But I am getting the same error, I have tried with both hardhat verify and hardhat etherscan . I am getting this error message: `DEPRECATION WARNING: 'hardhat-etherscan' has been deprecated in favor of 'hardhat-verify'. You can find more information about the migration in the readme. Error in plugin @nomiclabs/hardhat-etherscan: Invalid compiler version. See [etherscan.io/vyperversions](https://etherscan.io/vyperversions) for list of supported Vyper versions
> 
> For more info run Hardhat with --show-stack-traces`
> 
> Can you please help me with it. It was fine before few days

I suspect this is a temporary infrastructure issue, but I will check with the etherscan team.

**Comment by AndreaBarbon** [comment]
I have the same issue. Any news?

**Comment by x0good** [comment]
Also see Error today
> Invalid compiler version. See https://etherscan.io/vyperversions for list of supported Vyper versions
