### ISSUE TITLE
npx hardhat --network localhost faucet 0x9a7d6faD786E8c5CB2F8f7c935d2616301841c0A Error HH303: Unrecognized task 'faucet'  For more info go to https://hardhat.org/HH303 or run Hardhat with --show-stack-traces

### ISSUE THREAD

**Issue by phpmac** [NomicFoundation/hardhat#5941]
npx hardhat --network localhost faucet 0x9a7d6faD786E8c5CB2F8f7c935d2616301841c0A
Error HH303: Unrecognized task 'faucet'

For more info go to https://hardhat.org/HH303 or run Hardhat with --show-stack-traces

**Comment by iosh** [comment]
Hi This error occurs because faucet is not a built-in hardhat task; it is a custom task. You can see it here: https://github.com/NomicFoundation/hardhat-boilerplate/blob/master/tasks/faucet.js

**Comment by kanej** [comment]
Hardhat has not built-in task called `faucet`, are you expecting this task to come from a plugin?

**Comment by kanej** [comment]
I am going to close this. We can reopen if new information comes up.
