### ISSUE TITLE
I can't verify my contracts on base-sepolia using hardhat Please

### ISSUE THREAD

**Issue by yahiashihab** [NomicFoundation/hardhat#5944]
I've been trying for a couple of days, and I'm so tired. When I use the custom chain, there's an error, and I don't know why the Base Sepolia chain isn't verified Please need some help This is my hardhat-ignition I need to deploy it in base chain

require("@nomicfoundation/hardhat-toolbox");
// require("@nomiclabs/hardhat-etherscan");
require('dotenv').config();

const NETWORK_TESTNET_URL = process.env.NETWORK_TESTNET_URL;
const NETWORK_MAINNET_URL = process.env.NETWORK_MAINNET_URL;
const SEPOLIA_PRIVATE_KEY = process.env.SEPOLIA_PRIVATE_KEY;
const MAINNET_PRIVATE_KEY = process.env.MAINNET_PRIVATE_KEY;
const ETHERSCAN_API_KEY = process.env.ETHERSCAN_API_KEY;

module.exports = {
  solidity: {
    version: "0.8.24",
    settings: {
      optimizer: {
        enabled: true,
        runs: 200
      }
    }
  },
  networks: {
     sepolia: {
      url: NETWORK_TESTNET_URL,
      accounts: [SEPOLIA_PRIVATE_KEY]
    }
    // mainnet: {
    //   url: NETWORK_MAINNET_URL,
    //   accounts: [MAINNET_PRIVATE_KEY]
    // }
  },
  etherscan: {
    apiKey: ETHERSCAN_API_KEY
  }
};

it's showing 

Error in plugin hardhat-ignition: IGN1002: Verification not natively supported for chainId 84532. Please use a custom chain configuration to add support.

For more info run Hardhat with --show-stack-traces

**Comment by kanej** [comment]
Hey, Hardhat does not have built in support for Base Sepolia for verification. You need to give some more configuration information to let Hardhat verify know which service to use for verification.

The base docs have an example of such a configuration here to setup basescan: https://docs.base.org/tutorials/deploy-with-hardhat/#verifying-the-smart-contract

```ts
etherscan: {
   apiKey: {
    "base-sepolia": "PLACEHOLDER_STRING"
   },
   customChains: [
     {
       network: "base-sepolia",
       chainId: 84532,
       urls: {
        apiURL: "https://api-sepolia.basescan.org/api",
        browserURL: "https://sepolia.basescan.org"
       }
     }
   ]
 },
```

**Comment by yahiashihab** [comment]
Thank you So much Bro kanej When I add your details There's an error The last comma   },    

Greetings

**Comment by yahiashihab** [comment]
Thank you kane I will try it have a nice day
