### ISSUE TITLE
Invalid value undefined supplied to : RpcBlockWithTransactions | null/totalDifficulty: QUANTITY

### ISSUE THREAD

**Issue by 0xmichalis** [NomicFoundation/hardhat#5986]
### Version of Hardhat

2.19.5

### What happened?

Forking a Base Sepolia node has started failing with the following error:
```
Errors: Invalid value undefined supplied to : RpcBlockWithTransactions | null/totalDifficulty: QUANTITY
```

### Minimal reproduction steps

```
git clone https://github.com/0xmichalis/hardhat-5986-repro
cd hardhat-5986-repro
npm i
npx hardhat test
```

**Comment by 0xmichalis** [comment]
Seems to work fine with the latest Hardhat version (`2.22.16`)

**Comment by 0xmichalis** [comment]
This has started happening since today. It'd be great to understand whether there is a workaround we can apply without changing versions as it's hard to do that at the moment (upgrading breaks our tests for some reason).

**Comment by aspiers** [comment]
Wild guess this is the same as #5816 which was fixed in v2.22.14.

**Comment by aspiers** [comment]
See also #2106 and #2313 although those are much older and no longer valid.

**Comment by aspiers** [comment]
Looks like OpenZeppelin Defender just got bitten with the same issue :laughing: 

![image](https://github.com/user-attachments/assets/9e6cc1c9-144d-4628-85d7-38882c2b53f7)

**Comment by kanej** [comment]
The upcoming `2.22.17` release makes the `totalDifficulty` field optional.
I suspect, however, there is not a work around for the removal of `totalDifficulty` from the API without changing version.
The versions of Hardhat after `2.19` uses EDR for the underlying Hardhat node (a rewrite of Hardhat node in Rust). If you are running into bugs after upgrading could you post them as issues here to help us diagnose any problems EDR has introduced?

**Comment by nebasuke** [comment]
EDR depends on the `RpcBlockWithTransactions` from hardhat-core definitions, so updating Hardhat to the upcoming `2.22.17` would be the way to go. Do let us know if there unexpected downstream consequences on the EDR level though!

**Comment by schaable** [comment]
Hardhat 2.22.17 has been released and includes a fix for this issue. You can see the release notes [here](https://github.com/NomicFoundation/hardhat/releases/tag/hardhat%402.22.17).
