### ISSUE TITLE
Can't fork BSC network in latest versions

### ISSUE THREAD

**Issue by gilsapir86** [NomicFoundation/hardhat#6049]
### Version of Hardhat

^2.22.17

### What happened?

When just running a simple test that reads simple data (i.e. executing "getReserves()" on some random pair)
I get:
ProviderError: No known hardfork for execution on historical block 44805643 (relative to fork block number 44805643). The node was not configured with a hardfork activation history.

The issue is "solved" when downgrading to hardhat@2.19.4

### Minimal reproduction steps

Create a simple test, that's using hardhat.provider
the network should be BSC, RPC can be: https://bsc-rpc.publicnode.com
choose some pair, and call "getReserves"

**Comment by galargh** [comment]
Hi! Could you share your network configuration and the test in question with us?

**Comment by galargh** [comment]
I'm going to close it now due to inactivity.
