### ISSUE TITLE
Feature Request:  `buidler node` option to not log private key in the console

### ISSUE THREAD

**Issue by wighawag** [NomicFoundation/hardhat#622]
Currently when executing `buidler node` the set of account private key is outputed in the console. It would be great to have an option to not show them

On that note, if https://github.com/nomiclabs/buidler/issues/621 is implemented, `buidler node` should not show the private key by default as this could be sensitive enough.

**Comment by alcuadrado** [comment]
I think showing those PKs was a mistake. Users may copy them and accidentally use them in mainnet. For example, by importing them into MM.

We will remove them from the output for sure.

**Comment by fvictorio** [comment]
@alcuadrado is this still something we want to do?

**Comment by fvictorio** [comment]
I think we already have an improvement related to this, where we only show the private keys for the default mnemonic. I'm going to assume this is enough.
