### ISSUE TITLE
Add support for multiple `sources`

### ISSUE THREAD

**Issue by rhlsthrm** [NomicFoundation/hardhat#635]
In our workflow, we are importing contract packages as NPM packages. It would be nice to be able to include the NPM contract `.sol` files as sources so that we can build them and run them in tests. Right now we have to copy-paste what we are using into the `sources` directory.

**Comment by alcuadrado** [comment]
Nice idea, @rhlsthrm. We are going to change how things are compiled. You can check #553 to learn more. This may be a good fit for that.

An easier workaround is to just add a `.sol` file that imports the ones you want to compile. This way you don't need to copy&paste everything.

**Comment by rhlsthrm** [comment]
Thanks for the workaround! Will use that until then.

**Comment by fvictorio** [comment]
Closing in favor of https://github.com/NomicFoundation/hardhat/issues/776
