### ISSUE TITLE
[buidler-web3] Support for 'subscribe'.

### ISSUE THREAD

**Issue by dsystems-io** [NomicFoundation/hardhat#679]
**buidler 1.3.8**
**buidler-web3 1.3.4**

When attempting to test with buidler-web3 within our react app, all of the subscribe functions throw:

`Error: The current provider doesn't support subscriptions: Web3HTTPProviderAdapter`

Using the subscribe feature in many places and would love to be able to test these portions with buidler.

**Comment by fvictorio** [comment]
Hi, I'm closing old issues that are unlikely to still be valid. Please let us know if that's not the case.
