### ISSUE TITLE
Improve colors when printing compiler errors

### ISSUE THREAD

**Issue by frangio** [NomicFoundation/hardhat#680]
Solidity errors and warnings are currently printed in full red or yellow color. While some color is nice, printing the entire text in a single color isn't comfortable to read.

I'd say only the error category (`Warning`, `ParserError`, ...) should be printed in the corresponding yellow or red color.

It could also be nice to experiment with further formatting of other things like the source code location, the error description itself, or the `^----^` marker that points at the error location, using bold, dimming, or more colors.

**Comment by alcuadrado** [comment]
Thanks for opening this issue, @frangio 

We are currently redoing our compilation pipeline, so it's a great time to implement changes to how errors are displayed. This is being tracked in #553, where printing colorful errors pointing to the exact place were they happened was also suggested.

**Comment by frangio** [comment]
I want to raise this again. :slightly_smiling_face: Given the general verbosity of Solidity error messages it would be very helpful for users if the output colors were improved.

**Comment by cameel** [comment]
We're considering adding a version of these messages with ANSI escapes to Standard JSON output (https://github.com/ethereum/solidity/issues/11507). Would that be usable for Hardhat?

**Comment by alcuadrado** [comment]
Really cool, @cameel !

**Comment by axic** [comment]
Is hardhat output used in any other context than a terminal? Such as in browsers?

**Comment by fvictorio** [comment]
> Is hardhat output used in any other context than a terminal? Such as in browsers?

No. Right now it's not possible to use Hardhat in a browser, so no. And I can't think about any other context where it could be used.

**Comment by axic** [comment]
I assume hardhat also uses the `formattedMessage` of the error list from Solidity? So then if there's an option to make it have colours, it would have ANSI escapes for it. There are some libraries which can be used to transform ANSI escapes into HTML spans, hence you'd need that if hardhat would be used in the browser.

However if you already craft the error messages yourself, by using `message` and the other fields, then you can already colour it.

**Comment by axic** [comment]
Here's a concrete proposal, happy to hear your opinions: https://github.com/ethereum/solidity/issues/11507#issuecomment-919556059
