### ISSUE TITLE
buidler-ganache should work well together with buidler-deployer

### ISSUE THREAD

**Issue by vporton** [NomicFoundation/hardhat#688]
Add a hook to be called from `buidler deploy`, to make use it in `buidler-deployer` and after adding the hook report bug there.

**Comment by fvictorio** [comment]
Hey @vporton, `buidler deploy` is developed in a different repo, I think you should open the issue there: https://github.com/wighawag/buidler-deploy

**Comment by vporton** [comment]
@fvictorio But we need a hook in `buidler-ganache` to make it possible in `buidler-deploy`.

**Comment by fvictorio** [comment]
Oh, I see, that makes sense :+1:
