### ISSUE TITLE
Ganache and BuilderEVM use different gas

### ISSUE THREAD

**Issue by vporton** [NomicFoundation/hardhat#782]
Ganache CLI v6.10.2 (ganache-core: 2.11.3) and Buidler EVM (1.4.4) produce different `gasUsed` for a contract call running under a controlled test environment where not if...else branch should behave differently.

It uses https://github.com/vporton/ubi-russia/commit/d303600d30b2847313fed068c9d31a0aa3b61870 for testing.

```
npx ganache-cli -d
```

```
$ npx buidler run scripts/estimate-gas.js --network ganache
All contracts have already been compiled, skipping compilation.
144378
78703
max gas for single account: 144378
227988
111638
max gas for 2 accounts: 227988
ethereum,0$ npx buidler run scripts/estimate-gas.js 
All contracts have already been compiled, skipping compilation.
144378
78703
max gas for single account: 144378
227976
111626
max gas for 2 accounts: 227976
```

**Comment by vporton** [comment]
Rinkeby produced the same results as Ganache. So, it is apparently is a Buidler bug.

**Comment by alcuadrado** [comment]
Thanks for reporting this, @vporton

**Comment by alcuadrado** [comment]
Hi,

I'm closing this issue as it has been a long time without activity, and it's unlikely it's still relevant/present.

Thanks for reporting it anyway, and please open a new one if you think it's needed.
