### ISSUE TITLE
[feature request] Better Assertion Error objects.

### ISSUE THREAD

**Issue by SilentCicero** [NomicFoundation/hardhat#788]
## Motivation
I have come across a few scenarios where I can't get the raw revert data I need to test my contracts.

Revert, in accordance with EVM standard, has no formal return specification, i.e. it's not always strings from Solidity.

It would be nice if Buidler handled non-standard reverts.

## Solution
When testing add the ability for it to throw with a rich error, including revert codes, transaction hashes etc.

Currently the Error is weak, with a simple message and no further data about the revert. The console only shows some data but it is unreachable in code terms.

Here we add `revert` and `transactionHash` properties. As well this allows me to wrap these calls with different `expect` handlers and deal with my non-standard reverts easily.

```js
try {
   await erc20.transfer(ethers.constants.emptyAddress, 500);
} catch (error) {
   console.log(error.revert.code);
   console.log(error.transactionHash);
}
```

**Comment by fvictorio** [comment]
This seems like a good idea. @alcuadrado is this doable?

**Comment by alcuadrado** [comment]
Yes, this is a great idea, and should be doable for Buidler EVM.

**Comment by alcuadrado** [comment]
Hi,

I'm closing this issue as it has been a long time without activity, and it's unlikely it's still relevant/present.

Thanks for reporting it anyway, and please open a new one if you think it's needed. I believe this has been addressed.
