### ISSUE TITLE
Can't run tasks from parent repo using npm explore

### ISSUE THREAD

**Issue by lmcorbalan** [NomicFoundation/hardhat#928]
`A` is the repo where I developed my contracts using `buidler`, it also uses `buidler-deploy` plugin so when the contracts are deployed it saves the artefacts into `deployments` folder.

`B` is a repo that includes `A` as dependency where I'm trying to use [npm explore](https://preview-docs.npmjs.com/cli-commands/npm-explore) to run a deployment task in `A` which throws the error **`Error BDLR402: File SOME-PATH/buidler-issue-rep/node_modules/buidler-issue-contracts/contracts/Greeter.sol belongs to a library but was treated as a local one.`**

This can be reproduced with this repo: https://github.com/lmcorbalan/buidler-issue-rep

**Comment by alcuadrado** [comment]
Thanks for taking the time to prepare the reproduction repository, @lmcorbalan!

We'll take a look at this soon.
