### ISSUE TITLE
Allow the test command to be run multiple times in the same process

### ISSUE THREAD

**Issue by xanderdeseyn** [NomicFoundation/hardhat#980]
Due to how Mocha works internally, `hardhat test` can only be run once in the same process. Truffle ran into the same issue and fixed it relatively easily: https://github.com/robcoder26/truffle/commit/c647c99ddf5a73273019cedb89e80526663f9bac

**Comment by alcuadrado** [comment]
Thanks for digging deeper into this. I'm not convinced that truffle's solution is complete, but we have experienced similar things and I'm confident we can make it work.

I don't think we can push a fix for this week, but will probably the next one.

**Comment by alcuadrado** [comment]
Hi,

I'm closing this issue as it has been a long time without activity, and it's unlikely it's still relevant/present.

Thanks for reporting it anyway, and please open a new one if you think it's needed.
