### ISSUE TITLE
feature request: network config for doing hardhat_reset between test files

### ISSUE THREAD

**Issue by gitpusha** [NomicFoundation/hardhat#992]
Hi, 

I think it would be cool if `hardhat` network could have a config to [hardhat_reset](https://hardhat.org/guides/mainnet-forking.html#resetting-the-fork) automatically between test files or maybe even `describe` function blocks. 

I guess similar to what Truffle does with their "clean room environment"  and [contract](https://www.trufflesuite.com/docs/truffle/testing/writing-tests-in-javascript#use-contract-instead-of-describe-) function.

**Comment by fvictorio** [comment]
This seems like a good idea for a plugin, since it seems easy to do in user-land and it's kind of opinionated, what do you think?

**Comment by fvictorio** [comment]
Oh, for the `describe` part you would indeed need some support from core. I think at some point we are going to revisit how mocha is used, so it might be a good idea to keep this in mind when we do.

**Comment by gitpusha** [comment]
sounds good! to be honest, I am fine with invoking `hardhat_reset` manually in each file where I want it. It has its own merits too being that explicit.  

Actually I am using `deployments.fixture()` from `hardhat-deploy` everywhere at the moment and that is incompatible with `hardhat_reset` anyway at the moment still. 


See https://github.com/nomiclabs/hardhat/issues/991

**Comment by fvictorio** [comment]
I think I'm going to close this. This is doable with mocha's hooks and that feels good enough. Maybe this is worth re-visiting after #2455, but that's not something we are going to do soon, so this issue is not very actionable. Sorry @gitpusha :(
